-- Attempt to match signer by email/fingerprint or create new signer record. @31 @24 @52
CREATE OR REPLACE PROCEDURE DOCGEN.MATCH_OR_CREATE_SIGNER(email STRING, request_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNERS t USING (SELECT :email AS EMAIL) s ON t.SIGNER_EMAIL = LOWER(s.EMAIL)
WHEN NOT MATCHED THEN INSERT (SIGNER_ID, REQUEST_ID, ACCOUNT_ID, SIGNER_EMAIL, CREATED_AT) VALUES (UUID_STRING(), :request_id, :account_id, LOWER(s.EMAIL), CURRENT_TIMESTAMP());
$$;

