-- Register a device fingerprint for a signer. @31 @24 @52
CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNER_DEVICE(signer_id STRING, device_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SIGNER_DEVICE_REGISTRY (DEVICE_ID, SIGNER_ID, DEVICE_META) VALUES (UUID_STRING(), :signer_id, :device_meta); $$;

