-- Create an escalation record for operator review. @31 @24 @52
CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ESCALATION(request_id STRING, reason STRING, assigned_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SIGNATURE_ESCALATIONS (ESCALATION_ID, REQUEST_ID, REASON, ASSIGNED_TO, STATUS) VALUES (UUID_STRING(), :request_id, :reason, :assigned_to, 'OPEN'); $$;

