-- Activate a template version and mark prior versions inactive. @31 @24 @52
CREATE OR REPLACE PROCEDURE DOCGEN.ACTIVATE_TEMPLATE_VERSION(version_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ UPDATE DOCGEN.SIGNATURE_TEMPLATE_VERSIONS SET IS_ACTIVE = FALSE WHERE TEMPLATE_ID = (SELECT TEMPLATE_ID FROM DOCGEN.SIGNATURE_TEMPLATE_VERSIONS WHERE VERSION_ID = :version_id); UPDATE DOCGEN.SIGNATURE_TEMPLATE_VERSIONS SET IS_ACTIVE = TRUE WHERE VERSION_ID = :version_id; $$;

