-- Schedule a batch export job entry. @31 @24 @52
CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_BATCH_EXPORT(export_type STRING, cron_expr STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SIGNATURE_BATCH_EXPORTS (EXPORT_ID, EXPORT_TYPE, STATUS, SCHEDULE) VALUES (UUID_STRING(), :export_type, 'ENABLED', :cron_expr); $$;

