-- Rotate show-once integration key hash entries and mark prior keys as rotated per key lifecycle guidance. @1 @31
CREATE OR REPLACE PROCEDURE DOCGEN.ROTATE_INTEGRATION_KEY(account_id STRING, new_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.ACCOUNTS_INTEGRATION_KEYS SET ROTATED_AT = CURRENT_TIMESTAMP() WHERE ACCOUNT_ID = :account_id;
INSERT INTO DOCGEN.ACCOUNTS_INTEGRATION_KEYS (ACCOUNT_ID, INTEGRATION_KEY_HASH, CREATED_AT) VALUES (:account_id, :new_hash, CURRENT_TIMESTAMP());
$$;

