-- Cleanup test fixtures to reset CI state between runs. @1 @31
CREATE OR REPLACE PROCEDURE DOCGEN.RESET_TEST_FIXTURES()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DELETE FROM DOCGEN.SIGNATURE_REQUESTS WHERE REQUEST_ID = 'req-0001';
$$;

