-- Update device trust score using signal aggregation pipelines. @1 @31
CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_TRUST_SCORE(device_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_TRUST_SCORES tgt USING (SELECT :device_id AS d, :score AS s) src ON tgt.DEVICE_ID = src.d WHEN MATCHED THEN UPDATE SET TRUST_SCORE = src.s, LAST_UPDATED = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DEVICE_ID, TRUST_SCORE) VALUES (src.d, src.s);
$$;

