CREATE OR REPLACE PROCEDURE DOCGEN.NEXT_ID(seq_name STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SEQ_IDS t USING (SELECT :seq_name AS s) src ON t.SEQ_NAME = src.s
WHEN MATCHED THEN UPDATE SET LAST_VAL = LAST_VAL + 1
WHEN NOT MATCHED THEN INSERT (SEQ_NAME, LAST_VAL) VALUES (src.s, 1);
SELECT TO_VARCHAR((SELECT LAST_VAL FROM DOCGEN.SEQ_IDS WHERE SEQ_NAME = :seq_name));
$$;

