-- Upsert with activation audit logging to mirror Admin Console activation patterns @1 @6.
CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_EVENT_WITH_AUDIT(payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.SIGNATURE_EVENTS tgt USING (SELECT :payload AS p) src ON tgt.EVENT_ID = src.p:EVENT_ID::STRING WHEN MATCHED THEN UPDATE SET EVENT_PAYLOAD = src.p, EVENT_TS = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (EVENT_ID, REQUEST_ID, DOCUMENT_ID, SIGNER_ID, ACCOUNT_ID, EVENT_TYPE, EVENT_PAYLOAD) VALUES (src.p:EVENT_ID::STRING, src.p:REQUEST_ID::STRING, src.p:DOCUMENT_ID::STRING, src.p:SIGNER_ID::STRING, src.p:ACCOUNT_ID::STRING, src.p:EVENT_TYPE::STRING, src.p); INSERT INTO DOCGEN.SIGNATURE_AUDIT_LOG (AUDIT_ID, ACCOUNT_ID, USER_ID, ACTION, META) VALUES (UUID_STRING(), src.p:ACCOUNT_ID::STRING, 'system', 'INGEST_EVENT', src.p); RETURN OBJECT_CONSTRUCT('status','ok'); $$;

