CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_SIGNER( request_id STRING, signer_email STRING, signer_name STRING, signer_method STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNERS (SIGNER_ID, REQUEST_ID, ACCOUNT_ID, SIGNER_EMAIL, SIGNER_NAME, SIGNER_METHOD, CREATED_AT)
VALUES (UUID_STRING(), :request_id, (SELECT ACCOUNT_ID FROM DOCGEN.SIGNATURE_REQUESTS WHERE REQUEST_ID=:request_id), :signer_email, :signer_name, :signer_method, CURRENT_TIMESTAMP());
$$;

