CREATE OR REPLACE PROCEDURE DOCGEN.MARK_EVENT_HANDLED(event_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.SIGNATURE_EVENTS SET EVENT_PAYLOAD = OBJECT_INSERT_IFNULL(EVENT_PAYLOAD,'handled',TRUE) WHERE EVENT_ID = :event_id;
$$;

