CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INTEGRATION_AUDIT(provider STRING, action STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SIGNATURE_INTEGRATIONS_AUDIT (AUDIT_ID, PROVIDER, ACTION, PAYLOAD) VALUES (UUID_STRING(), :provider, :action, :payload); $$;

