CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_ROLLING_METRICS(window_minutes INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_METRICS_ROLLING (METRIC_ID, WINDOW_START, WINDOW_END, ACCOUNT_ID, SIGNATURE_COUNT)
SELECT UUID_STRING(), DATEADD(minute, -:window_minutes, CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP(), ACCOUNT_ID, COUNT(*) FROM DOCGEN.SIGNATURE_EVENTS WHERE EVENT_TYPE='SIGNED' GROUP BY ACCOUNT_ID;
$$;

