CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SESSION_TOKEN(session_id STRING, ttl_minutes INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SIGNER_SESSION_TOKENS (TOKEN_ID, SESSION_ID, EXPIRES_AT) VALUES (UUID_STRING(), :session_id, DATEADD(minute, :ttl_minutes, CURRENT_TIMESTAMP())); $$;

