-- Update non-secret operational settings used by procedures and tasks @1 @6.
CREATE OR REPLACE PROCEDURE DOCGEN.SET_SETTING(key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.SIGNATURE_SETTINGS tgt USING (SELECT :key AS k, :value AS v) src ON tgt.SETTING_KEY = src.k WHEN MATCHED THEN UPDATE SET SETTING_VALUE = src.v, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE) VALUES (src.k, src.v); $$;

