CREATE OR REPLACE PROCEDURE DOCGEN.GET_RETRY_POLICY(provider STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ SELECT POLICY_ID, MAX_ATTEMPTS, INITIAL_DELAY_SECONDS, BACKOFF_MULTIPLIER FROM DOCGEN.WEBHOOK_RETRY_POLICY WHERE PROVIDER = :provider; $$;

