CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULER_KV_UPSERT(k STRING, v VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.SCHEDULER_KV t USING (SELECT :k AS k, :v AS v) s ON t.KEY = s.k WHEN MATCHED THEN UPDATE SET VALUE = s.v, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (KEY, VALUE) VALUES (s.k, s.v); $$;

