-- Record a provider credential/config change for audit. CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_CRED_CHANGE(provider_id STRING, changed_by STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.PROVIDER_CREDENTIALS_AUDIT (AUDIT_ID, PROVIDER_ID, CHANGED_BY, CHANGE_PAYLOAD) VALUES (UUID_STRING(), :provider_id, :changed_by, :payload); $$;

