CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_WORKER_LEASE(worker_name STRING, ttl_seconds INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
-- naive lease acquisition for distributed workers
MERGE INTO DOCGEN.WORKER_LEASES t USING (SELECT :worker_name AS wn) s ON t.WORKER_NAME = s.wn
WHEN MATCHED AND t.LEASE_EXPIRES_AT < CURRENT_TIMESTAMP() THEN UPDATE SET LEASE_EXPIRES_AT = DATEADD(second,:ttl_seconds,CURRENT_TIMESTAMP()), HEARTBEAT_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (LEASE_ID, WORKER_NAME, LEASE_EXPIRES_AT, HEARTBEAT_AT) VALUES (UUID_STRING(), :worker_name, DATEADD(second,:ttl_seconds,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP());
$$;

