-- Return current on-call operators for escalation workflows. CREATE OR REPLACE PROCEDURE DOCGEN.GET_ONCALL_OPERATORS()
RETURNS VARIANT
LANGUAGE SQL
AS
$$ SELECT ARRAY_AGG(OBJECT_CONSTRUCT('operator_id', OPERATOR_ID, 'contact', CONTACT)) FROM DOCGEN.OPERATORS WHERE ON_CALL = TRUE; $$;

