CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PERMISSION_AUDIT(principal STRING, object_name STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.PERMISSIONS_AUDIT (AUDIT_ID, PRINCIPAL, OBJECT_NAME, ACTION) VALUES (UUID_STRING(), :principal, :object_name, :action); $$;

