CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_SECURITY_EVENT(severity STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.SECURITY_EVENTS (EVENT_ID, SEVERITY, DETAILS) VALUES (UUID_STRING(), :severity, :details); $$;

