CREATE OR REPLACE PROCEDURE DOCGEN.VALIDATE_API_KEY(api_key_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ SELECT OBJECT_CONSTRUCT('valid', CASE WHEN EXISTS(SELECT 1 FROM DOCGEN.API_KEYS WHERE API_KEY_HASH = :api_key_hash AND ENABLED=TRUE) THEN TRUE ELSE FALSE END) ;
$$;

