CREATE OR REPLACE PROCEDURE DOCGEN.ADD_OPERATIONAL_ANNOTATION(entity_ref STRING, text STRING, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.OPERATIONAL_ANNOTATIONS (ANNOTATION_ID, ENTITY_REF, ANNOTATION_TEXT, CREATED_BY) VALUES (UUID_STRING(), :entity_ref, :text, :created_by); $$;

