-- Update provider heartbeat entry when a scheduled ping completes. CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_HEARTBEAT(provider_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.PROVIDER_HEARTBEAT tgt USING (SELECT :provider_id AS pid, :status AS st, :details AS d) src ON tgt.PROVIDER_ID = src.pid WHEN MATCHED THEN UPDATE SET LAST_HEARTBEAT = CURRENT_TIMESTAMP(), STATUS = src.st, DETAILS = src.d WHEN NOT MATCHED THEN INSERT (PROVIDER_ID, LAST_HEARTBEAT, STATUS, DETAILS) VALUES (src.pid, CURRENT_TIMESTAMP(), src.st, src.d); $$;

