CREATE OR REPLACE PROCEDURE DOCGEN.RUN_DEMO_SMOKE()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
CALL DOCGEN.UPSERT_SIGNATURE_WEBHOOK(PARSE_JSON('{"EVENT_ID":"smk-1","REQUEST_ID":"req-0001","DOCUMENT_ID":"doc-0001","SIGNER_ID":"signer-1","ACCOUNT_ID":"acct-1","EVENT_TYPE":"SIGNED"}'));
CALL DOCGEN.PREVIEW_BILLING('acct-1', CURRENT_TIMESTAMP());
$$;

