CREATE OR REPLACE PROCEDURE DOCGEN.SET_SLA_TARGET(metric_name STRING, threshold VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.SLA_TARGETS t USING (SELECT :metric_name AS m, :threshold AS th) s ON t.METRIC_NAME = s.m WHEN MATCHED THEN UPDATE SET THRESHOLD = s.th WHEN NOT MATCHED THEN INSERT (TARGET_ID, METRIC_NAME, THRESHOLD) VALUES (UUID_STRING(), s.m, s.th); $$;

