CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_DOCUMENT_CONTENT(doc_id STRING, snippet STRING, embedding VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.DOCUMENT_CONTENT_INDEX t USING (SELECT :doc_id AS d, :snippet AS s, :embedding AS e) src ON t.DOC_ID = src.d WHEN MATCHED THEN UPDATE SET SNIPPET = src.s, EMBEDDING = src.e, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DOC_ID, SNIPPET, EMBEDDING) VALUES (src.d, src.s, src.e);
$$;

