CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_EVENT(admin_user STRING, action STRING, target STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.ADMIN_EVENTS (EVENT_ID, ADMIN_USER, ACTION, TARGET, DETAILS) VALUES (UUID_STRING(), :admin_user, :action, :target, :details); $$;

