CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MAINTENANCE(operation STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.MAINTENANCE_LOG (LOG_ID, OPERATION, STATUS, DETAILS, STARTED_AT) VALUES (UUID_STRING(), :operation, :status, :details, CURRENT_TIMESTAMP()); $$;

