CREATE OR REPLACE PROCEDURE DOCGEN.MARK_NOTIFICATION_SENT(notif_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ UPDATE DOCGEN.SIGNATURE_NOTIFICATIONS SET STATUS='SENT', ATTEMPT_COUNT = ATTEMPT_COUNT + 1, LAST_ATTEMPT_AT = CURRENT_TIMESTAMP() WHERE NOTIF_ID = :notif_id; $$;

