CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PREVIEW(request_id STRING, user_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ INSERT INTO DOCGEN.DOC_PREVIEW_TRACK (PREVIEW_ID, REQUEST_ID, USER_ID) VALUES (UUID_STRING(), :request_id, :user_id); $$;

