CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_QUICK_SEARCH(key STRING, ref VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ MERGE INTO DOCGEN.QUICK_SEARCH_INDEX t USING (SELECT :key AS k, :ref AS r) s ON t.KEY = s.k WHEN MATCHED THEN UPDATE SET REF = s.r, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (KEY, REF) VALUES (s.k, s.r); $$;

