CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_EVENT_ATTRIBUTE(event_id STRING, key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_EVENT_ATTRIBUTES t USING (SELECT :event_id AS eid, :key AS k, :value AS v) s ON t.EVENT_ID = s.eid AND t.ATTR_KEY = s.k
WHEN MATCHED THEN UPDATE SET ATTR_VALUE = s.v
WHEN NOT MATCHED THEN INSERT (ATTR_ID, EVENT_ID, ATTR_KEY, ATTR_VALUE) VALUES (UUID_STRING(), s.eid, s.k, s.v);
$$;

