CREATE OR REPLACE PROCEDURE DOCGEN.STORE_ATTACHMENT_REFERENCE(request_id STRING, filename STRING, file_url STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_ATTACHMENTS (ATTACH_ID, REQUEST_ID, FILENAME, FILE_URL, META) VALUES (UUID_STRING(), :request_id, :filename, :file_url, :meta);
$$;

