CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_NOTARY(name STRING, license_info VARIANT, issued_at TIMESTAMP_LTZ, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_REGISTRY (NOTARY_ID, NAME, LICENSE_INFO, ISSUED_AT, EXPIRES_AT) VALUES (UUID_STRING(), :name, :license_info, :issued_at, :expires_at);
$$;

