CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTARY_ACTION(notary_id STRING, request_id STRING, action_string STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_ACTIONS (ACTION_ID, NOTARY_ID, REQUEST_ID, ACTION_STRING) VALUES (UUID_STRING(), :notary_id, :request_id, :action_string);
$$;

