CREATE OR REPLACE PROCEDURE DOCGEN.GET_LOCALIZATION_POLICY(jurisdiction STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT OBJECT_AGG(POLICY_ID, PARSE_JSON(OBJECT_CONSTRUCT(*))) FROM DOCGEN.LOCALIZATION_POLICIES WHERE JURISDICTION = :jurisdiction;
$$;

