CREATE OR REPLACE PROCEDURE DOCGEN.GET_TERMS(jurisdiction STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT * FROM DOCGEN.TERMS_AND_CONDITIONS_VERSIONS WHERE JURISDICTION = :jurisdiction ORDER BY VERSION_NUMBER DESC LIMIT 1;
$$;

