CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PHONE_ATTEMPT(signer_id STRING, success BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PHONE_VERIF_ATTEMPTS (ATTEMPT_ID, SIGNER_ID, SUCCESS) VALUES (UUID_STRING(), :signer_id, :success);
$$;

