CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_REMINDER(request_id STRING, scheduled_at TIMESTAMP_LTZ, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SCHEDULED_REMINDERS (REMINDER_ID, REQUEST_ID, SCHEDULED_AT, CHANNEL) VALUES (UUID_STRING(), :request_id, :scheduled_at, :channel);
$$;

