CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PROVIDER_CRED_REF(provider_id STRING, cred_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CREDENTIALS (CRED_ID, PROVIDER_ID, CRED_META) VALUES (UUID_STRING(), :provider_id, :cred_meta);
$$;

