CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SIGNATURE_MODEL(model_name STRING, version STRING, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_MODEL_REGISTRY (MODEL_ID, MODEL_NAME, VERSION, METADATA) VALUES (UUID_STRING(), :model_name, :version, :metadata);
$$;

