CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_METRIC(model_id STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_MODEL_METRICS (METRIC_ID, MODEL_ID, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :model_id, :metric_name, :metric_value);
$$;

