CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_MODEL_ALERT(model_id STRING, alert_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_MODEL_ALERTS (ALERT_ID, MODEL_ID, ALERT_TYPE, DETAILS) VALUES (UUID_STRING(), :model_id, :alert_type, :details);
$$;

