CREATE OR REPLACE PROCEDURE DOCGEN.GET_FASTPATH_CACHE(cache_key STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT PAYLOAD FROM DOCGEN.FASTPATH_CACHE WHERE CACHE_KEY = :cache_key AND EXPIRES_AT > CURRENT_TIMESTAMP();
$$;

