CREATE OR REPLACE PROCEDURE DOCGEN.PUT_FASTPATH_CACHE(cache_key STRING, payload VARIANT, ttl_minutes INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.FASTPATH_CACHE t USING (SELECT :cache_key AS k, :payload AS p) s ON t.CACHE_KEY = s.k
WHEN MATCHED THEN UPDATE SET PAYLOAD = s.p, EXPIRES_AT = DATEADD(minute, :ttl_minutes, CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (CACHE_KEY, PAYLOAD, EXPIRES_AT) VALUES (s.k, s.p, DATEADD(minute, :ttl_minutes, CURRENT_TIMESTAMP()));
$$;

