CREATE OR REPLACE PROCEDURE DOCGEN.GET_CONSENT_TEMPLATE(jurisdiction STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$ SELECT * FROM DOCGEN.CONSENT_TEMPLATES WHERE JURISDICTION = :jurisdiction ORDER BY CREATED_AT DESC LIMIT 1; $$;

