CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_ENFORCEMENT(policy_id STRING, request_id STRING, outcome STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_ENFORCEMENT_EVENTS (EVENT_ID, POLICY_ID, REQUEST_ID, OUTCOME, DETAILS) VALUES (UUID_STRING(), :policy_id, :request_id, :outcome, :details);
$$;

