CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_BILLING_EVENT(provider_id STRING, amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_BILLING_EVENTS (EVENT_ID, PROVIDER_ID, AMOUNT) VALUES (UUID_STRING(), :provider_id, :amount);
$$;

