CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_CHANGE_REQUEST(request_id STRING, requested_by STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_CHANGE_REQUESTS (CHANGE_ID, REQUEST_ID, REQUESTED_BY, CHANGE_PAYLOAD, STATUS) VALUES (UUID_STRING(), :request_id, :requested_by, :payload, 'OPEN');
$$;

