CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNER_ALIAS(signer_id STRING, alias_type STRING, alias_value STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_IDENTITY_ALIASES t USING (SELECT :signer_id AS s, :alias_type AS at, :alias_value AS av) src ON t.SIGNER_ID = src.s AND t.ALIAS_TYPE = src.at AND t.ALIAS_VALUE = src.av WHEN NOT MATCHED THEN INSERT (ALIAS_ID, SIGNER_ID, ALIAS_TYPE, ALIAS_VALUE) VALUES (UUID_STRING(), src.s, src.at, src.av);
$$;

