CREATE OR REPLACE PROCEDURE DOCGEN.PARSE_AND_UPSERT_EVENT(raw_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_EVENTS_PARSED tgt
USING (SELECT RAW_PAYLOAD FROM DOCGEN.SIGNATURE_EVENTS_RAW WHERE RAW_ID = :raw_id) src
ON tgt.RAW_ID = :raw_id
WHEN NOT MATCHED THEN
INSERT (EVENT_ID, RAW_ID, REQUEST_ID, DOCUMENT_ID, SIGNER_ID, ACCOUNT_ID, EVENT_TYPE, EVENT_TS, PAYLOAD)
VALUES (UUID_STRING(), :raw_id, src.RAW_PAYLOAD:request_id::STRING, src.RAW_PAYLOAD:document_id::STRING, src.RAW_PAYLOAD:signer_id::STRING, src.RAW_PAYLOAD:account_id::STRING, src.RAW_PAYLOAD:event_type::STRING, CURRENT_TIMESTAMP(), src.RAW_PAYLOAD);
$$;

