CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_VERIFICATION(bundle_id STRING, request_id STRING, signer_id STRING, result STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_VERIFICATIONS (VERIF_ID, BUNDLE_ID, REQUEST_ID, SIGNER_ID, RESULT, DETAILS) VALUES (UUID_STRING(), :bundle_id, :request_id, :signer_id, :result, :details);
$$;

