CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_HASH(signer_id STRING, hash VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_HASHES (BH_ID, SIGNER_ID, HASH) VALUES (UUID_STRING(), :signer_id, :hash);
$$;

