CREATE OR REPLACE PROCEDURE DOCGEN.APPEND_AUDIT(entity_type STRING, entity_id STRING, action STRING, actor STRING, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_AUDIT_TRAIL (AUDIT_ID, ENTITY_TYPE, ENTITY_ID, ACTION, ACTOR, METADATA) VALUES (UUID_STRING(), :entity_type, :entity_id, :action, :actor, :metadata);
$$;

