CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_NOTIFICATION(request_id STRING, signer_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_NOTIFICATIONS (NOTIFICATION_ID, REQUEST_ID, SIGNER_ID, CHANNEL, PAYLOAD, STATUS) VALUES (UUID_STRING(), :request_id, :signer_id, :channel, :payload, 'PENDING');
$$;

