CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEO_FACTOR(request_id STRING, ip_addr STRING, geo VARIANT, risk_score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_GEO_FACTORS (FACTOR_ID, REQUEST_ID, IP_ADDR, GEO, RISK_SCORE) VALUES (UUID_STRING(), :request_id, :ip_addr, :geo, :risk_score);
$$;

