CREATE OR REPLACE PROCEDURE DOCGEN.SET_RATECARD_OVERRIDE(account_id STRING, template_id STRING, price NUMBER, valid_from TIMESTAMP_LTZ, valid_to TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RATECARD_OVERRIDES (OVERRIDE_ID, ACCOUNT_ID, TEMPLATE_ID, PRICE_OVERRIDE, VALID_FROM, VALID_TO) VALUES (UUID_STRING(), :account_id, :template_id, :price, :valid_from, :valid_to);
$$;

