CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_USAGE_CREDIT(account_id STRING, amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.USAGE_CREDITS SET CREDITS = CREDITS - :amount WHERE ACCOUNT_ID = :account_id AND EXPIRES_AT > CURRENT_TIMESTAMP();
$$;

