CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_PROVIDER_STATUS(provider_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_PROVIDER_STATUS tgt USING (SELECT :provider_id AS pid, :status AS st, :details AS d) src ON tgt.PROVIDER_ID = src.pid
WHEN MATCHED THEN UPDATE SET STATUS = src.st, DETAILS = src.d, LAST_UPDATED = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PROVIDER_ID, STATUS, DETAILS) VALUES (src.pid, src.st, src.d);
$$;

