CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PROVIDER_REQUEST(provider_id STRING, request_id STRING, priority NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_QUEUES (QUEUE_ID, PROVIDER_ID, REQUEST_ID, PRIORITY) VALUES (UUID_STRING(), :provider_id, :request_id, :priority);
$$;

