CREATE OR REPLACE PROCEDURE DOCGEN.PLACE_LEGAL_HOLD(bundle_id STRING, reason STRING, placed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLDS (HOLD_ID, BUNDLE_ID, REASON, PLACED_BY) VALUES (UUID_STRING(), :bundle_id, :reason, :placed_by);
$$;

