CREATE OR REPLACE PROCEDURE DOCGEN.SET_PROVIDER_BACKOFF(provider_id STRING, delay_seconds INT, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_BACKOFF (BACKOFF_ID, PROVIDER_ID, NEXT_ATTEMPT_AT, REASON) VALUES (UUID_STRING(), :provider_id, DATEADD(second, :delay_seconds, CURRENT_TIMESTAMP()), :reason);
$$;

