CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HOLD_AUDIT(hold_id STRING, action STRING, actor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_AUDIT (AUDIT_ID, HOLD_ID, ACTION, ACTOR) VALUES (UUID_STRING(), :hold_id, :action, :actor);
$$;

