CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_FAILURE(provider_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_FAILURES (FAILURE_ID, PROVIDER_ID, DETAILS) VALUES (UUID_STRING(), :provider_id, :details);
$$;

