CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_RETENTION_ACTION(target STRING, action_type STRING, schedule_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_ACTIONS (ACTION_ID, TARGET, ACTION_TYPE, SCHEDULE_AT) VALUES (UUID_STRING(), :target, :action_type, :schedule_at);
$$;

