CREATE OR REPLACE PROCEDURE DOCGEN.RUN_SCHEDULED_RETENTION()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.8'
HANDLER='handler'
AS
$$
# staged handler at @~/procedures/run_scheduled_retention.py
$$;

