CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ESCALATION_STEP(incident_id STRING, step INT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_ESCALATIONS (ESCALATION_ID, INCIDENT_ID, STEP, ACTION) VALUES (UUID_STRING(), :incident_id, :step, :action);
$$;

