CREATE OR REPLACE PROCEDURE DOCGEN.INGEST_RT_EVENT(stream_name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REALTIME_MONITORING_EVENTS (EVENT_ID, STREAM_NAME, PAYLOAD) VALUES (UUID_STRING(), :stream_name, :payload);
$$;

