CREATE OR REPLACE PROCEDURE DOCGEN.AGGREGATE_DAILY_METRICS(day DATE)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DAILY_SIGNATURE_METRICS (DAY_ID, DAY, ACCOUNT_ID, SIGNATURES_COUNT, FAILURES_COUNT)
SELECT UUID_STRING(), :day, ACCOUNT_ID, SUM(CASE WHEN EVENT_TYPE='SIGNED' THEN 1 ELSE 0 END), SUM(CASE WHEN EVENT_TYPE='FAILED' THEN 1 ELSE 0 END))
FROM DOCGEN.SIGNATURE_EVENTS
WHERE CAST(EVENT_TS AS DATE) = :day
GROUP BY ACCOUNT_ID;
$$;

