CREATE OR REPLACE PROCEDURE DOCGEN.PUT_SIMILARITY_CACHE(query_hash STRING, results VARIANT, ttl_minutes INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIMILARITY_CACHE t USING (SELECT :query_hash AS q, :results AS r) s ON t.QUERY_HASH = s.q WHEN MATCHED THEN UPDATE SET RESULTS = s.r, EXPIRES_AT = DATEADD(minute, :ttl_minutes, CURRENT_TIMESTAMP()) WHEN NOT MATCHED THEN INSERT (CACHE_ID, QUERY_HASH, RESULTS, EXPIRES_AT) VALUES (UUID_STRING(), s.q, s.r, DATEADD(minute, :ttl_minutes, CURRENT_TIMESTAMP()));
$$;

