CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_NOTIFICATION(title STRING, body STRING, level STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_NOTIFICATIONS (NOTIF_ID, TITLE, BODY, LEVEL) VALUES (UUID_STRING(), :title, :body, :level);
$$;

