CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_REQUEST_LOCK(request_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.REQUEST_LOCKS t USING (SELECT :request_id AS rid, :locked_by AS lb) s ON t.REQUEST_ID = s.rid
WHEN MATCHED THEN UPDATE SET LOCKED_AT = CURRENT_TIMESTAMP(), LOCKED_BY = s.lb
WHEN NOT MATCHED THEN INSERT (LOCK_ID, REQUEST_ID, LOCKED_AT, LOCKED_BY) VALUES (UUID_STRING(), s.rid, CURRENT_TIMESTAMP(), s.lb);
$$;

