CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_QUICK_ACTION(name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_QUICK_ACTIONS (ACTION_ID, NAME, PAYLOAD) VALUES (UUID_STRING(), :name, :payload);
$$;

