CREATE OR REPLACE PROCEDURE DOCGEN.SET_TENANT_PREF(account_id STRING, key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TENANT_PREFERENCES t USING (SELECT :account_id AS aid, :key AS k, :value AS v) s ON t.ACCOUNT_ID = s.aid AND t.PREF_KEY = s.k
WHEN MATCHED THEN UPDATE SET PREF_VALUE = s.v, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PREF_ID, ACCOUNT_ID, PREF_KEY, PREF_VALUE) VALUES (UUID_STRING(), s.aid, s.k, s.v);
$$;

