CREATE OR REPLACE PROCEDURE DOCGEN.SET_FEATURE_FLAG(name STRING, enabled BOOLEAN, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.FEATURE_FLAGS t USING (SELECT :name AS n, :enabled AS e, :meta AS m) s ON t.NAME = s.n WHEN MATCHED THEN UPDATE SET ENABLED = s.e, META = s.m, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (FLAG_ID, NAME, ENABLED, META) VALUES (UUID_STRING(), s.n, s.e, s.m);
$$;

