CREATE OR REPLACE PROCEDURE DOCGEN.MOVE_TO_DLQ(raw_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_DLQ (DLQ_ID, RAW_ID, REASON) VALUES (UUID_STRING(), :raw_id, :reason);
$$;

