CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_EMAIL_TEMPLATE(name STRING, subject STRING, body STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EMAIL_TEMPLATES t USING (SELECT :name AS n, :subject AS s, :body AS b) src ON t.NAME = src.n WHEN MATCHED THEN UPDATE SET SUBJECT = src.s, BODY = src.b WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, SUBJECT, BODY) VALUES (UUID_STRING(), src.n, src.s, src.b);
$$;

