CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTIFICATION_HISTORY(notif_id STRING, channel STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_HISTORY (NH_ID, NOTIF_ID, CHANNEL, STATUS) VALUES (UUID_STRING(), :notif_id, :channel, :status);
$$;

