CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SMS_TEMPLATE(name STRING, body STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SMS_TEMPLATES t USING (SELECT :name AS n, :body AS b) src ON t.NAME = src.n WHEN MATCHED THEN UPDATE SET BODY = src.b WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, BODY) VALUES (UUID_STRING(), src.n, src.b);
$$;

