CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BILLING_HISTORY(account_id STRING, start_date DATE, end_date DATE, amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TENANT_BILLING_HISTORY (BILL_ID, ACCOUNT_ID, PERIOD_START, PERIOD_END, TOTAL_AMOUNT) VALUES (UUID_STRING(), :account_id, :start_date, :end_date, :amount);
$$;

