CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SMS_LOG(to_number STRING, body STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMS_LOG (LOG_ID, TO_NUMBER, BODY, STATUS) VALUES (UUID_STRING(), :to_number, :body, :status);
$$;

