CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RECONCILIATION(bill_id STRING, ext_ref STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_RECONCILIATIONS (RECON_ID, BILL_ID, EXTERNAL_INVOICE_REF, STATUS, DETAILS) VALUES (UUID_STRING(), :bill_id, :ext_ref, :status, :details);
$$;

