CREATE OR REPLACE PROCEDURE DOCGEN.OPEN_DISPUTE(bill_id STRING, reason STRING, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_DISPUTES (DISPUTE_ID, BILL_ID, REASON, CREATED_BY, STATUS) VALUES (UUID_STRING(), :bill_id, :reason, :created_by, 'OPEN');
$$;

