CREATE OR REPLACE PROCEDURE DOCGEN.SET_USER_PREF(user_id STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.USER_PREFERENCES t USING (SELECT :user_id AS uid, :prefs AS p) s ON t.USER_ID = s.uid WHEN MATCHED THEN UPDATE SET PREFS = s.p, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PREF_ID, USER_ID, PREFS) VALUES (UUID_STRING(), s.uid, s.p);
$$;

