CREATE OR REPLACE PROCEDURE DOCGEN.POST_ACTIVITY_FEED(account_id STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_ACTIVITY_FEED (FEED_ID, ACCOUNT_ID, MESSAGE) VALUES (UUID_STRING(), :account_id, :message);
$$;

