CREATE OR REPLACE PROCEDURE DOCGEN.END_USER_SESSION(session_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.USER_SESSIONS SET ENDED_AT = CURRENT_TIMESTAMP() WHERE SESSION_ID = :session_id;
$$;

