CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_TEMPLATE_PERMISSION(template_id STRING, principal STRING, perm STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PERMISSIONS (TP_ID, TEMPLATE_ID, PRINCIPAL, PERM) VALUES (UUID_STRING(), :template_id, :principal, :perm);
$$;

