CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_VERSION_CHANGE(template_id STRING, version_number INT, changed_by STRING, diff VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_VERSIONS_HISTORY (TVH_ID, TEMPLATE_ID, VERSION_NUMBER, CHANGED_BY, DIFF) VALUES (UUID_STRING(), :template_id, :version_number, :changed_by, :diff);
$$;

