CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT_AUDIT(consent_id STRING, signer_id STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_AUDIT (AUDIT_ID, CONSENT_ID, SIGNER_ID, ACTION) VALUES (UUID_STRING(), :consent_id, :signer_id, :action);
$$;

