CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_HASH(signer_id STRING, template_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES (TEMPLATE_ID, SIGNER_ID, TEMPLATE_HASH) VALUES (UUID_STRING(), :signer_id, :template_hash);
$$;

