CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_DEVICE_FINGERPRINT(device_id STRING, attributes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_FINGERPRINTS t USING (SELECT :device_id AS did, :attributes AS attrs) s ON t.DEVICE_ID = s.did
WHEN MATCHED THEN UPDATE SET ATTRIBUTES = s.attrs, LAST_SEEN = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (FINGERPRINT_ID, DEVICE_ID, ATTRIBUTES) VALUES (UUID_STRING(), s.did, s.attrs);
$$;

