CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RISK_SCORE(request_id STRING, score FLOAT, factors VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_SCORES (SCORE_ID, REQUEST_ID, SCORE, FACTORS) VALUES (UUID_STRING(), :request_id, :score, :factors);
$$;

