CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_FAILURE_RETRY(request_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_FAILURE_RETRIES t USING (SELECT :request_id AS rid, :reason AS r) s ON t.REQUEST_ID = s.rid
WHEN MATCHED THEN UPDATE SET ATTEMPTS = ATTEMPTS + 1, NEXT_ATTEMPT_AT = DATEADD(minute, POWER(2, ATTEMPTS), CURRENT_TIMESTAMP())
WHEN NOT MATCHED THEN INSERT (RETRY_ID, REQUEST_ID, FAILURE_REASON, ATTEMPTS, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), s.rid, s.r, 1, DATEADD(minute, 1, CURRENT_TIMESTAMP()));
$$;

