CREATE OR REPLACE PROCEDURE DOCGEN.PUSH_TO_PROVIDER_BACKLOG(provider_id STRING, data VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_BACKLOG (BACKLOG_ID, PROVIDER_ID, DATA) VALUES (UUID_STRING(), :provider_id, :data);
$$;

