CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONFIDENCE_SCORE(request_id STRING, signer_id STRING, score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONFIDENCE_SCORES (SCORE_ID, REQUEST_ID, SIGNER_ID, SCORE, DETAILS) VALUES (UUID_STRING(), :request_id, :signer_id, :score, :details);
$$;

