CREATE OR REPLACE PROCEDURE DOCGEN.WRITE_PROVENANCE_ENTRY(bundle_id STRING, hash STRING, anchor_txid STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVENANCE_INDEX (PROV_ID, BUNDLE_ID, HASH, ANCHOR_TXID) VALUES (UUID_STRING(), :bundle_id, :hash, :anchor_txid);
$$;

