CREATE OR REPLACE PROCEDURE DOCGEN.STORE_CERTIFICATE(cert_pem CLOB, subject STRING, issuer STRING, serial STRING, not_before TIMESTAMP_LTZ, not_after TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERTIFICATE_STORE (CERT_ID, CERT_PEM, SUBJECT, ISSUER, SERIAL_NUMBER, NOT_BEFORE, NOT_AFTER) VALUES (UUID_STRING(), :cert_pem, :subject, :issuer, :serial, :not_before, :not_after);
$$;

