CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_OCSP_STATUS(cert_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OCSP_CACHE t USING (SELECT :cert_id AS cid, :status AS st) s ON t.CERT_ID = s.cid WHEN MATCHED THEN UPDATE SET STATUS = s.st, CHECKED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (OCSP_ID, CERT_ID, STATUS) VALUES (UUID_STRING(), s.cid, s.st);
$$;

