CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_OCSP_POLL(cert_id STRING, cron_expr STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OCSP_POLL_JOBS (JOB_ID, CERT_ID, SCHEDULE_CRON) VALUES (UUID_STRING(), :cert_id, :cron_expr);
$$;

