CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_TEMPLATE_ACL(template_id STRING, principal STRING, permissions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_ACL (ACL_ID, TEMPLATE_ID, PRINCIPAL, PERMISSIONS) VALUES (UUID_STRING(), :template_id, :principal, :permissions);
$$;

