CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SHARING_LINK(template_id STRING, ttl_hours INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_SHARING_LINKS (LINK_ID, TEMPLATE_ID, LINK_TOKEN, EXPIRES_AT) VALUES (UUID_STRING(), :template_id, UUID_STRING(), DATEADD(hour, :ttl_hours, CURRENT_TIMESTAMP()));
$$;

