CREATE OR REPLACE PROCEDURE DOCGEN.RELEASE_LEGAL_HOLD(hold_id STRING, released_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_RELEASES (RELEASE_ID, HOLD_ID, RELEASED_BY) VALUES (UUID_STRING(), :hold_id, :released_by);
$$;

