CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ARCHIVAL_MANIFEST(request_id STRING, files ARRAY, stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVAL_MANIFESTS (MANIFEST_ID, REQUEST_ID, FILES, ARCHIVE_STAGE) VALUES (UUID_STRING(), :request_id, :files, :stage);
$$;

