CREATE OR REPLACE PROCEDURE DOCGEN.REQUEST_COMPLIANCE_EXPORT(manifest_id STRING, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_EXPORTS (EXPORT_ID, MANIFEST_ID, TARGET_STAGE, STATUS) VALUES (UUID_STRING(), :manifest_id, :target_stage, 'PENDING');
$$;

