CREATE OR REPLACE PROCEDURE DOCGEN.RUN_COMPLIANCE_EXPORTS()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.8'
HANDLER='handler'
AS
$$
# staged handler at @~/procedures/run_compliance_exports.py
$$;

