CREATE OR REPLACE PROCEDURE DOCGEN.ADD_OPERATOR_NOTE(operator_id STRING, note_text STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_NOTES (NOTE_ID, OPERATOR_ID, NOTE_TEXT) VALUES (UUID_STRING(), :operator_id, :note_text);
$$;

