CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH(signer_id STRING, score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCH_HISTORY (MATCH_ID, SIGNER_ID, MATCH_SCORE, DETAILS) VALUES (UUID_STRING(), :signer_id, :score, :details);
$$;

