CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_API_USAGE(account_id STRING, endpoint STRING, increment INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.API_USAGE t USING (SELECT :account_id AS aid, :endpoint AS ep, :increment AS inc) s ON t.ACCOUNT_ID = s.aid AND t.ENDPOINT = s.ep
WHEN MATCHED THEN UPDATE SET COUNT = COUNT + s.inc
WHEN NOT MATCHED THEN INSERT (USAGE_ID, ACCOUNT_ID, ENDPOINT, COUNT, WINDOW_START) VALUES (UUID_STRING(), s.aid, s.ep, s.inc, CURRENT_TIMESTAMP());
$$;

