CREATE OR REPLACE PROCEDURE DOCGEN.CHECK_AND_RESERVE_PROVIDER_CAPACITY(provider_id STRING, requested INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT OBJECT_CONSTRUCT('ok', CASE WHEN CURRENT_CONCURRENT + :requested <= MAX_CONCURRENT THEN TRUE ELSE FALSE END) FROM DOCGEN.PROVIDER_CAPACITIES WHERE PROVIDER_ID = :provider_id;
$$;

