CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_METRIC(template_id STRING, name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_METRICS (METRIC_ID, TEMPLATE_ID, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :template_id, :name, :value);
$$;

