CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_SEARCH_TOKEN(token STRING, entity_ref VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_TOKENS (TOKEN_ID, TOKEN, ENTITY_REF) VALUES (UUID_STRING(), :token, :entity_ref);
$$;

