CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_REPORT(name STRING, query STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPORT_DEFINITIONS (REPORT_ID, NAME, QUERY, OWNER) VALUES (UUID_STRING(), :name, :query, :owner);
$$;

