CREATE OR REPLACE PROCEDURE DOCGEN.CHARGE_EXPORT_USAGE(account_id STRING, amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.EXPORT_QUOTAS SET USED = USED + :amount, UPDATED_AT = CURRENT_TIMESTAMP() WHERE ACCOUNT_ID = :account_id;
$$;

