CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_HEARTBEAT(provider_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_HEARTBEAT (HB_ID, PROVIDER_ID, STATUS) VALUES (UUID_STRING(), :provider_id, :status);
$$; 
-- @31 @24 @52

