CREATE OR REPLACE PROCEDURE DOCGEN.TAG_PROVIDER(provider_id STRING, tag STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_TAGS (TAG_ID, PROVIDER_ID, TAG) VALUES (UUID_STRING(), :provider_id, :tag);
$$; 
-- @31 @24 @52

