CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_SYNONYM(template_id STRING, synonym STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_SYNONYMS (SYN_ID, TEMPLATE_ID, SYNONYM) VALUES (UUID_STRING(), :template_id, :synonym);
$$;

