CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_SLA_CHANGE(provider_id STRING, slo VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_SLA_HISTORY (HIST_ID, PROVIDER_ID, SLO) VALUES (UUID_STRING(), :provider_id, :slo);
$$; 
-- @31 @24 @52

