CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_QUALITY_SCORE(template_id STRING, score FLOAT, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_QUALITY_SCORES (SCORE_ID, TEMPLATE_ID, SCORE, METRICS) VALUES (UUID_STRING(), :template_id, :score, :metrics);
$$;

