CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ROUTING_RULE(name STRING, criteria VARIANT, priority INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ROUTING_RULES (RULE_ID, NAME, CRITERIA, PRIORITY) VALUES (UUID_STRING(), :name, :criteria, :priority);
$$; 
-- @31 @24 @52

