CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_TOKEN(token_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVOKED_TOKENS (REVOKE_ID, TOKEN_ID, REASON) VALUES (UUID_STRING(), :token_id, :reason);
$$;

