CREATE OR REPLACE PROCEDURE DOCGEN.SET_PROVIDER_QUOTA(provider_id STRING, max_per_min INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_QUOTAS t USING (SELECT :provider_id AS pid, :max_per_min AS m) s ON t.PROVIDER_ID = s.pid WHEN MATCHED THEN UPDATE SET MAX_PER_MIN = s.m, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (QUOTA_ID, PROVIDER_ID, MAX_PER_MIN) VALUES (UUID_STRING(), s.pid, s.m);
$$; 
-- @31 @24 @52

