CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_INTEGRATION(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRDPARTY_INTEGRATIONS (INTEGRATION_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$;

