CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ACCOUNT_WHITELIST(account_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_WHITELIST (WL_ID, ACCOUNT_ID, REASON) VALUES (UUID_STRING(), :account_id, :reason);
$$; 
-- @31 @24 @52

