CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_AND_STORE_CHECKSUM(document_id STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_CHECKSUMS (CHECK_ID, DOCUMENT_ID, CHECKSUM) VALUES (UUID_STRING(), :document_id, :checksum);
$$; 
-- @31 @24 @52

