CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POOL_STATS(pool_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_POOL_STATS (STATS_ID, POOL_ID, METRICS) VALUES (UUID_STRING(), :pool_id, :metrics);
$$;

