CREATE OR REPLACE PROCEDURE DOCGEN.LOCK_TEMPLATE(template_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_LOCKS (LOCK_ID, TEMPLATE_ID, LOCKED_BY) VALUES (UUID_STRING(), :template_id, :locked_by);
$$; 
-- @31 @24 @52

