CREATE OR REPLACE PROCEDURE DOCGEN.FLAG_SUSPECT_ACTIVITY(request_id STRING, reason STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUSPECT_ACTIVITY (SUSPECT_ID, REQUEST_ID, REASON, DETAILS) VALUES (UUID_STRING(), :request_id, :reason, :details);
$$;

