CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_UNLOCK(template_id STRING, unlocked_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.TEMPLATE_LOCK_HISTORY SET UNLOCKED_AT = :unlocked_at WHERE TEMPLATE_ID = :template_id;
$$; 
-- @31 @24 @52

