CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LOCKOUT_EVENT(signer_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LOCKOUT_EVENTS (EVENT_ID, SIGNER_ID, REASON) VALUES (UUID_STRING(), :signer_id, :reason);
$$; 
-- @31 @24 @52

