CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SLA(metric STRING, sla_def VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_MAP (MAP_ID, METRIC, SLA_DEF) VALUES (UUID_STRING(), :metric, :sla_def);
$$;

