CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_VIOLATION(metric STRING, value VARIANT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_VIOLATIONS (VIOLATION_ID, METRIC, VALUE, DETAILS) VALUES (UUID_STRING(), :metric, :value, :details);
$$;

