CREATE OR REPLACE PROCEDURE DOCGEN.SUBSCRIBE_ALERT(principal STRING, alert_type STRING, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_SUBSCRIPTIONS (SUB_ID, PRINCIPAL, ALERT_TYPE, CHANNEL) VALUES (UUID_STRING(), :principal, :alert_type, :channel);
$$; 
-- @31 @24 @52

