CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ALERT_DELIVERY(alert_id STRING, principal STRING, channel STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_DELIVERY_LOG (DELIVERY_ID, ALERT_ID, PRINCIPAL, CHANNEL, STATUS) VALUES (UUID_STRING(), :alert_id, :principal, :channel, :status);
$$; 
-- @31 @24 @52

