CREATE OR REPLACE PROCEDURE DOCGEN.ADD_PROVIDER_REGION(provider_id STRING, region STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_REGIONS (PR_ID, PROVIDER_ID, REGION, CONFIG) VALUES (UUID_STRING(), :provider_id, :region, :config);
$$;

