CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_OUTAGE(provider_id STRING, started_at TIMESTAMP_LTZ, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_OUTAGES (OUTAGE_ID, PROVIDER_ID, STARTED_AT, DETAILS) VALUES (UUID_STRING(), :provider_id, :started_at, :details);
$$; 
-- @31 @24 @52

