CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_REGION_FAILOVER(region STRING, fallback_region STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REGION_FAILOVERS (FAIL_ID, REGION, FALLBACK_REGION) VALUES (UUID_STRING(), :region, :fallback_region);
$$;

