CREATE OR REPLACE PROCEDURE DOCGEN.RUN_HEALTH_CHECK(component STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HEALTH_CHECKS (HC_ID, COMPONENT, STATUS, DETAILS) VALUES (UUID_STRING(), :component, :status, :details);
$$; 
-- @31 @24 @52

