CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATOR_ROLE(role_name STRING, description STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION) VALUES (UUID_STRING(), :role_name, :description);
$$; 
-- @31 @24 @52

