CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_SLA_REPORT(name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_REPORTS (REPORT_ID, NAME, PAYLOAD) VALUES (UUID_STRING(), :name, :payload);
$$; 
-- @31 @24 @52

