CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_SLA_ALERT(report_id STRING, level STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_ALERTS (ALERT_ID, REPORT_ID, LEVEL, DETAILS) VALUES (UUID_STRING(), :report_id, :level, :details);
$$; 
-- @31 @24 @52

