CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_DASHBOARD_WIDGET(name STRING, config VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DASHBOARD_WIDGETS (WIDGET_ID, NAME, CONFIG, OWNER) VALUES (UUID_STRING(), :name, :config, :owner);
$$; 
-- @31 @24 @52

