CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DASHBOARD_DATA(widget_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DASHBOARD_DATA t USING (SELECT :widget_id AS wid, :payload AS p) s ON t.WIDGET_ID = s.wid WHEN MATCHED THEN UPDATE SET PAYLOAD = s.p, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DATA_ID, WIDGET_ID, PAYLOAD) VALUES (UUID_STRING(), s.wid, s.p);
$$; 
-- @31 @24 @52

