CREATE OR REPLACE PROCEDURE DOCGEN.BIND_POLICY(policy_id STRING, target STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_BINDINGS (BIND_ID, POLICY_ID, TARGET) VALUES (UUID_STRING(), :policy_id, :target);
$$; 
-- @31 @24 @52

