CREATE OR REPLACE PROCEDURE DOCGEN.REPORT_POLICY_VIOLATION(policy_id STRING, entity_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_VIOLATIONS (VIOLATION_ID, POLICY_ID, ENTITY_REF, DETAILS) VALUES (UUID_STRING(), :policy_id, :entity_ref, :details);
$$; 
-- @31 @24 @52

