CREATE OR REPLACE PROCEDURE DOCGEN.START_INCIDENT_RUN(incident_id STRING, playbook_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_RUN_LOG (RUN_ID, INCIDENT_ID, PLAYBOOK_ID, STARTED_AT, STATUS) VALUES (UUID_STRING(), :incident_id, :playbook_id, CURRENT_TIMESTAMP(), 'RUNNING');
$$; 
-- @31 @24 @52

