CREATE OR REPLACE PROCEDURE DOCGEN.COMPLETE_INCIDENT_RUN(run_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.INCIDENT_RUN_LOG SET COMPLETED_AT = CURRENT_TIMESTAMP(), STATUS = :status WHERE RUN_ID = :run_id;
$$; 
-- @31 @24 @52

