CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATOR_CHECKLIST(name STRING, items VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_CHECKLISTS (CHECKLIST_ID, NAME, ITEMS, OWNER) VALUES (UUID_STRING(), :name, :items, :owner);
$$; 
-- @31 @24 @52

