CREATE OR REPLACE PROCEDURE DOCGEN.START_CHECKLIST_RUN(checklist_id STRING, run_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHECKLIST_RUNS (RUN_ID, CHECKLIST_ID, RUN_BY, STATUS) VALUES (UUID_STRING(), :checklist_id, :run_by, 'IN_PROGRESS');
$$; 
-- @31 @24 @52

