CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COST_CENTER(account_id STRING, name STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COST_CENTERS (CC_ID, ACCOUNT_ID, NAME, OWNER) VALUES (UUID_STRING(), :account_id, :name, :owner);
$$; 
-- @31 @24 @52

