CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BUDGET_ALERT(cc_id STRING, threshold NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BUDGET_ALERTS (ALERT_ID, CC_ID, THRESHOLD) VALUES (UUID_STRING(), :cc_id, :threshold);
$$; 
-- @31 @24 @52

