CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BUDGET_RUN(cc_id STRING, spent NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BUDGET_RUNS (RUN_ID, CC_ID, SPENT) VALUES (UUID_STRING(), :cc_id, :spent);
$$; 
-- @31 @24 @52

