CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_KEY_AUDIT(client_id STRING, action STRING, action_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEYS_AUDIT (AUDIT_ID, CLIENT_ID, ACTION, ACTION_BY, META) VALUES (UUID_STRING(), :client_id, :action, :action_by, :meta);
$$;

