CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_WEBHOOK_CONSUMER(provider STRING, endpoint STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_CONSUMERS (CONSUMER_ID, PROVIDER, ENDPOINT, SECRET_HASH) VALUES (UUID_STRING(), :provider, :endpoint, :secret_hash);
$$;

