CREATE OR REPLACE PROCEDURE DOCGEN.ROTATE_PROVIDER_ENDPOINT(provider_id STRING, old_endpoint STRING, new_endpoint STRING, rotated_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ROTATION_LOG (ROT_ID, PROVIDER_ID, OLD_ENDPOINT, NEW_ENDPOINT, ROTATED_BY) VALUES (UUID_STRING(), :provider_id, :old_endpoint, :new_endpoint, :rotated_by);
$$;

