CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_PREVIEW(template_id STRING, account_id STRING, payload VARIANT, render_url STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PREVIEWS (PREVIEW_ID, TEMPLATE_ID, ACCOUNT_ID, PREVIEW_PAYLOAD, RENDER_URL) VALUES (UUID_STRING(), :template_id, :account_id, :payload, :render_url);
$$;

