CREATE OR REPLACE PROCEDURE DOCGEN.LOG_PREVIEW_ACCESS(preview_id STRING, user_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PREVIEW_ACCESS_LOG (ACCESS_ID, PREVIEW_ID, USER_ID) VALUES (UUID_STRING(), :preview_id, :user_id);
$$;

