CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_TEMPLATE_RENDERER(name STRING, image_ref STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_RENDERERS (RENDERER_ID, NAME, IMAGE_REF, CONFIG) VALUES (UUID_STRING(), :name, :image_ref, :config);
$$;

