CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_RENDERER_JOB(renderer_id STRING, job_payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDERER_QUEUE (QUEUE_ID, RENDERER_ID, JOB_PAYLOAD) VALUES (UUID_STRING(), :renderer_id, :job_payload);
$$;

