CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RENDERER_LOG(queue_id STRING, renderer_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDERER_LOGS (LOG_ID, QUEUE_ID, RENDERER_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :queue_id, :renderer_id, :status, :details);
$$;

