CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_RENDER_ERROR_CODE(error_code STRING, description STRING, recoverable BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_ERROR_CODES (ERROR_CODE, DESCRIPTION, RECOVERABLE) VALUES (:error_code, :description, :recoverable);
$$;

