CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RENDER_RETRY_POLICY(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_RETRY_POLICIES (POLICY_ID, NAME, RULES) VALUES (UUID_STRING(), :name, :rules);
$$;

