CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_ANCHOR(template_id STRING, anchor_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_ANCHORS (ANCHOR_ID, TEMPLATE_ID, ANCHOR_HASH) VALUES (UUID_STRING(), :template_id, :anchor_hash);
$$;

