CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_COMPLIANCE_TAG(template_id STRING, tag STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_COMPLIANCE_TAGS (TAG_ID, TEMPLATE_ID, TAG) VALUES (UUID_STRING(), :template_id, :tag);
$$;

