CREATE OR REPLACE PROCEDURE DOCGEN.SET_TEMPLATE_CERT_REQUIREMENT(template_id STRING, requirement VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CERT_REQUIREMENTS (REQ_ID, TEMPLATE_ID, REQUIREMENT) VALUES (UUID_STRING(), :template_id, :requirement);
$$;

