CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_JURISDICTION(template_id STRING, country_code STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_JURISDICTIONS (JURIS_ID, TEMPLATE_ID, COUNTRY_CODE, RULES) VALUES (UUID_STRING(), :template_id, :country_code, :rules);
$$;

