CREATE OR REPLACE PROCEDURE DOCGEN.PERFORM_JURISDICTION_CHECK(request_id STRING, country_code STRING, passed BOOLEAN, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.JURISDICTION_CHECKS (CHECK_ID, REQUEST_ID, COUNTRY_CODE, PASSED, DETAILS) VALUES (UUID_STRING(), :request_id, :country_code, :passed, :details);
$$;

