CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ZIP_RECONCILE(manifest_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ZIP_RECONCILE (RECON_ID, MANIFEST_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :manifest_id, :status, :details);
$$;

