CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PURGE_SCHEDULE(target_table STRING, cron_expr STRING, retention_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_SCHEDULES (SCHEDULE_ID, TARGET_TABLE, CRON_EXPR, RETENTION_DAYS) VALUES (UUID_STRING(), :target_table, :cron_expr, :retention_days);
$$;

