CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PURGE_AUDIT(schedule_id STRING, target_table STRING, purged_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_AUDIT (AUDIT_ID, SCHEDULE_ID, TARGET_TABLE, PURGED_COUNT) VALUES (UUID_STRING(), :schedule_id, :target_table, :purged_count);
$$;

