CREATE OR REPLACE PROCEDURE DOCGEN.SET_SLA_THRESHOLD(metric_name STRING, threshold_value VARIANT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_THRESHOLDS (THRESHOLD_ID, METRIC_NAME, THRESHOLD_VALUE, ACTION) VALUES (UUID_STRING(), :metric_name, :threshold_value, :action);
$$;

