CREATE OR REPLACE PROCEDURE DOCGEN.SEND_SLA_NOTIFICATION(threshold_id STRING, sent_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_NOTIFICATIONS (NOTIF_ID, THRESHOLD_ID, SENT_TO) VALUES (UUID_STRING(), :threshold_id, :sent_to);
$$;

