CREATE OR REPLACE PROCEDURE DOCGEN.SET_QUOTA_OVERRIDE(account_id STRING, quota_type STRING, value VARIANT, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_OVERRIDES (OVERRIDE_ID, ACCOUNT_ID, QUOTA_TYPE, VALUE, EXPIRES_AT) VALUES (UUID_STRING(), :account_id, :quota_type, :value, :expires_at);
$$;

