CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_QUOTA_CHANGE(account_id STRING, quota_type STRING, old_value VARIANT, new_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_HISTORY (HISTORY_ID, ACCOUNT_ID, QUOTA_TYPE, OLD_VALUE, NEW_VALUE) VALUES (UUID_STRING(), :account_id, :quota_type, :old_value, :new_value);
$$;

