CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RATECARD_CHANGE(account_id STRING, change VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RATECARD_CHANGES (CHANGE_ID, ACCOUNT_ID, CHANGE) VALUES (UUID_STRING(), :account_id, :change);
$$;

