CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INVOICE_DRAFT(account_id STRING, period_start DATE, period_end DATE, line_items VARIANT, total NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_DRAFTS (DRAFT_ID, ACCOUNT_ID, PERIOD_START, PERIOD_END, LINE_ITEMS, TOTAL) VALUES (UUID_STRING(), :account_id, :period_start, :period_end, :line_items, :total);
$$;

