CREATE OR REPLACE PROCEDURE DOCGEN.ADD_INVOICE_COMMENT(draft_id STRING, comment_by STRING, comment TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_COMMENTS (COMMENT_ID, DRAFT_ID, COMMENT_BY, COMMENT) VALUES (UUID_STRING(), :draft_id, :comment_by, :comment);
$$;

