CREATE OR REPLACE PROCEDURE DOCGEN.APPROVE_INVOICE_DRAFT(draft_id STRING, approved_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_APPROVALS (APPROVAL_ID, DRAFT_ID, APPROVED_BY, STATUS) VALUES (UUID_STRING(), :draft_id, :approved_by, 'APPROVED');
$$;

