CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INVOICE_DISTRIBUTION(invoice_id STRING, sent_to STRING, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_DISTRIBUTIONS (DIST_ID, INVOICE_ID, SENT_TO, CHANNEL) VALUES (UUID_STRING(), :invoice_id, :sent_to, :channel);
$$;

