CREATE OR REPLACE PROCEDURE DOCGEN.SET_ACCOUNT_BILLING_PREF(account_id STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ACCOUNT_BILLING_PREFERENCES t USING (SELECT :account_id AS aid, :prefs AS p) s ON t.ACCOUNT_ID = s.aid WHEN MATCHED THEN UPDATE SET PREFERENCES = s.p, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PREF_ID, ACCOUNT_ID, PREFERENCES) VALUES (UUID_STRING(), s.aid, s.p);
$$;

