CREATE OR REPLACE PROCEDURE DOCGEN.SEND_BILLING_NOTIFICATION(account_id STRING, message STRING, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_NOTIFICATIONS (NOTIF_ID, ACCOUNT_ID, MESSAGE, CHANNEL) VALUES (UUID_STRING(), :account_id, :message, :channel);
$$;

