CREATE OR REPLACE PROCEDURE DOCGEN.SEED_DEMO_TEMPLATE(name STRING, body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEMO_TEMPLATES (TEMPLATE_ID, NAME, BODY) VALUES (UUID_STRING(), :name, :body);
$$;

