CREATE OR REPLACE PROCEDURE DOCGEN.SEED_DEMO_SIGNER(name STRING, email STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEMO_SIGNERS (SIGNER_ID, NAME, EMAIL) VALUES (UUID_STRING(), :name, :email);
$$;

