CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DEMO_JOB(template_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEMO_JOBS (JOB_ID, TEMPLATE_ID, ACCOUNT_ID, STATUS) VALUES (UUID_STRING(), :template_id, :account_id, 'CREATED');
$$;

