CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ACTION(action_name STRING, payload VARIANT, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTIONS (ACTION_ID, ACTION_NAME, PAYLOAD, PERFORMED_BY) VALUES (UUID_STRING(), :action_name, :payload, :performed_by);
$$;

