CREATE OR REPLACE PROCEDURE DOCGEN.PUBLISH_RELEASE_NOTE(version STRING, notes TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RELEASE_NOTES (NOTE_ID, VERSION, NOTES) VALUES (UUID_STRING(), :version, :notes);
$$;

