CREATE OR REPLACE PROCEDURE DOCGEN.ADD_REQUEST_LABEL(request_id STRING, label STRING, added_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REQUEST_LABELS (LABEL_ID, REQUEST_ID, LABEL, ADDED_BY)
VALUES (UUID_STRING(), :request_id, :label, :added_by);
$$;

