CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_LABEL_COUNT(label STRING, delta INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.LABEL_INDEX t
USING (SELECT :label AS lbl, :delta AS d) s
ON t.LABEL = s.lbl
WHEN MATCHED THEN UPDATE SET COUNT = COUNT + s.d
WHEN NOT MATCHED THEN INSERT (IDX_ID, LABEL, COUNT) VALUES (UUID_STRING(), s.lbl, s.d);
$$;

