CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_TEMPLATE_REVIEW(template_id STRING, reviewer STRING, score FLOAT, comments STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_REVIEWS (REVIEW_ID, TEMPLATE_ID, REVIEWER, SCORE, COMMENTS)
VALUES (UUID_STRING(), :template_id, :reviewer, :score, :comments);
$$;

