CREATE OR REPLACE PROCEDURE DOCGEN.LOCK_TEMPLATE_VERSION(version_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_VERSION_LOCKS (LOCK_ID, TEMPLATE_VERSION_ID, LOCKED_BY)
VALUES (UUID_STRING(), :version_id, :locked_by);
$$;

