CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_VERSION_AUDIT(version_id STRING, changes VARIANT, audited_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_VERSION_AUDIT (AUDIT_ID, TEMPLATE_VERSION_ID, CHANGES, AUDITED_BY)
VALUES (UUID_STRING(), :version_id, :changes, :audited_by);
$$;

