CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_TAG_HISTORY(provider_id STRING, tag STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_TAGS_HISTORY (PTH_ID, PROVIDER_ID, TAG, ACTION)
VALUES (UUID_STRING(), :provider_id, :tag, :action);
$$;

