CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POLICY_TEMPLATE(name STRING, template VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_TEMPLATES (PT_ID, NAME, TEMPLATE)
VALUES (UUID_STRING(), :name, :template);
$$;

