CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COMPLIANCE_REVIEW(scope VARIANT, reviewer STRING, result STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_REVIEWS (REVIEW_ID, SCOPE, REVIEWER, RESULT, NOTES)
VALUES (UUID_STRING(), :scope, :reviewer, :result, :notes);
$$;

