CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_COMPLIANCE_FINDING(review_id STRING, severity STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_FINDINGS (FINDING_ID, REVIEW_ID, SEVERITY, DETAILS)
VALUES (UUID_STRING(), :review_id, :severity, :details);
$$;

