CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_EVIDENCE_ACCESS(bundle_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EVIDENCE_ACCESS_STATS t USING (SELECT :bundle_id AS bid) s ON t.BUNDLE_ID = s.bid
WHEN MATCHED THEN UPDATE SET ACCESS_COUNT = ACCESS_COUNT + 1, LAST_ACCESSED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (STAT_ID, BUNDLE_ID, ACCESS_COUNT, LAST_ACCESSED_AT) VALUES (UUID_STRING(), s.bid, 1, CURRENT_TIMESTAMP());
$$;

