CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RETENTION_POLICY(scope VARIANT, retention_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_RETENTION_POLICIES (POLICY_ID, SCOPE, RETENTION_DAYS)
VALUES (UUID_STRING(), :scope, :retention_days);
$$;

