CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETENTION_RUN(policy_id STRING, purged_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_RUNS (RUN_ID, POLICY_ID, PURGED_COUNT)
VALUES (UUID_STRING(), :policy_id, :purged_count);
$$;

