CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD_POLICY(name STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_POLICIES (HOLD_POLICY_ID, NAME, SCOPE)
VALUES (UUID_STRING(), :name, :scope);
$$;

