CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COUNTERSIGN_REQUEST(original_bundle_id STRING, counter_parties ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COUNTERSIGN_REQUESTS (COUNTER_ID, ORIGINAL_BUNDLE_ID, COUNTER_PARTIES)
VALUES (UUID_STRING(), :original_bundle_id, :counter_parties);
$$;

