CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_COUNTERSIGN_STATUS(counter_id STRING, party STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COUNTERSIGN_STATUS (STATUS_ID, COUNTER_ID, PARTY, STATUS)
VALUES (UUID_STRING(), :counter_id, :party, :status);
$$;

