CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_EVENT(session_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_EVENTS (EVENT_ID, SESSION_ID, EVENT_TYPE, PAYLOAD)
VALUES (UUID_STRING(), :session_id, :event_type, :payload);
$$;

