CREATE OR REPLACE PROCEDURE DOCGEN.ADD_CLASSIFICATION_RULE(name STRING, conditions VARIANT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLASSIFICATION_RULES (RULE_ID, NAME, CONDITIONS, ACTION)
VALUES (UUID_STRING(), :name, :conditions, :action);
$$;

