CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REDACTION_AUDIT(request_id STRING, rule_id STRING, redacted_fields VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_AUDIT (AUDIT_ID, REQUEST_ID, RULE_ID, REDACTED_FIELDS)
VALUES (UUID_STRING(), :request_id, :rule_id, :redacted_fields);
$$;

