CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BIOMETRIC_POLICY(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_POLICIES (POLICY_ID, NAME, RULES)
VALUES (UUID_STRING(), :name, :rules);
$$;

