CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_AUDIT(template_id STRING, action STRING, by_whom STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_AUDIT (AUDIT_ID, TEMPLATE_ID, ACTION, BY_WHOM)
VALUES (UUID_STRING(), :template_id, :action, :by_whom);
$$;

