CREATE OR REPLACE PROCEDURE DOCGEN.REQUEST_FORENSICS_EXPORT(bundle_id STRING, scope VARIANT, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FORENSICS_EXPORTS (EXPORT_ID, BUNDLE_ID, SCOPE, TARGET_STAGE, STATUS)
VALUES (UUID_STRING(), :bundle_id, :scope, :target_stage, 'PENDING');
$$;

