CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_RETRY_JOB(target_proc STRING, payload VARIANT, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETRY_QUEUE (QUEUE_ID, TARGET_PROC, PAYLOAD, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :target_proc, :payload, :next_attempt_at);
$$;

