CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETRY_BACKOFF(queue_id STRING, attempt INT, backoff_seconds INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETRY_BACKOFF_LOG (LOG_ID, QUEUE_ID, ATTEMPT, BACKOFF_SECONDS) VALUES (UUID_STRING(), :queue_id, :attempt, :backoff_seconds);
$$;

