CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_AUDIT(session_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_AUDIT (AUDIT_ID, SESSION_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :session_id, :action, :details);
$$;

