CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RATE_LIMIT_LOG(client_id STRING, endpoint STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RATE_LIMIT_LOGS (LOG_ID, CLIENT_ID, ENDPOINT, STATUS) VALUES (UUID_STRING(), :client_id, :endpoint, :status);
$$;

