CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACKNOWLEDGEMENT(entity_ref STRING, subject STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACKNOWLEDGEMENTS (ACK_ID, ENTITY_REF, SUBJECT) VALUES (UUID_STRING(), :entity_ref, :subject);
$$;

