CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONFIDENCE_SCORE(bundle_id STRING, metric_name STRING, value FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONFIDENCE_SCORES (SCORE_ID, BUNDLE_ID, METRIC_NAME, VALUE) VALUES (UUID_STRING(), :bundle_id, :metric_name, :value);
$$;

