CREATE OR REPLACE PROCEDURE DOCGEN.STORE_AI_EXPLANATION(request_id STRING, model_ref STRING, explanation VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AI_EXPLAINABILITY (EXPL_ID, REQUEST_ID, MODEL_REF, EXPLANATION) VALUES (UUID_STRING(), :request_id, :model_ref, :explanation);
$$;

