CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ENSEMBLE_ROUTE(name STRING, rules VARIANT, priority INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ENSEMBLE_ROUTES (ROUTE_ID, NAME, RULES, PRIORITY) VALUES (UUID_STRING(), :name, :rules, :priority);
$$;

