CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ENSEMBLE_LOG(route_id STRING, request_id STRING, selected_models ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ENSEMBLE_LOGS (LOG_ID, ROUTE_ID, REQUEST_ID, SELECTED_MODELS) VALUES (UUID_STRING(), :route_id, :request_id, :selected_models);
$$;

