CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_TELEMETRY(model_ref STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_TELEMETRY (TELE_ID, MODEL_REF, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :model_ref, :metric_name, :metric_value);
$$;

