CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_MODEL_REGISTRY_EVENT(model_ref STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_REGISTRY_EVENTS (EVENT_ID, MODEL_REF, EVENT_TYPE, PAYLOAD) VALUES (UUID_STRING(), :model_ref, :event_type, :payload);
$$;

