CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_MODEL_VERSION(model_ref STRING, version INT, artifact_ref STRING, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_VERSIONS (VERSION_ID, MODEL_REF, VERSION, ARTIFACT_REF, METADATA) VALUES (UUID_STRING(), :model_ref, :version, :artifact_ref, :metadata);
$$;

