CREATE OR REPLACE PROCEDURE DOCGEN.APPROVE_MODEL_VERSION(version_id STRING, approved_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_APPROVALS (APPROVAL_ID, VERSION_ID, APPROVED_BY, STATUS) VALUES (UUID_STRING(), :version_id, :approved_by, 'APPROVED');
$$;

