CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CANARY_METRIC(canary_id STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_CANARY_METRICS (METRIC_ID, CANARY_ID, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :canary_id, :metric_name, :metric_value);
$$;

