CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_USER_FEEDBACK(request_id STRING, user_id STRING, rating INT, comment STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_FEEDBACK (FEEDBACK_ID, REQUEST_ID, USER_ID, RATING, COMMENT) VALUES (UUID_STRING(), :request_id, :user_id, :rating, :comment);
$$;

