CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_ESCALATION(request_id STRING, reason STRING, raised_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATIONS (ESC_ID, REQUEST_ID, REASON, RAISED_BY) VALUES (UUID_STRING(), :request_id, :reason, :raised_by);
$$;

