CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESCALATION_ACTION(esc_id STRING, action_taken STRING, taken_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_ACTIONS (ACTION_ID, ESC_ID, ACTION_TAKEN, TAKEN_BY) VALUES (UUID_STRING(), :esc_id, :action_taken, :taken_by);
$$;

