CREATE OR REPLACE PROCEDURE DOCGEN.FILE_COMPLAINT(account_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLAINTS (COMPLAINT_ID, ACCOUNT_ID, DETAILS) VALUES (UUID_STRING(), :account_id, :details);
$$;

