CREATE OR REPLACE PROCEDURE DOCGEN.RESOLVE_COMPLAINT(complaint_id STRING, resolved_by STRING, resolution TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLAINT_RESOLUTIONS (RES_ID, COMPLAINT_ID, RESOLVED_BY, RESOLUTION) VALUES (UUID_STRING(), :complaint_id, :resolved_by, :resolution);
$$;

