CREATE OR REPLACE PROCEDURE DOCGEN.SHARE_AUDIT_ENTRY(audit_id STRING, shared_with STRING, share_method STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_SHARES (SHARE_ID, AUDIT_ID, SHARED_WITH, SHARE_METHOD) VALUES (UUID_STRING(), :audit_id, :shared_with, :share_method);
$$;

