CREATE OR REPLACE PROCEDURE DOCGEN.IMPORT_THIRDPARTY_CERT(provider_id STRING, cert_pem CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRDPARTY_CERTIFICATES (CERT_ID, PROVIDER_ID, CERT_PEM) VALUES (UUID_STRING(), :provider_id, :cert_pem);
$$;

