CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CERT_FINGERPRINT(cert_id STRING, fingerprint STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERT_FINGERPRINTS (FINGERPRINT_ID, CERT_ID, FINGERPRINT) VALUES (UUID_STRING(), :cert_id, :fingerprint);
$$;

