CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CRL_ENTRY(cert_id STRING, revoked_at TIMESTAMP_LTZ, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CRL_INDEX (CRL_ID, CERT_ID, REVOKED_AT, DETAILS) VALUES (UUID_STRING(), :cert_id, :revoked_at, :details);
$$;

