CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BLOCKCHAIN_ANCHOR(bundle_id STRING, tx_id STRING, network STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_ANCHORS (ANCHOR_ID, BUNDLE_ID, TX_ID, NETWORK) VALUES (UUID_STRING(), :bundle_id, :tx_id, :network);
$$;

