CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ANCHOR_RECONCILE(anchor_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHOR_RECONCILE (RECON_ID, ANCHOR_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :anchor_id, :status, :details);
$$;

