CREATE OR REPLACE PROCEDURE DOCGEN.STORE_USER_AGENT(user_agent STRING, normalized VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.USER_AGENTS t USING (SELECT :user_agent AS ua, :normalized AS n) s ON t.USER_AGENT = s.ua WHEN MATCHED THEN UPDATE SET NORMALIZED = s.n WHEN NOT MATCHED THEN INSERT (UA_ID, USER_AGENT, NORMALIZED) VALUES (UUID_STRING(), s.ua, s.n);
$$;

