CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEVICE_RISK_SCORE(fp_id STRING, risk_score FLOAT, reason VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_RISK_SCORES (RISK_ID, FP_ID, RISK_SCORE, REASON) VALUES (UUID_STRING(), :fp_id, :risk_score, :reason);
$$;

