CREATE OR REPLACE PROCEDURE DOCGEN.FLAG_FRAUDULENT_SIGNER(signer_id STRING, flag_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_FLAGS (FLAG_ID, SIGNER_ID, FLAG_TYPE, DETAILS) VALUES (UUID_STRING(), :signer_id, :flag_type, :details);
$$;

