CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATION_LOG(subject STRING, operation STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATION_LOGS (OP_ID, SUBJECT, OPERATION, PAYLOAD) VALUES (UUID_STRING(), :subject, :operation, :payload);
$$;

