CREATE OR REPLACE PROCEDURE DOCGEN.INITIATE_DSR_EXPORT(dsr_id STRING, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DSR_EXPORTS (EXPORT_ID, DSR_ID, TARGET_STAGE, STATUS) VALUES (UUID_STRING(), :dsr_id, :target_stage, 'PENDING');
$$;

