CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCESS_REVIEW(queue_id STRING, reviewer STRING, outcome STRING, notes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_LOGS (LOG_ID, QUEUE_ID, REVIEWER, OUTCOME, NOTES) VALUES (UUID_STRING(), :queue_id, :reviewer, :outcome, :notes);
$$;

