CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SLA_ALERT_RULE(metric STRING, operator STRING, threshold VARIANT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_ALERT_RULES (RULE_ID, METRIC, OPERATOR, THRESHOLD, ACTION) VALUES (UUID_STRING(), :metric, :operator, :threshold, :action);
$$;

