CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THREAT_SIGNAL(subject STRING, signal_type STRING, score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_SIGNALS (SIGNAL_ID, SUBJECT, SIGNAL_TYPE, SCORE, DETAILS) VALUES (UUID_STRING(), :subject, :signal_type, :score, :details);
$$;

