CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DOCUMENT_SNAPSHOT(document_id STRING, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_SNAPSHOTS (SNAP_ID, DOCUMENT_ID, LOCATION, META) VALUES (UUID_STRING(), :document_id, :location, :meta);
$$;

