CREATE OR REPLACE PROCEDURE DOCGEN.ADD_SNAPSHOT_REFERENCE(snap_id STRING, ref_type STRING, ref_value STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SNAPSHOT_REFERENCES (REF_ID, SNAP_ID, REF_TYPE, REF_VALUE) VALUES (UUID_STRING(), :snap_id, :ref_type, :ref_value);
$$;

