CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_CHECKSUM(document_id STRING, algorithm STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_CHECKSUMS (CHK_ID, DOCUMENT_ID, ALGORITHM, CHECKSUM) VALUES (UUID_STRING(), :document_id, :algorithm, :checksum);
$$;

