CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HASH_ANCHOR(hash STRING, method STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HASH_ANCHORS (ANCHOR_ID, HASH, METHOD) VALUES (UUID_STRING(), :hash, :method);
$$;

