CREATE OR REPLACE PROCEDURE DOCGEN.ADD_STAKEHOLDER_CONTACT(account_id STRING, name STRING, email STRING, role STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.STAKEHOLDER_CONTACTS (CONTACT_ID, ACCOUNT_ID, NAME, EMAIL, ROLE) VALUES (UUID_STRING(), :account_id, :name, :email, :role);
$$;

