CREATE OR REPLACE PROCEDURE DOCGEN.ADD_CONTRACT_SIGNATORY(contract_id STRING, signer_id STRING, role STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONTRACT_SIGNATORIES (SIGN_ID, CONTRACT_ID, SIGNER_ID, ROLE) VALUES (UUID_STRING(), :contract_id, :signer_id, :role);
$$;

