CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TIMELINE_EVENT(bundle_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TIMELINE_EVENTS (EVENT_ID, BUNDLE_ID, EVENT_TYPE, PAYLOAD) VALUES (UUID_STRING(), :bundle_id, :event_type, :payload);
$$;

