CREATE OR REPLACE PROCEDURE DOCGEN.LOCK_DOCUMENT(document_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_LOCKS (LOCK_ID, DOCUMENT_ID, LOCKED_BY) VALUES (UUID_STRING(), :document_id, :locked_by);
$$;

