CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_TEMPLATE_ACCESS(template_id STRING, role_or_user STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_ACCESS_CONTROLS (TAC_ID, TEMPLATE_ID, ROLE_OR_USER, PERMISSIONS) VALUES (UUID_STRING(), :template_id, :role_or_user, :permissions);
$$;

