CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ALERT_SUPPRESSION(name STRING, scope VARIANT, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_SUPPRESSIONS (SUPPRESS_ID, NAME, SCOPE, EXPIRES_AT) VALUES (UUID_STRING(), :name, :scope, :expires_at);
$$;

