CREATE OR REPLACE PROCEDURE DOCGEN.SET_REQUEST_RETENTION_STATE(request_id STRING, state STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.REQUEST_RETENTION_STATE t USING (SELECT :request_id AS rid, :state AS st) s ON t.REQUEST_ID = s.rid WHEN MATCHED THEN UPDATE SET STATE = s.st, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (STATE_ID, REQUEST_ID, STATE) VALUES (UUID_STRING(), s.rid, s.st);
$$;

