CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REVIEW_TEMPLATE(name STRING, definition VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_TEMPLATES (ART_ID, NAME, DEFINITION) VALUES (UUID_STRING(), :name, :definition);
$$;

