CREATE OR REPLACE PROCEDURE DOCGEN.ADD_FINGERPRINT_WATCH(fingerprint STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FINGERPRINT_WATCHLIST (WATCH_ID, FINGERPRINT, REASON) VALUES (UUID_STRING(), :fingerprint, :reason);
$$;

