CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACTIVITY_METRIC(metric_name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACTIVITY_RATE_METRICS (METRIC_ID, METRIC_NAME, VALUE) VALUES (UUID_STRING(), :metric_name, :value);
$$;

