CREATE OR REPLACE PROCEDURE DOCGEN.SET_ACCOUNT_SECURITY_POLICY(account_id STRING, policy VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ACCOUNT_SECURITY_POLICIES t USING (SELECT :account_id AS aid, :policy AS p) s ON t.ACCOUNT_ID = s.aid WHEN MATCHED THEN UPDATE SET POLICY = s.p, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (POLICY_ID, ACCOUNT_ID, POLICY) VALUES (UUID_STRING(), s.aid, s.p);
$$;

