CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SECURITY_EXCEPTION(account_id STRING, reason STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_SECURITY_EXCEPTIONS (EX_ID, ACCOUNT_ID, REASON, EXPIRES_AT) VALUES (UUID_STRING(), :account_id, :reason, :expires_at);
$$;

