CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PRIVACY_CONTROL(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_CONTROLS (CONTROL_ID, NAME, RULES) VALUES (UUID_STRING(), :name, :rules);
$$;

