CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIVACY_AUDIT(control_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_AUDITS (AUDIT_ID, CONTROL_ID, RESULT) VALUES (UUID_STRING(), :control_id, :result);
$$;

