CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_AUDIT(policy_id STRING, changed_by STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_AUDIT (AUDIT_ID, POLICY_ID, CHANGED_BY, CHANGES) VALUES (UUID_STRING(), :policy_id, :changed_by, :changes);
$$

