CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ROLE_MAPPING(role_name STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ROLE_MAPPINGS t USING (SELECT :role_name AS rn, :permissions AS p) s ON t.ROLE_NAME = s.rn WHEN MATCHED THEN UPDATE SET PERMISSIONS = s.p WHEN NOT MATCHED THEN INSERT (MAP_ID, ROLE_NAME, PERMISSIONS) VALUES (UUID_STRING(), s.rn, s.p);
$$

