CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ALERT_DEFINITION(name STRING, condition VARIANT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_DEFINITIONS (ALERT_DEF_ID, NAME, CONDITION, ACTION) VALUES (UUID_STRING(), :name, :condition, :action);
$$

