CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_OPERATION_TASK(queue_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATION_TASKS (TASK_ID, QUEUE_ID, PAYLOAD) VALUES (UUID_STRING(), :queue_id, :payload);
$$

