CREATE OR REPLACE PROCEDURE DOCGEN.START_BATCH_RUN(name STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_RUNS (RUN_ID, NAME, STATUS, STARTED_AT, META) VALUES (UUID_STRING(), :name, 'RUNNING', CURRENT_TIMESTAMP(), :meta);
$$

