CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BATCH_STEP_LOG(run_id STRING, step_name STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_STEP_LOGS (STEP_LOG_ID, RUN_ID, STEP_NAME, STATUS, DETAILS) VALUES (UUID_STRING(), :run_id, :step_name, :status, :details);
$$

