CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_METRICS_ALERT(metric_name STRING, threshold VARIANT, observed VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.METRICS_ALERT_HISTORY (ALERT_ID, METRIC_NAME, THRESHOLD, OBSERVED) VALUES (UUID_STRING(), :metric_name, :threshold, :observed);
$$

