CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HEALTH_CHECK(check_name STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HEALTH_CHECK_HISTORY (CHECK_ID, CHECK_NAME, STATUS, DETAILS) VALUES (UUID_STRING(), :check_name, :status, :details);
$$

