CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SERVICE(name STRING, description STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_CATALOG (SERVICE_ID, NAME, DESCRIPTION, CONFIG) VALUES (UUID_STRING(), :name, :description, :config);
$$

