CREATE OR REPLACE PROCEDURE DOCGEN.SUBSCRIBE_INTEGRATION(integration STRING, callback_url STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INTEGRATION_SUBSCRIPTIONS (SUB_ID, INTEGRATION, CALLBACK_URL, SECRET_HASH) VALUES (UUID_STRING(), :integration, :callback_url, :secret_hash);
$$

