CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INTEGRATION_SUB_LOG(sub_id STRING, event_type STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INTEGRATION_SUBS_LOGS (LOG_ID, SUB_ID, EVENT_TYPE, STATUS) VALUES (UUID_STRING(), :sub_id, :event_type, :status);
$$

