CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SAMPLING_JOB(name STRING, query STRING, schedule VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SAMPLING_JOBS (JOB_ID, NAME, QUERY, SCHEDULE) VALUES (UUID_STRING(), :name, :query, :schedule);
$$

