CREATE OR REPLACE PROCEDURE DOCGEN.AGGREGATE_DOCUMENT_ACTIVITY()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.8'
HANDLER='handler'
AS
$$
# staged at @~/procedures/aggregate_document_activity.py
$$

