CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_USAGE_FORECAST(account_id STRING, forecast_month DATE, estimate VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_FORECASTS (FORECAST_ID, ACCOUNT_ID, FORECAST_MONTH, ESTIMATE) VALUES (UUID_STRING(), :account_id, :forecast_month, :estimate);
$$

