CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BILLING_FORECAST_SNAPSHOT(account_id STRING, snapshot VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_FORECAST_SNAPSHOTS (SNAP_ID, ACCOUNT_ID, SNAPSHOT) VALUES (UUID_STRING(), :account_id, :snapshot);
$$

