CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCOUNT_HEALTH_SCORE(account_id STRING, score FLOAT, drivers VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_HEALTH_SCORES (SCORE_ID, ACCOUNT_ID, SCORE, DRIVERS) VALUES (UUID_STRING(), :account_id, :score, :drivers);
$$

