CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_COST(provider_id STRING, cost_metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_COSTS (COST_ID, PROVIDER_ID, COST_METRICS) VALUES (UUID_STRING(), :provider_id, :cost_metrics);
$$

