CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_PERFORMANCE(provider_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_PERFORMANCE (PERF_ID, PROVIDER_ID, METRICS) VALUES (UUID_STRING(), :provider_id, :metrics);
$$

