CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_PROVIDER_PENALTY(provider_id STRING, reason STRING, amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_PENALTIES (PEN_ID, PROVIDER_ID, REASON, AMOUNT) VALUES (UUID_STRING(), :provider_id, :reason, :amount);
$$

