CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PARTNER_SYNC_LOG(partner_id STRING, action STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_SYNC_LOGS (LOG_ID, PARTNER_ID, ACTION, STATUS, DETAILS) VALUES (UUID_STRING(), :partner_id, :action, :status, :details);
$$

