CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PARTNER_WEBHOOK(partner_id STRING, event_type STRING, callback_url STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_WEBHOOKS (WEBHOOK_ID, PARTNER_ID, EVENT_TYPE, CALLBACK_URL, SECRET_HASH) VALUES (UUID_STRING(), :partner_id, :event_type, :callback_url, :secret_hash);
$$

