CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_THIRDPARTY_SYNC(partner_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRDPARTY_SYNC_QUEUE (SYNC_ID, PARTNER_ID, PAYLOAD) VALUES (UUID_STRING(), :partner_id, :payload);
$$

