CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THIRDPARTY_SYNC_LOG(sync_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRDPARTY_SYNC_LOGS (LOG_ID, SYNC_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :sync_id, :status, :response);
$$

