CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_USAGE_ALARM(account_id STRING, metric STRING, threshold VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_ALARMS (ALARM_ID, ACCOUNT_ID, METRIC, THRESHOLD) VALUES (UUID_STRING(), :account_id, :metric, :threshold);
$$

