CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_USAGE_ALARM_LOG(alarm_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_ALARM_LOGS (LOG_ID, ALARM_ID, PAYLOAD) VALUES (UUID_STRING(), :alarm_id, :payload);
$$

