CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_REQUEST_TAG_SUMMARY(request_id STRING, tag_counts VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.REQUEST_TAG_SUMMARY t USING (SELECT :request_id AS rid, :tag_counts AS tc) s ON t.REQUEST_ID = s.rid WHEN MATCHED THEN UPDATE SET TAG_COUNTS = s.tc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SUMMARY_ID, REQUEST_ID, TAG_COUNTS) VALUES (UUID_STRING(), s.rid, s.tc);
$$

