CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TAGGING_RULE(name STRING, conditions VARIANT, actions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TAGGING_RULES (RULE_ID, NAME, CONDITIONS, ACTIONS) VALUES (UUID_STRING(), :name, :conditions, :actions);
$$

