CREATE OR REPLACE PROCEDURE DOCGEN.STORE_AD_HOC_QUERY(name STRING, query_text STRING, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AD_HOC_QUERIES (QUERY_ID, NAME, QUERY_TEXT, CREATED_BY) VALUES (UUID_STRING(), :name, :query_text, :created_by);
$$

