CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SAVED_REPORT(name STRING, definition VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SAVED_REPORTS (REPORT_ID, NAME, DEFINITION, OWNER) VALUES (UUID_STRING(), :name, :definition, :owner);
$$

