CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REPORT_RUN(report_id STRING, status STRING, output_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPORT_RUNS (RUN_ID, REPORT_ID, STATUS, OUTPUT_LOCATION) VALUES (UUID_STRING(), :report_id, :status, :output_location);
$$

