CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTIFICATION_PREF_CHANGE(account_id STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_PREFERENCES_HISTORY (HP_ID, ACCOUNT_ID, PREFS) VALUES (UUID_STRING(), :account_id, :prefs);
$$

