CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_RATE_USAGE(client_id STRING, endpoint STRING, count INT, window_start TIMESTAMP_LTZ, window_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_RATE_USAGE (USAGE_ID, CLIENT_ID, ENDPOINT, COUNT, WINDOW_START, WINDOW_END) VALUES (UUID_STRING(), :client_id, :endpoint, :count, :window_start, :window_end);
$$

