CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ROTATION(key_ref STRING, rotated_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_HISTORY (ROT_ID, KEY_REF, ROTATED_BY, META) VALUES (UUID_STRING(), :key_ref, :rotated_by, :meta);
$$

