CREATE OR REPLACE PROCEDURE DOCGEN.SET_SERVICE_QUOTA(service_id STRING, limits VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SERVICE_QUOTAS t USING (SELECT :service_id AS sid, :limits AS l) s ON t.SERVICE_ID = s.sid WHEN MATCHED THEN UPDATE SET LIMITS = s.l, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (QUOTA_ID, SERVICE_ID, LIMITS) VALUES (UUID_STRING(), s.sid, s.l);
$$

