CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_QUOTA_BREACH(quota_id STRING, account_id STRING, usage VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_BREACHES (BREACH_ID, QUOTA_ID, ACCOUNT_ID, USAGE) VALUES (UUID_STRING(), :quota_id, :account_id, :usage);
$$

