CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_KEY_AUDIT(api_key_id STRING, action STRING, by_user STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEY_AUDIT (AUDIT_ID, API_KEY_ID, ACTION, BY_USER) VALUES (UUID_STRING(), :api_key_id, :action, :by_user);
$$

