CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SESSION_TOKEN(session_id STRING, token STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_TOKENS (ST_ID, SESSION_ID, TOKEN, EXPIRES_AT) VALUES (UUID_STRING(), :session_id, :token, :expires_at);
$$

