CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_TEMPLATE_USAGE(template_id STRING, delta INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_USAGE_STATS t USING (SELECT :template_id AS tid, :delta AS d) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET USAGE_COUNT = USAGE_COUNT + s.d, LAST_USED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (TUS_ID, TEMPLATE_ID, USAGE_COUNT, LAST_USED_AT) VALUES (UUID_STRING(), s.tid, s.d, CURRENT_TIMESTAMP());
$$

