CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_TEMPLATE_TAG_COUNT(tag STRING, delta INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_TAG_INDEX t USING (SELECT :tag AS tg, :delta AS d) s ON t.TAG = s.tg WHEN MATCHED THEN UPDATE SET COUNT = COUNT + s.d WHEN NOT MATCHED THEN INSERT (INDEX_ID, TAG, COUNT) VALUES (UUID_STRING(), s.tg, s.d);
$$

