CREATE OR REPLACE PROCEDURE DOCGEN.SHARE_TEMPLATE(template_id STRING, shared_to STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_SHARES (SHARE_ID, TEMPLATE_ID, SHARED_TO, PERMISSIONS) VALUES (UUID_STRING(), :template_id, :shared_to, :permissions);
$$

