CREATE OR REPLACE PROCEDURE DOCGEN.ADD_DOCUMENT_ANNOTATION(bundle_id STRING, annotator STRING, content VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_ANNOTATIONS (ANNOT_ID, BUNDLE_ID, ANNOTATOR, CONTENT) VALUES (UUID_STRING(), :bundle_id, :annotator, :content);
$$

