CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_VIEW_ACCESS(view_id STRING, user_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VIEW_ACCESS_LOGS (LOG_ID, VIEW_ID, USER_ID) VALUES (UUID_STRING(), :view_id, :user_id);
$$

