CREATE OR REPLACE PROCEDURE DOCGEN.STORE_SAVED_SEARCH(name STRING, query STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SAVED_SEARCHES (SEARCH_ID, NAME, QUERY, OWNER) VALUES (UUID_STRING(), :name, :query, :owner);
$$

