CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SEARCH_HISTORY(search_id STRING, ran_by STRING, result_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_HISTORY (HISTORY_ID, SEARCH_ID, RAN_BY, RESULT_COUNT) VALUES (UUID_STRING(), :search_id, :ran_by, :result_count);
$$

