CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SEARCH_TELEMETRY(search_id STRING, latency_ms INT, hit_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_TELEMETRY (TELE_ID, SEARCH_ID, LATENCY_MS, HIT_COUNT) VALUES (UUID_STRING(), :search_id, :latency_ms, :hit_count);
$$

