CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INDEX_MAINTENANCE_LOG(task_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_MAINTENANCE_LOGS (LOG_ID, TASK_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :task_id, :status, :details);
$$

