CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SHARD_LOAD(manifest_id STRING, shard_ref STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SHARD_LOAD_HISTORY (LOAD_ID, MANIFEST_ID, SHARD_REF, STATUS) VALUES (UUID_STRING(), :manifest_id, :shard_ref, :status);
$$

