CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INDEX_QUERY_METRIC(index_name STRING, query_text STRING, latency_ms INT, result_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_QUERY_METRICS (METRIC_ID, INDEX_NAME, QUERY_TEXT, LATENCY_MS, RESULT_COUNT) VALUES (UUID_STRING(), :index_name, :query_text, :latency_ms, :result_count);
$$

