CREATE OR REPLACE PROCEDURE DOCGEN.SET_INDEX_CAPACITY_PLAN(index_name STRING, capacity VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.INDEX_CAPACITY_PLANS t USING (SELECT :index_name AS iname, :capacity AS c) s ON t.INDEX_NAME = s.iname WHEN MATCHED THEN UPDATE SET CAPACITY = s.c, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PLAN_ID, INDEX_NAME, CAPACITY) VALUES (UUID_STRING(), s.iname, s.c);
$$

