CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INDEX_REBALANCE_LOG(op_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_REBALANCE_LOGS (LOG_ID, OP_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :op_id, :status, :details);
$$

