CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKFILL_LOG(backfill_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKFILL_LOGS (LOG_ID, BACKFILL_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :backfill_id, :status, :details);
$$

