CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ROUTING_LOG(rule_id STRING, request_id STRING, selected_target STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROUTING_LOGS (LOG_ID, RULE_ID, REQUEST_ID, SELECTED_TARGET) VALUES (UUID_STRING(), :rule_id, :request_id, :selected_target);
$$

