CREATE OR REPLACE PROCEDURE DOCGEN.SET_REQUEST_PRIORITY(request_id STRING, priority INT, set_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REQUEST_PRIORITY (PRIORITY_ID, REQUEST_ID, PRIORITY, SET_BY) VALUES (UUID_STRING(), :request_id, :priority, :set_by);
$$

