CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PRIORITY_REQUEST(request_id STRING, priority INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIORITY_QUEUE (Q_ID, REQUEST_ID, PRIORITY) VALUES (UUID_STRING(), :request_id, :priority);
$$

