CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIORITY_DISPATCH(q_id STRING, dispatched_to STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIORITY_DISPATCH_LOGS (LOG_ID, Q_ID, DISPATCHED_TO, STATUS) VALUES (UUID_STRING(), :q_id, :dispatched_to, :status);
$$

