CREATE OR REPLACE PROCEDURE DOCGEN.ISSUE_COMPLIANCE_CERTIFICATE(name STRING, issued_to STRING, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CERTIFICATES (CERT_ID, NAME, ISSUED_TO, EXPIRES_AT, META) VALUES (UUID_STRING(), :name, :issued_to, :expires_at, :meta);
$$

