CREATE OR REPLACE PROCEDURE DOCGEN.MARK_BUNDLE_FINALIZED(bundle_id STRING, storage_location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FINALIZED_BUNDLES (BUNDLE_ID, DOCUMENT_ID, STORAGE_LOCATION, META) SELECT :bundle_id, DOCUMENT_ID, :storage_location, :meta FROM DOCGEN.SIGNATURE_EVIDENCE_BUNDLES WHERE BUNDLE_ID = :bundle_id;
$$

