CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FINALIZATION_HISTORY(bundle_id STRING, finalized_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FINALIZATION_HISTORY (FH_ID, BUNDLE_ID, FINALIZED_BY, META) VALUES (UUID_STRING(), :bundle_id, :finalized_by, :meta);
$$;

