CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ESCALATION_POLICY(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_POLICIES (POLICY_ID, NAME, RULES) VALUES (UUID_STRING(), :name, :rules);
$$

