CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CALLBACK_LOG(callback_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_LOGS (LOG_ID, CALLBACK_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :callback_id, :status, :response);
$$;

