CREATE OR REPLACE PROCEDURE DOCGEN.SEND_ESCALATION_NOTIFICATION(esc_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.8'
HANDLER='handler'
AS
$$
# staged at @~/procedures/send_escalation_notification.py
$$

