CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DOCUMENT_VERSION(document_id STRING, version_number INT, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_VERSIONS (VERSION_ID, DOCUMENT_ID, VERSION_NUMBER, LOCATION, META) VALUES (UUID_STRING(), :document_id, :version_number, :location, :meta);
$$;

