CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_VERSION_AUDIT(version_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERSION_AUDIT (AUDIT_ID, VERSION_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :version_id, :action, :performed_by, :details);
$$;

