CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EXPORT_JOB(job_type STRING, scope VARIANT, target_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_JOBS (JOB_ID, JOB_TYPE, SCOPE, TARGET_LOCATION) VALUES (UUID_STRING(), :job_type, :scope, :target_location);
$$;

