CREATE OR REPLACE PROCEDURE DOCGEN.ESCALATE_INCIDENT(incident_id STRING, escalated_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_ESCALATIONS (IE_ID, INCIDENT_ID, ESCALATED_TO) VALUES (UUID_STRING(), :incident_id, :escalated_to);
$$

