CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_ACCESS(subject STRING, resource_ref STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_GRANTS (GRANT_ID, SUBJECT, RESOURCE_REF, PERMISSIONS) VALUES (UUID_STRING(), :subject, :resource_ref, :permissions);
$$;

