CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_ACCESS(grant_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVOCATIONS (REVOC_ID, GRANT_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :grant_id, :revoked_by, :reason);
$$;

