CREATE OR REPLACE PROCEDURE DOCGEN.CLEANUP_OLD_SNAPSHOTS(retention_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DELETE FROM DOCGEN.DOCUMENT_SNAPSHOTS WHERE SNAPSHOT_AT < DATEADD(day, -:retention_days, CURRENT_TIMESTAMP());
$$

