CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REVIEW_POLICY(name STRING, rules VARIANT, schedule VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_POLICIES (POLICY_ID, NAME, RULES, SCHEDULE) VALUES (UUID_STRING(), :name, :rules, :schedule);
$$;

