CREATE OR REPLACE PROCEDURE DOCGEN.PURGE_RETENTION_EXCEPTIONS(older_than_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DELETE FROM DOCGEN.RETENTION_EXCEPTIONS WHERE CREATED_AT < DATEADD(day, -:older_than_days, CURRENT_TIMESTAMP());
$$

