CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PRIVACY_REQUEST(subject STRING, request_type STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUESTS (REQUEST_ID, SUBJECT, REQUEST_TYPE, META) VALUES (UUID_STRING(), :subject, :request_type, :meta);
$$;

