CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIVACY_REQUEST_LOG(request_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUEST_LOGS (LOG_ID, REQUEST_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :request_id, :action, :details);
$$;

