CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT(subject STRING, consent_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_REGISTRY (CONSENT_ID, SUBJECT, CONSENT_TYPE, DETAILS) VALUES (UUID_STRING(), :subject, :consent_type, :details);
$$;

