CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD(target_ref STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLDS (HOLD_ID, TARGET_REF, REASON) VALUES (UUID_STRING(), :target_ref, :reason);
$$

