CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_CERT_REQUEST(subject STRING, requested_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_CERT_REQUESTS (REQ_ID, SUBJECT, REQUESTED_BY, META) VALUES (UUID_STRING(), :subject, :requested_by, :meta);
$$;

