CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LEGAL_HOLD_AUDIT(hold_id STRING, action STRING, by_user STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_AUDIT (AUDIT_ID, HOLD_ID, ACTION, BY_USER) VALUES (UUID_STRING(), :hold_id, :action, :by_user);
$$

