CREATE OR REPLACE PROCEDURE DOCGEN.INITIATE_RETENTION_EXPORT(scope VARIANT, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_EXPORT_REQUESTS (REQ_ID, SCOPE, TARGET_STAGE) VALUES (UUID_STRING(), :scope, :target_stage);
$$

