CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETENTION_EXPORT_LOG(req_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_EXPORT_LOGS (LOG_ID, REQ_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :req_id, :status, :details);
$$

