CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SYSTEM_CONFIG(conf_key STRING, conf_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SYSTEM_CONFIG t USING (SELECT :conf_key AS ck, :conf_value AS cv) s ON t.CONF_KEY = s.ck WHEN MATCHED THEN UPDATE SET CONF_VALUE = s.cv, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONF_KEY, CONF_VALUE) VALUES (s.ck, s.cv);
$$;

