CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIVACY_REQUEST_LOG(pr_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUEST_LOGS (LOG_ID, PR_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :pr_id, :action, :details);
$$

