CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REVIEW_TEAM(name STRING, members ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_TEAMS (TEAM_ID, NAME, MEMBERS) VALUES (UUID_STRING(), :name, :members);
$$

