CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ACTIVITY_EXPORT(scope VARIANT, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACTIVITY_EXPORT_QUEUE (EQ_ID, SCOPE, TARGET_STAGE) VALUES (UUID_STRING(), :scope, :target_stage);
$$;

