CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCESS_REVIEW_TEAM_LOG(team_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_TEAM_LOGS (LOG_ID, TEAM_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :team_id, :action, :details);
$$

