CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACTIVITY_EXPORT_LOG(eq_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACTIVITY_EXPORT_LOGS (LOG_ID, EQ_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :eq_id, :status, :details);
$$;

