CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ARCHIVE_MANIFEST(target_stage STRING, objects VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_MANIFEST (MANIFEST_ID, TARGET_STAGE, OBJECTS) VALUES (UUID_STRING(), :target_stage, :objects);
$$;

