CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ROLE_LOG(assign_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ROLE_LOGS (LOG_ID, ASSIGN_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :assign_id, :action, :details);
$$

