CREATE OR REPLACE PROCEDURE DOCGEN.SET_RETAIN_FLAG(target_ref STRING, reason STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETAIN_FLAGS (FLAG_ID, TARGET_REF, REASON, EXPIRES_AT) VALUES (UUID_STRING(), :target_ref, :reason, :expires_at);
$$;

