CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ADMIN_CONFIGURATION(name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ADMIN_CONFIGURATIONS t USING (SELECT :name AS nm, :value AS v) s ON t.NAME = s.nm WHEN MATCHED THEN UPDATE SET VALUE = s.v, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, NAME, VALUE) VALUES (UUID_STRING(), s.nm, s.v);
$$

