CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETAIN_FLAG_LOG(flag_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETAIN_FLAG_LOGS (LOG_ID, FLAG_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :flag_id, :action, :details);
$$;

