CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD_REQUEST(account_id STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_REQUESTS (HOLD_ID, ACCOUNT_ID, SCOPE) VALUES (UUID_STRING(), :account_id, :scope);
$$;

