CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_ADMIN_HEALTHCHECK(name STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ADMIN_HEALTHCHECKS t USING (SELECT :name AS nm, :status AS st, :details AS d) s ON t.NAME = s.nm WHEN MATCHED THEN UPDATE SET STATUS = s.st, DETAILS = s.d, CHECKED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CHECK_ID, NAME, STATUS, DETAILS) VALUES (UUID_STRING(), s.nm, s.st, s.d);
$$

