CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SUPPORT_TICKET_LOG(ticket_id STRING, action STRING, by_user STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_TICKET_LOGS (LOG_ID, TICKET_ID, ACTION, BY_USER) VALUES (UUID_STRING(), :ticket_id, :action, :by_user);
$$

