CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_MAINTENANCE_WINDOW(name STRING, window_def VARIANT, active BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS (WINDOW_ID, NAME, WINDOW_DEF, ACTIVE) VALUES (UUID_STRING(), :name, :window_def, :active);
$$

