CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MAINTENANCE_LOG(window_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_LOGS (LOG_ID, WINDOW_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :window_id, :action, :details);
$$

