CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ROLLBACK(deploy_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROLLBACKS (ROLLBACK_ID, DEPLOY_ID, REASON) VALUES (UUID_STRING(), :deploy_id, :reason);
$$

