CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_OBJECT_LOCK(object_ref STRING, locked_by STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OBJECT_LOCKS (LOCK_ID, OBJECT_REF, LOCKED_BY, EXPIRES_AT)
VALUES (UUID_STRING(), :object_ref, :locked_by, :expires_at);
$$

