CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REFUND_REQUEST(account_id STRING, billing_run_id STRING, amount NUMBER, currency STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REFUND_REQUESTS (REFUND_ID, ACCOUNT_ID, BILLING_RUN_ID, AMOUNT, CURRENCY, META)
VALUES (UUID_STRING(), :account_id, :billing_run_id, :amount, :currency, :meta);
$$

