CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REFUND_AUDIT(refund_id STRING, action STRING, action_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REFUND_AUDIT (AUDIT_ID, REFUND_ID, ACTION, ACTION_BY, DETAILS)
VALUES (UUID_STRING(), :refund_id, :action, :action_by, :details);
$$

