CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DISPUTE_LOG(dispute_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DISPUTE_LOGS (LOG_ID, DISPUTE_ID, ACTION, PERFORMED_BY, DETAILS)
VALUES (UUID_STRING(), :dispute_id, :action, :performed_by, :details);
$$

