CREATE OR REPLACE PROCEDURE DOCGEN.RUN_AML_CHECK(subject_ref STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AML_CHECKS (AML_ID, SUBJECT_REF, CHECK_RESULT)
VALUES (UUID_STRING(), :subject_ref, :result);
$$

