CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_SANCTIONS_LIST(list_id STRING, name STRING, source STRING, last_updated TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SANCTIONS_LISTS t USING (SELECT :list_id AS lid, :name AS nm, :source AS src, :last_updated AS lu) s ON t.LIST_ID = s.lid WHEN MATCHED THEN UPDATE SET NAME = s.nm, SOURCE = s.src, LAST_UPDATED = s.lu WHEN NOT MATCHED THEN INSERT (LIST_ID, NAME, SOURCE, LAST_UPDATED) VALUES (s.lid, s.nm, s.src, s.lu);
$$

