CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_IDENTITY_PROVIDER(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IDENTITY_PROVIDERS (PROVIDER_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

