CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_IDENTITY_PROVIDER_LOG(provider_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IDENTITY_PROVIDER_LOGS (LOG_ID, PROVIDER_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :provider_id, :action, :details);
$$

