CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_DEVICE_TRUST(device_hash STRING, subject_ref STRING, trust_level STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_TRUSTS (TRUST_ID, DEVICE_HASH, SUBJECT_REF, TRUST_LEVEL) VALUES (UUID_STRING(), :device_hash, :subject_ref, :trust_level);
$$

