CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_TEMPLATE(subject_ref STRING, template_hash STRING, template_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES (TEMPLATE_ID, SUBJECT_REF, TEMPLATE_HASH, TEMPLATE_TYPE) VALUES (UUID_STRING(), :subject_ref, :template_hash, :template_type);
$$

