CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH(template_id STRING, score FLOAT, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCHES (MATCH_ID, TEMPLATE_ID, SCORE, META) VALUES (UUID_STRING(), :template_id, :score, :meta);
$$

