CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FRAUD_SCORE(subject_ref STRING, score FLOAT, reason VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_SCORES (SCORE_ID, SUBJECT_REF, SCORE, REASON) VALUES (UUID_STRING(), :subject_ref, :score, :reason);
$$

