CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FRAUD_ALERT(subject_ref STRING, score FLOAT, actions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_ALERTS (ALERT_ID, SUBJECT_REF, SCORE, ACTIONS) VALUES (UUID_STRING(), :subject_ref, :score, :actions);
$$

