CREATE OR REPLACE PROCEDURE DOCGEN.STORE_DEVICE_FINGERPRINT(subject_ref STRING, fp_hash STRING, fp_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_FINGERPRINTS (FP_ID, SUBJECT_REF, FP_HASH, FP_META) VALUES (UUID_STRING(), :subject_ref, :fp_hash, :fp_meta);
$$

