CREATE OR REPLACE PROCEDURE DOCGEN.STORE_SESSION_ARTIFACT(session_id STRING, type STRING, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_ARTIFACTS (ARTIFACT_ID, SESSION_ID, TYPE, LOCATION, META) VALUES (UUID_STRING(), :session_id, :type, :location, :meta);
$$

