CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMP_TOKEN_USAGE(tat_id STRING, used_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMP_TOKEN_USAGE (USG_ID, TAT_ID, USED_BY, META) VALUES (UUID_STRING(), :tat_id, :used_by, :meta);
$$

