CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_AUDIT_ITEM(ref_type STRING, ref_id STRING, summary VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_INDEX (AIDX_ID, REF_TYPE, REF_ID, SUMMARY) VALUES (UUID_STRING(), :ref_type, :ref_id, :summary);
$$

