CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_AUDIT_INDEX_LOG(aidx_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_INDEX_LOGS (LOG_ID, AIDX_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :aidx_id, :status, :details);
$$

