CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_TELEMETRY(session_id STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_TELEMETRY (TELE_ID, SESSION_ID, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :session_id, :metric_name, :metric_value);
$$

