CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KPI_RUN(kpi_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KPI_RUNS (RUN_ID, KPI_ID, RESULT) VALUES (UUID_STRING(), :kpi_id, :result);
$$

