CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATIONAL_METRIC(name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATIONAL_METRICS (MET_ID, NAME, VALUE) VALUES (UUID_STRING(), :name, :value);
$$

