CREATE OR REPLACE PROCEDURE DOCGEN.SET_BATCH_RETRY_POLICY(name STRING, policy VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_RETRY_POLICIES (POLICY_ID, NAME, POLICY) VALUES (UUID_STRING(), :name, :policy);
$$

