CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BATCH_RETRY_LOG(policy_id STRING, run_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_RETRY_LOGS (LOG_ID, POLICY_ID, RUN_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :policy_id, :run_id, :status, :details);
$$

