CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REPORT_DELIVERY_LOG(srep_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPORT_DELIVERY_LOGS (LOG_ID, SREP_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :srep_id, :status, :details);
$$

