CREATE OR REPLACE PROCEDURE DOCGEN.ESCALATE_SUPPORT_TICKET(ticket_id STRING, level STRING, escalated_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_ESCALATIONS (ESC_ID, TICKET_ID, LEVEL, ESCALATED_TO) VALUES (UUID_STRING(), :ticket_id, :level, :escalated_to);
$$

