CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SUPPORT_SLA_METRIC(ticket_id STRING, sla_metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_SLA_METRICS (MET_ID, TICKET_ID, SLA_METRIC) VALUES (UUID_STRING(), :ticket_id, :sla_metric);
$$

