CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FEEDBACK_METRIC(fb_id STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEEDBACK_METRICS (METRIC_ID, FB_ID, METRIC_NAME, METRIC_VALUE) VALUES (UUID_STRING(), :fb_id, :metric_name, :metric_value);
$$

