CREATE OR REPLACE PROCEDURE DOCGEN.CHECK_TEMPLATE_USAGE_ALERTS()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_ALERTS (ALERT_ID, TEMPLATE_ID, THRESHOLD) SELECT UUID_STRING(), TEMPLATE_ID, 1000 FROM DOCGEN.TEMPLATE_USAGE_STATS WHERE USAGE_COUNT > 1000;
$$

