CREATE OR REPLACE PROCEDURE DOCGEN.DEPRECATE_TEMPLATE(template_id STRING, deprecated_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEPRECATIONS (DEPREC_ID, TEMPLATE_ID, DEPRECATED_BY, REASON) VALUES (UUID_STRING(), :template_id, :deprecated_by, :reason);
$$

