CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_MIGRATION(template_id STRING, from_version INT, to_version INT, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_MIGRATIONS (MIG_ID, TEMPLATE_ID, FROM_VERSION, TO_VERSION, META) VALUES (UUID_STRING(), :template_id, :from_version, :to_version, :meta);
$$

