CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_NOTICE_EVENT(bundle_id STRING, notice_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTICE_EVENTS (NOTICE_ID, BUNDLE_ID, NOTICE_TYPE, PAYLOAD) VALUES (UUID_STRING(), :bundle_id, :notice_type, :payload);
$$

