CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_NOTIFICATION_TEMPLATE(name STRING, channel STRING, body VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_TEMPLATES (TEMPLATE_ID, NAME, CHANNEL, BODY) VALUES (UUID_STRING(), :name, :channel, :body);
$$

