CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTIFICATION_HISTORY(template_id STRING, target STRING, status STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_HISTORY (NH_ID, TEMPLATE_ID, TARGET, STATUS, PAYLOAD) VALUES (UUID_STRING(), :template_id, :target, :status, :payload);
$$

