CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_WEBHOOK_CONSUMER(name STRING, endpoint STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_CONSUMERS (CONSUMER_ID, NAME, ENDPOINT, SECRET_HASH) VALUES (UUID_STRING(), :name, :endpoint, :secret_hash);
$$

