CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_HEALTH(provider_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_HEALTH (PH_ID, PROVIDER_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :provider_id, :status, :details);
$$

