CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_CONFIG_CHANGE(provider_id STRING, changed_by STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CONFIG_CHANGES (CHANGE_ID, PROVIDER_ID, CHANGED_BY, CHANGES) VALUES (UUID_STRING(), :provider_id, :changed_by, :changes);
$$

