CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_PROVIDER_CREDENTIAL(provider_id STRING, cred_type STRING, cred_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_CREDENTIALS t
USING (SELECT :provider_id AS pid, :cred_type AS ct, :cred_meta AS cm) s
ON t.PROVIDER_ID = s.pid AND t.CRED_TYPE = s.ct
WHEN MATCHED THEN UPDATE SET CRED_META = s.cm
WHEN NOT MATCHED THEN INSERT (CRED_ID, PROVIDER_ID, CRED_TYPE, CRED_META) VALUES (UUID_STRING(), s.pid, s.ct, s.cm);
$$;

