CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_CRED_ROTATION(cred_id STRING, rotated_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CRED_ROTATION (ROT_ID, CRED_ID, ROTATED_BY, META) VALUES (UUID_STRING(), :cred_id, :rotated_by, :meta);
$$;

