CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_ACCESS_AUDIT(provider_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ACCESS_AUDIT (AUDIT_ID, PROVIDER_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :provider_id, :action, :performed_by, :details);
$$;

