CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ENROLLMENT_REQUEST(subject_ref STRING, type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ENROLLMENT_REQUESTS (REQ_ID, SUBJECT_REF, TYPE, PAYLOAD) VALUES (UUID_STRING(), :subject_ref, :type, :payload);
$$;

