CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_PROVIDER_RATE_USAGE(provider_id STRING, window_start TIMESTAMP_LTZ, increment INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_RATE_USAGE t USING (SELECT :provider_id AS pid, :window_start AS ws, :increment AS inc) s
ON t.PROVIDER_ID = s.pid AND t.WINDOW_START = s.ws
WHEN MATCHED THEN UPDATE SET CALLS = CALLS + s.inc, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (USAGE_ID, PROVIDER_ID, WINDOW_START, CALLS) VALUES (UUID_STRING(), s.pid, s.ws, s.inc);
$$

