CREATE OR REPLACE PROCEDURE DOCGEN.SET_PROVIDER_SLA(provider_id STRING, sla_json VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_SLA t USING (SELECT :provider_id AS pid, :sla_json AS sj) s
ON t.PROVIDER_ID = s.pid
WHEN MATCHED THEN UPDATE SET SLA_JSON = s.sj
WHEN NOT MATCHED THEN INSERT (SLA_ID, PROVIDER_ID, SLA_JSON) VALUES (UUID_STRING(), s.pid, s.sj);
$$

