CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_EXPORT_JOB(scope VARIANT, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_EXPORT_JOBS (JOB_ID, SCOPE, TARGET_STAGE) VALUES (UUID_STRING(), :scope, :target_stage);
$$;

