CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_PROVIDER_MAINTENANCE(provider_id STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_MAINTENANCE (MAINT_ID, PROVIDER_ID, START_AT, END_AT, REASON) VALUES (UUID_STRING(), :provider_id, :start_at, :end_at, :reason);
$$

