CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EVIDENCE_CHECKSUM(bundle_id STRING, checksum STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_CHECKSUMS (CHECK_ID, BUNDLE_ID, CHECKSUM, META) VALUES (UUID_STRING(), :bundle_id, :checksum, :meta);
$$;

