CREATE OR REPLACE PROCEDURE DOCGEN.ADD_PROVIDER_SUPPORT_CONTACT(provider_id STRING, name STRING, email STRING, phone STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_SUPPORT_CONTACTS (CONTACT_ID, PROVIDER_ID, NAME, EMAIL, PHONE, META) VALUES (UUID_STRING(), :provider_id, :name, :email, :phone, :meta);
$$

