CREATE OR REPLACE PROCEDURE DOCGEN.VERIFY_EVIDENCE_CHECKSUM(check_id STRING, verified_by STRING, result BOOLEAN, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHECKSUM_VERIFICATIONS (VER_ID, CHECK_ID, VERIFIED_BY, RESULT, DETAILS) VALUES (UUID_STRING(), :check_id, :verified_by, :result, :details);
$$;

