CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_BLOCKCHAIN_ANCHOR(bundle_id STRING, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_ANCHOR_QUEUE (ANCHOR_ID, BUNDLE_ID, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :bundle_id, :next_attempt_at);
$$;

