CREATE OR REPLACE PROCEDURE DOCGEN.ALLOCATE_PROVIDER_COST(cost_id STRING, account_id STRING, alloc_amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_COST_ALLOCATIONS (ALLOC_ID, COST_ID, ACCOUNT_ID, ALLOC_AMOUNT) VALUES (UUID_STRING(), :cost_id, :account_id, :alloc_amount);
$$

