CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BLOCKCHAIN_ANCHOR_LOG(anchor_id STRING, status STRING, txhash STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_ANCHOR_LOGS (LOG_ID, ANCHOR_ID, STATUS, TXHASH, DETAILS) VALUES (UUID_STRING(), :anchor_id, :status, :txhash, :details);
$$;

