CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_CAPACITY(provider_id STRING, cap_metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_CAPACITY t USING (SELECT :provider_id AS pid, :cap_metrics AS cm) s ON t.PROVIDER_ID = s.pid WHEN MATCHED THEN UPDATE SET CAP_METRICS = s.cm, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CAP_ID, PROVIDER_ID, CAP_METRICS) VALUES (UUID_STRING(), s.pid, s.cm);
$$

