CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_NOTARY_REQUEST(bundle_id STRING, requested_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_REQUESTS (NREQ_ID, BUNDLE_ID, REQUESTED_BY, META) VALUES (UUID_STRING(), :bundle_id, :requested_by, :meta);
$$;

