CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTARY_LOG(nreq_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_LOGS (LOG_ID, NREQ_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :nreq_id, :status, :details);
$$;

