CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXTERNAL_FUNCTION_EVENT(name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXTERNAL_FUNCTION_EVENTS (EFE_ID, NAME, PAYLOAD) VALUES (UUID_STRING(), :name, :payload);
$$

