CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THIRD_PARTY_EVIDENCE(bundle_id STRING, provider STRING, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_EVIDENCE (EVID_ID, BUNDLE_ID, PROVIDER, LOCATION, META) VALUES (UUID_STRING(), :bundle_id, :provider, :location, :meta);
$$;

