CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXTERNAL_FUNCTION_LOG(efe_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXTERNAL_FUNCTION_LOGS (LOG_ID, EFE_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :efe_id, :status, :response);
$$

