CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_CONFORMANCE_TEST(name STRING, description STRING, assertions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONFORMANCE_TESTS (TEST_ID, NAME, DESCRIPTION, ASSERTIONS) VALUES (UUID_STRING(), :name, :description, :assertions);
$$;

