CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONFORMANCE_RUN(test_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONFORMANCE_RUNS (RUN_ID, TEST_ID, RESULT) VALUES (UUID_STRING(), :test_id, :result);
$$;

