CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_VECTOR_REBUILD(index_name STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VECTOR_REBUILD_JOBS (JOB_ID, INDEX_NAME, META) VALUES (UUID_STRING(), :index_name, :meta);
$$

