CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_EXECUTION_LOG(rule_id STRING, context VARIANT, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_EXECUTION_LOGS (LOG_ID, RULE_ID, CONTEXT, RESULT) VALUES (UUID_STRING(), :rule_id, :context, :result);
$$;

