CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_EMBEDDING_HEALTH(index_name STRING, num_vectors INT, last_updated TIMESTAMP_LTZ, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EMBEDDING_HEALTH t USING (SELECT :index_name AS iname, :num_vectors AS nv, :last_updated AS lu, :metrics AS m) s ON t.INDEX_NAME = s.iname WHEN MATCHED THEN UPDATE SET NUM_VECTORS = s.nv, LAST_UPDATED = s.lu, METRICS = s.m WHEN NOT MATCHED THEN INSERT (EH_ID, INDEX_NAME, NUM_VECTORS, LAST_UPDATED, METRICS) VALUES (UUID_STRING(), s.iname, s.nv, s.lu, s.m);
$$

