CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_QUALITY_RULE(template_id STRING, rule VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_QUALITY_RULES (TQR_ID, TEMPLATE_ID, RULE) VALUES (UUID_STRING(), :template_id, :rule);
$$;

