CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_QUALITY_ISSUE(template_id STRING, issue VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_QUALITY_ISSUES (ISSUE_ID, TEMPLATE_ID, ISSUE) VALUES (UUID_STRING(), :template_id, :issue);
$$;

