CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INDEX_ALERT(index_name STRING, alert_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_ALERTS (ALERT_ID, INDEX_NAME, ALERT_TYPE, DETAILS) VALUES (UUID_STRING(), :index_name, :alert_type, :details);
$$

