CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INDEX_RECOMMENDATION(index_name STRING, recommendation VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_RECOMMENDATIONS (REC_ID, INDEX_NAME, RECOMMENDATION) VALUES (UUID_STRING(), :index_name, :recommendation);
$$

