CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BULK_EXPORT_JOB(scope VARIANT, target_uri STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BULK_EXPORT_JOBS (JOB_ID, SCOPE, TARGET_URI) VALUES (UUID_STRING(), :scope, :target_uri);
$$

