CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_APPROVAL(template_id STRING, approved_by STRING, comments STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_APPROVAL_HISTORY (APPROVAL_ID, TEMPLATE_ID, APPROVED_BY, COMMENTS) VALUES (UUID_STRING(), :template_id, :approved_by, :comments);
$$;

