CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_BUCKET_ARCHIVAL(bucket_path STRING, object_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BUCKET_ARCHIVAL_INDEX (INDEX_ID, BUCKET_PATH, OBJECT_COUNT) VALUES (UUID_STRING(), :bucket_path, :object_count);
$$

