CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ARCHIVAL_POLICY(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVAL_POLICIES (POLICY_ID, NAME, RULES) VALUES (UUID_STRING(), :name, :rules);
$$

