CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ARCHIVAL_AUDIT(policy_id STRING, object_ref STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVAL_AUDIT (AUDIT_ID, POLICY_ID, OBJECT_REF, ACTION, DETAILS) VALUES (UUID_STRING(), :policy_id, :object_ref, :action, :details);
$$

