CREATE OR REPLACE PROCEDURE DOCGEN.SET_COMPLIANCE_RETENTION(target_ref STRING, retention_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.COMPLIANCE_RETENTION_INDEX t USING (SELECT :target_ref AS tref, :retention_days AS rd) s ON t.TARGET_REF = s.tref WHEN MATCHED THEN UPDATE SET RETENTION_DAYS = s.rd WHEN NOT MATCHED THEN INSERT (RET_ID, TARGET_REF, RETENTION_DAYS) VALUES (UUID_STRING(), s.tref, s.rd);
$$

