CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_MASKING_RULE(field_path STRING, mask_expression STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_MASKING_RULES (RULE_ID, FIELD_PATH, MASK_EXPRESSION) VALUES (UUID_STRING(), :field_path, :mask_expression);
$$

