CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REDACTION_REQUEST(target_ref STRING, requested_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_REQUESTS (REQ_ID, TARGET_REF, REQUESTED_BY, META) VALUES (UUID_STRING(), :target_ref, :requested_by, :meta);
$$

