CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REDACTION_LOG(req_id STRING, action STRING, by_user STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_LOGS (LOG_ID, REQ_ID, ACTION, BY_USER, DETAILS) VALUES (UUID_STRING(), :req_id, :action, :by_user, :details);
$$

