CREATE OR REPLACE PROCEDURE DOCGEN.BLACKLIST_ACCESS_TOKEN(token_id STRING, subject_ref STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_TOKEN_BLACKLIST (TOKEN_ID, SUBJECT_REF, REASON) VALUES (UUID_STRING(), :subject_ref, :reason);
$$

