CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SESSION_RECOVERY_TOKEN(session_id STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_RECOVERY_TOKENS (TOKEN_ID, SESSION_ID, TOKEN_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :session_id, :token_hash, :expires_at);
$$

