CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNER_PREFERENCES(signer_id STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_PREFERENCES t USING (SELECT :signer_id AS sid, :prefs AS p) s
ON t.SIGNER_ID = s.sid
WHEN MATCHED THEN UPDATE SET PREFERENCES = s.p, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PREF_ID, SIGNER_ID, PREFERENCES) VALUES (UUID_STRING(), s.sid, s.p);
$$

