CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OTP_CODE(signer_id STRING, otp_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTP_CODES (OTP_ID, SIGNER_ID, OTP_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :signer_id, :otp_hash, :expires_at);
$$

