CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OTP_USAGE(otp_id STRING, signer_id STRING, result STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTP_USAGE_LOG (LOG_ID, OTP_ID, SIGNER_ID, RESULT, META) VALUES (UUID_STRING(), :otp_id, :signer_id, :result, :meta);
UPDATE DOCGEN.OTP_CODES SET USED = TRUE WHERE OTP_ID = :otp_id;
$$

