CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SIGNING_WORKFLOW(account_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_WORKFLOWS (WORKFLOW_ID, ACCOUNT_ID, NAME, CONFIG) VALUES (UUID_STRING(), :account_id, :name, :config);
$$

