CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNING_STEP_HISTORY(step_id STRING, instance_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_STEP_HISTORY (H_ID, STEP_ID, INSTANCE_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :step_id, :instance_id, :status, :details);
$$

