CREATE OR REPLACE PROCEDURE DOCGEN.CHANGE_DOCUMENT_STATE(document_id STRING, state_name STRING, changed_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_LIFECYCLE_STATES (STATE_ID, DOCUMENT_ID, STATE_NAME, CHANGED_BY, META) VALUES (UUID_STRING(), :document_id, :state_name, :changed_by, :meta);
$$

