CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SIGNING_INSTANCE_TOKEN(instance_id STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_INSTANCE_TOKENS (TOKEN_ID, INSTANCE_ID, TOKEN_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :instance_id, :token_hash, :expires_at);
$$

