CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNING_INSTANCE_TOKEN_USAGE(token_id STRING, used_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_INSTANCE_TOKEN_USAGE (USG_ID, TOKEN_ID, USED_BY, META) VALUES (UUID_STRING(), :token_id, :used_by, :meta);
$$

