CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_SIGNER_ROLE(signer_id STRING, role STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_ROLE_MAPPINGS (MAP_ID, SIGNER_ID, ROLE) VALUES (UUID_STRING(), :signer_id, :role);
$$

