CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_2FA_SETTINGS(signer_id STRING, enabled BOOLEAN, methods ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_2FA_SETTINGS t USING (SELECT :signer_id AS sid, :enabled AS en, :methods AS m) s
ON t.SIGNER_ID = s.sid
WHEN MATCHED THEN UPDATE SET ENABLED = s.en, METHODS = s.m, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (SETTING_ID, SIGNER_ID, ENABLED, METHODS) VALUES (UUID_STRING(), s.sid, s.en, s.m);
$$

