CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNATURE_EMAIL_SEND(template_id STRING, to_address STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EMAIL_SEND_LOGS (LOG_ID, TEMPLATE_ID, TO_ADDRESS, STATUS, DETAILS) VALUES (UUID_STRING(), :template_id, :to_address, :status, :details);
$$

