CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEOLOCATION(subject_ref STRING, latitude FLOAT, longitude FLOAT, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEOLOCATION_RECORDS (GEO_ID, SUBJECT_REF, LATITUDE, LONGITUDE, META) VALUES (UUID_STRING(), :subject_ref, :latitude, :longitude, :meta);
$$

