CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DEVICE_RISK_SCORE(device_hash STRING, score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_RISK_SCORES t USING (SELECT :device_hash AS dh, :score AS sc, :details AS d) s
ON t.DEVICE_HASH = s.dh
WHEN MATCHED THEN UPDATE SET SCORE = s.sc, DETAILS = s.d, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (RISK_ID, DEVICE_HASH, SCORE, DETAILS) VALUES (UUID_STRING(), s.dh, s.sc, s.d);
$$

