CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT(subject_ref STRING, consent_type STRING, given_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_CONSENTS (CONSENT_ID, SUBJECT_REF, CONSENT_TYPE, GIVEN_AT, META) VALUES (UUID_STRING(), :subject_ref, :consent_type, :given_at, :meta);
$$

