CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_CONSENT(consent_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_REVOCATIONS (REV_ID, CONSENT_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :consent_id, :revoked_by, :reason);
$$

