CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SHARE_AUDIT(share_id STRING, action STRING, action_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SHARE_AUDIT_LOGS (LOG_ID, SHARE_ID, ACTION, ACTION_BY, DETAILS) VALUES (UUID_STRING(), :share_id, :action, :action_by, :details);
$$

