CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_EMBEDDED_MEDIA(bundle_id STRING, media_type STRING, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMBEDDED_MEDIA (MEDIA_ID, BUNDLE_ID, MEDIA_TYPE, LOCATION, META) VALUES (UUID_STRING(), :bundle_id, :media_type, :location, :meta);
$$

