CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_TEMPLATE_LOCALIZATION(template_id STRING, locale STRING, content VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_LOCALIZATIONS t USING (SELECT :template_id AS tid, :locale AS lc, :content AS c) s
ON t.TEMPLATE_ID = s.tid AND t.LOCALE = s.lc
WHEN MATCHED THEN UPDATE SET CONTENT = s.c, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (LOC_ID, TEMPLATE_ID, LOCALE, CONTENT) VALUES (UUID_STRING(), s.tid, s.lc, s.c);
$$

