CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_PREVIEW_METRIC(cache_id STRING, latency_ms INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PREVIEW_METRICS (MET_ID, CACHE_ID, LATENCY_MS) VALUES (UUID_STRING(), :cache_id, :latency_ms);
$$

