CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_APPROVAL(requester STRING, resource_ref STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_APPROVALS (APPROVAL_ID, REQUESTER, RESOURCE_REF, META) VALUES (UUID_STRING(), :requester, :resource_ref, :meta);
$$

