CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCESS_APPROVAL_LOG(approval_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_APPROVAL_LOGS (LOG_ID, APPROVAL_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :approval_id, :action, :performed_by, :details);
$$

