CREATE OR REPLACE PROCEDURE DOCGEN.SET_API_CALL_QUOTA(account_id STRING, window_seconds INT, max_calls INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.API_CALL_QUOTAS t USING (SELECT :account_id AS aid, :window_seconds AS ws, :max_calls AS mc) s ON t.ACCOUNT_ID = s.aid WHEN MATCHED THEN UPDATE SET WINDOW_SECONDS = s.ws, MAX_CALLS = s.mc WHEN NOT MATCHED THEN INSERT (QUOTA_ID, ACCOUNT_ID, WINDOW_SECONDS, MAX_CALLS) VALUES (UUID_STRING(), s.aid, s.ws, s.mc);
$$

