CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_API_CALL_USAGE(account_id STRING, window_start TIMESTAMP_LTZ, increment INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.API_CALL_USAGE t USING (SELECT :account_id AS aid, :window_start AS ws, :increment AS inc) s ON t.ACCOUNT_ID = s.aid AND t.WINDOW_START = s.ws WHEN MATCHED THEN UPDATE SET CALLS = CALLS + s.inc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (USG_ID, ACCOUNT_ID, WINDOW_START, CALLS) VALUES (UUID_STRING(), s.aid, s.ws, s.inc);
$$

