CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_QUOTA_VIOLATION(account_id STRING, window_start TIMESTAMP_LTZ, calls INT, quota INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_QUOTA_VIOLATIONS (VIOLATION_ID, ACCOUNT_ID, WINDOW_START, CALLS, QUOTA) VALUES (UUID_STRING(), :account_id, :window_start, :calls, :quota);
$$

