CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD_REQUEST(target_ref STRING, requested_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_REQUESTS (HOLD_ID, TARGET_REF, REQUESTED_BY, META) VALUES (UUID_STRING(), :target_ref, :requested_by, :meta);
$$

