CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LEGAL_HOLD_ACTION(hold_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_ACTIONS (ACTION_ID, HOLD_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :hold_id, :action, :performed_by, :details);
$$

