CREATE OR REPLACE PROCEDURE DOCGEN.RUN_RETENTION_COMPLIANCE_CHECK(target_ref STRING, result STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_COMPLIANCE_CHECKS (CHECK_ID, TARGET_REF, RESULT, DETAILS) VALUES (UUID_STRING(), :target_ref, :result, :details);
$$

