CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EVENT_REPLAY(event_id STRING, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_REPLAY_QUEUE (REPLAY_ID, EVENT_ID, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :event_id, :next_attempt_at);
$$

