CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EVENT_REPLAY_LOG(replay_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_REPLAY_LOGS (LOG_ID, REPLAY_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :replay_id, :status, :details);
$$

