CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SLO_DEFINITION(name STRING, target VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLO_DEFINITIONS (SLO_ID, NAME, TARGET, OWNER) VALUES (UUID_STRING(), :name, :target, :owner);
$$

