CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_WEEKLY_SIGNATURE_AGGREGATES(week_start DATE)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEEKLY_SIGNATURE_AGGREGATES (AGG_ID, ACCOUNT_ID, WEEK_START, TOTAL_SIGNATURES, FAILED_SIGNATURES)
SELECT UUID_STRING(), ACCOUNT_ID, :week_start, COUNT(*), SUM(CASE WHEN EVENT_TYPE = 'signature_failed' THEN 1 ELSE 0 END)
FROM DOCGEN.SIGNATURE_EVENTS WHERE DATE_TRUNC('WEEK', EVENT_TS::DATE) = :week_start GROUP BY ACCOUNT_ID;
$$

