CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_HEARTBEAT(session_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_HEARTBEATS (HB_ID, SESSION_ID, META) VALUES (UUID_STRING(), :session_id, :meta);
$$

