CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_SESSION_LOCK(session_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_LOCKS (LOCK_ID, SESSION_ID, LOCKED_BY) VALUES (UUID_STRING(), :session_id, :locked_by);
$$

