CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_LOCK_HISTORY(lock_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_LOCK_HISTORY (H_ID, LOCK_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :lock_id, :action, :performed_by, :details);
$$

