CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_SNAPSHOT(snapshot_json VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_SNAPSHOTS (SNAP_ID, SNAP_JSON) VALUES (UUID_STRING(), :snapshot_json);
$$

