CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DOCUMENT_CHECKSUM(document_id STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DOCUMENT_CHECKSUMS t USING (SELECT :document_id AS docid, :checksum AS cs) s
ON t.DOCUMENT_ID = s.docid
WHEN MATCHED THEN UPDATE SET CHECKSUM = s.cs, COMPUTED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (DOCUMENT_ID, CHECKSUM) VALUES (s.docid, s.cs);
$$

