CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SIGNER_DEVICE(signer_id STRING, device_info VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_DEVICE_REGISTRATIONS (REG_ID, SIGNER_ID, DEVICE_INFO) VALUES (UUID_STRING(), :signer_id, :device_info);
$$

