CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNER_DEVICE_ACTIVITY(reg_id STRING, activity_type STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_DEVICE_ACTIVITY (ACT_ID, REG_ID, ACTIVITY_TYPE, META) VALUES (UUID_STRING(), :reg_id, :activity_type, :meta);
$$

