CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_TEMPLATE(signer_id STRING, template_hash STRING, template_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES (TEMPLATE_ID, SIGNER_ID, TEMPLATE_HASH, TEMPLATE_META) VALUES (UUID_STRING(), :signer_id, :template_hash, :template_meta);
$$

