CREATE OR REPLACE PROCEDURE DOCGEN.ADD_RISK_POLICY_RULE(name STRING, condition VARIANT, actions VARIANT, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_POLICY_RULES (RULE_ID, NAME, CONDITION, ACTIONS, SEVERITY) VALUES (UUID_STRING(), :name, :condition, :actions, :severity);
$$

