CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_FRAUD_ALERT(subject_ref STRING, score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_ALERTS (ALERT_ID, SUBJECT_REF, SCORE, DETAILS) VALUES (UUID_STRING(), :subject_ref, :score, :details);
$$

