CREATE OR REPLACE PROCEDURE DOCGEN.OPEN_FRAUD_INVESTIGATION(alert_id STRING, investigator STRING, notes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_INVESTIGATIONS (INV_ID, ALERT_ID, INVESTIGATOR, NOTES) VALUES (UUID_STRING(), :alert_id, :investigator, :notes);
$$

