CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FORENSIC_EXPORT(alert_id STRING, bundle_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FORENSIC_EXPORTS (EXPORT_ID, ALERT_ID, BUNDLE_REF) VALUES (UUID_STRING(), :alert_id, :bundle_ref);
$$

