CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REGULATORY_NOTIFICATION(region STRING, description STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REGULATORY_NOTIFICATIONS (NOTIF_ID, REGION, DESCRIPTION, META) VALUES (UUID_STRING(), :region, :description, :meta);
$$

