CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RULE_VIOLATION_AUDIT(rule_id STRING, subject_ref STRING, violation_detail VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RULE_VIOLATION_AUDITS (AUDIT_ID, RULE_ID, SUBJECT_REF, VIOLATION_DETAIL) VALUES (UUID_STRING(), :rule_id, :subject_ref, :violation_detail);
$$

