CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_REVIEW_TASK(q_id STRING, assigned_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVIEW_ASSIGNMENTS (ASSIGN_ID, Q_ID, ASSIGNED_TO) VALUES (UUID_STRING(), :q_id, :assigned_to);
$$

