CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ESCALATION_RULE(name STRING, condition VARIANT, escalation_chain VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_RULES (ESC_ID, NAME, CONDITION, ESCALATION_CHAIN) VALUES (UUID_STRING(), :name, :condition, :escalation_chain);
$$

