CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESCALATION_HISTORY(esc_id STRING, subject_ref STRING, action_taken STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_HISTORY (HIST_ID, ESC_ID, SUBJECT_REF, ACTION_TAKEN, DETAILS) VALUES (UUID_STRING(), :esc_id, :subject_ref, :action_taken, :details);
$$

