CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_RETENTION_POLICY(name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_RETENTION_POLICIES (POLICY_ID, NAME, RULES) VALUES (UUID_STRING(), :name, :rules);
$$

