CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DATA_PURGE_LOG(job_id STRING, target_ref STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_PURGE_LOGS (LOG_ID, JOB_ID, TARGET_REF, ACTION, DETAILS) VALUES (UUID_STRING(), :job_id, :target_ref, :action, :details);
$$

