CREATE OR REPLACE PROCEDURE DOCGEN.INGEST_THREAT_FEED_ITEM(source STRING, details VARIANT, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_FEED (THREAT_ID, SOURCE, DETAILS, SEVERITY) VALUES (UUID_STRING(), :source, :details, :severity);
$$

