CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_THREAT_ALERT(threat_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_ALERTS (ALERT_ID, THREAT_ID, META) VALUES (UUID_STRING(), :threat_id, :meta);
$$

