CREATE OR REPLACE PROCEDURE DOCGEN.NOTIFY_RESPONDERS(roster_id STRING, message STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RESPONDER_NOTIFICATIONS (NOTIF_ID, ROSTER_ID, MESSAGE, META) VALUES (UUID_STRING(), :roster_id, :message, :meta);
$$

