CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_MAINTENANCE_WINDOW(component STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS (WINDOW_ID, COMPONENT, START_AT, END_AT, REASON) VALUES (UUID_STRING(), :component, :start_at, :end_at, :reason);
$$

