CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MAINTENANCE_NOTIFICATION(window_id STRING, channel STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_NOTIFICATIONS (NOTIF_ID, WINDOW_ID, CHANNEL, DETAILS) VALUES (UUID_STRING(), :window_id, :channel, :details);
$$

