CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_HEALTH_SUMMARY(component STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HEALTH_SUMMARY (SUMMARY_ID, COMPONENT, STATUS, METRICS) VALUES (UUID_STRING(), :component, 'OK', :metrics);
$$

