CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_DASHBOARD(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_DASHBOARDS (DASH_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

