CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_USER_FEEDBACK(user_id STRING, category STRING, comments STRING, rating INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_FEEDBACK (FB_ID, USER_ID, CATEGORY, COMMENTS, RATING) VALUES (UUID_STRING(), :user_id, :category, :comments, :rating);
$$

