CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_USER_SATISFACTION(period_start DATE, period_end DATE)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_SATISFACTION_METRICS (MET_ID, PERIOD_START, PERIOD_END, AVERAGE_RATING) VALUES (UUID_STRING(), :period_start, :period_end, 0);
$$

