CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FEEDBACK_ACTION_ITEM(fb_id STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEEDBACK_ACTION_ITEMS (ITEM_ID, FB_ID, OWNER) VALUES (UUID_STRING(), :fb_id, :owner);
$$

