CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_UX_METRIC(metric_name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.UX_METRICS (UX_ID, METRIC_NAME, VALUE) VALUES (UUID_STRING(), :metric_name, :value);
$$

