CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CAPACITY_PLAN(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CAPACITY_PLANS (PLAN_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

