CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BILLING_ALERT(rule_id STRING, account_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_ALERTS (ALERT_ID, RULE_ID, ACCOUNT_ID, PAYLOAD) VALUES (UUID_STRING(), :rule_id, :account_id, :payload);
$$

