CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FINANCIAL_RECON_LOG(recon_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FINANCIAL_RECONCILIATION_LOGS (LOG_ID, RECON_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :recon_id, :status, :details);
$$

