CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CHARGEBACK_ENTRY(account_id STRING, amount NUMBER, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHARGEBACK_ENTRIES (ENTRY_ID, ACCOUNT_ID, AMOUNT, REASON) VALUES (UUID_STRING(), :account_id, :amount, :reason);
$$

