CREATE OR REPLACE PROCEDURE DOCGEN.FILE_BILLING_DISPUTE(account_id STRING, invoice_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_DISPUTES (DISPUTE_ID, ACCOUNT_ID, INVOICE_ID, REASON) VALUES (UUID_STRING(), :account_id, :invoice_id, :reason);
$$

