CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REFUND_OUTCOME(request_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REFUND_OUTCOMES (OUTCOME_ID, REQUEST_ID, STATUS, PROCESSED_AT, DETAILS)
VALUES (UUID_STRING(), :request_id, :status, CURRENT_TIMESTAMP(), :details);
$$

