CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SETTLEMENT_BATCH(account_id STRING, amount NUMBER, currency STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SETTLEMENT_BATCHES (BATCH_ID, ACCOUNT_ID, AMOUNT, CURRENCY) VALUES (UUID_STRING(), :account_id, :amount, :currency);
$$

