CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SETTLEMENT_LOG(batch_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SETTLEMENT_LOGS (LOG_ID, BATCH_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :batch_id, :status, :details);
$$

