CREATE OR REPLACE PROCEDURE DOCGEN.ADD_SLACK_INTEGRATION(provider_id STRING, webhook_url STRING, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLACK_INTEGRATIONS (INTEG_ID, PROVIDER_ID, WEBHOOK_URL, CHANNEL) VALUES (UUID_STRING(), :provider_id, :webhook_url, :channel);
$$

