CREATE OR REPLACE PROCEDURE DOCGEN.SEND_ALERT_NOTIFICATION(alert_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_NOTIFICATIONS (NOTIF_ID, ALERT_ID, CHANNEL, PAYLOAD) VALUES (UUID_STRING(), :alert_id, :channel, :payload);
$$

