CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_WEBHOOK_SUBSCRIPTION(account_id STRING, event_name STRING, target_url STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_SUBSCRIPTIONS (SUB_ID, ACCOUNT_ID, EVENT_NAME, TARGET_URL, SECRET_HASH) VALUES (UUID_STRING(), :account_id, :event_name, :target_url, :secret_hash);
$$

