CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_WEBHOOK_DELIVERY_LOG(sub_id STRING, event_id STRING, status STRING, http_status INT, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_DELIVERY_LOGS (DL_ID, SUB_ID, EVENT_ID, STATUS, HTTP_STATUS, RESPONSE) VALUES (UUID_STRING(), :sub_id, :event_id, :status, :http_status, :response);
$$

