CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_WEBHOOK_RETRY(dl_id STRING, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_RETRY_QUEUE (Q_ID, DL_ID, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :dl_id, :next_attempt_at);
$$

