CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_API_KEY(key_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEY_REVOCATIONS (REV_ID, KEY_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :key_id, :revoked_by, :reason);
$$

