CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_KEY_USAGE(key_id STRING, endpoint STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEY_USAGE (USG_ID, KEY_ID, ENDPOINT, META) VALUES (UUID_STRING(), :key_id, :endpoint, :meta);
$$

