CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TO_THREAT_BLACKLIST(subject STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_BLACKLIST (BL_ID, SUBJECT, REASON) VALUES (UUID_STRING(), :subject, :reason);
$$

