CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DATA_ACCESS_REQUEST(requester STRING, target STRING, purpose STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_ACCESS_REQUESTS (REQ_ID, REQUESTER, TARGET, PURPOSE) VALUES (UUID_STRING(), :requester, :target, :purpose);
$$

