CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DATA_ACCESS_AUDIT(req_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_ACCESS_AUDITS (AUDIT_ID, REQ_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :req_id, :action, :performed_by, :details);
$$

