CREATE OR REPLACE PROCEDURE DOCGEN.STORE_COMPLIANCE_CERTIFICATE(name STRING, body CLOB, issued_at TIMESTAMP_LTZ, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CERTIFICATES (CERT_ID, NAME, BODY, ISSUED_AT, EXPIRES_AT, META) VALUES (UUID_STRING(), :name, :body, :issued_at, :expires_at, :meta);
$$

