CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_CERTIFICATE(cert_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERTIFICATE_REVOCATIONS (REV_ID, CERT_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :cert_id, :revoked_by, :reason);
$$

