CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_OCSP_CACHE(cert_id STRING, status STRING, raw_response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OCSP_CACHE t USING (SELECT :cert_id AS cid, :status AS st, :raw_response AS rr) s ON t.CERT_ID = s.cid WHEN MATCHED THEN UPDATE SET STATUS = s.st, RAW_RESPONSE = s.rr, CHECKED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CACHE_ID, CERT_ID, STATUS, RAW_RESPONSE) VALUES (UUID_STRING(), s.cid, s.st, s.rr);
$$

