CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_CRL_ENTRY(cert_id STRING, revoked_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CRL_INDEX (INDEX_ID, CERT_ID, REVOKED_AT, META) VALUES (UUID_STRING(), :cert_id, :revoked_at, :meta);
$$

