CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PKI_AUDIT(action STRING, subject STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PKI_AUDIT_TRAIL (AUDIT_ID, ACTION, SUBJECT, DETAILS) VALUES (UUID_STRING(), :action, :subject, :details);
$$

