CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_HSM_KEY_REF(hsm_key_id STRING, purpose STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HSM_KEY_REFERENCES (KEY_REF_ID, HSM_KEY_ID, PURPOSE, META) VALUES (UUID_STRING(), :hsm_key_id, :purpose, :meta);
$$

