CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HSM_USAGE(key_ref_id STRING, operation STRING, user STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HSM_USAGE_LOGS (LOG_ID, KEY_REF_ID, OPERATION, USER, DETAILS) VALUES (UUID_STRING(), :key_ref_id, :operation, :user, :details);
$$

