CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_NOTARY_CERT(notary STRING, cert_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_CERT_INDEX (INDEX_ID, NOTARY, CERT_REF) VALUES (UUID_STRING(), :notary, :cert_ref);
$$

