CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_THIRD_PARTY_CONNECTOR_CONFIG(provider STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.THIRD_PARTY_CONNECTOR_CONFIGS t USING (SELECT :provider AS prov, :config AS cfg, :enabled AS en) s ON t.PROVIDER = s.prov WHEN MATCHED THEN UPDATE SET CONFIG = s.cfg, ENABLED = s.en, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, PROVIDER, CONFIG, ENABLED) VALUES (UUID_STRING(), s.prov, s.cfg, s.en);
$$

