CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_CONNECTOR_HEALTH(provider STRING, status STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.CONNECTOR_HEALTH t USING (SELECT :provider AS prov, :status AS st, :meta AS m) s ON t.PROVIDER = s.prov WHEN MATCHED THEN UPDATE SET STATUS = s.st, META = s.m, LAST_CHECKED = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (HEALTH_ID, PROVIDER, STATUS, META) VALUES (UUID_STRING(), s.prov, s.st, s.m);
$$

