CREATE OR REPLACE PROCEDURE DOCGEN.ADD_PROVIDER_TEST_PAYLOAD(provider_id STRING, name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_TEST_PAYLOADS (PAYLOAD_ID, PROVIDER_ID, NAME, PAYLOAD) VALUES (UUID_STRING(), :provider_id, :name, :payload);
$$

