CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_TEST_RUN(payload_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_TEST_RUNS (RUN_ID, PAYLOAD_ID, RESULT) VALUES (UUID_STRING(), :payload_id, :result);
$$

