CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_BREACH_NOTIFICATION(sla_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_BREACH_NOTIFICATIONS (NOTIF_ID, SLA_ID, DETAILS) VALUES (UUID_STRING(), :sla_id, :details);
$$

