CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_ONBOARDING_AUDIT(provider_id STRING, action STRING, by_user STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ONBOARDING_AUDIT (AUDIT_ID, PROVIDER_ID, ACTION, BY_USER, DETAILS) VALUES (UUID_STRING(), :provider_id, :action, :by_user, :details);
$$

