CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_PROVIDER_DEPRECATION(provider_id STRING, deprecate_at TIMESTAMP_LTZ, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_DEPRECATION_SCHEDULE (SCHED_ID, PROVIDER_ID, DEPRECATE_AT, NOTE) VALUES (UUID_STRING(), :provider_id, :deprecate_at, :note);
$$

