CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PROVIDER_MIGRATION_TASK(from_provider STRING, to_provider STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_MIGRATION_TASKS (TASK_ID, FROM_PROVIDER, TO_PROVIDER, META) VALUES (UUID_STRING(), :from_provider, :to_provider, :meta);
$$

