CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PROVIDER_RBAC_ROLE(provider_id STRING, role_name STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_RBAC_ROLES (ROLE_ID, PROVIDER_ID, ROLE_NAME, PERMISSIONS) VALUES (UUID_STRING(), :provider_id, :role_name, :permissions);
$$

