CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_HISTORY(sla_id STRING, snapshot VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_HISTORY (HIST_ID, SLA_ID, SNAPSHOT) VALUES (UUID_STRING(), :sla_id, :snapshot);
$$

