CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_PROVIDER_COST_TRENDS(provider_id STRING, period_start DATE, period_end DATE)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_COST_TRENDS (TREND_ID, PROVIDER_ID, PERIOD_START, PERIOD_END, METRICS) VALUES (UUID_STRING(), :provider_id, :period_start, :period_end, PARSE_JSON('{}'));
$$

