CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PROVIDER_CHANGE_REQUEST(provider_id STRING, requested_by STRING, change_json VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CHANGE_REQUESTS (REQ_ID, PROVIDER_ID, REQUESTED_BY, CHANGE_JSON) VALUES (UUID_STRING(), :provider_id, :requested_by, :change_json);
$$

