CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_CHANGE_LOG(req_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CHANGE_LOGS (LOG_ID, REQ_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :req_id, :action, :performed_by, :details);
$$

