CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PROVIDER_ARTIFACT(provider_id STRING, artifact_type STRING, location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_DEPLOY_ARTIFACTS (ART_ID, PROVIDER_ID, ARTIFACT_TYPE, LOCATION, META) VALUES (UUID_STRING(), :provider_id, :artifact_type, :location, :meta);
$$

