CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ROLLBACK_PLAN(provider_id STRING, plan VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ROLLBACK_PLANS (PLAN_ID, PROVIDER_ID, PLAN) VALUES (UUID_STRING(), :provider_id, :plan);
$$

