CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POSTMORTEM(incident_id STRING, summary VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_POSTMORTEMS (PM_ID, INCIDENT_ID, SUMMARY) VALUES (UUID_STRING(), :incident_id, :summary);
$$

