CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_RETIREMENT(provider_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_RETIREMENT_RECORDS (RET_ID, PROVIDER_ID, REASON) VALUES (UUID_STRING(), :provider_id, :reason);
$$

