CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_GEO_RESTRICTIONS(provider_id STRING, allowed_regions ARRAY, denied_regions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_GEO_RESTRICTIONS t USING (SELECT :provider_id AS pid, :allowed_regions AS ar, :denied_regions AS dr) s ON t.PROVIDER_ID = s.pid WHEN MATCHED THEN UPDATE SET ALLOWED_REGIONS = s.ar, DENIED_REGIONS = s.dr, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (GR_ID, PROVIDER_ID, ALLOWED_REGIONS, DENIED_REGIONS) VALUES (UUID_STRING(), s.pid, s.ar, s.dr);
$$

