CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SERVICE_ENDPOINT(name STRING, type STRING, url STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_ENDPOINTS (ENDPOINT_ID, NAME, TYPE, URL, META) VALUES (UUID_STRING(), :name, :type, :url, :meta);
$$

