CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TOKEN_TO_BLACKLIST(token_hash STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TOKEN_BLACKLIST (BL_ID, TOKEN_HASH, REASON) VALUES (UUID_STRING(), :token_hash, :reason);
$$

