CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_API_RATE_WINDOW(name STRING, window_seconds INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_RATE_WINDOWS (WINDOW_ID, NAME, WINDOW_SECONDS) VALUES (UUID_STRING(), :name, :window_seconds);
$$

