CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_DOCUMENT_QRCODE(document_id STRING, qr_payload STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_QRCODES (QR_ID, DOCUMENT_ID, QR_PAYLOAD) VALUES (UUID_STRING(), :document_id, :qr_payload);
$$

