CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BULK_EXPORT_JOB(requestor STRING, scope VARIANT, target_stage STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BULK_EXPORT_JOBS (JOB_ID, REQUESTOR, SCOPE, TARGET_STAGE) VALUES (UUID_STRING(), :requestor, :scope, :target_stage);
$$

