CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ROLE_AUDIT(subject_ref STRING, role_assigned STRING, assigned_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROLE_AUDIT_LOG (AUDIT_ID, SUBJECT_REF, ROLE_ASSIGNED, ASSIGNED_BY, META) VALUES (UUID_STRING(), :subject_ref, :role_assigned, :assigned_by, :meta);
$$

