CREATE OR REPLACE PROCEDURE DOCGEN.RESOLVE_DOCUMENT_FLAG(flag_id STRING, resolved_by STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FLAG_RESOLUTIONS (RES_ID, FLAG_ID, RESOLVED_BY, NOTES) VALUES (UUID_STRING(), :flag_id, :resolved_by, :notes);
$$

