CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REDACTION_REQUEST(document_id STRING, requested_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_REQUESTS (REQ_ID, DOCUMENT_ID, REQUESTED_BY, META) VALUES (UUID_STRING(), :document_id, :requested_by, :meta);
$$

