CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REDACTION_AUDIT(req_id STRING, performed_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_AUDIT (AUDIT_ID, REQ_ID, PERFORMED_BY, META) VALUES (UUID_STRING(), :req_id, :performed_by, :meta);
$$

