CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_MULTI_REGION_CONFIG(account_id STRING, region STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.MULTI_REGION_CONFIG t USING (SELECT :account_id AS aid, :region AS reg, :config AS cfg) s ON t.ACCOUNT_ID = s.aid AND t.REGION = s.reg WHEN MATCHED THEN UPDATE SET CONFIG = s.cfg, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, ACCOUNT_ID, REGION, CONFIG) VALUES (UUID_STRING(), s.aid, s.reg, s.cfg);
$$

