CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_REGIONAL_DATA_LOCATION(account_id STRING, region STRING, storage_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REGIONAL_DATA_LOCATIONS (LOC_ID, ACCOUNT_ID, REGION, STORAGE_LOCATION) VALUES (UUID_STRING(), :account_id, :region, :storage_location);
$$

