CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PRIVACY_POLICY(name STRING, content VARIANT, effective_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_POLICIES (POLICY_ID, NAME, CONTENT, EFFECTIVE_AT) VALUES (UUID_STRING(), :name, :content, :effective_at);
$$

