CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_ROLE_MAPPING(role_name STRING, audit_scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_ROLE_MAPPINGS (MAPPING_ID, ROLE_NAME, AUDIT_SCOPE) VALUES (UUID_STRING(), :role_name, :audit_scope);
$$

