CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EVIDENCE_REPLICATION(bundle_id STRING, target_region STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_REPLICATION_QUEUE (Q_ID, BUNDLE_ID, TARGET_REGION) VALUES (UUID_STRING(), :bundle_id, :target_region);
$$

