CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REPLICATION_LOG(q_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPLICATION_LOGS (LOG_ID, Q_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :q_id, :status, :details);
$$

