CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ATTESTATION_TEMPLATE(name STRING, body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ATTESTATION_TEMPLATES (TEMPLATE_ID, NAME, BODY) VALUES (UUID_STRING(), :name, :body);
$$

