CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_REGULATORY_RULE(name STRING, jurisdiction STRING, condition VARIANT, actions VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.REGULATORY_RULES t USING (SELECT :name AS nm, :jurisdiction AS jur, :condition AS cond, :actions AS acts, :enabled AS en) s ON t.NAME = s.nm AND t.JURISDICTION = s.jur WHEN MATCHED THEN UPDATE SET CONDITION = s.cond, ACTIONS = s.acts, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, JURISDICTION, CONDITION, ACTIONS, ENABLED) VALUES (UUID_STRING(), s.nm, s.jur, s.cond, s.acts, s.en);
$$

