CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REGULATORY_VIOLATION(rule_id STRING, subject_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REGULATORY_VIOLATIONS (VIOLATION_ID, RULE_ID, SUBJECT_REF, DETAILS) VALUES (UUID_STRING(), :rule_id, :subject_ref, :details);
$$

