CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REGULATORY_ESCROW(subject_ref STRING, hold_reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REGULATORY_ESCROWS (ESCROW_ID, SUBJECT_REF, HOLD_REASON) VALUES (UUID_STRING(), :subject_ref, :hold_reason);
$$

