CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_ACTION(operator STRING, action STRING, target_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ACTIONS (ACTION_ID, OPERATOR, ACTION, TARGET_REF, DETAILS) VALUES (UUID_STRING(), :operator, :action, :target_ref, :details);
$$

