CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATOR_ROLE(name STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ROLES (ROLE_ID, NAME, PERMISSIONS) VALUES (UUID_STRING(), :name, :permissions);
$$

