CREATE OR REPLACE PROCEDURE DOCGEN.START_OPERATOR_SESSION(operator STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_SESSIONS (SESSION_ID, OPERATOR, META) VALUES (UUID_STRING(), :operator, :meta);
$$

