CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POLICY_CHANGE_REQUEST(requested_by STRING, policy_id STRING, change JSON)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_CHANGE_REQUESTS (REQ_ID, REQUESTED_BY, POLICY_ID, CHANGE) VALUES (UUID_STRING(), :requested_by, :policy_id, :change);
$$

