CREATE OR REPLACE PROCEDURE DOCGEN.APPROVE_POLICY_CHANGE_REQUEST(req_id STRING, approved_by STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_APPROVALS (APPROVAL_ID, REQ_ID, APPROVED_BY, NOTES) VALUES (UUID_STRING(), :req_id, :approved_by, :notes);
$$

