CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DATA_RETENTION_LOG(policy_id STRING, target_ref STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_RETENTION_LOGS (LOG_ID, POLICY_ID, TARGET_REF, ACTION, DETAILS) VALUES (UUID_STRING(), :policy_id, :target_ref, :action, :details);
$$

