CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_DATA_ACCESS_POLICY(name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DATA_ACCESS_POLICIES t USING (SELECT :name AS nm, :rules AS r, :enabled AS en) s ON t.NAME = s.nm WHEN MATCHED THEN UPDATE SET RULES = s.r, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RULES, ENABLED) VALUES (UUID_STRING(), s.nm, s.r, s.en);
$$

