CREATE OR REPLACE PROCEDURE DOCGEN.BIND_ACCESS_POLICY(policy_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_POLICY_BINDINGS (BIND_ID, POLICY_ID, TARGET_REF) VALUES (UUID_STRING(), :policy_id, :target_ref);
$$

