CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REVIEW(target_ref STRING, schedule VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEWS (REVIEW_ID, TARGET_REF, SCHEDULE) VALUES (UUID_STRING(), :target_ref, :schedule);
$$

