CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCESS_REVIEW_RUN(review_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_RUNS (RUN_ID, REVIEW_ID, RESULT) VALUES (UUID_STRING(), :review_id, :result);
$$

