CREATE OR REPLACE PROCEDURE DOCGEN.ADD_SUPPORT_TICKET_UPDATE(ticket_id STRING, updated_by STRING, update_text STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_TICKET_UPDATES (UPDATE_ID, TICKET_ID, UPDATED_BY, UPDATE_TEXT) VALUES (UUID_STRING(), :ticket_id, :updated_by, :update_text);
$$

