CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SUPPORT_SLA_METRIC(period_start DATE, period_end DATE, avg_response_time_ms NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_SLA_METRICS (METRIC_ID, PERIOD_START, PERIOD_END, AVG_RESPONSE_TIME_MS) VALUES (UUID_STRING(), :period_start, :period_end, :avg_response_time_ms);
$$

