CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KPI_VALUE(kpi_id STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KPI_VALUES (VALUE_ID, KPI_ID, VALUE) VALUES (UUID_STRING(), :kpi_id, :value);
$$

