CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATIONAL_PLAYBOOK(name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATIONAL_PLAYBOOKS (PLAYBOOK_ID, NAME, STEPS) VALUES (UUID_STRING(), :name, :steps);
$$

