CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PLAYBOOK_RUN(playbook_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PLAYBOOK_RUNS (RUN_ID, PLAYBOOK_ID, RESULT) VALUES (UUID_STRING(), :playbook_id, :result);
$$

