CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHANGE_LOG(object_ref STRING, changed_by STRING, change_json VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHANGE_LOGS (CHANGE_ID, OBJECT_REF, CHANGED_BY, CHANGE_JSON) VALUES (UUID_STRING(), :object_ref, :changed_by, :change_json);
$$

