CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_AUDIT_ENTRY(object_type STRING, object_id STRING, audit_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_INDEX (IDX_ID, OBJECT_TYPE, OBJECT_ID, AUDIT_REF) VALUES (UUID_STRING(), :object_type, :object_id, :audit_ref);
$$

