CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POLICY_VERSION(policy_id STRING, version_number INT, content VARIANT, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_VERSIONS (VERSION_ID, POLICY_ID, VERSION_NUMBER, CONTENT, CREATED_BY) VALUES (UUID_STRING(), :policy_id, :version_number, :content, :created_by);
$$
