CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_VERIFICATION_STATS(period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERIFICATION_STATS (STAT_ID, PERIOD_START, PERIOD_END, TOTAL_VERIFICATIONS, SUCCESSFUL, FAILED)
SELECT UUID_STRING(), :period_start, :period_end, COUNT(*), SUM(CASE WHEN RESULT = 'PASS' THEN 1 ELSE 0 END), SUM(CASE WHEN RESULT <> 'PASS' THEN 1 ELSE 0 END)
FROM DOCGEN.SIGNATURE_VERIFICATIONS WHERE VERIFIED_AT BETWEEN :period_start AND :period_end;
$$

