CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_METRIC(session_id STRING, duration_ms INT, events_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_METRICS (METRIC_ID, SESSION_ID, DURATION_MS, EVENTS_COUNT) VALUES (UUID_STRING(), :session_id, :duration_ms, :events_count);
$$

