CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_ACCESS_TOKEN(token_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TOKEN_REVOCATIONS (REVOC_ID, TOKEN_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :token_id, :revoked_by, :reason);
UPDATE DOCGEN.ACCESS_TOKENS SET REVOKED = TRUE WHERE TOKEN_ID = :token_id;
$$
