CREATE OR REPLACE PROCEDURE DOCGEN.ADD_DOCUMENT_ANNOTATION(document_id STRING, page_number INT, annotator STRING, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_ANNOTATIONS (ANNOTATION_ID, DOCUMENT_ID, PAGE_NUMBER, ANNOTATOR, NOTE) VALUES (UUID_STRING(), :document_id, :page_number, :annotator, :note);
$$
