CREATE OR REPLACE PROCEDURE DOCGEN.DEPRECATE_TEMPLATE(template_id STRING, deprecate_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEPRECATIONS (DEPRECATION_ID, TEMPLATE_ID, DEPRECATE_AT, REASON) VALUES (UUID_STRING(), :template_id, :deprecate_at, :reason);
$$

