CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ANNOTATION_HISTORY(annotation_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANNOTATION_HISTORY (H_ID, ANNOTATION_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (UUID_STRING(), :annotation_id, :action, :performed_by, :details);
$$
