CREATE OR REPLACE PROCEDURE DOCGEN.SET_TEMPLATE_PERMISSIONS(template_id STRING, entity_ref STRING, permissions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_PERMISSIONS t USING (SELECT :template_id AS tid, :entity_ref AS er, :permissions AS perms) s ON t.TEMPLATE_ID = s.tid AND t.ENTITY_REF = s.er WHEN MATCHED THEN UPDATE SET PERMISSIONS = s.perms WHEN NOT MATCHED THEN INSERT (PERM_ID, TEMPLATE_ID, ENTITY_REF, PERMISSIONS) VALUES (UUID_STRING(), s.tid, s.er, s.perms);
$$
