CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_TEMPLATE_COMPATIBILITY(template_id STRING, platform STRING, supported BOOLEAN, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_COMPAT_MATRIX t USING (SELECT :template_id AS tid, :platform AS plat, :supported AS sup, :notes AS nts) s
ON t.TEMPLATE_ID = s.tid AND t.PLATFORM = s.plat
WHEN MATCHED THEN UPDATE SET SUPPORTED = s.sup, NOTES = s.nts, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (MATRIX_ID, TEMPLATE_ID, PLATFORM, SUPPORTED, NOTES) VALUES (UUID_STRING(), s.tid, s.plat, s.sup, s.nts);
$$

