CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_TEMPLATE_USAGE(template_id STRING, usage_date DATE, increment INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_USAGE_STATS t USING (SELECT :template_id AS tid, :usage_date AS ud, :increment AS inc) s ON t.TEMPLATE_ID = s.tid AND t.USAGE_DATE = s.ud WHEN MATCHED THEN UPDATE SET USAGE_COUNT = USAGE_COUNT + s.inc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (STATS_ID, TEMPLATE_ID, USAGE_DATE, USAGE_COUNT) VALUES (UUID_STRING(), s.tid, s.ud, s.inc);
$$
