CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_DOCUMENT_THUMBNAIL(document_id STRING, page_num INT, thumb_url STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_THUMBNAILS (THUMB_ID, DOCUMENT_ID, PAGE_NUM, THUMB_URL) VALUES (UUID_STRING(), :document_id, :page_num, :thumb_url);
$$
