CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_HEALTH_CHECK(template_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_HEALTH_CHECKS (HC_ID, TEMPLATE_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :template_id, :status, :details);
$$
