CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_CHANGE_LOG(template_id STRING, changed_by STRING, change JSON)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CHANGE_LOGS (LOG_ID, TEMPLATE_ID, CHANGED_BY, CHANGE) VALUES (UUID_STRING(), :template_id, :changed_by, :change);
$$
