CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PDF_STORAGE(bundle_id STRING, url STRING, size_bytes NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PDF_STORAGE_INDEX (INDEX_ID, BUNDLE_ID, URL, SIZE_BYTES) VALUES (UUID_STRING(), :bundle_id, :url, :size_bytes);
$$

