CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THUMBNAIL(bundle_id STRING, url STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THUMBNAIL_INDEX (THUMB_ID, BUNDLE_ID, URL) VALUES (UUID_STRING(), :bundle_id, :url);
$$

