CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_PUBLISH_LOG(queue_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PUBLISH_LOGS (LOG_ID, QUEUE_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :queue_id, :status, :details);
$$
