CREATE OR REPLACE PROCEDURE DOCGEN.STORE_OCR_OUTPUT(bundle_id STRING, page_number INT, text CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OCR_OUTPUTS (OCR_ID, BUNDLE_ID, PAGE_NUMBER, TEXT) VALUES (UUID_STRING(), :bundle_id, :page_number, :text);
$$

