CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_DEPLOY_HISTORY(template_id STRING, environment STRING, deployed_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEPLOY_HISTORY (DEP_ID, TEMPLATE_ID, ENVIRONMENT, DEPLOYED_BY, META) VALUES (UUID_STRING(), :template_id, :environment, :deployed_by, :meta);
$$
