CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_KEY_ROTATION(key_ref STRING, next_rotation TIMESTAMP_LTZ, interval_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_SCHEDULE (SCHEDULE_ID, KEY_REF, NEXT_ROTATION, INTERVAL_DAYS) VALUES (UUID_STRING(), :key_ref, :next_rotation, :interval_days);
$$

