CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ROTATION_LOG(schedule_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_LOGS (LOG_ID, SCHEDULE_ID, DETAILS) VALUES (UUID_STRING(), :schedule_id, :details);
$$

