CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_STABLE_HASH(bundle_id STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.STABLE_HASH_INDEX (HASH_ID, BUNDLE_ID, HASH) VALUES (UUID_STRING(), :bundle_id, :hash);
$$

