CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_DEPENDENCY(template_id STRING, depends_on_template_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEPENDENCY_GRAPH (EDGE_ID, TEMPLATE_ID, DEPENDS_ON_TEMPLATE_ID) VALUES (UUID_STRING(), :template_id, :depends_on_template_id);
$$
