CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ARCHIVE_HEALTH(target_stage STRING, last_synchronized TIMESTAMP_LTZ, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_HEALTH (HEALTH_ID, TARGET_STAGE, LAST_SYNCHRONIZED, STATUS, DETAILS) VALUES (UUID_STRING(), :target_stage, :last_synchronized, :status, :details);
$$

