CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_CHUNK_REASSEMBLY(bundle_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHUNK_REASSEMBLY_JOBS (JOB_ID, BUNDLE_ID) VALUES (UUID_STRING(), :bundle_id);
$$

