CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_REVIEWER(template_id STRING, reviewer STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_REVIEWERS (REVIEWER_ID, TEMPLATE_ID, REVIEWER) VALUES (UUID_STRING(), :template_id, :reviewer);
$$
