CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHUNK_REASSEMBLY_LOG(job_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHUNK_REASSEMBLY_LOGS (LOG_ID, JOB_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :job_id, :status, :details);
$$

