CREATE OR REPLACE PROCEDURE DOCGEN.RUN_CONTENT_INTEGRITY_CHECK(bundle_id STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONTENT_INTEGRITY_CHECKS (CHECK_ID, BUNDLE_ID, CHECKSUM, RESULT) VALUES (UUID_STRING(), :bundle_id, :checksum, 'PENDING');
$$

