CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_CONTENT_TAMPER_ALERT(bundle_id STRING, reason STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONTENT_TAMPER_ALERTS (ALERT_ID, BUNDLE_ID, REASON, META) VALUES (UUID_STRING(), :bundle_id, :reason, :meta);
$$

