CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_APPROVAL_REQUEST(template_id STRING, policy_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_APPROVAL_REQUESTS (REQ_ID, TEMPLATE_ID, POLICY_ID) VALUES (UUID_STRING(), :template_id, :policy_id);
$$
