CREATE OR REPLACE PROCEDURE DOCGEN.ISSUE_ACCESS_TOKEN(subject_ref STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_TOKEN_ISSUANCE (ISSUE_ID, SUBJECT_REF, TOKEN_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :subject_ref, :token_hash, :expires_at);
$$

