CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_ACCESS_TOKEN(issue_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_TOKEN_REVOCATIONS (REV_ID, ISSUE_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :issue_id, :revoked_by, :reason);
$$

