CREATE OR REPLACE PROCEDURE DOCGEN.SET_KEY_USAGE_QUOTA(key_ref_id STRING, max_operations INT, window_seconds INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KEY_USAGE_QUOTAS t USING (SELECT :key_ref_id AS kr, :max_operations AS mo, :window_seconds AS ws) s ON t.KEY_REF_ID = s.kr WHEN MATCHED THEN UPDATE SET MAX_OPERATIONS = s.mo, WINDOW_SECONDS = s.ws WHEN NOT MATCHED THEN INSERT (QUOTA_ID, KEY_REF_ID, MAX_OPERATIONS, WINDOW_SECONDS) VALUES (UUID_STRING(), s.kr, s.mo, s.ws);
$$

