CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_KEY_USAGE_COUNTER(key_ref_id STRING, window_start TIMESTAMP_LTZ, increment INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KEY_USAGE_COUNTERS t USING (SELECT :key_ref_id AS kr, :window_start AS ws, :increment AS inc) s ON t.KEY_REF_ID = s.kr AND t.WINDOW_START = s.ws WHEN MATCHED THEN UPDATE SET OPS = OPS + s.inc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (COUNTER_ID, KEY_REF_ID, WINDOW_START, OPS) VALUES (UUID_STRING(), s.kr, s.ws, s.inc);
$$

