CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_TEMPLATE_EDIT_LOCK(template_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_EDIT_LOCKS (LOCK_ID, TEMPLATE_ID, LOCKED_BY) VALUES (UUID_STRING(), :template_id, :locked_by);
$$
