CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COMPLIANCE_CHECK_TEMPLATE(name STRING, check_definition VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CHECK_TEMPLATES (TEMPLATE_ID, NAME, CHECK_DEFINITION) VALUES (UUID_STRING(), :name, :check_definition);
$$

