CREATE OR REPLACE PROCEDURE DOCGEN.SEND_TEMPLATE_USAGE_NOTIFICATION(template_id STRING, event STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_NOTIFICATIONS (NOTIF_ID, TEMPLATE_ID, EVENT, META) VALUES (UUID_STRING(), :template_id, :event, :meta);
$$
