CREATE OR REPLACE PROCEDURE DOCGEN.RUN_COMPLIANCE_CHECK(template_id STRING, scope VARIANT, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_RUNS (RUN_ID, TEMPLATE_ID, SCOPE, RESULT) VALUES (UUID_STRING(), :template_id, :scope, :result);
$$

