CREATE OR REPLACE PROCEDURE DOCGEN.SET_TEMPLATE_AUTO_ARCHIVE_RULE(template_filter VARIANT, archive_after_days INT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_AUTO_ARCHIVE_RULES (RULE_ID, TEMPLATE_FILTER, ARCHIVE_AFTER_DAYS, ENABLED) VALUES (UUID_STRING(), :template_filter, :archive_after_days, :enabled);
$$
