CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_EXPORT_FILE(export_id STRING, file_path STRING, size_bytes NUMBER, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_AUDIT_INDEX (IDX_ID, EXPORT_ID, FILE_PATH, SIZE_BYTES, CHECKSUM) VALUES (UUID_STRING(), :export_id, :file_path, :size_bytes, :checksum);
$$

