CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_SCHEMA_COMMENT(template_id STRING, comment TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_SCHEMA_COMMENTS (COMMENT_ID, TEMPLATE_ID, COMMENT) VALUES (UUID_STRING(), :template_id, :comment);
$$
