CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BATCH_JOB_SCHEDULE(name STRING, cron_expr STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_JOB_SCHEDULES (SCHEDULE_ID, NAME, CRON_EXPR) VALUES (UUID_STRING(), :name, :cron_expr);
$$

