CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_TEMPLATE_DOCUMENTATION(template_id STRING, doc_content CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_DOCUMENTATION t USING (SELECT :template_id AS tid, :doc_content AS dc) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET DOC_CONTENT = s.dc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DOC_ID, TEMPLATE_ID, DOC_CONTENT) VALUES (UUID_STRING(), s.tid, s.dc);
$$
