CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BATCH_JOB_RUN(schedule_id STRING, status STRING, result VARIANT, ended_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_JOB_RUNS (RUN_ID, SCHEDULE_ID, STATUS, RESULT, ENDED_AT) VALUES (UUID_STRING(), :schedule_id, :status, :result, :ended_at);
$$

