CREATE OR REPLACE PROCEDURE DOCGEN.START_TEMPLATE_EDITOR_SESSION(template_id STRING, editor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_EDITOR_SESSIONS (SESSION_ID, TEMPLATE_ID, EDITOR) VALUES (UUID_STRING(), :template_id, :editor);
$$
