CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_EDITOR_ACTIVITY(session_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_EDITOR_ACTIVITY (ACT_ID, SESSION_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :session_id, :action, :details);
$$
