CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SCHEDULED_TASK_ERROR(task_name STRING, error_msg STRING, trace VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SCHEDULED_TASK_ERRORS (ERROR_ID, TASK_NAME, ERROR_MSG, TRACE) VALUES (UUID_STRING(), :task_name, :error_msg, :trace);
$$

