CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DEVELOPER_KEY(developer STRING, key_hash STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVELOPER_KEYS (DEV_KEY_ID, DEVELOPER, KEY_HASH, SCOPE) VALUES (UUID_STRING(), :developer, :key_hash, :scope);
$$

