CREATE OR REPLACE PROCEDURE DOCGEN.AUTOSAVE_TEMPLATE(template_id STRING, saved_by STRING, save_content VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_AUTOSAVES (SAVE_ID, TEMPLATE_ID, SAVED_BY, SAVE_CONTENT) VALUES (UUID_STRING(), :template_id, :saved_by, :save_content);
$$
