CREATE OR REPLACE PROCEDURE DOCGEN.REVERT_TEMPLATE_TO_VERSION(template_id STRING, reverted_to_version INT, reverted_by STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_REVERT_ACTIONS (ACTION_ID, TEMPLATE_ID, REVERTED_TO_VERSION, REVERTED_BY, NOTES) VALUES (UUID_STRING(), :template_id, :reverted_to_version, :reverted_by, :notes);
$$
