CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEVELOPER_KEY_USAGE(dev_key_id STRING, endpoint STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVELOPER_KEY_USAGE (USG_ID, DEV_KEY_ID, ENDPOINT, META) VALUES (UUID_STRING(), :dev_key_id, :endpoint, :meta);
$$

