CREATE OR REPLACE PROCEDURE DOCGEN.APPROVE_TEMPLATE_PUBLISH(template_id STRING, approver STRING, comments STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PUBLISH_APPROVALS (APPROVAL_ID, TEMPLATE_ID, APPROVER, COMMENTS, APPROVED_AT) VALUES (UUID_STRING(), :template_id, :approver, :comments, CURRENT_TIMESTAMP());
$$
