CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_PUBLISH_DENIAL(template_id STRING, denied_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PUBLISH_DENIALS (DENIAL_ID, TEMPLATE_ID, DENIED_BY, REASON) VALUES (UUID_STRING(), :template_id, :denied_by, :reason);
$$
