CREATE OR REPLACE PROCEDURE DOCGEN.STORE_OAUTH_TOKEN(client_id STRING, subject_ref STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_TOKENS (TOKEN_ID, CLIENT_ID, SUBJECT_REF, TOKEN_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :client_id, :subject_ref, :token_hash, :expires_at);
$$

