CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_OAUTH_TOKEN(token_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_REVOCATIONS (REV_ID, TOKEN_ID, REVOKED_BY, REASON) VALUES (UUID_STRING(), :token_id, :revoked_by, :reason);
$$

