CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_TEMPLATE_PUBLISH_METRICS(template_id STRING, publish_attempts INT, last_attempt_at TIMESTAMP_LTZ, success_rate FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_PUBLISH_METRICS t USING (SELECT :template_id AS tid, :publish_attempts AS pa, :last_attempt_at AS la, :success_rate AS sr) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET PUBLISH_ATTEMPTS = s.pa, LAST_ATTEMPT_AT = s.la, SUCCESS_RATE = s.sr WHEN NOT MATCHED THEN INSERT (METRIC_ID, TEMPLATE_ID, PUBLISH_ATTEMPTS, LAST_ATTEMPT_AT, SUCCESS_RATE) VALUES (UUID_STRING(), s.tid, s.pa, s.la, s.sr);
$$
