CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_OPENID_CLIENT(name STRING, jwks CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPENID_CLIENTS (CLIENT_ID, NAME, JWKS) VALUES (UUID_STRING(), :name, :jwks);
$$

