CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_DEPRECATION_LOG(template_id STRING, deprecated_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEPRECATION_LOGS (LOG_ID, TEMPLATE_ID, DEPRECATED_BY, REASON) VALUES (UUID_STRING(), :template_id, :deprecated_by, :reason);
$$
