CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_CLONE_JOB(source_template_id STRING, target_template_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CLONE_JOBS (JOB_ID, SOURCE_TEMPLATE_ID, TARGET_TEMPLATE_ID) VALUES (UUID_STRING(), :source_template_id, :target_template_id);
$$
