CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPENID_AUDIT(client_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPENID_AUDITS (AUDIT_ID, CLIENT_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :client_id, :action, :details);
$$

