CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SECURITY_INCIDENT(title STRING, description STRING, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SECURITY_INCIDENTS (INCIDENT_ID, TITLE, DESCRIPTION, SEVERITY) VALUES (UUID_STRING(), :title, :description, :severity);
$$

