CREATE OR REPLACE PROCEDURE DOCGEN.ADD_SECURITY_INCIDENT_UPDATE(incident_id STRING, updated_by STRING, update_text STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SECURITY_INCIDENT_UPDATES (UPDATE_ID, INCIDENT_ID, UPDATED_BY, UPDATE_TEXT) VALUES (UUID_STRING(), :incident_id, :updated_by, :update_text);
$$

