CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COMPLIANCE_CERT_REQUEST(requestor STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CERT_REQUESTS (REQ_ID, REQUESTOR, SCOPE) VALUES (UUID_STRING(), :requestor, :scope);
$$

