CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_INTEGRATION_LOG(mapping_id STRING, event STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_INTEGRATION_LOGS (LOG_ID, MAPPING_ID, EVENT, DETAILS) VALUES (UUID_STRING(), :mapping_id, :event, :details);
$$
