CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PSEUDONYM_MAPPING(original_ref STRING, pseudo_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PSEUDONYMIZATION_MAPPINGS (MAP_ID, ORIGINAL_REF, PSEUDO_REF) VALUES (UUID_STRING(), :original_ref, :pseudo_ref);
$$

