CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_USAGE_EXPORT(template_id STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_EXPORTS (EXPORT_ID, TEMPLATE_ID, REQUESTED_BY) VALUES (UUID_STRING(), :template_id, :requested_by);
$$
