CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EMAIL(template_id STRING, recipient STRING, context VARIANT, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_QUEUE (QUEUE_ID, TEMPLATE_ID, RECIPIENT, CONTEXT, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :template_id, :recipient, :context, :next_attempt_at);
$$

