CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EMAIL_DELIVERY_LOG(queue_id STRING, status STRING, http_status INT, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_DELIVERY_LOG (LOG_ID, QUEUE_ID, STATUS, HTTP_STATUS, RESPONSE) VALUES (UUID_STRING(), :queue_id, :status, :http_status, :response);
$$

