CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SMS_TEMPLATE(template_id STRING, name STRING, body STRING, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SMS_TEMPLATES t
USING (SELECT :template_id AS tid, :name AS nm, :body AS bd, :created_by AS cb) s
ON t.TEMPLATE_ID = s.tid
WHEN MATCHED THEN UPDATE SET NAME = s.nm, BODY = s.bd
WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, BODY, CREATED_BY) VALUES (s.tid, s.nm, s.bd, s.cb);
$$

