CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PUSH(template_id STRING, device_token STRING, context VARIANT, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PUSH_QUEUE (QUEUE_ID, TEMPLATE_ID, DEVICE_TOKEN, CONTEXT, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :template_id, :device_token, :context, :next_attempt_at);
$$

