CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PUSH_DELIVERY_LOG(queue_id STRING, status STRING, provider_response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PUSH_DELIVERY_LOG (LOG_ID, QUEUE_ID, STATUS, PROVIDER_RESPONSE) VALUES (UUID_STRING(), :queue_id, :status, :provider_response);
$$

