CREATE OR REPLACE PROCEDURE DOCGEN.SUBSCRIBE_EVENT(event_name STRING, target STRING, delivery_method STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_SUBSCRIBERS (SUB_ID, EVENT_NAME, TARGET, DELIVERY_METHOD) VALUES (UUID_STRING(), :event_name, :target, :delivery_method);
$$

