CREATE OR REPLACE PROCEDURE DOCGEN.BROADCAST_EVENT(event_name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_BROADCASTS (BROADCAST_ID, EVENT_NAME, PAYLOAD) VALUES (UUID_STRING(), :event_name, :payload);
$$

