CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EVENT_DISPATCH(broadcast_id STRING, sub_id STRING, target STRING, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_DISPATCH_QUEUE (Q_ID, BROADCAST_ID, SUB_ID, TARGET, NEXT_ATTEMPT_AT) VALUES (UUID_STRING(), :broadcast_id, :sub_id, :target, :next_attempt_at);
$$

