CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DISPATCH_LOG(q_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DISPATCH_LOGS (LOG_ID, Q_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :q_id, :status, :response);
$$

