CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_AUTO_SUGGEST_JOB(scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUTO_SUGGEST_JOBS (JOB_ID, SCHEDULED_AT) VALUES (UUID_STRING(), :scheduled_at);
$$

