CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_AUTO_SUGGEST_LOG(job_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUTO_SUGGEST_LOGS (LOG_ID, JOB_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :job_id, :status, :details);
$$

