CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_USER_FEEDBACK(user_ref STRING, target_ref STRING, rating INT, comments STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_FEEDBACK (FB_ID, USER_REF, TARGET_REF, RATING, COMMENTS) VALUES (UUID_STRING(), :user_ref, :target_ref, :rating, :comments);
$$

