CREATE OR REPLACE PROCEDURE DOCGEN.EVALUATE_USER_SATISFACTION(target_ref STRING, threshold FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE avg_rating FLOAT;
avg_rating := (SELECT AVG(RATING) FROM DOCGEN.USER_FEEDBACK WHERE TARGET_REF = :target_ref);
IF avg_rating IS NULL THEN
  avg_rating := 0;
END IF;
INSERT INTO DOCGEN.USER_SAT_ALERTS (ALERT_ID, TARGET_REF, THRESHOLD, LAST_EVALUATED, STATUS) VALUES (UUID_STRING(), :target_ref, :threshold, CURRENT_TIMESTAMP(), CASE WHEN avg_rating < :threshold THEN 'ALERT' ELSE 'OK' END);
$$

