CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_USER_REPORT(user_ref STRING, report_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_REPORTS (REPORT_ID, USER_REF, REPORT_TYPE, PAYLOAD) VALUES (UUID_STRING(), :user_ref, :report_type, :payload);
$$

