CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_REPLAY_LOG(replay_id STRING, event_ts TIMESTAMP_LTZ, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_REPLAY_LOGS (LOG_ID, REPLAY_ID, EVENT_TS, EVENT_TYPE, PAYLOAD) VALUES (UUID_STRING(), :replay_id, :event_ts, :event_type, :payload);
$$

