CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_PROVIDER_CONFIG(provider_id STRING, name STRING, type STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_CONFIGS t USING (SELECT :provider_id AS pid, :name AS nm, :type AS tp, :config AS cfg, :enabled AS en) s ON t.PROVIDER_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, TYPE = s.tp, CONFIG = s.cfg, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (PROVIDER_ID, NAME, TYPE, CONFIG, ENABLED) VALUES (s.pid, s.nm, s.tp, s.cfg, s.en);
$$
