CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_DEVICE_FINGERPRINT(signer_id STRING, device_info VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_FINGERPRINTS (FP_ID, SIGNER_ID, DEVICE_INFO) VALUES (UUID_STRING(), :signer_id, :device_info);
$$

