CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_HEALTH(provider_id STRING, status STRING, last_check TIMESTAMP_LTZ, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_HEALTH (HEALTH_ID, PROVIDER_ID, STATUS, LAST_CHECK, DETAILS) VALUES (UUID_STRING(), :provider_id, :status, :last_check, :details);
$$
