CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_PROVIDER_ALERT(provider_id STRING, severity STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ALERTS (ALERT_ID, PROVIDER_ID, SEVERITY, MESSAGE) VALUES (UUID_STRING(), :provider_id, :severity, :message);
$$
