CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_TEMPLATE(signer_id STRING, template VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES (TEMPLATE_ID, SIGNER_ID, TEMPLATE) VALUES (UUID_STRING(), :signer_id, :template);
$$

