CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_WEBHOOK_ENDPOINT(name STRING, url STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_ENDPOINTS (ENDPOINT_ID, NAME, URL, SECRET_HASH) VALUES (UUID_STRING(), :name, :url, :secret_hash);
$$
