CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH(signer_id STRING, match_score FLOAT, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCHES (MATCH_ID, SIGNER_ID, MATCH_SCORE, META) VALUES (UUID_STRING(), :signer_id, :match_score, :meta);
$$

