CREATE OR REPLACE PROCEDURE DOCGEN.INGEST_WEBHOOK_PAYLOAD(endpoint_id STRING, payload VARIANT, headers VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_INBOUND (INBOUND_ID, ENDPOINT_ID, PAYLOAD, HEADERS) VALUES (UUID_STRING(), :endpoint_id, :payload, :headers);
$$
