CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_WEBHOOK_PROCESSING(inbound_id STRING, next_run_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_PROCESS_QUEUE (Q_ID, INBOUND_ID, NEXT_RUN_AT) VALUES (UUID_STRING(), :inbound_id, :next_run_at);
$$
