CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DEVICE_TRUST_SCORE(device_id STRING, trust_score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_TRUST_SCORES t USING (SELECT :device_id AS did, :trust_score AS ts) s ON t.DEVICE_ID = s.did WHEN MATCHED THEN UPDATE SET TRUST_SCORE = s.ts, COMPUTED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SCORE_ID, DEVICE_ID, TRUST_SCORE) VALUES (UUID_STRING(), s.did, s.ts);
$$

