CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_WEBHOOK_ERROR(q_id STRING, error_msg STRING, trace VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_ERROR_LOGS (LOG_ID, Q_ID, ERROR_MSG, TRACE) VALUES (UUID_STRING(), :q_id, :error_msg, :trace);
$$
