CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_SESSION_EVENT(session_id STRING, event_ref STRING, event_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_EVENT_INDEX (SEI_ID, SESSION_ID, EVENT_REF, EVENT_TYPE) VALUES (UUID_STRING(), :session_id, :event_ref, :event_type);
$$

