CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_SESSION_ALERT(session_id STRING, alert_type STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_ALERTS (ALERT_ID, SESSION_ID, ALERT_TYPE, META) VALUES (UUID_STRING(), :session_id, :alert_type, :meta);
$$

