CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_WEBHOOK_RETRY_POLICY(name STRING, backoff_seconds ARRAY, max_attempts INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_RETRY_POLICY (POLICY_ID, NAME, BACKOFF_SECONDS, MAX_ATTEMPTS) VALUES (UUID_STRING(), :name, :backoff_seconds, :max_attempts);
$$
