CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_ANOMALY_SCORE(session_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_ANOMALY_SCORES (SCORE_ID, SESSION_ID, SCORE) VALUES (UUID_STRING(), :session_id, :score);
$$

