CREATE OR REPLACE PROCEDURE DOCGEN.MOVE_TO_WEBHOOK_DLQ(inbound_id STRING, error_msg STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_DLQ (DLQ_ID, INBOUND_ID, ERROR_MSG) VALUES (UUID_STRING(), :inbound_id, :error_msg);
$$
