CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_HEALTH(provider_name STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_HEALTH (HEALTH_ID, PROVIDER_NAME, STATUS, DETAILS) VALUES (UUID_STRING(), :provider_name, :status, :details);
$$

