CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SESSION_TOKEN(subject_ref STRING, token_hash STRING, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_TOKENS (SESSION_ID, SUBJECT_REF, TOKEN_HASH, EXPIRES_AT, META) VALUES (UUID_STRING(), :subject_ref, :token_hash, :expires_at, :meta);
$$
