CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PROVIDER_FAILOVER_RULE(primary_provider STRING, secondary_provider STRING, conditions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_FAILOVER_RULES (RULE_ID, PRIMARY_PROVIDER, SECONDARY_PROVIDER, CONDITIONS) VALUES (UUID_STRING(), :primary_provider, :secondary_provider, :conditions);
$$

