CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_USER_DEVICE(user_ref STRING, device_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_DEVICES (DEVICE_ID, USER_REF, DEVICE_META) VALUES (UUID_STRING(), :user_ref, :device_meta);
$$
