CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_SWITCH_LOG(rule_id STRING, from_provider STRING, to_provider STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_SWITCH_LOGS (LOG_ID, RULE_ID, FROM_PROVIDER, TO_PROVIDER, DETAILS) VALUES (UUID_STRING(), :rule_id, :from_provider, :to_provider, :details);
$$

