CREATE OR REPLACE PROCEDURE DOCGEN.STORE_DEVICE_FINGERPRINT(device_id STRING, fingerprint_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_FINGERPRINTS (FP_ID, DEVICE_ID, FINGERPRINT_HASH) VALUES (UUID_STRING(), :device_id, :fingerprint_hash);
$$
