CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ENCRYPTION_KEY(key_alias STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ENCRYPTION_KEYS_METADATA (KEY_ID, KEY_ALIAS, META) VALUES (UUID_STRING(), :key_alias, :meta);
$$

