CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_KEY_ROTATION_REQUEST(key_id STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_REQUESTS (REQ_ID, KEY_ID, REQUESTED_BY) VALUES (UUID_STRING(), :key_id, :requested_by);
$$

