CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LIVENESS_CHECK(session_id STRING, check_type STRING, result STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LIVENESS_CHECKS (CHECK_ID, SESSION_ID, CHECK_TYPE, RESULT, DETAILS) VALUES (UUID_STRING(), :session_id, :check_type, :result, :details);
$$
