CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_CERTIFICATE(subject STRING, issuer STRING, not_before TIMESTAMP_LTZ, not_after TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERTIFICATE_INVENTORY (CERT_ID, SUBJECT, ISSUER, NOT_BEFORE, NOT_AFTER, META) VALUES (UUID_STRING(), :subject, :issuer, :not_before, :not_after, :meta);
$$

