CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_MONITORING_RULE(name STRING, expression STRING, severity STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.MONITORING_RULES t USING (SELECT :name AS nm, :expression AS expr, :severity AS sev, :enabled AS en) s ON t.NAME = s.nm WHEN MATCHED THEN UPDATE SET EXPRESSION = s.expr, SEVERITY = s.sev, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, EXPRESSION, SEVERITY, ENABLED) VALUES (UUID_STRING(), s.nm, s.expr, s.sev, s.en);
$$
