CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_HSM_INTEGRATION_REQUEST(purpose STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HSM_INTEGRATION_REQUESTS (REQ_ID, PURPOSE, PAYLOAD) VALUES (UUID_STRING(), :purpose, :payload);
$$

