CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INCIDENT_PLAYBOOK(incident_type STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_PLAYBOOKS (PLAYBOOK_ID, INCIDENT_TYPE, STEPS) VALUES (UUID_STRING(), :incident_type, :steps);
$$
