CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNING_POLICY_RULE(name STRING, conditions VARIANT, actions VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNING_POLICY_RULES t USING (SELECT :name AS nm, :conditions AS cond, :actions AS acts, :enabled AS en) s ON t.NAME = s.nm WHEN MATCHED THEN UPDATE SET CONDITIONS = s.cond, ACTIONS = s.acts, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, CONDITIONS, ACTIONS, ENABLED) VALUES (UUID_STRING(), s.nm, s.cond, s.acts, s.en);
$$

