CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SERVICE_HEALTH_CHECK(service_ref STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_HEALTH_CHECKS (HC_ID, SERVICE_REF, STATUS, DETAILS) VALUES (UUID_STRING(), :service_ref, :status, :details);
$$
