CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_BREACH(sla_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_BREACHES (BREACH_ID, SLA_ID, DETAILS) VALUES (UUID_STRING(), :sla_id, :details);
$$
