CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_TRUST_SCORE_AGGREGATE(account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TRUST_SCORE_AGGREGATES (AGG_ID, ACCOUNT_ID, AVG_TRUST)
SELECT UUID_STRING(), :account_id, AVG(TRUST_SCORE) FROM DOCGEN.DEVICE_TRUST_SCORES WHERE DEV_ID IN (SELECT FP_ID FROM DOCGEN.DEVICE_FINGERPRINTS WHERE SIGNER_ID IN (SELECT SIGNER_ID FROM DOCGEN.SIGNERS WHERE ACCOUNT_ID = :account_id));
$$

