CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_VIOLATION(sla_id STRING, account_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_VIOLATION_LOGS (LOG_ID, SLA_ID, ACCOUNT_ID, DETAILS) VALUES (UUID_STRING(), :sla_id, :account_id, :details);
$$

