CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INCIDENT_RESPONSE_PLAYBOOK(name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_RESPONSE_PLAYBOOKS (PLAYBOOK_ID, NAME, STEPS) VALUES (UUID_STRING(), :name, :steps);
$$

