CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ONCALL_ROSTER_ENTRY(operator STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, role STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ONCALL_ROSTER (ROSTER_ID, OPERATOR, START_AT, END_AT, ROLE) VALUES (UUID_STRING(), :operator, :start_at, :end_at, :role);
$$

