CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_ESCALATION_RUN(policy_id STRING, incident_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ESCALATION_RUNS (RUN_ID, POLICY_ID, INCIDENT_ID, RESULT) VALUES (UUID_STRING(), :policy_id, :incident_id, :result);
$$

