CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SLA_DEFINITION(name STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_DEFINITIONS (SLA_ID, NAME, METRICS) VALUES (UUID_STRING(), :name, :metrics);
$$

