CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACTIVITY_DASHBOARD(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACTIVITY_DASHBOARDS (DASH_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

