CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DASHBOARD_RUN(dash_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DASHBOARD_RUNS (RUN_ID, DASH_ID, RESULT) VALUES (UUID_STRING(), :dash_id, :result);
$$

