CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXPORT_RETRY(export_id STRING, attempt_number INT, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_RETRIES (RETRY_ID, EXPORT_ID, ATTEMPT_NUMBER, STATUS, DETAILS) VALUES (UUID_STRING(), :export_id, :attempt_number, :status, :details);
$$

