CREATE OR REPLACE PROCEDURE DOCGEN.ADD_DATA_LINEAGE_EDGE(source_ref STRING, target_ref STRING, transformation VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_LINEAGE_EDGES (EDGE_ID, SOURCE_REF, TARGET_REF, TRANSFORMATION) VALUES (UUID_STRING(), :source_ref, :target_ref, :transformation);
$$

