CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LINEAGE_RECONCILIATION(edge_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LINEAGE_RECONCILIATIONS (RECON_ID, EDGE_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :edge_id, :status, :details);
$$

