CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_DATA_MIGRATION_JOB(description STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_MIGRATION_JOBS (JOB_ID, DESCRIPTION) VALUES (UUID_STRING(), :description);
$$

