CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_ETAG(object_ref STRING, etag STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ETAG_INDEX (ETAG_ID, OBJECT_REF, ETAG) VALUES (UUID_STRING(), :object_ref, :etag);
$$

