CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_REPLAYABILITY_ALERT(check_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPLAYABILITY_ALERTS (ALERT_ID, CHECK_ID, META) VALUES (UUID_STRING(), :check_id, :meta);
$$

