CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_CONSENT_NOTIFICATION(consent_id STRING, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_NOTIFICATIONS (NOTIF_ID, CONSENT_ID, CHANNEL, STATUS) VALUES (UUID_STRING(), :consent_id, :channel, 'PENDING');
$$

