CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT_NOTIFICATION_LOG(notif_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_NOTIFICATION_LOG (LOG_ID, NOTIF_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :notif_id, :status, :response);
$$

