CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESCALATION_HISTORY(rule_id STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_HISTORY (HIST_ID, RULE_ID, CONTEXT, RAISED_AT) VALUES (UUID_STRING(), :rule_id, :context, CURRENT_TIMESTAMP());
$$

