CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_TEST_VECTOR(bundle_id STRING, embedding VARIANT, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEST_VECTORS (VECTOR_ID, BUNDLE_ID, EMBEDDING, METADATA) VALUES (UUID_STRING(), :bundle_id, PARSE_JSON(:embedding), :metadata);
$$

