CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_QUALITY_CHECK(check_id STRING, name STRING, definition VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.QUALITY_CHECKS t USING (SELECT :check_id AS cid, :name AS nm, :definition AS def, :enabled AS en) s ON t.CHECK_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, DEFINITION = s.def, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (CHECK_ID, NAME, DEFINITION, ENABLED) VALUES (s.cid, s.nm, s.def, s.en);
$$

