CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_QUALITY_ALERT(check_id STRING, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUALITY_ALERTS (ALERT_ID, CHECK_ID, SEVERITY) VALUES (UUID_STRING(), :check_id, :severity);
$$

