CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_AUDIT_RETENTION_POLICY(policy_id STRING, name STRING, retention_days INT, applied_to VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.AUDIT_RETENTION_POLICIES t USING (SELECT :policy_id AS pid, :name AS nm, :retention_days AS rd, :applied_to AS at, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RETENTION_DAYS = s.rd, APPLIED_TO = s.at, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RETENTION_DAYS, APPLIED_TO, ENABLED) VALUES (s.pid, s.nm, s.rd, s.at, s.en);
$$

