CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_AUDIT(rule_id STRING, changed_by STRING, change_payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_AUDIT_TRAIL (AUDIT_ID, RULE_ID, CHANGED_BY, CHANGE_PAYLOAD) VALUES (UUID_STRING(), :rule_id, :changed_by, :change_payload);
$$

