CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THREAT_EVENT(feed_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_EVENTS (EVENT_ID, FEED_ID, DETAILS) VALUES (UUID_STRING(), :feed_id, :details);
$$

