CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FRAUD_INCIDENT(bundle_id STRING, risk_score FLOAT, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_INCIDENTS (INCIDENT_ID, BUNDLE_ID, RISK_SCORE, STATUS) VALUES (UUID_STRING(), :bundle_id, :risk_score, :status);
$$

