CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_COMPLIANCE_APPROVAL(request_id STRING, approver STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_APPROVALS (APPROVAL_ID, REQUEST_ID, APPROVER, NOTES) VALUES (UUID_STRING(), :request_id, :approver, :notes);
$$

