CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_EXPORT_PERMISSION(export_id STRING, granted_to STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_PERMISSIONS (PERM_ID, EXPORT_ID, GRANTED_TO) VALUES (UUID_STRING(), :export_id, :granted_to);
$$

