CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PRIVACY_REQUEST(subject_ref STRING, request_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUESTS (PR_ID, SUBJECT_REF, REQUEST_TYPE) VALUES (UUID_STRING(), :subject_ref, :request_type);
$$

