CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIVACY_REQUEST_LOG(pr_id STRING, status STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUEST_LOGS (LOG_ID, PR_ID, STATUS, NOTES) VALUES (UUID_STRING(), :pr_id, :status, :notes);
$$

