CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ENROLLMENT_REQUEST(subject_ref STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ENROLLMENT_REQUESTS (REQUEST_ID, SUBJECT_REF, META) VALUES (UUID_STRING(), :subject_ref, :meta);
$$

