CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT_AUDIT(consent_id STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_AUDIT (AUDIT_ID, CONSENT_ID, CHANGES) VALUES (UUID_STRING(), :consent_id, :changes);
$$

