CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_ATTACHMENT(bundle_id STRING, path STRING, content_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ATTACHMENT_INDEX (ATTACH_ID, BUNDLE_ID, PATH, CONTENT_HASH) VALUES (UUID_STRING(), :bundle_id, :path, :content_hash);
$$

