CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_TEMPLATE_METRIC(template_id STRING, usage_inc INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_METRICS t USING (SELECT :template_id AS tid, :usage_inc AS ui) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET USAGE_COUNT = COALESCE(t.USAGE_COUNT,0) + s.ui, LAST_USED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (METRIC_ID, TEMPLATE_ID, USAGE_COUNT, LAST_USED_AT) VALUES (UUID_STRING(), s.tid, s.ui, CURRENT_TIMESTAMP());
$$

