CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_ARCHIVE_STATUS(archive_id STRING, status STRING, stage_path STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ARCHIVE_STATUS t USING (SELECT :archive_id AS aid, :status AS st, :stage_path AS sp) s ON t.ARCHIVE_ID = s.aid WHEN MATCHED THEN UPDATE SET STATUS = s.st, STAGE_PATH = s.sp WHEN NOT MATCHED THEN INSERT (ARCHIVE_ID, STATUS, STAGE_PATH) VALUES (s.aid, s.st, s.sp);
$$

