CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CLAUSE_USAGE(clause_id STRING, template_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLAUSE_USAGE (USAGE_ID, CLAUSE_ID, TEMPLATE_ID, ACCOUNT_ID) VALUES (UUID_STRING(), :clause_id, :template_id, :account_id);
$$

