CREATE OR REPLACE PROCEDURE DOCGEN.STORE_TEMPLATE_PREVIEW(template_id STRING, rendered_cblob CLOB, ttl_seconds INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PREVIEW_CACHE (PREVIEW_ID, TEMPLATE_ID, RENDERED_CLOB, TTL_SECONDS) VALUES (UUID_STRING(), :template_id, :rendered_cblob, :ttl_seconds);
$$

