CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHAIN_OF_TRUST(bundle_id STRING, hash_chain VARIANT, anchor_txid STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHAIN_OF_TRUST (COT_ID, BUNDLE_ID, HASH_CHAIN, ANCHOR_TXID) VALUES (UUID_STRING(), :bundle_id, :hash_chain, :anchor_txid);
$$

