CREATE OR REPLACE PROCEDURE DOCGEN.INVALIDATE_TEMPLATE_PREVIEWS(template_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PREVIEW_INVALIDATIONS (INVALID_ID, TEMPLATE_ID, REASON) VALUES (UUID_STRING(), :template_id, :reason);
$$

