CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ANCHOR_AUDIT(cot_id STRING, anchor_txid STRING, verified BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHOR_AUDIT (AUDIT_ID, COT_ID, ANCHOR_TXID, VERIFIED) VALUES (UUID_STRING(), :cot_id, :anchor_txid, :verified);
$$

