CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_NOTARY_REQUEST(bundle_id STRING, requester STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_REQUESTS (NOTARY_REQ_ID, BUNDLE_ID, REQUESTER, STATUS) VALUES (UUID_STRING(), :bundle_id, :requester, 'PENDING');
$$

