CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_RENDER_JOB(template_id STRING, merge_context VARIANT, next_run_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_QUEUE (RENDER_ID, TEMPLATE_ID, MERGE_CONTEXT, NEXT_RUN_AT) VALUES (UUID_STRING(), :template_id, :merge_context, :next_run_at);
$$

