CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTARY_LOG(notary_req_id STRING, event STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTARY_LOGS (LOG_ID, NOTARY_REQ_ID, EVENT, PAYLOAD) VALUES (UUID_STRING(), :notary_req_id, :event, :payload);
$$

