CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RENDER_LOG(render_id STRING, status STRING, output_location STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_LOGS (LOG_ID, RENDER_ID, STATUS, OUTPUT_LOCATION, DETAILS) VALUES (UUID_STRING(), :render_id, :status, :output_location, :details);
$$

