CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PDF_FILE(render_id STRING, file_url STRING, size_bytes NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PDF_STORAGE (PDF_ID, RENDER_ID, FILE_URL, SIZE_BYTES) VALUES (UUID_STRING(), :render_id, :file_url, :size_bytes);
$$

