CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_REDACTION_REQUEST(pdf_id STRING, fields VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_REQUESTS (REQ_ID, PDF_ID, FIELDS) VALUES (UUID_STRING(), :pdf_id, :fields);
$$

