CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_DOCUMENT_SEMANTICS(doc_id STRING, topics VARIANT, entities VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DOCUMENT_SEMANTICS t USING (SELECT :doc_id AS did, :topics AS tp, :entities AS ent) s ON t.DOC_ID = s.did WHEN MATCHED THEN UPDATE SET TOPICS = s.tp, ENTITIES = s.ent, GENERATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DOC_ID, TOPICS, ENTITIES) VALUES (s.did, s.tp, s.ent);
$$

