CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_CLAUSE_USAGE(clause_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.CLAUSE_USAGE_STATS t USING (SELECT :clause_id AS cid) s ON t.CLAUSE_ID = s.cid WHEN MATCHED THEN UPDATE SET USAGE_COUNT = COALESCE(USAGE_COUNT,0)+1, LAST_USED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CLAUSE_ID, USAGE_COUNT, LAST_USED_AT) VALUES (s.cid, 1, CURRENT_TIMESTAMP());
$$

