CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_RECOMMENDATION(template_id STRING, score FLOAT, reason VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_RECOMMENDATIONS (RECO_ID, TEMPLATE_ID, SCORE, REASON) VALUES (UUID_STRING(), :template_id, :score, :reason);
$$

