CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_TEMPLATE_LOCALIZATION(template_id STRING, lang STRING, content CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_LOCALIZATIONS t USING (SELECT :template_id AS tid, :lang AS lg, :content AS ct) s ON t.TEMPLATE_ID = s.tid AND t.LANG = s.lg WHEN MATCHED THEN UPDATE SET CONTENT = s.ct, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (LOC_ID, TEMPLATE_ID, LANG, CONTENT) VALUES (UUID_STRING(), s.tid, s.lg, s.ct);
$$

