CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COLLAB_SESSION(document_id STRING, host STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COLLAB_SESSIONS (SESSION_ID, DOCUMENT_ID, HOST, STATUS, STARTED_AT) VALUES (UUID_STRING(), :document_id, :host, 'ACTIVE', CURRENT_TIMESTAMP());
$$

