CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_TOKEN(subject_ref STRING, scope STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_TOKENS (TOKEN_ID, SUBJECT_REF, SCOPE, EXPIRES_AT) VALUES (UUID_STRING(), :subject_ref, :scope, :expires_at);
$$

