CREATE OR REPLACE PROCEDURE DOCGEN.ADD_COMMENT(thread_id STRING, author STRING, body STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMMENTS (COMMENT_ID, THREAD_ID, AUTHOR, BODY) VALUES (UUID_STRING(), :thread_id, :author, :body);
$$

