CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_OAUTH_CLIENT(client_id STRING, name STRING, redirect_uris ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_CLIENTS (CLIENT_ID, NAME, REDIRECT_URIS) VALUES (UUID_STRING(), :name, :redirect_uris);
$$

