CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REDACTION_REQUEST(bundle_id STRING, fields ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_REQUESTS (REQ_ID, BUNDLE_ID, FIELDS) VALUES (UUID_STRING(), :bundle_id, :fields);
$$

