CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OAUTH_AUTHORIZATION(client_id STRING, subject_ref STRING, scope STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_AUTHORIZATIONS (AUTH_ID, CLIENT_ID, SUBJECT_REF, SCOPE) VALUES (UUID_STRING(), :client_id, :subject_ref, :scope);
$$

