CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REDACTION_LOG(req_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_LOGS (LOG_ID, REQ_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :req_id, :status, :details);
$$

