CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_RISK_ENGINE_CONFIG(config_id STRING, name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RISK_ENGINE_CONFIG t USING (SELECT :config_id AS cid, :name AS nm, :rules AS r, :enabled AS en) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, ENABLED = s.en, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, NAME, RULES, ENABLED) VALUES (s.cid, s.nm, s.r, s.en);
$$

