CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RISK_SCORE(bundle_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_SCORES (SCORE_ID, BUNDLE_ID, SCORE) VALUES (UUID_STRING(), :bundle_id, :score);
$$

