CREATE OR REPLACE PROCEDURE DOCGEN.SEND_SLA_NOTIFICATION(sla_id STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_NOTIFICATIONS (NOTIF_ID, SLA_ID, MESSAGE) VALUES (UUID_STRING(), :sla_id, :message);
$$

