CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_API_KEY(owner STRING, key_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEYS (API_KEY_ID, OWNER, KEY_HASH) VALUES (UUID_STRING(), :owner, :key_hash);
$$

