CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CASE_TRANSITION(case_id STRING, from_status STRING, to_status STRING, by_user STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CASE_TRANSITIONS (TRANS_ID, CASE_ID, FROM_STATUS, TO_STATUS, BY_USER) VALUES (UUID_STRING(), :case_id, :from_status, :to_status, :by_user);
$$

