CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_KEY_AUDIT(api_key_id STRING, action STRING, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_KEY_AUDIT (AUDIT_ID, API_KEY_ID, ACTION, PERFORMED_BY) VALUES (UUID_STRING(), :api_key_id, :action, :performed_by);
$$

