CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RATE_LIMIT_PROFILE(profile_id STRING, name STRING, limits VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RATE_LIMIT_PROFILES t USING (SELECT :profile_id AS pid, :name AS nm, :limits AS lim, :enabled AS en) s ON t.PROFILE_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, LIMITS = s.lim, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (PROFILE_ID, NAME, LIMITS, ENABLED) VALUES (s.pid, s.nm, s.lim, s.en);
$$

