CREATE OR REPLACE PROCEDURE DOCGEN.INC_RATE_LIMIT_COUNTER(profile_id STRING, key_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RATE_LIMIT_COUNTERS t USING (SELECT :profile_id AS pid, :key_ref AS kr) s ON t.PROFILE_ID = s.pid AND t.KEY_REF = s.kr WHEN MATCHED THEN UPDATE SET COUNT = COALESCE(COUNT,0)+1 WHEN NOT MATCHED THEN INSERT (COUNTER_ID, PROFILE_ID, KEY_REF, COUNT, WINDOW_START) VALUES (UUID_STRING(), s.pid, s.kr, 1, CURRENT_TIMESTAMP());
$$

