CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_USAGE_METRIC(api_key_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KEY_USAGE_METRICS t USING (SELECT :api_key_id AS ak) s ON t.API_KEY_ID = s.ak WHEN MATCHED THEN UPDATE SET USAGE_COUNT = COALESCE(USAGE_COUNT,0)+1 WHEN NOT MATCHED THEN INSERT (METRIC_ID, API_KEY_ID, USAGE_COUNT, WINDOW_START) VALUES (UUID_STRING(), s.ak, 1, CURRENT_TIMESTAMP());
$$

