CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ACTION(admin_user STRING, action STRING, target STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTIONS (ACTION_ID, ADMIN_USER, ACTION, TARGET) VALUES (UUID_STRING(), :admin_user, :action, :target);
$$

