CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_EXPORT(request_id STRING, target_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_EXPORTS (EXPORT_ID, REQUEST_ID, TARGET_LOCATION, STATUS) VALUES (UUID_STRING(), :request_id, :target_location, 'PENDING');
$$

