CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKUP_RUN(manifest_id STRING, status STRING, ended_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKUP_RUNS (RUN_ID, MANIFEST_ID, STATUS, ENDED_AT) VALUES (UUID_STRING(), :manifest_id, :status, :ended_at);
$$

