CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RESTORE_REQUEST(manifest_id STRING, requestor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RESTORE_REQUESTS (REQ_ID, MANIFEST_ID, REQUESTOR) VALUES (UUID_STRING(), :manifest_id, :requestor);
$$

