CREATE OR REPLACE PROCEDURE DOCGEN.RUN_ARCHIVE_RECONCILIATION(archive_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_RECONCILIATION (RECON_ID, ARCHIVE_ID, EXPECTED_COUNT, ACTUAL_COUNT, STATUS) VALUES (UUID_STRING(), :archive_id, 0, 0, 'PENDING');
$$

