CREATE OR REPLACE PROCEDURE DOCGEN.VALIDATE_CHAIN(cot_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHAIN_VALIDATIONS (VALID_ID, COT_ID, VALID) VALUES (UUID_STRING(), :cot_id, FALSE);
$$

