CREATE OR REPLACE PROCEDURE DOCGEN.STORE_CERTIFICATE(cert_pem CLOB, subject STRING, issued_at TIMESTAMP_LTZ, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERTIFICATE_STORE (CERT_ID, CERT_PEM, SUBJECT, ISSUED_AT, EXPIRES_AT, META) VALUES (UUID_STRING(), :cert_pem, :subject, :issued_at, :expires_at, :meta);
$$

