CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OCSP_STATUS(cert_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OCSP_STATUS (OCSP_ID, CERT_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :cert_id, :status, :details);
$$

