CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EVIDENCE_HASH(bundle_id STRING, hash_value STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_HASHES (HASH_ID, BUNDLE_ID, HASH_VALUE) VALUES (UUID_STRING(), :bundle_id, :hash_value);
$$

