CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ANCHORING_JOB(bundle_id STRING, target_chain STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHORING_JOBS (JOB_ID, BUNDLE_ID, TARGET_CHAIN) VALUES (UUID_STRING(), :bundle_id, :target_chain);
$$

