CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ANCHORING_HISTORY(job_id STRING, anchor_txid STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHORING_HISTORY (AH_ID, JOB_ID, ANCHOR_TXID, STATUS) VALUES (UUID_STRING(), :job_id, :anchor_txid, :status);
$$

