CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_BLOCKCHAIN_PEER(name STRING, rpc_endpoint STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_PEERS (PEER_ID, NAME, RPC_ENDPOINT, CONFIG) VALUES (UUID_STRING(), :name, :rpc_endpoint, :config);
$$

