CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHAIN_ANCHOR(cot_id STRING, peer_id STRING, txid STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHAIN_ANCHORS (ANCHOR_ID, COT_ID, PEER_ID, TXID, PUBLISHED_AT) VALUES (UUID_STRING(), :cot_id, :peer_id, :txid, CURRENT_TIMESTAMP());
$$

