CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_HSM_REQUEST(action STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HSM_REQUESTS (REQ_ID, ACTION, PAYLOAD) VALUES (UUID_STRING(), :action, :payload);
$$

