CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ROTATION(key_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_HISTORY (ROTATION_ID, KEY_REF, DETAILS) VALUES (UUID_STRING(), :key_ref, :details);
$$

