CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_KEY_METADATA(key_id STRING, key_type STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KEY_METADATA t USING (SELECT :key_id AS kid, :key_type AS kt, :meta AS m) s ON t.KEY_ID = s.kid WHEN MATCHED THEN UPDATE SET KEY_TYPE = s.kt, META = s.m WHEN NOT MATCHED THEN INSERT (KEY_ID, KEY_TYPE, META) VALUES (s.kid, s.kt, s.m);
$$

