CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_EVENT_HANDLER(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVENT_HANDLERS (HANDLER_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

