CREATE OR REPLACE PROCEDURE DOCGEN.MOVE_EVENT_TO_DLQ(event_id STRING, error_msg STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVENT_DLQ (DLQ_ID, EVENT_ID, ERROR_MSG) VALUES (UUID_STRING(), :event_id, :error_msg);
UPDATE DOCGEN.SIGNATURE_EVENT_QUEUE SET STATUS='DLQ' WHERE EVENT_ID = :event_id;
$$

