CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_CALLBACK_ENDPOINT(name STRING, url STRING, auth VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_ENDPOINTS (ENDPOINT_ID, NAME, URL, AUTH) VALUES (UUID_STRING(), :name, :url, :auth);
$$

