CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CALLBACK_LOG(endpoint_id STRING, request VARIANT, response VARIANT, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_LOGS (LOG_ID, ENDPOINT_ID, REQUEST, RESPONSE, STATUS) VALUES (UUID_STRING(), :endpoint_id, :request, :response, :status);
$$

