CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_WEBHOOK(source STRING, secret_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_REGISTRATIONS (WH_ID, SOURCE, SECRET_HASH) VALUES (UUID_STRING(), :source, :secret_hash);
$$

