CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_WEBHOOK_INBOUND(source STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_INBOUND (INBOUND_ID, SOURCE, PAYLOAD) VALUES (UUID_STRING(), :source, :payload);
$$

