CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_VERIFICATION_WORKER(bundle_id STRING, next_run_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERIFICATION_QUEUE (QUEUE_ID, BUNDLE_ID, NEXT_RUN_AT) VALUES (UUID_STRING(), :bundle_id, :next_run_at);
$$

