CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_TEMPLATE(subject_ref STRING, template VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES (TEMPLATE_ID, SUBJECT_REF, TEMPLATE) VALUES (UUID_STRING(), :subject_ref, :template);
$$

