CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH(subject_ref STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCHES (MATCH_ID, SUBJECT_REF, SCORE) VALUES (UUID_STRING(), :subject_ref, :score);
$$

