CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_FRAUD_RULE(rule_id STRING, name STRING, expressions VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.FRAUD_RULES t USING (SELECT :rule_id AS rid, :name AS nm, :expressions AS expr, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, EXPRESSIONS = s.expr, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, EXPRESSIONS, ENABLED) VALUES (s.rid, s.nm, s.expr, s.en);
$$

