CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FRAUD_HIT(rule_id STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_HITS (HIT_ID, RULE_ID, CONTEXT) VALUES (UUID_STRING(), :rule_id, :context);
$$

