CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SESSION_TOKEN(session_id STRING, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_TOKENS (TOKEN_ID, SESSION_ID, EXPIRES_AT, META) VALUES (UUID_STRING(), :session_id, :expires_at, :meta);
$$

