CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_SESSION_TOKEN(token_id STRING, revoked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_REVOCATIONS (REV_ID, TOKEN_ID, REVOKED_BY) VALUES (UUID_STRING(), :token_id, :revoked_by);
UPDATE DOCGEN.SESSION_TOKENS SET EXPIRES_AT = CURRENT_TIMESTAMP() WHERE TOKEN_ID = :token_id;
$$

