CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_ARCHIVE_FILE(archive_id STRING, file_ref STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_INDEX (INDEX_ID, ARCHIVE_ID, FILE_REF, CHECKSUM) VALUES (UUID_STRING(), :archive_id, :file_ref, :checksum);
$$

