CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ARCHIVE_CATALOG(archive_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_CATALOG (CATALOG_ID, ARCHIVE_ID, META) VALUES (UUID_STRING(), :archive_id, :meta);
$$

