CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_ACCESS_REVIEW(target_ref STRING, due_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEWS (REVIEW_ID, TARGET_REF, DUE_AT, STATUS) VALUES (UUID_STRING(), :target_ref, :due_at, 'SCHEDULED');
$$

