CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_POLICY_EXCEPTION(policy_id STRING, granted_to STRING, expires_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_EXCEPTIONS (EXC_ID, POLICY_ID, GRANTED_TO, EXPIRES_AT, REASON) VALUES (UUID_STRING(), :policy_id, :granted_to, :expires_at, :reason);
$$

