CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_EXCEPTION_LOG(exc_id STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_EXCEPTION_LOGS (LOG_ID, EXC_ID, ACTION) VALUES (UUID_STRING(), :exc_id, :action);
$$

