CREATE OR REPLACE PROCEDURE DOCGEN.SUBSCRIBE_ADMIN_NOTIFICATIONS(admin_user STRING, notif_levels ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_SUBSCRIPTIONS (SUB_ID, ADMIN_USER, NOTIF_LEVELS) VALUES (UUID_STRING(), :admin_user, :notif_levels);
$$

