CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_ACTION(operator STRING, action STRING, target STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ACTIONS (ACTION_ID, OPERATOR, ACTION, TARGET) VALUES (UUID_STRING(), :operator, :action, :target);
$$

