CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_MEASUREMENT(sla_id STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_MEASUREMENTS (MEAS_ID, SLA_ID, METRIC) VALUES (UUID_STRING(), :sla_id, :metric);
$$

