CREATE OR REPLACE PROCEDURE DOCGEN.SEND_INCIDENT_NOTIFICATION(incident_id STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_NOTIFICATIONS (NOTIF_ID, INCIDENT_ID, MESSAGE) VALUES (UUID_STRING(), :incident_id, :message);
$$

