CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MAINTENANCE_LOG(window_id STRING, event STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_LOGS (LOG_ID, WINDOW_ID, EVENT) VALUES (UUID_STRING(), :window_id, :event);
$$

