CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKFILL_RUN(req_id STRING, status STRING, ended_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKFILL_RUNS (RUN_ID, REQ_ID, STATUS, ENDED_AT) VALUES (UUID_STRING(), :req_id, :status, :ended_at);
$$

