CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_TENANT_MAPPING(mapping_id STRING, tenant_id STRING, external_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TENANT_MAPPINGS t USING (SELECT :mapping_id AS mid, :tenant_id AS tid, :external_id AS eid) s ON t.MAPPING_ID = s.mid WHEN MATCHED THEN UPDATE SET TENANT_ID = s.tid, EXTERNAL_ID = s.eid WHEN NOT MATCHED THEN INSERT (MAPPING_ID, TENANT_ID, EXTERNAL_ID) VALUES (s.mid, s.tid, s.eid);
$$

