CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POLICY_AUDIT(paudit_id STRING, policy_id STRING, changed_by STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_AUDIT (PAUDIT_ID, POLICY_ID, CHANGED_BY, CHANGES) VALUES (:paudit_id, :policy_id, :changed_by, :changes);
$$

