CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_EVIDENCE_ARCHIVAL_POLICY(policy_id STRING, name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EVIDENCE_ARCHIVAL_POLICIES t USING (SELECT :policy_id AS pid, :name AS nm, :rules AS r, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RULES, ENABLED) VALUES (s.pid, s.nm, s.r, s.en);
$$

