CREATE OR REPLACE PROCEDURE DOCGEN.BIND_ARCHIVAL_POLICY(policy_id STRING, target_table STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVAL_POLICY_BINDINGS (BINDING_ID, POLICY_ID, TARGET_TABLE) VALUES (UUID_STRING(), :policy_id, :target_table);
$$

