CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXPORT_AUDIT(export_id STRING, requestor STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_AUDIT (AUDIT_ID, EXPORT_ID, REQUESTOR, DETAILS) VALUES (UUID_STRING(), :export_id, :requestor, :details);
$$

