CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_COMPLIANCE_ISSUE(check_id STRING, target_ref STRING, issue_details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_ISSUES (ISSUE_ID, CHECK_ID, TARGET_REF, ISSUE_DETAILS) VALUES (UUID_STRING(), :check_id, :target_ref, :issue_details);
$$

