CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LEGAL_HOLD_LOG(hold_id STRING, event STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_LOGS (LOG_ID, HOLD_ID, EVENT, DETAILS) VALUES (UUID_STRING(), :hold_id, :event, :details);
$$

