CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RETENTION_RUN(policy_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_RUNS (RUN_ID, POLICY_ID, STARTED_AT, STATUS) VALUES (UUID_STRING(), :policy_id, CURRENT_TIMESTAMP(), 'RUNNING');
$$

