CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETENTION_ACTION(run_id STRING, target_ref STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_ACTIONS (ACTION_ID, RUN_ID, TARGET_REF, ACTION, ACTIONED_AT) VALUES (UUID_STRING(), :run_id, :target_ref, :action, CURRENT_TIMESTAMP());
$$

