CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EPHEMERAL_KEY(subject_ref STRING, key_blob STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EPHEMERAL_KEYS (KEY_ID, SUBJECT_REF, KEY_BLOB, EXPIRES_AT) VALUES (UUID_STRING(), :subject_ref, :key_blob, :expires_at);
$$

