CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ONE_TIME_LINK(target_ref STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ONE_TIME_LINKS (LINK_ID, TARGET_REF, TOKEN_HASH, EXPIRES_AT) VALUES (UUID_STRING(), :target_ref, :token_hash, :expires_at);
$$

