CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ONE_TIME_LINK_USE(link_id STRING, used_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ONE_TIME_LINK_USES (USE_ID, LINK_ID, USED_BY) VALUES (UUID_STRING(), :link_id, :used_by);
$$

