CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEVICE_RISK_SCORE(finger_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_RISK_SCORES (SCORE_ID, FINGER_ID, SCORE) VALUES (UUID_STRING(), :finger_id, :score);
$$

