CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEOIP_LOOKUP(ip_addr STRING, geo VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEOIP_LOOKUPS (LOOKUP_ID, IP_ADDR, GEO) VALUES (UUID_STRING(), :ip_addr, :geo);
$$

