CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_HISTORY(session_id STRING, event STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_HISTORY (HISTORY_ID, SESSION_ID, EVENT, PAYLOAD) VALUES (UUID_STRING(), :session_id, :event, :payload);
$$

