CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THIRD_PARTY_INTEGRATION(name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_INTEGRATIONS (INTEGRATION_ID, NAME, CONFIG) VALUES (UUID_STRING(), :name, :config);
$$

