CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INTEGRATION_HEALTH(integration_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INTEGRATION_HEALTH (HEALTH_ID, INTEGRATION_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :integration_id, :status, :details);
$$

