CREATE OR REPLACE PROCEDURE DOCGEN.SET_PROVIDER_FALLBACK(primary_provider STRING, fallback_providers ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_FALLBACKS (FALLBACK_ID, PRIMARY_PROVIDER, FALLBACK_PROVIDERS) VALUES (UUID_STRING(), :primary_provider, :fallback_providers);
$$

