CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_METRIC(provider STRING, latency_ms FLOAT, err_rate FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_METRICS (METRIC_ID, PROVIDER, LATENCY_MS, ERR_RATE) VALUES (UUID_STRING(), :provider, :latency_ms, :err_rate);
$$

