CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_ROUTING(route_id STRING, tenant_id STRING, route_rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_ROUTING t USING (SELECT :route_id AS rid, :tenant_id AS tid, :route_rules AS rr) s ON t.ROUTE_ID = s.rid WHEN MATCHED THEN UPDATE SET TENANT_ID = s.tid, ROUTE_RULES = s.rr, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (ROUTE_ID, TENANT_ID, ROUTE_RULES) VALUES (s.rid, s.tid, s.rr);
$$

