CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ROUTING_AUDIT(route_id STRING, changed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROUTING_AUDIT (AUDIT_ID, ROUTE_ID, CHANGED_BY, DETAILS) VALUES (UUID_STRING(), :route_id, :changed_by, :details);
$$

