CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEST_HARNESS_JOB(name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEST_HARNESS_JOBS (JOB_ID, NAME, PAYLOAD) VALUES (UUID_STRING(), :name, :payload);
$$

