CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SMOKE_TEST(name STRING, script CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMOKE_TESTS (TEST_ID, NAME, SCRIPT) VALUES (UUID_STRING(), :name, :script);
$$

