CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POSTMORTEM(incident_id STRING, analysis VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_POSTMORTEMS (PM_ID, INCIDENT_ID, ANALYSIS) VALUES (UUID_STRING(), :incident_id, :analysis);
$$

