CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SERVICE_HEALTH(service_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_HEALTH (HEALTH_ID, SERVICE_ID, STATUS, DETAILS) VALUES (UUID_STRING(), :service_id, :status, :details);
$$

