CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEPLOYMENT(component STRING, version STRING, deployed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEPLOYMENT_RECORDS (DEPLOY_ID, COMPONENT, VERSION, DEPLOYED_BY) VALUES (UUID_STRING(), :component, :version, :deployed_by);
$$

