CREATE OR REPLACE PROCEDURE DOCGEN.ADD_RELEASE_NOTE(version STRING, notes CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RELEASE_NOTES (NOTE_ID, VERSION, NOTES) VALUES (UUID_STRING(), :version, :notes);
$$

