CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ACCOUNT_ADMIN(account_id STRING, user_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_ADMINS (ADMIN_ID, ACCOUNT_ID, USER_REF) VALUES (UUID_STRING(), :account_id, :user_ref);
$$

