CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_ROLE(name STRING, permissions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ROLES (ROLE_ID, NAME, PERMISSIONS) VALUES (UUID_STRING(), :name, :permissions);
$$

