CREATE OR REPLACE PROCEDURE DOCGEN.BIND_ROLE(role_id STRING, user_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROLE_BINDINGS (BIND_ID, ROLE_ID, USER_REF) VALUES (UUID_STRING(), :role_id, :user_ref);
$$

