CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESCALATION_LOG(policy_id STRING, incident_id STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_LOGS (LOG_ID, POLICY_ID, INCIDENT_ID, ACTION) VALUES (UUID_STRING(), :policy_id, :incident_id, :action);
$$

