CREATE OR REPLACE PROCEDURE DOCGEN.INGEST_TELEMETRY_EVENT(source STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TELEMETRY_EVENTS (EVENT_ID, SOURCE, METRIC) VALUES (UUID_STRING(), :source, :metric);
$$

