CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLO_BREACH(slo_id STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLO_BREACHES (BREACH_ID, SLO_ID, METRIC) VALUES (UUID_STRING(), :slo_id, :metric);
$$

