CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TRIGGERED_ALERT(rule_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TRIGGERED_ALERTS (ALERT_ID, RULE_ID, PAYLOAD) VALUES (UUID_STRING(), :rule_id, :payload);
$$

