CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_RETENTION_OVERRIDE(target_ref STRING, retention_days INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_RETENTION_OVERRIDES (OVERRIDE_ID, TARGET_REF, RETENTION_DAYS) VALUES (UUID_STRING(), :target_ref, :retention_days);
$$

