CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_REVIEW_TASK(target_ref STRING, assigned_to STRING, due_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_REVIEW_TASKS (TASK_ID, TARGET_REF, ASSIGNED_TO, STATUS, DUE_AT) VALUES (UUID_STRING(), :target_ref, :assigned_to, 'OPEN', :due_at);
$$

