CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_REVIEW_LOG(task_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_REVIEW_LOGS (LOG_ID, TASK_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :task_id, :action, :details);
$$

