CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_OPERATOR_CHECKLIST(checklist_id STRING, name STRING, items VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OPERATOR_CHECKLISTS t USING (SELECT :checklist_id AS cid, :name AS nm, :items AS it) s ON t.CHECKLIST_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, ITEMS = s.it, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CHECKLIST_ID, NAME, ITEMS) VALUES (s.cid, s.nm, s.it);
$$

