CREATE OR REPLACE PROCEDURE DOCGEN.BIND_POLICY_TEMPLATE(template_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_BINDINGS (BIND_ID, TEMPLATE_ID, TARGET_REF) VALUES (UUID_STRING(), :template_id, :target_ref);
$$

