CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REQUEST(target_ref STRING, requestor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REQUESTS (REQUEST_ID, TARGET_REF, REQUESTOR) VALUES (UUID_STRING(), :target_ref, :requestor);
$$

