CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_ACCESS(request_id STRING, granted_to STRING, granted_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_GRANTS (GRANT_ID, REQUEST_ID, GRANTED_TO, GRANTED_BY) VALUES (UUID_STRING(), :request_id, :granted_to, :granted_by);
$$

