CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DPR(subject_ref STRING, request_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_PRIVACY_REQUESTS (DPR_ID, SUBJECT_REF, REQUEST_TYPE) VALUES (UUID_STRING(), :subject_ref, :request_type);
$$

