CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DPR_ACTION(dpr_id STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DPR_ACTIONS (ACTION_ID, DPR_ID, ACTION, DETAILS) VALUES (UUID_STRING(), :dpr_id, :action, :details);
$$

