CREATE OR REPLACE PROCEDURE DOCGEN.SET_USER_PREFERENCES(user_ref STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_PREFERENCES (PREF_ID, USER_REF, PREFS) VALUES (UUID_STRING(), :user_ref, :prefs) ON DUPLICATE KEY UPDATE PREFS = :prefs, UPDATED_AT = CURRENT_TIMESTAMP();
$$

