CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_NOTIFICATION_TEMPLATE(template_id STRING, name STRING, channel STRING, template_body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_TEMPLATES (TEMPLATE_ID, NAME, CHANNEL, TEMPLATE_BODY) VALUES (:template_id, :name, :channel, :template_body);
$$

