CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_ACCESS(document_id STRING, user_ref STRING, action STRING, ip_addr STRING, user_agent STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_ACCESS_LOGS (LOG_ID, DOCUMENT_ID, USER_REF, ACTION, IP_ADDR, USER_AGENT) VALUES (UUID_STRING(), :document_id, :user_ref, :action, :ip_addr, :user_agent);
$$

