CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DOCUMENT_SHARE(document_id STRING, shared_with STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_SHARES (SHARE_ID, DOCUMENT_ID, SHARED_WITH, PERMISSIONS) VALUES (UUID_STRING(), :document_id, :shared_with, :permissions);
$$

