CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_VERSION_DIFF(version_id STRING, diff VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERSION_DIFFS (DIFF_ID, VERSION_ID, DIFF) VALUES (UUID_STRING(), :version_id, :diff);
$$

