CREATE OR REPLACE PROCEDURE DOCGEN.SET_DOCUMENT_RETENTION(document_id STRING, retention_until TIMESTAMP_LTZ, policy_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_RETENTION (RETENTION_ID, DOCUMENT_ID, RETENTION_UNTIL, POLICY_ID) VALUES (UUID_STRING(), :document_id, :retention_until, :policy_id);
$$

