CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_PURGE(document_id STRING, by_whom STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_PURGES (PURGE_ID, DOCUMENT_ID, BY) VALUES (UUID_STRING(), :document_id, :by_whom);
$$

