CREATE OR REPLACE PROCEDURE DOCGEN.SET_VERSION_RETENTION_OVERRIDE(version_id STRING, retention_until TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERSION_RETENTION_OVERRIDES (OVERRIDE_ID, VERSION_ID, RETENTION_UNTIL) VALUES (UUID_STRING(), :version_id, :retention_until);
$$

