CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKUP_RUN_DETAIL(run_id STRING, file_ref STRING, status STRING, detail VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKUP_RUN_DETAILS (DETAIL_ID, RUN_ID, FILE_REF, STATUS, DETAIL) VALUES (UUID_STRING(), :run_id, :file_ref, :status, :detail);
$$

