CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RESTORE_POLICY(policy_id STRING, name STRING, allowed_sources ARRAY, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RESTORE_POLICIES t USING (SELECT :policy_id AS pid, :name AS nm, :allowed_sources AS asrc, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, ALLOWED_SOURCES = s.asrc, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, ALLOWED_SOURCES, ENABLED) VALUES (s.pid, s.nm, s.asrc, s.en);
$$

