CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RESTORE_RUN_DETAIL(req_id STRING, file_ref STRING, status STRING, detail VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RESTORE_RUN_DETAILS (DETAIL_ID, REQ_ID, FILE_REF, STATUS, DETAIL) VALUES (UUID_STRING(), :req_id, :file_ref, :status, :detail);
$$

