CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_METRICS_CONFIG(config_id STRING, name STRING, agg_rules VARIANT, schedule STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.METRICS_CONFIG t USING (SELECT :config_id AS cid, :name AS nm, :agg_rules AS ar, :schedule AS sch, :enabled AS en) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, AGG_RULES = s.ar, SCHEDULE = s.sch, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (CONFIG_ID, NAME, AGG_RULES, SCHEDULE, ENABLED) VALUES (s.cid, s.nm, s.ar, s.sch, s.en);
$$

