CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_METRIC_RUN(config_id STRING, status STRING, ended_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.METRIC_RUNS (RUN_ID, CONFIG_ID, STATUS, ENDED_AT) VALUES (UUID_STRING(), :config_id, :status, :ended_at);
$$

