CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_METRIC_VALUE(run_id STRING, metric_key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.METRIC_VALUES (VALUE_ID, RUN_ID, METRIC_KEY, VALUE) VALUES (UUID_STRING(), :run_id, :metric_key, :value);
$$

