CREATE OR REPLACE PROCEDURE DOCGEN.SUBSCRIBE_ALERT_RULE(rule_id STRING, channel STRING, destination STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_SUBSCRIBERS (SUB_ID, RULE_ID, CHANNEL, DESTINATION) VALUES (UUID_STRING(), :rule_id, :channel, :destination);
$$

