CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ALERT_DISPATCH(alert_id STRING, sub_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_DISPATCH_LOGS (DISPATCH_ID, ALERT_ID, SUB_ID, STATUS, RESPONSE) VALUES (UUID_STRING(), :alert_id, :sub_id, :status, :response);
$$

