CREATE OR REPLACE PROCEDURE DOCGEN.SET_ALERT_RATE_LIMIT(sub_id STRING, max_per_hour INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_RATE_LIMITS (LIMIT_ID, SUB_ID, MAX_PER_HOUR) VALUES (UUID_STRING(), :sub_id, :max_per_hour);
$$

