CREATE OR REPLACE PROCEDURE DOCGEN.INC_ALERT_RATE_USAGE(sub_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ALERT_RATE_USAGE t USING (SELECT :sub_id AS sid) s ON t.SUB_ID = s.sid AND t.WINDOW_START = DATE_TRUNC('hour', CURRENT_TIMESTAMP()) WHEN MATCHED THEN UPDATE SET COUNT = COALESCE(COUNT,0)+1 WHEN NOT MATCHED THEN INSERT (USAGE_ID, SUB_ID, COUNT, WINDOW_START) VALUES (UUID_STRING(), s.sid, 1, DATE_TRUNC('hour', CURRENT_TIMESTAMP()));
$$

