CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TRANSCRIPT_ENTRY(bundle_id STRING, actor STRING, text CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TRANSCRIPTS (TRANSCRIPT_ID, BUNDLE_ID, ACTOR, TEXT) VALUES (UUID_STRING(), :bundle_id, :actor, :text);
$$

