CREATE OR REPLACE PROCEDURE DOCGEN.ADD_CONVERSATION_MESSAGE(session_id STRING, sender STRING, content CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONVERSATION_MESSAGES (MESSAGE_ID, SESSION_ID, SENDER, CONTENT) VALUES (UUID_STRING(), :session_id, :sender, :content);
$$

