CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_APPROVAL_PIPELINE(pipe_id STRING, name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_PIPELINES (PIPE_ID, NAME, STEPS) VALUES (UUID_STRING(), :pipe_id, :name, :steps);
$$

