CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_APPROVAL_INSTANCE(pipe_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_INSTANCES (INSTANCE_ID, PIPE_ID, TARGET_REF, STATUS) VALUES (UUID_STRING(), :pipe_id, :target_ref, 'PENDING');
$$

