CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_APPROVAL_ACTION(instance_id STRING, actor STRING, action STRING, comment STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_ACTIONS (ACTION_ID, INSTANCE_ID, ACTOR, ACTION, COMMENT) VALUES (UUID_STRING(), :instance_id, :actor, :action, :comment);
$$

