CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_APPROVAL_AUDIT(instance_id STRING, summary VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_AUDIT (AUDIT_ID, INSTANCE_ID, SUMMARY) VALUES (UUID_STRING(), :instance_id, :summary);
$$

