CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CASE(title STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CASES (CASE_ID, TITLE, STATUS, OWNER) VALUES (UUID_STRING(), :title, 'OPEN', :owner);
$$

