CREATE OR REPLACE PROCEDURE DOCGEN.ADD_CASE_COMMENT(case_id STRING, author STRING, body STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CASE_COMMENTS (COMMENT_ID, CASE_ID, AUTHOR, BODY) VALUES (UUID_STRING(), :case_id, :author, :body);
$$

