CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_INCIDENT_SEVERITY(sev_id STRING, name STRING, priority INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.INCIDENT_SEVERITY_LEVELS t USING (SELECT :sev_id AS sid, :name AS nm, :priority AS pr) s ON t.SEV_ID = s.sid WHEN MATCHED THEN UPDATE SET NAME = s.nm, PRIORITY = s.pr WHEN NOT MATCHED THEN INSERT (SEV_ID, NAME, PRIORITY) VALUES (s.sid, s.nm, s.pr);
$$

