CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_INCIDENT_NOTIFICATION(incident_id STRING, message STRING, destination VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_NOTIFICATION_QUEUE (QUEUE_ID, INCIDENT_ID, MESSAGE, DESTINATION) VALUES (UUID_STRING(), :incident_id, :message, :destination);
$$

