CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RESOLUTION_TEMPLATE(template_id STRING, name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RESOLUTION_TEMPLATES t USING (SELECT :template_id AS tid, :name AS nm, :steps AS st) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET NAME = s.nm, STEPS = s.st, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, STEPS) VALUES (s.tid, s.nm, s.st);
$$

