CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_KPI_DEFINITION(kpi_id STRING, name STRING, definition VARIANT, agg_interval STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KPI_DEFINITIONS t USING (SELECT :kpi_id AS kid, :name AS nm, :definition AS def, :agg_interval AS ai) s ON t.KPI_ID = s.kid WHEN MATCHED THEN UPDATE SET NAME = s.nm, DEFINITION = s.def, AGG_INTERVAL = s.ai WHEN NOT MATCHED THEN INSERT (KPI_ID, NAME, DEFINITION, AGG_INTERVAL) VALUES (s.kid, s.nm, s.def, s.ai);
$$

