CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RUNBOOK_ENTRY(entry_id STRING, title STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RUNBOOK_ENTRIES t USING (SELECT :entry_id AS eid, :title AS ttl, :steps AS st) s ON t.ENTRY_ID = s.eid WHEN MATCHED THEN UPDATE SET TITLE = s.ttl, STEPS = s.st, LAST_UPDATED = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (ENTRY_ID, TITLE, STEPS) VALUES (s.eid, s.ttl, s.st);
$$

