CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RUNBOOK_RUN(entry_id STRING, status STRING, completed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RUNBOOK_RUNS (RUN_ID, ENTRY_ID, STATUS, COMPLETED_AT) VALUES (UUID_STRING(), :entry_id, :status, :completed_at);
$$

