CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_DATA_CLASSIFICATION(class_id STRING, name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DATA_CLASSIFICATIONS t USING (SELECT :class_id AS cid, :name AS nm, :rules AS r) s ON t.CLASS_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CLASS_ID, NAME, RULES) VALUES (s.cid, s.nm, s.r);
$$

