CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PII_SCAN_JOB(target_table STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PII_SCAN_JOBS (JOB_ID, TARGET_TABLE, STATUS, STARTED_AT) VALUES (UUID_STRING(), :target_table, 'RUNNING', CURRENT_TIMESTAMP());
$$

