CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MASKING_AUDIT(rule_id STRING, target_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MASKING_AUDIT (AUDIT_ID, RULE_ID, TARGET_REF, DETAILS) VALUES (UUID_STRING(), :rule_id, :target_ref, :details);
$$

