CREATE OR REPLACE PROCEDURE DOCGEN.ATTACH_POLICY_TO_TABLE(policy_id STRING, target_table STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_ATTACHMENTS (ATTACH_ID, POLICY_ID, TARGET_TABLE) VALUES (UUID_STRING(), :policy_id, :target_table);
$$

