CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PIA_RECORD(pia_id STRING, title STRING, summary VARIANT, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PIA_RECORDS (PIA_ID, TITLE, SUMMARY, STATUS) VALUES (:pia_id, :title, :summary, :status);
$$

