CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PIA_REVIEW(pia_id STRING, reviewer STRING, result STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PIA_REVIEWS (REVIEW_ID, PIA_ID, REVIEWER, RESULT) VALUES (UUID_STRING(), :pia_id, :reviewer, :result);
$$

