CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_METADATA(target_ref STRING, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.METADATA_INDEX (IDX_ID, TARGET_REF, METADATA) VALUES (UUID_STRING(), :target_ref, :metadata);
$$

