CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_SIGNATORY_KEY_01(signatory_ref STRING, key_type STRING, key_pem CLOB, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATORY_KEYS_01 (KEY_ID, SIGNATORY_REF, KEY_TYPE, KEY_PEM, EXPIRES_AT, META)
VALUES (UUID_STRING(), :signatory_ref, :key_type, :key_pem, :expires_at, :meta);
$$

