CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_ADMIN_ACTIVITY(action_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTIVITY_INDEX (INDEX_ID, ACTION_ID, ADMIN_USER, TARGET_REF) SELECT UUID_STRING(), ACTION_ID, ADMIN_USER, TARGET FROM DOCGEN.ADMIN_ACTIONS WHERE ACTION_ID = :action_id;
$$
-- @1

