CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNATURE_POLICY_01(policy_id STRING, name STRING, rules VARIANT, scope VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_POLICIES_01 t
USING (SELECT :policy_id AS pid, :name AS nm, :rules AS r, :scope AS s, :enabled AS e) s
ON t.POLICY_ID = s.pid
WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, SCOPE = s.s, ENABLED = s.e
WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RULES, SCOPE, ENABLED) VALUES (s.pid, s.nm, s.r, s.s, s.e);
$$

