CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SEARCH_METRIC(query STRING, result_count INT, latency_ms FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_METRICS (METRIC_ID, QUERY, RESULT_COUNT, LATENCY_MS) VALUES (UUID_STRING(), :query, :result_count, :latency_ms);
$$
-- @1

