CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SIGNING_SESSION_01(bundle_id STRING, signatory_ref STRING, expires_at TIMESTAMP_LTZ, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_SESSIONS_01 (SESSION_ID, BUNDLE_ID, SIGNATORY_REF, STATUS, EXPIRES_AT, META)
VALUES (UUID_STRING(), :bundle_id, :signatory_ref, 'CREATED', :expires_at, :meta);
$$

