CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_USER_CONSENT(user_ref STRING, scope VARIANT, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_CONSENT_RECORDS (CONSENT_ID, USER_REF, SCOPE, META) VALUES (UUID_STRING(), :user_ref, :scope, :meta);
$$
-- @1

