CREATE OR REPLACE PROCEDURE DOCGEN.ISSUE_CHALLENGE_01(session_id STRING, challenge TEXT, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_CHALLENGES_01 (CHALLENGE_ID, SESSION_ID, CHALLENGE, EXPIRES_AT)
VALUES (UUID_STRING(), :session_id, :challenge, :expires_at);
$$

