CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_LOCALIZATION_STRING(key_id STRING, locale STRING, key_name STRING, value STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.LOCALIZATION_STRINGS t USING (SELECT :key_id AS kid, :locale AS loc, :key_name AS kn, :value AS val) s ON t.KEY_ID = s.kid WHEN MATCHED THEN UPDATE SET LOCALE = s.loc, KEY_NAME = s.kn, VALUE = s.val WHEN NOT MATCHED THEN INSERT (KEY_ID, LOCALE, KEY_NAME, VALUE) VALUES (s.kid, s.loc, s.kn, s.val);
$$
-- @1

