CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHALLENGE_RESPONSE_01(challenge_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHALLENGE_RESPONSES_01 (RESPONSE_ID, CHALLENGE_ID, RESPONSE)
VALUES (UUID_STRING(), :challenge_id, :response);
$$

