CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_TEMPLATE_PERMISSION(template_id STRING, subject_ref STRING, permissions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PERMISSIONS (PERM_ID, TEMPLATE_ID, SUBJECT_REF, PERMISSIONS) VALUES (UUID_STRING(), :template_id, :subject_ref, :permissions);
$$
-- @1

