CREATE OR REPLACE PROCEDURE DOCGEN.ADD_EVIDENCE_COMPONENT_01(bundle_id STRING, type STRING, ref STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_COMPONENTS_01 (COMPONENT_ID, BUNDLE_ID, TYPE, REF, HASH)
VALUES (UUID_STRING(), :bundle_id, :type, :ref, :hash);
$$

