CREATE OR REPLACE PROCEDURE DOCGEN.ADD_CLAUSE_DEPENDENCY(clause_id STRING, depends_on ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLAUSE_DEPENDENCIES (DEP_ID, CLAUSE_ID, DEPENDS_ON) VALUES (UUID_STRING(), :clause_id, :depends_on);
$$
-- @1

