CREATE OR REPLACE PROCEDURE DOCGEN.PERFORM_EVIDENCE_INTEGRITY_CHECK_01(bundle_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_INTEGRITY_CHECKS_01 (CHECK_ID, BUNDLE_ID, STATUS)
VALUES (UUID_STRING(), :bundle_id, 'PENDING');
$$

