CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_TEMPLATE_REVIEW(template_id STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_REVIEW_QUEUE (QUEUE_ID, TEMPLATE_ID, REQUESTED_BY) VALUES (UUID_STRING(), :template_id, :requested_by);
$$
-- @1

