CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OTP_01(session_id STRING, otp_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTPS_01 (OTP_ID, SESSION_ID, OTP_HASH, EXPIRES_AT)
VALUES (UUID_STRING(), :session_id, :otp_hash, :expires_at);
$$

