CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNER_PROFILE_01(signer_ref STRING, name STRING, email STRING, phone STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_PROFILES_01 t
USING (SELECT :signer_ref AS sr, :name AS nm, :email AS em, :phone AS ph, :meta AS m) s
ON t.SIGNER_REF = s.sr
WHEN MATCHED THEN UPDATE SET NAME = s.nm, EMAIL = s.em, PHONE = s.ph, META = s.m
WHEN NOT MATCHED THEN INSERT (SIGNER_REF, NAME, EMAIL, PHONE, META) VALUES (s.sr, s.nm, s.em, s.ph, s.m);
$$

