CREATE OR REPLACE PROCEDURE DOCGEN.APPROVE_TEMPLATE(template_id STRING, approved_by STRING, comment STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_APPROVALS (APPROVAL_ID, TEMPLATE_ID, APPROVED_BY, COMMENT) VALUES (UUID_STRING(), :template_id, :approved_by, :comment);
MERGE INTO DOCGEN.TEMPLATE_VERSIONS t USING (SELECT :template_id AS tid) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET IS_ACTIVE = FALSE WHERE t.TEMPLATE_ID = s.tid;
$$
-- @1

