CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_VERSION_NOTE(version_id STRING, note CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_VERSION_NOTES (NOTE_ID, TEMPLATE_VERSION_ID, NOTE) VALUES (UUID_STRING(), :version_id, :note);
$$
-- @1

