CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_SIGNATURE_REMINDER_01(bundle_id STRING, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_REMINDERS_01 (REMINDER_ID, BUNDLE_ID, SCHEDULED_AT)
VALUES (UUID_STRING(), :bundle_id, :scheduled_at);
$$

