CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_CHANGE_REQUEST(template_id STRING, requestor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CHANGE_REQUESTS (CR_ID, TEMPLATE_ID, REQUESTOR) VALUES (UUID_STRING(), :template_id, :requestor);
$$
-- @1

