CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REMINDER_LOG_01(reminder_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_REMINDER_LOGS_01 (LOG_ID, REMINDER_ID, RESPONSE) VALUES (UUID_STRING(), :reminder_id, :response);
UPDATE DOCGEN.SIGNATURE_REMINDERS_01 SET SENT = TRUE WHERE REMINDER_ID = :reminder_id;
$$

