CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CR_WORKFLOW_STEP(cr_id STRING, step INT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CR_WORKFLOWS (WF_ID, CR_ID, STEP, OWNER, STATUS) VALUES (UUID_STRING(), :cr_id, :step, :owner, 'PENDING');
$$
-- @1

