CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CR_AUDIT(cr_id STRING, action STRING, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_CR_AUDIT (AUDIT_ID, CR_ID, ACTION, PERFORMED_BY) VALUES (UUID_STRING(), :cr_id, :action, :performed_by);
$$
-- @1

