CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DEADLINE_TRIGGER_01(policy_id STRING, bundle_id STRING, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEADLINE_TRIGGERS_01 (TRIGGER_ID, POLICY_ID, BUNDLE_ID, ACTION) VALUES (UUID_STRING(), :policy_id, :bundle_id, :action);
$$

