CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ESIGN_PROVIDER_01(name STRING, type STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESIGN_PROVIDER_CONFIGS_01 (CONFIG_ID, NAME, TYPE, CONFIG) VALUES (UUID_STRING(), :name, :type, :config);
$$

