CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_GLOBAL_SETTING(setting_key STRING, setting_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.GLOBAL_SETTINGS t USING (SELECT :setting_key AS sk, :setting_value AS sv) s ON t.SETTING_KEY = s.sk WHEN MATCHED THEN UPDATE SET SETTING_VALUE = s.sv, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE) VALUES (s.sk, s.sv);
$$
-- @1

