CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PROVIDER_REQUEST_01(provider_config_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_REQUESTS_01 (REQ_ID, PROVIDER_CONFIG_ID, PAYLOAD, STATUS) VALUES (UUID_STRING(), :provider_config_id, :payload, 'PENDING');
$$

