CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_RESPONSE_01(req_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_RESPONSES_01 (RESP_ID, REQ_ID, RESPONSE) VALUES (UUID_STRING(), :req_id, :response);
UPDATE DOCGEN.PROVIDER_REQUESTS_01 SET STATUS = 'COMPLETED' WHERE REQ_ID = :req_id;
$$

