CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INTERACTION_01(bundle_id STRING, actor STRING, action STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INTERACTION_HISTORIES_01 (INTERACT_ID, BUNDLE_ID, ACTOR, ACTION, PAYLOAD) VALUES (UUID_STRING(), :bundle_id, :actor, :action, :payload);
$$

