CREATE OR REPLACE PROCEDURE DOCGEN.ADD_KB_LINK_01(topic STRING, url STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KNOWLEDGE_BASE_LINKS_01 (LINK_ID, TOPIC, URL, META) VALUES (UUID_STRING(), :topic, :url, :meta);
$$

