CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_TELEMETRY(model_id STRING, metric_key STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_TELEMETRY (TELE_ID, MODEL_ID, METRIC_KEY, METRIC_VALUE)
VALUES (UUID_STRING(), :model_id, :metric_key, :metric_value);
$$

