CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EMBEDDING_JOB(job_id STRING, source_ref STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMBEDDING_JOBS (JOB_ID, SOURCE_REF, STATUS, STARTED_AT, META)
VALUES (:job_id, :source_ref, 'PENDING', CURRENT_TIMESTAMP(), :meta);
$$

