CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_EMBEDDING_VECTOR(vector_id STRING, bundle_id STRING, vector VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EMBEDDING_VECTORS t USING (SELECT :vector_id AS vid, :bundle_id AS bid, :vector AS vec) s
ON t.VECTOR_ID = s.vid
WHEN MATCHED THEN UPDATE SET BUNDLE_ID = s.bid, VECTOR = s.vec
WHEN NOT MATCHED THEN INSERT (VECTOR_ID, BUNDLE_ID, VECTOR) VALUES (s.vid, s.bid, s.vec);
$$

