CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_AI_REQUEST(req_id STRING, type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AI_REQUESTS (REQ_ID, TYPE, PAYLOAD, STATUS) VALUES (:req_id, :type, :payload, 'QUEUED');
$$

