CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_ANALYTIC(template_id STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_ANALYTICS (ANALYTIC_ID, TEMPLATE_ID, METRIC) VALUES (UUID_STRING(), :template_id, :metric);
$$

