CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_SECRET_AUDIT(key_id STRING, action STRING, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_SECRETS_AUDIT (AUDIT_ID, KEY_ID, ACTION, PERFORMED_BY) VALUES (UUID_STRING(), :key_id, :action, :performed_by);
$$

