CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_USAGE(provider_name STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_USAGE (USAGE_ID, PROVIDER_NAME, METRIC) VALUES (UUID_STRING(), :provider_name, :metric);
$$

