CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ALERT_SUPPRESSION(rule_id STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_SUPPRESSIONS (SUPP_ID, RULE_ID, START_AT, END_AT, REASON) VALUES (UUID_STRING(), :rule_id, :start_at, :end_at, :reason);
$$

