CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BILLING_AUDIT(invoice_id STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_AUDIT (AUDIT_ID, INVOICE_ID, CHANGES) VALUES (UUID_STRING(), :invoice_id, :changes);
$$

