CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_QUOTA_ALERT(account_id STRING, threshold VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_ALERTS (ALERT_ID, ACCOUNT_ID, THRESHOLD) VALUES (UUID_STRING(), :account_id, :threshold);
$$

