CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SYNC_CHANGE(job_id STRING, change_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SYNC_CHANGE_LOGS (LOG_ID, JOB_ID, CHANGE_TYPE, DETAILS) VALUES (UUID_STRING(), :job_id, :change_type, :details);
$$

