CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_IDENTITY_PROVIDER(idp_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IDENTITY_PROVIDERS (IDP_ID, NAME, CONFIG) VALUES (:idp_id, :name, :config);
$$

