CREATE OR REPLACE PROCEDURE DOCGEN.STORE_OAUTH_TOKEN(token_id STRING, subject_ref STRING, provider STRING, token_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_TOKENS (TOKEN_ID, SUBJECT_REF, PROVIDER, TOKEN_META) VALUES (:token_id, :subject_ref, :provider, :token_meta);
$$

