CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEO_VIOLATION(rule_id STRING, bundle_id STRING, geo_info VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEO_VIOLATION_LOGS (LOG_ID, RULE_ID, BUNDLE_ID, GEO_INFO) VALUES (UUID_STRING(), :rule_id, :bundle_id, :geo_info);
$$

