CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ALERT_HISTORY_02(rule_id STRING, bundle_id STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_HISTORY_02 (HISTORY_ID, RULE_ID, BUNDLE_ID, CONTEXT) VALUES (UUID_STRING(), :rule_id, :bundle_id, :context);
$$

