CREATE OR REPLACE PROCEDURE DOCGEN.APPEND_AUDIT_STREAM_02(source STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_STREAM_02 (AUDIT_ID, SOURCE, EVENT_TYPE, PAYLOAD) VALUES (UUID_STRING(), :source, :event_type, :payload);
$$

