CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HEALTH_CHECK_02(check_id STRING, name STRING, last_ok TIMESTAMP_LTZ, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.HEALTH_CHECKS_02 t
USING (SELECT :check_id AS cid, :name AS nm, :last_ok AS lo, :status AS st, :details AS dt) s
ON t.CHECK_ID = s.cid
WHEN MATCHED THEN UPDATE SET NAME = s.nm, LAST_OK = s.lo, STATUS = s.st, DETAILS = s.dt
WHEN NOT MATCHED THEN INSERT (CHECK_ID, NAME, LAST_OK, STATUS, DETAILS) VALUES (s.cid, s.nm, s.lo, s.st, s.dt);
$$

