CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SCHEDULER_JOB_02(job_id STRING, name STRING, cron_expression STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SCHEDULER_JOBS_02 t
USING (SELECT :job_id AS jid, :name AS nm, :cron_expression AS ce, :enabled AS en) s
ON t.JOB_ID = s.jid
WHEN MATCHED THEN UPDATE SET NAME = s.nm, CRON_EXPRESSION = s.ce, ENABLED = s.en
WHEN NOT MATCHED THEN INSERT (JOB_ID, NAME, CRON_EXPRESSION, ENABLED) VALUES (s.jid, s.nm, s.ce, s.en);
$$

