CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_JOB_EXECUTION_02(job_id STRING, started_at TIMESTAMP_LTZ, ended_at TIMESTAMP_LTZ, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.JOB_EXECUTIONS_02 (EXEC_ID, JOB_ID, STARTED_AT, ENDED_AT, STATUS, DETAILS) VALUES (UUID_STRING(), :job_id, :started_at, :ended_at, :status, :details);
$$

