CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ERROR_CATALOG_02(error_code STRING, summary STRING, description STRING, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ERROR_CATALOG_02 t
USING (SELECT :error_code AS ec, :summary AS sm, :description AS ds, :severity AS sv) s
ON t.ERROR_CODE = s.ec
WHEN MATCHED THEN UPDATE SET SUMMARY = s.sm, DESCRIPTION = s.ds, SEVERITY = s.sv
WHEN NOT MATCHED THEN INSERT (ERROR_CODE, SUMMARY, DESCRIPTION, SEVERITY) VALUES (s.ec, s.sm, s.ds, s.sv);
$$

