CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ERROR_EVENT_02(error_code STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ERROR_EVENTS_02 (EVENT_ID, ERROR_CODE, CONTEXT) VALUES (UUID_STRING(), :error_code, :context);
$$

