CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD_02(target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLDS_02 (HOLD_ID, TARGET_REF) VALUES (UUID_STRING(), :target_ref);
$$

