CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_LEGAL_HOLD_ACTION_02(hold_id STRING, action STRING, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLD_ACTIONS_02 (ACTION_ID, HOLD_ID, ACTION, PERFORMED_BY) VALUES (UUID_STRING(), :hold_id, :action, :performed_by);
$$

