CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_EXPORT_REQUEST_02(scope VARIANT, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_EXPORTS_02 (EXPORT_ID, SCOPE, REQUESTED_BY, STATUS) VALUES (UUID_STRING(), :scope, :requested_by, 'QUEUED');
$$

