CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETENTION_EXECUTION_02(policy_id STRING, started_at TIMESTAMP_LTZ, completed_at TIMESTAMP_LTZ, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_POLICY_EXECUTIONS_02 (EXEC_ID, POLICY_ID, STARTED_AT, COMPLETED_AT, RESULT) VALUES (UUID_STRING(), :policy_id, :started_at, :completed_at, :result);
$$

