CREATE OR REPLACE PROCEDURE DOCGEN.CAPTURE_DATA_LINEAGE_02(target_ref STRING, source_refs ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_LINEAGE_02 (LINEAGE_ID, TARGET_REF, SOURCE_REFS) VALUES (UUID_STRING(), :target_ref, :source_refs);
$$

