CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_USER_SECURITY_EVENT_02(user_ref STRING, event_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_SECURITY_EVENTS_02 (EVENT_ID, USER_REF, EVENT_TYPE, DETAILS) VALUES (UUID_STRING(), :user_ref, :event_type, :details);
$$

