CREATE OR REPLACE PROCEDURE DOCGEN.FLAG_SUSPICIOUS_ACTIVITY_02(target_ref STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUSPICIOUS_ACTIVITY_FLAGS_02 (FLAG_ID, TARGET_REF, REASON) VALUES (UUID_STRING(), :target_ref, :reason);
$$

