CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RISK_PROFILE_02(profile_id STRING, name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_SCORING_PROFILES_02 (PROFILE_ID, NAME, RULES) VALUES (:profile_id, :name, :rules);
$$

