CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RISK_SCORE_02(target_ref STRING, profile_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_SCORES_02 (SCORE_ID, TARGET_REF, PROFILE_ID, SCORE) VALUES (UUID_STRING(), :target_ref, :profile_id, :score);
$$

