CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_POST_SIGN_HOOK_02(hook_id STRING, name STRING, hook_type STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POST_SIGN_HOOKS_02 (HOOK_ID, NAME, HOOK_TYPE, CONFIG, ENABLED) VALUES (:hook_id, :name, :hook_type, :config, :enabled);
$$

