CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EXPORT_JOB_03(job_type STRING, target_location STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_JOBS_03 (JOB_ID, JOB_TYPE, TARGET_LOCATION, META) VALUES (UUID_STRING(), :job_type, :target_location, :meta);
$$

