CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EXPORT_JOB_03(job_id STRING, next_run_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_QUEUE_03 (QUEUE_ID, JOB_ID, NEXT_RUN_AT) VALUES (UUID_STRING(), :job_id, :next_run_at);
$$

