CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXPORT_FAILURE_03(queue_id STRING, error_code STRING, error_detail CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_FAILURES_03 (FAILURE_ID, QUEUE_ID, ERROR_CODE, ERROR_DETAIL) VALUES (UUID_STRING(), :queue_id, :error_code, :error_detail);
UPDATE DOCGEN.EXPORT_QUEUE_03 SET ATTEMPTS = COALESCE(ATTEMPTS,0)+1 WHERE QUEUE_ID = :queue_id;
$$

