CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RETRIEVAL_AUDIT_03(query VARIANT, result_count INT, user_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETRIEVAL_AUDIT_03 (AUDIT_ID, QUERY, RESULT_COUNT, USER_REF) VALUES (UUID_STRING(), :query, :result_count, :user_ref);
$$

