CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_USER_SESSION_03(session_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.USER_SESSIONS_03 SET STATUS = :status, LAST_UPDATED_AT = CURRENT_TIMESTAMP() WHERE SESSION_ID = :session_id;
$$

