CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ASYNC_CALLBACK_03(source STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ASYNC_CALLBACKS_03 (CALLBACK_ID, SOURCE, PAYLOAD) VALUES (UUID_STRING(), :source, :payload);
$$

