CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CALLBACK_RESPONSE_03(callback_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_RESPONSES_03 (RESPONSE_ID, CALLBACK_ID, RESPONSE) VALUES (UUID_STRING(), :callback_id, :response);
UPDATE DOCGEN.ASYNC_CALLBACKS_03 SET STATUS = 'COMPLETED' WHERE CALLBACK_ID = :callback_id;
$$

