CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNING_METRIC_03(bundle_id STRING, metric_key STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNING_METRICS_03 (METRIC_ID, BUNDLE_ID, METRIC_KEY, METRIC_VALUE) VALUES (UUID_STRING(), :bundle_id, :metric_key, :metric_value);
$$

