CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_CHECKSUM_03(document_id STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_CHECKSUMS_03 (CHECKSUM_ID, DOCUMENT_ID, HASH) VALUES (UUID_STRING(), :document_id, :hash);
$$

