CREATE OR REPLACE PROCEDURE DOCGEN.STORE_AFFIDAVIT_03(bundle_id STRING, text CLOB, signed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AFFIDAVITS_03 (AFFIDAVIT_ID, BUNDLE_ID, TEXT, SIGNED_AT) VALUES (UUID_STRING(), :bundle_id, :text, :signed_at);
$$

