CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNATURE_POLICY_AUDIT_03(policy_id STRING, action STRING, admin_user STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_POLICY_AUDIT_03 (AUDIT_ID, POLICY_ID, ACTION, ADMIN_USER) VALUES (UUID_STRING(), :policy_id, :action, :admin_user);
$$

