CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THIRD_PARTY_INTEGRATION_03(integration_id STRING, name STRING, type STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_INTEGRATIONS_03 (INTEGRATION_ID, NAME, TYPE, CONFIG) VALUES (:integration_id, :name, :type, :config);
$$

