CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THIRD_PARTY_EVENT_03(integration_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_EVENTS_03 (EVENT_ID, INTEGRATION_ID, PAYLOAD) VALUES (UUID_STRING(), :integration_id, :payload);
$$

