CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RETENTION_EXCEPTION_03(target_ref STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_EXCEPTIONS_03 (EXCEPTION_ID, TARGET_REF, REASON) VALUES (UUID_STRING(), :target_ref, :reason);
$$

