CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_NOTIFICATION_03(title STRING, body CLOB, level STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_NOTIFICATIONS_03 (NOTIFY_ID, TITLE, BODY, LEVEL, CONTEXT) VALUES (UUID_STRING(), :title, :body, :level, :context);
$$

