CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ACTION_03(admin_user STRING, action STRING, target_object STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTIONS_03 (ACTION_ID, ADMIN_USER, ACTION, TARGET_OBJECT, DETAILS) VALUES (UUID_STRING(), :admin_user, :action, :target_object, :details);
$$

