CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_API_TOKEN_03(token_id STRING, name STRING, token_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_TOKENS_03 (TOKEN_ID, NAME, TOKEN_HASH, EXPIRES_AT) VALUES (:token_id, :name, :token_hash, :expires_at);
$$

