CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_ACCESS_LOG_03(token_id STRING, endpoint STRING, request_payload VARIANT, response_code INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_ACCESS_LOGS_03 (LOG_ID, TOKEN_ID, ENDPOINT, REQUEST_PAYLOAD, RESPONSE_CODE) VALUES (UUID_STRING(), :token_id, :endpoint, :request_payload, :response_code);
$$

