CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ROTATION_03(key_id STRING, rotated_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_HISTORY_03 (ROTATION_ID, KEY_ID, ROTATED_BY, META) VALUES (UUID_STRING(), :key_id, :rotated_by, :meta);
$$

