CREATE OR REPLACE PROCEDURE DOCGEN.SEND_SIGNATURE_NOTIFICATION_04(notify_id STRING, bundle_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_NOTIFICATIONS_04 (NOTIFY_ID, BUNDLE_ID, CHANNEL, PAYLOAD, STATUS) VALUES (:notify_id, :bundle_id, :channel, :payload, 'PENDING');
$$

