CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_CHANNEL_CONFIG_04(config_id STRING, channel STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.CHANNEL_CONFIGS_04 t USING (SELECT :config_id AS cid, :channel AS ch, :config AS cfg, :enabled AS en) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET CHANNEL = s.ch, CONFIG = s.cfg, ENABLED = s.en, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, CHANNEL, CONFIG, ENABLED) VALUES (s.cid, s.ch, s.cfg, s.en);
$$

