CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SMS_DELIVERY_04(delivery_id STRING, notify_id STRING, phone STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMS_DELIVERIES_04 (DELIVERY_ID, NOTIFY_ID, PHONE, STATUS, RESPONSE) VALUES (:delivery_id, :notify_id, :phone, :status, :response);
$$

