CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EMAIL_DELIVERY_04(delivery_id STRING, notify_id STRING, email STRING, subject STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_DELIVERIES_04 (DELIVERY_ID, NOTIFY_ID, EMAIL, SUBJECT, STATUS, RESPONSE) VALUES (:delivery_id, :notify_id, :email, :subject, :status, :response);
$$

