CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_HEALTH_04(provider_name STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_HEALTH_04 t USING (SELECT :provider_name AS pn, :status AS st, :details AS dt) s ON t.PROVIDER_NAME = s.pn WHEN MATCHED THEN UPDATE SET STATUS = s.st, LAST_CHECK = CURRENT_TIMESTAMP(), DETAILS = s.dt WHEN NOT MATCHED THEN INSERT (PROVIDER_NAME, STATUS, LAST_CHECK, DETAILS) VALUES (s.pn, s.st, CURRENT_TIMESTAMP(), s.dt);
$$

