CREATE OR REPLACE PROCEDURE DOCGEN.SET_PROVIDER_RATE_LIMIT_04(limit_id STRING, provider_name STRING, limits VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_RATE_LIMITS_04 t USING (SELECT :limit_id AS lid, :provider_name AS pn, :limits AS l) s ON t.LIMIT_ID = s.lid WHEN MATCHED THEN UPDATE SET PROVIDER_NAME = s.pn, LIMITS = s.l, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (LIMIT_ID, PROVIDER_NAME, LIMITS) VALUES (s.lid, s.pn, s.l);
$$

