CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_QUOTA_04(quota_id STRING, provider_name STRING, quota VARIANT, period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_QUOTAS_04 (QUOTA_ID, PROVIDER_NAME, QUOTA, PERIOD_START, PERIOD_END) VALUES (:quota_id, :provider_name, :quota, :period_start, :period_end);
$$

