CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_TELEMETRY_04(provider_name STRING, metric_key STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_TELEMETRY_04 (TELE_ID, PROVIDER_NAME, METRIC_KEY, METRIC_VALUE) VALUES (UUID_STRING(), :provider_name, :metric_key, :metric_value);
$$

