CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_USAGE_04(usage_id STRING, template_id STRING, account_id STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_04 (USAGE_ID, TEMPLATE_ID, ACCOUNT_ID, CONTEXT) VALUES (:usage_id, :template_id, :account_id, :context);
$$

