CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT_04(consent_id STRING, user_ref STRING, consent_type STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_RECORDS_04 (CONSENT_ID, USER_REF, CONSENT_TYPE, META) VALUES (:consent_id, :user_ref, :consent_type, :meta);
$$

