CREATE OR REPLACE PROCEDURE DOCGEN.STORE_LEGAL_METADATA_04(meta_id STRING, bundle_id STRING, jurisdiction STRING, legal_notes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_METADATA_04 (META_ID, BUNDLE_ID, JURISDICTION, LEGAL_NOTES) VALUES (:meta_id, :bundle_id, :jurisdiction, :legal_notes);
$$

