CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXTERNAL_AUDIT_04(audit_id STRING, bundle_id STRING, auditor STRING, report_ref STRING, completed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXTERNAL_AUDITS_04 (AUDIT_ID, BUNDLE_ID, AUDITOR, REPORT_REF, COMPLETED_AT) VALUES (:audit_id, :bundle_id, :auditor, :report_ref, :completed_at);
$$

