CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_ARCHIVE_CHECKSUM_04(archive_id STRING, bundle_id STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_CHECKSUMS_04 (ARCHIVE_ID, BUNDLE_ID, CHECKSUM) VALUES (:archive_id, :bundle_id, :checksum);
$$

