CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DATA_EXPORT_04(export_id STRING, type STRING, created_by STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_EXPORTS_04 (EXPORT_ID, TYPE, CREATED_BY, STATUS, LOCATION) VALUES (:export_id, :type, :created_by, 'QUEUED', :location);
$$

