CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXPORT_RECONCILIATION_04(recon_id STRING, export_id STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPORT_RECONCILIATIONS_04 (RECON_ID, EXPORT_ID, STATUS, DETAILS) VALUES (:recon_id, :export_id, :status, :details);
$$

