CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DELETION_REQUEST_04(req_id STRING, target_ref STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DELETION_REQUESTS_04 (REQ_ID, TARGET_REF, REQUESTED_BY) VALUES (:req_id, :target_ref, :requested_by);
$$

