CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DELETION_ACTION_04(action_id STRING, req_id STRING, action STRING, performed_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DELETION_ACTIONS_04 (ACTION_ID, REQ_ID, ACTION, PERFORMED_BY) VALUES (:action_id, :req_id, :action, :performed_by);
$$

