CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PRIVACY_REQUEST_04(req_id STRING, user_ref STRING, type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUESTS_04 (REQ_ID, USER_REF, TYPE, STATUS) VALUES (:req_id, :user_ref, :type, 'OPEN');
$$

