CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PRIVACY_RESPONSE_04(resp_id STRING, req_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_RESPONSES_04 (RESP_ID, REQ_ID, RESPONSE) VALUES (:resp_id, :req_id, :response);
UPDATE DOCGEN.PRIVACY_REQUESTS_04 SET STATUS = 'CLOSED' WHERE REQ_ID = :req_id;
$$

