CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_OBFUSCATION_RULE_04(rule_id STRING, name STRING, pattern STRING, replacement STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OBFUSCATION_RULES_04 t USING (SELECT :rule_id AS rid, :name AS nm, :pattern AS pat, :replacement AS repl, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, PATTERN = s.pat, REPLACEMENT = s.repl, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, PATTERN, REPLACEMENT, ENABLED) VALUES (s.rid, s.nm, s.pat, s.repl, s.en);
$$

