CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ASYNC_METRIC_04(name STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ASYNC_METRICS_04 (METRIC_ID, NAME, VALUE) VALUES (UUID_STRING(), :name, :value);
$$

