CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_ROLE_04(role_id STRING, name STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ROLES_04 (ROLE_ID, NAME, PERMISSIONS) VALUES (:role_id, :name, :permissions);
$$

