CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEVICE_FINGERPRINT_05(fp_id STRING, signer_id STRING, device_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_FINGERPRINTS_05 (FP_ID, SIGNER_ID, DEVICE_META) VALUES (:fp_id, :signer_id, :device_meta);
$$

