CREATE OR REPLACE PROCEDURE DOCGEN.STORE_NONCE_05(nonce_id STRING, bundle_id STRING, nonce STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NONCE_STORE_05 (NONCE_ID, BUNDLE_ID, NONCE, EXPIRES_AT) VALUES (:nonce_id, :bundle_id, :nonce, :expires_at);
$$

