CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POLICY_VERSION_05(version_id STRING, policy_id STRING, version_num INT, definition VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_VERSIONS_05 (VERSION_ID, POLICY_ID, VERSION_NUM, DEFINITION) VALUES (:version_id, :policy_id, :version_num, :definition);
$$

