CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONSENT_HISTORY_05(consent_id STRING, change_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_HISTORY_05 (CH_ID, CONSENT_ID, CHANGE_TYPE, DETAILS) VALUES (UUID_STRING(), :consent_id, :change_type, :details);
$$

