CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TAMPER_CHECK_05(check_id STRING, bundle_id STRING, check_type STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TAMPER_CHECKS_05 (CHECK_ID, BUNDLE_ID, CHECK_TYPE, RESULT) VALUES (:check_id, :bundle_id, :check_type, :result);
$$

