CREATE OR REPLACE PROCEDURE DOCGEN.RUN_EVIDENCE_CHECK_05(evc_id STRING, bundle_id STRING, check_name STRING, pass BOOLEAN, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_CHECKS_05 (EVC_ID, BUNDLE_ID, CHECK_NAME, PASS, DETAILS) VALUES (:evc_id, :bundle_id, :check_name, :pass, :details);
$$

