CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SIGNATURE_IMAGE_05(img_id STRING, signer_id STRING, bundle_id STRING, image_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_IMAGES_05 (IMG_ID, SIGNER_ID, BUNDLE_ID, IMAGE_REF) VALUES (:img_id, :signer_id, :bundle_id, :image_ref);
$$

