CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_IMAGE_DERIVATIVE_05(deriv_id STRING, img_id STRING, deriv_type STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IMAGE_DERIVATIVES_05 (DERIV_ID, IMG_ID, DERIV_TYPE, LOCATION) VALUES (:deriv_id, :img_id, :deriv_type, :location);
$$

