CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_IMAGE_HASH_05(hash_id STRING, img_id STRING, hash STRING, algorithm STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IMAGE_HASHES_05 (HASH_ID, IMG_ID, HASH, ALGORITHM) VALUES (:hash_id, :img_id, :hash, :algorithm);
$$

