CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EMBEDDING_SNAPSHOT_05(snap_id STRING, shard_ref STRING, snap_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMBEDDING_SNAPSHOTS_05 (SNAP_ID, SHARD_REF, SNAP_LOCATION) VALUES (:snap_id, :shard_ref, :snap_location);
$$

