CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_INDEX_SHARD_05(shard_id STRING, snap_id STRING, node_ref STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_SHARD_MAP_05 (SHARD_ID, SNAP_ID, NODE_REF, STATUS) VALUES (:shard_id, :snap_id, :node_ref, :status);
$$

