CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_REBALANCE_05(rebal_id STRING, shard_id STRING, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_REBALANCE_05 (REBAL_ID, SHARD_ID, ACTION) VALUES (:rebal_id, :shard_id, :action);
$$

