CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_DECISION_05(decision_id STRING, bundle_id STRING, model_id STRING, decision VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_DECISIONS_05 (DECISION_ID, BUNDLE_ID, MODEL_ID, DECISION) VALUES (:decision_id, :bundle_id, :model_id, :decision);
$$

