CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_MODEL_FEEDBACK_05(fb_id STRING, decision_id STRING, feedback VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_FEEDBACK_05 (FB_ID, DECISION_ID, FEEDBACK) VALUES (:fb_id, :decision_id, :feedback);
$$

