CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EXPLAINABILITY_05(log_id STRING, decision_id STRING, explanation VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EXPLAINABILITY_LOGS_05 (LOG_ID, DECISION_ID, EXPLANATION) VALUES (:log_id, :decision_id, :explanation);
$$

