CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ARCHIVAL_INDEX_05(arch_id STRING, bundle_id STRING, arch_location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVAL_INDEX_05 (ARCH_ID, BUNDLE_ID, ARCH_LOCATION) VALUES (:arch_id, :bundle_id, :arch_location);
$$

