CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RESTORE_JOB_05(restore_id STRING, arch_id STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RESTORE_JOBS_05 (RESTORE_ID, ARCH_ID, REQUESTED_BY, STATUS) VALUES (:restore_id, :arch_id, :requested_by, 'QUEUED');
$$

