CREATE OR REPLACE PROCEDURE DOCGEN.RUN_COMPLIANCE_CHECK_05(cchk_id STRING, bundle_id STRING, check_name STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CHECKS_05 (CCHK_ID, BUNDLE_ID, CHECK_NAME, RESULT) VALUES (:cchk_id, :bundle_id, :check_name, :result);
$$

