CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_COMPLIANCE_ISSUE_05(issue_id STRING, bundle_id STRING, description STRING, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_ISSUES_05 (ISSUE_ID, BUNDLE_ID, DESCRIPTION, SEVERITY) VALUES (:issue_id, :bundle_id, :description, :severity);
$$

