CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_MONITORING_RULE_05(rule_id STRING, name STRING, expression STRING, severity STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.MONITORING_RULES_05 t USING (SELECT :rule_id AS rid, :name AS nm, :expression AS expr, :severity AS sev, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, EXPRESSION = s.expr, SEVERITY = s.sev, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, EXPRESSION, SEVERITY, ENABLED) VALUES (s.rid, s.nm, s.expr, s.sev, s.en);
$$

