CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MONITORING_EVENT_05(rule_id STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MONITORING_EVENTS_05 (EVENT_ID, RULE_ID, CONTEXT) VALUES (UUID_STRING(), :rule_id, :context);
$$

