CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ONCALL_ROTATION_05(rotation_id STRING, name STRING, members ARRAY, timezone STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ONCALL_ROTATIONS_05 (ROTATION_ID, NAME, MEMBERS, TIMEZONE) VALUES (:rotation_id, :name, :members, :timezone);
$$

