CREATE OR REPLACE PROCEDURE DOCGEN.ADD_ESCALATION_CONTACT_05(ec_id STRING, policy_id STRING, contact_id STRING, ordering INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_CONTACTS_05 (EC_ID, POLICY_ID, CONTACT_ID, ORDERING) VALUES (:ec_id, :policy_id, :contact_id, :ordering);
$$

