CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SUPPORT_TICKET_05(ticket_id STRING, bundle_id STRING, subject STRING, body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_TICKETS_05 (TICKET_ID, BUNDLE_ID, SUBJECT, BODY, STATUS) VALUES (:ticket_id, :bundle_id, :subject, :body, 'OPEN');
$$

