CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TICKET_UPDATE_05(update_id STRING, ticket_id STRING, author STRING, update_text CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TICKET_UPDATES_05 (UPDATE_ID, TICKET_ID, AUTHOR, UPDATE_TEXT) VALUES (:update_id, :ticket_id, :author, :update_text);
$$

