CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_MAINTENANCE_WINDOW_05(window_id STRING, name STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS_05 (WINDOW_ID, NAME, START_AT, END_AT, REASON) VALUES (:window_id, :name, :start_at, :end_at, :reason);
$$

