CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SAML_MAPPING_05(mapping_id STRING, idp_id STRING, mapping_rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SAML_MAPPINGS_05 t USING (SELECT :mapping_id AS mid, :idp_id AS iid, :mapping_rules AS mr) s ON t.MAPPING_ID = s.mid WHEN MATCHED THEN UPDATE SET IDP_ID = s.iid, MAPPING_RULES = s.mr, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (MAPPING_ID, IDP_ID, MAPPING_RULES) VALUES (s.mid, s.iid, s.mr);
$$

