CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_OAUTH_CLIENT_05(client_id STRING, name STRING, redirect_uris ARRAY, scopes ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_CLIENTS_05 (CLIENT_ID, NAME, REDIRECT_URIS, SCOPES) VALUES (:client_id, :name, :redirect_uris, :scopes);
$$

