CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_SIGNATURE_EVENT_06(sei_id STRING, event_ref STRING, event_type STRING, source_system STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVENT_INDEX_06 (SEI_ID, EVENT_REF, EVENT_TYPE, SOURCE_SYSTEM) VALUES (:sei_id, :event_ref, :event_type, :source_system);
$$
