CREATE OR REPLACE PROCEDURE DOCGEN.QUARANTINE_BUNDLE_06(qid STRING, bundle_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_QUARANTINE_06 (QUARANTINE_ID, BUNDLE_ID, REASON) VALUES (:qid, :bundle_id, :reason);
$$
