CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_QUARANTINE_HISTORY_06(history_id STRING, quarantine_id STRING, action STRING, acted_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUARANTINE_HISTORY_06 (HISTORY_ID, QUARANTINE_ID, ACTION, ACTED_BY) VALUES (:history_id, :quarantine_id, :action, :acted_by);
$$
