CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_BIOMETRICS_PROFILE_06(profile_id STRING, signer_id STRING, biometric_hash STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.BIOMETRICS_PROFILES_06 t USING (SELECT :profile_id AS pid, :signer_id AS sid, :biometric_hash AS bh, :meta AS m) s ON t.PROFILE_ID = s.pid WHEN MATCHED THEN UPDATE SET SIGNER_ID = s.sid, BIOMETRIC_HASH = s.bh, META = s.m WHEN NOT MATCHED THEN INSERT (PROFILE_ID, SIGNER_ID, BIOMETRIC_HASH, META) VALUES (s.pid, s.sid, s.bh, s.m);
$$
