CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_EVENT_06(event_id STRING, profile_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_EVENTS_06 (EVENT_ID, PROFILE_ID, EVENT_TYPE, PAYLOAD) VALUES (:event_id, :profile_id, :event_type, :payload);
$$
