CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BIOMETRICS_MATCH_JOB_06(job_id STRING, profile_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRICS_MATCH_JOBS_06 (JOB_ID, PROFILE_ID, STATUS) VALUES (:job_id, :profile_id, 'QUEUED');
$$
