CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH_06(match_id STRING, job_id STRING, candidate_profile_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCHES_06 (MATCH_ID, JOB_ID, CANDIDATE_PROFILE_ID, SCORE) VALUES (:match_id, :job_id, :candidate_profile_id, :score);
$$
