CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEVICE_TRUST_SCORE_06(score_id STRING, device_ref STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_TRUST_SCORES_06 (SCORE_ID, DEVICE_REF, SCORE) VALUES (:score_id, :device_ref, :score);
$$
