CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TIME_SERIES_METRIC_06(metric_id STRING, name STRING, ts TIMESTAMP_LTZ, value FLOAT, tags VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TIME_SERIES_METRICS_06 (METRIC_ID, NAME, TS, VALUE, TAGS) VALUES (:metric_id, :name, :ts, :value, :tags);
$$
