CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CAPACITY_PLAN_06(plan_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CAPACITY_PLANS_06 (PLAN_ID, NAME, CONFIG) VALUES (:plan_id, :name, :config);
$$
