CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_USAGE_FORECAST_06(forecast_id STRING, account_id STRING, prediction VARIANT, horizon STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_FORECASTS_06 (FORECAST_ID, ACCOUNT_ID, PREDICTION, HORIZON) VALUES (:forecast_id, :account_id, :prediction, :horizon);
$$
