CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BILLING_ALERT_06(alert_id STRING, account_id STRING, trigger VARIANT, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_ALERTS_06 (ALERT_ID, ACCOUNT_ID, TRIGGER, ACTION) VALUES (:alert_id, :account_id, :trigger, :action);
$$
