CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FRAUD_ALERT_06(alert_id STRING, bundle_id STRING, rule_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_ALERTS_06 (ALERT_ID, BUNDLE_ID, RULE_ID, SCORE) VALUES (:alert_id, :bundle_id, :rule_id, :score);
$$
