CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THREAT_INTEL_FEED_06(feed_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_INTEL_FEEDS_06 (FEED_ID, NAME, CONFIG) VALUES (:feed_id, :name, :config);
$$
