CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THREAT_INTEL_HIT_06(hit_id STRING, feed_id STRING, target_ref STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_INTEL_HITS_06 (HIT_ID, FEED_ID, TARGET_REF, DETAILS) VALUES (:hit_id, :feed_id, :target_ref, :details);
$$
