CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_KPI_DEFINITION_06(kpi_id STRING, name STRING, query STRING, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.KPI_DEFINITIONS_06 t USING (SELECT :kpi_id AS kid, :name AS nm, :query AS q, :owner AS o) s ON t.KPI_ID = s.kid WHEN MATCHED THEN UPDATE SET NAME = s.nm, QUERY = s.q, OWNER = s.o, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (KPI_ID, NAME, QUERY, OWNER) VALUES (s.kid, s.nm, s.q, s.o);
$$
