CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KPI_VALUE_06(value_id STRING, kpi_id STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KPI_VALUES_06 (VALUE_ID, KPI_ID, VALUE) VALUES (:value_id, :kpi_id, :value);
$$
