CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REPORT_JOB_06(report_job_id STRING, name STRING, schedule STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPORT_JOBS_06 (REPORT_JOB_ID, NAME, SCHEDULE) VALUES (:report_job_id, :name, :schedule);
$$
