CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REPORT_RUN_06(run_id STRING, report_job_id STRING, status STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REPORT_RUNS_06 (RUN_ID, REPORT_JOB_ID, STATUS, LOCATION) VALUES (:run_id, :report_job_id, :status, :location);
$$
