CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_CLOSURE_TASK_06(task_id STRING, bundle_id STRING, type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLOSURE_TASKS_06 (TASK_ID, BUNDLE_ID, TYPE, STATUS) VALUES (:task_id, :bundle_id, :type, 'QUEUED');
$$
