CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REVIEW_WORKFLOW_06(workflow_id STRING, bundle_id STRING, name STRING, steps VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVIEW_WORKFLOWS_06 (WORKFLOW_ID, BUNDLE_ID, NAME, STEPS, OWNER) VALUES (:workflow_id, :bundle_id, :name, :steps, :owner);
$$

