CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REVIEW_INSTANCE_06(instance_id STRING, workflow_id STRING, current_step INT, status STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVIEW_INSTANCES_06 (INSTANCE_ID, WORKFLOW_ID, CURRENT_STEP, STATUS, META) VALUES (:instance_id, :workflow_id, :current_step, :status, :meta);
$$

