CREATE OR REPLACE PROCEDURE DOCGEN.BIND_POLICY_06(binding_id STRING, policy_id STRING, target_type STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_BINDINGS_06 (BINDING_ID, POLICY_ID, TARGET_TYPE, TARGET_REF) VALUES (:binding_id, :policy_id, :target_type, :target_ref);
$$

