CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REVIEW_EVENT_06(event_id STRING, instance_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVIEW_EVENTS_06 (EVENT_ID, INSTANCE_ID, EVENT_TYPE, PAYLOAD) VALUES (:event_id, :instance_id, :event_type, :payload);
$$

