CREATE OR REPLACE PROCEDURE DOCGEN.EVALUATE_POLICY_06(eval_id STRING, binding_id STRING, context VARIANT, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_EVALUATIONS_06 (EVAL_ID, BINDING_ID, CONTEXT, RESULT) VALUES (:eval_id, :binding_id, :context, :result);
$$

