CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_APPROVAL_LOG_06(log_id STRING, instance_id STRING, approver STRING, action STRING, notes CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_LOGS_06 (LOG_ID, INSTANCE_ID, APPROVER, ACTION, NOTES) VALUES (:log_id, :instance_id, :approver, :action, :notes);
$$

