CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_IDENTITY_PROVIDER_06(idp_id STRING, name STRING, type STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IDENTITY_PROVIDERS_06 (IDP_ID, NAME, TYPE, CONFIG) VALUES (:idp_id, :name, :type, :config);
$$

