CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_SSO_SESSION_06(session_id STRING, user_ref STRING, idp_id STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SSO_SESSIONS_06 (SESSION_ID, USER_REF, IDP_ID, EXPIRES_AT) VALUES (:session_id, :user_ref, :idp_id, :expires_at);
$$

