CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ESIGN_TEMPLATE_06(template_id STRING, name STRING, version INT, content CLOB, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESIGN_TEMPLATES_06 (TEMPLATE_ID, NAME, VERSION, CONTENT, METADATA) VALUES (:template_id, :name, :version, :content, :metadata);
$$

