CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_USER_ROLE_06(ur_id STRING, user_ref STRING, role_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_ROLES_06 (UR_ID, USER_REF, ROLE_ID) VALUES (:ur_id, :user_ref, :role_id);
$$

