CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_CLAUSE_06(clause_id STRING, name STRING, text CLOB, tags ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLAUSE_LIBRARY_06 (CLAUSE_ID, NAME, TEXT, TAGS) VALUES (:clause_id, :name, :text, :tags);
$$

