CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MOTION_LOG_06(log_id STRING, bundle_id STRING, motion_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MOTION_LOGS_06 (LOG_ID, BUNDLE_ID, MOTION_TYPE, DETAILS) VALUES (:log_id, :bundle_id, :motion_type, :details);
$$

