CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_TOKEN_06(revoc_id STRING, token_id STRING, revoked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TOKEN_REVOCATIONS_06 (REVOC_ID, TOKEN_ID, REVOKED_BY) VALUES (:revoc_id, :token_id, :revoked_by);
$$

