CREATE OR REPLACE PROCEDURE DOCGEN.BLACKLIST_SESSION_06(bl_id STRING, session_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_BLACKLIST_06 (BL_ID, SESSION_ID, REASON) VALUES (:bl_id, :session_id, :reason);
$$

