CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RENDER_LOG_06(log_id STRING, render_id STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_LOGS_06 (LOG_ID, RENDER_ID, MESSAGE) VALUES (:log_id, :render_id, :message);
$$

