CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PDF_ARCHIVE_06(archive_id STRING, document_id STRING, s3_path STRING, size_bytes NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PDF_ARCHIVES_06 (ARCHIVE_ID, DOCUMENT_ID, S3_PATH, SIZE_BYTES) VALUES (:archive_id, :document_id, :s3_path, :size_bytes);
$$

