CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_QUOTA_USAGE_06(usage_id STRING, client_id STRING, period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ, usage_count INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.API_QUOTA_USAGE_06 (USAGE_ID, CLIENT_ID, PERIOD_START, PERIOD_END, USAGE_COUNT) VALUES (:usage_id, :client_id, :period_start, :period_end, :usage_count);
$$

