CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ABUSE_REPORT_06(report_id STRING, reported_by STRING, target_ref STRING, description STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ABUSE_REPORTS_06 (REPORT_ID, REPORTED_BY, TARGET_REF, DESCRIPTION) VALUES (:report_id, :reported_by, :target_ref, :description);
$$

