CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PREVIEW_CACHE_06(cache_id STRING, document_id STRING, preview_url STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PREVIEW_CACHE_06 (CACHE_ID, DOCUMENT_ID, PREVIEW_URL, EXPIRES_AT) VALUES (:cache_id, :document_id, :preview_url, :expires_at);
$$

