CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ABUSE_ACTION_06(action_id STRING, report_id STRING, action STRING, actioned_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ABUSE_ACTIONS_06 (ACTION_ID, REPORT_ID, ACTION, ACTIONED_BY) VALUES (:action_id, :report_id, :action, :actioned_by);
$$

