CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RENDITION_METRIC_06(metric_id STRING, render_id STRING, latency_ms INT, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDITION_METRICS_06 (METRIC_ID, RENDER_ID, LATENCY_MS, STATUS) VALUES (:metric_id, :render_id, :latency_ms, :status);
$$

