CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ACCESS_POLICY_06(policy_id STRING, name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ACCESS_POLICIES_06 t USING (SELECT :policy_id AS pid, :name AS nm, :rules AS r, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, ENABLED = s.en, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RULES, ENABLED) VALUES (s.pid, s.nm, s.r, s.en);
$$

