CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CALLBACK_AUTH_06(auth_id STRING, sub_id STRING, auth_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_AUTHORIZATIONS_06 (AUTH_ID, SUB_ID, AUTH_HASH, EXPIRES_AT) VALUES (:auth_id, :sub_id, :auth_hash, :expires_at);
$$

