CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CALLBACK_AUDIT_06(audit_id STRING, auth_id STRING, payload VARIANT, validated BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_AUDIT_06 (AUDIT_ID, AUTH_ID, PAYLOAD, VALIDATED) VALUES (:audit_id, :auth_id, :payload, :validated);
$$

