CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_ROLE_POLICY_06(role_policy_id STRING, role_id STRING, policy_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROLE_POLICIES_06 (ROLE_POLICY_ID, ROLE_ID, POLICY_REF) VALUES (:role_policy_id, :role_id, :policy_ref);
$$

