CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PROVIDER_CREDENTIAL_06(cred_id STRING, provider_name STRING, cred_hash STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CREDENTIALS_06 (CRED_ID, PROVIDER_NAME, CRED_HASH, META) VALUES (:cred_id, :provider_name, :cred_hash, :meta);
$$

