CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_ROTATION_06(rotation_id STRING, provider_name STRING, rotated_by STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_ROTATION_06 (ROTATION_ID, PROVIDER_NAME, ROTATED_BY, META) VALUES (:rotation_id, :provider_name, :rotated_by, :meta);
$$

