CREATE OR REPLACE PROCEDURE DOCGEN.TOGGLE_FEATURE_FLAG_06(flag_id STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.FEATURE_FLAGS_06 SET DEFAULT = :enabled, UPDATED_AT = CURRENT_TIMESTAMP() WHERE FLAG_ID = :flag_id;
$$

