CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REMEDIATION_TASK_06(task_id STRING, sa_id STRING, actions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REMEDIATION_TASKS_06 (TASK_ID, SA_ID, ACTIONS) VALUES (:task_id, :sa_id, :actions);
$$

