CREATE OR REPLACE PROCEDURE DOCGEN.SET_ACCOUNT_LIMIT_06(limit_id STRING, account_id STRING, limits VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ACCOUNT_LIMITS_06 t USING (SELECT :limit_id AS lid, :account_id AS aid, :limits AS l) s ON t.LIMIT_ID = s.lid WHEN MATCHED THEN UPDATE SET ACCOUNT_ID = s.aid, LIMITS = s.l WHEN NOT MATCHED THEN INSERT (LIMIT_ID, ACCOUNT_ID, LIMITS) VALUES (s.lid, s.aid, s.l);
$$

