CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PAYMENT_METHOD_REF_06(pm_id STRING, account_id STRING, pm_type STRING, reference VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PAYMENT_METHOD_REFS_06 (PM_ID, ACCOUNT_ID, PM_TYPE, REFERENCE) VALUES (:pm_id, :account_id, :pm_type, :reference);
$$

