CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PURGE_JOB_06(purge_id STRING, target_table STRING, cron_expr STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_QUEUE_06 (PURGE_ID, TARGET_TABLE, CRON_EXPR) VALUES (:purge_id, :target_table, :cron_expr);
$$

