CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PAYMENT_ATTEMPT_06(attempt_id STRING, pm_id STRING, amount NUMBER, currency STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PAYMENT_ATTEMPTS_06 (ATTEMPT_ID, PM_ID, AMOUNT, CURRENCY, STATUS) VALUES (:attempt_id, :pm_id, :amount, :currency, :status);
$$

