CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PURGE_AUDIT_06(audit_id STRING, purge_id STRING, rows_purged NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_AUDIT_06 (AUDIT_ID, PURGE_ID, ROWS_PURGED) VALUES (:audit_id, :purge_id, :rows_purged);
$$

