CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BACKUP_MANIFEST_06(manifest_id STRING, targets VARIANT, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKUP_MANIFESTS_06 (MANIFEST_ID, TARGETS, LOCATION) VALUES (:manifest_id, :targets, :location);
$$

