CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKUP_RUN_06(run_id STRING, manifest_id STRING, status STRING, output VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKUP_RUNS_06 (RUN_ID, MANIFEST_ID, STATUS, OUTPUT) VALUES (:run_id, :manifest_id, :status, :output);
$$

