CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_BILLING_DISPUTE_06(dispute_id STRING, invoice_id STRING, account_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_DISPUTES_06 (DISPUTE_ID, INVOICE_ID, ACCOUNT_ID, REASON, STATUS) VALUES (:dispute_id, :invoice_id, :account_id, :reason, 'OPEN');
$$

