CREATE OR REPLACE PROCEDURE DOCGEN.ROTATE_STORAGE_KEY_06(key_id STRING, key_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.STORAGE_ENCRYPTION_KEYS_06 (KEY_ID, KEY_META, ACTIVE) VALUES (:key_id, :key_meta, TRUE);
$$

