CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ACCESS_06(log_id STRING, key_id STRING, accessor STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ACCESS_LOGS_06 (LOG_ID, KEY_ID, ACCESSOR, ACTION) VALUES (:log_id, :key_id, :accessor, :action);
$$

