CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_HSM_LOG_06(log_id STRING, integration_id STRING, operation STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HSM_LOGS_06 (LOG_ID, INTEGRATION_ID, OPERATION, DETAILS) VALUES (:log_id, :integration_id, :operation, :details);
$$

