CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_CERT_REVOCATION_STATUS_06(cert_id STRING, revocation_status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.CERT_REVOCATION_INDEX_06 t USING (SELECT :cert_id AS cid, :revocation_status AS rs) s ON t.CERT_ID = s.cid WHEN MATCHED THEN UPDATE SET REVOCATION_STATUS = s.rs, LAST_CHECK = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CERT_ID, REVOCATION_STATUS, LAST_CHECK) VALUES (s.cid, s.rs, CURRENT_TIMESTAMP());
$$

