CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_TIMESTAMP_AUTHORITY_06(ta_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TIMESTAMP_AUTHORITIES_06 (TA_ID, NAME, CONFIG) VALUES (:ta_id, :name, :config);
$$

