CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TIMESTAMP_06(ts_id STRING, bundle_id STRING, ta_id STRING, ts_token VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TIMESTAMPS_06 (TS_ID, BUNDLE_ID, TA_ID, TS_TOKEN) VALUES (:ts_id, :bundle_id, :ta_id, :ts_token);
$$

