CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FORENSIC_EXPORT_06(forensic_id STRING, bundle_id STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FORENSIC_EXPORTS_06 (FORENSIC_ID, BUNDLE_ID, LOCATION) VALUES (:forensic_id, :bundle_id, :location);
$$

