CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHAIN_PROOF_06(proof_id STRING, bundle_id STRING, proof VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHAIN_PROOFS_06 (PROOF_ID, BUNDLE_ID, PROOF) VALUES (:proof_id, :bundle_id, :proof);
$$

