CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_EVIDENCE_EXPORT_06(evidence_export_id STRING, bundle_id STRING, format STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_EXPORTS_06 (EVIDENCE_EXPORT_ID, BUNDLE_ID, FORMAT, LOCATION) VALUES (:evidence_export_id, :bundle_id, :format, :location);
$$

