CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_LEGAL_HOLD_06(hold_id STRING, target_ref STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLDS_06 (HOLD_ID, TARGET_REF, REASON) VALUES (:hold_id, :target_ref, :reason);
$$

