CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_HOLD_EXEMPTION_06(exemption_id STRING, hold_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HOLD_EXEMPTIONS_06 (EXEMPTION_ID, HOLD_ID, REASON) VALUES (:exemption_id, :hold_id, :reason);
$$

