CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_THIRD_PARTY_EXPORT_06(export_id STRING, integration_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_EXPORTS_06 (EXPORT_ID, INTEGRATION_ID, PAYLOAD, STATUS) VALUES (:export_id, :integration_id, :payload, 'QUEUED');
$$

