CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INTEGRATION_RESPONSE_06(resp_id STRING, export_id STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INTEGRATION_RESPONSES_06 (RESP_ID, EXPORT_ID, RESPONSE) VALUES (:resp_id, :export_id, :response);
$$

