CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_CONSENT_06(consent_id STRING, integration_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_CONSENT_06 (CONSENT_ID, INTEGRATION_ID, ACCOUNT_ID) VALUES (:consent_id, :integration_id, :account_id);
$$

