CREATE OR REPLACE PROCEDURE DOCGEN.ACTIVATE_RATECARD_VERSION_06(rate_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.RATECARD_VERSIONS_06 SET ACTIVE = CASE WHEN RATE_ID = :rate_id THEN TRUE ELSE FALSE END;
$$

