CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_PRICING_CACHE_06(cache_id STRING, account_id STRING, rate_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PRICING_CACHE_06 t USING (SELECT :cache_id AS cid, :account_id AS aid, :rate_ref AS rr) s ON t.CACHE_ID = s.cid WHEN MATCHED THEN UPDATE SET ACCOUNT_ID = s.aid, RATE_REF = s.rr, CACHED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CACHE_ID, ACCOUNT_ID, RATE_REF) VALUES (s.cid, s.aid, s.rr);
$$

