CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INVOICE_PREVIEW_06(preview_id STRING, account_id STRING, line_items VARIANT, invoice_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_PREVIEWS_06 (PREVIEW_ID, ACCOUNT_ID, LINE_ITEMS, INVOICE_HASH) VALUES (:preview_id, :account_id, :line_items, :invoice_hash);
$$

