CREATE OR REPLACE PROCEDURE DOCGEN.ADD_INVOICE_LINE_ITEM_06(item_id STRING, preview_id STRING, description STRING, amount NUMBER, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_LINE_ITEMS_06 (ITEM_ID, PREVIEW_ID, DESCRIPTION, AMOUNT, META) VALUES (:item_id, :preview_id, :description, :amount, :meta);
$$

