CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_BILLING_RECONCILE_06(job_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_RECONCILE_JOBS_06 (JOB_ID, ACCOUNT_ID, STATUS) VALUES (:job_id, :account_id, 'QUEUED');
$$

