CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PARTNER_ACCOUNT_06(partner_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_ACCOUNTS_06 (PARTNER_ID, NAME, CONFIG) VALUES (:partner_id, :name, :config);
$$

