CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PARTNER_MAPPING_06(mapping_id STRING, partner_id STRING, account_id STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_MAPPINGS_06 (MAPPING_ID, PARTNER_ID, ACCOUNT_ID, CONFIG) VALUES (:mapping_id, :partner_id, :account_id, :config);
$$

