CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PARTNER_TELEMETRY_06(partner_id STRING, metric_key STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_TELEMETRY_06 (TELE_ID, PARTNER_ID, METRIC_KEY, METRIC_VALUE) VALUES (UUID_STRING(), :partner_id, :metric_key, :metric_value);
$$

