CREATE OR REPLACE PROCEDURE DOCGEN.SET_PARTNER_RATE_LIMIT_06(limit_id STRING, partner_id STRING, limits VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PARTNER_RATE_LIMITS_06 t USING (SELECT :limit_id AS lid, :partner_id AS pid, :limits AS l) s ON t.LIMIT_ID = s.lid WHEN MATCHED THEN UPDATE SET PARTNER_ID = s.pid, LIMITS = s.l, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (LIMIT_ID, PARTNER_ID, LIMITS) VALUES (s.lid, s.pid, s.l);
$$

