CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PARTNER_SETTLEMENT_06(settlement_id STRING, partner_id STRING, amount NUMBER, period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_SETTLEMENTS_06 (SETTLEMENT_ID, PARTNER_ID, AMOUNT, PERIOD_START, PERIOD_END, STATUS) VALUES (:settlement_id, :partner_id, :amount, :period_start, :period_end, 'PENDING');
$$

