CREATE OR REPLACE PROCEDURE DOCGEN.LINK_PARTNER_INVOICE_06(link_id STRING, partner_id STRING, invoice_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PARTNER_INVOICE_LINKS_06 (LINK_ID, PARTNER_ID, INVOICE_ID) VALUES (:link_id, :partner_id, :invoice_id);
$$

