CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ADMIN_DASHBOARD_06(dash_id STRING, name STRING, config VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ADMIN_DASHBOARDS_06 t USING (SELECT :dash_id AS did, :name AS nm, :config AS cfg, :owner AS o) s ON t.DASH_ID = s.did WHEN MATCHED THEN UPDATE SET NAME = s.nm, CONFIG = s.cfg, OWNER = s.o, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (DASH_ID, NAME, CONFIG, OWNER) VALUES (s.did, s.nm, s.cfg, s.o);
$$

