CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DASHBOARD_RUN_06(run_id STRING, dash_id STRING, status STRING, output VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DASHBOARD_RUNS_06 (RUN_ID, DASH_ID, STATUS, OUTPUT) VALUES (:run_id, :dash_id, :status, :output);
$$

