CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_METRIC_06(metric_id STRING, session_id STRING, key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_SESSIONS_METRICS_06 (METRIC_ID, SESSION_ID, KEY, VALUE) VALUES (:metric_id, :session_id, :key, :value);
$$

