CREATE OR REPLACE PROCEDURE DOCGEN.RUN_IDLE_SESSION_CLEANUP_06(cleanup_id STRING, threshold_min INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.IDLE_SESSION_CLEANUP_06 (CLEANUP_ID, THRESHOLD_MIN, LAST_RUN_AT) VALUES (:cleanup_id, :threshold_min, CURRENT_TIMESTAMP());
$$

