CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_SIGNATURE_META_TAG_07(tag_id STRING, bundle_id STRING, tag STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_META_TAGS_07 (TAG_ID, BUNDLE_ID, TAG) VALUES (:tag_id, :bundle_id, :tag);
$$

