CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_LANG_TEMPLATE_07(lang_tpl_id STRING, template_id STRING, locale STRING, content CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LANG_TEMPLATES_07 (LANG_TPL_ID, TEMPLATE_ID, LOCALE, CONTENT) VALUES (:lang_tpl_id, :template_id, :locale, :content);
$$

