CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_TEMPLATE_PERMISSION_07(perm_id STRING, template_id STRING, subject_ref STRING, perm_level STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PERMISSIONS_07 (PERM_ID, TEMPLATE_ID, SUBJECT_REF, PERM_LEVEL) VALUES (:perm_id, :template_id, :subject_ref, :perm_level);
$$

