CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_DOCUMENT_PERMISSION_07(dp_id STRING, document_id STRING, subject_ref STRING, perm_level STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_PERMISSIONS_07 (DP_ID, DOCUMENT_ID, SUBJECT_REF, PERM_LEVEL) VALUES (:dp_id, :document_id, :subject_ref, :perm_level);
$$

