CREATE OR REPLACE PROCEDURE DOCGEN.APPEND_USER_ACTIVITY_07(cache_id STRING, user_ref STRING, activity VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.USER_ACTIVITY_CACHE_07 t USING (SELECT :cache_id AS cid, :user_ref AS ur, :activity AS act) s ON t.CACHE_ID = s.cid WHEN MATCHED THEN UPDATE SET USER_REF = s.ur, ACTIVITY = s.act, CACHED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CACHE_ID, USER_REF, ACTIVITY) VALUES (s.cid, s.ur, s.act);
$$

