CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_USER_ALERT_07(alert_id STRING, user_ref STRING, title STRING, body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_ALERTS_07 (ALERT_ID, USER_REF, TITLE, BODY, STATUS) VALUES (:alert_id, :user_ref, :title, :body, 'UNREAD');
$$

