CREATE OR REPLACE PROCEDURE DOCGEN.ADD_KEYWORD_BLACKLIST_07(kw_id STRING, keyword STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEYWORD_BLACKLIST_07 (KW_ID, KEYWORD, REASON) VALUES (:kw_id, :keyword, :reason);
$$

