CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEYWORD_HIT_07(hit_id STRING, kw_id STRING, document_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEYWORD_HITS_07 (HIT_ID, KW_ID, DOCUMENT_ID) VALUES (:hit_id, :kw_id, :document_id);
$$

