CREATE OR REPLACE PROCEDURE DOCGEN.RESOLVE_CONTENT_FLAG_07(res_id STRING, flag_id STRING, resolver STRING, resolution TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONTENT_FLAG_RESOLUTIONS_07 (RES_ID, FLAG_ID, RESOLVER, RESOLUTION) VALUES (:res_id, :flag_id, :resolver, :resolution);
$$

