CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_CONSENT_TOKEN_07(token_id STRING, user_ref STRING, consent_scope STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_CONSENT_TOKENS_07 (TOKEN_ID, USER_REF, CONSENT_SCOPE, EXPIRES_AT) VALUES (:token_id, :user_ref, :consent_scope, :expires_at);
$$

