CREATE OR REPLACE PROCEDURE DOCGEN.RUN_CONSENT_CHECK_07(check_id STRING, user_ref STRING, scope STRING, result BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_CHECKS_07 (CHECK_ID, USER_REF, SCOPE, RESULT) VALUES (:check_id, :user_ref, :scope, :result);
$$

