CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_GEO_RESTRICTION_07(restrict_id STRING, target_ref STRING, regions ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEO_RESTRICTIONS_07 (RESTRICT_ID, TARGET_REF, REGIONS) VALUES (:restrict_id, :target_ref, :regions);
$$

