CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEO_VIOLATION_07(violation_id STRING, target_ref STRING, region STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEO_VIOLATIONS_07 (VIOLATION_ID, TARGET_REF, REGION) VALUES (:violation_id, :target_ref, :region);
$$

