CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_PII_MASK_07(mask_id STRING, field_name STRING, mask_pattern STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PII_MASKS_07 (MASK_ID, FIELD_NAME, MASK_PATTERN) VALUES (:mask_id, :field_name, :mask_pattern);
$$

