CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PII_SCAN_JOB_07(job_id STRING, target_table STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PII_SCAN_JOBS_07 (JOB_ID, TARGET_TABLE, STATUS, STARTED_AT) VALUES (:job_id, :target_table, 'QUEUED', CURRENT_TIMESTAMP());
$$

