CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_WEBHOOK_DELIVERY_07(delivery_id STRING, sub_id STRING, payload VARIANT, next_attempt_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_DELIVERY_QUEUE_07 (DELIVERY_ID, SUB_ID, PAYLOAD, NEXT_ATTEMPT_AT) VALUES (:delivery_id, :sub_id, :payload, :next_attempt_at);
$$

