CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_WEBHOOK_ATTEMPT_07(attempt_id STRING, delivery_id STRING, response VARIANT, success BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_DELIVERY_ATTEMPTS_07 (ATTEMPT_ID, DELIVERY_ID, RESPONSE, SUCCESS) VALUES (:attempt_id, :delivery_id, :response, :success);
$$

