CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ASYNC_WORKER_07(worker_id STRING, type STRING, payload VARIANT, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ASYNC_WORKERS_07 (WORKER_ID, TYPE, PAYLOAD, STATUS, SCHEDULED_AT) VALUES (:worker_id, :type, :payload, 'PENDING', :scheduled_at);
$$

