CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EVENT_TELEMETRY_07(tele_id STRING, bundle_id STRING, event_name STRING, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVENT_TELEMETRY_07 (TELE_ID, BUNDLE_ID, EVENT_NAME, METADATA) VALUES (:tele_id, :bundle_id, :event_name, :metadata);
$$

