CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CONSENT_TEMPLATE_07(template_id STRING, name STRING, content CLOB, version INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_TEMPLATES_07 (TEMPLATE_ID, NAME, CONTENT, VERSION) VALUES (:template_id, :name, :content, :version);
$$

