-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_REVOCATION_REQUEST_07(req_id STRING, bundle_id STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVOCATION_REQUESTS_07 (REQ_ID, BUNDLE_ID, REQUESTED_BY, STATUS) VALUES (:req_id, :bundle_id, :requested_by, 'PENDING');
$$

