CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_APPROVER_QUEUE_07(queue_id STRING, name STRING, members ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVER_QUEUES_07 (QUEUE_ID, NAME, MEMBERS) VALUES (:queue_id, :name, :members);
$$

