CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_APPROVER_07(assign_id STRING, queue_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVER_ASSIGNMENTS_07 (ASSIGN_ID, QUEUE_ID, TARGET_REF) VALUES (:assign_id, :queue_id, :target_ref);
$$

