CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_SLACK_NOTIFICATION_07(notif_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLACK_NOTIFICATIONS_07 (NOTIF_ID, CHANNEL, PAYLOAD, STATUS) VALUES (:notif_id, :channel, :payload, 'QUEUED');
$$

