-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_HASH_INDEX_07(hash_id STRING, bundle_id STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.HASH_INDEX_07 t USING (SELECT :hash_id AS hid, :bundle_id AS bid, :hash AS h) s ON t.HASH_ID = s.hid WHEN MATCHED THEN UPDATE SET BUNDLE_ID = s.bid, HASH = s.h, CREATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (HASH_ID, BUNDLE_ID, HASH) VALUES (s.hid, s.bid, s.h);
$$

