CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EMAIL_07(email_id STRING, template_id STRING, recipient STRING, context VARIANT, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_QUEUE_07 (EMAIL_ID, TEMPLATE_ID, RECIPIENT, CONTEXT, STATUS, SCHEDULED_AT) VALUES (:email_id, :template_id, :recipient, :context, 'QUEUED', :scheduled_at);
$$

