CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EMAIL_DELIVERY_07(delivery_id STRING, email_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_DELIVERIES_07 (DELIVERY_ID, EMAIL_ID, STATUS, RESPONSE) VALUES (:delivery_id, :email_id, :status, :response);
$$

