-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_BLOCKCHAIN_PROVIDER_07(provider_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_PROVIDERS_07 (PROVIDER_ID, NAME, CONFIG) VALUES (:provider_id, :name, :config);
$$

