-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_BLOCKCHAIN_JOB_07(job_id STRING, provider_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_JOBS_07 (JOB_ID, PROVIDER_ID, STATUS) VALUES (:job_id, :provider_id, 'QUEUED');
$$

