CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_SMS_07(sms_id STRING, template_id STRING, recipient STRING, context VARIANT, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMS_QUEUE_07 (SMS_ID, TEMPLATE_ID, RECIPIENT, CONTEXT, STATUS, SCHEDULED_AT) VALUES (:sms_id, :template_id, :recipient, :context, 'QUEUED', :scheduled_at);
$$

