CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SMS_DELIVERY_07(delivery_id STRING, sms_id STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMS_DELIVERIES_07 (DELIVERY_ID, SMS_ID, STATUS, RESPONSE) VALUES (:delivery_id, :sms_id, :status, :response);
$$

