-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THIRD_PARTY_VERIFICATION_07(verif_id STRING, bundle_id STRING, provider STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THIRD_PARTY_VERIFICATIONS_07 (VERIF_ID, BUNDLE_ID, PROVIDER, RESULT) VALUES (:verif_id, :bundle_id, :provider, :result);
$$

