CREATE OR REPLACE PROCEDURE DOCGEN.ACQUIRE_TASK_LOCK_07(lock_id STRING, task_name STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TASK_LOCK_07 (LOCK_ID, TASK_NAME, LOCKED_BY) VALUES (:lock_id, :task_name, :locked_by);
$$

