-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.ACTIVATE_POLICY_VERSION_07(version_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.POLICY_VERSIONS_07 SET ACTIVATED_AT = CURRENT_TIMESTAMP() WHERE VERSION_ID = :version_id;
$$

