CREATE OR REPLACE PROCEDURE DOCGEN.CONSUME_RATE_LIMIT_BUCKET_07(bucket_id STRING, amount INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.RATE_LIMIT_BUCKETS_07 SET REMAINING = GREATEST(0, REMAINING - :amount) WHERE BUCKET_ID = :bucket_id;
$$

