CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_BACKPRESSURE_SIGNAL_07(signal_id STRING, source STRING, level STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKPRESSURE_SIGNALS_07 (SIGNAL_ID, SOURCE, LEVEL, DETAILS) VALUES (:signal_id, :source, :level, :details);
$$

