CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SLA_VIOLATION_07(violation_id STRING, bench_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_VIOLATIONS_07 (VIOLATION_ID, BENCH_ID, DETAILS) VALUES (:violation_id, :bench_id, :details);
$$

