CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ALERT_SUBSCRIPTION_07(sub_id STRING, name STRING, condition VARIANT, channels ARRAY, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ALERT_SUBSCRIPTIONS_07 t USING (SELECT :sub_id AS sid, :name AS nm, :condition AS cond, :channels AS ch, :enabled AS en) s ON t.SUB_ID = s.sid WHEN MATCHED THEN UPDATE SET NAME = s.nm, CONDITION = s.cond, CHANNELS = s.ch, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (SUB_ID, NAME, CONDITION, CHANNELS, ENABLED) VALUES (s.sid, s.nm, s.cond, s.ch, s.en);
$$

