CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_ALERT_EVENT_07(event_id STRING, sub_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_EVENTS_07 (EVENT_ID, SUB_ID, PAYLOAD) VALUES (:event_id, :sub_id, :payload);
$$

