CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_CASE_07(case_id STRING, title STRING, owner STRING, status STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CASES_07 (CASE_ID, TITLE, OWNER, STATUS, META) VALUES (:case_id, :title, :owner, :status, :meta);
$$

