CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CASE_EVENT_07(event_id STRING, case_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CASE_EVENTS_07 (EVENT_ID, CASE_ID, EVENT_TYPE, PAYLOAD) VALUES (:event_id, :case_id, :event_type, :payload);
$$

