CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESCALATION_RUN_07(run_id STRING, policy_id STRING, context VARIANT, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESCALATION_RUNS_07 (RUN_ID, POLICY_ID, CONTEXT, RESULT) VALUES (:run_id, :policy_id, :context, :result);
$$

