-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_TENANT_CONFIG_07(config_id STRING, tenant_id STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TENANT_CONFIGS_07 t USING (SELECT :config_id AS cid, :tenant_id AS tid, :config AS cfg) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET TENANT_ID = s.tid, CONFIG = s.cfg, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, TENANT_ID, CONFIG) VALUES (s.cid, s.tid, s.cfg);
$$

