CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATOR_NOTE_07(note_id STRING, op_id STRING, note CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_NOTES_07 (NOTE_ID, OP_ID, NOTE) VALUES (:note_id, :op_id, :note);
$$

