-- Generated per Snowflake E-Signature patterns @31 @36
CREATE OR REPLACE PROCEDURE DOCGEN.SET_TENANT_USAGE_CAPS_07(cap_id STRING, tenant_id STRING, caps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TENANT_USAGE_CAPS_07 t USING (SELECT :cap_id AS cid, :tenant_id AS tid, :caps AS c) s ON t.CAP_ID = s.cid WHEN MATCHED THEN UPDATE SET TENANT_ID = s.tid, CAPS = s.c, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CAP_ID, TENANT_ID, CAPS) VALUES (s.cid, s.tid, s.c);
$$

