CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_ONCALL_ROSTER_07(roster_id STRING, name STRING, members ARRAY, active BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ONCALL_ROSTERS_07 t USING (SELECT :roster_id AS rid, :name AS nm, :members AS m, :active AS a) s ON t.ROSTER_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, MEMBERS = s.m, ACTIVE = s.a WHEN NOT MATCHED THEN INSERT (ROSTER_ID, NAME, MEMBERS, ACTIVE) VALUES (s.rid, s.nm, s.m, s.a);
$$

