CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INCIDENT_REPORT_07(incident_id STRING, title STRING, description STRING, severity STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_REPORTS_07 (INCIDENT_ID, TITLE, DESCRIPTION, SEVERITY) VALUES (:incident_id, :title, :description, :severity);
$$

