CREATE OR REPLACE PROCEDURE DOCGEN.ADD_INCIDENT_COMMENT_07(comment_id STRING, incident_id STRING, author STRING, body CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_COMMENTS_07 (COMMENT_ID, INCIDENT_ID, AUTHOR, BODY) VALUES (:comment_id, :incident_id, :author, :body);
$$

