CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ESIGN_AUDIT_INDEX_08(index_id STRING, bundle_id STRING, audit_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ESIGN_AUDIT_INDEX_08 (INDEX_ID, BUNDLE_ID, AUDIT_REF) VALUES (:index_id, :bundle_id, :audit_ref);
$$

