CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POSTMORTEM_TEMPLATE_07(template_id STRING, name STRING, template CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POSTMORTEM_TEMPLATES_07 (TEMPLATE_ID, NAME, TEMPLATE) VALUES (:template_id, :name, :template);
$$

