CREATE OR REPLACE PROCEDURE DOCGEN.STORE_DEVICE_FINGERPRINT_08(fp_id STRING, signer_id STRING, hash STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEVICE_FINGERPRINTS_08 (FP_ID, SIGNER_ID, HASH, META) VALUES (:fp_id, :signer_id, :hash, :meta);
$$

