CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_POSTMORTEM_RUN_07(run_id STRING, incident_id STRING, template_id STRING, output VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POSTMORTEM_RUNS_07 (RUN_ID, INCIDENT_ID, TEMPLATE_ID, OUTPUT) VALUES (:run_id, :incident_id, :template_id, :output);
$$

