CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_TEMPLATE_08(template_id STRING, signer_id STRING, template_hash STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_TEMPLATES_08 (TEMPLATE_ID, SIGNER_ID, TEMPLATE_HASH, META) VALUES (:template_id, :signer_id, :template_hash, :meta);
$$

