CREATE OR REPLACE PROCEDURE DOCGEN.TAG_DOCUMENT_07(tag_id STRING, document_id STRING, tag STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_TAGS_07 (TAG_ID, DOCUMENT_ID, TAG) VALUES (:tag_id, :document_id, :tag);
$$

