CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH_08(match_id STRING, template_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCHES_08 (MATCH_ID, TEMPLATE_ID, SCORE) VALUES (:match_id, :template_id, :score);
$$

