CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TAG_ANALYTIC_07(analytic_id STRING, tag STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TAG_ANALYTICS_07 (ANALYTIC_ID, TAG, METRICS) VALUES (:analytic_id, :tag, :metrics);
$$

