CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_DEVICE_TRUST_SCORE_08(score_id STRING, fp_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_TRUST_SCORES_08 t USING (SELECT :score_id AS sid, :fp_id AS fid, :score AS sc) s ON t.SCORE_ID = s.sid WHEN MATCHED THEN UPDATE SET FP_ID = s.fid, SCORE = s.sc, COMPUTED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SCORE_ID, FP_ID, SCORE) VALUES (s.sid, s.fid, s.sc);
$$

