CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SEARCH_INDEX_07(index_id STRING, name STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_INDEX_META_07 (INDEX_ID, NAME, CONFIG, STATUS) VALUES (:index_id, :name, :config, 'CREATED');
$$

