CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RISK_ASSESSMENT_08(risk_id STRING, bundle_id STRING, risk_score FLOAT, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_ASSESSMENTS_08 (RISK_ID, BUNDLE_ID, RISK_SCORE, DETAILS) VALUES (:risk_id, :bundle_id, :risk_score, :details);
$$

