CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SEARCH_INDEX_STATS_07(stats_id STRING, index_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SEARCH_INDEX_STATS_07 (STATS_ID, INDEX_ID, METRICS) VALUES (:stats_id, :index_id, :metrics);
$$

