CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_AML_CHECK_08(aml_id STRING, signer_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AML_CHECKS_08 (AML_ID, SIGNER_ID, RESULT) VALUES (:aml_id, :signer_id, :result);
$$

