CREATE OR REPLACE PROCEDURE DOCGEN.REQUEST_INDEX_REBUILD_07(job_id STRING, index_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_REBUILD_JOBS_07 (JOB_ID, INDEX_ID, STATUS) VALUES (:job_id, :index_id, 'REQUESTED');
$$

