CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KYC_VERIFICATION_08(verif_id STRING, doc_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KYC_VERIFICATIONS_08 (VERIF_ID, DOC_ID, RESULT) VALUES (:verif_id, :doc_id, :result);
$$

