CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CONTENT_SIGNOFF_08(signoff_id STRING, document_id STRING, signed_by STRING, notes STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONTENT_SIGN_OFFS_08 (SIGNOFF_ID, DOCUMENT_ID, SIGNED_BY, NOTES) VALUES (:signoff_id, :document_id, :signed_by, :notes);
$$

