CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SAMPLING_CONFIG_07(config_id STRING, index_id STRING, strategy VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SAMPLING_CONFIGS_07 t USING (SELECT :config_id AS cid, :index_id AS iid, :strategy AS s) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET INDEX_ID = s.iid, STRATEGY = s.s, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, INDEX_ID, STRATEGY) VALUES (s.cid, s.iid, s.s);
$$

