CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_PREVIEW_LOG_08(log_id STRING, template_id STRING, user_ref STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_PREVIEW_LOGS_08 (LOG_ID, TEMPLATE_ID, USER_REF, ACTION) VALUES (:log_id, :template_id, :user_ref, :action);
$$

