CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DATA_DRIFT_ALERT_07(alert_id STRING, index_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_DRIFT_ALERTS_07 (ALERT_ID, INDEX_ID, METRICS) VALUES (:alert_id, :index_id, :metrics);
$$

