CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_DRIFT_EVENT_07(event_id STRING, model_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_DRIFT_EVENTS_07 (EVENT_ID, MODEL_ID, METRICS) VALUES (:event_id, :model_id, :metrics);
$$

