CREATE OR REPLACE PROCEDURE DOCGEN.LOCK_TEMPLATE_08(lock_id STRING, template_id STRING, locked_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_LOCKS_08 (LOCK_ID, TEMPLATE_ID, LOCKED_BY) VALUES (:lock_id, :template_id, :locked_by);
$$

