CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_MODEL_VERSION_07(ver_id STRING, model_id STRING, version INT, artifact VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_REGISTRY_VERSIONS_07 (VER_ID, MODEL_ID, VERSION, ARTIFACT) VALUES (:ver_id, :model_id, :version, :artifact);
$$

