CREATE OR REPLACE PROCEDURE DOCGEN.RELEASE_TEMPLATE_LOCK_08(release_id STRING, lock_id STRING, released_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_LOCK_RELEASES_08 (RELEASE_ID, LOCK_ID, RELEASED_BY) VALUES (:release_id, :lock_id, :released_by);
$$

