CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MODEL_COST_ESTIMATE_07(est_id STRING, model_id STRING, estimate VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_COST_ESTIMATES_07 (EST_ID, MODEL_ID, ESTIMATE) VALUES (:est_id, :model_id, :estimate);
$$

