CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_USAGE_COST_07(cost_id STRING, account_id STRING, period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ, breakdown VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_COSTING_07 (COST_ID, ACCOUNT_ID, PERIOD_START, PERIOD_END, COST_BREAKDOWN) VALUES (:cost_id, :account_id, :period_start, :period_end, :breakdown);
$$

