CREATE OR REPLACE PROCEDURE DOCGEN.SET_ORG_QUOTA_07(quota_id STRING, org_id STRING, quotas VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ORG_QUOTAS_07 t USING (SELECT :quota_id AS qid, :org_id AS oid, :quotas AS q) s ON t.QUOTA_ID = s.qid WHEN MATCHED THEN UPDATE SET ORG_ID = s.oid, QUOTAS = s.q WHEN NOT MATCHED THEN INSERT (QUOTA_ID, ORG_ID, QUOTAS) VALUES (s.qid, s.oid, s.q);
$$

