CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_TEMPLATE_VIEW_COUNT_08(stat_id STRING, template_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_PREVIEW_STATS_08 t USING (SELECT :stat_id AS sid, :template_id AS tid) s ON t.STAT_ID = s.sid WHEN MATCHED THEN UPDATE SET VIEW_COUNT = COALESCE(VIEW_COUNT,0)+1, LAST_VIEWED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (STAT_ID, TEMPLATE_ID, VIEW_COUNT, LAST_VIEWED_AT) VALUES (s.sid, s.tid, 1, CURRENT_TIMESTAMP());
$$

