CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_QUOTA_BREACH_07(breach_id STRING, org_id STRING, quota_key STRING, usage VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_BREACHES_07 (BREACH_ID, ORG_ID, QUOTA_KEY, USAGE) VALUES (:breach_id, :org_id, :quota_key, :usage);
$$

