CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_QUALITY_SCORE_08(score_id STRING, template_id STRING, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_QUALITY_SCORES_08 (SCORE_ID, TEMPLATE_ID, SCORE) VALUES (:score_id, :template_id, :score);
$$

