CREATE OR REPLACE PROCEDURE DOCGEN.TRANSITION_DOCUMENT_STATE_08(lifecycle_id STRING, document_id STRING, state STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_LIFECYCLE_08 (LIFECYCLE_ID, DOCUMENT_ID, STATE) VALUES (:lifecycle_id, :document_id, :state);
$$

