CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_MAINTENANCE_WINDOW_07(window_id STRING, name STRING, cron_expr STRING, duration_mins INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS_07 (WINDOW_ID, NAME, CRON_EXPR, DURATION_MINS) VALUES (:window_id, :name, :cron_expr, :duration_mins);
$$

