CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DOCUMENT_ANNOTATION_08(annot_id STRING, document_id STRING, annotator STRING, annotation CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_ANNOTATIONS_08 (ANNOT_ID, DOCUMENT_ID, ANNOTATOR, ANNOTATION) VALUES (:annot_id, :document_id, :annotator, :annotation);
$$

