CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_MAINTENANCE_EVENT_07(event_id STRING, window_id STRING, started_at TIMESTAMP_LTZ, ended_at TIMESTAMP_LTZ, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_EVENTS_07 (EVENT_ID, WINDOW_ID, STARTED_AT, ENDED_AT, STATUS) VALUES (:event_id, :window_id, :started_at, :ended_at, :status);
$$

