CREATE OR REPLACE PROCEDURE DOCGEN.PUBLISH_RELEASE_NOTE_07(note_id STRING, version STRING, notes CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RELEASE_NOTES_07 (NOTE_ID, VERSION, NOTES) VALUES (:note_id, :version, :notes);
$$

