CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ROLLOUT_METRIC_07(metric_id STRING, rollout_id STRING, key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ROLLOUT_METRICS_07 (METRIC_ID, ROLLOUT_ID, KEY, VALUE) VALUES (:metric_id, :rollout_id, :key, :value);
$$

