CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_REVISION_REVIEW_LOG_08(log_id STRING, rev_id STRING, reviewer STRING, comment CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVISION_REVIEW_LOGS_08 (LOG_ID, REV_ID, REVIEWER, COMMENT) VALUES (:log_id, :rev_id, :reviewer, :comment);
$$

