CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_AUDIT_SUMMARY_07(summary_id STRING, scope VARIANT, summary VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_SUMMARIES_07 (SUMMARY_ID, SCOPE, SUMMARY) VALUES (:summary_id, :scope, :summary);
$$

