CREATE OR REPLACE PROCEDURE DOCGEN.ADD_TEMPLATE_DEP_EDGE_08(edge_id STRING, parent_template STRING, child_template STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_DEP_GRAPH_08 (EDGE_ID, PARENT_TEMPLATE, CHILD_TEMPLATE) VALUES (:edge_id, :parent_template, :child_template);
$$

