CREATE OR REPLACE PROCEDURE DOCGEN.AGGREGATE_TEMPLATE_USAGE_08(stat_id STRING, template_id STRING, usage_count INT, window_start TIMESTAMP_LTZ, window_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_STATS_08 (STAT_ID, TEMPLATE_ID, USAGE_COUNT, WINDOW_START, WINDOW_END) VALUES (:stat_id, :template_id, :usage_count, :window_start, :window_end);
$$

