CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_TEMPLATE_RECOMMENDATION_08(rec_id STRING, template_id STRING, recommended_for VARIANT, score FLOAT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_RECOMMENDATIONS_08 (REC_ID, TEMPLATE_ID, RECOMMENDED_FOR, SCORE) VALUES (:rec_id, :template_id, :recommended_for, :score);
$$

