CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_AUDIT_CONFIG_ENTRY_08(entry_id STRING, config_key STRING, config_val VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_CONFIG_ENTRIES_08 (ENTRY_ID, CONFIG_KEY, CONFIG_VAL) VALUES (:entry_id, :config_key, :config_val);
$$

