CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_JOB_CHECKPOINT_08(checkpoint_id STRING, job_id STRING, checkpoint_data VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.JOB_CHECKPOINTS_08 t USING (SELECT :checkpoint_id AS cid, :job_id AS jid, :checkpoint_data AS cd) s ON t.CHECKPOINT_ID = s.cid WHEN MATCHED THEN UPDATE SET JOB_ID = s.jid, CHECKPOINT_DATA = s.cd, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CHECKPOINT_ID, JOB_ID, CHECKPOINT_DATA) VALUES (s.cid, s.jid, s.cd);
$$

