CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_DEAD_LETTER_08(dlq_id STRING, origin STRING, payload VARIANT, error TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEAD_LETTER_08 (DLQ_ID, ORIGIN, PAYLOAD, ERROR) VALUES (:dlq_id, :origin, :payload, :error);
$$

