CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RETRY_POLICY_08(policy_id STRING, name STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RETRY_POLICIES_08 t USING (SELECT :policy_id AS pid, :name AS nm, :config AS cfg, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, CONFIG = s.cfg, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, CONFIG, ENABLED) VALUES (s.pid, s.nm, s.cfg, s.en);
$$

