CREATE OR REPLACE PROCEDURE DOCGEN.SET_EVENT_BACKOFF_08(backoff_id STRING, event_ref STRING, next_try TIMESTAMP_LTZ, attempts INT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.EVENT_BACKOFFS_08 t USING (SELECT :backoff_id AS bid, :event_ref AS er, :next_try AS nt, :attempts AS at) s ON t.BACKOFF_ID = s.bid WHEN MATCHED THEN UPDATE SET EVENT_REF = s.er, NEXT_TRY = s.nt, ATTEMPTS = s.at WHEN NOT MATCHED THEN INSERT (BACKOFF_ID, EVENT_REF, NEXT_TRY, ATTEMPTS) VALUES (s.bid, s.er, s.nt, s.at);
$$

