CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_BATCH_JOB_08(job_id STRING, name STRING, payload VARIANT, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BATCH_JOBS_08 (JOB_ID, NAME, PAYLOAD, STATUS, SCHEDULED_AT) VALUES (:job_id, :name, :payload, 'PENDING', :scheduled_at);
$$

