CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ADMIN_ACTION_08(queue_id STRING, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTIONS_QUEUE_08 (QUEUE_ID, ACTION) VALUES (:queue_id, :action);
$$

