CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_OPERATOR_TASK_08(task_id STRING, name STRING, assigned_to STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_TASKS_08 (TASK_ID, NAME, ASSIGNED_TO, STATUS, META) VALUES (:task_id, :name, :assigned_to, 'OPEN', :meta);
$$

