CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_TASK_UPDATE_08(update_id STRING, task_id STRING, update VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_TASK_UPDATES_08 (UPDATE_ID, TASK_ID, UPDATE) VALUES (:update_id, :task_id, :update);
$$

