CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_LOGIN_ATTEMPT_08(attempt_id STRING, admin_id STRING, success BOOLEAN, ip STRING, user_agent STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_LOGIN_ATTEMPTS_08 (ATTEMPT_ID, ADMIN_ID, SUCCESS, IP, USER_AGENT) VALUES (:attempt_id, :admin_id, :success, :ip, :user_agent);
$$

