CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_LOCKOUT_08(lockout_id STRING, admin_id STRING, reason STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_LOCKOUTS_08 (LOCKOUT_ID, ADMIN_ID, REASON, EXPIRES_AT) VALUES (:lockout_id, :admin_id, :reason, :expires_at);
$$

