CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_SESSION_ACTIVITY_08(act_id STRING, session_id STRING, action STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_SESSION_ACTIVITIES_08 (ACT_ID, SESSION_ID, ACTION, PAYLOAD) VALUES (:act_id, :session_id, :action, :payload);
$$

