CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_PRIVACY_REQUEST_08(req_id STRING, account_id STRING, request_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_REQUESTS_08 (REQ_ID, ACCOUNT_ID, REQUEST_TYPE, STATUS) VALUES (:req_id, :account_id, :request_type, 'PENDING');
$$

