CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PSEUDONYMIZATION_JOB_08(job_id STRING, target_table STRING, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PSEUDONYMIZATION_JOBS_08 (JOB_ID, TARGET_TABLE, STATUS, SCHEDULED_AT) VALUES (:job_id, :target_table, 'QUEUED', :scheduled_at);
$$

