CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_DEPENDENCY_MANIFEST_08(manifest_id STRING, name STRING, content VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEPENDENCY_MANIFESTS_08 (MANIFEST_ID, NAME, CONTENT) VALUES (:manifest_id, :name, :content);
$$

