CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DEPLOYMENT_08(deploy_id STRING, component STRING, version STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DEPLOYMENT_RECORDS_08 (DEPLOY_ID, COMPONENT, VERSION, STATUS) VALUES (:deploy_id, :component, :version, :status);
$$

- User:  

- Anara: FILENAME: sql/ddl/4474_signature_access_policies_09.sql
-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_POLICIES_09 ( POLICY_ID STRING PRIMARY KEY, NAME STRING, RULES VARIANT, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

