CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_CHECKSUM_09(checksum_id STRING, document_id STRING, checksum STRING, algorithm STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_CHECKSUMS_09 (CHECKSUM_ID, DOCUMENT_ID, CHECKSUM, ALGORITHM)
VALUES (:checksum_id, :document_id, :checksum, :algorithm);
$$

