CREATE OR REPLACE PROCEDURE DOCGEN.STORE_VERIFICATION_EVIDENCE_09(evidence_id STRING, bundle_id STRING, verifier STRING, result STRING, detail VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERIFICATION_EVIDENCES_09 (EVIDENCE_ID, BUNDLE_ID, VERIFIER, RESULT, DETAIL)
VALUES (:evidence_id, :bundle_id, :verifier, :result, :detail);
$$

