CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ANCHOR_RECORD_09(anchor_id STRING, bundle_id STRING, anchor_type STRING, anchor_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHOR_RECORDS_09 (ANCHOR_ID, BUNDLE_ID, ANCHOR_TYPE, ANCHOR_REF)
VALUES (:anchor_id, :bundle_id, :anchor_type, :anchor_ref);
$$

