CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BLOCKCHAIN_ANCHOR_09(tx_id STRING, anchor_id STRING, blockchain STRING, tx_ref STRING, confirmed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BLOCKCHAIN_ANCHORS_09 (TX_ID, ANCHOR_ID, BLOCKCHAIN, TX_REF, CONFIRMED_AT)
VALUES (:tx_id, :anchor_id, :blockchain, :tx_ref, :confirmed_at);
$$

