CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_ACCESS_CONTROL_09(control_id STRING, resource_ref STRING, principal STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_CONTROLS_09 (CONTROL_ID, RESOURCE_REF, PRINCIPAL, PERMISSIONS)
VALUES (:control_id, :resource_ref, :principal, :permissions);
$$

