-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PURGE_JOB_09(job_id STRING, policy_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_JOBS_09 (JOB_ID, POLICY_ID, STATUS, STARTED_AT) VALUES (:job_id, :policy_id, 'STARTED', CURRENT_TIMESTAMP());
$$

