CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_KEY_ROTATION_JOB_09(job_id STRING, key_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATION_JOBS_09 (JOB_ID, KEY_REF, STATUS)
VALUES (:job_id, :key_ref, 'QUEUED');
$$

