-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_EVIDENCE_ACCESS_REQUEST_09(req_id STRING, requestor STRING, bundle_id STRING, purpose STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_ACCESS_REQUESTS_09 (REQ_ID, REQUESTOR, BUNDLE_ID, PURPOSE, STATUS) VALUES (:req_id, :requestor, :bundle_id, :purpose, 'PENDING');
$$

