-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_COMPLIANCE_REPORT_09(report_id STRING, name STRING, scope VARIANT, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_REPORTS_09 (REPORT_ID, NAME, SCOPE, RESULT) VALUES (:report_id, :name, :scope, :result);
$$

