CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CERT_REVOCATION_09(revoc_id STRING, cert_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CERT_REVOCATIONS_09 (REVOC_ID, CERT_ID, REASON)
VALUES (:revoc_id, :cert_id, :reason);
$$

