CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_OCSP_CACHE_09(ocsp_id STRING, cert_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OCSP_CACHE_09 t USING (SELECT :ocsp_id AS oid, :cert_id AS cid, :status AS st) s ON t.OCSP_ID = s.oid WHEN MATCHED THEN UPDATE SET CERT_ID = s.cid, STATUS = s.st, FETCHED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (OCSP_ID, CERT_ID, STATUS) VALUES (s.oid, s.cid, s.st);
$$

