CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CRL_ENTRY_09(crl_id STRING, cert_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CRL_INDEX_09 (CRL_ID, CERT_ID, STATUS) VALUES (:crl_id, :cert_id, :status);
$$

