CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_POLICY_ENFORCEMENT_09(enforce_id STRING, policy_id STRING, target_ref STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POLICY_ENFORCEMENTS_09 (ENFORCE_ID, POLICY_ID, TARGET_REF, RESULT) VALUES (:enforce_id, :policy_id, :target_ref, :result);
$$

