-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ARCHIVE_JOB_09(job_id STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_JOBS_09 (JOB_ID, SCOPE, STATUS) VALUES (:job_id, :scope, 'QUEUED');
$$

