CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_COMPLIANCE_REPORT_09(report_id STRING, scope VARIANT, results VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_REPORTS_09 (REPORT_ID, SCOPE, RESULTS) VALUES (:report_id, :scope, :results);
$$

