CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_AUDIT_EXPORT_JOB_09(job_id STRING, scope VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_EXPORT_JOBS_09 (JOB_ID, SCOPE, STATUS) VALUES (:job_id, :scope, 'QUEUED');
$$

