-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RECOVERY_PLAN_09(plan_id STRING, name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RECOVERY_PLANS_09 t USING (SELECT :plan_id AS pid, :name AS nm, :steps AS s) s ON t.PLAN_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, STEPS = s.s, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PLAN_ID, NAME, STEPS) VALUES (s.pid, s.nm, s.s);
$$

