CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ADMIN_NOTIFICATION_09(notif_id STRING, title STRING, body VARIANT, level STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_NOTIFICATIONS_09 (NOTIF_ID, TITLE, BODY, LEVEL) VALUES (:notif_id, :title, :body, :level);
$$

