CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_ALERT_ROUTE_09(route_id STRING, name STRING, channels ARRAY, criteria VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ALERT_ROUTES_09 (ROUTE_ID, NAME, CHANNELS, CRITERIA) VALUES (:route_id, :name, :channels, :criteria);
$$

