-- Generated per Snowflake E-Signature patterns. @31
CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_CREDENTIAL_ROTATION_09(rot_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CREDENTIAL_ROTATIONS_09 (ROT_ID, TARGET_REF, STATUS) VALUES (:rot_id, :target_ref, 'QUEUED');
$$

