CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ADMIN_ACTION_TEMPLATE_09(template_id STRING, name STRING, action VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACTION_TEMPLATES_09 (TEMPLATE_ID, NAME, ACTION) VALUES (:template_id, :name, :action);
$$

