CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_DASHBOARD_METRIC_09(metric_id STRING, view_id STRING, metric_def VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_DASHBOARD_METRICS_09 (METRIC_ID, VIEW_ID, METRIC_DEF) VALUES (:metric_id, :view_id, :metric_def);
$$

