CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_HEARTBEAT_09(hb_id STRING, component STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_HEARTBEAT_09 (HB_ID, COMPONENT, STATUS) VALUES (:hb_id, :component, :status);
$$

