CREATE OR REPLACE PROCEDURE DOCGEN.INSERT_VERIFICATION_METADATA_10(meta_id STRING, bundle_id STRING, provider STRING, method STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.VERIFICATION_METADATA_10 (META_ID, BUNDLE_ID, PROVIDER, METHOD, DETAILS) VALUES (:meta_id, :bundle_id, :provider, :method, :details);
$$

