CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNATURE_PROVIDER_CONFIG_10(config_id STRING, provider STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_PROVIDER_CONFIGS_10 t USING (SELECT :config_id AS cid, :provider AS p, :config AS c, :enabled AS e) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET PROVIDER = s.p, CONFIG = s.c, ENABLED = s.e, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, PROVIDER, CONFIG, ENABLED) VALUES (s.cid, s.p, s.c, s.e);
$$

