CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PENDING_ACTION_10(action_id STRING, bundle_id STRING, action_type STRING, payload VARIANT, due_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PENDING_ACTIONS_10 (ACTION_ID, BUNDLE_ID, ACTION_TYPE, PAYLOAD, DUE_AT) VALUES (:action_id, :bundle_id, :action_type, :payload, :due_at);
$$

