CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EMAIL_DELIVERY_10(queue_id STRING, recipient STRING, subject STRING, body VARIANT, channel STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMAIL_DELIVERY_QUEUE_10 (QUEUE_ID, RECIPIENT, SUBJECT, BODY, CHANNEL) VALUES (:queue_id, :recipient, :subject, :body, :channel);
$$

