CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_SMS_DELIVERY_10(queue_id STRING, msisdn STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SMS_DELIVERY_QUEUE_10 (QUEUE_ID, MSISDN, MESSAGE) VALUES (:queue_id, :msisdn, :message);
$$

