CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_PUSH_NOTIFICATION_10(notif_id STRING, target_ref STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PUSH_NOTIFICATIONS_10 (NOTIF_ID, TARGET_REF, PAYLOAD) VALUES (:notif_id, :target_ref, :payload);
$$

