CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_WEBHOOK_INBOUND_10(webhook_id STRING, source STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOKS_INBOUND_10 (WEBHOOK_ID, SOURCE, PAYLOAD) VALUES (:webhook_id, :source, :payload);
$$

