CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_WEBHOOK_HANDLER_10(handler_id STRING, source STRING, endpoint STRING, method STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.WEBHOOK_HANDLERS_10 (HANDLER_ID, SOURCE, ENDPOINT, METHOD, CONFIG) VALUES (:handler_id, :source, :endpoint, :method, :config);
$$

