CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_CALLBACK_ENDPOINT_10(endpoint_id STRING, name STRING, url STRING, secret_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CALLBACK_ENDPOINTS_10 (ENDPOINT_ID, NAME, URL, SECRET_REF) VALUES (:endpoint_id, :name, :url, :secret_ref);
$$

