CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RATE_LIMIT_RULE_10(rule_id STRING, name STRING, scope VARIANT, limit_config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RATE_LIMIT_RULES_10 t USING (SELECT :rule_id AS rid, :name AS nm, :scope AS sc, :limit_config AS lc, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, SCOPE = s.sc, LIMIT_CONFIG = s.lc, ENABLED = s.en, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, SCOPE, LIMIT_CONFIG, ENABLED) VALUES (s.rid, s.nm, s.sc, s.lc, s.en);
$$

