CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_THROTTLE_EVENT_10(event_id STRING, rule_id STRING, key STRING, action STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THROTTLE_EVENTS_10 (EVENT_ID, RULE_ID, KEY, ACTION) VALUES (:event_id, :rule_id, :key, :action);
$$

