CREATE OR REPLACE PROCEDURE DOCGEN.STORE_TENANT_SECRET_10(secret_id STRING, tenant_id STRING, secret_ref STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TENANT_SECRETS_10 (SECRET_ID, TENANT_ID, SECRET_REF, META) VALUES (:secret_id, :tenant_id, :secret_ref, :meta);
$$

