CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_ACCOUNT_ENTITLEMENT_10(ent_id STRING, account_id STRING, feature STRING, enabled BOOLEAN, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_ENTITLEMENTS_10 (ENT_ID, ACCOUNT_ID, FEATURE, ENABLED, META) VALUES (:ent_id, :account_id, :feature, :enabled, :meta);
$$

