CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OFFLINE_VERIFICATION_10(verif_id STRING, bundle_id STRING, method STRING, result STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OFFLINE_VERIFICATIONS_10 (VERIF_ID, BUNDLE_ID, METHOD, RESULT, DETAILS) VALUES (:verif_id, :bundle_id, :method, :result, :details);
$$

