CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_VALIDATION_RULE_10(rule_id STRING, name STRING, target STRING, expression STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.VALIDATION_RULES_10 t USING (SELECT :rule_id AS rid, :name AS nm, :target AS t, :expression AS e, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, TARGET = s.t, EXPRESSION = s.e, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, TARGET, EXPRESSION, ENABLED) VALUES (s.rid, s.nm, s.t, s.e, s.en);
$$

