CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ALERT_RULE_10(rule_id STRING, name STRING, condition VARIANT, actions ARRAY, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ALERT_RULES_10 t USING (SELECT :rule_id AS rid, :name AS nm, :condition AS c, :actions AS a, :enabled AS e) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, CONDITION = s.c, ACTIONS = s.a, ENABLED = s.e WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, CONDITION, ACTIONS, ENABLED) VALUES (s.rid, s.nm, s.c, s.a, s.e);
$$

