CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ALERT_EVENT_10(alert_id STRING, rule_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ALERT_EVENTS_10 (ALERT_ID, RULE_ID, PAYLOAD) VALUES (:alert_id, :rule_id, :payload);
$$

