CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INCIDENT_UPDATE_10(update_id STRING, incident_id STRING, update_text STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_UPDATES_10 (UPDATE_ID, INCIDENT_ID, UPDATE_TEXT) VALUES (:update_id, :incident_id, :update_text);
$$

