CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POSTMORTEM_10(pm_id STRING, incident_id STRING, summary CLOB, actions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.POSTMORTEMS_10 (PM_ID, INCIDENT_ID, SUMMARY, ACTIONS) VALUES (:pm_id, :incident_id, :summary, :actions);
$$

