CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_SERVICE_HEALTH_10(service_id STRING, name STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SERVICE_HEALTH_10 t USING (SELECT :service_id AS sid, :name AS nm, :status AS st) s ON t.SERVICE_ID = s.sid WHEN MATCHED THEN UPDATE SET NAME = s.nm, STATUS = s.st, LAST_CHECK = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SERVICE_ID, NAME, STATUS) VALUES (s.sid, s.nm, s.st);
$$

