CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_MAINTENANCE_WINDOW_10(window_id STRING, name STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS_10 (WINDOW_ID, NAME, START_AT, END_AT) VALUES (:window_id, :name, :start_at, :end_at);
$$

