CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_AUDIT_RUN_10(run_id STRING, audit_id STRING, status STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_RUN_HISTORY_10 (RUN_ID, AUDIT_ID, STATUS, RESULT) VALUES (:run_id, :audit_id, :status, :result);
$$

