CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SESSION_AUDIT_11(audit_id STRING, session_id STRING, event_type STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_AUDIT_11 (AUDIT_ID, SESSION_ID, EVENT_TYPE, PAYLOAD) VALUES (:audit_id, :session_id, :event_type, :payload);
$$

