CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_HASH_11(bio_id STRING, signer_id STRING, type STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRICS_INDEX_11 (BIOMETRIC_ID, SIGNER_ID, TYPE, HASH) VALUES (:bio_id, :signer_id, :type, :hash);
$$

