CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RISK_SCORE_11(risk_id STRING, subject_id STRING, scope STRING, score NUMBER, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.RISK_SCORES_11 t USING (SELECT :risk_id AS rid, :subject_id AS sid, :scope AS sc, :score AS scv, :metadata AS md) s
ON t.RISK_ID = s.rid
WHEN MATCHED THEN UPDATE SET SUBJECT_ID = s.sid, SCOPE = s.sc, SCORE = s.scv, METADATA = s.md, SCORED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (RISK_ID, SUBJECT_ID, SCOPE, SCORE, METADATA) VALUES (s.rid, s.sid, s.sc, s.scv, s.md);
$$

