CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_FRAUD_ALERT_11(alert_id STRING, signer_id STRING, bundle_id STRING, alert_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_ALERTS_11 (ALERT_ID, SIGNER_ID, BUNDLE_ID, ALERT_TYPE, DETAILS) VALUES (:alert_id, :signer_id, :bundle_id, :alert_type, :details);
$$

