CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DEVICE_REPUTATION_11(repute_id STRING, device_hash STRING, score NUMBER, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_REPUTATION_11 t USING (SELECT :repute_id AS rid, :device_hash AS dh, :score AS sc, :details AS dt) s ON t.REPUTE_ID = s.rid WHEN MATCHED THEN UPDATE SET DEVICE_HASH = s.dh, SCORE = s.sc, DETAILS = s.dt, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (REPUTE_ID, DEVICE_HASH, SCORE, DETAILS) VALUES (s.rid, s.dh, s.sc, s.dt);
$$

