CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_GEO_RESTRICTION_11(restr_id STRING, name STRING, countries ARRAY, action STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.GEO_RESTRICTIONS_11 t USING (SELECT :restr_id AS rid, :name AS nm, :countries AS c, :action AS a, :enabled AS e) s ON t.RESTR_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, COUNTRIES = s.c, ACTION = s.a, ENABLED = s.e WHEN NOT MATCHED THEN INSERT (RESTR_ID, NAME, COUNTRIES, ACTION, ENABLED) VALUES (s.rid, s.nm, s.c, s.a, s.e);
$$

