CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_GEO_EVENT_11(geo_event_id STRING, bundle_id STRING, country STRING, action STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.GEO_EVENTS_11 (GEO_EVENT_ID, BUNDLE_ID, COUNTRY, ACTION, DETAILS) VALUES (:geo_event_id, :bundle_id, :country, :action, :details);
$$

