CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_REDACTION_JOB_11(job_id STRING, bundle_id STRING, fields ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REDACTION_JOBS_11 (JOB_ID, BUNDLE_ID, FIELDS, STATUS) VALUES (:job_id, :bundle_id, :fields, 'QUEUED');
$$

