CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_MIGRATION_JOB_11(job_id STRING, name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MIGRATION_JOBS_11 (JOB_ID, NAME, PAYLOAD, STATUS) VALUES (:job_id, :name, :payload, 'QUEUED');
$$

