CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_SCHEMA_CHANGE_REQUEST_11(request_id STRING, requestor STRING, request VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SCHEMA_CHANGE_REQUESTS_11 (REQUEST_ID, REQUESTOR, REQUEST, STATUS) VALUES (:request_id, :requestor, :request, 'PENDING');
$$

