CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_APPROVAL_WORKFLOW_11(wf_id STRING, name STRING, steps VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_WORKFLOWS_11 (WF_ID, NAME, STEPS) VALUES (:wf_id, :name, :steps);
$$

