CREATE OR REPLACE PROCEDURE DOCGEN.START_APPROVAL_INSTANCE_11(instance_id STRING, wf_id STRING, target_ref STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.APPROVAL_INSTANCES_11 (INSTANCE_ID, WF_ID, TARGET_REF, STATUS, META) VALUES (:instance_id, :wf_id, :target_ref, 'OPEN', :meta);
$$

