CREATE OR REPLACE PROCEDURE DOCGEN.INDEX_DOCUMENT_12(doc_index_id STRING, bundle_id STRING, document_text CLOB, metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_INDEX_12 (DOC_INDEX_ID, BUNDLE_ID, DOCUMENT_TEXT, METADATA) VALUES (:doc_index_id, :bundle_id, :document_text, :metadata);
$$

