CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_VECTOR_METADATA_12(vector_id STRING, bundle_id STRING, shard_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.VECTOR_METADATA_12 t USING (SELECT :vector_id AS vid, :bundle_id AS bid, :shard_id AS sid, :meta AS m) s ON t.VECTOR_ID = s.vid
WHEN MATCHED THEN UPDATE SET BUNDLE_ID = s.bid, SHARD_ID = s.sid, META = s.m
WHEN NOT MATCHED THEN INSERT (VECTOR_ID, BUNDLE_ID, SHARD_ID, META) VALUES (s.vid, s.bid, s.sid, s.m);
$$

