CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_INDEX_SHARD_11(shard_id STRING, shard_prefix STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOC_INDEX_SHARDS_11 (SHARD_ID, SHARD_PREFIX, STATUS) VALUES (:shard_id, :shard_prefix, :status);
$$

