CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SHARD_MANIFEST_12(shard_id STRING, s3_prefix STRING, vector_count NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SHARD_MANIFEST_12 (SHARD_ID, S3_PREFIX, VECTOR_COUNT) VALUES (:shard_id, :s3_prefix, :vector_count);
$$

