CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_FAISS_BUILD_JOB_12(job_id STRING, shard_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FAISS_BUILD_JOBS_12 (JOB_ID, SHARD_ID, STATUS, STARTED_AT) VALUES (:job_id, :shard_id, 'QUEUED', CURRENT_TIMESTAMP());
$$

