CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_EMBEDDING_FLUSH_JOB_11(job_id STRING, shard_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMBEDDING_FLUSH_JOBS_11 (JOB_ID, SHARD_ID, STATUS) VALUES (:job_id, :shard_id, 'QUEUED');
$$

