CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_SIMILARITY_REQUEST_12(req_id STRING, query_variant VARIANT, shard_pref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIMILARITY_REQUESTS_12 (REQ_ID, QUERY_VARIANT, SHARD_PREF, STATUS) VALUES (:req_id, :query_variant, :shard_pref, 'PENDING');
$$

