CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIMILARITY_CACHE_11(cache_key STRING, query VARIANT, results VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIMILARITY_CACHE_11 t USING (SELECT :cache_key AS ck, :query AS q, :results AS r) s ON t.CACHE_KEY = s.ck WHEN MATCHED THEN UPDATE SET QUERY = s.q, RESULTS = s.r, CACHED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CACHE_KEY, QUERY, RESULTS) VALUES (s.ck, s.q, s.r);
$$

