CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_QUERY_SERVICE_12(service_id STRING, host STRING, port NUMBER, health_var VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUERY_SERVICE_REGISTRY_12 (SERVICE_ID, HOST, PORT, HEALTH_VAR) VALUES (:service_id, :host, :port, :health_var);
$$

