CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_QUERY_HEALTH_12(check_id STRING, service_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.QUERY_HEALTH_12 t USING (SELECT :check_id AS cid, :service_id AS sid, :status AS st) s ON t.CHECK_ID = s.cid WHEN MATCHED THEN UPDATE SET SERVICE_ID = s.sid, STATUS = s.st, LAST_CHECK = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CHECK_ID, SERVICE_ID, STATUS) VALUES (s.cid, s.sid, s.st);
$$

