CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_USAGE_METRIC_11(metric_id STRING, template_id STRING, account_id STRING, usage_count NUMBER, window_start TIMESTAMP_LTZ, window_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_USAGE_METRICS_11 (METRIC_ID, TEMPLATE_ID, ACCOUNT_ID, USAGE_COUNT, WINDOW_START, WINDOW_END) VALUES (:metric_id, :template_id, :account_id, :usage_count, :window_start, :window_end);
$$

