CREATE OR REPLACE PROCEDURE DOCGEN.AGGREGATE_TEMPLATE_POPULARITY_11()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.TEMPLATE_POPULARITY_11 t USING (SELECT TEMPLATE_ID, SUM(USAGE_COUNT) AS total, MAX(WINDOW_END) AS last_used FROM DOCGEN.TEMPLATE_USAGE_METRICS_11 GROUP BY TEMPLATE_ID) s ON t.TEMPLATE_ID = s.TEMPLATE_ID WHEN MATCHED THEN UPDATE SET TOTAL_USES = s.total, LAST_USED_AT = s.last_used WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, TOTAL_USES, LAST_USED_AT) VALUES (s.TEMPLATE_ID, s.total, s.last_used);
$$

