CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_QUERY_RETRY_12(retry_id STRING, req_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.QUERY_RETRIES_12 t USING (SELECT :retry_id AS rid, :req_id AS rq) s ON t.RETRY_ID = s.rid WHEN MATCHED THEN UPDATE SET ATTEMPTS = COALESCE(ATTEMPTS,0)+1, LAST_ATTEMPT_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (RETRY_ID, REQ_ID, ATTEMPTS, LAST_ATTEMPT_AT) VALUES (s.rid, s.rq, 1, CURRENT_TIMESTAMP());
$$

