CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_TEMPLATE_RECOMMENDATIONS_11(reco_id STRING, account_id STRING, template_id STRING, score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_RECOMMENDATIONS_11 (RECO_ID, ACCOUNT_ID, TEMPLATE_ID, SCORE) VALUES (:reco_id, :account_id, :template_id, :score);
$$

