CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_CLAUSE_REFERENCE_11(clause_id STRING, inc NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.CLAUSE_LIBRARY_STATS_11 t USING (SELECT :clause_id AS cid, :inc AS inc) s ON t.CLAUSE_ID = s.cid WHEN MATCHED THEN UPDATE SET TOTAL_REFERENCES = COALESCE(TOTAL_REFERENCES,0)+s.inc, LAST_REFERENCED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CLAUSE_ID, TOTAL_REFERENCES, LAST_REFERENCED_AT) VALUES (s.cid, s.inc, CURRENT_TIMESTAMP());
$$

