CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DOCUMENT_SIMILARITY_SCORE_11(score_id STRING, doc_a STRING, doc_b STRING, score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DOCUMENT_SIMILARITY_SCORES_11 (SCORE_ID, DOC_A, DOC_B, SCORE) VALUES (:score_id, :doc_a, :doc_b, :score);
$$

