CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNER_BEHAVIOR_PROFILE_11(profile_id STRING, signer_id STRING, behavior_metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_BEHAVIOR_PROFILES_11 t USING (SELECT :profile_id AS pid, :signer_id AS sid, :behavior_metrics AS bm) s ON t.PROFILE_ID = s.pid WHEN MATCHED THEN UPDATE SET SIGNER_ID = s.sid, BEHAVIOR_METRICS = s.bm, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PROFILE_ID, SIGNER_ID, BEHAVIOR_METRICS) VALUES (s.pid, s.sid, s.bm);
$$

