CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_SIGNER_BEHAVIOR_ALERT_11(alert_id STRING, profile_id STRING, alert_type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_BEHAVIOR_ALERTS_11 (ALERT_ID, PROFILE_ID, ALERT_TYPE, DETAILS) VALUES (:alert_id, :profile_id, :alert_type, :details);
$$

