CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_MODEL_12(model_id STRING, name STRING, version STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_REGISTRY_12 (MODEL_ID, NAME, VERSION, META) VALUES (:model_id, :name, :version, :meta);
$$

