CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNER_RISK_CONFIG_11(config_id STRING, name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNER_RISK_CONFIGS_11 t USING (SELECT :config_id AS cid, :name AS nm, :rules AS r, :enabled AS e) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, ENABLED = s.e WHEN NOT MATCHED THEN INSERT (CONFIG_ID, NAME, RULES, ENABLED) VALUES (s.cid, s.nm, s.r, s.e);
$$

