CREATE OR REPLACE PROCEDURE DOCGEN.STORE_OTP_REQUEST_11(otp_id STRING, signer_id STRING, channel STRING, otp_hash STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTP_REQUESTS_11 (OTP_ID, SIGNER_ID, CHANNEL, OTP_HASH, EXPIRES_AT) VALUES (:otp_id, :signer_id, :channel, :otp_hash, :expires_at);
$$

