CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OTP_ATTEMPT_11(attempt_id STRING, otp_id STRING, signer_id STRING, success BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTP_ATTEMPTS_11 (ATTEMPT_ID, OTP_ID, SIGNER_ID, SUCCESS) VALUES (:attempt_id, :otp_id, :signer_id, :success);
$$

