CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KPI_RUN_11(run_id STRING, kpi_id STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KPI_RUNS_11 (RUN_ID, KPI_ID, RESULT) VALUES (:run_id, :kpi_id, :result);
$$
