CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_USAGE_SUMMARY_11(summary_id STRING, account_id STRING, period_start TIMESTAMP_LTZ, period_end TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USAGE_SUMMARY_11 (SUMMARY_ID, ACCOUNT_ID, PERIOD_START, PERIOD_END, METRICS) VALUES (:summary_id, :account_id, :period_start, :period_end, PARSE_JSON('{}'));
$$
