CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INVOICE_PREVIEW_AUDIT_11(audit_id STRING, account_id STRING, inv_preview VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_PREVIEW_AUDIT_11 (AUDIT_ID, ACCOUNT_ID, INV_PREVIEW) VALUES (:audit_id, :account_id, :inv_preview);
$$
