CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INVOICE_EXPORT_11(export_id STRING, invoice_id STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_EXPORTS_11 (EXPORT_ID, INVOICE_ID, LOCATION) VALUES (:export_id, :invoice_id, :location);
$$
