CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_RETENTION_POLICY_11(policy_id STRING, name STRING, target_table STRING, retention_days NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_POLICIES_11 (POLICY_ID, NAME, TARGET_TABLE, RETENTION_DAYS) VALUES (:policy_id, :name, :target_table, :retention_days);
$$
