CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PURGE_AUDIT_11(purge_id STRING, target_table STRING, rows_purged NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PURGE_AUDIT_11 (PURGE_ID, TARGET_TABLE, ROWS_PURGED) VALUES (:purge_id, :target_table, :rows_purged);
$$
