CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COMPLIANCE_EXPORT_11(export_id STRING, bundle_id STRING, format STRING, location STRING, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_EXPORTS_11 (EXPORT_ID, BUNDLE_ID, FORMAT, LOCATION, REQUESTED_BY) VALUES (:export_id, :bundle_id, :format, :location, :requested_by);
$$
