CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_LEGAL_HOLD_11(hold_id STRING, target_table STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.LEGAL_HOLDS_11 (HOLD_ID, TARGET_TABLE, REASON) VALUES (:hold_id, :target_table, :reason);
$$
