CREATE OR REPLACE PROCEDURE DOCGEN.GRANT_HOLD_EXEMPTION_11(exempt_id STRING, hold_id STRING, reason STRING, granted_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.HOLD_EXEMPTIONS_11 (EXEMPT_ID, HOLD_ID, REASON, GRANTED_BY) VALUES (:exempt_id, :hold_id, :reason, :granted_by);
$$
