CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_DATA_SUBJECT_REQUEST_11(req_id STRING, subject_ref STRING, request_type STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_SUBJECT_REQUESTS_11 (REQ_ID, SUBJECT_REF, REQUEST_TYPE, STATUS) VALUES (:req_id, :subject_ref, :request_type, 'OPEN');
$$
