CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_COMPLIANCE_CHECKLIST_11(checklist_id STRING, name STRING, items VARIANT, owner STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COMPLIANCE_CHECKLISTS_11 (CHECKLIST_ID, NAME, ITEMS, OWNER) VALUES (:checklist_id, :name, :items, :owner);
$$
