CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ACCESS_REVIEW_TASK_11(task_id STRING, target STRING, schedule STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_TASKS_11 (TASK_ID, TARGET, SCHEDULE) VALUES (:task_id, :target, :schedule);
$$
