CREATE OR REPLACE PROCEDURE DOCGEN.INGEST_THREAT_FEED_ITEM_11(feed_id STRING, source STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_FEED_11 (FEED_ID, SOURCE, DETAILS) VALUES (:feed_id, :source, :details);
$$
