CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_COURT_ORDER_11(order_id STRING, target STRING, order_doc CLOB, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.COURT_ORDERS_11 (ORDER_ID, TARGET, ORDER_DOC, STATUS) VALUES (:order_id, :target, :order_doc, :status);
$$
