CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DISPUTE_UPDATE_11(update_id STRING, case_id STRING, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DISPUTE_UPDATES_11 (UPDATE_ID, CASE_ID, NOTE) VALUES (:update_id, :case_id, :note);
$$
