CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_AML_CHECK_11(aml_id STRING, subject_ref STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AML_CHECKS_11 (AML_ID, SUBJECT_REF, RESULT) VALUES (:aml_id, :subject_ref, :result);
$$
