CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SANCTIONS_ENTRY_11(entry_id STRING, name STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SANCTIONS_LIST_11 t USING (SELECT :entry_id AS eid, :name AS nm, :meta AS m) s ON t.ENTRY_ID = s.eid WHEN MATCHED THEN UPDATE SET NAME = s.nm, META = s.m WHEN NOT MATCHED THEN INSERT (ENTRY_ID, NAME, META) VALUES (s.eid, s.nm, s.m);
$$
