CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_GEOFENCING_RULE_11(rule_id STRING, name STRING, polygon VARIANT, action STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.GEOFENCING_RULES_11 t USING (SELECT :rule_id AS rid, :name AS nm, :polygon AS pg, :action AS ac, :enabled AS en) s ON t.RULE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, POLYGON = s.pg, ACTION = s.ac, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (RULE_ID, NAME, POLYGON, ACTION, ENABLED) VALUES (s.rid, s.nm, s.pg, s.ac, s.en);
$$
