CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_PROVIDER_STATUS_11(provider_id STRING, name STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PROVIDER_STATUS_11 t USING (SELECT :provider_id AS pid, :name AS nm, :status AS st) s ON t.PROVIDER_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, STATUS = s.st, LAST_UPDATED = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PROVIDER_ID, NAME, STATUS) VALUES (s.pid, s.nm, s.st);
$$
