CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PROVIDER_COST_11(cost_id STRING, provider_id STRING, cost_variant VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_COSTS_11 (COST_ID, PROVIDER_ID, COST_VARIANT) VALUES (:cost_id, :provider_id, :cost_variant);
$$
