CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_PROVIDER_CHANNEL_11(channel_id STRING, provider_id STRING, channel_type STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PROVIDER_NOTIFICATION_CHANNELS_11 (CHANNEL_ID, PROVIDER_ID, CHANNEL_TYPE, CONFIG, ENABLED) VALUES (:channel_id, :provider_id, :channel_type, :config, :enabled);
$$
