CREATE OR REPLACE PROCEDURE DOCGEN.SEND_MAINTENANCE_NOTIFICATION_11(notif_id STRING, window_id STRING, channel STRING, message STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_NOTIFICATIONS_11 (NOTIF_ID, WINDOW_ID, CHANNEL, MESSAGE) VALUES (:notif_id, :window_id, :channel, :message);
$$
