CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FEATURE_TOGGLE_AUDIT_11(audit_id STRING, feature_key STRING, account_id STRING, old_value VARIANT, new_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEATURE_TOGGLE_AUDIT_11 (AUDIT_ID, FEATURE_KEY, ACCOUNT_ID, OLD_VALUE, NEW_VALUE) VALUES (:audit_id, :feature_key, :account_id, :old_value, :new_value);
$$
