CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FEATURE_FLAG_ROLLOUT_11(rollout_id STRING, feature_key STRING, segment VARIANT, status STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEATURE_FLAG_ROLLOUTS_11 (ROLLOUT_ID, FEATURE_KEY, SEGMENT, STATUS, START_AT, END_AT) VALUES (:rollout_id, :feature_key, :segment, :status, :start_at, :end_at);
$$
