CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNER_CONSENT_12(consent_id STRING, signer_id STRING, bundle_id STRING, consent_text STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_CONSENTS_12 (CONSENT_ID, SIGNER_ID, BUNDLE_ID, CONSENT_TEXT) VALUES (:consent_id, :signer_id, :bundle_id, :consent_text);
$$

