CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SYSTEM_EVENT_12(event_id STRING, source STRING, level STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SYSTEM_EVENTS_12 (EVENT_ID, SOURCE, LEVEL, PAYLOAD) VALUES (:event_id, :source, :level, :payload);
$$

