CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_CONSENT_12(revoc_id STRING, consent_id STRING, revoked_by STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_CONSENT_REVOCATIONS_12 (REVOC_ID, CONSENT_ID, REVOKED_BY, REASON) VALUES (:revoc_id, :consent_id, :revoked_by, :reason);
$$

