CREATE OR REPLACE PROCEDURE DOCGEN.EMIT_TELEMETRY_EVENT_12(tele_id STRING, type STRING, context VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TELEMETRY_EVENTS_12 (TELE_ID, TYPE, CONTEXT) VALUES (:tele_id, :type, :context);
$$

