CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TEMPLATE_AUDIT_12(audit_id STRING, template_id STRING, action STRING, performed_by STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_AUDIT_12 (AUDIT_ID, TEMPLATE_ID, ACTION, PERFORMED_BY, DETAILS) VALUES (:audit_id, :template_id, :action, :performed_by, :details);
$$

