CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_HEALTH_CHECK_12(check_id STRING, component STRING, status STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.HEALTH_CHECKS_12 t USING (SELECT :check_id AS cid, :component AS comp, :status AS st, :details AS dt) s
ON t.CHECK_ID = s.cid
WHEN MATCHED THEN UPDATE SET COMPONENT = s.comp, STATUS = s.st, DETAILS = s.dt, CHECKED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CHECK_ID, COMPONENT, STATUS, DETAILS) VALUES (s.cid, s.comp, s.st, s.dt);
$$

