CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CLAUSE_USAGE_12(usage_id STRING, clause_id STRING, template_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CLAUSE_USAGE_12 (USAGE_ID, CLAUSE_ID, TEMPLATE_ID, ACCOUNT_ID) VALUES (:usage_id, :clause_id, :template_id, :account_id);
$$

