CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_ALERT_POLICY_12(policy_id STRING, name STRING, rules VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ALERT_POLICIES_12 t USING (SELECT :policy_id AS pid, :name AS nm, :rules AS r, :enabled AS e) s
ON t.POLICY_ID = s.pid
WHEN MATCHED THEN UPDATE SET NAME = s.nm, RULES = s.r, ENABLED = s.e, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, RULES, ENABLED) VALUES (s.pid, s.nm, s.r, s.e);
$$

