CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_TEMPLATE_SNAPSHOT_12(snapshot_id STRING, template_id STRING, version_number NUMBER, snapshot_clob CLOB)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TEMPLATE_SNAPSHOTS_12 (SNAPSHOT_ID, TEMPLATE_ID, VERSION_NUMBER, SNAPSHOT_CLOB) VALUES (:snapshot_id, :template_id, :version_number, :snapshot_clob);
$$

