CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_RENDER_JOB_12(queue_id STRING, bundle_id STRING, template_id STRING, priority NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_QUEUE_12 (QUEUE_ID, BUNDLE_ID, TEMPLATE_ID, PRIORITY, STATUS) VALUES (:queue_id, :bundle_id, :template_id, :priority, 'PENDING');
$$

