CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INCIDENT_RESPONSE_12(response_id STRING, incident_id STRING, actions VARIANT, resolved_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INCIDENT_RESPONSES_12 (RESPONSE_ID, INCIDENT_ID, ACTIONS, RESOLVED_AT) VALUES (:response_id, :incident_id, :actions, :resolved_at);
$$

