CREATE OR REPLACE PROCEDURE DOCGEN.STORE_PDF_METADATA_12(pdf_id STRING, bundle_id STRING, url STRING, size_bytes NUMBER, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PDF_STORAGE_12 (PDF_ID, BUNDLE_ID, URL, SIZE_BYTES, CHECKSUM) VALUES (:pdf_id, :bundle_id, :url, :size_bytes, :checksum);
$$

