CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CHANGE_LOG_12(log_id STRING, entity_name STRING, entity_id STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CHANGE_LOGS_12 (LOG_ID, ENTITY_NAME, ENTITY_ID, CHANGES) VALUES (:log_id, :entity_name, :entity_id, :changes);
$$

