CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_NOTIFICATION_12(notif_id STRING, bundle_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_QUEUE_12 (NOTIF_ID, BUNDLE_ID, CHANNEL, PAYLOAD, STATUS) VALUES (:notif_id, :bundle_id, :channel, :payload, 'PENDING');
$$

