CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTIFICATION_DISPATCH_12(log_id STRING, notif_id STRING, channel STRING, status STRING, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_DISPATCH_LOG_12 (LOG_ID, NOTIF_ID, CHANNEL, STATUS, RESPONSE) VALUES (:log_id, :notif_id, :channel, :status, :response);
$$

