CREATE OR REPLACE PROCEDURE DOCGEN.START_PLAYBOOK_EXECUTION_12(exec_id STRING, runbook_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PLAYBOOK_EXECUTIONS_12 (EXEC_ID, RUNBOOK_ID, STATUS) VALUES (:exec_id, :runbook_id, 'RUNNING');
$$

