CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_ACTION_12(action_id STRING, exec_id STRING, operator STRING, step STRING, result VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ACTIONS_12 (ACTION_ID, EXEC_ID, OPERATOR, STEP, RESULT) VALUES (:action_id, :exec_id, :operator, :step, :result);
$$

