CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SMS_TEMPLATE_12(template_id STRING, name STRING, body STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SMS_TEMPLATES_12 t USING (SELECT :template_id AS tid, :name AS nm, :body AS bd) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET NAME = s.nm, BODY = s.bd, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, BODY) VALUES (s.tid, s.nm, s.bd);
$$

