CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_PUSH_TEMPLATE_12(template_id STRING, name STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.PUSH_TEMPLATES_12 t USING (SELECT :template_id AS tid, :name AS nm, :payload AS pl) s ON t.TEMPLATE_ID = s.tid WHEN MATCHED THEN UPDATE SET NAME = s.nm, PAYLOAD = s.pl, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (TEMPLATE_ID, NAME, PAYLOAD) VALUES (s.tid, s.nm, s.pl);
$$

