CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_MAINTENANCE_WINDOW_12(window_id STRING, start_at TIMESTAMP_LTZ, end_at TIMESTAMP_LTZ, description STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MAINTENANCE_WINDOWS_12 (WINDOW_ID, START_AT, END_AT, DESCRIPTION) VALUES (:window_id, :start_at, :end_at, :description);
$$

