CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BACKUP_RUN_12(run_id STRING, schedule_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BACKUP_RUNS_12 (RUN_ID, SCHEDULE_ID, STATUS) VALUES (:run_id, :schedule_id, :status);
$$

