CREATE OR REPLACE PROCEDURE DOCGEN.ADD_SUPPORT_TICKET_UPDATE_12(update_id STRING, ticket_id STRING, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SUPPORT_TICKET_UPDATES_12 (UPDATE_ID, TICKET_ID, NOTE) VALUES (:update_id, :ticket_id, :note);
$$

