CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_QUOTA_USAGE_12(usage_id STRING, quota_id STRING, usage_amount NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_USAGE_12 (USAGE_ID, QUOTA_ID, USAGE_AMOUNT) VALUES (:usage_id, :quota_id, :usage_amount);
$$

