CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_SLA_ALERT_12(alert_id STRING, sla_id STRING, metric STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SLA_ALERTS_12 (ALERT_ID, SLA_ID, METRIC, VALUE) VALUES (:alert_id, :sla_id, :metric, :value);
$$

