CREATE OR REPLACE PROCEDURE DOCGEN.TRIGGER_QUOTA_ALERT_12(alert_id STRING, quota_id STRING, threshold NUMBER, current_usage NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.QUOTA_ALERTS_12 (ALERT_ID, QUOTA_ID, THRESHOLD, CURRENT_USAGE) VALUES (:alert_id, :quota_id, :threshold, :current_usage);
$$

