CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_HEARTBEAT_12(check_id STRING, component STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.HEARTBEAT_CHECKS_12 t USING (SELECT :check_id AS cid, :component AS comp, :status AS st) s ON t.CHECK_ID = s.cid WHEN MATCHED THEN UPDATE SET COMPONENT = s.comp, STATUS = s.st, LAST_HEARTBEAT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CHECK_ID, COMPONENT, STATUS) VALUES (s.cid, s.comp, s.st);
$$

