CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ACCESS_LOG_12(log_id STRING, admin_user STRING, action STRING, target STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_ACCESS_LOGS_12 (LOG_ID, ADMIN_USER, ACTION, TARGET) VALUES (:log_id, :admin_user, :action, :target);
$$

