CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_NOTIFICATION_PREFERENCE_12(pref_id STRING, tenant_id STRING, channels ARRAY)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.NOTIFICATION_PREFERENCES_12 t USING (SELECT :pref_id AS pid, :tenant_id AS tid, :channels AS ch) s ON t.PREF_ID = s.pid WHEN MATCHED THEN UPDATE SET TENANT_ID = s.tid, CHANNELS = s.ch, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PREF_ID, TENANT_ID, CHANNELS) VALUES (s.pid, s.tid, s.ch);
$$

