CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SCHEDULED_JOB_12(job_id STRING, name STRING, cron_expr STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SCHEDULED_JOBS_12 (JOB_ID, NAME, CRON_EXPR, ENABLED) VALUES (:job_id, :name, :cron_expr, :enabled);
$$

