CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_NOTIFICATION_HISTORY_12(nh_id STRING, pref_id STRING, channel STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.NOTIFICATION_HISTORY_12 (NH_ID, PREF_ID, CHANNEL, PAYLOAD) VALUES (:nh_id, :pref_id, :channel, :payload);
$$

