CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ADMIN_TASK_12(task_id STRING, name STRING, command STRING, schedule STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_TASKS_12 (TASK_ID, NAME, COMMAND, SCHEDULE, ENABLED) VALUES (:task_id, :name, :command, :schedule, :enabled);
$$

