CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_JOB_RUN_12(run_id STRING, job_id STRING, status STRING, started_at TIMESTAMP_LTZ, completed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.JOB_RUNS_12 (RUN_ID, JOB_ID, STATUS, STARTED_AT, COMPLETED_AT) VALUES (:run_id, :job_id, :status, :started_at, :completed_at);
$$

