CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_TASK_RUN_12(run_id STRING, task_id STRING, status STRING, logs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_TASK_RUNS_12 (RUN_ID, TASK_ID, STATUS, LOGS) VALUES (:run_id, :task_id, :status, :logs);
$$

