CREATE OR REPLACE PROCEDURE DOCGEN.STORE_SERVICE_KEY_12(key_id STRING, service_id STRING, key_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_KEYS_12 (KEY_ID, SERVICE_ID, KEY_HASH) VALUES (:key_id, :service_id, :key_hash);
$$

