CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_KEY_ROTATION_12(rotation_id STRING, key_id STRING, prev_hash STRING, new_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.KEY_ROTATIONS_12 (ROTATION_ID, KEY_ID, PREV_HASH, NEW_HASH) VALUES (:rotation_id, :key_id, :prev_hash, :new_hash);
$$

