CREATE OR REPLACE PROCEDURE DOCGEN.ISSUE_ACCESS_TOKEN_12(token_id STRING, subject STRING, scope STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_TOKENS_12 (TOKEN_ID, SUBJECT, SCOPE, EXPIRES_AT) VALUES (:token_id, :subject, :scope, :expires_at);
$$

