CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_OAUTH_CLIENT_13(client_id STRING, account_id STRING, client_metadata VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_CLIENTS_13 (CLIENT_ID, ACCOUNT_ID, CLIENT_METADATA) VALUES (:client_id, :account_id, :client_metadata);
$$

