CREATE OR REPLACE PROCEDURE DOCGEN.BIND_SESSION_TOKEN_12(sess_token_id STRING, session_id STRING, token_id STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SESSION_TOKENS_12 (SESS_TOKEN_ID, SESSION_ID, TOKEN_ID, EXPIRES_AT) VALUES (:sess_token_id, :session_id, :token_id, :expires_at);
$$

