CREATE OR REPLACE PROCEDURE DOCGEN.ISSUE_OAUTH_TOKEN_13(token_id STRING, client_id STRING, subject STRING, scope STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_TOKENS_13 (TOKEN_ID, CLIENT_ID, SUBJECT, SCOPE, EXPIRES_AT) VALUES (:token_id, :client_id, :subject, :scope, :expires_at);
$$

