CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_AUDIT_EXPORT_REQUEST_12(req_id STRING, scope VARIANT, requested_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_EXPORT_REQUESTS_12 (REQ_ID, SCOPE, REQUESTED_BY, STATUS) VALUES (:req_id, :scope, :requested_by, 'PENDING');
$$

