CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_OAUTH_TOKEN_13(revoc_id STRING, token_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OAUTH_REVOCATIONS_13 (REVOC_ID, TOKEN_ID, REASON) VALUES (:revoc_id, :token_id, :reason);
$$

