CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ARCHIVE_INDEX_13(archive_id STRING, bundle_id STRING, location STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ARCHIVE_INDEX_13 (ARCHIVE_ID, BUNDLE_ID, LOCATION) VALUES (:archive_id, :bundle_id, :location);
$$

