CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_NOTE_12(note_id STRING, operator STRING, context VARIANT, note TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_NOTES_12 (NOTE_ID, OPERATOR, CONTEXT, NOTE) VALUES (:note_id, :operator, :context, :note);
$$

