CREATE OR REPLACE PROCEDURE DOCGEN.COMPUTE_EVIDENCE_CHECKSUM_13(check_id STRING, bundle_id STRING, checksum STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EVIDENCE_CHECKSUMS_13 (CHECK_ID, BUNDLE_ID, CHECKSUM) VALUES (:check_id, :bundle_id, :checksum);
$$

