CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_FEEDBACK_12(fb_id STRING, ann_id STRING, user STRING, feedback TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_FEEDBACK_12 (FB_ID, ANN_ID, USER, FEEDBACK) VALUES (:fb_id, :ann_id, :user, :feedback);
$$

