CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_ANCHOR_PUBLISH_JOB_13(job_id STRING, prov_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ANCHOR_PUBLISH_JOBS_13 (JOB_ID, PROV_ID, STATUS) VALUES (:job_id, :prov_id, 'QUEUED');
$$

