CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SIGNATURE_BLOCK_13(block_id STRING, template_id STRING, field_ref STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_BLOCK_REGISTRY_13 (BLOCK_ID, TEMPLATE_ID, FIELD_REF, CONFIG) VALUES (:block_id, :template_id, :field_ref, :config);
$$

