CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_POLICY_AUDIT_12(audit_id STRING, policy_id STRING, changed_by STRING, changes VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ADMIN_POLICY_AUDIT_12 (AUDIT_ID, POLICY_ID, CHANGED_BY, CHANGES) VALUES (:audit_id, :policy_id, :changed_by, :changes);
$$

