CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIGNATURE_BLOCK_USAGE_13(usage_id STRING, block_id STRING, document_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_BLOCK_USAGE_13 (USAGE_ID, BLOCK_ID, DOCUMENT_ID) VALUES (:usage_id, :block_id, :document_id);
$$

