CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_DATA_RETENTION_REPORT_12(report_id STRING, policy_id STRING, summary VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.DATA_RETENTION_REPORTS_12 (REPORT_ID, POLICY_ID, SUMMARY) VALUES (:report_id, :policy_id, :summary);
$$

