CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_PIA_ASSESSMENT_12(pia_id STRING, name STRING, scope VARIANT, findings VARIANT, completed_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PIA_ASSESSMENTS_12 (PIA_ID, NAME, SCOPE, FINDINGS, COMPLETED_AT) VALUES (:pia_id, :name, :scope, :findings, :completed_at);
$$

