CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_THREAT_MODEL_12(model_id STRING, name STRING, description STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_MODELS_12 (MODEL_ID, NAME, DESCRIPTION) VALUES (:model_id, :name, :description);
$$

