CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_UI_THEME_13(theme_id STRING, account_id STRING, theme VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.UI_THEMES_13 t USING (SELECT :theme_id AS tid, :account_id AS aid, :theme AS th) s ON t.THEME_ID = s.tid WHEN MATCHED THEN UPDATE SET ACCOUNT_ID = s.aid, THEME = s.th, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (THEME_ID, ACCOUNT_ID, THEME) VALUES (s.tid, s.aid, s.th);
$$

