CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_RED_TEAM_FINDING_12(finding_id STRING, model_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RED_TEAM_FINDINGS_12 (FINDING_ID, MODEL_ID, DETAILS) VALUES (:finding_id, :model_id, :details);
$$

