CREATE OR REPLACE PROCEDURE DOCGEN.REVOKE_TOKEN_RECORD_13(revoke_id STRING, token_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.REVOKED_TOKENS_13 (REVOKE_ID, TOKEN_ID) VALUES (:revoke_id, :token_id);
$$

