CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_USER_PREFERENCES_13(pref_id STRING, user_id STRING, prefs VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.USER_PREFERENCES_13 t USING (SELECT :pref_id AS pid, :user_id AS uid, :prefs AS p) s ON t.PREF_ID = s.pid WHEN MATCHED THEN UPDATE SET USER_ID = s.uid, PREFS = s.p, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (PREF_ID, USER_ID, PREFS) VALUES (s.pid, s.uid, s.p);
$$

