CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_TRAINING_JOB_12(job_id STRING, model_id STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TRAINING_JOBS_12 (JOB_ID, MODEL_ID, CONFIG, STATUS) VALUES (:job_id, :model_id, :config, 'QUEUED');
$$

