CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_USER_DEVICE_13(device_id STRING, user_id STRING, meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.USER_DEVICES_13 (DEVICE_ID, USER_ID, META) VALUES (:device_id, :user_id, :meta);
$$

