CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_DEVICE_TRUST_SCORE_13(score_id STRING, device_id STRING, score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.DEVICE_TRUST_SCORES_13 t USING (SELECT :score_id AS sid, :device_id AS did, :score AS sc) s ON t.SCORE_ID = s.sid WHEN MATCHED THEN UPDATE SET DEVICE_ID = s.did, SCORE = s.sc, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SCORE_ID, DEVICE_ID, SCORE) VALUES (s.sid, s.did, s.sc);
$$

