CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_MODEL_DEPLOYMENT_12(deploy_id STRING, model_id STRING, env STRING, version STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_DEPLOYMENTS_12 (DEPLOY_ID, MODEL_ID, ENV, VERSION) VALUES (:deploy_id, :model_id, :env, :version);
$$

