CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BIOMETRIC_HASH_13(hash_id STRING, signer_id STRING, hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_HASHES_13 (HASH_ID, SIGNER_ID, HASH) VALUES (:hash_id, :signer_id, :hash);
$$

