CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_FEATURE_USAGE_ALERT_12(alert_id STRING, feature_key STRING, account_id STRING, metric VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEATURE_USAGE_ALERTS_12 (ALERT_ID, FEATURE_KEY, ACCOUNT_ID, METRIC) VALUES (:alert_id, :feature_key, :account_id, :metric);
$$

