CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SERVICE_SLOWNESS_12(incident_id STRING, service_id STRING, latency_ms NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SERVICE_SLOWNESS_12 (INCIDENT_ID, SERVICE_ID, LATENCY_MS) VALUES (:incident_id, :service_id, :latency_ms);
$$

