CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_BIOMETRIC_MATCH_13(log_id STRING, hash_id STRING, score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BIOMETRIC_MATCH_LOGS_13 (LOG_ID, HASH_ID, SCORE) VALUES (:log_id, :hash_id, :score);
$$

