CREATE OR REPLACE PROCEDURE DOCGEN.OPEN_FRAUD_INVESTIGATION_13(invest_id STRING, signer_id STRING, bundle_id STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FRAUD_INVESTIGATIONS_13 (INVEST_ID, SIGNER_ID, BUNDLE_ID, STATUS, DETAILS) VALUES (:invest_id, :signer_id, :bundle_id, 'OPEN', :details);
$$

