CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_AUDIT_ACCESS_POLICY_12(policy_id STRING, name STRING, conditions VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.AUDIT_ACCESS_POLICIES_12 t USING (SELECT :policy_id AS pid, :name AS nm, :conditions AS cond, :enabled AS en) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, CONDITIONS = s.cond, ENABLED = s.en WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, CONDITIONS, ENABLED) VALUES (s.pid, s.nm, s.cond, s.en);
$$

