CREATE OR REPLACE PROCEDURE DOCGEN.SUBMIT_AUDIT_ACCESS_REQUEST_12(req_id STRING, policy_id STRING, requestor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.AUDIT_ACCESS_REQUESTS_12 (REQ_ID, POLICY_ID, REQUESTOR, STATUS) VALUES (:req_id, :policy_id, :requestor, 'PENDING');
$$

