CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_RISK_POLICY_13(assign_id STRING, policy_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RISK_POLICY_ASSIGNMENTS_13 (ASSIGN_ID, POLICY_ID, TARGET_REF) VALUES (:assign_id, :policy_id, :target_ref);
$$

