CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_OPERATOR_ROLE_12(role_id STRING, name STRING, permissions VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.OPERATOR_ROLES_12 t USING (SELECT :role_id AS rid, :name AS nm, :permissions AS perms) s ON t.ROLE_ID = s.rid WHEN MATCHED THEN UPDATE SET NAME = s.nm, PERMISSIONS = s.perms, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (ROLE_ID, NAME, PERMISSIONS) VALUES (s.rid, s.nm, s.perms);
$$

