CREATE OR REPLACE PROCEDURE DOCGEN.ASSIGN_OPERATOR_ROLE_12(assign_id STRING, operator STRING, role_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_ASSIGNMENTS_12 (ASSIGN_ID, OPERATOR, ROLE_ID) VALUES (:assign_id, :operator, :role_id);
$$

