CREATE OR REPLACE PROCEDURE DOCGEN.START_OPERATOR_SESSION_12(session_id STRING, operator STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_SESSIONS_12 (SESSION_ID, OPERATOR) VALUES (:session_id, :operator);
$$

