CREATE OR REPLACE PROCEDURE DOCGEN.SET_PRIVACY_FLAG_13(flag_id STRING, bundle_id STRING, flag_type STRING, set_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.PRIVACY_FLAGS_13 (FLAG_ID, BUNDLE_ID, FLAG_TYPE, SET_BY) VALUES (:flag_id, :bundle_id, :flag_type, :set_by);
$$

