CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_AUDIT_12(audit_id STRING, operator STRING, action STRING, target STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OPERATOR_AUDIT_TRAIL_12 (AUDIT_ID, OPERATOR, ACTION, TARGET, DETAILS) VALUES (:audit_id, :operator, :action, :target, :details);
$$

