CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_TRAINING_FEEDBACK_12(fb_id STRING, job_id STRING, user STRING, feedback TEXT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.TRAINING_FEEDBACK_12 (FB_ID, JOB_ID, USER, FEEDBACK) VALUES (:fb_id, :job_id, :user, :feedback);
$$

