CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_FEATURE_OWNER_CONTACT_12(contact_id STRING, feature_key STRING, owner STRING, contact_info VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEATURE_OWNER_CONTACTS_12 (CONTACT_ID, FEATURE_KEY, OWNER, CONTACT_INFO) VALUES (:contact_id, :feature_key, :owner, :contact_info);
$$

