CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_FEATURE_OWNER_ESCALATION_12(esc_id STRING, contact_id STRING, issue_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FEATURE_OWNER_ESCALATIONS_12 (ESC_ID, CONTACT_ID, ISSUE_REF) VALUES (:esc_id, :contact_id, :issue_ref);
$$

