CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ADMIN_ANNOUNCEMENT_13(ann_id STRING, title STRING, body STRING, level STRING, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_ADMIN_ANNOUNCEMENTS_13 (ANN_ID, TITLE, BODY, LEVEL, CREATED_BY) VALUES (:ann_id, :title, :body, :level, :created_by);
$$

