CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OPERATOR_NOTE_13(note_id STRING, operator STRING, context VARIANT, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_OPERATOR_NOTES_13 (NOTE_ID, OPERATOR, CONTEXT, NOTE) VALUES (:note_id, :operator, :context, :note);
$$

