CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_PLAYBOOK_TEMPLATE_13(template_id STRING, name STRING, steps VARIANT, created_by STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_PLAYBOOK_TEMPLATES_13 (TEMPLATE_ID, NAME, STEPS, CREATED_BY) VALUES (:template_id, :name, :steps, :created_by);
$$

