CREATE OR REPLACE PROCEDURE DOCGEN.START_PLAYBOOK_RUN_13(run_id STRING, template_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_PLAYBOOK_RUNS_13 (RUN_ID, TEMPLATE_ID, STATUS) VALUES (:run_id, :template_id, 'STARTED');
$$

