CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INCIDENT_UPDATE_13(update_id STRING, incident_id STRING, note STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_INCIDENT_UPDATES_13 (UPDATE_ID, INCIDENT_ID, NOTE) VALUES (:update_id, :incident_id, :note);
$$

