CREATE OR REPLACE PROCEDURE DOCGEN.INCREMENT_WEBHOOK_RETRY_13(retry_id STRING, event_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIG_WEBHOOK_RETRIES_13 t USING (SELECT :retry_id AS rid, :event_id AS eid) s ON t.RETRY_ID = s.rid WHEN MATCHED THEN UPDATE SET ATTEMPTS = t.ATTEMPTS + 1, LAST_ATTEMPT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (RETRY_ID, EVENT_ID, ATTEMPTS, LAST_ATTEMPT) VALUES (s.rid, s.eid, 1, CURRENT_TIMESTAMP());
$$

