CREATE OR REPLACE PROCEDURE DOCGEN.MOVE_TO_DLQ_13(dlq_id STRING, orig_event_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_DLQ_EVENTS_13 (DLQ_ID, ORIG_EVENT_ID, REASON) VALUES (:dlq_id, :orig_event_id, :reason);
$$

