CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_RETRY_POLICY_13(policy_id STRING, name STRING, max_attempts NUMBER, base_backoff_ms NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIG_RETRY_POLICIES_13 t USING (SELECT :policy_id AS pid, :name AS nm, :max_attempts AS ma, :base_backoff_ms AS bb) s ON t.POLICY_ID = s.pid WHEN MATCHED THEN UPDATE SET NAME = s.nm, MAX_ATTEMPTS = s.ma, BASE_BACKOFF_MS = s.bb WHEN NOT MATCHED THEN INSERT (POLICY_ID, NAME, MAX_ATTEMPTS, BASE_BACKOFF_MS) VALUES (s.pid, s.nm, s.ma, s.bb);
$$

