CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_DELIVERY_PROVIDER_13(provider_id STRING, name STRING, type STRING, config VARIANT, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_DELIVERY_PROVIDERS_13 (PROVIDER_ID, NAME, TYPE, CONFIG, ENABLED) VALUES (:provider_id, :name, :type, :config, :enabled);
$$

