CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_DELIVERY_PROVIDER_METRIC_13(metric_id STRING, provider_id STRING, metric_name STRING, metric_value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_DELIVERY_PROVIDER_METRICS_13 (METRIC_ID, PROVIDER_ID, METRIC_NAME, METRIC_VALUE) VALUES (:metric_id, :provider_id, :metric_name, :metric_value);
$$

