CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_DELIVERY_PROVIDER_CONFIG_13(config_id STRING, provider_id STRING, config VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIG_DELIVERY_PROVIDER_CONFIGS_13 t USING (SELECT :config_id AS cid, :provider_id AS pid, :config AS cfg) s ON t.CONFIG_ID = s.cid WHEN MATCHED THEN UPDATE SET PROVIDER_ID = s.pid, CONFIG = s.cfg, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (CONFIG_ID, PROVIDER_ID, CONFIG) VALUES (s.cid, s.pid, s.cfg);
$$

