CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_CALLBACK_ENDPOINT_13(endpoint_id STRING, name STRING, url STRING, method STRING, headers VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_CALLBACK_ENDPOINTS_13 (ENDPOINT_ID, NAME, URL, METHOD, HEADERS) VALUES (:endpoint_id, :name, :url, :method, :headers);
$$

