CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CALLBACK_HISTORY_13(callback_id STRING, endpoint_id STRING, payload VARIANT, response VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_CALLBACK_HISTORY_13 (CALLBACK_ID, ENDPOINT_ID, PAYLOAD, RESPONSE) VALUES (:callback_id, :endpoint_id, :payload, :response);
$$

