CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_ACTION_FROM_TEMPLATE_13(action_id STRING, template_id STRING, next_run TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_SCHEDULED_ACTIONS_13 (ACTION_ID, TEMPLATE_ID, NEXT_RUN, STATUS) VALUES (:action_id, :template_id, :next_run, 'SCHEDULED');
$$

