CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACTION_EXECUTION_13(log_id STRING, action_id STRING, status STRING, output VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_ACTION_EXECUTION_LOGS_13 (LOG_ID, ACTION_ID, STATUS, OUTPUT) VALUES (:log_id, :action_id, :status, :output);
$$

