CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_API_USAGE_13(usage_id STRING, key_id STRING, endpoint STRING, method STRING, response_code NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_API_USAGE_13 (USAGE_ID, KEY_ID, ENDPOINT, METHOD, RESPONSE_CODE) VALUES (:usage_id, :key_id, :endpoint, :method, :response_code);
$$

