CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_API_RATE_LIMIT_13(limit_id STRING, key_id STRING, window_seconds NUMBER, max_requests NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIG_API_RATE_LIMITS_13 t USING (SELECT :limit_id AS lid, :key_id AS kid, :window_seconds AS ws, :max_requests AS mr) s ON t.LIMIT_ID = s.lid WHEN MATCHED THEN UPDATE SET KEY_ID = s.kid, WINDOW_SECONDS = s.ws, MAX_REQUESTS = s.mr WHEN NOT MATCHED THEN INSERT (LIMIT_ID, KEY_ID, WINDOW_SECONDS, MAX_REQUESTS) VALUES (s.lid, s.kid, s.ws, s.mr);
$$

