CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_OCSP_CHECK_13(check_id STRING, cert_id STRING, status STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_OCSP_CHECKS_13 (CHECK_ID, CERT_ID, STATUS) VALUES (:check_id, :cert_id, :status);
$$

