CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_CRL_UPDATE_13(update_id STRING, source STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_CRL_UPDATES_13 (UPDATE_ID, SOURCE, DETAILS) VALUES (:update_id, :source, :details);
$$

