CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_POLICY_TEMPLATE_13(template_id STRING, name STRING, rules VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_POLICY_TEMPLATES_13 (TEMPLATE_ID, NAME, RULES) VALUES (:template_id, :name, :rules);
$$

