CREATE OR REPLACE PROCEDURE DOCGEN.APPLY_POLICY_INSTANCE_13(instance_id STRING, template_id STRING, target_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIG_POLICY_INSTANCES_13 (INSTANCE_ID, TEMPLATE_ID, TARGET_REF) VALUES (:instance_id, :template_id, :target_ref);
$$

