CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OTP_CHALLENGE_14(otp_id STRING, signer_id STRING, bundle_id STRING, otp_value STRING, expires_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OTP_CHALLENGES_14 (OTP_ID, SIGNER_ID, BUNDLE_ID, OTP_VALUE, EXPIRES_AT)
VALUES (:otp_id, :signer_id, :bundle_id, :otp_value, :expires_at);
$$

