CREATE OR REPLACE PROCEDURE DOCGEN.ARCHIVE_CONSENT_14(archive_id STRING, consent_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.CONSENT_ARCHIVE_14 (ARCHIVE_ID, CONSENT_ID, PAYLOAD) VALUES (:archive_id, :consent_id, :payload);
$$

