CREATE OR REPLACE PROCEDURE DOCGEN.SCHEDULE_RETENTION_ACTION_14(action_id STRING, policy_id STRING, target_table STRING, scheduled_at TIMESTAMP_LTZ)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RETENTION_ACTIONS_14 (ACTION_ID, POLICY_ID, TARGET_TABLE, STATUS, SCHEDULED_AT) VALUES (:action_id, :policy_id, :target_table, 'SCHEDULED', :scheduled_at);
$$

