CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_SHARD_14(shard_id STRING, index_name STRING, shard_uri STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SHARD_MANIFEST_14 (SHARD_ID, INDEX_NAME, SHARD_URI) VALUES (:shard_id, :index_name, :shard_uri);
$$

