CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_FAISS_SNAPSHOT_14(snapshot_id STRING, index_name STRING, s3_prefix STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FAISS_SNAPSHOT_MANIFEST_14 (SNAPSHOT_ID, INDEX_NAME, S3_PREFIX) VALUES (:snapshot_id, :index_name, :s3_prefix);
$$

