CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_EMBEDDING_LOAD_ERROR_14(error_id STRING, job_id STRING, error_payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.EMBEDDING_LOAD_ERRORS_14 (ERROR_ID, JOB_ID, ERROR_PAYLOAD) VALUES (:error_id, :job_id, :error_payload);
$$

