CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_SIMILARITY_REQUEST_14(req_id STRING, account_id STRING, query VARIANT, result_count NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIMILARITY_REQUEST_LOG_14 (REQ_ID, ACCOUNT_ID, QUERY, RESULT_COUNT) VALUES (:req_id, :account_id, :query, :result_count);
$$

