CREATE OR REPLACE PROCEDURE DOCGEN.REPORT_INDEX_RECON_ISSUE_14(issue_id STRING, recon_id STRING, item_ref STRING, issue_desc STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_RECON_ISSUES_14 (ISSUE_ID, RECON_ID, ITEM_REF, ISSUE_DESC) VALUES (:issue_id, :recon_id, :item_ref, :issue_desc);
$$

