CREATE OR REPLACE PROCEDURE DOCGEN.STORE_BILLING_PREVIEW_14(preview_id STRING, account_id STRING, payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.BILLING_PREVIEW_CACHE_14 (PREVIEW_ID, ACCOUNT_ID, PAYLOAD) VALUES (:preview_id, :account_id, :payload);
$$

