CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_INVOICE_RECON_JOB_14(job_id STRING, account_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_RECON_JOBS_14 (JOB_ID, ACCOUNT_ID, STATUS) VALUES (:job_id, :account_id, 'QUEUED');
$$

