CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_INVOICE_DISCREPANCY_14(disc_id STRING, job_id STRING, line_ref STRING, expected VARIANT, actual VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INVOICE_RECON_DISCREPANCIES_14 (DISC_ID, JOB_ID, LINE_REF, EXPECTED, ACTUAL) VALUES (:disc_id, :job_id, :line_ref, :expected, :actual);
$$

