CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_BUSINESS_HOURS_14(bh_id STRING, account_id STRING, timezone STRING, hours VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.BUSINESS_HOURS_14 t USING (SELECT :bh_id AS bid, :account_id AS aid, :timezone AS tz, :hours AS hrs) s ON t.BH_ID = s.bid WHEN MATCHED THEN UPDATE SET ACCOUNT_ID = s.aid, TIMEZONE = s.tz, HOURS = s.hrs, UPDATED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (BH_ID, ACCOUNT_ID, TIMEZONE, HOURS) VALUES (s.bid, s.aid, s.tz, s.hrs);
$$

