CREATE OR REPLACE PROCEDURE DOCGEN.UPDATE_ACCOUNT_TRUST_SCORE_14(score_id STRING, account_id STRING, score NUMBER)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.ACCOUNT_TRUST_SCORES_14 t USING (SELECT :score_id AS sid, :account_id AS aid, :score AS sc) s ON t.SCORE_ID = s.sid WHEN MATCHED THEN UPDATE SET ACCOUNT_ID = s.aid, SCORE = s.sc, COMPUTED_AT = CURRENT_TIMESTAMP() WHEN NOT MATCHED THEN INSERT (SCORE_ID, ACCOUNT_ID, SCORE) VALUES (s.sid, s.aid, s.sc);
$$

