CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_ACCOUNT_INCIDENT_14(incident_id STRING, account_id STRING, severity STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_INCIDENTS_14 (INCIDENT_ID, ACCOUNT_ID, SEVERITY, DETAILS) VALUES (:incident_id, :account_id, :severity, :details);
$$

