CREATE OR REPLACE PROCEDURE DOCGEN.REGISTER_ACCOUNT_CONTACT_14(contact_id STRING, account_id STRING, name STRING, email STRING, role STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_CONTACTS_14 (CONTACT_ID, ACCOUNT_ID, NAME, EMAIL, ROLE) VALUES (:contact_id, :account_id, :name, :email, :role);
$$

