CREATE OR REPLACE PROCEDURE DOCGEN.RECORD_ACCOUNT_ESCALATION_14(esc_id STRING, account_id STRING, issue_ref STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCOUNT_ESCALATIONS_14 (ESC_ID, ACCOUNT_ID, ISSUE_REF) VALUES (:esc_id, :account_id, :issue_ref);
$$

