CREATE OR REPLACE PROCEDURE DOCGEN.FLAG_SIGNATURE_14(flag_id STRING, bundle_id STRING, signer_id STRING, reason STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.FLAGGED_SIGNATURES_14 (FLAG_ID, BUNDLE_ID, SIGNER_ID, REASON) VALUES (:flag_id, :bundle_id, :signer_id, :reason);
$$

