CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_MODERATION_14(mod_id STRING, bundle_id STRING, signer_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODERATION_QUEUE_14 (MOD_ID, BUNDLE_ID, SIGNER_ID, STATUS) VALUES (:mod_id, :bundle_id, :signer_id, 'PENDING');
$$

