CREATE OR REPLACE PROCEDURE DOCGEN.RAISE_THREAT_ALERT_14(alert_id STRING, signer_id STRING, type STRING, details VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.THREAT_ALERTS_14 (ALERT_ID, SIGNER_ID, TYPE, DETAILS) VALUES (:alert_id, :signer_id, :type, :details);
$$

