CREATE OR REPLACE PROCEDURE DOCGEN.GENERATE_MODEL_BIAS_REPORT_14(report_id STRING, model_id STRING, metrics VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.MODEL_BIAS_REPORTS_14 (REPORT_ID, MODEL_ID, METRICS) VALUES (:report_id, :model_id, :metrics);
$$

