CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_ACCESS_REVIEW_REQUEST_14(req_id STRING, target_ref STRING, requestor STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.ACCESS_REVIEW_REQUESTS_14 (REQ_ID, TARGET_REF, REQUESTOR, STATUS) VALUES (:req_id, :target_ref, :requestor, 'PENDING');
$$

