-- Idempotent ingestion stored procedure (SQL wrapper for stage processing)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.UPSERT_SIGNATURE_WEBHOOK(stage_payload VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SIGNATURE_EVENTS t
USING (SELECT :stage_payload::VARIANT AS payload) s
ON t.EVENT_ID = s.payload:EVENT_ID::STRING
WHEN MATCHED THEN UPDATE SET EVENT_PAYLOAD = s.payload, EVENT_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (EVENT_ID, BUNDLE_ID, DOCUMENT_ID, SIGNER_ID, EVENT_TYPE, EVENT_PAYLOAD, EVENT_TS)
VALUES (s.payload:EVENT_ID::STRING, s.payload:BUNDLE_ID::STRING, s.payload:DOCUMENT_ID::STRING, s.payload:SIGNER_ID::STRING, s.payload:EVENT_TYPE::STRING, s.payload, CURRENT_TIMESTAMP());
$$;

Idempotent MERGE-based webhook ingestion procedure following Snowflake patterns. @42 @52

