USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.WRITE_EVIDENCE_BUNDLE(bundle VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVIDENCE_BUNDLE (BUNDLE_ID, REQUEST_ID, ARCHIVE_URL, META, CREATED_AT)
VALUES (bundle:BUNDLE_ID::STRING, bundle:REQUEST_ID::STRING, bundle:ARCHIVE_URL::STRING, bundle:META, CURRENT_TIMESTAMP());
RETURN PARSE_JSON('{"status":"ok","bundle_id":' || QUOTE_LITERAL(bundle:BUNDLE_ID::STRING) || '}');
$$;

Evidence bundle writer to persist CompliancePacket metadata after archive to S3. @36 @61

