USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.RUN_OCSP_CHECK(cert_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OCSP_REVOCATION_INDEX (INDEX_ID, CERT_ID, STATUS, LAST_CHECK)
VALUES (UUID_STRING(), cert_id, 'UNKNOWN', CURRENT_TIMESTAMP());
RETURN PARSE_JSON('{"status":"scheduled"}');
$$;

Schedules OCSP checks and records initial index entry for polling jobs. @118 @31

