USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Example External Function registration template (fill API_INTEGRATION params)
CREATE OR REPLACE API INTEGRATION DOCGEN.SIMILARITY_API_INTEGRATION
ENABLED = TRUE
API_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/SIMILARITY_ROLE'
API_ALLOWED_PREFIXES = ('https://faiss-query.example.com/');
CREATE OR REPLACE EXTERNAL FUNCTION DOCGEN.SIMILARITY_LOOKUP(query EMBEDDING VECTOR)
RETURNS VARIANT
API_INTEGRATION = DOCGEN.SIMILARITY_API_INTEGRATION
HEADERS = (('x-api-key', '<<API_KEY_PLACEHOLDER>>'));

External Function registration pattern for FAISS/query service per Snowflake External Function guidance. @82 @31

