USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.PUBLISH_SIGNATURE_EVENT(event VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVENTS (EVENT_ID, BUNDLE_ID, DOCUMENT_ID, SIGNER_ID, EVENT_TYPE, EVENT_PAYLOAD, EVENT_TS)
VALUES (UUID_STRING(), event:BUNDLE_ID::STRING, event:DOCUMENT_ID::STRING, event:SIGNER_ID::STRING, event:EVENT_TYPE::STRING, event, CURRENT_TIMESTAMP());
$$;

Procedure to publish local events for downstream processing and tasks. @90 @31

