USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.VERIFY_OCSP_AND_RECORD(cert_id STRING)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.10'
HANDLER='verify_ocsp_and_record';

Executes OCSP check for a certificate and records result in OCSP_REVOCATION_INDEX. @118 @31

