USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_CLEANUP_SNAPSHOTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 4 * * * UTC'
AS
CALL DOCGEN.CLEANUP_OLD_SNAPSHOTS(30);

Scheduled maintenance task to expire old index snapshots. @66 @31

