USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.ENQUEUE_DOCUMENT_ASSEMBLY(assembly_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.RENDER_JOBS (JOB_ID, ASSEMBLY_ID, STATUS, CREATED_AT) VALUES (UUID_STRING(), assembly_id, 'QUEUED', CURRENT_TIMESTAMP());
$$;

Enqueues assembly jobs for renderer workers. @66 @31

