USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.STORE_RENDERED_ARTIFACT(job_id STRING, url STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
UPDATE DOCGEN.RENDER_JOBS SET STATUS='COMPLETED', WORKER_NODE=CURRENT_USER(), ATTEMPTS=ATTEMPTS+1 WHERE JOB_ID = job_id;
UPDATE DOCGEN.DOCUMENT_ASSEMBLIES SET RENDERED_URL = url, STATUS='RENDERED' WHERE ASSEMBLY_ID = (SELECT ASSEMBLY_ID FROM DOCGEN.RENDER_JOBS WHERE JOB_ID = job_id);
$$;

Stores rendered artifact references and updates assembly status. @86 @31

