USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.PRUNE_PREVIEW_CACHE()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DELETE FROM DOCGEN.PREVIEW_CACHE WHERE EXPIRES_AT < CURRENT_TIMESTAMP();
$$;

Maintenance proc to prune expired preview cache entries. @88 @31

