CREATE OR REPLACE PROCEDURE DOCGEN.ADMIN_TOGGLE_FEATURE(account_id STRING, feature_key STRING, enabled BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SYS_CONFIG_08 t
USING (SELECT feature_key AS k, PARSE_JSON(OBJECT_CONSTRUCT('enabled', enabled)) AS v) s
ON t.KEY = s.k
WHEN MATCHED THEN UPDATE SET VALUE = s.v, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (KEY, VALUE, UPDATED_AT) VALUES (s.k, s.v, CURRENT_TIMESTAMP());
$$;

Admin toggle stored-proc to turn features on/off per tenant via SYS_CONFIG. @21 @37

