CREATE OR REPLACE PROCEDURE DOCGEN.ARCHIVE_SIGNATURE_EVENT(event_id STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNATURE_EVENTS_ARCHIVE (ARCHIVE_ID, EVENT_ID, DOCUMENT_ID, SIGNER_ID, EVENT_TYPE, EVENT_PAYLOAD, ARCHIVED_AT)
SELECT UUID_STRING(), EVENT_ID, DOCUMENT_ID, SIGNER_ID, EVENT_TYPE, EVENT_PAYLOAD, CURRENT_TIMESTAMP() FROM DOCGEN.SIGNATURE_EVENTS WHERE EVENT_ID = event_id;
$$;

Archives signature events into archival table for long-term retention. @9 @31

