USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_QUERY_CACHE (
  CACHE_KEY STRING PRIMARY KEY,
  QUERY_PAYLOAD VARIANT,
  RESULTS VARIANT,
  CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ
);

Optional cache for frequent FAISS query responses to reduce container calls. @31 @66

