CREATE OR REPLACE PROCEDURE DOCGEN.PRUNE_FAISS_QUERY_CACHE()
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DELETE FROM DOCGEN.FAISS_QUERY_CACHE WHERE EXPIRES_AT < CURRENT_TIMESTAMP();
$$;

Maintenance proc to prune FAISS query cache. @66 @31

