CREATE OR REPLACE TASK DOCGEN.TASK_GENERATE_REPORTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
CALL DOCGEN.GENERATE_DAILY_REPORTS();

Daily reporting generator task for admin dashboards. @116 @31

