CREATE OR REPLACE TASK DOCGEN.TASK_RUN_SIGNATURE_SCORING
WAREHOUSE = 'ML_WH'
SCHEDULE = 'USING CRON 0 */6 * * * UTC'
AS
CALL DOCGEN.RUN_SIGNATURE_SCORING();

Scheduled ML scoring task for signature risk models. @500 @31

