CREATE OR REPLACE VIEW DOCGEN.V_OPERATOR_ALERTS AS
SELECT INCIDENT_ID, SEVERITY, STATUS, CREATED_AT FROM DOCGEN.INCIDENT_REPORTS WHERE STATUS != 'RESOLVED';

Admin/operator dashboard view for outstanding incidents. @344 @31

