CREATE OR REPLACE VIEW DOCGEN.V_POLICY_AUDIT AS
SELECT PAUDIT_ID, VERSION_ID, CHANGED_BY, CHANGED_AT FROM DOCGEN.POLICY_AUDIT ORDER BY CHANGED_AT DESC;

View to present policy audit trail to compliance reviewers. @123 @31

