CREATE OR REPLACE VIEW DOCGEN.V_ADMIN_ROLES AS
SELECT ROLE_ID, NAME, CREATED_AT FROM DOCGEN.ACCESS_CONTROL_ROLES ORDER BY CREATED_AT DESC;

Admin roles view for UI consumption and role management pages. @126 @31

