CREATE OR REPLACE VIEW DOCGEN.V_INCIDENT_PLANS AS
SELECT PLAN_ID, NAME, CREATED_AT FROM DOCGEN.INCIDENT_RESPONSE_PLANS ORDER BY CREATED_AT DESC;

Operational incident plan view for runbook integration. @126 @31

