CREATE OR REPLACE VIEW DOCGEN.V_BILLING_RECONCILIATION AS
SELECT r.INVOICE_ID, r.ACCOUNT_ID, r.TOTAL_AMOUNT, rr.STATUS FROM DOCGEN.BILLING_RUN r LEFT JOIN DOCGEN.BILLING_RECONCILIATION rr ON r.RUN_ID = rr.RUN_ID;

Billing reconciliation view to aid finance audits. @35 @31

