CREATE OR REPLACE TABLE DOCGEN.SERVICE_SLO_METRICS (
  SLO_ID STRING PRIMARY KEY,
  SLO_NAME STRING,
  METRIC_PAYLOAD VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

SLO metrics table to drive operator and SLA dashboards. @62 @31

