CREATE OR REPLACE PROCEDURE DOCGEN.STORE_ADMIN_SECRET(key STRING, value VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
MERGE INTO DOCGEN.SYS_CONFIG_08 t
USING (SELECT key AS k, PARSE_JSON(TO_VARIANT(value)) AS v) s
ON t.KEY = s.k
WHEN MATCHED THEN UPDATE SET VALUE = s.v, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (KEY, VALUE, UPDATED_AT) VALUES (s.k, s.v, CURRENT_TIMESTAMP());
$$;

Secret-like configuration storage for non-credential admin metadata (do not store secrets in plaintext). @78 @31

