CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTION_LOG (
  ACTION_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ACTION STRING,
  TARGET STRING,
  PAYLOAD VARIANT,
  ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Logs human operator actions for compliance and post-incident reviews. @344 @31

