CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_ADMIN_KPIS AS
SELECT ACCOUNT_ID, COUNT(*) AS SIGNATURES_TODAY, SUM(CASE WHEN RESULT='SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_TODAY FROM DOCGEN.SIGNATURE_VERIFICATIONS WHERE VERIFIED_AT >= DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) GROUP BY ACCOUNT_ID;

KPI materialized view for admin console summarizing daily signature counts. @344 @31

