CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_OPERATOR_RECORD(op_id STRING, name STRING, contact VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.OWNER_MAPPING (OWNER_ID, ACCOUNT_ID, CONTACT_REF, CREATED_AT) VALUES (op_id, NULL, TO_VARIANT(contact), CURRENT_TIMESTAMP());
$$;

Utility to seed operator/owner mapping records used by admin consoles. @229 @31

