CREATE OR REPLACE TABLE DOCGEN.ESCALATION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  RULE VARIANT,
  CONTACTS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Escalation policy metadata for alert dispatch workflows. @63 @31

