CREATE OR REPLACE PROCEDURE DOCGEN.CHECK_OPERATOR_KPIS()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.10'
HANDLER='check_operator_kpis';

Operator KPI evaluator for SLO ticket generation. @344 @31

