CREATE OR REPLACE TABLE DOCGEN.SIGNER_FEEDBACK (
  FEEDBACK_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  RATING INT,
  COMMENTS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Captures signer feedback after signature completion for product analytics. @344 @31

