CREATE OR REPLACE PROCEDURE DOCGEN.CAPTURE_SIGNER_FEEDBACK(signer_id STRING, rating INT, comments STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.SIGNER_FEEDBACK (FEEDBACK_ID, SIGNER_ID, RATING, COMMENTS, CREATED_AT) VALUES (UUID_STRING(), signer_id, rating, comments, CURRENT_TIMESTAMP());
$$;

Procedure to persist signer feedback entries. @344 @31

