CREATE OR REPLACE TABLE DOCGEN.SEVERITY_MAP (
  SEVERITY_ID STRING PRIMARY KEY,
  NAME STRING,
  THRESHOLD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Severity mapping used by alerts and incident classification. @63 @31

