CREATE OR REPLACE TABLE DOCGEN.NOTIFY_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  CHANNEL STRING,
  SUBJECT STRING,
  BODY CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Notification templates for consistent operator and customer messages. @24 @31

