USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.CREATE_INDEX_SNAPSHOT(snap_id STRING, shard_meta VARIANT)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
INSERT INTO DOCGEN.INDEX_SNAPSHOT_MANIFEST (SNAP_ID, SHARD, S3_PREFIX, CREATED_AT, META)
VALUES (snap_id, shard_meta:shard::STRING, shard_meta:s3_prefix::STRING, CURRENT_TIMESTAMP(), PARSE_JSON(shard_meta:s3_meta::STRING));
$$;
-- Snapshot registration proc for FAISS manifest pattern @31 @367

