USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.VERIFY_CERT_OCSP(cert_pem STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT DOCGEN.CALL_OCSP(:cert_pem);
$$;
-- SQL wrapper to call OCSP External Function from stored-proc contexts @82 @68

