Purpose: least‑privilege role and grant templates to enforce separation of duties and tenant isolation as required by your security guidance @316 @446.  
-- create_roles_and_grants.sql  
CREATE ROLE DOCGEN_ADMIN;  
CREATE ROLE DOCGEN_MONITOR;  
CREATE ROLE DOCGEN_INGEST;  
GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_INGEST;  
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_INGEST;  
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_INGEST;  
GRANT SELECT ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_MONITOR;  
GRANT OWNERSHIP ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_ADMIN;  

