-- Create roles and grants for Admin, Compliance and Service with explicit privileges
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE ROLE IF NOT EXISTS DOCGEN_ADMIN;
CREATE ROLE IF NOT EXISTS DOCGEN_COMPLIANCE;
CREATE ROLE IF NOT EXISTS DOCGEN_SERVICE;

GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_ADMIN;
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_ADMIN;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_ADMIN;

GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_COMPLIANCE;
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_COMPLIANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_COMPLIANCE;

GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_SERVICE;
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_SERVICE;
GRANT SELECT, INSERT, UPDATE ON TABLES DOCGEN.SIGNATURE_EVENTS, DOCGEN.SIGNATURE_REQUESTS, DOCGEN.SIGNATURE_VALIDATION, DOCGEN.EVIDENCE_BUNDLE TO ROLE DOCGEN_SERVICE;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_SERVICE;

