-- Smoke test that calls EXPORT_EVIDENCE_TO_S3 and checks for bundle row in SIGNATURE_EVIDENCE_BUNDLE. @28 @27
CALL DOCGEN.EXPORT_EVIDENCE_TO_S3('req-0001');
SELECT * FROM DOCGEN.SIGNATURE_EVIDENCE_BUNDLE WHERE REQUEST_ID='req-0001';

