-- Create monitoring role and grant read-only access to telemetry for dashboards
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE ROLE IF NOT EXISTS DOCGEN_MONITOR;
GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_MONITOR;
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_MONITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE DOCGEN_MONITOR;

