-- Roles and grants template for signature domain objects; apply least-privilege and tune per environment before go-live. @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE ROLE IF NOT EXISTS DOCGEN_SIGNATURE_ADMIN;
CREATE ROLE IF NOT EXISTS DOCGEN_SIGNATURE_USER;
GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE DOCGEN_SIGNATURE_USER;
GRANT ALL ON SCHEMA DOCGEN TO ROLE DOCGEN_SIGNATURE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA DOCGEN TO ROLE DOCGEN_SIGNATURE_USER;

