-- Useful admin queries for monitoring and reconciliation
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

-- Recent evidence bundles
SELECT BUNDLE_ID, DOCUMENT_ID, ACCOUNT_ID, CREATED_AT FROM DOCGEN.EVIDENCE_BUNDLE ORDER BY CREATED_AT DESC LIMIT 100;

-- Pending signers
SELECT s.SIGNER_ID, s.REQUEST_ID, r.STATUS, r.DOCUMENT_ID, r.ACCOUNT_ID, r.CREATED_AT
FROM DOCGEN.SIGNERS s
JOIN DOCGEN.SIGNATURE_REQUESTS r ON s.REQUEST_ID = r.REQUEST_ID
WHERE r.STATUS IN ('PENDING','VIEWED') ORDER BY r.CREATED_AT ASC LIMIT 200;

-- Billing mismatch summary
SELECT * FROM DOCGEN.BILLING_RECONCILIATION_RUN WHERE STATUS = 'MISMATCH' ORDER BY RUN_TS DESC LIMIT 50;

