USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE FUNCTION DOCGEN.COMPUTE_PROVENANCE_HASH(payload VARIANT)
RETURNS STRING
LANGUAGE SQL
AS
$$
SELECT MD5(TO_VARCHAR(payload));
$$;
-- Deterministic provenance hash UDF used to anchor CompliancePacket entries @2438 @2271

