USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS (
  SESSION_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  REQUEST_ID STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  IP_ADDRESS STRING,
  USER_AGENT STRING,
  METADATA VARIANT
); Generated per Snowflake E-Sign patterns. @31 @24

