USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATIONS (
  VERIFY_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  METHOD STRING,
  RESULT STRING,
  DETAILS VARIANT,
  VERIFICATION_HASH STRING
); Generated per Snowflake E-Sign patterns. @31 @24

