USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_BUNDLES (
  BUNDLE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  BUNDLE_URL STRING,
  BUNDLE_META VARIANT,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

