USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  SUBJECT STRING,
  ISSUER STRING,
  SERIAL_NUMBER STRING,
  PEM CLOB,
  NOT_BEFORE TIMESTAMP_LTZ,
  NOT_AFTER TIMESTAMP_LTZ,
  OCSP_URLS ARRAY,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

