USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_PROVENANCE (
  PROV_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  VERIFICATION_ID STRING,
  PROV_HASH STRING,
  SOURCE_VARIANT VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

