USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ANCHOR_TX (
  ANCHOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHAIN STRING,
  TXID STRING,
  EXPLORER_URL STRING,
  ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

