USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINALIZATION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @10 @24

