USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OBJECT_LOCKS (
  LOCK_ID STRING PRIMARY KEY,
  OBJECT_REF STRING,
  LOCKED_BY STRING,
  LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ
); Generated per Snowflake E-Sign patterns. @11 @24

