USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS_ARCHIVE (
  ARCHIVE_ID STRING PRIMARY KEY,
  EVENT_ID STRING,
  DOCUMENT_ID STRING,
  SIGNER_ID STRING,
  EVENT_TYPE STRING,
  EVENT_PAYLOAD VARIANT,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @14 @24

