USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_LOCKS (
  LOCK_ID STRING PRIMARY KEY,
  RESOURCE_REF STRING,
  LOCKED_BY STRING,
  LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  TTL_SECONDS INT
); Generated per Snowflake E-Sign patterns. @11 @24

