USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_META_INDEX_01 (
  META_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  META_KEY STRING,
  META_VALUE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @23 @31

