USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_HEALTH_03 (
  HEALTH_ID STRING PRIMARY KEY,
  INTEGRATION_NAME STRING,
  STATUS STRING,
  LAST_CHECK TIMESTAMP_LTZ,
  DETAILS VARIANT
); Generated per Snowflake E-Sign patterns. @27 @31

