USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  TEMPLATE_BODY CLOB,
  DEFAULT_POLICY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @36 @24

