USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_PROCESS_EXPORTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 */2 * * * UTC'
AS CALL DOCGEN.EXPORT_WORKER(10); Generated per Snowflake E-Sign patterns. @120 @31

