USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CONSENT_RECORDS (
  CONSENT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CONSENT_TEXT STRING,
  CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
); Generated per Snowflake E-Sign patterns. @130 @31

