USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VECTOR_STORE (
  VECTOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  EMBEDDING VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @131 @31

