USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECKS (
  HEALTH_ID STRING PRIMARY KEY,
  CHECK_NAME STRING,
  STATUS STRING,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @134 @31

