USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_KEYS_HISTORY (
  KEY_ID STRING PRIMARY KEY,
  KEY_PEM CLOB,
  KEY_CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  KEY_EXPIRES_AT TIMESTAMP_LTZ,
  ROTATED_AT TIMESTAMP_LTZ,
  REVOKED BOOLEAN DEFAULT FALSE
); Generated per Snowflake E-Sign patterns. @144 @31

