USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VERSIONS (
  VERSION_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  VERSION_NUMBER INT,
  BODY CLOB,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @142 @31

