USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_REFRESH_SIGNATURE_REPORTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 * * * * UTC'
AS CALL DOCGEN.REFRESH_SIGNATURE_REPORTS(); Generated per Snowflake E-Sign patterns. @148 @31

