USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_SIGNATURE_AUDIT_SUMMARY AS
SELECT REQUEST_ID, COUNT(*) AS EVENT_COUNT, MAX(EVENT_TS) AS LAST_EVENT_AT
FROM DOCGEN.SIGNATURE_EVENTS
GROUP BY REQUEST_ID; Generated per Snowflake E-Sign patterns. @150 @31

