USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  TABLES VARIANT,
  RETENTION_DAYS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @143 @31

