USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  ALERT_LEVEL STRING,
  DETAILS VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @149 @31

