USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECONCILIATION_LOG (
  RECON_ID STRING PRIMARY KEY,
  SOURCE STRING,
  TARGET STRING,
  STATUS STRING,
  DETAILS VARIANT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @150 @31

