USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_REVIEWS (
  REVIEW_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SCOPE VARIANT,
  REVIEWER STRING,
  RESULT STRING,
  NOTES STRING,
  REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @141 @31

