USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_MANIFESTS (
  MANIFEST_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TARGET_URI STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @244 @31

