USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  ACTION STRING,
  DETAIL VARIANT,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @143 @31

