USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_INDEX (
  ARCHIVE_INDEX_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  LOCATION STRING,
  CHECKSUM STRING,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @149 @31

