USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_METRICS_SUMMARY (
  METRIC_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  METRIC_NAME STRING,
  VALUE NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @304 @31

