USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATIONS (
  NOTIFY_ID STRING PRIMARY KEY,
  CONTEXT VARIANT,
  TITLE STRING,
  BODY STRING,
  LEVEL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

