USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_INDEX_08 (
  AUDIT_IDX_ID STRING PRIMARY KEY,
  AUDIT_REF STRING,
  PAYLOAD VARIANT,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

