USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_METRICS (
  AM_ID STRING PRIMARY KEY,
  ADMIN_USER STRING,
  ACTION STRING,
  AGG_PAYLOAD VARIANT,
  AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

