USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_LINE_ITEM (
  LINE_ITEM_ID STRING PRIMARY KEY,
  BILLING_RUN_ID STRING,
  DESCRIPTION STRING,
  AMOUNT NUMBER,
  CURRENCY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

