USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RUN (
  RUN_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING,
  INVOICE_HASH STRING,
  META VARIANT
); Generated per Snowflake E-Sign patterns. @31 @24

