USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTITLEMENT_CACHE (
  CACHE_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  FEATURE_KEY STRING,
  ALLOWED BOOLEAN,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

