USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_TRAIL (
  AUDIT_ID STRING PRIMARY KEY,
  OBJECT_REF STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

