USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CLAUSES (
  CLAUSE_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  CLAUSE_TEXT CLOB,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @36 @31

