USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_INDEX (
  PROV_IDX_ID STRING PRIMARY KEY,
  PROV_HASH STRING,
  SOURCE_REF STRING,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @55 @31

