USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_AUDIT (
  EXPORT_AUDIT_ID STRING PRIMARY KEY,
  MANIFEST_ID STRING,
  OUTCOME STRING,
  DETAILS VARIANT,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @88 @31

