USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIVITY (
  OP_ID STRING PRIMARY KEY,
  OP_USER STRING,
  ACTION STRING,
  CONTEXT VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @86 @31

