USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDENTIAL_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  CRED_ID STRING,
  ACTION STRING,
  DETAILS VARIANT,
  AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

