USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_JOBS (
  JOB_ID STRING PRIMARY KEY,
  JOB_NAME STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT
); Generated per Snowflake E-Sign patterns. @31 @24

