-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  EVENT_TYPE STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

