-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_IMAGES (
  IMAGE_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  REQUEST_ID STRING,
  IMAGE_REF STRING,
  HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

