-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_HASHES (
  HASH_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  DOCUMENT_HASH STRING,
  SIGNATURE_HASH STRING,
  PROVENANCE_HASH STRING,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

