-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CERT_FINGERPRINT STRING,
  CERT_PEM CLOB,
  ISSUED_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ,
  META VARIANT
);

