-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_BUNDLE (
  BUNDLE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  ACCOUNT_ID STRING,
  BUNDLE_URL STRING,
  MANIFEST VARIANT,
  PROVENANCE_HASH STRING,
  CERT_CHAIN VARIANT,
  OCSP_SNAPSHOTS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

