-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  ACTION STRING,
  RESOURCE STRING,
  SOURCE_IP STRING,
  USER_AGENT STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

