-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_ATTESTATION_RECORDS (
  ATTEST_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  ATTESTATION_JSON VARIANT,
  ATTESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

