-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ALERT_SUBSCRIPTIONS (
  SUB_ID STRING PRIMARY KEY,
  ADMIN_USER STRING,
  ALERT_RULE_ID STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

