-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_LOG (
  CHANGE_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  CHANGED_BY STRING,
  CHANGE_JSON VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

