USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_USAGE ( USAGE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CERT_ID STRING, USAGE_COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

