-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ESCALATION_NOTIFS (
  NOTIF_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  LEVEL STRING,
  MESSAGE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

