USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_ROTATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SCHEDULE_ID STRING, PERFORMED_BY STRING, OUTCOME STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

