USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ENDPOINT_CONFIGS ( EP_ID STRING PRIMARY KEY, PROVIDER_ID STRING, ENDPOINT_URL STRING, AUTH_METHOD STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

