USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_INCIDENT_PLANS AS
SELECT PLAN_ID, NAME, CREATED_AT FROM DOCGEN.INCIDENT_RESPONSE_PLANS ORDER BY CREATED_AT DESC; Generated per Snowflake E-Sign patterns. @158 @31

