USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS (
  SESSION_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  REQUEST_ID STRING,
  SESSION_TOKEN STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);
-- Session table for signer sessions and ephemeral tokens, per session lifecycle design @3 @31

