USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_ATTEMPTS ( ATTEMPT_ID STRING PRIMARY KEY, Q_ID STRING, ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE_CODE INT, RESPONSE_BODY VARIANT );

