-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ASSEMBLIES (
  ASSEMBLY_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  STATUS STRING,
  METADATA VARIANT,
  RENDERED_URL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

