-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_THREAT_INTEL (
  INTEL_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  SOURCE STRING,
  RISK_LEVEL STRING,
  DETAILS VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

