USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  DOCUMENT_ID STRING,
  SIGNER_ID STRING,
  ACCOUNT_ID STRING,
  EVENT_TYPE STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Event stream table for incoming webhook events and local events (ingest target) @3 @18 @31

