USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_WHITELIST ( WL_ID STRING PRIMARY KEY, CLIENT_ID STRING, ALLOWED_PREFIXES ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

