-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_SCHEDULES (
  SCHEDULE_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  CRON_EXPR STRING,
  RETENTION_DAYS INT,
  LAST_RUN_AT TIMESTAMP_LTZ,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

