USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_API_ACCESS_LOG ( LOG_ID STRING PRIMARY KEY, USER_REF STRING, ENDPOINT STRING, METHOD STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

