-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RECONCILE (
  RECON_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  EXPECTED_COUNT INT,
  ACTUAL_COUNT INT,
  STATUS STRING,
  LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

