-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  ADMIN_USER STRING,
  ACTION STRING,
  TARGET STRING,
  DETAILS VARIANT,
  AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

