USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, REQ_ID STRING, ADMIN_USER STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

