USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEATURE_FLAG_HISTORY ( HIST_ID STRING PRIMARY KEY, FLAG_ID STRING, CHANGE_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

