-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_USAGE_LEDGER (
  LEDGER_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  FEATURE_NAME STRING,
  USAGE_COUNT NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

