-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_PROFILES (
  PROFILE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  FEATURE_NAME STRING,
  LIMIT_VALUE NUMBER,
  WINDOW STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

