USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_HEALTH_SUMMARY AS
SELECT CHECK_NAME, STATUS, MAX(CHECKED_AT) AS LAST_CHECK FROM DOCGEN.HEALTH_CHECKS GROUP BY CHECK_NAME; Generated per Snowflake E-Sign patterns. @134 @31

