USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_NOTIFICATION_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGETS ARRAY, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

