USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_BOUNCE_INDEX ( BOUNCE_ID STRING PRIMARY KEY, EMAIL STRING, BOUNCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );

