-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VECTOR_STORE (
  VECTOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  EMBEDDING VECTOR,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

