-- Emitted per Snowflake_E-Sign_V1.2 patterns and registration order. @1 @3
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOTS (
  SNAPSHOT_ID STRING PRIMARY KEY,
  INDEX_NAME STRING,
  S3_LOCATION STRING,
  SHARD_META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

