USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_OPT_OUTS ( OPT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CHANNEL STRING, OPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

