USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_BUNDLE (
  BUNDLE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  BUNDLE_URL STRING,
  MANIFEST VARIANT,
  PROVENANCE_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Evidence bundle manifest table for CompliancePacket records and archival manifests @3 @4 @99

