USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_RETENTION ( RET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_ID STRING, RETENTION_DAYS INT, SCHEDULED_PURGE_AT TIMESTAMP_LTZ );

