USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_HISTORY_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_ID STRING, EVENT_TYPE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

