USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHECKSUM_REGISTRY ( CHK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_ID STRING, CHECKSUM STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

