USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE (
  USAGE_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  USAGE_COUNT INT,
  LAST_USED_AT TIMESTAMP_LTZ
); Generated per Snowflake E-Sign patterns. @31 @24

