USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CERT_PEM CLOB,
  CERT_FINGERPRINT STRING,
  ISSUER VARIANT,
  NOT_BEFORE TIMESTAMP_LTZ,
  NOT_AFTER TIMESTAMP_LTZ,
  STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Stores certificate chains/metadata referenced by evidence bundles and verifications @3 @52

