USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_HASH_CATALOG ( HASH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_ID STRING, HASH STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

