USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_SNAPSHOT_MANIFEST_VERSIONS ( VERSION_ID STRING PRIMARY KEY, SNAPSHOT_ID STRING, VERSION_NUMBER INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

