USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SNAPSHOT_RETENTION_POLICIES ( POLICY_ID STRING PRIMARY KEY, SNAPSHOT_ID STRING, RETENTION_DAYS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

