USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_METRICS ( METRIC_ID STRING PRIMARY KEY, WORKER_ID STRING, JOB_COUNT NUMBER, LAST_HEARTBEAT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

