USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_STORAGE_QUOTA ( QUOTA_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ALLOCATED_BYTES NUMBER, USED_BYTES NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

