USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INDEX_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, PROVIDER STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

