USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_RESTORE_JOBS ( JOB_ID STRING PRIMARY KEY, SOURCE_LOCATION STRING, TARGET_REF STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

