USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_RESPONSES (
  OCSP_ID STRING PRIMARY KEY,
  CERT_FINGERPRINT STRING,
  OCSP_STATUS STRING,
  OCSP_RAW VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- OCSP/CRL snapshot store used by verification procedures and evidence capture @3 @51

