USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SATISFACTION_METRICS ( MET_ID STRING PRIMARY KEY, SURVEY_ID STRING, METRICS VARIANT, AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

