USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_COMPLIANCE_FINDINGS ( FIND_ID STRING PRIMARY KEY, RUN_ID STRING, ITEM_ID STRING, FINDING JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

