USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRIEVAL_TELEMETRY ( TELE_ID STRING PRIMARY KEY, QUERY_HASH STRING, LATENCY_MS NUMBER, RESULT_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

