USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_RISK_HISTORY ( HIST_ID STRING PRIMARY KEY, POLICY_ID STRING, SCORE NUMBER, REASON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

