USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_AUDIT (
  PAUDIT_ID STRING PRIMARY KEY,
  VERSION_ID STRING,
  CHANGED_BY STRING,
  CHANGES VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @23 @31

