USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_NOTICES ( NOTICE_ID STRING PRIMARY KEY, AUDIT_ID STRING, NOTICE_TEXT CLOB, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

