USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, USAGE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

