USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_LINES ( LINE_ID STRING PRIMARY KEY, INVOICE_ID STRING, DESCRIPTION STRING, AMOUNT NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

