USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_CONTROL_AUDIT (
  ACA_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  ACTION STRING,
  RESOURCE STRING,
  AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); Generated per Snowflake E-Sign patterns. @31 @24

