USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_DASHBOARD_LAYOUTS ( LAYOUT_ID STRING PRIMARY KEY, NAME STRING, WIDGETS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

