USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_REQUEST_LOG ( REQ_ID STRING PRIMARY KEY, OP STRING, PAYLOAD VARIANT, RESPONSE VARIANT, STATUS STRING, CALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

