USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_JOBS ( JOB_ID STRING PRIMARY KEY, CERT_ID STRING, STATUS STRING DEFAULT 'PENDING', LAST_POLLED_AT TIMESTAMP_LTZ, RETRY_COUNT INT DEFAULT 0 );

