USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_BACKUP_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, CHECKSUM STRING, BACKED_UP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

