USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_NODES (
  NODE_ID STRING PRIMARY KEY,
  NODE_TYPE STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Node store for provenance graph entries referenced by edges table @19 @3

