USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL (
  ONCALL_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  SHIFT_START TIMESTAMP_LTZ,
  SHIFT_END TIMESTAMP_LTZ
); Generated per Snowflake E-Sign patterns. @31 @24

