USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_QUEUE ( Q_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PRIORITY INT DEFAULT 0, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

