USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIALS (
  CRED_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  CRED_TYPE STRING,
  CRED_META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Provider credential storage for registered e-sign providers (meta only; secrets in vault) @31 @244

