USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_AUDIT ( REPLAY_ID STRING PRIMARY KEY, SESSION_ID STRING, PAYLOAD VARIANT, REPLAYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

