USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_THREAT_SCORES ( SCORE_ID STRING PRIMARY KEY, SESSION_ID STRING, SCORE NUMBER, REASONS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

