USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTITENANT_CONFIG ( CONFIG_ID STRING PRIMARY KEY, TENANT_ID STRING, CONFIG_KEY STRING, CONFIG_VALUE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

