USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_RATE_USAGE ( USAGE_ID STRING PRIMARY KEY, TENANT_ID STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, COUNT NUMBER );

