USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_QUOTA_EVENTS ( EVENT_ID STRING PRIMARY KEY, TENANT_ID STRING, QUOTA_KEY STRING, CHANGE NUMBER, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

