USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONFIG (
  PROVIDER_ID STRING PRIMARY KEY,
  NAME STRING,
  CONFIG VARIANT,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Provider configuration and feature toggles for provider selection and failover @31 @183

