USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_FEATURE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE_NAME STRING, LIMIT_VALUE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

