USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRIAL_ACCOUNT_REGISTRY ( TRIAL_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENDS_AT TIMESTAMP_LTZ );

