USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_PROMOTIONS ( PROMO_ID STRING PRIMARY KEY, NAME STRING, RULES VARIANT, ACTIVE BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

