USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_PROVIDER_CALLBACKS ( CALLBACK_ID STRING PRIMARY KEY, PROVIDER STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), HANDLED BOOLEAN DEFAULT FALSE );

