USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_SUSPEND_JOBS ( JOB_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, REASON STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ );

