USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACCESS_REVIEW ( REVIEW_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, RESULT STRING, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
