USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_AUDIT_TRAIL (
  AUDIT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  DETAIL VARIANT,
  AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Immutable audit trail entries for signature lifecycle events and operator actions @90 @113

