USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EDGE_CACHE_INDEX ( EDGE_ID STRING PRIMARY KEY, FROM_REF STRING, TO_REF STRING, META VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
