USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_CHECKSUM_INDEX ( CHK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHECKSUM STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
