USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_METHODS ( METHOD_ID STRING PRIMARY KEY, SIGNER_ID STRING, METHOD_TYPE STRING, META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
