USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_STATE_HISTORY ( HIST_ID STRING PRIMARY KEY, SESSION_ID STRING, STATE_FROM STRING, STATE_TO STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
