USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INDEX_ALIASES ( ALIAS_ID STRING PRIMARY KEY, ALIAS_NAME STRING, TARGET_INDEX STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
