USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_INTEGRATION_TOKENS ( TOKEN_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, TOKEN_HASH STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
