USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_FUNCTION_USAGE ( USAGE_ID STRING PRIMARY KEY, EF_ID STRING, CALLER STRING, PAYLOAD VARIANT, CALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
