USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_BACKOFF_STATE ( STATE_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, NEXT_TRY_AT TIMESTAMP_LTZ, ATTEMPTS INT, LAST_ERROR VARIANT );
