USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  NAME STRING,
  VALUE NUMBER,
  TAGS VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Operational telemetry sink for signature module KPIs and SLOs @30 @71

