USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_LEVEL_BREACH_LOG ( LOG_ID STRING PRIMARY KEY, SCOPE STRING, BREACH_DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
