USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  ACTION STRING,
  RESOURCE STRING,
  SOURCE_IP STRING,
  USER_AGENT STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Access logging for security and audit purposes @250 @316

