USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_RUNBOOK_EXECUTIONS ( EXEC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TRIGGER_REF STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );
