USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_FEEDBACK_SUMMARIES ( SUM_ID STRING PRIMARY KEY, OPERATOR_REF STRING, SUMMARY JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
