USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SATISFACTION_SURVEYS ( SURV_ID STRING PRIMARY KEY, OPERATOR_REF STRING, RESPONSES VARIANT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
