USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_COACHING_LOGS ( LOG_ID STRING PRIMARY KEY, OPERATOR_REF STRING, COACHING_NOTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
