USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_QUALITY_AUDITS ( AUDIT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, SCORE NUMBER, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
