USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_LOGS ( LOG_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR_REF STRING, SEVERITY STRING, MESSAGE CLOB, LOG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

