-- Notification templates for email/SMS channels used by notification workers. @31 @24 @52
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_NOTIFICATION_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  CHANNEL STRING,
  SUBJECT STRING,
  BODY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

