USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_INSTANCES ( INSTANCE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TRIGGER_REF STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

