USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPOUND_EVENT_INDEX ( IDX_ID STRING PRIMARY KEY, EVENT_KEYS VARIANT, ENTITY_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

