-- Registration table for webhook consumer metadata (providers, retries, last_seen). @31 @24 @52
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_CONSUMERS (
  CONSUMER_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  LAST_RECEIVED_AT TIMESTAMP_LTZ,
  FAILURE_COUNT INT DEFAULT 0,
  CONFIG VARIANT
);

