USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TAG_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TAG STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

