-- Aggregation table for daily signature event metrics for billing/analytics. @31 @24 @52
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_METRICS (
  METRIC_DATE DATE,
  ACCOUNT_ID STRING,
  EVENT_TYPE STRING,
  COUNT_EVENTS NUMBER,
  PRIMARY KEY (METRIC_DATE, ACCOUNT_ID, EVENT_TYPE)
);

