USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_HISTORY ( HIST_ID STRING PRIMARY KEY, POLICY_ID STRING, CHANGE_JSON VARIANT, APPLIED_BY STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

