USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_INTEGRATION_INDEX ( IDX_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, CONFIG VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

