-- Table to record threat intelligence or fraud flags per signer for review by admin. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNER_THREAT_INTEL (
  INTEL_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  SOURCE STRING,
  RISK_LEVEL STRING,
  DETAILS VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

