-- Registered devices for signer binding and device fingerprint provenance. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_REGISTRY (
  DEVICE_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  DEVICE_META VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

