-- Stores email/pdf templates used in signing notifications and evidence packaging. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  TEMPLATE_NAME STRING,
  TEMPLATE_BODY CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

