USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_JOBS (
  JOB_ID STRING PRIMARY KEY,
  OBJECT_NAME STRING,
  STATUS STRING DEFAULT 'PENDING',
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT
);
-- Synchronization job tracking for external syncs and admin actions @225 @31

