-- Tracks document assembly runs used to render preview PDFs prior to signing. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ASSEMBLY_JOBS (
  ASSEMBLY_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  STATUS STRING,
  RENDERED_URL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

