-- Per-account signing policy definitions (required_auth_level, allowed_methods, retention). @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNING_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  REQUIRED_AUTH_LEVEL STRING,
  ALLOWED_METHODS ARRAY,
  RETENTION_DAYS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

