USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSS_TENANT_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, SCOPE VARIANT, ENTRIES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

