-- Table to reference stored signed documents (links to stage or external storage). @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNED_DOCUMENT_STORE (
  DOCSTORE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNED_URL STRING,
  STORAGE_META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

