-- Table for arbitrary flags/tags applied to requests for policy or analytics use. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_FLAGS (
  FLAG_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  FLAG_KEY STRING,
  FLAG_VALUE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

