USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_BIAS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MODEL_ID STRING, CHECK_JSON VARIANT, RESULT VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

