USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_EXPLAINABILITY_LOGS ( LOG_ID STRING PRIMARY KEY, MODEL_ID STRING, REQUEST_JSON VARIANT, EXPLANATION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

