USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_PERFORMANCE_BASELINES ( BASE_ID STRING PRIMARY KEY, MODEL_ID STRING, METRICS VARIANT, SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

