-- Health/status table for provider endpoints for failover and alerts. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_PROVIDER_STATUS (
  PROVIDER_ID STRING PRIMARY KEY,
  LAST_HEALTH_AT TIMESTAMP_LTZ,
  STATUS STRING,
  DETAILS VARIANT
);

