USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_ENDPOINT_USAGE ( USAGE_ID STRING PRIMARY KEY, ENDPOINT_ID STRING, CALLER STRING, LATENCY_MS NUMBER, TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

