-- Backfill job registry to track long-running reconciliation or migration jobs. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_BACKFILL_JOBS (
  JOB_ID STRING PRIMARY KEY,
  JOB_TYPE STRING,
  STATUS STRING,
  PROGRESS VARIANT,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);

