-- Audit log for access to signature artifacts (who accessed evidence, downloads). @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  ACTION STRING,
  RESOURCE STRING,
  SOURCE_IP STRING,
  USER_AGENT STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

