USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_KEY STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

