USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_AUDIT_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  OBJECT_REF STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Queue table for async sync operations and retries between systems @24 @36

