-- Versioning for signature templates to allow rollback and audit of template changes. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TEMPLATE_VERSIONS (
  VERSION_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  VERSION_NUMBER INT,
  BODY CLOB,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);

