USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_ATTENDANCE ( ATT_ID STRING PRIMARY KEY, SHIFT_ID STRING, OPERATOR_REF STRING, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

