USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_OPERATION_LOGS ( LOG_ID STRING PRIMARY KEY, OP_NAME STRING, REQUEST_JSON VARIANT, RESPONSE_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

