USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_PUBLICATION_JOBS ( JOB_ID STRING PRIMARY KEY, ANCHOR_ID STRING, STATUS STRING, ATTEMPTS INT DEFAULT 0, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

