-- Table to record generated alerts (OCSP failures, mismatches) for operator workflows. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  ALERT_TYPE STRING,
  ENTITY_REF STRING,
  DETAILS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED BOOLEAN DEFAULT FALSE
);

