-- Operator notes attached to requests for triage and audit. @31 @24 @52
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPERATOR_NOTES (
  NOTE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  OPERATOR STRING,
  NOTE TEXT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

