USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TARGET_LOCATION STRING, STATUS STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

