USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, SIGNER_ID STRING, ACTION STRING, DETAILS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

