USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_EVENT_INDEX ( FRAUD_ID STRING PRIMARY KEY, SIGNER_ID STRING, EVENT_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

