USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PROVENANCE_EDGES ( EDGE_ID STRING PRIMARY KEY, FROM_REF STRING, TO_REF STRING, RELATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

