-- Record explicit signer consents and terms accepted at time of signature for legal audit trails. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CONSENTS (
  CONSENT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  CONSENT_TEXT CLOB,
  CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

