USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTACHMENT_STORAGE_INDEX ( ATT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, SIZE_BYTES NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

