USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINT_STORE ( FP_ID STRING PRIMARY KEY, SIGNER_ID STRING, DEVICE_META VARIANT, FIRST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

