-- Lightweight journal for ephemeral cookies/session tokens used during signer flows for forensic replay. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_COOKIE_JOURNAL (
  COOKIE_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  COOKIE_PAYLOAD VARIANT,
  ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

