USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_ALERTS ( ALERT_ID STRING PRIMARY KEY, ENTITY_REF STRING, RISK_SCORE NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

