-- Historical log of signer session state transitions for audit and replay. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_HISTORY (
  HISTORY_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  OLD_STATUS STRING,
  NEW_STATUS STRING,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

