USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MITIGATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ALERT_ID STRING, ACTION_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

