-- Audit table for changes to signing policy templates and enforcement configuration. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_POLICY_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  CHANGED_BY STRING,
  CHANGE_PAYLOAD VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

