USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_JOBS (
  JOB_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ATTEMPT INT DEFAULT 0,
  STATUS STRING DEFAULT 'PENDING',
  LAST_ERROR VARIANT,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Render job queue to coordinate async PDF/HTML generation (assembly -> render) @36 @104

