-- One-time download tokens for signed documents to support secure evidence retrieval. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_DOWNLOAD_TOKENS (
  TOKEN_ID STRING PRIMARY KEY,
  DOCSTORE_ID STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

