USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_EVIDENCE_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, EVID_ID STRING, LOCATION STRING, STATUS STRING, EXPORTED_AT TIMESTAMP_LTZ );

