-- Mapping table to support delegated signing across tenant boundaries when allowed by policies. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CROSS_TENANT_LINKS (
  LINK_ID STRING PRIMARY KEY,
  SOURCE_ACCOUNT_ID STRING,
  TARGET_ACCOUNT_ID STRING,
  POLICY_REF STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

