-- Metadata for templates (tags, owner, scopes) to support discovery and governance. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TEMPLATE_METADATA (
  TEMPLATE_ID STRING PRIMARY KEY,
  OWNER_ACCOUNT STRING,
  TAGS ARRAY,
  SCOPE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

