USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_STORE ( CONSENT_ID STRING PRIMARY KEY, USER_REF STRING, CONSENT_JSON VARIANT, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

