USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_REVOCATION_LOG ( LOG_ID STRING PRIMARY KEY, CONSENT_ID STRING, REVOKED_BY STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB ); @31 @24

