-- Log of template usage (who used which template, when) for billing and audit correlations. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TEMPLATE_USAGE_LOG (
  LOG_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONTEXT VARIANT
);

