USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERED_DOCUMENTS (
  DOCUMENT_ID STRING PRIMARY KEY,
  ASSEMBLY_RUN_ID STRING,
  RENDERED_URL STRING,
  MIME_TYPE STRING DEFAULT 'application/pdf',
  SIZE_BYTES NUMBER,
  HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Stores final rendered document metadata and hash for provenance @88 @100

