-- History of retries for batch exports and bulk operations for operational observability. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_RETRY_HISTORY (
  HISTORY_ID STRING PRIMARY KEY,
  EXPORT_ID STRING,
  ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING,
  DETAILS VARIANT
);

