USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RETAINMENT_POLICIES ( POLICY_ID STRING PRIMARY KEY, NAME STRING, RETENTION_DAYS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

