-- Store checksums for artifacts in evidence bundles to enable integrity verification. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHECKSUMS (
  CHECKSUM_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  FILENAME STRING,
  CHECKSUM STRING,
  ALGO STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

