USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_LOGS ( CONSENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

