-- API key / integration-specific rate limits to protect provider endpoints and enforce quotas. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_INTEGRATION_RATE_LIMITS (
  LIMIT_ID STRING PRIMARY KEY,
  INTEGRATION_KEY_HASH STRING,
  LIMIT_PER_MINUTE INT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

