-- Per-account retention policy definitions that drive purge/enforce retention procedures. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  TARGET_TABLE STRING,
  RETENTION_DAYS INT,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

