USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_REQUEST_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, REQ_ID STRING, TENANT_ID STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

