-- Table to store lineage events linking source system identifiers to Snowflake records for compliance and traceability. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_LINEAGE_EVENTS (
  LINEAGE_ID STRING PRIMARY KEY,
  SOURCE_SYSTEM STRING,
  SOURCE_ID STRING,
  TARGET_TABLE STRING,
  TARGET_ID STRING,
  CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

