USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSSBORDER_TRANSFER_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, TARGET_COUNTRY STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

