-- Scheduled integrity checks configuration for verifying bundle checksums and anchors. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRITY_CHECKS_CONFIG (
  CHECK_ID STRING PRIMARY KEY,
  TARGET_BUNDLE_ID STRING,
  SCHEDULE_CRON STRING,
  LAST_RUN_AT TIMESTAMP_LTZ
);

