USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_REGISTRY ( INDEX_ID STRING PRIMARY KEY, SHARD_JSON VARIANT, LOCATION STRING, STATUS STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

