USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_QUERY_METRICS ( MET_ID STRING PRIMARY KEY, INDEX_ID STRING, QPS NUMBER, LATENCY_P95 NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

