USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INSPECTOR_CHECKLISTS (
  CHECKLIST_ID STRING PRIMARY KEY,
  NAME STRING,
  STEPS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Operator/inspector checklist templates for incident response and audits @31 @14

