-- SLA measurement store to capture operation latencies and availability metrics for signing flows. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  METRIC_NAME STRING,
  METRIC_VALUE VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

