USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DUE_DILIGENCE_RECORDS ( DUE_ID STRING PRIMARY KEY, PROVIDER STRING, RECORD JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

