USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARD_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, INDEX_ID STRING, SHARD_LIST VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

