USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARD_HEALTH_INDEX ( HEALTH_ID STRING PRIMARY KEY, SHARD_REF STRING, STATUS STRING, LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), METRICS VARIANT ); @31 @24

