-- Table to store runbook links and operator playbooks per alert type for on-call guidance. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_RUNBOOKS (
  RUNBOOK_ID STRING PRIMARY KEY,
  ALERT_TYPE STRING,
  RUNBOOK_URL STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

