USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, CONSENT_ID STRING, NOTICE JSON, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

