-- Definition of escalation policy steps (notify, page, auto-assign) for automated alert handling. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  ALERT_TYPE STRING,
  STEPS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

