-- Registry of objects used by CI smoke tests to allow safe teardown and validation. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CI_ARTIFACTS_REGISTRY (
  ARTIFACT_ID STRING PRIMARY KEY,
  NAME STRING,
  DESCRIPTION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

