USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_TAX_RULE_REGISTRY ( TAX_ID STRING PRIMARY KEY, NAME STRING, RULE_JSON VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ ); @31 @24

