USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_USAGE_ANOMALIES ( ANOMALY_ID STRING PRIMARY KEY, TENANT_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

