-- Store rate card events specific to signature operations for billing attribution (per-template, per-account). @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_RATECARD_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  TEMPLATE_ID STRING,
  EVENT_TYPE STRING,
  EVENT_VALUE VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

