USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_PAYMENT_METHODS ( PM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METHOD_JSON VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

