-- Table to store pre-sign automated checks and their outcomes (e.g., identity verification results). @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRE_SIGN_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  CHECK_TYPE STRING,
  RESULT STRING,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

