USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_NOTIFICATION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, CHANNEL STRING, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

