USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_NOTIFICATION_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGETS VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31 @24

