-- Table to store device-based trust scores computed from fingerprinting and telemetry. @1 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_TRUST_SCORES (
  DEVICE_ID STRING PRIMARY KEY,
  TRUST_SCORE FLOAT,
  LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

