USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_EDGES_V2 (
  EDGE_ID STRING PRIMARY KEY,
  FROM_NODE STRING,
  TO_NODE STRING,
  RELATION STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Extended provenance edges table for larger audit graphs @19 @3

