USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHARGEBACK_ADJUSTMENTS ( ADJ_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT NUMBER, REASON STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

