USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
INSERT INTO DOCGEN.ACCOUNTS (ACCOUNT_ID, NAME) VALUES ('acct-1','Demo Account');
INSERT INTO DOCGEN.SIGNERS (SIGNER_ID, REQUEST_ID, ACCOUNT_ID, SIGNER_EMAIL, SIGNER_NAME) VALUES ('signer-1','req-0001','acct-1','alice@example.com','Alice');

