-- Sequence-like UUID helper table for deterministic surrogate ID generation in SQL-only flows @1 @6.
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UUID_COUNTER ( COUNTER_NAME STRING PRIMARY KEY, COUNTER BIGINT DEFAULT 0 );
CREATE OR REPLACE PROCEDURE DOCGEN.NEXT_UUID(counter_name STRING) RETURNS STRING LANGUAGE SQL AS $$ UPDATE DOCGEN.UUID_COUNTER SET COUNTER = COALESCE(COUNTER,0) + 1 WHERE COUNTER_NAME = :counter_name; RETURN CONCAT(counter_name,'-',CURRENT_TIMESTAMP(),'-',LPAD(COALESCE((SELECT COUNTER FROM DOCGEN.UUID_COUNTER WHERE COUNTER_NAME=:counter_name),0)::STRING,10,'0')); $$;

