USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_REPORT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REPORT_REF STRING, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

