USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLECTOR_ACCOUNT_BALANCES ( BAL_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, BALANCE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

