USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_RECONCILE_RUNS ( RUN_ID STRING PRIMARY KEY, SCOPE VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31 @24

