USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDIT_LIMIT_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @31 @24

