USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, CENTER_ID STRING, AMOUNT NUMBER, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

