USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_DISPUTE_INDEX ( DISPUTE_ID STRING PRIMARY KEY, PROVIDER_REF STRING, STATUS STRING, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

