-- Backfill queue for reprocessing old events during migrations and schema changes @1 @6.
CREATE OR REPLACE TABLE DOCGEN.EVENTS_BACKFILL_QUEUE ( BACKFILL_ID STRING PRIMARY KEY, REQUEST_ID STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

