USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXCHANGE_RATE_FEEDS ( FEED_ID STRING PRIMARY KEY, CURRENCY_PAIR STRING, RATE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

