USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CURRENCY_CONVERSION_LOGS ( LOG_ID STRING PRIMARY KEY, FROM_CURRENCY STRING, TO_CURRENCY STRING, RATE NUMBER, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

