CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_FILTERS ( FILTER_ID STRING PRIMARY KEY, PROVIDER STRING, PATH_PATTERN STRING, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

