USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CANCELLATION_REQUEST_QUEUE ( REQ_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, REASON CLOB, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

