USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_DELIVERY_METHODS ( METHOD_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METHOD_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

