USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_CYCLE_SETTINGS ( SETTING_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CYCLE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

