CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RENDER_LOGS ( RENDER_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ASSEMBLY_ID STRING, RENDERED_URL STRING, STATUS STRING, LOG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

