CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_POLICY ( POLICY_ID STRING PRIMARY KEY, PROVIDER STRING, MAX_ATTEMPTS INT, INITIAL_DELAY_SECONDS INT, BACKOFF_MULTIPLIER FLOAT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

