USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_FINANCIAL_SUMMARY ( SUMMARY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SUMMARY VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

