-- Audit for changes to provider credentials or endpoints for compliance tracking @1 @6.
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIALS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHANGED_BY STRING, CHANGE_PAYLOAD VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

