USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_BILLING_CYCLES ( CYCLE_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, STATUS STRING );

