USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_BILLING_EVENTS ( EVENT_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, EVENT_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

