-- Alerting policy configuration used by escalation/apply logic to map thresholds to actions @1 @6.
CREATE OR REPLACE TABLE DOCGEN.ALERT_POLICY_CONFIG ( POLICY_ID STRING PRIMARY KEY, ALERT_TYPE STRING, THRESHOLD VARIANT, ACTIONS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

