USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ADJUSTMENT_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, ADJ_ID STRING, APPROVED_BY STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

