USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VENDOR_CONTRACT_REGISTRY ( CONTRACT_ID STRING PRIMARY KEY, VENDOR STRING, TERMS VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ, EXPIRES_AT TIMESTAMP_LTZ );

