-- Generic telemetry event store for operational tracing and observability @1 @6.
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_EVENTS ( TELE_ID STRING PRIMARY KEY, SOURCE STRING, EVENT_NAME STRING, PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

