-- Provider-side rate limit config to avoid overloading third-party signing providers @1 @6.
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, LIMIT_PER_MINUTE INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

