-- Collect metrics on provider latency/error rates for routing and canary decisions @1 @6.
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_METRICS ( METRIC_ID STRING PRIMARY KEY, PROVIDER_ID STRING, METRIC_NAME STRING, METRIC_VALUE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

