USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_INDEX ( VID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_NUMBER INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

