USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUBSCRIPTIONS (
  SUB_ID STRING PRIMARY KEY,
  ADMIN_USER STRING,
  ALERT_RULE_ID STRING,
  CHANNEL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Who should be notified when alerts fire for signature module issues @23 @31

