USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_ACTIVITY_TIMELINE ( ATL_ID STRING PRIMARY KEY, SIGNER_ID STRING, ACTIVITY_TYPE STRING, PAYLOAD VARIANT, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

