CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_ANNOTATIONS ( ANNOTATION_ID STRING PRIMARY KEY, ENTITY_REF STRING, ANNOTATION_TEXT STRING, CREATED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

