USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOGIN_ATTEMPT_METRICS ( MET_ID STRING PRIMARY KEY, SUBJECT_REF STRING, RESULT STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

