USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_IDLE_TIMEOUT_JOBS ( JOB_ID STRING PRIMARY KEY, SESSION_ID STRING, STATUS STRING, SCHEDULED_AT TIMESTAMP_LTZ, EXECUTED_AT TIMESTAMP_LTZ );

