USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ESCALATION_NOTIFS (
  NOTIF_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  LEVEL STRING,
  MESSAGE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Admin escalation notifications for serious incidents in signature flows @10 @29

