USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHN_METHOD_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHODS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

