USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_ENROLLMENT_RECORDS ( ENR_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHOD_JSON VARIANT, ENROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

