USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_CHALLENGE_LOGS ( LOG_ID STRING PRIMARY KEY, ENR_ID STRING, CHALLENGE JSON, RESULT STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

