-- Queue table for sync tasks between Salesforce Admin or other control planes and Snowflake @1 @6.
CREATE OR REPLACE TABLE DOCGEN.SYNC_QUEUE ( SYNC_ID STRING PRIMARY KEY, ENTITY_TYPE STRING, ENTITY_ID STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

