USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_AUDIT_V2 (
  AUDIT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CONSENT_JSON VARIANT,
  ACTION STRING,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Extended consent audit table for more granular consent records @11 @31

