USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_INCIDENT_CORRELATION ( CORR_ID STRING PRIMARY KEY, ALERT_ID STRING, INCIDENT_ID STRING, CORRELATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

