USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PRIVILEGE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, PRIVILEGE STRING, ACTION STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

