USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RBAC_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, REQUESTOR STRING, CHANGE_JSON VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

