USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_DELEGATION_LOGS ( LOG_ID STRING PRIMARY KEY, ROLE_ID STRING, DELEGATED_TO STRING, DELEGATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

