USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_SCOPES ( SCOPE_ID STRING PRIMARY KEY, CLIENT_ID STRING, SCOPE_JSON VARIANT, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

