USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_API_KEYS (
  KEY_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  KEY_HASH STRING,
  SCOPE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Show-once integration key hash table pattern (store only KDF/hash) for admin integrations @36 @66

