USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_VENDOR_ORIGIN ( ORIG_ID STRING PRIMARY KEY, CLAUSE_ID STRING, VENDOR STRING, METADATA VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

