USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VALIDATION_JOBS (
  JOB_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  VALIDATION_RULES VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Document validation job queue for running automated validation rules on artifacts @16 @71

