INSERT INTO DOCGEN.SIGNATURE_RATECARD_EVENTS (EVENT_ID, ACCOUNT_ID, TEMPLATE_ID, EVENT_TYPE, EVENT_VALUE) VALUES (UUID_STRING(),'acct-1','tmpl-1','SIGNATURE_COMPLETED',PARSE_JSON('{"qty":1,"price":0.5}'));

