USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_FEEDBACK_ANALYTICS ( ANALYTIC_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METRICS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

