USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_HEATMAP_TILES ( TILE_ID STRING PRIMARY KEY, SCOPE VARIANT, DATA VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

