USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_REQUESTS (
  REQUEST_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  REQUESTED_BY STRING,
  REQUEST_JSON VARIANT,
  STATUS STRING DEFAULT 'OPEN',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Policy change request queue to support approvals & activation audits @25 @36

