USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_LABELS (
  LABEL_ID STRING PRIMARY KEY,
  EVENT_ID STRING,
  LABEL STRING,
  TAGGED_BY STRING,
  TAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

