USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_HEALTH_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SCOPE VARIANT, METRICS VARIANT, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

