USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_ATTRIBUTES (
  ATTR_ID STRING PRIMARY KEY,
  EVENT_ID STRING,
  ATTR_KEY STRING,
  ATTR_VALUE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

