USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ATTACHMENTS (
  ATTACH_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  FILENAME STRING,
  FILE_URL STRING,
  META VARIANT,
  UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

