USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QES_SIGNATURE_REQUESTS (
  QES_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  ACCOUNT_ID STRING,
  QES_STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

