USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLUSTER_AUTOSCALE_RUNS ( RUN_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION JSON, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

