USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ESTIMATION_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCOPE VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

