USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTARY_REGISTRY (
  NOTARY_ID STRING PRIMARY KEY,
  NAME STRING,
  LICENSE_INFO VARIANT,
  ISSUED_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ
);

