USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSE_PLAYBOOKS (
  PLAYBOOK_ID STRING PRIMARY KEY,
  NAME STRING,
  STEPS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Playbooks for operational responders to follow during incidents affecting signatures @12 @28

