USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_LOG (
  CONSENT_LOG_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  TC_ID STRING,
  VERSION_NUMBER INT,
  CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

