USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PHONE_VERIFICATIONS (
  VERIF_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  PHONE_NUMBER STRING,
  VERIF_CODE STRING,
  VERIFIED_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ
);

