USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_GRANTS ( GRANT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, GRANT_JSON VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

