USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARING_LINK_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, LINK_ID STRING, SUBJECT_REF STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SOURCE_IP STRING );

