USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_REMINDERS (
  REMINDER_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SCHEDULED_AT TIMESTAMP_LTZ,
  CHANNEL STRING,
  STATUS STRING DEFAULT 'PENDING'
);

