USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.AUDIT_SUMMARY_MV AS
SELECT
  ACCOUNT_ID,
  COUNT(*) AS TOTAL_SIGNATURES,
  MAX(CREATED_AT) AS LAST_ACTIVITY
FROM DOCGEN.SIGNATURE_EVENTS
GROUP BY ACCOUNT_ID;
-- Materialized view for admin KPIs and audit summary reports @27 @31

