USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOCALIZATION_COVERAGE_REPORTS ( REPORT_ID STRING PRIMARY KEY, LOCALE STRING, COVERAGE JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

