USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_KEY_ROTATIONS (
  ROT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

