USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINAL_TRANCHE_MARKER_08 ( MARKER_ID STRING PRIMARY KEY, TRANCHE_ID STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

