USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ENDPOINTS (
  ENDPOINT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  URL STRING,
  METHOD STRING,
  LAST_CHECK TIMESTAMP_LTZ
);

