USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LOCK_HISTORY ( LOCK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCKED_BY STRING, LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), UNLOCKED_AT TIMESTAMP_LTZ );

