USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_RULES (
  RULE_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  FALLBACK_PROVIDER_ID STRING,
  CONDITION VARIANT
);

