USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.DOCUMENT_SIGNATURE_SUMMARY_MV AS
SELECT DOCUMENT_ID, COUNT(*) AS SIGNATURE_COUNT, MAX(EVENT_TS) AS LAST_SIGNED_AT
FROM DOCGEN.SIGNATURE_EVENTS
GROUP BY DOCUMENT_ID;
-- MV to accelerate document signature dashboards and queries @28 @71

