USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_MODEL_REGISTRY (
  MODEL_ID STRING PRIMARY KEY,
  MODEL_NAME STRING,
  VERSION STRING,
  DEPLOYED BOOLEAN,
  METADATA VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

