USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_FEEDBACK_LOGS ( LOG_ID STRING PRIMARY KEY, CLAUSE_ID STRING, USER_REF STRING, FEEDBACK CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

