USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MATERIALIZED_VIEWS_REGISTRY (
  MV_ID STRING PRIMARY KEY,
  NAME STRING,
  REF_QUERY STRING,
  LAST_REFRESH TIMESTAMP_LTZ
);

