USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  NAME STRING,
  STATUS STRING,
  DETAILS VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Health check store for monitoring external functions (OCSP/HSM/FAISS) and internal tasks @147 @31

