USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  JURISDICTION STRING,
  TEXT_CLOB CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

