USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENFORCEMENT_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  REQUEST_ID STRING,
  OUTCOME STRING,
  DETAILS VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

