USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_BILLING_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  AMOUNT NUMBER,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

