USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_THROTTLE_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, EVENT_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

