USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_AUDIT_QUEUE_V2 (
  QUEUE_ID STRING PRIMARY KEY,
  OBJECT_REF STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RETRY_COUNT INT DEFAULT 0
);
-- Retry-capable sync audit queue for robust cross-system reconciliation @24 @31

