USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIAL_ROTATION ( ROT_ID STRING PRIMARY KEY, PROVIDER_ID STRING,LAST_ROTATED_AT TIMESTAMP_LTZ, NEXT_ROTATION_AT TIMESTAMP_LTZ, META VARIANT );

