USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ENDPOINTS_HISTORY ( PID STRING PRIMARY KEY, PROVIDER_ID STRING, URL STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGED_BY STRING, NOTES VARIANT
);

