USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS ( SESSION_ID STRING PRIMARY KEY, REQUEST_ID STRING, SIGNER_ID STRING, IP_ADDRESS STRING, USER_AGENT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_ACTIVITY_AT TIMESTAMP_LTZ );

