USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ANNOUNCEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, ANNOUNCEMENT_ID STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ACTOR STRING, DETAILS VARIANT );

