USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATIONS ( VERIF_ID STRING PRIMARY KEY, BUNDLE_ID STRING, REQUEST_ID STRING, SIGNER_ID STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT STRING, DETAILS VARIANT );

