USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEATURE_ROLLBACKS ( ROLLBACK_ID STRING PRIMARY KEY, FEATURE_ID STRING, REVERTED_BY STRING, REVERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

