USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_DOCUMENT_STORE ( DOCSTORE_ID STRING PRIMARY KEY, REQUEST_ID STRING, STORAGE_PATH STRING, CHECKSUM STRING, SIZE_BYTES NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

