USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_GEO_FACTORS ( FACTOR_ID STRING PRIMARY KEY, REQUEST_ID STRING, IP_ADDR STRING, GEO JSON, RISK_SCORE NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

