USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_NOTIFICATIONS ( NOTIFICATION_ID STRING PRIMARY KEY, REQUEST_ID STRING, SIGNER_ID STRING, CHANNEL STRING, PAYLOAD VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SENT_AT TIMESTAMP_LTZ );

