USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATECARD_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TEMPLATE_ID STRING, PRICE_OVERRIDE NUMBER, VALID_FROM TIMESTAMP_LTZ, VALID_TO TIMESTAMP_LTZ
);

