USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_PROVIDER_STATUS ( PROVIDER_ID STRING PRIMARY KEY, STATUS STRING, LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

