USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ONBOARDING_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, STEP STRING, STATUS STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

