USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUARANTINE_BLOBS ( QUARANTINE_ID STRING PRIMARY KEY, REASON STRING, PAYLOAD VARIANT, QUARANTINED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

