USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ENTITLEMENT_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, TENANT_ID STRING, ENTITLEMENT_JSON VARIANT, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

