USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_DISPATCH_LOG ( DISPATCH_ID STRING PRIMARY KEY, REQUEST_ID STRING, PROVIDER_ID STRING, DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), OUTCOME STRING, DETAILS VARIANT );

