USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ENTITLEMENT_EXCEPTIONS ( EXC_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, EXCEPTION_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

