USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, TARGET STRING, ACTION_TYPE STRING, SCHEDULE_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'SCHEDULED'
);

