USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, METRIC_NAME STRING, SEVERITY STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED_AT TIMESTAMP_LTZ, DETAILS VARIANT );

