USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_OPERATIONAL_RUNBOOK_INDEX ( RUNBOOK_ID STRING PRIMARY KEY, PATH STRING, SUMMARY STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

