USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTEXT_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, REQUEST_ID STRING, SNAPSHOT VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

