USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DAILY_SIGNATURE_METRICS ( DAY_ID STRING PRIMARY KEY, DAY DATE, ACCOUNT_ID STRING, SIGNATURES_COUNT NUMBER, FAILURES_COUNT NUMBER );

