USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_VERSION_REGISTRY ( VERSION_ID STRING PRIMARY KEY, OBJECT_NAME STRING, VERSION_NUMBER INT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

