USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.GET_SIMILARITY_CACHE(query_hash STRING)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
SELECT RESULTS FROM DOCGEN.SIMILARITY_CACHE WHERE QUERY_HASH = :query_hash AND EXPIRES_AT > CURRENT_TIMESTAMP();
$$;

