USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLACK_PROVIDER_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, PROVIDER_ID STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

