USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, WINDOW_ID STRING, CHANNELS ARRAY, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

