USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_APPROVAL_ACTIONS ( ACTION_ID STRING PRIMARY KEY, APPROVAL_ID STRING, ACTION_BY STRING, ACTION STRING, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

