USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_PREFERENCES ( PREF_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PREF_KEY STRING, PREF_VALUE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

