USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPS_RUNBOOK_ENTRIES ( ENTRY_ID STRING PRIMARY KEY, TITLE STRING, CONTENT CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

