USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESS_LOGS ( ACCESS_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, USER_ID STRING, ACCESS_TYPE STRING, ACCESS_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

