USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FLAG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FLAG_NAME STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

