USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_REPORTS_ARCHIVE (
  ARCHIVE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PAYLOAD VARIANT
);
-- Archived incident reports for long-term forensic storage and compliance @150 @31

