USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_AUDIT_02 ( AUDIT_ID STRING PRIMARY KEY, EVENT_REF STRING, SOURCE_SYSTEM STRING, PAYLOAD VARIANT, AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

