USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACTION_TRACE ( TRACE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ACTION STRING, META VARIANT, TRACE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

