USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_QUEUE ( COMPLAINT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, DETAILS VARIANT, STATUS STRING DEFAULT 'OPEN', RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

