USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_DISPUTES ( DISPUTE_ID STRING PRIMARY KEY, BILL_ID STRING, REASON STRING, CREATED_BY STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

