USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ACTIVITY_FEED ( FEED_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, MESSAGE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

