CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_ISSUE_TRACKER ( ISSUE_ID STRING PRIMARY KEY, PROVIDER STRING, DESCRIPTION CLOB, STATUS STRING, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

