CREATE OR REPLACE TABLE DOCGEN.CHANGE_CONTROL_REQUESTS ( REQ_ID STRING PRIMARY KEY, TITLE STRING, DESCRIPTION CLOB, REQUESTOR STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

