CREATE OR REPLACE TABLE DOCGEN.CHANGE_CONTROL_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB ); @31 @24

