USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PERMISSIONS ( TP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PRINCIPAL STRING, PERM STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

