USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VERSIONS_HISTORY ( TVH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VERSION_NUMBER INT, BODY CLOB, UPDATED_BY STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

