CREATE OR REPLACE TABLE DOCGEN.CONFIGURATION_VERSIONED_STORE ( CONFIG_ID STRING PRIMARY KEY, KEY STRING, VALUE VARIANT, VERSION_NUMBER INT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

