CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, FLAG_KEY STRING, ACTION STRING, USER_REF STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

