USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_QUEUE ( RENDER_JOB_ID STRING PRIMARY KEY, ASSEMBLY_ID STRING, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

