USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_ACTIVITY ( ACT_ID STRING PRIMARY KEY, HOLD_ID STRING, ACTION STRING, ACTED_BY STRING, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

