USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_POLICY_EXCEPTIONS ( EXC_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, REASON CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

