USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_METRICS ( METRIC_ID STRING PRIMARY KEY, RENDER_JOB_ID STRING, DURATION_MS NUMBER, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

