USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINTS ( FINGERPRINT_ID STRING PRIMARY KEY, DEVICE_ID STRING, ATTRIBUTES VARIANT, LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

