CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CALLBACK_INDEX ( CB_ID STRING PRIMARY KEY, PROVIDER_ID STRING, EVENT_TYPE STRING, HANDLER_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

