CREATE OR REPLACE TABLE DOCGEN.PROVIDER_WEBHOOK_HEALTH ( HEALTH_ID STRING PRIMARY KEY, PROVIDER_ID STRING, STATUS STRING, LAST_RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

