USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_JOBS_V2 (
  JOB_ID STRING PRIMARY KEY,
  OBJECT_NAME STRING,
  STATUS STRING DEFAULT 'PENDING',
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT,
  LAST_ERROR VARIANT
);
-- Enhanced sync job record for improved diagnostics and retries @225 @31

