USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_FAILURE_RETRIES ( RETRY_ID STRING PRIMARY KEY, REQUEST_ID STRING, FAILURE_REASON STRING, ATTEMPTS INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ );

