USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, KEY_REF STRING, ACTION STRING, PERFORMED_BY STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

