USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SIGNER_MAP ( MAP_ID STRING PRIMARY KEY, RAW_ID STRING, SIGNER_ID STRING, MAPPED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

