USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONFIDENCE_SCORES ( SCORE_ID STRING PRIMARY KEY, REQUEST_ID STRING, SIGNER_ID STRING, SCORE FLOAT, DETAILS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

