CREATE OR REPLACE TABLE DOCGEN.ENTITLEMENT_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE STRING, REQUESTOR STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

