USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERTIFICATE_INDEX ( IDX_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CERT_ID STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

