USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_STORE ( CERT_ID STRING PRIMARY KEY, CERT_PEM CLOB, SUBJECT STRING, ISSUER STRING, SERIAL_NUMBER STRING, NOT_BEFORE TIMESTAMP_LTZ, NOT_AFTER TIMESTAMP_LTZ );

