USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EVIDENCE_CROSSREFS ( XF_ID STRING PRIMARY KEY, AUDIT_ID STRING, EVID_ID STRING, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

