USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_ACCESS_PROFILE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, PROFILE_ID STRING, SUBJECT_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

