USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_SIGN_REQUESTS ( REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SIGNATURE_METHOD STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

