USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACT_EXPIRY ( EXP_ID STRING PRIMARY KEY, CONTRACT_ID STRING, EXPIRES_AT TIMESTAMP_LTZ, NOTIFIED BOOLEAN DEFAULT FALSE );

