USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLDS ( HOLD_ID STRING PRIMARY KEY, REQUEST_ID STRING, REASON STRING, PLACED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RELEASED_AT TIMESTAMP_LTZ );

