USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REALTIME_ALERT_ACK ( ACK_ID STRING PRIMARY KEY, ALERT_ID STRING, ACKED_BY STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

