USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_RELEASES ( RELEASE_ID STRING PRIMARY KEY, HOLD_ID STRING, RELEASED_BY STRING, RELEASED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

