USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_POLICY_TEMPLATES_V2 (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  RULES VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_LTZ
);
-- Versioned access policy templates for iterative policy changes and deployment @22 @36

