USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_RULE_VERSIONING ( VERSION_ID STRING PRIMARY KEY, POLICY_ID STRING, VERSION_NUMBER INT, RULE_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

