USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALGORITHM_COMPAT_MATRIX ( MATRIX_ID STRING PRIMARY KEY, ALG_FROM STRING, ALG_TO STRING, COMPAT BOOLEAN, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

