USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_REGISTRY_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, MODEL_ID STRING, SNAPSHOT JSON, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

