USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VERSIONS (
  TEMPLATE_VERSION_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  VERSION_NUMBER NUMBER,
  CONTENT_CLOB STRING,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);
-- Template versions table to support document assembly rollback and audits @141 @131

