USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DEPLOYMENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MODEL_ID STRING, DEPLOYED_BY STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

