USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROMPT_TEMPLATE_REGISTRY ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, BODY CLOB, VERSION INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

