USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, MAX_PER_MIN INT, WINDOW_SECONDS INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

