USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_PUBLICATION_INDEX ( PUB_ID STRING PRIMARY KEY, BUNDLE_ID STRING, NETWORK STRING, TXID STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

