USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROMPT_EXECUTION_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, INPUT VARIANT, OUTPUT VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

