USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LONGTERM_VALIDATION_INDEX ( LTV_ID STRING PRIMARY KEY, BUNDLE_ID STRING, VALIDATION_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

