USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LTV_RETENTION_JOBS ( JOB_ID STRING PRIMARY KEY, BUNDLE_IDS ARRAY, STATUS STRING, SCHEDULED_AT TIMESTAMP_LTZ, EXECUTED_AT TIMESTAMP_LTZ );

