USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LIBRARY (
  TEMPLATE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  NAME STRING,
  DESCRIPTION STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Template catalog used by assembly service and admin UI @131 @130

