-- Stores signer records and per-signer policy attributes (masked email support via masking policies) per admin/privacy guidance. @31 @34
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNERS (
  SIGNER_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  ACCOUNT_ID STRING,
  SIGNER_EMAIL STRING,
  SIGNER_NAME STRING,
  SIGNER_METHOD STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

