USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_MIGRATION_JOBS ( JOB_ID STRING PRIMARY KEY, SOURCE_TIER STRING, TARGET_TIER STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

