USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_TAGS ( TAG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TAG STRING, TAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

