USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_LIBRARY (
  CLAUSE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  BODY CLOB,
  TAGS ARRAY,
  VERSION INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Clause library for reusable text snippets used during assembly and AI clause generation @31 @625

