USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_REQUEST_QUEUE ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

