USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATION_INDEX ( ANNO_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ANNOTATOR STRING, ANNOTATION JSON, ANNOTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

