USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_ATTEMPT_LOGS ( LOG_ID STRING PRIMARY KEY, INVOICE_ID STRING, PROVIDER_ID STRING, RESULT VARIANT, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

