-- Records verification runs (cert chain, OCSP/CRL results, verification details) for each verification attempt. @36 @12
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATIONS (
  VERIFY_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  METHOD STRING,
  RESULT STRING,
  DETAILS VARIANT
);

