USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_RATE_REGISTRY ( TAX_ID STRING PRIMARY KEY, REGION STRING, RATE NUMBER, EFFECTIVE_FROM TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

