USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEARTBEAT (HB_ID STRING PRIMARY KEY, PROVIDER_ID STRING, STATUS STRING, HEARTBEAT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

