USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_QUOTAS ( QUOTA_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, MONTHLY_LIMIT NUMBER, USED NUMBER DEFAULT 0, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

