USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RECOMMENDATION_CACHE ( CACHE_ID STRING PRIMARY KEY, TENANT_ID STRING, RECOMMENDATIONS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

