USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CURRENCY_RATE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, BASE_CURRENCY STRING, RATES VARIANT, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

