USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTI_CURRENCY_INVOICE_LINES ( LINE_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT_BASE NUMBER, AMOUNT_LOCAL NUMBER, CURRENCY STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

