USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PERSONALIZATION_PREVIEW_JOBS ( JOB_ID STRING PRIMARY KEY, PROFILE_ID STRING, TEMPLATE_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

