USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_ERRORS ( ERROR_ID STRING PRIMARY KEY, RENDER_JOB_ID STRING, ERROR_MESSAGE STRING, TRACE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

