USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CAPABILITIES (CAP_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CAPABILITY STRING, DETAILS VARIANT); 
-- @31 @24 @52

