USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ANOMALY_ALERTS ( ALERT_ID STRING PRIMARY KEY, INVOICE_ID STRING, METRIC VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

