USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ANOMALY_INVESTIGATIONS ( INV_ID STRING PRIMARY KEY, ALERT_ID STRING, INVESTIGATOR STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

