USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, CLAUSE_ID STRING, ACTION STRING, PERFORMED_BY STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

