USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_TAGS (
  TAG_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TAG STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Template tagging to help admin classification and tenant scoping @131 @630

