-- Evidence bundle table (CompliancePacket metadata) to persist evidence references and export manifests per compliance guidance. @28 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_BUNDLE (
  BUNDLE_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  ACCOUNT_ID STRING,
  BUNDLE_URL STRING,
  BUNDLE_MANIFEST VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ARCHIVE_STATUS STRING
);

