USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EDIT_PROPOSALS ( PROP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PROPOSER STRING, PROPOSAL JSON, STATUS STRING, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

