USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PROPOSAL_REVIEWS ( REV_ID STRING PRIMARY KEY, PROP_ID STRING, REVIEWER STRING, OUTCOME STRING, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

