USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROUTING_LOGS ( LOG_ID STRING PRIMARY KEY, RULE_ID STRING, REQUEST_ID STRING, CHOSEN_PROVIDER STRING, LOG_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); 
-- @31 @24 @52

