USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_QUOTAS ( QUOTA_ID STRING PRIMARY KEY, PROVIDER_ID STRING, MAX_PER_MIN INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

