-- Stores signature/document hash anchors and provenance for forensic validation. @3 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_HASHES (
  HASH_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  DOCUMENT_ID STRING,
  SIGNATURE_HASH STRING,
  ANCHOR_TXID STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

