USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATIONS (
  ANNOTATION_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  AUTHOR STRING,
  BODY VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Human or AI annotations attached to rendered documents for reviewer notes and provenance @625 @586

