USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_ADVISORY_REGISTRY ( ADV_ID STRING PRIMARY KEY, TITLE STRING, SEVERITY STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS CLOB );

