USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_BIOMETRIC_HASHES (
  BIO_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  SIGNER_ID STRING,
  BIOMETRIC_HASH STRING,
  METHOD STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Stores biometric template hashes (not raw biometrics) for behavioral scoring and privacy @177 @573

