USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_ROLLBACK_LOGS ( LOG_ID STRING PRIMARY KEY, REQ_ID STRING, ROLLBACK_BY STRING, ROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

