USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LOCK_HISTORY ( HIST_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCKED_BY STRING, LOCKED_AT TIMESTAMP_LTZ, UNLOCKED_AT TIMESTAMP_LTZ ); 
-- @31 @24 @52

