USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUSPECT_ACTIVITY ( SUSPECT_ID STRING PRIMARY KEY, REQUEST_ID STRING, REASON STRING, DETAILS VARIANT, FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

