USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_DEFINITION_REGISTRY ( SLO_ID STRING PRIMARY KEY, NAME STRING, TARGET JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

