USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DATA_LINEAGE ( LINEAGE_ID STRING PRIMARY KEY, MODEL_ID STRING, SOURCE_REF STRING, TRANSFORM JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

