USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUSPECT_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SUSPECT_ID STRING, NOTIF_PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

