USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_FEEDBACK_QUEUE ( FB_ID STRING PRIMARY KEY, TENANT_ID STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

