USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_GOVERNANCE_ENGAGEMENTS ( ENG_ID STRING PRIMARY KEY, POLICY_ID STRING, STAKEHOLDERS VARIANT, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

