USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_REGISTER ( RISK_ID STRING PRIMARY KEY, TITLE STRING, SEVERITY STRING, MITIGATION JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

