USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, ADMIN_USER STRING, ACTION STRING, TARGET_OBJECT STRING, DETAILS VARIANT, ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

