USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MITIGATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, RISK_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ );

