USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPROMISE_RESPONSE_LOGS ( LOG_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTIONS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

