USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_CHECKS ( CHECK_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHECK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT VARIANT );

