USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, PRINCIPAL STRING, ALERT_TYPE STRING, CHANNEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

