USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_RETIREMENT_REGISTRY ( RETIRE_ID STRING PRIMARY KEY, FEATURE_ID STRING, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

