USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_SCORES (
  SCORE_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  DOCUMENT_ID STRING,
  SCORE_DECIMAL NUMBER,
  MODEL_VERSION STRING,
  REASONS VARIANT,
  SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Biometric/fraud scoring records for risk evaluation and alerts @356 @573

