USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DELIVERY_LOG ( DELIVERY_ID STRING PRIMARY KEY, ALERT_ID STRING, PRINCIPAL STRING, CHANNEL STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

