USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_REGION_STATUS ( PRS_ID STRING PRIMARY KEY, PR_ID STRING, STATUS STRING, LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

