USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_OUTAGES ( OUTAGE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, DETAILS VARIANT); 
-- @31 @24 @52

