USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_VERSION_REGISTRY ( VERSION_ID STRING PRIMARY KEY, NAME STRING, VERSION STRING, RELEASED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

