USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGED_ACCESS_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUESTOR STRING, STATUS STRING, APPROVED_AT TIMESTAMP_LTZ );

