USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_DEPRECATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, VERSION_ID STRING, MESSAGE CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

