USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MAINTENANCE ( MAINT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SCHEDULED_AT TIMESTAMP_LTZ, DURATION_MIN INT, NOTES VARIANT); 
-- @31 @24 @52

