USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGED_SESSION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SESSION_ID STRING, SUBJECT_REF STRING, ACTIONS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

