USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CONTRACT_TEXT CLOB, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ );

