USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_CURATION_QUEUE ( Q_ID STRING PRIMARY KEY, INCIDENT_ID STRING, CURATOR STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

