-- ActivationAudit / API_AUDIT compatible log for admin actions and validation requests for reconciliation. @31 @236
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_AUDIT_LOG (
  AUDIT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  USER_ID STRING,
  ACTION STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

