USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_THREAT_INTEL (
  INTEL_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  SOURCE STRING,
  RISK_LEVEL STRING,
  DETAILS VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Threat intelligence records for signers to support risk decisions and automated blocks @135 @356

