USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_ROSTER ( ROSTER_ID STRING PRIMARY KEY, OPERATOR_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, SHIFT_JSON VARIANT );

