USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ACTIVITY_SUMMARY ( SUM_ID STRING PRIMARY KEY, USER_REF STRING, ACTIVITY_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

