USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ALERT_RESPONSES ( RESP_ID STRING PRIMARY KEY, ALERT_ID STRING, OPERATOR_REF STRING, RESPONDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

