USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULER_HEARTBEAT ( HB_ID STRING PRIMARY KEY, SCHEDULER_NAME STRING, LAST_HEARTBEAT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

