USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIVITY ( ACT_ID STRING PRIMARY KEY, OPERATOR_ID STRING, ACTION STRING, ENTITY_REF STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

