USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_FAILURE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TASK_NAME STRING, FAILURE_JSON VARIANT, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

