-- Table to store integration key hashes and rotation metadata; supports show-once UX for Admin Console. @124 @16
CREATE OR REPLACE TABLE DOCGEN.ACCOUNTS_INTEGRATION_KEYS (
  ACCOUNT_ID STRING PRIMARY KEY,
  INTEGRATION_KEY_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ROTATED_AT TIMESTAMP_LTZ
);

