USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_METRIC_EXPOSURES ( EXPOSURE_ID STRING PRIMARY KEY, FEATURE_ID STRING, METRIC_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

