USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DASHBOARD_WIDGETS ( WIDGET_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, OWNER STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

