USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_BINDINGS ( BIND_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

