USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_USAGE_AGGREGATE ( AGG_ID STRING PRIMARY KEY, TENANT_ID STRING, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, METRICS VARIANT ); @31 @24 @52

