USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_HEALTH_CHECKS ( CHECK_ID STRING PRIMARY KEY, COMPONENT STRING, SCHEDULE_CRON STRING, LAST_RUN TIMESTAMP_LTZ ); 
-- @31 @24 @52

