USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_QUEUE ( DISPUTE_ID STRING PRIMARY KEY, TENANT_ID STRING, INVOICE_REF STRING, STATUS STRING DEFAULT 'OPEN', OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

