USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_MANIFEST (
  MANIFEST_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TARGET_LOCATION STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Manifest table for recording evidence exports and archival jobs to object store @99 @2438

