USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_COMPLIANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, SCOPE VARIANT, LOCATION STRING, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

