USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_TOKEN_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TOKEN_REF STRING, SUBJECT_REF STRING, ACTION STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

