USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, HSM_REF STRING, NEXT_ROTATION_AT TIMESTAMP_LTZ, ROTATION_POLICY VARIANT ); @31 @24 @52

