USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRYPTO_OPERATION_METRICS ( MET_ID STRING PRIMARY KEY, OP_TYPE STRING, LATENCY_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

