USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CREDENTIAL_ROTATION ( ROT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, LAST_ROTATED_AT TIMESTAMP_LTZ, NEXT_ROTATION_AT TIMESTAMP_LTZ );

