USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACCESS_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, OPERATOR_REF STRING, STATUS STRING, REVIEWED_AT TIMESTAMP_LTZ );

