USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, CC_ID STRING, AMOUNT NUMBER, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

