USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATING_HISTORY ( RH_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RATING NUMBER, RATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SOURCE STRING ); @31 @24 @52

