USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUDGET_ALERTS ( ALERT_ID STRING PRIMARY KEY, CC_ID STRING, THRESHOLD NUMBER, NOTIFIED BOOLEAN DEFAULT FALSE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

