USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_SELF_ASSESSMENTS ( ASMT_ID STRING PRIMARY KEY, REG_ID STRING, TENANT_ID STRING, RESULT VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

