USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_COMPLIANCE_DOCS ( DOC_ID STRING PRIMARY KEY, PROVIDER_ID STRING, LOCATION STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

