USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUDGET_RUNS ( RUN_ID STRING PRIMARY KEY, CC_ID STRING, SPENT NUMBER, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()); 
-- @31 @24 @52

