USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_RISK_EVENTS ( EVENT_ID STRING PRIMARY KEY, RISK_ID STRING, EVENT_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @52

