USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_DIFF_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, BASE_VERSION INT, TARGET_VERSION INT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

