USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_CONSUMERS (
  CONSUMER_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  ENDPOINT STRING,
  SECRET_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

