USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_LOGS (
  LOG_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  CALLBACK_URL STRING,
  STATUS STRING,
  RESPONSE_CODE INT,
  RESPONSE_BODY VARIANT,
  ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

