USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_AGGREGATES_V2 (
  AGG_ID STRING PRIMARY KEY,
  AGG_KEY STRING,
  AGG_PAYLOAD VARIANT,
  AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE STRING
);
-- Extended audit aggregates with source tagging for cross-system audits @150 @31

