USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_USAGE_LOGS ( LOG_ID STRING PRIMARY KEY, CLAUSE_ID STRING, DOCUMENT_ID STRING, TENANT_ID STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

