USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ROTATION_LOG (
  ROT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  OLD_ENDPOINT STRING,
  NEW_ENDPOINT STRING,
  ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ROTATED_BY STRING
);

