USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PREVIEWS (
  PREVIEW_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  PREVIEW_PAYLOAD VARIANT,
  RENDER_URL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

