USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RENDERERS (
  RENDERER_ID STRING PRIMARY KEY,
  NAME STRING,
  IMAGE_REF STRING,
  CONFIG VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

