USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  RENDERER_ID STRING,
  JOB_PAYLOAD VARIANT,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

