USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IMAGE_ASSET_USAGE ( USAGE_ID STRING PRIMARY KEY, ASSET_ID STRING, DOCUMENT_ID STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

