USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_CACHE ( CACHE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PREVIEW_LOCATION STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

