USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ROTATION_HISTORY (
  ROTATION_ID STRING PRIMARY KEY,
  KEY_REF STRING,
  ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ROTATED_BY STRING,
  META VARIANT
);
-- Tracks rotation events for keys used in evidence signing or API clients @316 @110

