USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ANCHORS (
  ANCHOR_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ANCHOR_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

