USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_ALERT_QUEUE ( ALERT_ID STRING PRIMARY KEY, SIGNER_ID STRING, RISK_SCORE NUMBER, STATUS STRING DEFAULT 'OPEN', RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

