USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_ALERT_RESOLUTION ( RES_ID STRING PRIMARY KEY, ALERT_ID STRING, RESOLVED_BY STRING, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

