USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CERT_REQUIREMENTS (
  REQ_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  REQUIREMENT VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

