USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_CASE_REGISTRY ( CASE_ID STRING PRIMARY KEY, SIGNER_ID STRING, DETAILS VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

