USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_JURISDICTIONS (
  JURIS_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  COUNTRY_CODE STRING,
  RULES VARIANT
);

