USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JURISDICTION_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  COUNTRY_CODE STRING,
  PASSED BOOLEAN,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

