USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ZIP_MANIFESTS (
  MANIFEST_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  FILES ARRAY,
  ZIP_LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

