USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ZIP_RECONCILE ( RECON_ID STRING PRIMARY KEY, MANIFEST_ID STRING, STATUS STRING, DETAILS VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

