USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_PERMISSIONS ( PERM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, EXPORT_TYPE STRING, ALLOWED BOOLEAN, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

