USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, PROFILE_ID STRING, TARGET_TABLE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

