USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVAL_AUDIT_INDEX ( INDEX_ID STRING PRIMARY KEY, MANIFEST_ID STRING, ARCHIVE_STAGE STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

