USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_SCHEDULES (
  SCHEDULE_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  CRON_EXPR STRING,
  RETENTION_DAYS INT,
  ENABLED BOOLEAN DEFAULT TRUE,
  LAST_RUN_AT TIMESTAMP_LTZ
);

