USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_REGISTRY ( TRAIN_ID STRING PRIMARY KEY, OPERATOR_REF STRING, COURSE STRING, COMPLETED_AT TIMESTAMP_LTZ );

