USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, THRESHOLD_ID STRING, SENT_TO STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

