USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROCESSING_CHECKPOINT (
  CHECKPOINT_ID STRING PRIMARY KEY,
  NAME STRING,
  LAST_PROCESSED_AT TIMESTAMP_LTZ,
  META VARIANT
);
-- Checkpoint table for idempotent processors and backfill tracking @141 @315

