USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_TYPE STRING, VALUE VARIANT, EXPIRES_AT TIMESTAMP_LTZ );

