USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_HISTORY ( HISTORY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_TYPE STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

