USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATECARD_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SNAPSHOT VARIANT, SNAPSHOT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

