USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATECARD_CHANGES ( CHANGE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CHANGE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

