USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_SLA_CREDITS ( CREDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, AMOUNT NUMBER, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

