USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKFILL_JOBS (
  JOB_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  STATUS STRING DEFAULT 'PENDING',
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT
);
-- Backfill job registry for replaying or repairing ingestion windows @141 @315

