USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, DRAFT_ID STRING, COMMENT_BY STRING, COMMENT TEXT, COMMENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

