USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_RETRY_QUEUE ( QUEUE_ID STRING PRIMARY KEY, NOTIF_ID STRING, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, ATTEMPT_COUNT INT DEFAULT 0, STATUS STRING ); @31

