USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, DRAFT_ID STRING, APPROVED_BY STRING, STATUS STRING, APPROVED_AT TIMESTAMP_LTZ );

