USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_DELIVERY_INDEX ( DELIV_ID STRING PRIMARY KEY, PHONE STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

