USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_EVENT_LOG ( EVT_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), HANDLED BOOLEAN DEFAULT FALSE ); @31

