USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DLQ ( DLQ_ID STRING PRIMARY KEY, EVT_ID STRING, ERROR_MESSAGE STRING, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

