USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_DISTRIBUTIONS ( DIST_ID STRING PRIMARY KEY, INVOICE_ID STRING, SENT_TO STRING, CHANNEL STRING, SENT_AT TIMESTAMP_LTZ );

