USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_INTEGRATION_METRICS ( MET_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, LATENCY_MS NUMBER, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

