USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, MESSAGE STRING, CHANNEL STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

