USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  CHANNEL STRING,
  SENT_AT TIMESTAMP_LTZ,
  STATUS STRING
);
-- Consent notification history to record communications associated with consents @220 @31

