USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVOCATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, CERT_SERIAL STRING, ALERT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

