USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_CHAIN_STORE ( CHAIN_ID STRING PRIMARY KEY, CERT_CHAIN VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

