USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_EMAIL_VERIFICATION ( VER_ID STRING PRIMARY KEY, SIGNER_ID STRING, EMAIL STRING, VERIFIED_AT TIMESTAMP_LTZ ); @31

