USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_IP_HISTORY ( ENTRY_ID STRING PRIMARY KEY, SIGNER_ID STRING, IP_ADDR STRING, SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

