USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOLOCATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, SIGNER_ID STRING, LOCATION VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SEVERITY STRING ); @31

