USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_OVERRIDES (
  OVERRIDE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  ENDPOINT STRING,
  LIMIT_VALUE INT,
  EXPIRES_AT TIMESTAMP_LTZ
);

