USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_MODEL_ALERTS ( ALERT_ID STRING PRIMARY KEY, MODEL_ID STRING, SIGNER_ID STRING, SCORE NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

