USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_LABELS (
  LABEL_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  LABEL STRING,
  ADDED_BY STRING,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

