USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_REVIEW_WORKFLOW ( WF_ID STRING PRIMARY KEY, CASE_ID STRING, STAGE STRING, ASSIGNED_TO STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

