USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVIEWS (
  REVIEW_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  REVIEWER STRING,
  SCORE FLOAT,
  COMMENTS STRING,
  REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

