USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WATCHERS (
  WATCHER_ID STRING PRIMARY KEY,
  ENTITY_TYPE STRING,
  ENTITY_ID STRING,
  SUBSCRIBER STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Watchers/subscribers for entity change notifications and operator workflows @290 @31

