USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_REPLICATION_JOBS ( JOB_ID STRING PRIMARY KEY, SNAP_ID STRING, TARGET_LOCATION STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

