USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_GOVERNANCE ( GOV_ID STRING PRIMARY KEY, RULES VARIANT, OWNER STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

