USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VERSION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  TEMPLATE_VERSION_ID STRING,
  CHANGES VARIANT,
  AUDITED_BY STRING,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

