USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_REQUEST_QUEUE ( REQ_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUEST_TYPE STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

