USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TAGS_HISTORY (
  PTH_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  TAG STRING,
  ACTION STRING,
  ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

