USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNTHETIC_DATA_CATALOG ( CATALOG_ID STRING PRIMARY KEY, NAME STRING, DESCRIPTION CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

