USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_DATA_LINEAGE ( LINEAGE_ID STRING PRIMARY KEY, SOURCE_REF STRING, TRANSFORM JSON, LINKED_MODEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

