USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ASSIGNMENTS (
  PA_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_TYPE STRING,
  TARGET_ID STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

