USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_FINDINGS (
  FINDING_ID STRING PRIMARY KEY,
  REVIEW_ID STRING,
  SEVERITY STRING,
  DETAILS VARIANT,
  RESOLVED BOOLEAN DEFAULT FALSE
);

