USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ACCESS_STATS (
  STAT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ACCESS_COUNT INT DEFAULT 0,
  LAST_ACCESSED_AT TIMESTAMP_LTZ
);

