USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_RUNS (
  RUN_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  PURGED_COUNT INT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

