USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_METADATA_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, METADATA VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

