USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ENRICHMENT_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ENRICHMENT_TYPE STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

