USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTITY_RESOLUTION_INDEX ( IDX_ID STRING PRIMARY KEY, ENTITY_REF STRING, ALIASES ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

