USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COUNTERSIGN_REQUESTS (
  COUNTER_ID STRING PRIMARY KEY,
  ORIGINAL_BUNDLE_ID STRING,
  COUNTER_PARTIES ARRAY,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

