USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SIMILARITY_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, INDEX_REF STRING, LOCATION STRING, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

