USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOT_REGISTRY ( REG_ID STRING PRIMARY KEY, INDEX_NAME STRING, SNAPSHOT_LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

