USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_LOGS (
  CONSENT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CONSENT_TYPE STRING,
  CONSENT_GIVEN BOOLEAN,
  GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

