USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_INDEX_SHARD (
  SHARD_ID STRING PRIMARY KEY,
  SEI_ID STRING,
  SHARD_KEY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Sharded event index helper to scale event indexing across large corpora @332 @31

