USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_EXPLAINABILITY_INDEX ( IDX_ID STRING PRIMARY KEY, MODEL_ID STRING, EXPLAIN_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

