USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  RULE_ID STRING,
  REDACTED_FIELDS VARIANT,
  REDACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

