USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_SNAPSHOT_REGISTRY ( SNAP_ID STRING PRIMARY KEY, SCOPE VARIANT, LOCATION STRING, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

