USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_INSTANCES (
  INSTANCE_ID STRING PRIMARY KEY,
  WF_ID STRING,
  REF_ID STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

