USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  TEMPLATE_HASH STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

