USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_LEVEL_AGREEMENTS ( SLA_ID STRING PRIMARY KEY, NAME STRING, TERMS VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

