USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, INVOICE_REF STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

