USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_TELEMETRY (
  TELE_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  METRIC_NAME STRING,
  METRIC_VALUE VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Telemetry for model performance, drift detection, and explainability metrics @175 @176

