USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRY_BACKOFF_LOG (
  LOG_ID STRING PRIMARY KEY,
  QUEUE_ID STRING,
  ATTEMPT INT,
  BACKOFF_SECONDS INT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

