USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CONTACT_DIRECTORY ( CONTACT_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, CHANNELS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

