USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_COST_MONITORING ( MON_ID STRING PRIMARY KEY, QUERY_ID STRING, COST NUMBER, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

