USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACKNOWLEDGEMENTS (
  ACK_ID STRING PRIMARY KEY,
  ENTITY_REF STRING,
  SUBJECT STRING,
  ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

