USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONFIDENCE_SCORES (
  SCORE_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  METRIC_NAME STRING,
  VALUE FLOAT,
  COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

