USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_EXPLAINABILITY (
  EXPL_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  MODEL_REF STRING,
  EXPLANATION VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

