USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_PROVIDER_SETTLEMENT_INDEX ( IDX_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SETTLEMENT_REF STRING, SETTLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

