USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_CONTROL_CHECKLIST ( ITEM_ID STRING PRIMARY KEY, DESCRIPTION STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

