USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENSEMBLE_LOGS (
  LOG_ID STRING PRIMARY KEY,
  ROUTE_ID STRING,
  REQUEST_ID STRING,
  SELECTED_MODELS ARRAY,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

