USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOT_MANIFEST (
  SNAP_ID STRING PRIMARY KEY,
  SHARD STRING,
  S3_PREFIX STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);
-- Index snapshot manifest used by FAISS snapshot loader and container orchestration @84 @31

