USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_APPROVALS (
  APPROVAL_ID STRING PRIMARY KEY,
  VERSION_ID STRING,
  APPROVED_BY STRING,
  STATUS STRING,
  APPROVED_AT TIMESTAMP_LTZ
);

