USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_GEOLOCATION_INDEX ( GEO_ID STRING PRIMARY KEY, SIGNER_ID STRING, LAT NUMBER, LON NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
