USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_REQUESTS ( REQ_ID STRING PRIMARY KEY, REPLAY_ID STRING, REQUESTOR STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
