USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_QUEUE ( RETRY_ID STRING PRIMARY KEY, SOURCE STRING, PAYLOAD VARIANT, ATTEMPTS INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ ); @31 @24 @1
