USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_REGISTRY (
  INDEX_ID STRING PRIMARY KEY,
  SNAP_ID STRING,
  SHARD STRING,
  INDEX_META VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Registry for FAISS per-shard indexes and lifecycle management @84 @31

