USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_MISMATCH_INDEX ( MISMATCH_ID STRING PRIMARY KEY, SOURCE STRING, PAYLOAD VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
