USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATIONS (
  ESC_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  REASON STRING,
  RAISED_BY STRING,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

