USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CIRCUIT_BREAKER_STATE ( CB_ID STRING PRIMARY KEY, TARGET_REF STRING, STATE STRING, TRIPPED_AT TIMESTAMP_LTZ ); @31 @24 @1
