USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CIRCUIT_BREAKER_EVENTS ( EVT_ID STRING PRIMARY KEY, CB_ID STRING, EVENT JSON, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
