USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLAINTS (
  COMPLAINT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  DETAILS VARIANT,
  STATUS STRING DEFAULT 'OPEN',
  FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

