USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, CLIENT_ID STRING, NEXT_ROTATION_AT TIMESTAMP_LTZ, POLICY VARIANT ); @31 @24 @1
