USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLAINT_RESOLUTIONS (
  RES_ID STRING PRIMARY KEY,
  COMPLAINT_ID STRING,
  RESOLVED_BY STRING,
  RESOLUTION TEXT,
  RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

