USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_QUALITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, SESSION_ID STRING, SCORE NUMBER, SEVERITY STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
