USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_QUALITY_INVESTIGATIONS ( INV_ID STRING PRIMARY KEY, ALERT_ID STRING, INVESTIGATOR STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31 @24 @1
