USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRDPARTY_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  CERT_PEM CLOB,
  IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

