USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAULT_INJECTION_LOGS ( LOG_ID STRING PRIMARY KEY, TARGET_REF STRING, PAYLOAD VARIANT, INJECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
