USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_FINGERPRINTS (
  FINGERPRINT_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  FINGERPRINT STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

