USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_TOGGLES ( TOGGLE_ID STRING PRIMARY KEY, FEATURE_ID STRING, TENANT_ID STRING, ENABLED BOOLEAN, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
