USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHORS (
  ANCHOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TX_ID STRING,
  NETWORK STRING,
  ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

