USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_SNAPSHOTS (
  SNAPSHOT_ID STRING PRIMARY KEY,
  INDEX_ID STRING,
  S3_URL STRING,
  SIZE_BYTES NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Snapshot rows for FAISS index artifacts stored in object storage used by container pull @31 @84

