USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_GEODATA (
  GEODATA_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  IP_ADDRESS STRING,
  GEO JSON,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

