USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_AGENTS (
  UA_ID STRING PRIMARY KEY,
  USER_AGENT STRING,
  NORMALIZED VARIANT,
  FIRST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

