USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_HEALTH_ALERTS ( ALERT_ID STRING PRIMARY KEY, TENANT_ID STRING, METRIC VARIANT, SEVERITY STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
