USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_RISK_SCORES (
  RISK_ID STRING PRIMARY KEY,
  FP_ID STRING,
  RISK_SCORE FLOAT,
  REASON VARIANT,
  SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

