USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_TICKET_WORKFLOW_LOGS ( LOG_ID STRING PRIMARY KEY, TICKET_ID STRING, ACTION STRING, PERFORMED_BY STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
