USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_NOTES_INDEX ( NOTE_ID STRING PRIMARY KEY, VERSION STRING, CONTENT CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24 @1
