USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_FLAGS (
  FLAG_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  FLAG_TYPE STRING,
  DETAILS VARIANT,
  FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

