USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATION_LOGS (
  OP_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  OPERATION STRING,
  PAYLOAD VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

