USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_REQUESTS (
  DSR_ID STRING PRIMARY KEY,
  SUBJECT_ID STRING,
  REQUEST_TYPE STRING,
  SCOPE VARIANT,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

