USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_ATTACHMENT_INDEX ( ATTACH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, MIME_TYPE STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

