USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DSR_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, DSR_ID STRING, TARGET_STAGE STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

