USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_LOGS ( LOG_ID STRING PRIMARY KEY, QUEUE_ID STRING, REVIEWER STRING, OUTCOME STRING, NOTES VARIANT, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

