USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_PARTICIPANTS ( PART_ID STRING PRIMARY KEY, SESSION_ID STRING, SUBJECT_REF STRING, ROLE STRING, JOINED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

