USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_CALLS ( CALL_ID STRING PRIMARY KEY, TARGET STRING, PAYLOAD VARIANT, RESPONSE VARIANT, STATUS STRING, CALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Integration call logging table for External Functions and middleware call audits @217 @236

