USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARE_REVOCATION_QUEUE ( REQ_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TARGET_REF STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

