USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_NOTIFS ( NOTIF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TENANT_ID STRING, NOTIF_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @31

