USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_SCHEDULES ( SCHEDULE_ID STRING PRIMARY KEY, TARGET_TABLE STRING, CRON_EXPR STRING, RETENTION_DAYS INT, LAST_RUN_AT TIMESTAMP_LTZ, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Retention schedule table to drive purge tasks per retention & audit guidance @103 @176

