USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HASH_ANCHORS ( ANCHOR_ID STRING PRIMARY KEY, HASH STRING, METHOD STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

