USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_CASE_DOCUMENTS ( ENTRY_ID STRING PRIMARY KEY, CASE_ID STRING, DOCUMENT_ID STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

