USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.E_DISCOVERY_JOBS ( JOB_ID STRING PRIMARY KEY, CASE_ID STRING, QUERY JSON, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

