USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_SIGNATORIES ( SIGN_ID STRING PRIMARY KEY, CONTRACT_ID STRING, SIGNER_ID STRING, ROLE STRING, SIGNED_AT TIMESTAMP_LTZ );

