USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_MESSAGING_QUEUE ( MSG_ID STRING PRIMARY KEY, TO_OP STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', QUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

