USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LOCK_HISTORY ( HISTORY_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ACTION STRING, BY_USER STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

