USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ISSUE_TRIAGE_QUEUE ( Q_ID STRING PRIMARY KEY, TENANT_ID STRING, DESCRIPTION CLOB, STATUS STRING DEFAULT 'NEW', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

