USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AVAILABILITY_CALENDAR ( CAL_ID STRING PRIMARY KEY, OP_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, AVAILABILITY VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Operator availability calendar used by on-call rota and escalation workflows @31 @56

