USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_RETENTION_STATE ( STATE_ID STRING PRIMARY KEY, REQUEST_ID STRING, STATE STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

