USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SERVICE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, LIMITS JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

