USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINGERPRINT_WATCHLIST ( WATCH_ID STRING PRIMARY KEY, FINGERPRINT STRING, REASON STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

