USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_BREACH_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_REF STRING, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SEVERITY STRING ); @31

