USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_ADJUSTMENT_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REQUEST_JSON VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

