USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_POLICIES ( POLICY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, POLICY VARIANT, ENFORCED BOOLEAN DEFAULT TRUE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

