USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_REVERSALS ( REV_ID STRING PRIMARY KEY, NOTE_ID STRING, ACCOUNT_ID STRING, REVERSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

