USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_AUDITS ( AUDIT_ID STRING PRIMARY KEY, CONTROL_ID STRING, RESULT VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

