USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SUSPENSION_LOGS ( LOG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REASON CLOB, SUSPENDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESUMED_AT TIMESTAMP_LTZ ); @31

