USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_RESUMPTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REQUESTOR STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @31

