USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_RECONCILE_LOG ( LOG_ID STRING PRIMARY KEY, MANIFEST_ID STRING, EXPECTED_COUNT NUMBER, ACTUAL_COUNT NUMBER, STATUS STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Reconciliation log for evidence export manifests and operational auditing @62 @113

