USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_COMPLAINT_OUTCOMES ( OUT_ID STRING PRIMARY KEY, COMP_ID STRING, OUTCOME VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

