USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_NPS_SURVEYS ( SURVEY_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE INT, COMMENTS CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

