USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_NPS_AGGREGATES ( AGG_ID STRING PRIMARY KEY, TENANT_ID STRING, AVG_SCORE NUMBER, SAMPLE_SIZE INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

