USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DEFINITIONS ( ALERT_DEF_ID STRING PRIMARY KEY, NAME STRING, CONDITION VARIANT, ACTION VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

