USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_CONFIGS ( CONFIG_ID STRING PRIMARY KEY, NAME STRING, CONFIG JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Audit configuration store for controlling which events are audited and retention windows @31 @119

