USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_INCIDENT_RESPONSE_PLANS ( PLAN_ID STRING PRIMARY KEY, TENANT_ID STRING, PLAN_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

