USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ESCALATION_CONTACTS ( EC_ID STRING PRIMARY KEY, TENANT_ID STRING, CONTACT JSON, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

