USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SERVICE_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, TENANT_ID STRING, SERVICE_JSON VARIANT, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

