USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PERMISSION_GRANTS ( GRANT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REQ_ID STRING, GRANTED_TO STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Template permission grants for operational control of template access per tenant @31 @170

