USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SUBSCRIPTION_EVENTS ( EVT_ID STRING PRIMARY KEY, SUB_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

