USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_INTEGRATION_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, INTEGRATION_NAME STRING, PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

