USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SUBSCRIPTION_NOTIFS ( NOTIF_ID STRING PRIMARY KEY, SUB_ID STRING, TENANT_ID STRING, CHANNEL STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

