USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_NOTICE_ACKS ( ACK_ID STRING PRIMARY KEY, NOTICE_ID STRING, SUBJECT_REF STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

