USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_TRAINING_ATTENDANCE ( ATT_ID STRING PRIMARY KEY, SESSION_ID STRING, USER_REF STRING, ATTENDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

