USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, INTEGRATION STRING, CALLBACK_URL STRING, SECRET_HASH STRING, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

