USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_THROTTLE_EVENTS ( EVENT_ID STRING PRIMARY KEY, PROFILE_ID STRING, CLIENT_ID STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

