USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_CONCURRENCY_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTIVE_SESSIONS INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

