USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_LOGS_V2 ( LOG_ID STRING PRIMARY KEY, SUBJECT STRING, ACTION STRING, RESOURCE STRING, SOURCE_IP STRING, USER_AGENT STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CONTEXT VARIANT
);
-- Extended access logs with context for richer security analytics @2501 @126

