USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VIDEO_TRANSCRIPTION_INDEX ( TRANS_ID STRING PRIMARY KEY, MEDIA_ID STRING, TRANSCRIPT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

