USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIO_FINGERPRINT_INDEX ( FP_ID STRING PRIMARY KEY, MEDIA_ID STRING, FINGERPRINT VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

