USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_FORECAST_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SNAPSHOT VARIANT, SNAP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

