USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GRAPH_RELATIONSHIP_INDEX ( REL_ID STRING PRIMARY KEY, FROM_REF STRING, TO_REF STRING, REL_TYPE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

