USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GRAPH_TRAVERSAL_JOBS ( JOB_ID STRING PRIMARY KEY, START_REF STRING, PARAMS VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

