USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELATIONSHIP_CONFLICT_LOGS ( LOG_ID STRING PRIMARY KEY, FROM_REF STRING, TO_REF STRING, REASON CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

