USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VIOLATION_INDEX ( VIOL_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

