USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXCEPTION_WORKFLOW ( WF_ID STRING PRIMARY KEY, POLICY_ID STRING, REQUESTOR STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

