USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLRS ( SLR_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SLR_DEFINITION VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ );

