USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, REASON CLOB, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); @31

