USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PENALTIES ( PEN_ID STRING PRIMARY KEY, PROVIDER_ID STRING, REASON STRING, AMOUNT NUMBER, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

