USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_TRANSFORMS ( TRANSFORM_ID STRING PRIMARY KEY, FORMAT_ID STRING, SCRIPT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

