USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_SUMMARY_V2 ( SUM_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNATURE_COUNT INT, LAST_SIGNED_AT TIMESTAMP_LTZ, METRICS VARIANT );
-- Extended document signature summary for richer metrics and payloads @9455 @182

