USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_REPORTS ( SCHEDULE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, CRON_EXPR STRING, LAST_RUN_AT TIMESTAMP_LTZ ); @31

