USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_WEBHOOKS ( WEBHOOK_ID STRING PRIMARY KEY, PARTNER_ID STRING, EVENT_TYPE STRING, CALLBACK_URL STRING, SECRET_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

