USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, RUN_ID STRING, SUBJECT_REF STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

