USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRDPARTY_SYNC_QUEUE ( SYNC_ID STRING PRIMARY KEY, PARTNER_ID STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

