USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_PERMISSION_GRANTS ( GRANT_ID STRING PRIMARY KEY, QUERY_ID STRING, SUBJECT_REF STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

