USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAVED_SEARCH_INDEX ( SEARCH_ID STRING PRIMARY KEY, TENANT_ID STRING, QUERY_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

