USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRDPARTY_SYNC_LOGS ( LOG_ID STRING PRIMARY KEY, SYNC_ID STRING, STATUS STRING, RESPONSE VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

