USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_ALARMS ( ALARM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METRIC STRING, THRESHOLD VARIANT, NOTIFIED BOOLEAN DEFAULT FALSE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

