USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_TAG_SUMMARY ( SUMMARY_ID STRING PRIMARY KEY, REQUEST_ID STRING, TAG_COUNTS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

