USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAGGING_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITIONS VARIANT, ACTIONS VARIANT, ACTIVE BOOLEAN DEFAULT TRUE );

