USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AD_HOC_QUERIES ( QUERY_ID STRING PRIMARY KEY, NAME STRING, QUERY_TEXT STRING, CREATED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

