USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_HISTORIES ( HISTORY_ID STRING PRIMARY KEY, QUERY_ID STRING, RAN_BY STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT_SUMMARY VARIANT );

