USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DB_MIGRATION_REGISTRY ( MIG_ID STRING PRIMARY KEY, NAME STRING, SCRIPT_LOCATION STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

