USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_RELEASE_NOTES ( NOTE_ID STRING PRIMARY KEY, FEATURE_ID STRING, CONTENT CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

