USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, REPORT_ID STRING, SCHEDULE VARIANT, DESTINATION VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

