USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ANNOUNCEMENT_INDEX ( ANN_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

