USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_USAGE ( USAGE_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, COUNT INT, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

