USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_EXEC_METRICS ( MET_ID STRING PRIMARY KEY, PB_ID STRING, METRICS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Metrics for incident playbook execution and postmortem analytics @143 @154

