USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SCHEDULE_CHANGES ( CHANGE_ID STRING PRIMARY KEY, OPERATOR_REF STRING, CHANGE_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

