USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXEMPTIONS_REGISTRY ( EXEMPT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); @31

