USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOKEN_USAGE ( USAGE_ID STRING PRIMARY KEY, TOKEN_ID STRING, USED_BY STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

