USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_LEDGER ( ENTRY_ID STRING PRIMARY KEY, PROVIDER_ID STRING, AMOUNT NUMBER, CHARGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

