USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_NOTES ( NOTE_ID STRING PRIMARY KEY, OP_REF STRING, NOTE CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Quick notes table for operators to annotate incidents or bundle issues @152 @85

