USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_BREACHES ( BREACH_ID STRING PRIMARY KEY, QUOTA_ID STRING, ACCOUNT_ID STRING, USAGE VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

