USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_CREDENTIAL_STORE ( CRED_ID STRING PRIMARY KEY, PARTNER_ID STRING, CRED_META VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

