USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_ACCOUNT_MAPPINGS ( MAP_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, ACCOUNT_REF STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

