USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_ACTIVITY ( ACT_ID STRING PRIMARY KEY, CLIENT_ID STRING, ACTION STRING, DETAILS VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

