USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPRECATION_SCHEDULE ( SCHED_ID STRING PRIMARY KEY, SERVICE_NAME STRING, DEPRECATION_DATE TIMESTAMP_LTZ, NOTICE JSON );

