USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_STATS ( TUS_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, USAGE_COUNT INT DEFAULT 0, LAST_USED_AT TIMESTAMP_LTZ );

