USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_WEBHOOK_DLQ ( DLQ_ID STRING PRIMARY KEY, EVT_ID STRING, ERROR TEXT, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
