USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPRECATION_NOTIFICATION_LOGS ( LOG_ID STRING PRIMARY KEY, SCHED_ID STRING, TARGET STRING, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

