USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_ROLLBACKS ( ROLL_ID STRING PRIMARY KEY, FLAG_NAME STRING, TRIGGERED_BY STRING, ROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

