USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SHARES ( SHARE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SHARED_TO STRING, PERMISSIONS VARIANT, SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

