USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LICENSE_REGISTRY ( LICENSE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LICENSE_JSON VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
