USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_IMPORTS ( IMPORT_ID STRING PRIMARY KEY, SOURCE STRING, TEMPLATE_REF STRING, IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

