USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_NOTIF_QUEUE ( QUEUE_ID STRING PRIMARY KEY, NOTIF_PAYLOAD VARIANT, STATUS STRING DEFAULT 'ENQUEUED', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

