USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_CHECKSUM_INDEX ( IDX_ID STRING PRIMARY KEY, AUDIT_REF STRING, CHECKSUM STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

