USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_ATTEMPTS ( ATTEMPT_ID STRING PRIMARY KEY, SIGNER_ID STRING, METHOD STRING, STATUS STRING, ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

