USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_CACHE_INVALIDATION ( INV_ID STRING PRIMARY KEY, CACHE_ID STRING, INVALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );
