USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, OPTIONS VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );
