USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VIEW_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, VIEW_ID STRING, USER_ID STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

