USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_TEXT_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TEXT CLOB, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
