USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_WITHDRAWAL_REQUESTS ( REQ_ID STRING PRIMARY KEY, USER_REF STRING, CONSENT_REF STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

