USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARED_REPORTS ( SHARE_ID STRING PRIMARY KEY, REPORT_ID STRING, SHARED_WITH ARRAY, PERMISSIONS VARIANT, SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

