USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ALERT_EVENTS ( EVENT_ID STRING PRIMARY KEY, ALERT_ID STRING, ENTITY_REF STRING, SEVERITY STRING, PAYLOAD VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

