USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SSO_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, USER_REF STRING, PROVIDER STRING, EVENT STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

