USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PREVIEW_SESSIONS ( SESSION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );
