USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_USAGE_LEDGER ( ENTRY_ID STRING PRIMARY KEY, API_KEY_ID STRING, USAGE_COUNT INT, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

