USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_HISTORY ( HISTORY_ID STRING PRIMARY KEY, SEARCH_ID STRING, RAN_BY STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT_COUNT INT );

