USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_ACCOUNT_REGISTRY ( ACCOUNT_ID STRING PRIMARY KEY, NAME STRING, OWNER STRING, CONFIG VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

