USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_TELEMETRY ( TELE_ID STRING PRIMARY KEY, SEARCH_ID STRING, LATENCY_MS INT, HIT_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

