USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_ACCOUNT_ACTIVITY ( ACT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ACTION STRING, DETAILS VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

