USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELEGATED_ACCESS_TOKENS ( TOKEN_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, EXPIRES_AT TIMESTAMP_LTZ, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

