USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PREVIEW_ACL ( ACL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, PERMS VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
