USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_MAINTENANCE_LOGS ( LOG_ID STRING PRIMARY KEY, TASK_ID STRING, STATUS STRING, DETAILS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

