USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_SIGNING_STATES ( STATE_ID STRING PRIMARY KEY, SESSION_ID STRING, SIGNER_ID STRING, STATE STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
