USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_POLICY_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

