USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_FAILURE_DLQ ( DLQ_ID STRING PRIMARY KEY, SOURCE_TABLE STRING, ROW_REF STRING, ERROR_JSON VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

