USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REQUEST_WORKFLOW ( WF_ID STRING PRIMARY KEY, REQ_REF STRING, STAGES VARIANT, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

