USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_TOOLTIP_REGISTRY ( TOOLTIP_ID STRING PRIMARY KEY, KEY STRING, TEXT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
