USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_REGISTRY ( COMP_ID STRING PRIMARY KEY, TENANT_ID STRING, DETAILS CLOB, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

