USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_HELP_FEEDBACK ( FB_ID STRING PRIMARY KEY, ARTICLE_ID STRING, USER_REF STRING, RATING INT, COMMENT CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
