USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SHARD_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, INDEX_NAME STRING, SHARDS VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

