USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_A11Y_ISSUES ( ISSUE_ID STRING PRIMARY KEY, DESCRIPTION CLOB, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
