USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARD_LOAD_HISTORY ( LOAD_ID STRING PRIMARY KEY, MANIFEST_ID STRING, SHARD_REF STRING, STATUS STRING, LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

