USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSS_TENANT_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_LIST ARRAY, SCOPE VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

