USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESSIBILITY_CONFORMANCE_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LEVEL STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
