USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_QUERY_METRICS ( METRIC_ID STRING PRIMARY KEY, INDEX_NAME STRING, QUERY_TEXT STRING, LATENCY_MS INT, RESULT_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

