USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_CAPACITY_PLANS ( PLAN_ID STRING PRIMARY KEY, INDEX_NAME STRING, CAPACITY VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

