USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_IMPACT_REVIEW_LOGS ( LOG_ID STRING PRIMARY KEY, ASMT_ID STRING, REVIEWER STRING, NOTES CLOB, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

