USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRY_POLICIES ( POLICY_ID STRING PRIMARY KEY, NAME STRING, MAX_RETRIES INT, BACKOFF JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

