USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_UI_SESSION_INDEX ( SESSION_ID STRING PRIMARY KEY, ADMIN_USER STRING, STARTED_AT TIMESTAMP_LTZ, LAST_ACTIVE_AT TIMESTAMP_LTZ );
