USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_ACCESS_REPORT ( REPORT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LOCATION STRING );

