USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVOPS_RELEASE_CHECKS ( CHECK_ID STRING PRIMARY KEY, RELEASE_REF STRING, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
