USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_BACKFILL_QUEUE ( BACKFILL_ID STRING PRIMARY KEY, INDEX_NAME STRING, RANGE VARIANT, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

