USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_AUDIT_ENGAGEMENTS ( ENG_ID STRING PRIMARY KEY, TENANT_ID STRING, AUDITOR STRING, SCOPE VARIANT, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

