USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DB_BACKUP_REGISTRY ( BACKUP_ID STRING PRIMARY KEY, TARGET STRING, LOCATION STRING, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
