USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_AUDIT_REMEDIATIONS ( REM_ID STRING PRIMARY KEY, FIND_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ );

