USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_ROUTING_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITIONS VARIANT, TARGETS VARIANT, PRIORITY INT, ACTIVE BOOLEAN DEFAULT TRUE );

