USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_COMPLIANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, CERT_META VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

