USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACTION STRING, CHANGED_BY STRING, CHANGE_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

