USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROUTING_LOGS ( LOG_ID STRING PRIMARY KEY, RULE_ID STRING, REQUEST_ID STRING, SELECTED_TARGET STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

