USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOW_REGISTRY ( WIN_ID STRING PRIMARY KEY, COMPONENT_REF STRING, WINDOW JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
