USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLUE_GREEN_SWITCH_HISTORY ( SWITCH_ID STRING PRIMARY KEY, SERVICE_NAME STRING, FROM_VERSION STRING, TO_VERSION STRING, SWITCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

