USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EVALUATOR_RUNS ( RUN_ID STRING PRIMARY KEY, EVAL_ID STRING, CONTEXT VARIANT, RESULT VARIANT, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

