USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_CANARY_ROLLOUTS ( ROLL_ID STRING PRIMARY KEY, VERSION STRING, TARGET_SEGMENT VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

