USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_CHANGE_APPROVALS ( APR_ID STRING PRIMARY KEY, CHANGE_ID STRING, APPROVER STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
