USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PATCH_DEPLOYMENT_LOGS ( LOG_ID STRING PRIMARY KEY, PATCH_REF STRING, COMPONENT STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

