USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOKEN_BLACKLIST_CHECKS ( CHECK_ID STRING PRIMARY KEY, TOKEN_HASH STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), FOUND BOOLEAN );

