USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_SCORE_EXPOSURE ( EXPOSURE_ID STRING PRIMARY KEY, TENANT_ID STRING, RISK_SCORE NUMBER, CALCULATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

