USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PERFORMANCE_DASHBOARD (
  DASH_ID STRING PRIMARY KEY,
  OPERATOR_REF STRING,
  METRICS VARIANT,
  REFRESHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

