USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DEDUP_INDEX (
  DEDUP_ID STRING PRIMARY KEY,
  ALERT_HASH STRING,
  FIRST_SEEN AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

