USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MITIGATION_TASKS ( TASK_ID STRING PRIMARY KEY, EXPOSURE_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ );

