USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_PRIORITY ( PRIORITY_ID STRING PRIMARY KEY, REQUEST_ID STRING, PRIORITY INT, SET_BY STRING, SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

