USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_IMPACT_SCORES (
  SCORE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  IMPACT_SCORE NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

