USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_CLASSIFICATION_INDEX ( CLS_ID STRING PRIMARY KEY, FIELD_REF STRING, SENSITIVITY STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

