USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  ANNOT_ID STRING,
  ACTION STRING,
  ACTED_BY STRING,
  ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

