USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SENSITIVE_FIELD_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, FIELD_REF STRING, SUBJECT_REF STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PURPOSE STRING );

