USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANNOTATION_VERSION_HISTORY (
  VER_ID STRING PRIMARY KEY,
  ANNOT_ID STRING,
  VERSION_NUMBER INT,
  BODY CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

