USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIORITY_DISPATCH_LOGS ( LOG_ID STRING PRIMARY KEY, Q_ID STRING, DISPATCHED_TO STRING, DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

