USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_ACTIVITY_ANALYTICS (
  ANALYTICS_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  SUMMARY VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

