USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_RISK_REGISTER ( RISK_ID STRING PRIMARY KEY, TENANT_ID STRING, DESCRIPTION CLOB, RISK_LEVEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

