USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARING_AUDIT_TRAIL (
  TRAIL_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ACTION STRING,
  BY STRING,
  AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

