USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARE_POLICY_VERSIONS (
  VERSION_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  VERSION_NUMBER INT,
  RULES VARIANT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

