USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_COMPLIANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, DOC_LOCATION STRING, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

