USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HOLD_AUDIT_INDEX (
  AUDIT_ID STRING PRIMARY KEY,
  HOLD_ID STRING,
  ACTION STRING,
  PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

