USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_CATALOG_INDEX (
  ARCH_ID STRING PRIMARY KEY,
  LOCATION STRING,
  CHECKSUM STRING,
  BACKED_UP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

