USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RETENTION_INDEX (
  RET_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  RETENTION_POLICY_ID STRING,
  EXPIRES_AT TIMESTAMP_LTZ
); @31

