USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EDISCOVERY_ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  USER_REF STRING,
  ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

