USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_ASSIGNMENT_METRICS (
  MET_ID STRING PRIMARY KEY,
  ASSN_ID STRING,
  METRICS VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

