USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CORPORATE_ENTITY_INDEX ( ENTITY_ID STRING PRIMARY KEY, NAME STRING, IDENTIFIERS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

