USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, CERT_ID STRING, CHECK_RESULT VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

