USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_CACHE ( CACHE_ID STRING PRIMARY KEY, ASSEMBLY_ID STRING, RENDERED_URL STRING, CACHE_KEY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

