USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEEDBACK_SENTIMENT_INDEX (
  SENT_ID STRING PRIMARY KEY,
  FB_ID STRING,
  SENT_SCORE NUMBER,
  ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

