USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_LATENCY_METRICS (
  MET_ID STRING PRIMARY KEY,
  MAT_ID STRING,
  LATENCY_MS NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

