USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTOMATION_PLAYBOOK_INDEX (
  PB_ID STRING PRIMARY KEY,
  NAME STRING,
  STEPS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

