USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRIAGE_PRIORITY_RULES (
  RULE_ID STRING PRIMARY KEY,
  SCOPE VARIANT,
  PRIORITY INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

