USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KNOWLEDGE_BASE_UPDATES ( UPDATE_ID STRING PRIMARY KEY, KB_ID STRING, UPDATED_BY STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SUMMARY CLOB );

