USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TOGGLE_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  FLAG_NAME STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

