USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, ESC_ID STRING, ASSIGNEE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

