USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUSINESS_CONTINUITY_PLANS ( PLAN_ID STRING PRIMARY KEY, NAME STRING, STEPS VARIANT, LAST_VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

