USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_LOGS (
  LOG_ID STRING PRIMARY KEY,
  CALLBACK_ID STRING,
  STATUS STRING,
  RESPONSE VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

