USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISASTER_RECOVERY_TESTS ( TEST_ID STRING PRIMARY KEY, PLAN_ID STRING, STATUS STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

