USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, ESC_ID STRING, NOTIF_PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

