USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VENDOR_CONTRACT_COMPLIANCE (
  COMP_ID STRING PRIMARY KEY,
  CONTRACT_ID STRING,
  CHECKS VARIANT,
  LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

