USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_CONTROL_AUDIT_TRAILS ( TRAIL_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

