USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_ALLOCATION (
  ALLOC_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ALLOC_JSON VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

