USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_ADJUSTMENT_REQUESTS ( REQ_ID STRING PRIMARY KEY, INVOICE_ID STRING, REQUESTOR STRING, ADJUSTMENT_JSON VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

