USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RECONCILIATION_DISCREPANCIES ( DISC_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT_DIFF NUMBER, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

