USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDIT_CONTROL_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  RULES VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

