USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  TEMPLATE_ID STRING,
  STATUS STRING DEFAULT 'QUEUED',
  ATTEMPTS INT DEFAULT 0,
  NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

