USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GDPR_DATA_MAPPING ( MAP_ID STRING PRIMARY KEY, TENANT_ID STRING, FIELD_MAPPINGS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

