USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_GATEWAY_EVENTS (
  EVT_ID STRING PRIMARY KEY,
  GW_ID STRING,
  PAYLOAD VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

