USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RECONCILIATION_INDEX (
  IDX_ID STRING PRIMARY KEY,
  INVOICE_ID STRING,
  STATUS STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

