USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSE_LOG ( INCIDENT_LOG_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTION STRING, BY_USER STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

