USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PROVENANCE_INDEX ( PROV_ID STRING PRIMARY KEY, RECORD_REF STRING, PROVENANCE_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

