USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_JOBS (
  JOB_ID STRING PRIMARY KEY,
  JOB_TYPE STRING,
  SCOPE VARIANT,
  TARGET_LOCATION STRING,
  STATUS STRING DEFAULT 'CREATED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

