USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_DETECTION_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  REFERENCE_REF STRING,
  SCORE NUMBER,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); @31

