USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_MONITORS ( MON_ID STRING PRIMARY KEY, TARGET_REF STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

