USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FILE_TYPE_WHITELIST ( FT_ID STRING PRIMARY KEY, MIME_TYPE STRING, DESCRIPTION STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

