USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CONVERSION_QUEUE ( QUEUE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TARGET_FORMAT STRING, STATUS STRING DEFAULT 'PENDING', QUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

