USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_PLUGIN_REGISTRY (
  PLUGIN_ID STRING PRIMARY KEY,
  NAME STRING,
  CONFIG VARIANT,
  INSTALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

