USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_QUERY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  PLUGIN_ID STRING,
  RUN_BY STRING,
  QUERY_TEXT CLOB,
  RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

