USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVOCATIONS (
  REVOC_ID STRING PRIMARY KEY,
  GRANT_ID STRING,
  REVOKED_BY STRING,
  REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  REASON STRING
);

