CREATE OR REPLACE VIEW DOCGEN.V_PROVIDER_OVERVIEW AS
SELECT PROVIDER_ID, AVG((METRICS:latency_ms)::FLOAT) AS AVG_LATENCY FROM DOCGEN.PROVIDER_PERFORMANCE, LATERAL FLATTEN(INPUT => METRICS) GROUP BY PROVIDER_ID;

