USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_ACCESS_CONTROL (
  ACL_ID STRING PRIMARY KEY,
  DASH_ID STRING,
  SUBJECT_REF STRING,
  PERMS VARIANT,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

