CREATE OR REPLACE VIEW DOCGEN.V_COMPLIANCE_OVERVIEW AS
SELECT TEMPLATE_ID, COUNT(*) AS EXECUTIONS, SUM(CASE WHEN RESULT:status='FAIL' THEN 1 ELSE 0 END) AS FAILS FROM DOCGEN.COMPLIANCE_EXECUTIONS GROUP BY TEMPLATE_ID;

