USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOURCE_QUOTA_FORECASTS (
  FORECAST_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  FORECAST_JSON VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

