USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOCATION_REPORTS (
  REPORT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  LINES VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

