USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QUALITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SCORE NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

