USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHURN_EVENT_REGISTRY (
  EVENT_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  REASON CLOB,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

