USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENGAGEMENT_SCORE_INDEX (
  SCORE_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SCORE NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); @31

