USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, POLICY_REF STRING, RESULT VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

