USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_LOGS ( LOG_ID STRING PRIMARY KEY, JOB_ID STRING, MESSAGE STRING, LOG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

