USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2307 ( ID STRING PRIMARY KEY, EVENT_TYPE STRING, EVENT_PAYLOAD VARIANT, EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

