USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2308 ( ID STRING PRIMARY KEY, RESOURCE_REF STRING, ACTION STRING, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

