USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACTIVITY_EXPORT_QUEUE (
  EQ_ID STRING PRIMARY KEY,
  SCOPE VARIANT,
  TARGET_STAGE STRING,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

