USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_MANIFEST (
  MANIFEST_ID STRING PRIMARY KEY,
  TARGET_STAGE STRING,
  OBJECTS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

