USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2319 ( ID STRING PRIMARY KEY, PARENT_REF STRING, PAYLOAD VARIANT, INSERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

