USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETAIN_FLAGS (
  FLAG_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

