USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETAIN_FLAG_LOGS (
  LOG_ID STRING PRIMARY KEY,
  FLAG_ID STRING,
  ACTION STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

