USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REQUESTS (
  HOLD_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  SCOPE VARIANT,
  STATUS STRING DEFAULT 'OPEN',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

