USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  TARGETS VARIANT,
  RETENTION_DAYS INT,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

