USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, NAME STRING, WINDOW_DEF VARIANT, ACTIVE BOOLEAN DEFAULT FALSE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

