USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERERS ( RENDERER_ID STRING PRIMARY KEY, NAME STRING, TYPE STRING, CONFIG VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

