USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2334 ( ID STRING PRIMARY KEY, CHECKPOINT_REF STRING, STATE VARIANT, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

