USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLLBACKS ( ROLLBACK_ID STRING PRIMARY KEY, DEPLOY_ID STRING, REASON STRING, ROLLED_BACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

