USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2336 ( ID STRING PRIMARY KEY, PLUGIN_REF STRING, CONFIG VARIANT, INSTALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

