USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2342 ( ID STRING PRIMARY KEY, CONNECTION_REF STRING, CONFIG VARIANT, LAST_TESTED_AT TIMESTAMP_LTZ );

