USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_REQUESTS (
  REFUND_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  BILLING_RUN_ID STRING,
  AMOUNT NUMBER,
  CURRENCY STRING,
  STATUS STRING DEFAULT 'PENDING',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

