USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2344 ( ID STRING PRIMARY KEY, NOTIFICATION_REF STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

