USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  REFUND_ID STRING,
  ACTION STRING,
  ACTION_BY STRING,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

