USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISPUTES (
  DISPUTE_ID STRING PRIMARY KEY,
  REFUND_ID STRING,
  ACCOUNT_ID STRING,
  REASON STRING,
  STATUS STRING DEFAULT 'OPEN',
  OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

