USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISPUTE_LOGS (
  LOG_ID STRING PRIMARY KEY,
  DISPUTE_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

