USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_PAYMENTS (
  PAYMENT_ID STRING PRIMARY KEY,
  REFUND_ID STRING,
  PAYMENT_METHOD STRING,
  AMOUNT NUMBER,
  CURRENCY STRING,
  PAID_AT TIMESTAMP_LTZ,
  META VARIANT
);

