USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RECONCILIATION (
  RECON_ID STRING PRIMARY KEY,
  PAYMENT_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

