USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AML_CHECKS (
  AML_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  CHECK_RESULT VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

