USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_STORAGE ( PDF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, S3_URL STRING, SIZE_BYTES NUMBER, HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

