USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KYC_PROFILES (
  PROFILE_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  STATUS STRING,
  VERIFIED_AT TIMESTAMP_LTZ,
  METADATA VARIANT
);

