USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDENTITY_PROVIDER_LOGS (
  LOG_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ACTION STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

