USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_TRUSTS (
  TRUST_ID STRING PRIMARY KEY,
  DEVICE_HASH STRING,
  SUBJECT_REF STRING,
  TRUST_LEVEL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

