USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_OPS_MISC_2369 ( ID STRING PRIMARY KEY, CALLBACK_URL STRING, SECRET_HASH STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

