USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  TEMPLATE_HASH STRING,
  TEMPLATE_TYPE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

