USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  SCORE FLOAT,
  ACTIONS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

