USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_ARTIFACTS (
  ARTIFACT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  TYPE STRING,
  LOCATION STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

