USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_INDEX (
  AIDX_ID STRING PRIMARY KEY,
  REF_TYPE STRING,
  REF_ID STRING,
  SUMMARY VARIANT,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

