USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_RUNS (
  RUN_ID STRING PRIMARY KEY,
  KPI_ID STRING,
  RESULT VARIANT,
  RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

