USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_METRICS (
  MET_ID STRING PRIMARY KEY,
  NAME STRING,
  TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  VALUE VARIANT
);

