USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_RETRY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  RUN_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

