USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_DELIVERY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SREP_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  DELIVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

