USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_JOBS ( JOB_ID STRING PRIMARY KEY, REQ_ID STRING, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

