USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_ESCALATIONS (
  ESC_ID STRING PRIMARY KEY,
  TICKET_ID STRING,
  LEVEL STRING,
  ESCALATED_TO STRING,
  ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

