USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEEDBACK_RECORDS (
  FB_ID STRING PRIMARY KEY,
  SOURCE STRING,
  SUBJECT_REF STRING,
  FEEDBACK VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

