USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_QUEUE ( QUEUE_ID STRING PRIMARY KEY, REQ_ID STRING, PRIORITY INT DEFAULT 100, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

