USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATIONS ( DEPREC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPRECATED_BY STRING, DEPRECATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );

