USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_MIGRATIONS ( MIG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, FROM_VERSION INT, TO_VERSION INT, MIGRATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

