USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_INBOUND ( IN_ID STRING PRIMARY KEY, CONSUMER_ID STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PROCESSED BOOLEAN DEFAULT FALSE );

