USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_PROCESS_LOGS ( LOG_ID STRING PRIMARY KEY, IN_ID STRING, STATUS STRING, DETAILS VARIANT, PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

