USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_RULES ( RULE_ID STRING PRIMARY KEY, SOURCE_PROVIDER STRING, TARGET_PROVIDERS ARRAY, CONDITIONS VARIANT, PRIORITY INT );

