USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTION STRING, DETAIL VARIANT, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

