USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIALS (
  CRED_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  CRED_TYPE STRING,
  CRED_DATA VARIANT,
  LAST_ROTATED_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

