USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIAL_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  CRED_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  DETAILS VARIANT,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

