USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ACCESS_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  DETAILS VARIANT,
  AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

