USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATE_LIMITS (
  LIMIT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  WINDOW_SECONDS INT,
  MAX_CALLS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

