USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENROLLMENT_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  TYPE STRING,
  STATUS STRING DEFAULT 'PENDING',
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

