USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INCIDENTS (
  INCIDENT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  SEVERITY STRING,
  DESCRIPTION STRING,
  STATUS STRING DEFAULT 'OPEN',
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

