USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MAINTENANCE ( MAINT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

