USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHECKSUMS (
  CHECK_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHECKSUM STRING,
  COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

