USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SUPPORT_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, NAME STRING, EMAIL STRING, PHONE STRING, META VARIANT );

