USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHECKSUM_VERIFICATIONS (
  VER_ID STRING PRIMARY KEY,
  CHECK_ID STRING,
  VERIFIED_BY STRING,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT BOOLEAN,
  DETAILS VARIANT
);

