USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COSTS ( COST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, COST_CURRENCY STRING, COST_AMOUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

