USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_QUEUE (
  ANCHOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TXHASH STRING,
  STATUS STRING DEFAULT 'QUEUED',
  ATTEMPTS INT DEFAULT 0,
  NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

