USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, COST_ID STRING, ACCOUNT_ID STRING, ALLOC_AMOUNT NUMBER, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

