USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_USAGE_ESTIMATES ( EST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, EST_WINDOW VARIANT, EST_METRICS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

