USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_EVIDENCE (
  EVID_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  PROVIDER STRING,
  LOCATION STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

