USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_FUNCTION_LOGS ( LOG_ID STRING PRIMARY KEY, EFE_ID STRING, STATUS STRING, RESPONSE VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

