USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_BACKUP_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, SNAPSHOT_PATH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

