USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENGINE_RULES (
  RULE_ID STRING PRIMARY KEY,
  NAME STRING,
  CONDITION VARIANT,
  ACTIONS VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

