USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXECUTION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  CONTEXT VARIANT,
  RESULT VARIANT,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

