USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, TARGET_REF STRING, CHECK_TYPE STRING, RESULT STRING, DETAILS VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

