USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_RECOMMENDATIONS ( REC_ID STRING PRIMARY KEY, INDEX_NAME STRING, RECOMMENDATION VARIANT, RECOMMENDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

