USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_COMMENTS (
  COMMENT_ID STRING PRIMARY KEY,
  Q_ID STRING,
  COMMENT_BY STRING,
  COMMENT_TEXT STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

