USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_APPROVAL_HISTORY (
  APPROVAL_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  APPROVED_BY STRING,
  APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  COMMENTS STRING
);

