USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_EXPORT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, EXPORT_JOB_ID STRING, AUDITED_BY STRING, AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

