USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_MASKING_RULES ( RULE_ID STRING PRIMARY KEY, FIELD_PATH STRING, MASK_EXPRESSION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

