USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
