USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_ACTIVATION_EVENTS ( EVT_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ACCOUNT_ID STRING, ACTIVATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );
