USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_PROGRESS_METRICS ( METRIC_ID STRING PRIMARY KEY, TENANT_ID STRING, STAGE STRING, PCT_COMPLETE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
