USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_RECOVERY_USAGE ( USG_ID STRING PRIMARY KEY, TOKEN_ID STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), USED_BY STRING, META VARIANT );

