USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_BILLING_PREFERENCES ( PREF_ID STRING PRIMARY KEY, TENANT_ID STRING, PREFERENCES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
