USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OTP_CODES (
  OTP_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  OTP_HASH STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  USED BOOLEAN DEFAULT FALSE
);

