USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_METHOD_INDEX ( PM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METHOD_JSON VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
