USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OTP_USAGE_LOG (
  LOG_ID STRING PRIMARY KEY,
  OTP_ID STRING,
  SIGNER_ID STRING,
  USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT STRING,
  META VARIANT
);

