USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_METHOD_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PM_ID STRING, ACTION STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
