USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_PROOFS ( PROOF_ID STRING PRIMARY KEY, TX_ID STRING, PROOF_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

