USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRIAL_CONVERSION_METRICS ( METRIC_ID STRING PRIMARY KEY, TENANT_ID STRING, CONVERSION_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
