USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_STEPS (
  STEP_ID STRING PRIMARY KEY,
  WORKFLOW_ID STRING,
  SEQ INT,
  STEP_TYPE STRING,
  STEP_CONFIG VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

