USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROMOTIONAL_CREDIT_USAGE ( USAGE_ID STRING PRIMARY KEY, CREDIT_ID STRING, USAGE_AMOUNT NUMBER, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
