USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_STEP_HISTORY (
  H_ID STRING PRIMARY KEY,
  STEP_ID STRING,
  INSTANCE_ID STRING,
  STATUS STRING,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

