USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LIFECYCLE_STATES (
  STATE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  STATE_NAME STRING,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CHANGED_BY STRING,
  META VARIANT
);

