USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_INSTANCE_TOKENS (
  TOKEN_ID STRING PRIMARY KEY,
  INSTANCE_ID STRING,
  TOKEN_HASH STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

