USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_TRIAL_METRICS ( METRIC_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, USAGE_SUMMARY VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
