USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ADMIN_ROLES ( ROLE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, USER_REF STRING, ROLE_NAME STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
