USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_ROLE_MAPPINGS (
  MAP_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  ROLE STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

