USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_USAGE_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METRIC STRING, THRESHOLD NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

