USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FLAG_NAME STRING, VALUE BOOLEAN, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

