USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_NOTIFICATIONS_LOG ( LOG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CHANNEL STRING, SUBJECT STRING, BODY CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

