USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EMAIL_SEND_LOGS (
  LOG_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TO_ADDRESS STRING,
  STATUS STRING,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

