USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_INTEGRATION_ERRORS ( ERR_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INTEGRATION STRING, ERROR_TEXT CLOB, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

