USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_IDENTITY_ALIASES ( ALIAS_ID STRING PRIMARY KEY, SIGNER_ID STRING, ALIAS_TYPE STRING, ALIAS_VALUE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

