USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_WEBHOOK_AUDIT ( AUDIT_ID STRING PRIMARY KEY, WEBHOOK_ID STRING, STATUS STRING, ATTEMPT INT, LOG_TEXT CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

