USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_TRANSCRIPTS (
  TRANSCRIPT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  ROLE STRING,
  MESSAGE TEXT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

