USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_LEGAL_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, EMAIL STRING, PHONE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

