USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOLOCATION_RECORDS (
  GEO_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

