USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ESCALATION_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, LEVEL INT, CONTACT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

