USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_LEVELS (
  TL_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  LEVEL STRING,
  SOURCE STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

