USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_PRIVACY_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, REQUESTOR STRING, REQUEST_JSON VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
-- @31 @24

