USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CONSENTS (
  CONSENT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  CONSENT_TYPE STRING,
  GIVEN_AT TIMESTAMP_LTZ,
  META VARIANT
);

