USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_DPO_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, EMAIL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

