USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_DATA_SUBJECT_REQUESTS ( DSR_ID STRING PRIMARY KEY, TENANT_ID STRING, SUBJECT_REF STRING, REQUEST_TYPE STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
-- @31 @24

