USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PII_MASKING_REGISTRY ( MASK_ID STRING PRIMARY KEY, TENANT_ID STRING, FIELD_PATTERN STRING, MASK_RULE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

