USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARE_AUDIT_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SHARE_ID STRING,
  ACTION STRING,
  ACTION_BY STRING,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

