USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PII_MASKING_APPLICATIONS ( APP_ID STRING PRIMARY KEY, MASK_ID STRING, OBJECT_NAME STRING, FIELD_NAME STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

