USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDED_MEDIA (
  MEDIA_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  MEDIA_TYPE STRING,
  LOCATION STRING,
  META VARIANT,
  UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

