USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GDPR_DATA_MAP ( MAP_ID STRING PRIMARY KEY, TENANT_ID STRING, SCHEMA JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

