USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MEDIA_ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  MEDIA_ID STRING,
  ACCESSED_BY STRING,
  ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTION STRING,
  DETAILS VARIANT
);

