USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_REVIEW_INDEX ( REVIEW_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, RESULT STRING, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

