USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, SCOPE VARIANT, LOCATION STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

