USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PREVIEW_METRICS (
  MET_ID STRING PRIMARY KEY,
  CACHE_ID STRING,
  LATENCY_MS INT,
  RENDERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

