USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_SIGNOFF_REGISTRY ( SIGNOFF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNER_REF STRING, SIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SIGNOFF_META VARIANT );
-- @31 @24

