USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_COST_CUBES ( CUBE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CUBE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

