USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CALL_USAGE (
  USG_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  WINDOW_START TIMESTAMP_LTZ,
  CALLS INT DEFAULT 0,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

