USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_MODEL_TELEMETRY ( TELE_ID STRING PRIMARY KEY, MODEL_ID STRING, METRIC_NAME STRING, METRIC_VALUE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

