USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_QUOTA_VIOLATIONS (
  VIOLATION_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  WINDOW_START TIMESTAMP_LTZ,
  CALLS INT,
  QUOTA INT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

