USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_SERVING_ROUTES ( ROUTE_ID STRING PRIMARY KEY, MODEL_ID STRING, ROUTE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

