USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_ACTIONS (
  ACTION_ID STRING PRIMARY KEY,
  HOLD_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

