USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_COMPLIANCE_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  RESULT STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

