USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_REPLAY_QUEUE (
  REPLAY_ID STRING PRIMARY KEY,
  EVENT_ID STRING,
  ATTEMPTS INT DEFAULT 0,
  NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

