USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_CANARY_RUNS ( RUN_ID STRING PRIMARY KEY, MODEL_ID STRING, TRAFFIC_PCT NUMBER, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );
-- @31 @24

