USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_REPLAY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  REPLAY_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

