USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_HEALTH_CHECKS (
  HC_ID STRING PRIMARY KEY,
  COMPONENT STRING,
  STATUS STRING,
  METRICS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

