USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_BREACHES (
  BREACH_ID STRING PRIMARY KEY,
  SLO_ID STRING,
  METRIC VARIANT,
  BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  NOTES STRING
);

