USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPLOYMENTS (
  DEPLOY_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  DEPLOYED_BY STRING,
  DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  NOTES CLOB
);

