USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPLOY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  DEPLOY_ID STRING,
  STATUS STRING,
  LOG CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

