USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEEKLY_SIGNATURE_AGGREGATES (
  AGG_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  WEEK_START DATE,
  TOTAL_SIGNATURES INT,
  FAILED_SIGNATURES INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

