USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MONTHLY_BILLING_REPORTS (
  REPORT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  REPORT_MONTH DATE,
  LINE_ITEMS VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

