USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_GENERATION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  DOCUMENT_ID STRING,
  OUTPUT_URL STRING,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

