USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_TOKENS (
  TOKEN_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  SIGNER_ID STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

