USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_THRESHOLDS (
  THRESHOLD_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  METRIC_NAME STRING,
  THRESHOLD_VALUE NUMBER,
  NOTIFY BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

