USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_EVENTS (
  REPLAY_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

