USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_USER_ACTIVITY (
  ACT_ID STRING PRIMARY KEY,
  USER_REF STRING,
  ACTIVITY_TYPE STRING,
  PAYLOAD VARIANT,
  TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

