USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THRESHOLD_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  THRESHOLD_ID STRING,
  ACCOUNT_ID STRING,
  METRIC_NAME STRING,
  VALUE NUMBER,
  NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

