USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_ASSIGNMENTS (
  ASSN_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  OPERATOR_REF STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

