USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TIMEOUTS (
  TIMEOUT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  TIMEOUT_AT TIMESTAMP_LTZ,
  HANDLED BOOLEAN DEFAULT FALSE
);

