USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_LOCK_HISTORY (
  H_ID STRING PRIMARY KEY,
  LOCK_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

