USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOTS (
  SNAP_ID STRING PRIMARY KEY,
  SNAPSHOT_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SNAP_JSON VARIANT
);

