USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSIC_EXPORT_JOBS (
  JOB_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  REQUESTOR STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

