USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSIONS (
  VERSION_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  VERSION_NUMBER INT,
  VERSION_METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

