USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_ACTIVITY (
  ACT_ID STRING PRIMARY KEY,
  REG_ID STRING,
  ACTIVITY_TYPE STRING,
  ACTIVITY_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

