USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_REQUEST_QUEUE (
  REQ_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SCOPE VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

