USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_APPROVAL_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  ACTION JSON,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

