USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_MATCH_ATTEMPTS (
  ATTEMPT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  TEMPLATE_ID STRING,
  SCORE FLOAT,
  MATCHED BOOLEAN,
  ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

