USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXCEPTION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  REQUESTOR STRING,
  DECISION STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

