USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_ESCALATION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  ALERT_ID STRING,
  ESCALATION_TO STRING,
  ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

