USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_VIOLATIONS (
  VIOL_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SLO_NAME STRING,
  DETAILS VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

