USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS (
  MW_ID STRING PRIMARY KEY,
  SERVICE_NAME STRING,
  START_AT TIMESTAMP_LTZ,
  END_AT TIMESTAMP_LTZ,
  NOTES CLOB
);

