USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSIC_EXPORTS (
  EXPORT_ID STRING PRIMARY KEY,
  ALERT_ID STRING,
  BUNDLE_REF STRING,
  STATUS STRING DEFAULT 'PENDING',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

