USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_ASSESSMENT_INDEX (
  RISK_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SCORE NUMBER,
  DETAILS VARIANT,
  ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

