USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ROLE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, ROLE_ID STRING, ADMIN_USER STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

