USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RULE_VIOLATION_AUDITS (
  AUDIT_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  SUBJECT_REF STRING,
  VIOLATION_DETAIL VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

