USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PEN_TEST_FINDINGS (
  FINDING_ID STRING PRIMARY KEY,
  TARGET STRING,
  SEVERITY STRING,
  DESCRIPTION CLOB,
  FOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

