USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_ASSIGNMENTS (
  ASSIGN_ID STRING PRIMARY KEY,
  Q_ID STRING,
  ASSIGNED_TO STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

