USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PEN_TEST_REMEDIATIONS (
  REM_ID STRING PRIMARY KEY,
  FINDING_ID STRING,
  REMEDIATION JSON,
  STATUS STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

