USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_COMPLETION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  TRAIN_ID STRING,
  USER_REF STRING,
  COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

