USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_FEEDBACK_REGISTRY (
  FB_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  RATING NUMBER,
  COMMENTS CLOB,
  SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

