USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_HISTORY (
  HIST_ID STRING PRIMARY KEY,
  ESC_ID STRING,
  SUBJECT_REF STRING,
  ACTION TAKEN STRING,
  TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

