USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_NPS_RUNS (
  RUN_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  SCORE NUMBER,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

