USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRODUCT_ANALYTICS_INDEX (
  IDX_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  METRICS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

