USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_RETIREMENT_JOBS (
  JOB_ID STRING PRIMARY KEY,
  FEATURE_NAME STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ
);

