USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGELOG_INDEX (
  CHANGE_ID STRING PRIMARY KEY,
  PATH STRING,
  SUMMARY STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

