USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_FEED ( THREAT_ID STRING PRIMARY KEY, SOURCE STRING, DETAILS VARIANT, SEVERITY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

