USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_PIPELINE_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  PIPELINE_NAME STRING,
  METRICS VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

