USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_PIPELINE_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  PIPELINE_NAME STRING,
  SEVERITY STRING,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

