USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_PIPELINE_RUN_HISTORY (
  RUN_ID STRING PRIMARY KEY,
  PIPELINE_NAME STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ
);

