USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_ALERTS ( ALERT_ID STRING PRIMARY KEY, THREAT_ID STRING, STATUS STRING DEFAULT 'OPEN', RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

