USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SHARD_MANIFEST (
  SHARD_ID STRING PRIMARY KEY,
  SNAPSHOT_ID STRING,
  SHARD_META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

