USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ESCALATIONS ( ESCAL_ID STRING PRIMARY KEY, INCIDENT_ID STRING, LEVEL INT, NOTIFIED BOOLEAN DEFAULT FALSE, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

