USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_REBUILD_JOBS (
  JOB_ID STRING PRIMARY KEY,
  INDEX_REF STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ
);

