USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_SNAPSHOT_JOBS (
  JOB_ID STRING PRIMARY KEY,
  SNAPSHOT_REF STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);

