USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESPONDER_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, ROSTER_ID STRING, MESSAGE STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);

