USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_QUERY_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  INDEX_REF STRING,
  QPS NUMBER,
  LATENCY_MS NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

