USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, COMPONENT STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

