USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_SHARD_STATS (
  STAT_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  DOC_COUNT INT,
  MEMORY_BYTES NUMBER,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

