USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_SNAPSHOT_REGISTRY (
  REG_ID STRING PRIMARY KEY,
  SNAPSHOT_ID STRING,
  INDEX_REF STRING,
  LOCATION STRING,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

