USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_QUERY_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  QUERY_TEXT STRING,
  INDEX_REF STRING,
  RESULTS_COUNT INT,
  RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

