USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRIEVAL_CACHE_HITS (
  HIT_ID STRING PRIMARY KEY,
  CACHE_ID STRING,
  QUERY_REF STRING,
  HIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

