USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_FALLBACK_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  QUERY_REF STRING,
  USED_FAISS BOOLEAN,
  USED_VECTOR BOOLEAN,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

