USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_FEEDBACK ( FB_ID STRING PRIMARY KEY, USER_ID STRING, CATEGORY STRING, COMMENTS STRING, RATING INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

