USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_SATISFACTION_METRICS ( MET_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, AVERAGE_RATING FLOAT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

