USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CONFIDENCE_INDEX (
  CONF_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CONFIDENCE_SCORE NUMBER,
  EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

