USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ANOMALY_FLAGS (
  FLAG_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  REASON STRING,
  FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

