USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BI_SIGNATURE_TRENDS (
  TREND_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  TREND_METRICS VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

