USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MIGRATION_HISTORY ( MIG_ID STRING PRIMARY KEY, SCRIPT_NAME STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), APPLIED_BY STRING, META VARIANT );

