USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_CHANGES (
  CHANGE_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  CHANGED_BY STRING,
  CHANGES VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

