USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

