USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_PLANS ( PLAN_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

