USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_INTEGRATION_REGISTRY (
  REG_ID STRING PRIMARY KEY,
  SERVICE_NAME STRING,
  CONFIG VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

