USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, PLAN_ID STRING, ACCOUNT_ID STRING, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);

