USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_INTEGRATION_ERRORS (
  ERR_ID STRING PRIMARY KEY,
  REG_ID STRING,
  ERROR_JSON VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

