USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_AGENT_TASKS (
  TASK_ID STRING PRIMARY KEY,
  AGENT_REF STRING,
  PAYLOAD VARIANT,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

