USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_BILLING_CHARGES ( CHARGE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, CURRENCY STRING, CHARGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);

