USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_AGENT_HEARTBEAT (
  HB_ID STRING PRIMARY KEY,
  AGENT_REF STRING,
  STATUS STRING,
  LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

