USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CI_ARTIFACTS_REGISTRY ( ARTIFACT_ID STRING PRIMARY KEY, NAME STRING, DESCRIPTION STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

