USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_USAGE_FORECASTS ( FORECAST_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE_KEY STRING, FORECAST_WINDOW VARIANT, FORECAST_METRICS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

