USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_EVENTS ( EVENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_ID STRING, EVENT_TYPE STRING, EVENT_PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

