USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ALERTS ( ALERT_ID STRING PRIMARY KEY, RULE_ID STRING, ACCOUNT_ID STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PAYLOAD VARIANT
);

