USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_RECONCILIATIONS ( RECON_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PERIOD_START DATE, PERIOD_END DATE, STATUS STRING DEFAULT 'PENDING', RESULT VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

