USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHARGEBACK_ENTRIES ( ENTRY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

