USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_REGISTRY ( SCHEMA_ID STRING PRIMARY KEY, NAME STRING, VERSION INT, MAPPING_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

