USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTES ( DISPUTE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INVOICE_ID STRING, REASON STRING, STATUS STRING DEFAULT 'OPEN', FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

