USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INGEST_DEADLETTER_QUEUE ( DLQ_ID STRING PRIMARY KEY, EVENT_ID STRING, ERROR_TEXT CLOB, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

