USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INGEST_RETRY_TRACKER ( TRACK_ID STRING PRIMARY KEY, EVENT_ID STRING, ATTEMPT_COUNT INT DEFAULT 0, LAST_ATTEMPT TIMESTAMP_LTZ );

