USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_HISTORY ( VH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_NUMBER INT, CHANGES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

