USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_HASH_INDEX ( HASH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, HASH STRING, COMPUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

