USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SETTLEMENT_BATCHES (
  BATCH_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  AMOUNT NUMBER,
  CURRENCY STRING,
  STATUS STRING DEFAULT 'CREATED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

