USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_CHAIN_CACHE ( CHAIN_ID STRING PRIMARY KEY, CERT_ID STRING, CHAIN_JSON VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

