USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SUBSCRIPTIONS (
  SUB_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  EVENT_NAME STRING,
  TARGET_URL STRING,
  SECRET_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

