USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KMS_KEY_REGISTRY ( KEY_ID STRING PRIMARY KEY, KEY_NAME STRING, PROVIDER STRING, METADATA VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

