USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_LOGS (
  DL_ID STRING PRIMARY KEY,
  SUB_ID STRING,
  EVENT_ID STRING,
  STATUS STRING,
  HTTP_STATUS INT,
  RESPONSE VARIANT,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

