USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  SCHEDULE VARIANT,
  MAX_ATTEMPTS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

