USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_APPROVAL_LOGS ( LOG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, APPROVAL_JSON VARIANT, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

