USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_LOGS ( LOG_ID STRING PRIMARY KEY, OPERATOR_REF STRING, MODULE STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

