USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_REVOCATIONS (
  REV_ID STRING PRIMARY KEY,
  KEY_ID STRING,
  REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  REVOKED_BY STRING,
  REASON STRING
);

