USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_USAGE (
  USG_ID STRING PRIMARY KEY,
  KEY_ID STRING,
  ENDPOINT STRING,
  CALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

