USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDENTIAL_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, CRED_REF STRING, NEXT_ROTATION AT TIMESTAMP_LTZ, LAST_ROTATED_AT TIMESTAMP_LTZ );

