USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  REQUESTER STRING,
  TARGET STRING,
  PURPOSE STRING,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

