USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, POLICY_ID STRING, CHANGE_JSON VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

