USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_AUDITS (
  AUDIT_ID STRING PRIMARY KEY,
  REQ_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

