USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_BURN_RATE ( SLO_ID STRING PRIMARY KEY, SCOPE STRING, WINDOW VARIANT, BURN_RATE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

