USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  NAME STRING,
  BODY CLOB,
  ISSUED_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ,
  META VARIANT
);

