USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_DRIFT_ALERTS ( ALERT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

