USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CACHE (
  CACHE_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RAW_RESPONSE VARIANT
);

