USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PREVIEW_CACHE ( CACHE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PREVIEW_URL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

