USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PKI_AUDIT_TRAIL (
  AUDIT_ID STRING PRIMARY KEY,
  ACTION STRING,
  SUBJECT STRING,
  DETAILS VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

