USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_POOL ( WORKER_ID STRING PRIMARY KEY, STATUS STRING, LAST_HEARTBEAT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

