USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_CACHE_INDEX ( CACHE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, URL STRING, SIZE_BYTES NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

