USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_REFERENCES (
  KEY_REF_ID STRING PRIMARY KEY,
  HSM_KEY_ID STRING,
  PURPOSE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

