USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, POLICY_ID STRING, TENANT_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

