USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_USAGE_LOGS (
  LOG_ID STRING PRIMARY KEY,
  KEY_REF_ID STRING,
  OPERATION STRING,
  USER STRING,
  USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

