USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_CHALLENGE_LOGS ( CHAL_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHOD STRING, STATUS STRING, TRIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

