USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHZ_DECISION_LOGS ( LOG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, RESOURCE_REF STRING, DECISION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

