USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONNECTOR_HEALTH (
  HEALTH_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  STATUS STRING,
  LAST_CHECKED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

