USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TEST_PAYLOADS (
  PAYLOAD_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  NAME STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

