USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_HEALTH_EVENTS ( EVENT_ID STRING PRIMARY KEY, COMPONENT STRING, STATUS STRING, DETAILS VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

