USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TARGET_TABLE STRING, ROW_COUNT NUMBER, PURGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

