USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ONBOARDING_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ACTION STRING,
  BY_USER STRING,
  TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

