USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_EXEMPTIONS ( EXEMPT_ID STRING PRIMARY KEY, HOLD_ID STRING, OBJECT_REF STRING, EXEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

