USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_DEPRECATION_SCHEDULE (
  SCHED_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  DEPRECATE_AT TIMESTAMP_LTZ,
  NOTE STRING
);

