USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MIGRATION_TASKS (
  TASK_ID STRING PRIMARY KEY,
  FROM_PROVIDER STRING,
  TO_PROVIDER STRING,
  STATUS STRING DEFAULT 'PENDING',
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

