USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, VEND_ID STRING, DESCRIPTION CLOB, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

