USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_INCIDENT_RESPONSES ( RESP_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTIONS VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

