USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RBAC_ROLES (
  ROLE_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ROLE_NAME STRING,
  PERMISSIONS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

