USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_CONSUMPTION ( CONSUMPTION_ID STRING PRIMARY KEY, TENANT_ID STRING, METRIC_NAME STRING, CONSUMED NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

