USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_BREACH_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, LIMIT_NAME STRING, BREACH_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

