USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_HISTORY (
  HIST_ID STRING PRIMARY KEY,
  SLA_ID STRING,
  SNAPSHOT VARIANT,
  TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

