USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_EVENT_HANDLERS ( HANDLER_ID STRING PRIMARY KEY, EVENT_TYPE STRING, HANDLER_CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

