USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_TRENDS (
  TREND_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  PERIOD_START DATE,
  PERIOD_END DATE,
  METRICS VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

