USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_INGEST ( TLM_ID STRING PRIMARY KEY, SOURCE STRING, PAYLOAD VARIANT, INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

