USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CHANGE_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  REQUESTED_BY STRING,
  CHANGE_JSON VARIANT,
  STATUS STRING DEFAULT 'OPEN',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

