USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCHAIN_ANCHOR_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MANIFEST_ID STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

