USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_PUBLISH_JOBS ( JOB_ID STRING PRIMARY KEY, MANIFEST_ID STRING, PROVIDER_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

