USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ROLLBACK_PLANS (
  PLAN_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  PLAN VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

