USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_AGGREGATES ( AGG_ID STRING PRIMARY KEY, AGG_KEY STRING, PAYLOAD VARIANT, AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

