USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_POSTMORTEMS (
  PM_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  SUMMARY VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

