USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_CLIENT_REGISTRY ( CLIENT_ID STRING PRIMARY KEY, CLIENT_NAME STRING, REDIRECT_URIS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

