USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_CONSENT_LOGS ( LOG_ID STRING PRIMARY KEY, CLIENT_ID STRING, SUBJECT_REF STRING, SCOPE VARIANT, CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

