USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_WEBHOOK_REGISTRY ( WEBHOOK_ID STRING PRIMARY KEY, PROVIDER_ID STRING, ENDPOINT STRING, SECRET_HASH STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

