USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPLIANCE_CERTS (
  PC_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  CERT_REF STRING,
  ISSUED_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ
);

