USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_GEO_RESTRICTIONS (
  GR_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  ALLOWED_REGIONS ARRAY,
  DENIED_REGIONS ARRAY,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

