USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STREAM_PROCESSING_METRICS ( METRIC_ID STRING PRIMARY KEY, STREAM_NAME STRING, LAG_MS NUMBER, THROUGHPUT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

