USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_CONCURRENCY_LOCKS ( LOCK_ID STRING PRIMARY KEY, TASK_NAME STRING, HOLDER STRING, ACQUIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

