USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPLIANCE_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  CHECK_NAME STRING,
  RESULT VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

