USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_WINDOWS (
  WINDOW_ID STRING PRIMARY KEY,
  NAME STRING,
  WINDOW_SECONDS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

