USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_EXECUTION_LOG ( LOG_ID STRING PRIMARY KEY, PB_ID STRING, EXECUTOR STRING, RESULT VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

