USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_EXEMPTIONS ( EXEMPT_ID STRING PRIMARY KEY, TENANT_ID STRING, SLO_NAME STRING, REASON CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

