USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_HEALTH_INDEX ( HEALTH_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, DETAILS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

