USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOC_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, TAG_KEY STRING, ENTITY_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

