USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_RETENTION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );

