USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_BILLING_EXCEPTIONS ( EXC_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INVOICE_REF STRING, REASON CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

