USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_AUDIT_LOG (
  AUDIT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  ROLE_ASSIGNED STRING,
  ASSIGNED_BY STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

