USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPOSURE_INDEX ( EXPOSURE_ID STRING PRIMARY KEY, AUDIT_REF STRING, SUBJECT_REF STRING, EXPOSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

