USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FLAG_RESOLUTIONS (
  RES_ID STRING PRIMARY KEY,
  FLAG_ID STRING,
  RESOLVED_BY STRING,
  RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  NOTES STRING
);

