USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEPRECATION_INDEX ( DEP_ID STRING PRIMARY KEY, FEATURE_NAME STRING, DEPRECATION_DATE TIMESTAMP_LTZ, NOTES CLOB );

