USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEPRECATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, DEP_ID STRING, RECIPIENT STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

