USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  REQUESTED_BY STRING,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

