USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RETENTION_INDEX ( INDEX_ID STRING PRIMARY KEY, TENANT_ID STRING, RETENTION_DAYS INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

