USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RETENTION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RETENTION_DAYS INT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

