USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_DASHBOARD_INDEX ( DASH_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

