USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTI_REGION_CONFIG (
  CONFIG_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  REGION STRING,
  CONFIG VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

