USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_IMPACT_ANALYSIS ( ANALYSIS_ID STRING PRIMARY KEY, CHANGE_REF STRING, IMPACT_JSON VARIANT, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

