USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGIONAL_DATA_LOCATIONS (
  LOC_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  REGION STRING,
  STORAGE_LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

