USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  CONTENT VARIANT,
  EFFECTIVE_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

