USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QA_ISSUE_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, ISSUE_ID STRING, AUTHOR STRING, BODY CLOB, COMMENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

