USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SEARCH_ALIASES ( ALIAS_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ALIAS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
