USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_ROLE_MAPPINGS (
  MAPPING_ID STRING PRIMARY KEY,
  ROLE_NAME STRING,
  AUDIT_SCOPE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

