USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_USAGE_STATS_MV ( MV_ID STRING PRIMARY KEY, CLAUSE_ID STRING, TENANT_ID STRING, USAGE_COUNT NUMBER, LAST_USED_AT TIMESTAMP_LTZ );
