USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_REPLICATION_QUEUE (
  Q_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TARGET_REGION STRING,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

