USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUALITY_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REVIEWER STRING, SCORE NUMBER, NOTES CLOB, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
