USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ISSUE_TRACKER ( ISSUE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REPORTER STRING, SEVERITY STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
