USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_COLLISION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, COLLISION_REASON STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
