USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ASYNC_CALLBACK_REGISTRY ( CALLBACK_ID STRING PRIMARY KEY, TARGET_URL STRING, METHOD STRING, CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
