USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CALL_AUDIT ( CALL_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, STATUS_CODE INT, RESPONSE_TIME_MS NUMBER, CALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
