USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOCK_AUDIT_LOG ( AUDIT_ID STRING PRIMARY KEY, LOCK_ID STRING, ACTION STRING, BY_WHOM STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
