USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_VIOLATIONS (
  VIOLATION_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  SUBJECT_REF STRING,
  DETAILS VARIANT,
  DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

