USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_INDEX ( DISPUTE_ID STRING PRIMARY KEY, INVOICE_ID STRING, ACCOUNT_ID STRING, REASON CLOB, STATUS STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
