USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_ESCROWS (
  ESCROW_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  HOLD_REASON STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

