USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIONS (
  ACTION_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ACTION STRING,
  TARGET_REF STRING,
  ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

