USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_GATEWAY_EVENTS ( EVENT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, INVOICE_ID STRING, EVENT_PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
