USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SESSIONS (
  SESSION_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  START_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  END_AT TIMESTAMP_LTZ,
  META VARIANT
);

