USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AUDIT_TRAIL (
  AUDIT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  ACTION STRING,
  TIMESTAMP_LTZ TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

