USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTITLEMENT_CACHE ( CACHE_KEY STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE_NAME STRING, IS_ENTITLED BOOLEAN, EXPIRES_AT TIMESTAMP_LTZ );

