USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  TARGET_ROLE STRING,
  MESSAGE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

