USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISCOUNT_APPLICATIONS ( APP_ID STRING PRIMARY KEY, INVOICE_ID STRING, DETAIL VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
