USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHARGEBACK_REGISTRY ( CB_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT NUMBER, REASON CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
