USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_REPORTING_JOBS ( JOB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PERIOD_START DATE, PERIOD_END DATE, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
