USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  REQUESTED_BY STRING,
  POLICY_ID STRING,
  CHANGE JSON,
  STATUS STRING DEFAULT 'OPEN',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

