USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_APPROVALS (
  APPROVAL_ID STRING PRIMARY KEY,
  REQ_ID STRING,
  APPROVED_BY STRING,
  APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  NOTES STRING
);

