USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_PDF_STORE ( PDF_ID STRING PRIMARY KEY, INVOICE_ID STRING, URL STRING, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
