USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_MANIFESTS (
  MANIFEST_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  FILE_LIST ARRAY,
  STAGE_LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

