USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, INVOICE_ID STRING, ACCESSOR STRING, ACTION STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
