USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_SNAPSHOT_MANIFEST ( SNAP_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
