USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  ACTION STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

