USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EVENT_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, TYPE_ID STRING, TEMPLATE_CLOB CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
