USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_ACTIVATION_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
