USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_FEATURE_PRICING ( PRICING_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE_NAME STRING, PRICE_PER_UNIT NUMBER, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ );

