USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_TICKETS (
  TICKET_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  SUBJECT STRING,
  DESCRIPTION STRING,
  STATUS STRING DEFAULT 'OPEN',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

