USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_NOTIFICATION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, CHANNEL STRING, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); FILENAME: sql/ddl/2901_signature_customer_notification_history.sql
USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_NOTIFICATION_HISTORY ( HIST_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
