USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_SLA_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  PERIOD_START DATE,
  PERIOD_END DATE,
  AVG_RESPONSE_TIME_MS NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

