USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMMUNITY_FEEDBACK_INDEX ( FB_ID STRING PRIMARY KEY, TENANT_ID STRING, FEEDBACK_JSON VARIANT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
