USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_DOCUMENT_INDEX ( DOC_ID STRING PRIMARY KEY, NAME STRING, SCOPE STRING, LOCATION STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
