USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATE_INDEX ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, CERT_META VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
