USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_VALUES (
  VALUE_ID STRING PRIMARY KEY,
  KPI_ID STRING,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  VALUE VARIANT
);

