USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_ASSIGNMENTS_V2 ( ASSIGN_ID STRING PRIMARY KEY, PROFILE_ID STRING, TENANT_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

