USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_PLAYBOOKS (
  PLAYBOOK_ID STRING PRIMARY KEY,
  NAME STRING,
  STEPS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

