USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_RUNS (
  RUN_ID STRING PRIMARY KEY,
  PLAYBOOK_ID STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT VARIANT
);

