USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_QUALITY_METRICS ( METRIC_ID STRING PRIMARY KEY, BUNDLE_ID STRING, METRIC_NAME STRING, METRIC_VALUE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
