USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_FEATURE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, ACTION STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
