USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_REFERENCES (
  REF_ID STRING PRIMARY KEY,
  ORIGINAL_REF STRING,
  ARCHIVE_LOCATION STRING,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

