USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, NAME STRING, ENABLED BOOLEAN DEFAULT TRUE, SCOPE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

