USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_CONSENT_AUDIT AS
SELECT CONSENT_ID, SUBJECT_REF, CONSENT_TYPE, GIVEN_AT, META FROM DOCGEN.SIGNATURE_CONSENTS;

