USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SUCCESS_CONTACTS ( CS_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, EMAIL STRING, ROLE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
