USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SUCCESS_INTERVENTIONS ( INTERV_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INTERVENTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );
