USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_STATS ( STAT_ID STRING PRIMARY KEY, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, TOTAL_VERIFICATIONS INT, SUCCESSFUL INT, FAILED INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

