USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_TOKENS ( TOKEN_ID STRING PRIMARY KEY, SUBJECT_REF STRING, TOKEN_HASH STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REVoked BOOLEAN DEFAULT FALSE
);
