USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEATURE_FLAGS_HISTORY ( HIST_ID STRING PRIMARY KEY, FLAG_NAME STRING, OLD_VALUE BOOLEAN, NEW_VALUE BOOLEAN, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
