USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_METRICS ( METRIC_ID STRING PRIMARY KEY, SESSION_ID STRING, DURATION_MS INT, EVENTS_COUNT INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

