USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CAPACITY_PLANS ( PLAN_ID STRING PRIMARY KEY, SERVICE_REF STRING, CAPACITY_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
