USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATIONS ( ANNOTATION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PAGE_NUMBER INT, ANNOTATOR STRING, NOTE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
