USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATIONS ( DEPRECATION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPRECATE_AT TIMESTAMP_LTZ, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

