USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPRECATION_NOTICE_REGISTRY ( NOTICE_ID STRING PRIMARY KEY, FEATURE_NAME STRING, NOTICE CLOB, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
