USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_COMPAT_MATRIX ( MATRIX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PLATFORM STRING, SUPPORTED BOOLEAN, NOTES STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

