USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PERMISSIONS ( PERM_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ENTITY_REF STRING, PERMISSIONS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
