USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPENDENCY_IMPACT_INDEX ( IDX_ID STRING PRIMARY KEY, ENTITY_REF STRING, IMPACT_JSON VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
