USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PARSING_ERRORS ( ERROR_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ERROR_MSG STRING, TRACE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

