USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_TOOL_USAGE ( USAGE_ID STRING PRIMARY KEY, TOOL_ID STRING, USER_REF STRING, ACTION STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
