USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCESSED_BY STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ACTION STRING, META VARIANT
);

