USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CHANGE_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CHANGED_BY STRING, CHANGE JSON, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
