USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UPGRADE_MIGRATION_JOBS ( JOB_ID STRING PRIMARY KEY, DESCRIPTION CLOB, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );
