USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_CANDIDATE_REGISTRY ( RC_ID STRING PRIMARY KEY, VERSION STRING, ARTIFACTS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
