USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THUMBNAIL_INDEX ( THUMB_ID STRING PRIMARY KEY, BUNDLE_ID STRING, URL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

