USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_CANDIDATE_VALIDATION ( VAL_ID STRING PRIMARY KEY, RC_ID STRING, RESULT VARIANT, VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
