USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCR_OUTPUTS ( OCR_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PAGE_NUMBER INT, TEXT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

