USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPLOY_HISTORY ( DEP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ENVIRONMENT STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DEPLOYED_BY STRING, META VARIANT
);
