USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ARCHIVE ( ARCHIVE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ARCHIVE_CONTENT VARIANT, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
