USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_UPGRADE_NOTES ( NOTE_ID STRING PRIMARY KEY, SERVICE_REF STRING, NOTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
