USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RESTORE_JOBS ( JOB_ID STRING PRIMARY KEY, ARCHIVE_ID STRING, TARGET_TEMPLATE_ID STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
