USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECRETS_META ( META_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SECRET_KEY STRING, SECRET_META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

