USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPENDENCY_GRAPH ( EDGE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPENDS_ON_TEMPLATE_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
