USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_HEALTH ( HEALTH_ID STRING PRIMARY KEY, TARGET_STAGE STRING, LAST_SYNCHRONIZED TIMESTAMP_LTZ, STATUS STRING, DETAILS VARIANT
);

