USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPENDENCY_CYCLES ( CYCLE_ID STRING PRIMARY KEY, TEMPLATE_IDS ARRAY, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
