USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CREDENTIAL_AUDIT ( AUDIT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, ACTION STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

