USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOB_PART_INDEX ( PART_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PART_NUMBER INT, LOCATION STRING, SIZE_BYTES NUMBER, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

