USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_CONFIG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, KEY_NAME STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

