USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_INTEGRITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHECKSUM STRING, RESULT STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

