USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_TAMPER_ALERTS ( ALERT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, REASON STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);

