USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STREAM_REPLAY_REQUESTS ( REQ_ID STRING PRIMARY KEY, STREAM_NAME STRING, START_OFFSET STRING, END_OFFSET STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

