USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOURCE_QUOTA_CONSUMPTION ( CONS_ID STRING PRIMARY KEY, QUOTA_ID STRING, SUBJECT_REF STRING, CONSUMED NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

