USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_BREACH_ALERTS ( ALERT_ID STRING PRIMARY KEY, QUOTA_ID STRING, SUBJECT_REF STRING, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @1 @31 @24

