USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_USAGE_QUOTAS ( QUOTA_ID STRING PRIMARY KEY, KEY_REF_ID STRING, MAX_OPERATIONS INT, WINDOW_SECONDS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

