USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESS_REQUESTS ( REQ_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
