USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_ALERT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ALERT_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ ); @1 @31 @24

