USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_MAINTENANCE_HISTORY ( HIST_ID STRING PRIMARY KEY, MW_ID STRING, PERFORMED_BY STRING, STATUS STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

