USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_USAGE_COUNTERS ( COUNTER_ID STRING PRIMARY KEY, KEY_REF_ID STRING, WINDOW_START TIMESTAMP_LTZ, OPS INT DEFAULT 0, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

