USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EVENT STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);
