USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTO_ARCHIVE_RULES ( RULE_ID STRING PRIMARY KEY, TEMPLATE_FILTER VARIANT, ARCHIVE_AFTER_DAYS INT, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
