USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, VERSION_ID STRING, TENANT_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

