USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_IMPACT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, PIA_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ ); @1 @31 @24

