USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETENTION_EXEMPTIONS ( EXEMPT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REASON STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
