USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_ACCESS_CONTROLS ( AC_ID STRING PRIMARY KEY, EXPORT_ID STRING, GRANTED_TO STRING, PERMISSIONS VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

