USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SCHEMA_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, COMMENT TEXT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
