USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_CLASSIFICATION_INDEX ( CLASS_ID STRING PRIMARY KEY, FIELD_REF STRING, CLASSIFICATION STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

