USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_JOB_SCHEDULES ( SCHEDULE_ID STRING PRIMARY KEY, NAME STRING, CRON_EXPR STRING, LAST_RUN TIMESTAMP_LTZ, ENABLED BOOLEAN DEFAULT TRUE
);

