USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_JOB_RUNS ( RUN_ID STRING PRIMARY KEY, SCHEDULE_ID STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENDED_AT TIMESTAMP_LTZ, STATUS STRING, RESULT VARIANT
);

