USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_TABLE STRING, TARGET_COLUMN STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

