USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EDITOR_ACTIVITY ( ACT_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTION STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT
);
