USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURE_CONFIG_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, KEY_NAME STRING, REQUESTOR STRING, CHANGE_JSON VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

