USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_REGISTRY ( COMPLAINT_ID STRING PRIMARY KEY, TENANT_ID STRING, SUBJECT_REF STRING, DESCRIPTION CLOB, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

