USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVERT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REVERTED_TO_VERSION INT, REVERTED_BY STRING, REVERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES STRING
);
