USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_REGISTRATIONS ( CLIENT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, REDIRECT_URIS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

