USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVOCATION_LOGS ( LOG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, RESOURCE_REF STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB ); @1 @31 @24

