USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_SECURITY_REVIEW_QUEUE ( REQ_ID STRING PRIMARY KEY, ITEM_JSON VARIANT, STATUS STRING, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1 @31 @24

