USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PUBLISH_METRICS ( METRIC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PUBLISH_ATTEMPTS INT, LAST_ATTEMPT_AT TIMESTAMP_LTZ, SUCCESS_RATE FLOAT
);
