USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_MANIFESTS ( MANIFEST_ID STRING PRIMARY KEY, BUNDLE_ID STRING, DESTINATION VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

