USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, KEY_ID STRING, SUBJECT_REF STRING, ACTION STRING, ACCESS_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

