USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENT_UPDATES ( UPDATE_ID STRING PRIMARY KEY, INCIDENT_ID STRING, UPDATED_BY STRING, UPDATE_TEXT STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

