USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_UUID_INDEX ( UUID_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SIGNATURE_UUID STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

