USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_NOTIFICATION_PREFERENCES ( PREF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PREFERENCES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
