USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REQUESTED_BY STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
