USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_IP_LOOKUP_CACHE ( CACHE_ID STRING PRIMARY KEY, IP_ADDR STRING, GEO_JSON VARIANT, LAST_LOOKUP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

