USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, FINGERPRINT_ID STRING, RISK_SCORE NUMBER, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

