USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUSPICIOUS_ACTIVITY_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ACTIVITY_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

