USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_APPLICATIONS ( APP_ID STRING PRIMARY KEY, RULE_ID STRING, TARGET_REF STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

