USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BEHAVIORAL_EVENT_STORE ( EVENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

