USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BEHAVIORAL_ANOMALY_LOGS ( LOG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, MODEL_ID STRING, SCORE NUMBER, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

