USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_VERSION_INDEX ( VERSION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VERSION_NUMBER INT, BODY VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

