USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_RESPONSE_TIMES ( RT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, AVERAGE_MS NUMBER, SAMPLE_COUNT INT, MEASURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

