USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_RESPONSE_ALERTS ( ALERT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, THRESHOLD_MS NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

