USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  BODY STRING,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

