USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEGRADATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, SERVICE_REF STRING, SEVERITY STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

