USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_AUDIT_TASKS ( TASK_ID STRING PRIMARY KEY, SCOPE VARIANT, OWNER STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

