USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_REQUESTS ( REQ_ID STRING PRIMARY KEY, SESSION_ID STRING, REASON STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

