USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_STEWARD_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, STEWARD_REF STRING, SCOPE VARIANT, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

