USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VIDEO_EVIDENCE_INDEX ( VIDEO_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, DURATION_MS NUMBER, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

