USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVERNANCE_MEETING_MINUTES ( MIN_ID STRING PRIMARY KEY, TITLE STRING, MINUTES CLOB, MEETING_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

