USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PUSH_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  DEVICE_TOKEN STRING,
  CONTEXT VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  ATTEMPTS INT DEFAULT 0,
  NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

