USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REVIEW_QUEUE ( REQ_ID STRING PRIMARY KEY, HOLD_ID STRING, REVIEWER STRING, STATUS STRING, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

