USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PUSH_DELIVERY_LOG (
  LOG_ID STRING PRIMARY KEY,
  QUEUE_ID STRING,
  STATUS STRING,
  PROVIDER_RESPONSE VARIANT,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

