USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_SUBSCRIBERS (
  SUB_ID STRING PRIMARY KEY,
  EVENT_NAME STRING,
  TARGET STRING,
  DELIVERY_METHOD STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

