USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_EVENT_INDEX ( EVENT_IDX_ID STRING PRIMARY KEY, EVENT_REF STRING, SEVERITY STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

