USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHENTICATION_ANOMALIES ( ANOM_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ANOMALY_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

