USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDENTIAL_USE_METRICS ( METRIC_ID STRING PRIMARY KEY, CRED_REF STRING, USAGE_COUNT NUMBER, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

