USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGED_ACCESS_SESSIONS ( SESSION_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ADMIN_USER STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENDED_AT TIMESTAMP_LTZ ); @31

