USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_VERSION_DEPRECATION ( DEP_ID STRING PRIMARY KEY, MODEL_ID STRING, VERSION STRING, DEPRECATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

