USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PERFORMANCE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, OPERATOR_REF STRING, PERIOD_START DATE, PERIOD_END DATE, SUMMARY CLOB, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

