USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAG_INDEX (
  IDX_ID STRING PRIMARY KEY,
  TAG STRING,
  TEMPLATE_IDS ARRAY,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

