USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_HANDOFF_LOGS ( LOG_ID STRING PRIMARY KEY, ROT_ID STRING, HANDOFF_JSON VARIANT, HANDOFF_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

