USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_QUERY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  QUERY_TEXT STRING,
  USER_REF STRING,
  RESULTS_COUNT INT,
  RUNTIME_MS INT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

