USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_ANALYTICS (
  ANALYTIC_ID STRING PRIMARY KEY,
  PERIOD_START TIMESTAMP_LTZ,
  PERIOD_END TIMESTAMP_LTZ,
  TOP_QUERIES VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

