USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TASK_RETRY_QUEUE ( QUEUE_ID STRING PRIMARY KEY, TASK_NAME STRING, PAYLOAD VARIANT, NEXT_RUN_AT TIMESTAMP_LTZ, ATTEMPT INT DEFAULT 0, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

