USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TASK_DEAD_LETTER ( DLQ_ID STRING PRIMARY KEY, ORIG_QUEUE_ID STRING, ERROR_MSG STRING, PAYLOAD VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

