USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.JOB_RUN_HEARTBEAT ( HEARTBEAT_ID STRING PRIMARY KEY, JOB_REF STRING, STATUS STRING, LAST_HEARTBEAT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

