USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_QUERY_METRICS ( METRIC_ID STRING PRIMARY KEY, QUERY_REF STRING, LATENCY_MS NUMBER, RESULT_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

