USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_SUGGESTIONS (
  SUGG_ID STRING PRIMARY KEY,
  TERM STRING,
  SCORE FLOAT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

