USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_CACHE_INDEX ( CACHE_ID STRING PRIMARY KEY, QUERY_HASH STRING, RESULTS VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

