USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_REQUESTS ( REQ_ID STRING PRIMARY KEY, QUERY_TEXT CLOB, TENANT_ID STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

