USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTO_SUGGEST_JOBS (
  JOB_ID STRING PRIMARY KEY,
  STATUS STRING DEFAULT 'PENDING',
  SCHEDULED_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

