USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_STATUS ( WORKER_ID STRING PRIMARY KEY, HOSTNAME STRING, STATUS STRING, LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @31 @24

