USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INGEST_SCHEMA_VERSIONS ( SCHEMA_VER_ID STRING PRIMARY KEY, SOURCE STRING, VERSION_NUMBER INT, MAPPING JSON, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

