USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_SAT_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  THRESHOLD FLOAT,
  LAST_EVALUATED TIMESTAMP_LTZ,
  STATUS STRING DEFAULT 'OK'
);

