USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_WEBHOOK_HEALTH ( HEALTH_ID STRING PRIMARY KEY, PROVIDER_ID STRING, LAST_RECEIVED_AT TIMESTAMP_LTZ, STATUS STRING, METRICS VARIANT ); @31 @24

