USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EVENT_PARSED ( EVENT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, DOCUMENT_ID STRING, SIGNER_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, PARSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

