USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CURRENCY_RATE_FEEDS ( FEED_ID STRING PRIMARY KEY, PROVIDER STRING, RATES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

