USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EVENT_RAW ( RAW_ID STRING PRIMARY KEY, PROVIDER_ID STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), HANDLED BOOLEAN DEFAULT FALSE ); @31 @24

