USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_REFERENCE_INDEX ( REF_ID STRING PRIMARY KEY, INVOICE_ID STRING, EXTERNAL_REF STRING, MAPPED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

