USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RECON_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RUN_REF STRING, STATUS STRING, DETAILS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

