USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INCIDENT_INDEX ( INCIDENT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SUMMARY CLOB, OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

