USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONFIGS ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, TYPE STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
