USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CONTRACT_JSON VARIANT, SIGNED_AT TIMESTAMP_LTZ ); @31 @24

