USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ALERTS ( ALERT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SEVERITY STRING, MESSAGE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
