USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_ROLLOUT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ACTION STRING, BY STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

