USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_TELEMETRY_AGGREGATES ( AGG_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, AGG_PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

