USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOIP_LOOKUP_CACHE (
  LOOKUP_ID STRING PRIMARY KEY,
  IP_ADDRESS STRING,
  GEO_INFO VARIANT,
  LOOKED_UP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

