USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FLAG_NAME STRING, CHANGED_BY STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

