USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_ROLLOUT_HISTORY ( HIST_ID STRING PRIMARY KEY, ROLL_ID STRING, EVENT_JSON VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

