USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_PROCESS_QUEUE ( Q_ID STRING PRIMARY KEY, INBOUND_ID STRING, STATUS STRING DEFAULT 'QUEUED', ATTEMPTS INT DEFAULT 0, NEXT_RUN_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
