USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_EVENT_INDEX (
  SEI_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  EVENT_REF STRING,
  EVENT_TYPE STRING,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

