USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_POLICY ( POLICY_ID STRING PRIMARY KEY, NAME STRING, BACKOFF_SECONDS ARRAY, MAX_ATTEMPTS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
