USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  ALERT_TYPE STRING,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

