USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_REPORT_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCOPE VARIANT, STATUS STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

