USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DLQ ( DLQ_ID STRING PRIMARY KEY, INBOUND_ID STRING, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ERROR_MSG STRING, HANDLED BOOLEAN DEFAULT FALSE
);
