USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TOKENS ( SESSION_ID STRING PRIMARY KEY, SUBJECT_REF STRING, TOKEN_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ, META VARIANT
);
