USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PRIVACY_TRAINING_LOGS ( LOG_ID STRING PRIMARY KEY, USER_REF STRING, COURSE_REF STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

