USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_REGISTRY_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, MODEL_ID STRING, USER_REF STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

