USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_RULES (
  RULE_ID STRING PRIMARY KEY,
  PRIMARY_PROVIDER STRING,
  SECONDARY_PROVIDER STRING,
  CONDITIONS VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

