USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SWITCH_LOGS (
  LOG_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  FROM_PROVIDER STRING,
  TO_PROVIDER STRING,
  SWITCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

