USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_DEPLOYMENT_HISTORY ( DEPLOY_ID STRING PRIMARY KEY, MODEL_ID STRING, VERSION STRING, DEPLOYED_BY STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

