USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENCRYPTION_KEYS_METADATA (
  KEY_ID STRING PRIMARY KEY,
  KEY_ALIAS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ROTATED_AT TIMESTAMP_LTZ,
  META VARIANT
);

