USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_SERVING_METRICS ( METRIC_ID STRING PRIMARY KEY, MODEL_ID STRING, LATENCY_MS NUMBER, ERROR_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

