CREATE OR REPLACE TABLE DOCGEN.PKI_CERTIFICATE_STORE (CERT_ID STRING PRIMARY KEY, FINGERPRINT STRING, CERT_BLOB STRING, INSERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE TABLE DOCGEN.PKI_OCSP_STATUS (OCSP_ID STRING PRIMARY KEY, CERT_FINGERPRINT STRING, OCSP_RESPONSE VARIANT, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());

PKI certificate and OCSP tables implement the evidence & PKI lifecycle storage required for compliance and OCSP polling in your PKI design artifacts @74 @111. @74 @111

