USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEEDBACK_INDEX ( FB_ID STRING PRIMARY KEY, ADMIN_USER STRING, FEEDBACK_JSON VARIANT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

