USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SERVICE_SLO_DEFINITIONS ( SLO_ID STRING PRIMARY KEY, SERVICE_REF STRING, SLO_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

