USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LIVENESS_CHECKS ( CHECK_ID STRING PRIMARY KEY, SESSION_ID STRING, CHECK_TYPE STRING, RESULT STRING, DETAILS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
