USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DEVELOPER_NOTES_INDEX ( NOTE_ID STRING PRIMARY KEY, PATH STRING, SUMMARY STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

