USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_SCHEDULE (
  SCHEDULE_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  NEXT_POLL_AT TIMESTAMP_LTZ,
  POLL_INTERVAL_SECONDS INT,
  ENABLED BOOLEAN DEFAULT TRUE
);

