USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SCHEDULE_ID STRING,
  STATUS STRING,
  RESPONSE VARIANT,
  POLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

