USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSE_ACTIONS ( ACTION_ID STRING PRIMARY KEY, INCIDENT_ID STRING, STEP_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ ); @31 @24

