USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_HISTORY ( HIST_ID STRING PRIMARY KEY, OPERATOR_REF STRING, SHIFT_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

