USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPS_RUNBOOKS ( RUNBOOK_ID STRING PRIMARY KEY, NAME STRING, CONTENT CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
