USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEPRECATION_NOTICES ( NOTICE_ID STRING PRIMARY KEY, FEATURE_NAME STRING, NOTICE_CLOB CLOB, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

