USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_PLAYBOOKS ( PLAYBOOK_ID STRING PRIMARY KEY, INCIDENT_TYPE STRING, STEPS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
