USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RELEASE_POSTMORTEMS ( PM_ID STRING PRIMARY KEY, RELEASE_REF STRING, SUMMARY CLOB, ACTIONS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

