USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SERVICE_OWNERSHIP_INDEX ( OWN_ID STRING PRIMARY KEY, SERVICE_REF STRING, OWNER_REF STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

