USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_POLICY_RULES (
  RULE_ID STRING PRIMARY KEY,
  NAME STRING,
  CONDITIONS VARIANT,
  ACTIONS VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

