USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_REVISION_HISTORY ( REV_ID STRING PRIMARY KEY, RUNBOOK_REF STRING, AUTHOR STRING, NOTES CLOB, REVISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

