USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_VIOLATION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  SLA_ID STRING,
  ACCOUNT_ID STRING,
  VIOLATION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

