USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.BILLING_AUDIT_TRAIL_MV ( MV_ID STRING PRIMARY KEY, RUN_REF STRING, AGG_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

