USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_FEEDBACK_AGGREGATES ( AGG_ID STRING PRIMARY KEY, TENANT_ID STRING, METRICS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

