USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FEATURE_ADOPTION_METRICS ( METRIC_ID STRING PRIMARY KEY, FEATURE_NAME STRING, TENANT_ID STRING, ADOPTION_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

