USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_HEALTH_SCORES ( SCORE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCORE NUMBER, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

