USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ESCALATION_RUNS (
  RUN_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  INCIDENT_ID STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT VARIANT
);

