USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_CHURN_METRICS ( METRIC_ID STRING PRIMARY KEY, TENANT_ID STRING, CHURN_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

