USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_KB_ARTICLES (
  ARTICLE_ID STRING PRIMARY KEY,
  TITLE STRING,
  BODY CLOB,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

