USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SUPPORT_SLA_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, CASE_ID STRING, SLA_REF STRING, VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

