USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_EVALUATIONS (
  EVAL_ID STRING PRIMARY KEY,
  SLA_ID STRING,
  PERIOD_START TIMESTAMP_LTZ,
  PERIOD_END TIMESTAMP_LTZ,
  METRICS VARIANT,
  RESULT VARIANT,
  EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

