USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CS_ENGAGEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ACTIVITY_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

