USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DASHBOARD_RUNS (
  RUN_ID STRING PRIMARY KEY,
  DASH_ID STRING,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT VARIANT
);

