USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_PLAN ( PLAN_ID STRING PRIMARY KEY, OPERATOR_REF STRING, PLAN_JSON VARIANT, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31 @24

