USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SERVICE_ONBOARDING_CHECKLIST ( CHECK_ID STRING PRIMARY KEY, SERVICE_REF STRING, ITEM STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

