USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ADMIN_KPI_DEFINITIONS ( KPI_ID STRING PRIMARY KEY, NAME STRING, EXPRESSION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

