USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_EVENTS ( EVENT_ID STRING PRIMARY KEY, SIGNER_ID STRING, DOCUMENT_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

