USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOT_RUNS (
  RUN_ID STRING PRIMARY KEY,
  MANIFEST_ID STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ,
  STATUS STRING,
  RESULT VARIANT
);

