USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_RETRIES (
  RETRY_ID STRING PRIMARY KEY,
  EXPORT_ID STRING,
  ATTEMPT_NUMBER INT,
  STATUS STRING,
  LAST_ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

