USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SLO_COMPLIANCE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, STATUS STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

