USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LINEAGE_RECONCILIATIONS (
  RECON_ID STRING PRIMARY KEY,
  EDGE_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

