USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SCHEDULE_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, OPERATOR_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, REASON CLOB ); @31 @24

