USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_VERSION_INDEX (
  VERSION_ID STRING PRIMARY KEY,
  SCHEMA_NAME STRING,
  VERSION_NUMBER INT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);

