USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AVAILABILITY_METRICS ( METRIC_ID STRING PRIMARY KEY, OPERATOR_REF STRING, AVAILABLE_PCT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

