USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RELEASE_ROLLBACK_REGISTRY ( RB_ID STRING PRIMARY KEY, RELEASE_REF STRING, REASON CLOB, INITIATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

