USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DEPLOYMENT_CADENCE_METRICS ( METRIC_ID STRING PRIMARY KEY, TEAM STRING, DEPLOY_COUNT INT, AVG_TIME_MIN NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

