USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ETAG_INDEX (
  ETAG_ID STRING PRIMARY KEY,
  OBJECT_REF STRING,
  ETAG STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

