USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INCIDENT_COST_ESTIMATES ( EST_ID STRING PRIMARY KEY, INCIDENT_ID STRING, COST_JSON VARIANT, ESTIMATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

