USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPLAYABILITY_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

