USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INTERNAL_COMMS_INDEX ( COMM_ID STRING PRIMARY KEY, SUBJECT STRING, BODY CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

