USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITIONS VARIANT, ACTIONS VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

