USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_HISTORY ( HIST_ID STRING PRIMARY KEY, RULE_ID STRING, CONTEXT VARIANT, RAISED_AT TIMESTAMP_LTZ, HANDLED_AT TIMESTAMP_LTZ );

