USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VERSIONS ( VERSION_ID STRING PRIMARY KEY, RULE_ID STRING, VERSION_NUMBER INT, DEFINED_AT TIMESTAMP_LTZ, PAYLOAD VARIANT );

