USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, EXECUTED_AT TIMESTAMP_LTZ, STATUS STRING );

