USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, RULE_ID STRING, CHANGED_BY STRING, CHANGE_PAYLOAD VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

