USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_INCIDENT_INDEX ( INCIDENT_ID STRING PRIMARY KEY, SERVICE_REF STRING, SLA_REF STRING, INCIDENT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

