USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_REMEDIATION_RUNS ( RUN_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTIONS VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );
-- @31

