USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_CASE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ASSIGNED_TO STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

