USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_PLAN ( PLAN_ID STRING PRIMARY KEY, PROVIDER_GROUP STRING, PRIORITY_LIST ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

