USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_REQUESTS ( REQUEST_ID STRING PRIMARY KEY, REQUESTOR STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ );

