USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_REQUEST_LOGS ( LOG_ID STRING PRIMARY KEY, REQUEST_ID STRING, STATUS STRING, NOTES STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

