USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, REQUEST_ID STRING, APPROVER STRING, APPROVED_AT TIMESTAMP_LTZ, NOTES STRING );

