USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_REQUESTS ( REQ_ID STRING PRIMARY KEY, REQUESTOR STRING, TARGET_REF STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ );

