USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TARGET_TABLE STRING, POLICY_ID STRING, ACTION STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

