USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, REQ_ID STRING, DECISION STRING, DECIDED_BY STRING, DECIDED_AT TIMESTAMP_LTZ );

