USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_VIOLATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, TARGET_TABLE STRING, DESCRIPTION CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

