USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHAIN_INDEX ( CHAIN_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LINK_ORDER INT, LINK_META VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

