USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LONG_TERM_ARCHIVE_INDEX ( ARCHIVE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

