USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_DELETION_JOBS ( JOB_ID STRING PRIMARY KEY, TARGET_REF STRING, REQUEST_ID STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ );

