USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENROLLMENT_REQUESTS ( REQUEST_ID STRING PRIMARY KEY, SUBJECT_REF STRING, STATUS STRING DEFAULT 'NEW', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

