USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENROLLMENT_LOGS ( LOG_ID STRING PRIMARY KEY, REQUEST_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

