USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_OF_CUSTODY_RECORDS ( COC_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STEP JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

