USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_RECORDS ( CONSENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_TYPE STRING, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

