USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CONSENT_ID STRING, AUDIT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGES VARIANT );

