USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSICS_CASE_EVIDENCE ( EVID_ID STRING PRIMARY KEY, CASE_ID STRING, BUNDLE_ID STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

