USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_STATUS ( ARCHIVE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STAGE_PATH STRING, ARCHIVED_AT TIMESTAMP_LTZ, STATUS STRING );

