USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_REQUESTS ( EXPORT_ID STRING PRIMARY KEY, REQUESTOR STRING, SCOPE VARIANT, TARGET_LOCATION STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

