USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_OF_TRUST ( COT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, HASH_CHAIN VARIANT, ANCHOR_TXID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

