USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PREVIEW_CACHE ( PREVIEW_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RENDERED_CLOB CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), TTL_SECONDS INT
);

