USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATE_STORE ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, CERT_PEM CLOB, IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

