USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_INVALIDATIONS ( INVALID_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, INVALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING
);

