USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_AUDIT ( AUDIT_ID STRING PRIMARY KEY, COT_ID STRING, ANCHOR_TXID STRING, VERIFIED_AT TIMESTAMP_LTZ, VERIFIED BOOLEAN );

