USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTARY_REQUESTS ( NOTARY_REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, REQUESTER STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ );

