USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_QUEUE ( RENDER_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, MERGE_CONTEXT VARIANT, STATUS STRING DEFAULT 'QUEUED', ATTEMPTS INT DEFAULT 0, NEXT_RUN_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

