USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRL_UPDATE_REGISTRY ( REG_ID STRING PRIMARY KEY, PROVIDER STRING, LAST_UPDATED_AT TIMESTAMP_LTZ, LOCATION STRING );
-- @31

