USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTARY_LOGS ( LOG_ID STRING PRIMARY KEY, NOTARY_REQ_ID STRING, EVENT STRING, PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ );

