USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_FILES ( FILE_ID STRING PRIMARY KEY, INCIDENT_ID STRING, PATH STRING, META VARIANT, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

