USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_STORAGE ( PDF_ID STRING PRIMARY KEY, RENDER_ID STRING, FILE_URL STRING, SIZE_BYTES NUMBER, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

