USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, PDF_ID STRING, FIELDS VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

