USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_TRANSFORMS ( TRANSFORM_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STEP_NAME STRING, STATUS STRING, OUTPUT VARIANT, RAN_AT TIMESTAMP_LTZ );

