USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_TILE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, TILE_ID STRING, PAYLOAD VARIANT, SNAP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

