USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHECKLIST_EXECUTION_LOGS ( LOG_ID STRING PRIMARY KEY, CHECKLIST_ID STRING, EXECUTOR STRING, OUTCOME VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

