USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARD_TENANT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTION STRING, BY_WHOM STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

