USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RECOMMENDATIONS ( RECO_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE FLOAT, REASON VARIANT, GENERATED_AT TIMESTAMP_LTZ );

