USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_SESSIONS ( SESSION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, HOST STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ );

