USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LOCALIZATIONS ( LOC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LANG STRING, CONTENT CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

