USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SURVEY_RESPONSES ( RESP_ID STRING PRIMARY KEY, SURVEY_ID STRING, RESPONDER STRING, ANSWERS VARIANT, RESPONDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

