USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_HEALTH_SCORES ( SCORE_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

