USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMMENTS ( COMMENT_ID STRING PRIMARY KEY, THREAD_ID STRING, AUTHOR STRING, BODY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

