USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_RUN_HISTORY ( RUN_ID STRING PRIMARY KEY, KPI_ID STRING, VALUE VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

