USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINOPS_COST_CENTER_MAPPING ( MAP_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, COST_CENTER STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

