USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, FIELDS ARRAY, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ );

