USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_AUTHORIZATIONS ( AUTH_ID STRING PRIMARY KEY, CLIENT_ID STRING, SUBJECT_REF STRING, SCOPE STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

