USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, INVOICE_ID STRING, ACCOUNT_ID STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

