USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONFIG_HISTORY ( HISTORY_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CONFIG VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

