USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SCORE FLOAT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

