USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ADJUSTMENT_REQUESTS ( REQ_ID STRING PRIMARY KEY, INVOICE_ID STRING, REQUESTOR STRING, AMOUNT NUMBER, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

