USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_SCORE_HISTORY ( HIST_ID STRING PRIMARY KEY, SCORE_ID STRING, PREV_SCORE FLOAT, NEW_SCORE FLOAT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

