USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREPAID_BALANCE_TRANSACTIONS ( TXN_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, TYPE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

