USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_MEMO_INDEX ( MEMO_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT NUMBER, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

