USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_INVOICE_REASSIGNMENT ( REASSIGN_ID STRING PRIMARY KEY, OLD_ACCOUNT STRING, NEW_ACCOUNT STRING, INVOICE_ID STRING, REASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

