USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, EMAIL STRING, ROLE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31

