USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, CASE_ID STRING, AUTHOR STRING, COMMENT_TEXT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

