USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_PROVIDER_WEBHOOKS ( WH_ID STRING PRIMARY KEY, PROVIDER_ID STRING, EVENT_TYPE STRING, HANDLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PAYLOAD VARIANT );
-- @31

