USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, API_KEY_ID STRING, ACTION STRING, PERFORMED_BY STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

