USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_TRANSITIONS ( TRANS_ID STRING PRIMARY KEY, CASE_ID STRING, FROM_STATUS STRING, TO_STATUS STRING, TRANSITIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), BY_USER STRING
);

