USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_ATTACHMENTS ( ATTACH_ID STRING PRIMARY KEY, CASE_ID STRING, FILE_URL STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

