USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTITLEMENT_CHANGE_HISTORY ( CHG_ID STRING PRIMARY KEY, ENTITLEMENT_ID STRING, CHANGED_BY STRING, OLD_STATE VARIANT, NEW_STATE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

