USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_QUOTA_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_JSON VARIANT, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

