USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_REQUESTS ( REFUND_ID STRING PRIMARY KEY, INVOICE_ID STRING, ACCOUNT_ID STRING, AMOUNT NUMBER, REASON CLOB, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

