USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_COUNTERS ( COUNTER_ID STRING PRIMARY KEY, PROFILE_ID STRING, KEY_REF STRING, COUNT INT, WINDOW_START TIMESTAMP_LTZ );

