USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CURRENCY_ADJUSTMENTS ( ADJ_ID STRING PRIMARY KEY, INVOICE_ID STRING, OLD_AMOUNT NUMBER, NEW_AMOUNT NUMBER, ADJUSTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

