USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RESPONSE_TIME ( RT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, LATENCY_MS NUMBER, SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

