USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, REQUEST_ID STRING, TARGET_LOCATION STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ );

