USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_JURISDICTION_INDEX ( JUR_ID STRING PRIMARY KEY, NAME STRING, COUNTRY STRING, REGION STRING, META VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

