USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_COMPLIANCE_REPORTS ( REPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, LOCATION STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

