USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEE_SCHEDULE_HISTORY ( SCHEDULE_ID STRING PRIMARY KEY, TENANT_ID STRING, FEE_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

