USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUEST_INDEX ( REQ_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUEST_TYPE STRING, STATUS STRING, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

