USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_VERIFICATIONS ( VERIF_ID STRING PRIMARY KEY, ARCHIVE_ID STRING, VERIFIED_AT TIMESTAMP_LTZ, RESULT STRING, DETAILS VARIANT );

