USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_PLAN_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PLAN_ID STRING, ACTIVE_FROM TIMESTAMP_LTZ, ACTIVE_TO TIMESTAMP_LTZ );

