USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_PORTABILITY ( PORT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUEST_JSON VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

