USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRICING_ADJUSTMENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ADJUSTMENT_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), BY_USER STRING );

