USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESTORE_REQUESTS ( REQ_ID STRING PRIMARY KEY, MANIFEST_ID STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ );

