USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_TEMPLATE_LIBRARY ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, BODY CLOB, DEFAULT_LOCALE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

