USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MONITORING_ALERT_HISTORY ( ALERT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

