USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RETRY_HISTORY ( RETRY_ID STRING PRIMARY KEY, PAYMENT_REF STRING, ATTEMPT INT, STATUS STRING, TRIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

