USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ONBOARDING_TIMELINE ( TIMELINE_ID STRING PRIMARY KEY, TENANT_ID STRING, EVENTS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

