USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_COMPLIANCE_PROFILE ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, REQUIREMENTS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

