USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_DATA_LOCATION_PREFS ( PREF_ID STRING PRIMARY KEY, TENANT_ID STRING, REGION STRING, STORAGE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

