USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHORT_CODE_REGISTRY ( CODE_ID STRING PRIMARY KEY, PURPOSE STRING, ASSIGNED_TO STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

