USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SUPPORT_TIERS ( TIER_ID STRING PRIMARY KEY, TENANT_ID STRING, TIER_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

