USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_DELIVERY_QUEUE ( QUEUE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RECIPIENT STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

