USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SECURITY_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY CLOB, STATUS STRING, OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

