USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_VALIDATIONS ( VALID_ID STRING PRIMARY KEY, COT_ID STRING, VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), VALID BOOLEAN, DETAILS VARIANT
);

