USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, TEMPLATE_ID STRING, RECIPIENT STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

