USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_HISTORY ( HISTORY_ID STRING PRIMARY KEY, CONSENT_ID STRING, ACTION STRING, BY_USER STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

