USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLLBACK_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, RELEASE_REF STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

