USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICY_VERSIONS ( VERSION_ID STRING PRIMARY KEY, POLICY_CLOB CLOB, APPLICABLE_FROM TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

