USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICY_ACKS ( ACK_ID STRING PRIMARY KEY, SUBJECT_REF STRING, VERSION_ID STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

