USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHORING_JOBS ( JOB_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TARGET_CHAIN STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

