USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_INCIDENT_HANDLING ( HANDLING_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR_REF STRING, ACTION JSON, HANDLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

