USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PSEUDONYM_MAPPINGS ( MAP_ID STRING PRIMARY KEY, ORIGINAL_REF STRING, PSEUDO_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

