USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHORING_HISTORY ( AH_ID STRING PRIMARY KEY, JOB_ID STRING, ANCHOR_TXID STRING, PUBLISHED_AT TIMESTAMP_LTZ, STATUS STRING
);

