USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUG_FIX_METRICS ( METRIC_ID STRING PRIMARY KEY, BUG_ID STRING, FIX_TIME_MIN NUMBER, DEPLOY_RUN STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

