USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_ANCHORS ( ANCHOR_ID STRING PRIMARY KEY, COT_ID STRING, PEER_ID STRING, TXID STRING, PUBLISHED_AT TIMESTAMP_LTZ
);

