USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_TASKS ( TASK_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_TABLE STRING, LAST_RUN_AT TIMESTAMP_LTZ, STATUS STRING );

