USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOURCE_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, RESOURCE_REF STRING, THRESHOLD JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

