USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_SCHEDULE_HISTORY ( HIST_ID STRING PRIMARY KEY, POLICY_ID STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT VARIANT );

