USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOURCE_QUOTA_HISTORY ( HIST_ID STRING PRIMARY KEY, RESOURCE_REF STRING, USAGE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

