USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_INCIDENT_INDEX ( INCIDENT_ID STRING PRIMARY KEY, RESOURCE_REF STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, DETAILS VARIANT );

