USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RISK_SCORE NUMBER, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

