USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SHARING_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SHARED_WITH STRING, METHOD STRING, SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

