USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_RISK_MITIGATIONS ( MIT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );

