USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOKEN_AUDIT ( TA_ID STRING PRIMARY KEY, TOKEN_ID STRING, ACTION STRING, DETAILS VARIANT, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

