USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LOCKDOWN_EVENTS ( EVENT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REASON CLOB, LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), UNLOCKED_AT TIMESTAMP_LTZ );

