USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_AUTO_REMEDIATION_RULES ( RULE_ID STRING PRIMARY KEY, SLO_ID STRING, RULE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

