USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_COMPARE_DIFFS ( DIFF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FROM_VERSION INT, TO_VERSION INT, DIFF_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

