USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_MERGE_JOBS ( JOB_ID STRING PRIMARY KEY, PARENT_DOC STRING, CHILD_DOCS ARRAY, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

