USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_CANCELLATIONS ( CAN_ID STRING PRIMARY KEY, REQUEST_ID STRING, CANCELLED_BY STRING, CANCELLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING
);

