USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_RUN_LOGS ( LOG_ID STRING PRIMARY KEY, ESC_ID STRING, STEP JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

