USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, PB_ID STRING, STATUS STRING, LAST_RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

