USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_QUEUE ( EVENT_ID STRING PRIMARY KEY, EVENT_TYPE STRING, PAYLOAD VARIANT, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'NEW' );

