USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_DLQ ( DLQ_ID STRING PRIMARY KEY, EVENT_ID STRING, ERROR_MSG STRING, PUSHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

