USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_RISK_REGISTER ( RISK_ID STRING PRIMARY KEY, AREA STRING, RISK_JSON VARIANT, MITIGATION_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

