USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_REVIEW_LOGS ( LOG_ID STRING PRIMARY KEY, RISK_ID STRING, REVIEWER STRING, NOTES CLOB, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

