USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_DEPRECATION_NOTICE ( NOTICE_ID STRING PRIMARY KEY, CLAUSE_ID STRING, REASON CLOB, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

