USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_CONFLICT_LOGS ( LOG_ID STRING PRIMARY KEY, CLAUSE_ID STRING, DOCUMENT_ID STRING, DETAILS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

