USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_LOGS ( LOG_ID STRING PRIMARY KEY, ENDPOINT_ID STRING, REQUEST VARIANT, RESPONSE VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

