USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QC_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REVIEWER STRING, OUTCOME VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

