USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, KEY_REF STRING, NEXT_ROTATE_AT TIMESTAMP_LTZ, INTERVAL_DAYS INT );

