USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_ASSIST_PROMPTS ( PROMPT_ID STRING PRIMARY KEY, NAME STRING, TEMPLATE_CLOB CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

