USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_ASSIST_USAGE ( USAGE_ID STRING PRIMARY KEY, PROMPT_ID STRING, USER_REF STRING, INPUT_HASH STRING, OUTPUT_SUMMARY CLOB, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

