USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_QUEUE ( QUEUE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ATTEMPTS INT DEFAULT 0, NEXT_RUN_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING' );

