USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_ASSIST_CONFIDENCE_METRICS ( METRIC_ID STRING PRIMARY KEY, PROMPT_ID STRING, CONFIDENCE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

