USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KMS_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, KEY_REF STRING, ACTION STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

