USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_OPERATION_METRICS ( METRIC_ID STRING PRIMARY KEY, KEY_REF STRING, OPERATION STRING, COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

