USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, TEMPLATE VARIANT, CREATED_AT TIMESTAMP_LTZ );

