USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ERROR_RATE ( ER_ID STRING PRIMARY KEY, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, ERROR_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

