USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_MATCHES ( MATCH_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCORE FLOAT, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

