USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACKNOWLEDGEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, OPERATOR_REF STRING, ITEM_REF STRING, ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

