USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_TRAINING_ARTIFACTS ( ART_ID STRING PRIMARY KEY, MODEL_ID STRING, LOCATION STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

