USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTION_ITEMS ( ITEM_ID STRING PRIMARY KEY, OPERATOR_REF STRING, TASK_JSON VARIANT, DUE_AT TIMESTAMP_LTZ, STATUS STRING );

