USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_DATA_CATALOG ( DATA_ID STRING PRIMARY KEY, NAME STRING, SCOPE VARIANT, LOCATION STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

