USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPLOYMENT_GATE_CHECKS ( CHECK_ID STRING PRIMARY KEY, NAME STRING, CRITERIA VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PASS BOOLEAN );

