USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_HITS ( HIT_ID STRING PRIMARY KEY, RULE_ID STRING, CONTEXT VARIANT, HIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

