USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_STAGING_INDEX ( STAGE_ID STRING PRIMARY KEY, RELEASE_REF STRING, ARTIFACTS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

