USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MITIGATION_EFFECTIVENESS ( RES_ID STRING PRIMARY KEY, MIT_ID STRING, SCORE NUMBER, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

