USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CONFIG_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, SERVICE_REF STRING, TENANT_ID STRING, CONFIG JSON, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

