USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TOGGLE_SCHEDULE ( SCHED_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ENABLE_AT TIMESTAMP_LTZ, DISABLE_AT TIMESTAMP_LTZ, STATUS STRING );

