USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_ROSTER_INDEX ( ROSTER_ID STRING PRIMARY KEY, TEAM_REF STRING, SCHEDULE JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

