USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_EFFICIENCY_METRICS ( METRIC_ID STRING PRIMARY KEY, TEAM_REF STRING, METRIC JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

