USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_FEEDBACK_ACTIONS ( ACTION_ID STRING PRIMARY KEY, FB_ID STRING, ASSIGNED_TO STRING, STATUS STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

