USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_FEEDBACK_FOLLOWUPS ( FOLLOWUP_ID STRING PRIMARY KEY, ACTION_ID STRING, OUTCOME VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

