USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SRE_RUNBOOK_INDEX ( RUNBOOK_ID STRING PRIMARY KEY, NAME STRING, PATH STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

