USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_TRAINING_COMPLETION ( REC_ID STRING PRIMARY KEY, USER_REF STRING, COURSE_REF STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

