USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_AUDIT_FINDINGS ( FINDING_ID STRING PRIMARY KEY, AUDIT_ID STRING, SUMMARY CLOB, SEVERITY STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

