USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_FINDING_RESOLUTION ( RES_ID STRING PRIMARY KEY, FINDING_ID STRING, RESOLUTION_JSON VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

