USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_LOGS ( LOG_ID STRING PRIMARY KEY, REVIEW_ID STRING, ACTOR STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ );

