USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_EXECUTION_METRICS ( METRIC_ID STRING PRIMARY KEY, RUNBOOK_ID STRING, DURATION_MS NUMBER, OUTCOME STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

