USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSE_TIME_SERIES ( SERIES_ID STRING PRIMARY KEY, INCIDENT_ID STRING, TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE_MS NUMBER );

