USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_RESPONSE_TIME_INDEX ( IDX_ID STRING PRIMARY KEY, CASE_ID STRING, RESPONSE_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

