USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_USAGE_HISTORY ( USAGE_ID STRING PRIMARY KEY, PLAN_ID STRING, USAGE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

