USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_RISK_HEATMAP ( HEATMAP_ID STRING PRIMARY KEY, TENANT_ID STRING, HEATMAP_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

