USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTOSCALE_POLICY_REGISTRY ( POLICY_ID STRING PRIMARY KEY, SERVICE_REF STRING, RULES VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

