USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUDGET_ALERT_DEFINITIONS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, THRESHOLD NUMBER, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

