USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_RISK_MITIGATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, RISK_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );

