USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EVENT_RETENTION_INDEX ( IDX_ID STRING PRIMARY KEY, EVENT_REF STRING, RETENTION_POLICY STRING, EXPIRES_AT TIMESTAMP_LTZ );

