USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_READINESS_CHECKS ( CHECK_ID STRING PRIMARY KEY, AREA STRING, CHECK_JSON VARIANT, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

