USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CONTINUITY_PLANS ( PLAN_ID STRING PRIMARY KEY, SERVICE_REF STRING, STEPS VARIANT, LAST_TESTED_AT TIMESTAMP_LTZ );

