USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_MEASUREMENTS ( MEAS_ID STRING PRIMARY KEY, SLA_ID STRING, METRIC VARIANT, MEASURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

