USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SENSITIVITY_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, TARGET_REF STRING, REVIEWER STRING, RESULT STRING, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

