USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ESCALATED_TO STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

