USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_IMPACT_ASSESSMENTS ( PIA_ID STRING PRIMARY KEY, SCOPE VARIANT, SUMMARY CLOB, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

