USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POST_INCIDENT_REVIEW_CHECKLIST ( CHECK_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ITEMS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

