USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_IMPLEMENTATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, IMP_ID STRING, AUDITOR STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

