USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_COMPLIANCE_OBSERVATIONS ( OBS_ID STRING PRIMARY KEY, TENANT_ID STRING, OBS_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

