USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVERNANCE_COMMITTEE_NOTES ( NOTE_ID STRING PRIMARY KEY, MEETING_REF STRING, MINUTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

