USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVERNANCE_ACTION_ITEMS ( ITEM_ID STRING PRIMARY KEY, NOTE_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ );

