USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNATIONAL_COMPLIANCE_INDEX ( IDX_ID STRING PRIMARY KEY, REGION STRING, REQUIREMENTS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

