USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKFILL_REQUESTS ( REQ_ID STRING PRIMARY KEY, TARGET_TABLE STRING, QUERY VARIANT, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ );

