USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_OFFICER_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, EMAIL STRING, PHONE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

