USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKFILL_RUNS ( RUN_ID STRING PRIMARY KEY, REQ_ID STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, STATUS STRING );

