USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_POLICY_COMPLIANCE ( COMP_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

