USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_BREACH_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TENANT_ID STRING, INCIDENT_ID STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

