USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_REBUILDS ( REBUILD_ID STRING PRIMARY KEY, INDEX_NAME STRING, TRIGGERED_BY STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, STATUS STRING );

