USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_RESPONSE_RECORDS ( RES_ID STRING PRIMARY KEY, SUB_ID STRING, RESPONSE_JSON VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

