USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CONTRACT_INDEX ( CONTRACT_ID STRING PRIMARY KEY, SERVICE_REF STRING, CONTRACT_JSON VARIANT, SIGNED_AT TIMESTAMP_LTZ );

