USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CONTRACT_AMENDMENTS ( AMEND_ID STRING PRIMARY KEY, CONTRACT_ID STRING, AMEND_JSON VARIANT, AMENDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

