USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXECUTIVE_SUMMARY_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, REPORT_ID STRING, PAYLOAD VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

