USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATION_REGISTRY ( CERT_ID STRING PRIMARY KEY, NAME STRING, ISSUER STRING, ISSUED_AT TIMESTAMP_LTZ, EXPIRES_AT TIMESTAMP_LTZ );

