USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATION_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, CERT_ID STRING, TENANT_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

