USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_MAPPINGS ( MAPPING_ID STRING PRIMARY KEY, TENANT_ID STRING, EXTERNAL_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

