USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VENDOR_ASSURANCE_REPORTS ( REP_ID STRING PRIMARY KEY, PROVIDER_ID STRING, REPORT_JSON VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

