USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SYNC_HISTORY ( HIST_ID STRING PRIMARY KEY, MAPPING_ID STRING, SYNC_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING, DETAILS VARIANT );

