USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INSURANCE_POLICY_INDEX ( POLICY_ID STRING PRIMARY KEY, TENANT_ID STRING, PROVIDER STRING, POLICY_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

