USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_ACTION_FOLLOWUPS ( FOLLOWUP_ID STRING PRIMARY KEY, ASSESS_ID STRING, ACTION_JSON VARIANT, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

