USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INSURANCE_CLAIMS_INDEX ( CLAIM_ID STRING PRIMARY KEY, POLICY_ID STRING, INCIDENT_REF STRING, STATUS STRING, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

