USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_AGREEMENT_INDEX ( AGREEMENT_ID STRING PRIMARY KEY, TENANT_ID STRING, AGREEMENT_JSON VARIANT, SIGNED_AT TIMESTAMP_LTZ );

