USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVAL_POLICY_BINDINGS ( BINDING_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_TABLE STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

