USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MODEL_METRICS ( METRIC_ID STRING PRIMARY KEY, MODEL_VER_ID STRING, METRIC_NAME STRING, METRIC_VALUE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

