USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_MODEL_ALERTS ( ALERT_ID STRING PRIMARY KEY, MODEL_VER_ID STRING, SUBJECT_REF STRING, SCORE NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

