USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_HASH_REGISTRY ( HASH_ID STRING PRIMARY KEY, BUNDLE_ID STRING, HASH_ALGO STRING, HASH_VALUE STRING, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

