USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUPPRESSION_RULES ( RULE_ID STRING PRIMARY KEY, ALERT_TYPE STRING, SUPPRESSION_WINDOW_SECONDS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

