USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_CACHE ( CACHE_ID STRING PRIMARY KEY, SIGNATURE_REF STRING, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ ); @31 @24

