USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTODIAN_RECORDS ( CUST_ID STRING PRIMARY KEY, NAME STRING, CONTACT VARIANT, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

