USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFIER_SERVICE_REGISTRY ( SERVICE_ID STRING PRIMARY KEY, NAME STRING, ENDPOINT STRING, METADATA VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

