USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_ISSUES ( ISSUE_ID STRING PRIMARY KEY, CHECK_ID STRING, TARGET_REF STRING, ISSUE_DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

