USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_OPERATIONS_LOG ( OP_ID STRING PRIMARY KEY, KEY_ID STRING, OPERATION STRING, INITIATED_BY STRING, INITIATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

