USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_RESPONSE_CACHE ( CACHE_ID STRING PRIMARY KEY, CERT_ID STRING, RESPONSE_JSON VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

