USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REQUESTS ( HOLD_ID STRING PRIMARY KEY, TARGET_REF STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ );

