USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_FAILURE_INDEX ( FAIL_ID STRING PRIMARY KEY, CERT_ID STRING, ERROR_MSG STRING, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

