USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRL_FETCH_HISTORY ( FETCH_ID STRING PRIMARY KEY, SOURCE STRING, SUCCESS BOOLEAN, FETCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

