USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIAL_VAULT ( VAULT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CRED_META VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

