USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_POLICIES ( POLICY_ID STRING PRIMARY KEY, NAME STRING, RETENTION_DAYS INT, ARCHIVE_BEFORE BOOLEAN DEFAULT TRUE, ENABLED BOOLEAN DEFAULT TRUE );

