USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_RUNS ( RUN_ID STRING PRIMARY KEY, POLICY_ID STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ, STATUS STRING );

