USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_BACKOFF_QUEUE ( QUEUE_ID STRING PRIMARY KEY, TARGET_REF STRING, NEXT_RETRY_AT TIMESTAMP_LTZ, ATTEMPTS INT DEFAULT 0, PAYLOAD VARIANT ); @31 @24

