USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, RUN_ID STRING, TARGET_REF STRING, ACTION STRING, ACTIONED_AT TIMESTAMP_LTZ );

