USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SIGNATURE_VALIDATIONS ( VALID_ID STRING PRIMARY KEY, RAW_ID STRING, IS_VALID BOOLEAN, VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

