USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONE_TIME_LINK_USES ( USE_ID STRING PRIMARY KEY, LINK_ID STRING, USED_BY STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

