USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINTS ( FINGER_ID STRING PRIMARY KEY, SUBJECT_REF STRING, FINGERPRINT VARIANT, CREATED_AT TIMESTAMP_LTZ );

