USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOIP_LOOKUPS ( LOOKUP_ID STRING PRIMARY KEY, IP_ADDR STRING, GEO VARIANT, LOOKUP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

