USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_HISTORY ( HISTORY_ID STRING PRIMARY KEY, SESSION_ID STRING, EVENT STRING, PAYLOAD VARIANT, TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

