USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGED_OPERATION_APPROVALS ( APP_ID STRING PRIMARY KEY, OPERATION_JSON VARIANT, REQUESTED_BY STRING, STATUS STRING, APPROVED_AT TIMESTAMP_LTZ ); @31 @24

