USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGE_ESCALATION_ATTEMPTS ( ATTEMPT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, OPERATION_JSON VARIANT, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT STRING ); @31 @24

