USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FALLBACKS ( FALLBACK_ID STRING PRIMARY KEY, PRIMARY_PROVIDER STRING, FALLBACK_PROVIDERS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

