USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_METRICS ( METRIC_ID STRING PRIMARY KEY, PROVIDER STRING, LATENCY_MS FLOAT, ERR_RATE FLOAT, SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

