USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ESCALATION_LOGS ( LOG_ID STRING PRIMARY KEY, POLICY_ID STRING, INCIDENT_ID STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

