USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_SCORECARD ( SCORE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCORE NUMBER, FACTORS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

