USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_RISK_PROFILES ( PROFILE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, RISK_SCORE NUMBER, PROFILE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

