USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_FEEDS ( FEED_ID STRING PRIMARY KEY, NAME STRING, SOURCE JSON, LAST_POLL TIMESTAMP_LTZ, META VARIANT ); @31 @24

