USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SSO_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, IDP_ID STRING, EVENT_JSON VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

