USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RBAC_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

