USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACCESS_CERTIFICATIONS ( CERT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, CERTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

