USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_APPROVALS ( APP_ID STRING PRIMARY KEY, CHANGE_JSON VARIANT, REQUESTOR STRING, APPROVER STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

