USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_SECURITY_INCIDENT_INDEX ( INCIDENT_ID STRING PRIMARY KEY, SUMMARY CLOB, SEVERITY STRING, OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

