USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SLA_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SLO_REF STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

