USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FLAG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FLAG_ID STRING, CHANGED_BY STRING, NEW_VALUE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

