USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WATERMARK_APPLICATION_LOG ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, POLICY_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

