USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_GEO_INDEX ( GEO_ID STRING PRIMARY KEY, SIGNER_ID STRING, COUNTRY STRING, REGION STRING, LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

