USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PERMISSION_REQUESTS ( REQ_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REQUESTOR STRING, PURPOSE STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

