USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINT_INDEX ( FINGER_ID STRING PRIMARY KEY, SIGNER_ID STRING, FINGERPRINT_HASH STRING, LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

