USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOGGLE_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, TOGGLE_ID STRING, SUBJECT_REF STRING, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT BOOLEAN );

