USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_QUALITY_ISSUES ( ISSUE_ID STRING PRIMARY KEY, CLAUSE_ID STRING, REPORTER STRING, SEVERITY STRING, DETAILS CLOB, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

