USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_METRICS ( METRIC_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RENDER_TIME_MS NUMBER, RENDERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENGINE STRING );

