USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_FAILURE_INDEX ( FAIL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ERROR_MSG STRING, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), TRACE VARIANT );

