USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_BINDINGS ( BIND_ID STRING PRIMARY KEY, ROLE_ID STRING, USER_REF STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

