USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_ACCESS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PREVIEW_ID STRING, SUBJECT_REF STRING, ACTION STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

