USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_ADMIN_ACTIVITY AS SELECT a.ACTION_ID, a.ADMIN_USER, a.ACTION, a.TARGET, a.ACTION_TS FROM DOCGEN.ADMIN_ACTIONS a ORDER BY a.ACTION_TS DESC;

