USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_ERROR_LOG ( ERR_ID STRING PRIMARY KEY, JOB_ID STRING, ERROR_MSG CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

