USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_OPERATOR_ACTIVITY AS SELECT o.ACTION_ID, o.OPERATOR, o.ACTION, o.TARGET, o.CREATED_AT FROM DOCGEN.OPERATOR_ACTIONS o ORDER BY o.CREATED_AT DESC;

