USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IMAGE_OCR_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

