USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REVOCATION_LOG ( REV_ID STRING PRIMARY KEY, SESSION_ID STRING, REVOKED_BY STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

