USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_ACTIVITY_STREAM ( ACT_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTIVITY JSON, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

