USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_INCIDENT_WORKFLOW AS SELECT i.INCIDENT_ID, i.TITLE, i.STATUS, e.REPORTS FROM DOCGEN.INCIDENTS i LEFT JOIN (SELECT INCIDENT_ID, ARRAY_AGG(OBJECT_CONSTRUCT('REPORT_ID', REPORT_ID, 'SEVERITY', SEVERITY)) AS REPORTS FROM DOCGEN.INCIDENT_REPORTS GROUP BY INCIDENT_ID) e ON e.INCIDENT_ID = i.INCIDENT_ID;

