USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TEXT_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TEXT_CLOB CLOB, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

