USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_REUSE_INDEX ( IDX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, DOCUMENT_ID STRING, OCCURRENCES INT, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

