USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_METRICS ( METRIC_ID STRING PRIMARY KEY, INCIDENT_ID STRING, METRIC VARIANT, MEASURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

