USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINT_INDEX ( FPRINT_ID STRING PRIMARY KEY, SIGNER_ID STRING, FINGERPRINT VARIANT, FIRST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_SEEN TIMESTAMP_LTZ );

