USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPENDENCY_GRAPH ( EDGE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPENDS_ON STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

