USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BROWSER_FINGERPRINT_REGISTRY ( REG_ID STRING PRIMARY KEY, SIGNER_ID STRING, FINGERPRINT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

