USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_SAMPLE_INDEX ( SAMPLE_ID STRING PRIMARY KEY, SIGNER_ID STRING, SAMPLE_META VARIANT, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

