USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_CACHE_INDEX ( CACHE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RENDER_HASH STRING, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LOCATION STRING );

