USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_SESSION_STORE ( SESSION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

