USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRICS_CONSENT_RECORDS ( CONSENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_JSON VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

