USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_ADMIN_DASHBOARD AS SELECT (SELECT COUNT(*) FROM DOCGEN.BILLING_RUN) AS billing_runs, (SELECT COUNT(*) FROM DOCGEN.EVIDENCE_BUNDLE) AS evidence_count, (SELECT COUNT(*) FROM DOCGEN.INCIDENTS WHERE STATUS = 'OPEN') AS open_incidents;

