USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, SESSION_ID STRING, IP_ADDR STRING, USER_AGENT STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

