USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QR_INDEX ( QR_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, QR_PAYLOAD STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

