USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_RETRY_HISTORY ( RETRY_ID STRING PRIMARY KEY, NOTIF_ID STRING, ATTEMPT INT, STATUS STRING, TRIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

