USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QR_SCAN_EVENTS ( EVENT_ID STRING PRIMARY KEY, QR_ID STRING, SCANNER_REF STRING, SCANNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PAYLOAD VARIANT );

