USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_SHORT_CODE_METRICS ( METRIC_ID STRING PRIMARY KEY, SHORT_CODE_ID STRING, SENT_COUNT INT, FAILED_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

