USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOBILE_PUSH_TOKEN_REGISTRY ( TOKEN_ID STRING PRIMARY KEY, SUBJECT_REF STRING, DEVICE_REF STRING, TOKEN STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

