USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITION VARIANT, SEVERITY STRING, ENABLED BOOLEAN DEFAULT TRUE );

