USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATE_LIMIT_EVENTS ( EVENT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, LIMIT_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

