USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTITENANT_TEMPLATE_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, IS_SHARED BOOLEAN, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

