USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LABEL_INDEX ( LABEL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, KEY STRING, VALUE VARIANT, LABELED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

