USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TAGGING_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STRATEGY STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

