USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VIOLATION_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, EVENT_ID STRING, RESOLVED_BY STRING, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

