USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHECKLIST_RUNS ( RUN_ID STRING PRIMARY KEY, CHECKLIST_ID STRING, RUN_BY STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ, STATUS STRING );

