USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_RISK_PROFILE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SIGNER_ID STRING, RISK_PROFILE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGED_BY STRING );

