USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BLACKLIST ( BL_ID STRING PRIMARY KEY, SIGNER_ID STRING, REASON CLOB, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

