USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REQUESTS (
  REQUEST_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REQUESTOR STRING,
  STATUS STRING DEFAULT 'OPEN',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

