USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADAPTIVE_ROUTING_LOGS ( LOG_ID STRING PRIMARY KEY, ROUTE_ID STRING, INPUT VARIANT, CHOSEN_TARGET STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

