USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_RATECARD_UPDATES ( UPDATE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, RATECARD_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

