USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_USAGE_ANOMALIES ( ANOM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEATURE_NAME STRING, ANOMALY_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

