USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SNAPSHOT_RESTORE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SNAP_ID STRING, RESTORED_BY STRING, RESTORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

