USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANOMALY_INVESTIGATION_QUEUE ( Q_ID STRING PRIMARY KEY, ANOM_ID STRING, ASSIGNED_TO STRING, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

