USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_SIMILARITY_INDEX ( INDEX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VECTOR_REF STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

