USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_POLICY_VIOLATION_INDEX ( VIOL_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

