USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PRIVACY_REQUESTS (
  DPR_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  REQUEST_TYPE STRING,
  STATUS STRING DEFAULT 'RECEIVED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

