USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHANGE_STREAM_INDEX ( IDX_ID STRING PRIMARY KEY, STREAM_ID STRING, DOCUMENT_ID STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

