USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_HASH_REGISTRY ( HASH_ID STRING PRIMARY KEY, EMBED_REF STRING, HASH_VALUE STRING, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

