USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_RISK_SCORE_HISTORY ( SCORE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCORE NUMBER, REASON CLOB, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

