USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_COMPLIANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CERT_META VARIANT, ISSUED_AT TIMESTAMP_LTZ );

