USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DPR_ACTIONS (
  ACTION_ID STRING PRIMARY KEY,
  DPR_ID STRING,
  ACTION STRING,
  PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

