USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATE_EXPIRY ( EXP_ID STRING PRIMARY KEY, CERT_ID STRING, EXPIRES_AT TIMESTAMP_LTZ, NOTIFIED BOOLEAN DEFAULT FALSE );

