USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_METRIC_HISTORY ( METRIC_ID STRING PRIMARY KEY, SHARD_REF STRING, LATENCY_MS NUMBER, QPS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

