USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  CHANNEL STRING,
  TEMPLATE_BODY CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

