USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_PROCESSING_METRICS ( METRIC_ID STRING PRIMARY KEY, JOB_ID STRING, METRIC_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

