USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_LOGS (
  LOG_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  USER_REF STRING,
  ACTION STRING,
  IP_ADDR STRING,
  USER_AGENT STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

