USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONCEPT_USAGE_STATS ( STAT_ID STRING PRIMARY KEY, CON_ID STRING, COUNT INT, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

