USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONCEPT_SYNONYM_INDEX ( SYN_ID STRING PRIMARY KEY, CON_ID STRING, SYNONYM STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

