USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_TRANSFORM_JOBS ( JOB_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TRANSFORMS VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

