USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARE_REVOCATIONS (
  REVOC_ID STRING PRIMARY KEY,
  SHARE_ID STRING,
  REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  REVOKED_BY STRING,
  REASON STRING
);

