USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_SIMILARITY_STORE ( CS_ID STRING PRIMARY KEY, CLAUSE_ID STRING, EMBEDDING VECTOR, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

