USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERSION_DIFFS (
  DIFF_ID STRING PRIMARY KEY,
  VERSION_ID STRING,
  DIFF VARIANT,
  COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

