USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION ( RETENTION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RETENTION_UNTIL TIMESTAMP_LTZ, POLICY_ID STRING );

