USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PURGES (
  PURGE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  PURGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  BY STRING
);

