USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERSION_RETENTION_OVERRIDES (
  OVERRIDE_ID STRING PRIMARY KEY,
  VERSION_ID STRING,
  RETENTION_UNTIL TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

