USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_CHECKLIST_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, ITEMS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

