USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_INDEX_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, CLAUSE_SET STRING, S3_PREFIX STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

