USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKUP_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  SCHEDULE STRING,
  TARGET_LOCATION STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

