USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_EXPIRY_MONITOR ( MON_ID STRING PRIMARY KEY, CONSENT_ID STRING, EXPIRES_AT TIMESTAMP_LTZ, NOTIFIED BOOLEAN DEFAULT FALSE );

