USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_SUMMARY_MV ( MV_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENTS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

