USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESTORE_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  ALLOWED_SOURCES ARRAY,
  ENABLED BOOLEAN DEFAULT TRUE
);

