USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, SERVICE_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, DESCRIPTION CLOB );

