USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CAPACITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, THRESHOLD JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

