USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESTORE_RUN_DETAILS (
  DETAIL_ID STRING PRIMARY KEY,
  REQ_ID STRING,
  FILE_REF STRING,
  STATUS STRING,
  DETAIL VARIANT
);

