USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEAM_ROSTER_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, TEAM_REF STRING, ROSTER_JSON VARIANT, SNAP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

