USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METRICS_CONFIG (
  CONFIG_ID STRING PRIMARY KEY,
  NAME STRING,
  AGG_RULES VARIANT,
  SCHEDULE STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

