USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ONBOARDING_SLA ( SLA_ID STRING PRIMARY KEY, TENANT_ID STRING, SLA_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

