USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_QUERY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, QUERY TEXT, SNAP_ID STRING, RESULTS_COUNT INT, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

