USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUBSCRIBERS (
  SUB_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  CHANNEL STRING,
  DESTINATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

