USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DISPATCH_LOGS (
  DISPATCH_ID STRING PRIMARY KEY,
  ALERT_ID STRING,
  SUB_ID STRING,
  STATUS STRING,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESPONSE VARIANT
);

