USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERTIFICATION_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, CERT_REQ_ID STRING, OPERATOR_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

