USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPENDENCY_INDEX ( DEP_ID STRING PRIMARY KEY, SERVICE_REF STRING, DEPENDENCY_REF STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

