USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPENDENCY_CHANGE_EVENTS ( EVENT_ID STRING PRIMARY KEY, DEP_ID STRING, CHANGE_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

