USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_RATE_LIMITS (
  LIMIT_ID STRING PRIMARY KEY,
  SUB_ID STRING,
  MAX_PER_HOUR INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

