USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_OUTAGE_INDEX ( OUTAGE_ID STRING PRIMARY KEY, SERVICE_REF STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, SUMMARY CLOB );

