USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OUTAGE_IMPACT_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, OUTAGE_ID STRING, IMPACT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

