USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_CUSTOMER_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, INCIDENT_ID STRING, TENANT_ID STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

