USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRANSCRIPTS (
  TRANSCRIPT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ACTOR STRING,
  TEXT CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

