USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHECKSUM_ARCHIVE ( ARCH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECKSUM STRING, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LOCATION STRING );

