USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONVERSATION_SESSIONS (
  SESSION_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT
);

