USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ARCHIVAL_JOBS ( JOB_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGETS ARRAY, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

