USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TWO_FA_ENFORCEMENT_POLICIES ( POLICY_ID STRING PRIMARY KEY, TENANT_ID STRING, RULES VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

