USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEEDBACK_ACTION_QUEUE ( Q_ID STRING PRIMARY KEY, FB_ID STRING, ASSIGNED_TO STRING, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

