USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_ACTIONS (
  ACTION_ID STRING PRIMARY KEY,
  INSTANCE_ID STRING,
  ACTOR STRING,
  ACTION STRING,
  COMMENT STRING,
  ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

