USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_PRIVACY_AUDITS ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, FINDINGS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

