USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LINEAGE_CHANGE_LOGS ( LOG_ID STRING PRIMARY KEY, LINE_ID STRING, CHANGE_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

