USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_PRIVACY_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RESULTS VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

