USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  INSTANCE_ID STRING,
  SUMMARY VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

