USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_SHARING_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, EXCEPTION_JSON VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

