USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICY_ACK_AUDIT ( AUDIT_ID STRING PRIMARY KEY, VERSION_ID STRING, SUBJECT_REF STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

