USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METADATA_CATALOG_INDEX ( META_ID STRING PRIMARY KEY, OBJECT_REF STRING, META_JSON VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

