USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAMPAIGNS_REGISTRY ( CAMPAIGN_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, META VARIANT, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ );

