USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METADATA_CHANGE_HISTORY ( CHG_ID STRING PRIMARY KEY, META_ID STRING, OLD_JSON VARIANT, NEW_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

