USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_NOTIFICATION_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  MESSAGE STRING,
  DESTINATION VARIANT,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

