USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_VERSION_INDEX ( VER_ID STRING PRIMARY KEY, SCHEMA_NAME STRING, VERSION INT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

