USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RETENTION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, TARGET_SCOPE VARIANT, RETENTION_DAYS INT, NEXT_RUN_AT TIMESTAMP_LTZ );

