USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_ROLLBACK_INDEX ( ROLL_ID STRING PRIMARY KEY, VER_ID STRING, ROLLBACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

