USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOLUTION_RUNS (
  RUN_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  INCIDENT_ID STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ
);

