USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUALITY_FIX_JOBS ( JOB_ID STRING PRIMARY KEY, VIOL_ID STRING, FIX_SCRIPT STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

