USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CHAIN_VERIFICATION ( VER_ID STRING PRIMARY KEY, CHAIN_ID STRING, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

