USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_REGISTRY_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, VER_ID STRING, MESSAGE CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

