USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_QUERY_CACHE ( CACHE_ID STRING PRIMARY KEY, QUERY_HASH STRING, RESULT_LOCATION STRING, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

