USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  KPI_ID STRING,
  CONDITION VARIANT,
  SEVERITY STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

