USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ASSIGNMENT_AUDIT_LOGS ( LOG_ID STRING PRIMARY KEY, Q_ID STRING, ACTION STRING, BY_USER STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

