USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, OPERATOR_REF STRING, COURSE_REF STRING, SCHEDULE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

