USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_EXCEPTIONS (
  EXC_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  APPROVED_BY STRING,
  APPROVED_AT TIMESTAMP_LTZ
);

