USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PII_SCAN_JOBS (
  JOB_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);

