USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_ENTITLEMENTS ( ENT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, ENT_JSON VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
