USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CANARY_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_IDS ARRAY, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31
