USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  TARGET_REF STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

