USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_VALIDATION_JOBS ( JOB_ID STRING PRIMARY KEY, TARGET_LOCATION STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31
