USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSICS_EVIDENCE_LINKS ( LINK_ID STRING PRIMARY KEY, CASE_ID STRING, BUNDLE_ID STRING, LINK_TYPE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
