USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSICS_CHAIN_INDEX ( CHAIN_ID STRING PRIMARY KEY, CASE_ID STRING, CHAIN_JSON VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
