USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_QUEUE ( HOLD_ID STRING PRIMARY KEY, TARGET_REF STRING, TENANT_ID STRING, STATUS STRING DEFAULT 'ACTIVE', ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
