USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTODIAN_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, CUSTODIAN_REF STRING, TARGET_REF STRING, ACCESS_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31
