USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METADATA_INDEX (
  IDX_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  METADATA VARIANT,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

