USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACTIVITY_INDEX ( INDEX_ID STRING PRIMARY KEY, ACTION_ID STRING, ADMIN_USER STRING, TARGET_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @1

