USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICIES_01 (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  RULES VARIANT,
  SCOPE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENABLED BOOLEAN DEFAULT TRUE
);

