USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_METRICS ( METRIC_ID STRING PRIMARY KEY, QUERY STRING, RESULT_COUNT INT, LATENCY_MS FLOAT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @1

