USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_BINDINGS_01 (
  BINDING_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_TYPE STRING,
  TARGET_REF STRING,
  BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

