USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSIONS_01 (
  SESSION_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  SIGNATORY_REF STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ,
  META VARIANT
);

