USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_RECORDS ( CONSENT_ID STRING PRIMARY KEY, USER_REF STRING, SCOPE VARIANT, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );
-- @1

