USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_INCIDENT_INDEX ( INCIDENT_ID STRING PRIMARY KEY, RELEASE_REF STRING, SUMMARY CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
