USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_INCIDENT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING ); @31
