USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_CHALLENGES_01 (
  CHALLENGE_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  CHALLENGE TEXT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ,
  STATUS STRING DEFAULT 'ACTIVE'
);

