USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PLAYBOOK_ID STRING, RUN_ID STRING, ACTION JSON, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

