USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHALLENGE_RESPONSES_01 (
  RESPONSE_ID STRING PRIMARY KEY,
  CHALLENGE_ID STRING,
  RESPONSE VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  VERIFIED BOOLEAN DEFAULT FALSE
);

