USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AVAILABILITY_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, TEAM_REF STRING, AVAIL_JSON VARIANT, SNAP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
