USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_SWAP_REQUESTS ( REQ_ID STRING PRIMARY KEY, OP_A STRING, OP_B STRING, SHIFT_REF STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31
