USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PERMISSIONS ( PERM_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SUBJECT_REF STRING, PERMISSIONS ARRAY, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @1

