USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_PIN_ATTEMPTS_01 (
  ATTEMPT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SUCCESS BOOLEAN,
  SOURCE_IP STRING
);

