USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPLOYMENT_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, PIPELINE_REF STRING, STATUS STRING, LAST_RUN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31
