USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_COMPONENTS_01 (
  COMPONENT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TYPE STRING,
  REF STRING,
  HASH STRING,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

