USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LIFECYCLE ( LIFECYCLE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, STATE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGED_BY STRING );
-- @1

