USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_INTEGRITY_CHECKS_01 (
  CHECK_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING,
  DETAILS VARIANT
);

