USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_HEALTH ( HEALTH_ID STRING PRIMARY KEY, WORKER_ID STRING, STATUS STRING, LAST_HEARTBEAT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

