USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_POSTMORTEM_ACTIONS ( ACTION_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTION_JSON VARIANT, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

