USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_SNAPSHOT_RESTORE_JOBS ( JOB_ID STRING PRIMARY KEY, SNAP_ID STRING, STATUS STRING, REQUESTED_BY STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
