USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_PROFILES_01 (
  SIGNER_REF STRING PRIMARY KEY,
  NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

