USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SIMILARITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SIMILAR_TO ARRAY, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @1
