USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SIMILARITY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ALERT_ID STRING, REVIEWER STRING, ACTION STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
