USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REMINDERS_01 (
  REMINDER_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  SCHEDULED_AT TIMESTAMP_LTZ,
  SENT BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

