USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVCOMPLIANCE_ASSESSMENT ( ASSESS_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, RESULT VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

