USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVCOMPLIANCE_TASKS ( TASK_ID STRING PRIMARY KEY, ASSESS_ID STRING, OWNER STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

