USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_VERSION_INDEX ( VER_ID STRING PRIMARY KEY, CONTRACT_ID STRING, VERSION_NUMBER INT, SUMMARY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

