USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVISION_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, AUTHOR STRING, COMMENT_CLOB CLOB, POSTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
