USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_SIGNATURE_MAP ( MAP_ID STRING PRIMARY KEY, CONTRACT_ID STRING, SIGNATURE_REF STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

