USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_LIFECYCLE_EVENTS ( EVENT_ID STRING PRIMARY KEY, CONTRACT_REF STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
