USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_RENEWAL_QUEUE ( Q_ID STRING PRIMARY KEY, CONTRACT_REF STRING, TENANT_ID STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
