USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_AMENDMENT_REQUESTS ( REQ_ID STRING PRIMARY KEY, CONTRACT_REF STRING, REQUESTOR STRING, AMENDMENT JSON, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
