USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CR_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CR_ID STRING, ACTION STRING, PERFORMED_BY STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @1

