USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_SIGNATURE_SUMMARY ( SUM_ID STRING PRIMARY KEY, CONTRACT_REF STRING, SIGNATURE_COUNT INT, LAST_SIGNED_AT TIMESTAMP_LTZ ); @1
