USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESIGN_PROVIDER_CONFIGS_01 (
  CONFIG_ID STRING PRIMARY KEY,
  NAME STRING,
  TYPE STRING,
  CONFIG VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE
);

