USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_VERSION_INDEX ( VER_ID STRING PRIMARY KEY, CONTRACT_REF STRING, VERSION_NUMBER INT, RELEASE_NOTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
