USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_MERGE_HISTORY ( MERGE_ID STRING PRIMARY KEY, PRIMARY_DOC_ID STRING, MERGED_DOC_IDS ARRAY, MERGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

