USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_REQUESTS_01 (
  REQ_ID STRING PRIMARY KEY,
  PROVIDER_CONFIG_ID STRING,
  PAYLOAD VARIANT,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

