USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_APPROVAL_LOGS ( LOG_ID STRING PRIMARY KEY, WF_ID STRING, STEP_REF STRING, ACTOR STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @1
