USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TIMEOUTS_01 (
  TIMEOUT_ID STRING PRIMARY KEY,
  PROVIDER_CONFIG_ID STRING,
  TIMEOUT_SECONDS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

