USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CHECK_HISTORY ( CHK_ID STRING PRIMARY KEY, TENANT_ID STRING, CHECK_NAME STRING, RESULT VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
