USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_ISSUE_QUEUE ( Q_ID STRING PRIMARY KEY, TENANT_ID STRING, ISSUE_JSON VARIANT, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
