USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERACTION_HISTORIES_01 (
  INTERACT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ACTOR STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

