USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ETAG_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, ETAG_ID STRING, TENANT_ID STRING, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

