USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_REPORTING_REGISTRY ( REPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, REPORT_JSON VARIANT, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
