USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_CONCORDANCE_INDEX ( IDX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, TERM STRING, OCCURRENCES INT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

