USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_FEEDBACK_01 (
  FEEDBACK_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  INPUT VARIANT,
  RATING INT,
  COMMENTS STRING,
  SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

