USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RETENTION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB ); @1
