USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_QUOTA_USAGE ( USAGE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, USAGE_COUNT NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

