USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRACKING_CONSENT_REGISTER ( CONSENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); @1
