USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DEPLOYMENTS (
  DEPLOY_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  ENVIRONMENT STRING,
  DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING,
  META VARIANT
);

