USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TOPIC_INDEX ( TOPIC_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TOPICS ARRAY, SCORES VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

