USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOPIC_TREND_METRICS ( METRIC_ID STRING PRIMARY KEY, TOPIC_ID STRING, TREND_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

