USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_DATA_TRANSFERS ( TRANS_ID STRING PRIMARY KEY, TENANT_ID STRING, DESTINATION JSON, DATA_SCOPE VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @1
