USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_BACKUP_INDEX ( BACKUP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, BACKUP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

