USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNER_AFFINITY ( AFF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNER_ID STRING, AFFINITY_SCORE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

