USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  TYPE STRING,
  PAYLOAD VARIANT,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

