USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_RESPONSES (
  RESP_ID STRING PRIMARY KEY,
  REQ_ID STRING,
  RESPONSE VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

