USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_NOTIFICATION_SUMMARIES ( SUM_ID STRING PRIMARY KEY, JOB_ID STRING, SUCCESS INT, FAILED INT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

