USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_CONSENT_REGISTRY ( REG_ID STRING PRIMARY KEY, CLIENT_ID STRING, CONSENTS VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
