USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_NOTIFICATION_DETAILS ( DETAIL_ID STRING PRIMARY KEY, SUM_ID STRING, NOTIF_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

