USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_AUDIT_CHECKS ( CHECK_ID STRING PRIMARY KEY, NAME STRING, QUERY_CLOB CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

