USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ANALYTICS (
  ANALYTIC_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  METRIC VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

