USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_REVIEW_INDEX ( IDX_ID STRING PRIMARY KEY, POLICY_ID STRING, REVIEW_JSON VARIANT, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

