USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, HOLD_ID STRING, SUBJECT_REF STRING, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
