USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_USAGE (
  USAGE_ID STRING PRIMARY KEY,
  PROVIDER_NAME STRING,
  METRIC VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

