USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_OF_CUSTODY_REGISTRY ( CUSTODY_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STEPS VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
