USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACTS (
  CONTRACT_ID STRING PRIMARY KEY,
  PROVIDER_NAME STRING,
  TERMS VARIANT,
  EFFECTIVE_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ
);

