USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUPPRESSIONS (
  SUPP_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  START_AT TIMESTAMP_LTZ,
  END_AT TIMESTAMP_LTZ,
  REASON STRING
);

