USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IMMUTABLE_EVIDENCE_STORE ( STORE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, SEALED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @1
