USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ESCROW_REGISTRY ( ESCROW_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ESCROW_PARTY JSON, AGREEMENT VARIANT, DEPOSITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
