USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_LIMITS (
  LIMIT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  LIMITS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

