USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_LEGAL_HOLDS ( HOLD_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TENANT_ID STRING, ACTIVE BOOLEAN DEFAULT TRUE, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
