USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERED_DOCUMENTS_ARCHIVE ( ARCHIVE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ARCHIVE_LOCATION STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

