USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_CHANGE_LOGS (
  LOG_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  CHANGE_TYPE STRING,
  DETAILS VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

