USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVESTIGATION_CASE_ATTACHMENTS ( ATTACH_ID STRING PRIMARY KEY, CASE_ID STRING, LOCATION STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @1
