USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_INCIDENT_REPORTS ( REPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY CLOB, STATUS STRING, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1
