USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDP_AUTH_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  IDP_ID STRING,
  USER_REF STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

