USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAML_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  IDP_ID STRING,
  ASSERTION VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

