USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_LOGS_ARCHIVE (
  ARCHIVE_ID STRING PRIMARY KEY,
  LOG_ID STRING,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

