USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPROCESS_QUEUE (
  QUEUE_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING DEFAULT 'PENDING'
);

