USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRL_FETCH_HISTORY ( FETCH_ID STRING PRIMARY KEY, SOURCE_URL STRING, STATUS STRING, FETCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

