USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_REVOCATION_INDEX ( REV_ID STRING PRIMARY KEY, CERT_ID STRING, REVOKED_AT TIMESTAMP_LTZ, REVOKE_REASON STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

