USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_PROFILE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SIGNER_ID STRING, PROFILE_JSON VARIANT, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

