USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_RISK_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, SIGNER_ID STRING, SCORE NUMBER, REASON VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

