USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_POLICY_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, SIGNER_ID STRING, POLICY_ID STRING, OVERRIDE_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

