USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_HISTORY_02 (
  HISTORY_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  BUNDLE_ID STRING,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONTEXT VARIANT,
  RESOLVED BOOLEAN DEFAULT FALSE
);

