USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_ATTESTATION_JOBS ( JOB_ID STRING PRIMARY KEY, DEVICE_ID STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), COMPLETED_AT TIMESTAMP_LTZ );

