USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOBILE_SDK_EVENT_LOGS ( LOG_ID STRING PRIMARY KEY, SDK_CLIENT STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

