USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_STREAM_02 (
  AUDIT_ID STRING PRIMARY KEY,
  SOURCE STRING,
  EVENT_TYPE STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

