USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOBILE_SDK_ERROR_INDEX ( ERR_ID STRING PRIMARY KEY, SDK_CLIENT STRING, ERROR_CODE STRING, ERROR_MSG CLOB, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

