USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_RELEASE_REGISTRY ( RELEASE_ID STRING PRIMARY KEY, SDK_NAME STRING, VERSION STRING, RELEASE_NOTES CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

