USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECKS_02 (
  CHECK_ID STRING PRIMARY KEY,
  NAME STRING,
  LAST_OK TIMESTAMP_LTZ,
  STATUS STRING,
  DETAILS VARIANT
);

