USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULER_JOBS_02 (
  JOB_ID STRING PRIMARY KEY,
  NAME STRING,
  CRON_EXPRESSION STRING,
  LAST_RUN_AT TIMESTAMP_LTZ,
  NEXT_RUN_AT TIMESTAMP_LTZ,
  ENABLED BOOLEAN DEFAULT TRUE
);

