USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_PROVIDER_REGISTRY ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, ENDPOINT JSON, CONFIG VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

