USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SUBSCRIPTION_INDEX ( SUB_ID STRING PRIMARY KEY, PROVIDER_ID STRING, TARGET_URL STRING, SECRET_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

