USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_LOG ( DELIV_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, STATUS STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE VARIANT );

