USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JOB_EXECUTIONS_02 (
  EXEC_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  STATUS STRING,
  DETAILS VARIANT
);

