USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_FAILURE_DEADLETTER ( DLQ_ID STRING PRIMARY KEY, DELIV_ID STRING, ERROR_JSON VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

