USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_ERRORS ( ERR_ID STRING PRIMARY KEY, RENDERER_ID STRING, JOB_ID STRING, ERROR_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

