USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INBOUND_WEBHOOK_METRICS ( METRIC_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RECEIVED_COUNT INT, FAILED_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

