USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OUTBOUND_WEBHOOK_QUEUE ( Q_ID STRING PRIMARY KEY, TARGET_URL STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

