USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCROW_RECORDS_02 (
  ESCROW_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ESCROW_LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

