USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONFIG_HISTORY ( HIST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CONFIG JSON, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), APPLIED_BY STRING );

