USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CREDENTIAL_ROTATION_LOG ( LOG_ID STRING PRIMARY KEY, CLIENT_ID STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), BY_USER STRING, DETAILS VARIANT );

