USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CREDENTIAL_REGISTRY ( CRED_ID STRING PRIMARY KEY, CLIENT_ID STRING, CRED_META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

