USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPRECATION_REGISTRY ( DEP_ID STRING PRIMARY KEY, OBJECT_REF STRING, DEPRECATION_DATE TIMESTAMP_LTZ, NOTIFY JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

