USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_POLICY_EXECUTIONS_02 (
  EXEC_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ,
  RESULT VARIANT
);

