USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_LINEAGE_02 (
  LINEAGE_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  SOURCE_REFS ARRAY,
  CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

