USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_QUOTA_USAGE ( USAGE_ID STRING PRIMARY KEY, QUOTA_ID STRING, USAGE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

