USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUSPICIOUS_ACTIVITY_FLAGS_02 (
  FLAG_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED BOOLEAN DEFAULT FALSE
);

