USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_NOTES ( CREDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, AMOUNT NUMBER, REASON CLOB, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

