USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_REFUND_REQUESTS ( REQ_ID STRING PRIMARY KEY, BILLING_LINE_ID STRING, TENANT_ID STRING, AMOUNT NUMBER, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

