USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POST_SIGN_HOOKS_02 (
  HOOK_ID STRING PRIMARY KEY,
  NAME STRING,
  HOOK_TYPE STRING,
  CONFIG VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE
);

