USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POST_SIGN_EXECUTIONS_02 (
  EXEC_ID STRING PRIMARY KEY,
  HOOK_ID STRING,
  BUNDLE_ID STRING,
  STATUS STRING,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESULT VARIANT
);

