USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_QUEUE_03 ( QUEUE_ID STRING PRIMARY KEY, JOB_ID STRING, ATTEMPTS INT DEFAULT 0, NEXT_RUN_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

