USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECONCILIATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, DISC_ID STRING, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

