USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_FAILURES_03 ( FAILURE_ID STRING PRIMARY KEY, QUEUE_ID STRING, ERROR_CODE STRING, ERROR_DETAIL CLOB, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

