USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_APPLICATION_LOG ( LOG_ID STRING PRIMARY KEY, INVOICE_ID STRING, JUR_ID STRING, TAX_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

