USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_ADJUSTMENT_REQUESTS ( REQ_ID STRING PRIMARY KEY, INVOICE_ID STRING, TENANT_ID STRING, ADJUSTMENT_JSON VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

