USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRIEVAL_AUDIT_03 ( AUDIT_ID STRING PRIMARY KEY, QUERY VARIANT, RESULT_COUNT INT, USER_REF STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

