USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_SCHEDULER ( SCHED_ID STRING PRIMARY KEY, POLICY_ID STRING, CRON_EXPR STRING, LAST_RUN TIMESTAMP_LTZ, NEXT_RUN TIMESTAMP_LTZ );

