USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_SESSIONS_03 ( SESSION_ID STRING PRIMARY KEY, SIGNATORY_REF STRING, BUNDLE_ID STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_UPDATED_AT TIMESTAMP_LTZ );

