USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_ANNUAL_REPORTS ( REPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, YEAR INT, REPORT_LOCATION STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

