USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACT_INDEX ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, TERMS VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ, EXPIRES_AT TIMESTAMP_LTZ );

