USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_RESPONSES_03 ( RESPONSE_ID STRING PRIMARY KEY, CALLBACK_ID STRING, RESPONSE VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

