USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PAYOUT_RUNS ( RUN_ID STRING PRIMARY KEY, PROVIDER_ID STRING, AMOUNT NUMBER, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

