USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_CAPACITIES ( CAP_ID STRING PRIMARY KEY, RENDERER_ID STRING, MAX_CONCURRENCY INT, RESERVATION JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

