USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTICES_03 ( NOTICE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, NOTICE_TYPE STRING, SENT_AT TIMESTAMP_LTZ, META VARIANT );

