USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVERNANCE_MEETING_MINUTES ( MIN_ID STRING PRIMARY KEY, TOPICS VARIANT, ATTENDEES ARRAY, MINUTES CLOB, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

