USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_AUDIT_03 ( AUDIT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION STRING, ADMIN_USER STRING, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

