USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GOVERNANCE_ACTION_ITEMS ( ACTION_ID STRING PRIMARY KEY, MIN_ID STRING, OWNER STRING, STATUS STRING, DUE_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

