USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_INTEGRATIONS_03 ( INTEGRATION_ID STRING PRIMARY KEY, NAME STRING, TYPE STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

