USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_SLA_METRICS ( MET_ID STRING PRIMARY KEY, RENDERER_ID STRING, SLO_NAME STRING, VALUE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

