USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ONCALL_ROSTER ( ROSTER_ID STRING PRIMARY KEY, TEAM_REF STRING, MEMBERS ARRAY, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ );

