USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ALERT_HISTORY ( ALERT_ID STRING PRIMARY KEY, ROSTER_ID STRING, ALERT_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

