USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REDACTION_LOGS_03 ( REDACTION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REDACTED_BY STRING, FIELDS REDACTED VARIANT, REDACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

