USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SSO_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SSO_PROVIDER STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

