USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHN_METHOD_USAGE ( USAGE_ID STRING PRIMARY KEY, METHOD_ID STRING, SUBJECT_REF STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

