USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_EVENT_LOGS ( LOG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHOD_ID STRING, RESULT STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

