USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATIONS_03 ( NOTIFY_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, LEVEL STRING, CONTEXT VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

