USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_COST_ESTIMATES ( EST_ID STRING PRIMARY KEY, REQ_ID STRING, ESTIMATE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

