USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACTIONS_03 ( ACTION_ID STRING PRIMARY KEY, ADMIN_USER STRING, ACTION STRING, TARGET_OBJECT STRING, ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

