USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_MONITORING_ALERTS ( ALERT_ID STRING PRIMARY KEY, PARTY_REF STRING, ALERT_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

