USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_ACCESS_LOGS_03 ( LOG_ID STRING PRIMARY KEY, TOKEN_ID STRING, ENDPOINT STRING, REQUEST_PAYLOAD VARIANT, RESPONSE_CODE INT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

