USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_BUDGET_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, THRESHOLD VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

