USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANNEL_CONFIGS_04 ( CONFIG_ID STRING PRIMARY KEY, CHANNEL STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

