USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RUNBOOK_LINKS ( LINK_ID STRING PRIMARY KEY, INCIDENT_ID STRING, RUNBOOK_REF STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

