USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_COMMS_HISTORY ( HIST_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING, DETAILS VARIANT );

