USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_DELIVERIES_04 ( DELIVERY_ID STRING PRIMARY KEY, NOTIFY_ID STRING, EMAIL STRING, SUBJECT STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ, RESPONSE VARIANT );

