USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_EVENT_HANDLERS ( HANDLER_ID STRING PRIMARY KEY, STREAM_ID STRING, HANDLER_JSON VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

