USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_INSTALLATION_RECORDS ( INST_ID STRING PRIMARY KEY, TENANT_ID STRING, DEPLOY_ENV STRING, INSTALLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

