USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_EVENTS_04 ( EVENT_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ, STATUS STRING, RESPONSE VARIANT );

