USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_INSTALLATION_ISSUES ( ISSUE_ID STRING PRIMARY KEY, INST_ID STRING, DESCRIPTION CLOB, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

