USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRIES_04 ( RETRY_ID STRING PRIMARY KEY, EVENT_ID STRING, ATTEMPT INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, LAST_ERROR VARIANT );

