USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_SLA_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, PARTNER_ID STRING, SLO_REF STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

