USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATE_LIMITS_04 ( LIMIT_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, LIMITS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

