USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANNUAL_AUDIT_OUTCOMES ( OUTCOME_ID STRING PRIMARY KEY, AUDIT_ID STRING, OUTCOME VARIANT, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

