USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_QUOTAS_04 ( QUOTA_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, QUOTA VARIANT, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ );

