USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SLA_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, SLO_REF STRING, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

