USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_RECONCILIATION ( REC_ID STRING PRIMARY KEY, REQ_ID STRING, EXPECTED JSON, ACTUAL JSON, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

