USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_COMPLIANCE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, DOC_ID STRING, REVIEWER STRING, RESULT VARIANT, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

