USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_BREACH_RESOLUTION ( RES_ID STRING PRIMARY KEY, NOTIF_ID STRING, ACTIONS VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

