USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_REVIEW_WORK_ITEMS ( ITEM_ID STRING PRIMARY KEY, TENANT_ID STRING, ITEM_JSON VARIANT, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

