USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_04 ( USAGE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CONTEXT VARIANT );

