USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_FLAGS_04 ( FLAG_ID STRING PRIMARY KEY, TARGET_REF STRING, FLAG_TYPE STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED_AT TIMESTAMP_LTZ, DETAILS VARIANT );

