USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DISTRIBUTION_LIST ( DL_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RECIPIENTS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

