USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_METADATA_04 ( META_ID STRING PRIMARY KEY, BUNDLE_ID STRING, JURISDICTION STRING, LEGAL_NOTES VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

