USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_CHECKSUMS_04 ( ARCHIVE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHECKSUM STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

