USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RENDER_STATS ( STAT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RENDER_COUNT NUMBER, LAST_RENDERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

