USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_VIOLATIONS_04 ( VIOLATION_ID STRING PRIMARY KEY, SLA_ID STRING, BUNDLE_ID STRING, DESCRIPTION STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

