USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_GEOLOCATION_LOGS ( LOG_ID STRING PRIMARY KEY, DEVICE_ID STRING, LATITUDE NUMBER, LONGITUDE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

