USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_MATCH_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, MATCH_SCORE NUMBER, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

