USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_EXPORTS_04 ( EXPORT_ID STRING PRIMARY KEY, TYPE STRING, CREATED_BY STRING, STATUS STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

