USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_REVOCATION_LOG ( REV_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

