USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_COMPLIANCE_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_JSON VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

