USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLIANCE_DASHBOARDS ( DASH_ID STRING PRIMARY KEY, TENANT_ID STRING, DASH_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

