USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ADOPTION_METRICS ( MET_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, USAGE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

