USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELETION_ACTIONS_04 ( ACTION_ID STRING PRIMARY KEY, REQ_ID STRING, ACTION STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PERFORMED_BY STRING );

