USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_MODERATION_LOGS ( LOG_ID STRING PRIMARY KEY, DOC_ID STRING, VIOLATION_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

