USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_MODERATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, LOG_ID STRING, ACTION_JSON VARIANT, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

