USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DRIFT_RETRAINING_QUEUE ( Q_ID STRING PRIMARY KEY, MODEL_ID STRING, TRIGGER_REASON STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

