USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_HEALTH_CHECKS ( CHECK_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, STATUS STRING, DETAILS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

