USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_CONTENT_REGISTRY ( CONTENT_ID STRING PRIMARY KEY, NAME STRING, CONTENT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

