USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ROOT_CAUSE_INDEX ( ROOT_ID STRING PRIMARY KEY, INCIDENT_ID STRING, CAUSE_JSON VARIANT, IDENTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

