USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_MANAGEMENT_REGISTRY ( CHANGE_ID STRING PRIMARY KEY, TITLE STRING, DETAILS VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

