USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_AUDIT_05 (
  AUDIT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

