USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_MANAGEMENT_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, CHANGE_ID STRING, APPROVER STRING, STATUS STRING, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

