USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VERSIONS_05 (
  VERSION_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  VERSION_NUM INT,
  DEFINITION VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

