USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_HISTORY_05 (
  CH_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  CHANGE_TYPE STRING,
  DETAILS VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

