USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_QUEUE_05 (
  Q_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ATTEMPTS INT DEFAULT 0,
  STATUS STRING DEFAULT 'PENDING',
  NEXT_RUN_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

