USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SUCCESS_ACTIONS ( ACTION_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING );

