USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAMPER_CHECKS_05 (
  CHECK_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHECK_TYPE STRING,
  RESULT VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

