USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_TRANSACTIONS_05 (
  TX_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ANCHOR_TYPE STRING,
  ANCHOR_REF STRING,
  PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

