USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_INDEX_05 (
  INDEX_ID STRING PRIMARY KEY,
  TX_ID STRING,
  BUNDLE_ID STRING,
  PROOF VARIANT,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

