USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHECKS_05 (
  EVC_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHECK_NAME STRING,
  PASS BOOLEAN,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

