USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_OPERATION_RUN_LOGS ( LOG_ID STRING PRIMARY KEY, PB_ID STRING, EXEC_ID STRING, LOG_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

