USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IMAGE_HASHES_05 (
  HASH_ID STRING PRIMARY KEY,
  IMG_ID STRING,
  HASH STRING,
  ALGORITHM STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

