USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AB_TEST_ASSIGNMENT_LOG ( LOG_ID STRING PRIMARY KEY, TEST_ID STRING, SUBJECT_REF STRING, VARIANT STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

