USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SHARD_MAP_05 (
  SHARD_ID STRING PRIMARY KEY,
  SNAP_ID STRING,
  NODE_REF STRING,
  STATUS STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

