USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_ANALYTICS_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, ANALYTICS_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

