USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_HEALTH_05 (
  HEALTH_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  METRICS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

