USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_REBALANCE_05 (
  REBAL_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  ACTION VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

