USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ERROR_BUDGET_BURN_RATE ( BURN_ID STRING PRIMARY KEY, SERVICE_REF STRING, BURN_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

