USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_COMPLIANCE_DASHBOARD ( DASH_ID STRING PRIMARY KEY, SERVICE_REF STRING, SLO_SUMMARY VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

