USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DECISIONS_05 (
  DECISION_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  MODEL_ID STRING,
  DECISION VARIANT,
  DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

