USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_SOURCING_STREAMS ( STREAM_ID STRING PRIMARY KEY, ENTITY_REF STRING, STREAM_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

