USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_REPLAY_JOBS ( JOB_ID STRING PRIMARY KEY, STREAM_ID STRING, OFFSET BIGINT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

