USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPLAINABILITY_LOGS_05 (
  LOG_ID STRING PRIMARY KEY,
  DECISION_ID STRING,
  EXPLANATION VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

