USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_SNAPSHOT_MANIFEST ( SNAP_ID STRING PRIMARY KEY, LOCATION STRING, SIZE_BYTES NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

