USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESTORE_JOBS_05 (
  RESTORE_ID STRING PRIMARY KEY,
  ARCH_ID STRING,
  REQUESTED_BY STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

