USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CHECKS_05 (
  CCHK_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  CHECK_NAME STRING,
  RESULT VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

