USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_ISSUES_05 (
  ISSUE_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  DESCRIPTION STRING,
  SEVERITY STRING,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED_AT TIMESTAMP_LTZ
);

