USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_EVENTS_05 (
  EVENT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  BUNDLE_ID STRING,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING
);

