USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AUDIT_05 (
  AUDIT_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ACTION STRING,
  TARGET_REF STRING,
  DETAILS VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

