USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LABELING_QUALITY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RES_ID STRING, SCORE NUMBER, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

