USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_STEPS_05 (
  STEP_ID STRING PRIMARY KEY,
  TITLE STRING,
  BODY CLOB,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

