USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ONCALL_ROTATION ( ROT_ID STRING PRIMARY KEY, TEAM_REF STRING, MEMBERS ARRAY, ROTATION_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

