USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ROTATIONS_05 (
  ROTATION_ID STRING PRIMARY KEY,
  NAME STRING,
  MEMBERS ARRAY,
  TIMEZONE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

