USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENT_REGISTRY ( INCIDENT_ID STRING PRIMARY KEY, SUMMARY CLOB, SEVERITY STRING, STATUS STRING, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

