USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTACT_DIRECTORY_05 (
  CONTACT_ID STRING PRIMARY KEY,
  NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  ROLE STRING,
  META VARIANT
);

