USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENT_FOLLOWUPS ( FOLLOWUP_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTION_JSON VARIANT, ASSIGNED_TO STRING, DUE_AT TIMESTAMP_LTZ, STATUS STRING );

