USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_COMMUNICATION_LOG ( LOG_ID STRING PRIMARY KEY, CHANGE_ID STRING, MESSAGE CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANNEL STRING );

