USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_TICKETS_05 (
  TICKET_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  SUBJECT STRING,
  BODY CLOB,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

