USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_REPORT_SUMMARIES ( REPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

