USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TICKET_UPDATES_05 (
  UPDATE_ID STRING PRIMARY KEY,
  TICKET_ID STRING,
  AUTHOR STRING,
  UPDATE_TEXT CLOB,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

