USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS_05 (
  WINDOW_ID STRING PRIMARY KEY,
  NAME STRING,
  START_AT TIMESTAMP_LTZ,
  END_AT TIMESTAMP_LTZ,
  REASON STRING
);

