USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_EVENTS_05 (
  EVENT_ID STRING PRIMARY KEY,
  WINDOW_ID STRING,
  DESCRIPTION STRING,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

