USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REQUEST_ATTACHMENTS (
  ATTACH_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  FILE_REF STRING,
  CONTENT_TYPE STRING,
  SIZE_BYTES NUMBER,
  UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

