USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAML_MAPPINGS_05 (
  MAPPING_ID STRING PRIMARY KEY,
  IDP_ID STRING,
  MAPPING_RULES VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

