USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_CLIENTS_05 (
  CLIENT_ID STRING PRIMARY KEY,
  NAME STRING,
  REDIRECT_URIS ARRAY,
  SCOPES ARRAY,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

