USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_PROFILE_V2 ( PROFILE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PROFILE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

