USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_QUARANTINE_06 ( QUARANTINE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED BOOLEAN DEFAULT FALSE
);
