USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUARANTINE_HISTORY_06 ( HISTORY_ID STRING PRIMARY KEY, QUARANTINE_ID STRING, ACTION STRING, ACTED_BY STRING, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
