USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_ESCALATIONS_12 ( ESCALATION_ID STRING PRIMARY KEY, INSTANCE_ID STRING, STEP_REF STRING, ESCALATED_TO STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

