USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEYS_14 ( KEY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, KEY_HASH STRING, SCOPE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

