USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_ADMIN_ANNOUNCEMENTS_14 ( ANN_ID STRING PRIMARY KEY, TITLE STRING, BODY STRING, LEVEL STRING, CREATED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

