USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_VERSIONS_02 ( SCHEMA_VERSION_ID STRING PRIMARY KEY, SCHEMA_ID STRING, VERSION_NUMBER INT, MAPPING_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

