USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_MATCHES_06 ( MATCH_ID STRING PRIMARY KEY, JOB_ID STRING, CANDIDATE_PROFILE_ID STRING, SCORE FLOAT, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
