USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_TRUST_SCORES_06 ( SCORE_ID STRING PRIMARY KEY, DEVICE_REF STRING, SCORE FLOAT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
