USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_AUDIT_INDEX_02 ( IDX_ID STRING PRIMARY KEY, AUDIT_ID STRING, ENTITY_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

