USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_FORECASTS_06 ( FORECAST_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PREDICTION VARIANT, HORIZON STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
