USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINALIZATION_LOGS_02 ( LOG_ID STRING PRIMARY KEY, FQ_ID STRING, STATUS STRING, DETAILS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

