USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ALERTS_06 ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TRIGGER VARIANT, ACTION VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
