USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEEDBACK_METRICS_02 ( METRIC_ID STRING PRIMARY KEY, FB_ID STRING, METRIC_NAME STRING, METRIC_VALUE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

