USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_ALERTS_06 ( ALERT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RULE_ID STRING, SCORE FLOAT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
