USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REFUND_OUTCOMES_02 ( OUTCOME_ID STRING PRIMARY KEY, REQUEST_ID STRING, STATUS STRING, PROCESSED_AT TIMESTAMP_LTZ, DETAILS VARIANT );

