USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPLIANCE_CHECKS_02 ( CHECK_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHECK_NAME STRING, RESULT VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

