USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_HITS_06 ( HIT_ID STRING PRIMARY KEY, FEED_ID STRING, TARGET_REF STRING, DETAILS VARIANT, HIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
