USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_DEFINITIONS_06 ( KPI_ID STRING PRIMARY KEY, NAME STRING, QUERY STRING, OWNER STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
