USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_JOBS_02 ( JOB_ID STRING PRIMARY KEY, OBJECT_NAME STRING, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, META VARIANT );

