USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DASHBOARD_WIDGETS_06 ( WIDGET_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, OWNER STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
