USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_JOBS_06 ( REPORT_JOB_ID STRING PRIMARY KEY, NAME STRING, SCHEDULE STRING, LAST_RUN TIMESTAMP_LTZ, ENABLED BOOLEAN DEFAULT TRUE
);
