USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_RUNS_06 ( RUN_ID STRING PRIMARY KEY, REPORT_JOB_ID STRING, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LOCATION STRING
);
