USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANALYTICS_06 ( ANALYTIC_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, METRICS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
