USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_LOGS (
  LOG_ID STRING PRIMARY KEY,
  VERIFY_ID STRING,
  STEP STRING,
  DETAIL VARIANT,
  LOG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

