USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QUALITY_06 ( QUALITY_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SCORE FLOAT, DETAILS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
