USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUALITY_06 ( TQ_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE FLOAT, COMMENT STRING, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
