USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_SIMILARITY_CACHE_06 ( CACHE_ID STRING PRIMARY KEY, SOURCE_ID STRING, TARGET_ID STRING, SCORE FLOAT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
