CREATE OR REPLACE TABLE DOCGEN.ACCOUNTS (ACCOUNT_ID STRING PRIMARY KEY, NAME STRING, INTEGRATION_KEY_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE TABLE DOCGEN.ACTIVATION_AUDIT (AUDIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ACTION STRING, PERFORMED_BY STRING, DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());

Accounts and activation audit tables implement entitlement and activation audit patterns required by the Admin flows in your specs @21 @31. @21 @31

