USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_INSTANCES_06 (
  INSTANCE_ID STRING PRIMARY KEY,
  WORKFLOW_ID STRING,
  CURRENT_STEP INT,
  STATUS STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

