USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_ESCALATION_RULES ( RULE_ID STRING PRIMARY KEY, ALERT_TYPE STRING, ESCALATION_CHAIN VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

