USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, SLO_REF STRING, REASON CLOB, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GRANTED_BY STRING ); @31 @24

