USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_REGISTRY ( COMPLAINT_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY CLOB, STATUS STRING, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

