USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_EVENTS_06 (
  EVENT_ID STRING PRIMARY KEY,
  INSTANCE_ID STRING,
  EVENT_TYPE STRING,
  PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

