USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, COMPLAINT_ID STRING, ACTION_JSON VARIANT, ASSIGNED_TO STRING, DUE_AT TIMESTAMP_LTZ, STATUS STRING );

