USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EVALUATIONS_06 ( EVAL_ID STRING PRIMARY KEY, BINDING_ID STRING, CONTEXT VARIANT, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

