USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_LOGS_06 (
  LOG_ID STRING PRIMARY KEY,
  INSTANCE_ID STRING,
  APPROVER STRING,
  ACTION STRING,
  NOTES CLOB,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

