USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_EVIDENCE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, CHECKSUM STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

