USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESIGN_TEMPLATES_06 (
  TEMPLATE_ID STRING PRIMARY KEY,
  NAME STRING,
  VERSION INT,
  CONTENT CLOB,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

