USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DATA_INVENTORY ( ITEM_ID STRING PRIMARY KEY, TENANT_ID STRING, DATA_DESC VARIANT, SENSITIVITY STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

