USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SECTIONS_06 (
  SECTION_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  SECTION_KEY STRING,
  SECTION_CONTENT CLOB,
  ORDERING INT
);

