USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_RETENTION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, DOC_ID STRING, TENANT_ID STRING, EXPIRES_AT TIMESTAMP_LTZ, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB );

