USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_REFERENCES ( REF_ID STRING PRIMARY KEY, KEY_ID STRING, KEY_ROLE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB ); @31 @24

