USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CACHE ( CERT_FP STRING PRIMARY KEY, OCSP_STATUS STRING, RESP_JSON VARIANT, FRESH_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

