USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOTION_LOGS_06 ( LOG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, MOTION_TYPE STRING, DETAILS VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

