USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_TXID_REGISTRY ( REG_ID STRING PRIMARY KEY, ANCHOR_ID STRING, TXID STRING, NETWORK STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

