USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_WORKFLOW_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, WORKFLOW_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

