USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TEMPLATES_MAP_06 (
  MAP_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  TEMPLATE_ID STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

