USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_WORKFLOW_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RUN_ID STRING, STEP_REF STRING, ACTOR STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

