USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_BLACKLIST_06 ( BL_ID STRING PRIMARY KEY, SESSION_ID STRING, REASON STRING, BLACKLISTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

