USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENGINE_RUNS ( RUN_ID STRING PRIMARY KEY, RULE_ID STRING, TENANT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31 @24

