USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_LOGS_06 (
  LOG_ID STRING PRIMARY KEY,
  RENDER_ID STRING,
  MESSAGE STRING,
  LOG_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

