USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_ARCHIVES_06 (
  ARCHIVE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  S3_PATH STRING,
  SIZE_BYTES NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

