USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_CACHE_06 (
  CACHE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  PREVIEW_URL STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

