USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ABUSE_REPORTS_06 ( REPORT_ID STRING PRIMARY KEY, REPORTED_BY STRING, TARGET_REF STRING, DESCRIPTION STRING, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

