USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDITION_METRICS_06 (
  METRIC_ID STRING PRIMARY KEY,
  RENDER_ID STRING,
  LATENCY_MS INT,
  STATUS STRING,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

