USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ABUSE_ACTIONS_06 ( ACTION_ID STRING PRIMARY KEY, REPORT_ID STRING, ACTION STRING, ACTIONED_BY STRING, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

