USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, PROV_ID STRING, STATUS STRING, ISSUES VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

