USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_ANCHOR_RETRIES ( RETRY_ID STRING PRIMARY KEY, ANCHOR_ID STRING, STATUS STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

