USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGE_GRANTS_06 (
  GRANT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  RESOURCE_REF STRING,
  PRIVILEGES ARRAY,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

