USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TAMPER_ALERTS ( ALERT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, DETECTION_METHOD STRING, DETAILS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

