USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_POLICIES_06 (
  ROLE_POLICY_ID STRING PRIMARY KEY,
  ROLE_ID STRING,
  POLICY_REF STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

