USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_FIXES ( FIX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ACTION_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), APPLIED_BY STRING ); @31 @24

