USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_HASH_AUDIT ( AUDIT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, HASH_BEFORE STRING, HASH_AFTER STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

