USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_RECORDS_06 (
  MFA_ID STRING PRIMARY KEY,
  USER_REF STRING,
  METHOD STRING,
  ENROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

