USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_BACKUP_INDEX ( BACKUP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, BACKED_UP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHECKSUM STRING ); @31 @24

