USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RESTORE_JOBS ( JOB_ID STRING PRIMARY KEY, BACKUP_ID STRING, REQUESTED_BY STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31 @24

