USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_NOTES_SEARCH_INDEX ( IDX_ID STRING PRIMARY KEY, NOTE_ID STRING, TOKENS ARRAY, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

