USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONBOARDING_REGISTRY ( REG_ID STRING PRIMARY KEY, OPERATOR_REF STRING, STARTED_AT TIMESTAMP_LTZ, STATUS STRING, META VARIANT ); @31 @24

