USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_QUEUE_06 (
  PURGE_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  CRON_EXPR STRING,
  LAST_RUN_AT TIMESTAMP_LTZ,
  ENABLED BOOLEAN DEFAULT TRUE
);

