USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_FEEDBACK ( FB_ID STRING PRIMARY KEY, OPERATOR_REF STRING, FEEDBACK JSON, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

