USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_METHOD_REFS_06 ( PM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PM_TYPE STRING, REFERENCE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

