USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_SCHEDULE ( SCHED_ID STRING PRIMARY KEY, OPERATOR_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, ZONE STRING ); @31 @24

