USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_ATTEMPTS_06 ( ATTEMPT_ID STRING PRIMARY KEY, PM_ID STRING, AMOUNT NUMBER, CURRENCY STRING, STATUS STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

