USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_AUDIT_06 (
  AUDIT_ID STRING PRIMARY KEY,
  PURGE_ID STRING,
  ROWS_PURGED NUMBER,
  RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

