USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RECONCILIATIONS_06 ( RECON_ID STRING PRIMARY KEY, ATTEMPT_ID STRING, STATUS STRING, DETAILS VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

