USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_AGREEMENT_REGISTRY ( AGREEMENT_ID STRING PRIMARY KEY, TENANT_ID STRING, AGREEMENT_JSON VARIANT, EXECUTED_AT TIMESTAMP_LTZ );

