USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTES_06 ( DISPUTE_ID STRING PRIMARY KEY, INVOICE_ID STRING, ACCOUNT_ID STRING, REASON STRING, STATUS STRING, OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

