USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CAPACITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, PLAN_ID STRING, MESSAGE CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @31 @24

- Anara: Emitting next 150 SQL DDL artifacts (files 4101–4250) for the E-Signature module now. @31 @24 @263
