USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKUP_RUNS_06 (
  RUN_ID STRING PRIMARY KEY,
  MANIFEST_ID STRING,
  STATUS STRING,
  OUTPUT VARIANT,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP_LTZ
);

