USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_IMPACT_ANALYSIS ( ANALYSIS_ID STRING PRIMARY KEY, CHANGE_ID STRING, IMPACT_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

