USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ACCESS_LOGS_06 (
  LOG_ID STRING PRIMARY KEY,
  KEY_ID STRING,
  ACCESSOR STRING,
  ACTION STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

