USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DISCLOSURE_REGISTRY ( DISCLOSURE_ID STRING PRIMARY KEY, TENANT_ID STRING, DISCLOSURE_JSON VARIANT, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

