USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DISCLOSURE_ACCEPTANCES ( ACCEPT_ID STRING PRIMARY KEY, DISCLOSURE_ID STRING, SUBJECT_REF STRING, ACCEPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

