USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CACHE_06 (
  OCSP_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  OCSP_RESPONSE VARIANT,
  Fetched_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

