USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ALERT_ID STRING, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

