USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TIMESTAMPS_06 (
  TS_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  TA_ID STRING,
  TS_TOKEN VARIANT,
  ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

