USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_FRAUD_SIGNALS (
  SIGNAL_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  GEO VARIANT,
  RISK_LEVEL STRING,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

