USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_PROOFS_06 (
  PROOF_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  PROOF VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

