USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RUN_CHECKSUMS ( CHECK_ID STRING PRIMARY KEY, RUN_ID STRING, CHECKSUM STRING, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

