USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORTS_06 (
  EVIDENCE_EXPORT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  FORMAT STRING,
  LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

