USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_REPORTS_06 (
  REPORT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LOCATION STRING
);

