USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RATE_CARD_VERSIONS ( VERSION_ID STRING PRIMARY KEY, RATE_CARD_ID STRING, VERSION_NUMBER INT, BODY VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

