USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLDS_06 (
  HOLD_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ
);

