USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINT_INDEX (
  FP_ID STRING PRIMARY KEY,
  DEVICE_HASH STRING,
  SIGNER_ID STRING,
  LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

