USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DELIVERY_METRICS ( METRIC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DELIVERED INT, FAILED INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

