USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUPPRESSION_REGISTRY ( SUPP_ID STRING PRIMARY KEY, RULE_REF STRING, TENANT_ID STRING, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

