USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_EXPORTS_06 (
  EXPORT_ID STRING PRIMARY KEY,
  INTEGRATION_ID STRING,
  PAYLOAD VARIANT,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

