USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_RESPONSES_06 (
  RESP_ID STRING PRIMARY KEY,
  EXPORT_ID STRING,
  RESPONSE VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

