USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATECARD_VERSIONS_06 (
  RATE_ID STRING PRIMARY KEY,
  NAME STRING,
  VERSION INT,
  DEFINITION VARIANT,
  ACTIVE BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

