USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_ISSUES ( ISSUE_ID STRING PRIMARY KEY, LOG_ID STRING, DESCRIPTION CLOB, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

