USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_COVERAGE_MATRIX ( MATRIX_ID STRING PRIMARY KEY, TENANT_ID STRING, COVERAGE_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

