USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRICING_CACHE_06 (
  CACHE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  RATE_REF STRING,
  CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

