USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_PREVIEWS_06 (
  PREVIEW_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  LINE_ITEMS VARIANT,
  INVOICE_HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

