USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_LINE_ITEMS_06 (
  ITEM_ID STRING PRIMARY KEY,
  PREVIEW_ID STRING,
  DESCRIPTION STRING,
  AMOUNT NUMBER,
  META VARIANT
);

