USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINAL_INVOICES_06 (
  INVOICE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  TOTAL_AMOUNT NUMBER,
  LINE_ITEMS VARIANT,
  ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

