USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_ACCOUNTS_06 (
  PARTNER_ID STRING PRIMARY KEY,
  NAME STRING,
  CONFIG VARIANT,
  ACTIVE BOOLEAN DEFAULT TRUE
);

