USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REGISTRY ( HOLD_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, PLACED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RELEASED_AT TIMESTAMP_LTZ );

