USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_EVENTS_06 (
  EVENT_ID STRING PRIMARY KEY,
  PARTNER_ID STRING,
  TYPE STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

