USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_TELEMETRY_06 (
  TELE_ID STRING PRIMARY KEY,
  PARTNER_ID STRING,
  METRIC_KEY STRING,
  METRIC_VALUE VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

