USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_RATE_LIMITS_06 (
  LIMIT_ID STRING PRIMARY KEY,
  PARTNER_ID STRING,
  LIMITS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

