USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_INVOICE_LINKS_06 (
  LINK_ID STRING PRIMARY KEY,
  PARTNER_ID STRING,
  INVOICE_ID STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

