USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PENALTY_LOG ( PEN_ID STRING PRIMARY KEY, OPERATOR_REF STRING, REASON CLOB, AMOUNT NUMBER, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

