USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_REWARD_LOG ( REWARD_ID STRING PRIMARY KEY, OPERATOR_REF STRING, DETAILS VARIANT, AWARDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

