USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_MATERIAL_FEEDBACK ( FB_ID STRING PRIMARY KEY, CONTENT_ID STRING, OPERATOR_REF STRING, FEEDBACK JSON, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

