USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATE_LIMITS (
  LIMIT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  LIMIT_JSON VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

