USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_DASHBOARDS_06 (
  DASH_ID STRING PRIMARY KEY,
  NAME STRING,
  CONFIG VARIANT,
  OWNER STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

