USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DASHBOARD_RUNS_06 (
  RUN_ID STRING PRIMARY KEY,
  DASH_ID STRING,
  STATUS STRING,
  OUTPUT VARIANT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

