USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_SELECTION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RUN_ID STRING, SELECTED_MODEL STRING, INPUT_HASH STRING, SELECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

