USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LLM_COST_TRACKING ( TRACK_ID STRING PRIMARY KEY, MODEL_ID STRING, COST NUMBER, RUN_ID STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

