USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TERMINATIONS_06 (
  TERM_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  REASON STRING,
  TERMINATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

