USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LLM_QUOTA_ENFORCEMENT ( QUOTA_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, LIMITS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

