USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_USAGE (
  USAGE_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  METRIC_NAME STRING,
  VALUE NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

