USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_METERING ( METER_ID STRING PRIMARY KEY, CLIENT_ID STRING, API_ENDPOINT STRING, CALL_COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

