USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_THROTTLE_EVENTS ( EVENT_ID STRING PRIMARY KEY, CLIENT_ID STRING, PROFILE_ID STRING, VIOLATION_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

