USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PREFERENCES_07 ( PREF_ID STRING PRIMARY KEY, USER_REF STRING, PREF_KEY STRING, PREF_VALUE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

