USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLIENT_ALERT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, CLIENT_ID STRING, ALERT_KEYS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

