USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_REGISTRY ( DISPUTE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INVOICE_REF STRING, STATUS STRING, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

