USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATIONS_07 ( NOTIF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RECIPIENT VARIANT, CONTEXT VARIANT, STATUS STRING, SENT_AT TIMESTAMP_LTZ );

