USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DELIVERIES_07 ( DELIVERY_ID STRING PRIMARY KEY, NOTIF_ID STRING, STATUS STRING, RESPONSE VARIANT, DELIVERED_AT TIMESTAMP_LTZ );

