USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LANG_TEMPLATES_07 ( LANG_TPL_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCALE STRING, CONTENT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

