USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECIPIENT_PREFERENCES_07 ( PREF_ID STRING PRIMARY KEY, RECIPIENT_REF STRING, CHANNELS ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

