USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PERMISSIONS_07 ( DP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, PERM_LEVEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

