USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SURVEY_RESPONSE_ITEMS ( ITEM_ID STRING PRIMARY KEY, SURVEY_ID STRING, QUESTION_REF STRING, ANSWER VARIANT, RESPONDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

