USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_AUDITS_07 ( AUDIT_ID STRING PRIMARY KEY, EXPORT_ID STRING, USER_REF STRING, DETAILS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

