USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EVENT_SUMMARY_MV ( SUMMARY_ID STRING PRIMARY KEY, SCOPE STRING, AGG_PAYLOAD VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

