USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECENT_INCIDENTS_VIEW ( INCIDENT_ID STRING PRIMARY KEY, TITLE STRING, SEVERITY STRING, STATUS STRING, RAISED_AT TIMESTAMP_LTZ ); @31

