USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ACTIVITY_CACHE_07 ( CACHE_ID STRING PRIMARY KEY, USER_REF STRING, ACTIVITY VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

