USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ALERTS_07 ( ALERT_ID STRING PRIMARY KEY, USER_REF STRING, TITLE STRING, BODY CLOB, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

