USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ALERT_READS_07 ( READ_ID STRING PRIMARY KEY, ALERT_ID STRING, USER_REF STRING, READ_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

