USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDED_ASSET_INDEX ( IDX_ID STRING PRIMARY KEY, ASSET_ID STRING, KEYWORDS ARRAY, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

