USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BINARY_BLOB_REGISTRY ( BLOB_ID STRING PRIMARY KEY, LOCATION STRING, SIZE NUMBER, CONTENT_TYPE STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

