USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEYWORD_BLACKLIST_07 ( KW_ID STRING PRIMARY KEY, KEYWORD STRING, REASON STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

