USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOB_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, BLOB_ID STRING, SUBJECT STRING, ACTION STRING, ACCESS_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

