USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_HISTORY ( HIST_ID STRING PRIMARY KEY, FEATURE_NAME STRING, TENANT_ID STRING, VALUE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGED_BY STRING ); -- @31 @24

