USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_FLAGS_07 ( FLAG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FLAG_TYPE STRING, REPORTED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

