USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TOGGLE_MATRIX ( MATRIX_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_SET VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

