USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_QUOTA_DEFINITIONS ( QUOTA_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, LIMIT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

