USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_VERSION_HISTORY ( VERSION_ID STRING PRIMARY KEY, CLAUSE_ID STRING, VERSION_NUMBER INT, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

