USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_QUOTA_CONSUMPTION ( CONSUME_ID STRING PRIMARY KEY, QUOTA_ID STRING, PERIOD_START DATE, PERIOD_END DATE, USAGE_COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

