USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_CHECKS_07 ( CHECK_ID STRING PRIMARY KEY, USER_REF STRING, SCOPE STRING, RESULT BOOLEAN, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

