USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_RESTRICTIONS_07 ( RESTRICT_ID STRING PRIMARY KEY, TARGET_REF STRING, REGIONS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

