USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_EVENTS ( EVENT_ID STRING PRIMARY KEY, SIGNER_ID STRING, PROFILE_ID STRING, RESULT VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

