USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_FRAUD_ALERTS ( ALERT_ID STRING PRIMARY KEY, SIGNER_ID STRING, SCORE NUMBER, DETAILS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

