USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_COMPLIANCE_CHECKLIST ( CHECK_ID STRING PRIMARY KEY, TENANT_ID STRING, CHECKLIST_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

