USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDENTITY_PROOFING_RUNS ( RUN_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHOD STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31

