USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  PROVIDER_ID STRING,
  METRIC_NAME STRING,
  THRESHOLD VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

