USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_QUEUE_07 ( DELIVERY_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, ATTEMPTS INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'QUEUED', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

