-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_METRICS_07 ( METRIC_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, METRIC_KEY STRING, METRIC_VALUE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

