USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_ATTEMPTS_07 ( ATTEMPT_ID STRING PRIMARY KEY, DELIVERY_ID STRING, ATTEMPT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE VARIANT, SUCCESS BOOLEAN );

