USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANOMALY_DETECTION_PROFILES ( PROFILE_ID STRING PRIMARY KEY, NAME STRING, CONFIG JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

