USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEPRECATION_QUEUE ( Q_ID STRING PRIMARY KEY, FEATURE_NAME STRING, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'SCHEDULED', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

