USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ASYNC_WORKERS_07 ( WORKER_ID STRING PRIMARY KEY, TYPE STRING, PAYLOAD VARIANT, STATUS STRING, SCHEDULED_AT TIMESTAMP_LTZ );

