-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ERRORS_07 ( ERROR_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, BUNDLE_ID STRING, ERROR_TEXT STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

