USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METRIC_ALERT_THRESHOLDS ( THRESHOLD_ID STRING PRIMARY KEY, METRIC_NAME STRING, THRESHOLD JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

