USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METRIC_ALERT_EVENTS ( EVENT_ID STRING PRIMARY KEY, THRESHOLD_ID STRING, METRIC_PAYLOAD VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

