-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_BACKOFF_07 ( BACKOFF_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, NEXT_RETRY_AT TIMESTAMP_LTZ, ATTEMPTS INT, LAST_ERROR VARIANT );

