USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_TELEMETRY_07 ( TELE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, EVENT_NAME STRING, METADATA VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

