USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_ISSUES_REGISTRY ( ISSUE_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY CLOB, STATUS STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

