USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VALIDATION_RULES_07 ( RULE_ID STRING PRIMARY KEY, NAME STRING, EXPRESSION STRING, ERROR_MSG STRING, ENABLED BOOLEAN DEFAULT TRUE );

