USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_ISSUE_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ISSUE_ID STRING, ACTION JSON, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

