USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VALIDATION_VIOLATIONS_07 ( VIOLATION_ID STRING PRIMARY KEY, RULE_ID STRING, DOCUMENT_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

