USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_STATUS (
  STATUS_ID STRING PRIMARY KEY,
  AGENT_ID STRING,
  HOST STRING,
  STATUS STRING,
  LAST_HEARTBEAT TIMESTAMP_LTZ,
  META VARIANT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

