USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_TASK_QUEUE (
  TASK_ID STRING PRIMARY KEY,
  AGENT_ID STRING,
  TASK_TYPE STRING,
  PAYLOAD VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

