USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_TEMPLATES_07 ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, CONTENT CLOB, VERSION INT, ACTIVE BOOLEAN DEFAULT TRUE );

