USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_JOBS (
  JOB_ID STRING PRIMARY KEY,
  SOURCE_REF STRING,
  STATUS STRING DEFAULT 'PENDING',
  BATCH_SIZE INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

