USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_RECORDS_07 ( RECORD_ID STRING PRIMARY KEY, USER_REF STRING, TEMPLATE_ID STRING, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), METADATA VARIANT );

