USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HOTFIX_REGISTRY ( HOTFIX_ID STRING PRIMARY KEY, DESCRIPTION CLOB, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), APPLIED_BY STRING ); @31

