USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_ROLLOUTS ( ROLLOUT_ID STRING PRIMARY KEY, FEATURE_KEY STRING, TENANT_SCOPE VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @31

