USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_COMPACTION_JOBS (
  JOB_ID STRING PRIMARY KEY,
  TARGET_INDEX STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  META VARIANT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

