USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_SHARD_MANIFEST (
  SHARD_ID STRING PRIMARY KEY,
  INDEX_REF STRING,
  LOCATION STRING,
  CHECKSUM STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

