-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVOCATION_INDEX_07 ( CERT_SN STRING PRIMARY KEY, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ );

