USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_SHARD_LOADS (
  LOAD_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  FINISHED_AT TIMESTAMP_LTZ,
  ERROR_JSON VARIANT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

