USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVER_ASSIGNMENTS_07 ( ASSIGN_ID STRING PRIMARY KEY, QUEUE_ID STRING, TARGET_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

