USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_QUERY_AUDIT (
  Q_ID STRING PRIMARY KEY,
  QUERY_TEXT STRING,
  INDEX_REF STRING,
  RESPONSE_SIZE INT,
  LAT_MS NUMBER,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

