USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_REGISTRY (
  INDEX_ID STRING PRIMARY KEY,
  NAME STRING,
  SHARD_COUNT INT,
  LATEST_SNAPSHOT STRING,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

