USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_DERIVED_METRICS ( METRIC_ID STRING PRIMARY KEY, NAME STRING, VALUE NUMBER, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

