-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HASH_RECONCILIATIONS_07 ( RECON_ID STRING PRIMARY KEY, HASH_ID STRING, STATUS STRING, DETAILS VARIANT, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

