USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_HEALTH (
  HEALTH_ID STRING PRIMARY KEY,
  INDEX_ID STRING,
  SHARD_ID STRING,
  STATUS STRING,
  LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

