USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_TEMPLATES_07 ( TEMPLATE_ID STRING PRIMARY KEY, SUBJECT STRING, BODY CLOB, FROM_ADDR STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

