USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_ALERT_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITION VARIANT, SEVERITY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

