USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_VARIANT_REGISTRY (
  VARIANT_ID STRING PRIMARY KEY,
  CLAUSE_ID STRING,
  BODY CLOB,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

