-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_RECONCILIATIONS_07 ( RECON_ID STRING PRIMARY KEY, TX_ID STRING, STATUS STRING, DETAILS VARIANT, COMPLETED_AT TIMESTAMP_LTZ );

