USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_INHERITANCE_MAP (
  MAP_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  PARENT_TEMPLATE_ID STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

