USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATION_QUEUE (
  Q_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  SCHEDULED_AT TIMESTAMP_LTZ,
  STATUS STRING DEFAULT 'SCHEDULED',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

