USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_QUEUE_07 ( SMS_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RECIPIENT STRING, CONTEXT VARIANT, STATUS STRING DEFAULT 'QUEUED', SCHEDULED_AT TIMESTAMP_LTZ );

