USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_QUEUE_BACKLOG (
  BACKLOG_ID STRING PRIMARY KEY,
  Q_ID STRING,
  PRIORITY INT DEFAULT 0,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

