USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REFILENAME: sql/ddl/4324_signature_sms_deliveries_07.sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_DELIVERIES_07 ( DELIVERY_ID STRING PRIMARY KEY, SMS_ID STRING, STATUS STRING, RESPONSE VARIANT, DELIVERED_AT TIMESTAMP_LTZ );

