-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VERSIONS_07 ( VERSION_ID STRING PRIMARY KEY, POLICY_ID STRING, VERSION_NUMBER INT, DEFINITION VARIANT, ACTIVATED_AT TIMESTAMP_LTZ );

