USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_LOCK_HISTORY_07 ( HISTORY_ID STRING PRIMARY KEY, LOCK_ID STRING, ACTION STRING, ACTED_BY STRING, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

