USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_ERROR_INDEX (
  ERR_ID STRING PRIMARY KEY,
  HISTORY_ID STRING,
  ERROR_JSON VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

