USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_STATS (
  STATS_ID STRING PRIMARY KEY,
  ENDPOINT STRING,
  SUCCESS_COUNT INT,
  FAILURE_COUNT INT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

