-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_REQUESTS_07 ( REQ_ID STRING PRIMARY KEY, POLICY_ID STRING, REQUESTED_BY STRING, STATUS STRING, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

