USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKPRESSURE_SIGNALS_07 ( SIGNAL_ID STRING PRIMARY KEY, SOURCE STRING, LEVEL STRING, DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

