USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_QUEUE (
  RETRY_ID STRING PRIMARY KEY,
  ORIGINAL_EVENT JSON,
  ATTEMPT INT DEFAULT 0,
  NEXT_ATTEMPT_AT TIMESTAMP_LTZ,
  STATUS STRING DEFAULT 'PENDING'
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

