USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_ENDPOINT_REGISTRY (
  ENDPOINT_ID STRING PRIMARY KEY,
  NAME STRING,
  URL STRING,
  METHOD STRING,
  AUTH JSON,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

