-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_AUDIT_TRAIL_07 ( AUDIT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION STRING, PAYLOAD VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

