USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_DELIVERY_LOGS (
  LOG_ID STRING PRIMARY KEY,
  ENDPOINT_ID STRING,
  PAYLOAD VARIANT,
  STATUS STRING,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESPONSE_CODE INT
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

