USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_SESSION_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  USER_REF STRING,
  METRICS VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

