USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_SECURITY_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  EVENT_TYPE STRING,
  DETAILS VARIANT,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

