USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTITENANT_AUDIT_INDEX (
  IDX_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  AUDIT_JSON VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

