USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUBSCRIPTIONS_07 ( SUB_ID STRING PRIMARY KEY, NAME STRING, CONDITION VARIANT, CHANNELS ARRAY, ENABLED BOOLEAN DEFAULT TRUE );

