USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_QUOTA_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  QUOTA_REF STRING,
  MESSAGE CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

