-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACTIONS_07 ( ACTION_ID STRING PRIMARY KEY, ADMIN_ID STRING, ACTION STRING, TARGET_REF STRING, NOTES STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

