USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_ACTIONS (
  ACTION_ID STRING PRIMARY KEY,
  RUN_ID STRING,
  STEP_INDEX INT,
  ACTION_JSON VARIANT,
  STATUS STRING,
  EXECUTED_AT TIMESTAMP_LTZ
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

