-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_ADMIN_AUDIT_SUMMARY_07 AS SELECT ACTION_ID, ADMIN_ID, ACTION, TARGET_REF, ACTION_AT FROM DOCGEN.ADMIN_ACTIONS_07 ORDER BY ACTION_AT DESC;

