USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_EVENTS_07 ( EVENT_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, FIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

