USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_USAGE_ANOMALIES (
  ANOMALY_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  METRIC_JSON VARIANT,
  DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  STATUS STRING
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

