USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_ANOMALY_RUNS (
  RUN_ID STRING PRIMARY KEY,
  PROFILE_ID STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

