USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_EVENTS_07 ( EVENT_ID STRING PRIMARY KEY, CASE_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

