USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SUPPORT_TICKET_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  TICKET_ID STRING,
  EVENT_JSON VARIANT,
  EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

