USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SUPPORT_SLA_VIOLATIONS (
  VIOLATION_ID STRING PRIMARY KEY,
  TICKET_ID STRING,
  SLA_REF STRING,
  DETAILS VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign DDL patterns. @31 @24

