-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ROLE_ASSIGNMENTS_07 ( ASSIGN_ID STRING PRIMARY KEY, ADMIN_ID STRING, ROLE_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

