-- Generated per Snowflake E-Signature patterns @31 @36
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDIT_USES_07 ( USE_ID STRING PRIMARY KEY, CREDIT_ID STRING, BUNDLE_ID STRING, AMOUNT_USED NUMBER, USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

