USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_INDEX_VERSIONING ( VERSION_ID STRING PRIMARY KEY, INDEX_NAME STRING, VERSION_NUMBER INT, SNAPSHOT_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

