USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESIGN_AUDIT_INDEX_08 ( INDEX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, AUDIT_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

