USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POSTMORTEM_RUNS_07 ( RUN_ID STRING PRIMARY KEY, INCIDENT_ID STRING, TEMPLATE_ID STRING, OUTPUT VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

