USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_POLICIES ( POLICY_ID STRING PRIMARY KEY, SCOPE VARIANT, RETENTION_DAYS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

