USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAG_ANALYTICS_07 ( ANALYTIC_ID STRING PRIMARY KEY, TAG STRING, METRICS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

