USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_ASSESSMENTS_08 ( RISK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RISK_SCORE FLOAT, DETAILS VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

