USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_INTEGRATION_EVENTS ( EVENT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, INTEGRATION_NAME STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

