USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_FEEDBACK (
  FB_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  CONTEXT VARIANT,
  RATING INT,
  COMMENTS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

