USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_CHAIN_INDEX ( CERT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHAIN JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

