USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CHECK_HISTORY ( CHECK_ID STRING PRIMARY KEY, CERT_ID STRING, OCSP_RESPONSE VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

