USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KYC_DOCUMENTS_08 ( DOC_ID STRING PRIMARY KEY, SIGNER_ID STRING, TYPE STRING, STORAGE_REF STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

