USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KYC_VERIFICATIONS_08 ( VERIF_ID STRING PRIMARY KEY, DOC_ID STRING, RESULT VARIANT, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

