USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_DRIFT_ALERTS_07 ( ALERT_ID STRING PRIMARY KEY, INDEX_ID STRING, METRICS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

