USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_HASH_INDEX ( HASH_ID STRING PRIMARY KEY, BUNDLE_ID STRING, HASH STRING, FIRST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

