USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, ARCHIVE_REF STRING, BUNDLE_ID STRING, ACTION STRING, TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

