USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DRIFT_EVENTS_07 ( EVENT_ID STRING PRIMARY KEY, MODEL_ID STRING, METRICS VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

