USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LOCKS_08 ( LOCK_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCKED_BY STRING, LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

