USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_REGISTRY_VERSIONS_07 ( VER_ID STRING PRIMARY KEY, MODEL_ID STRING, VERSION INT, ARTIFACT VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

