USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LOCK_RELEASES_08 ( RELEASE_ID STRING PRIMARY KEY, LOCK_ID STRING, RELEASED_BY STRING, RELEASED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

