USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_APPROVALS_07 ( APPROVAL_ID STRING PRIMARY KEY, VER_ID STRING, APPROVER STRING, STATUS STRING, APPROVED_AT TIMESTAMP_LTZ );

