USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_COSTING_07 ( COST_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, COST_BREAKDOWN VARIANT );

