USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_BREACHES_07 ( BREACH_ID STRING PRIMARY KEY, ORG_ID STRING, QUOTA_KEY STRING, USAGE VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

