USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUALITY_SCORES_08 ( SCORE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE FLOAT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

