USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETIREMENTS_08 ( RETIRE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RETIRED_BY STRING, RETIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

