USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIVITY_LOG (
  ACT_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ACTION STRING,
  CONTEXT VARIANT,
  AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

