USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_COMPLIANCE_07 ( SLO_ID STRING PRIMARY KEY, SLO_NAME STRING, METRICS VARIANT, WINDOW VARIANT, COMPLIANT BOOLEAN, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

