USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LIFECYCLE_08 ( LIFECYCLE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STATE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

