USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS_07 ( WINDOW_ID STRING PRIMARY KEY, NAME STRING, CRON_EXPR STRING, DURATION_MINS INT, ENABLED BOOLEAN DEFAULT TRUE );

