USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATIONS_08 ( ANNOT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ANNOTATOR STRING, ANNOTATION CLOB, ANNOTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

