USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_POLICY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION STRING, PERFORMED_BY STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

