USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_ROLLOUTS_07 ( ROLLOUT_ID STRING PRIMARY KEY, FEATURE_ID STRING, STRATEGY VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

