USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPENDENCY_MAP ( MAP_ID STRING PRIMARY KEY, SERVICE_ID STRING, DEPENDS_ON ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

