USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_SERVICE_IMPACT ( IMPACT_ID STRING PRIMARY KEY, INCIDENT_ID STRING, SERVICE_ID STRING, IMPACT_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

