USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVISION_REVIEW_LOGS_08 ( LOG_ID STRING PRIMARY KEY, REV_ID STRING, REVIEWER STRING, COMMENT CLOB, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

