USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEP_GRAPH_08 ( EDGE_ID STRING PRIMARY KEY, PARENT_TEMPLATE STRING, CHILD_TEMPLATE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

