USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RECOMMENDATIONS_08 ( REC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RECOMMENDED_FOR VARIANT, SCORE FLOAT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

