USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINTS_REGISTRY ( COMPLAINT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, DETAILS CLOB, STATUS STRING, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

