USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_CONFIG_ENTRIES_08 ( ENTRY_ID STRING PRIMARY KEY, CONFIG_KEY STRING, CONFIG_VAL VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

