USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_AUDIT_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, REQUESTOR STRING, PURPOSE STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DURATION_SECONDS INT );

