USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BREACH_RESPONSE_ACTIONS ( ACTION_ID STRING PRIMARY KEY, NOTIF_ID STRING, ACTION JSON, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

