USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEAD_LETTER_08 ( DLQ_ID STRING PRIMARY KEY, ORIGIN STRING, PAYLOAD VARIANT, ERROR TEXT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

