USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_TRANSFER_LOGS ( LOG_ID STRING PRIMARY KEY, TRANSFER_ID STRING, ENTRY JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

