USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DISPATCH_LOG (
  DISPATCH_ID STRING PRIMARY KEY,
  ALERT_ID STRING,
  CHANNEL STRING,
  STATUS STRING,
  DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

