USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_RESPONSE_LOGS ( LOG_ID STRING PRIMARY KEY, OPERATOR_REF STRING, INCIDENT_ID STRING, ACTION_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

