USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TELEMETRY_SAMPLES ( SAMPLE_ID STRING PRIMARY KEY, FEATURE_NAME STRING, METRICS VARIANT, SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

