USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_PERMISSIONS (
  PERM_ID STRING PRIMARY KEY,
  ROLE STRING,
  RESOURCE STRING,
  ACTIONS ARRAY,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

