USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVOPS_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, TITLE STRING, DESCRIPTION CLOB, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

