USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVOPS_DEPLOY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, DEPLOY_REF STRING, USER_REF STRING, DETAILS VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

