USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SNOWFLAKE_USAGE_COSTS ( RECORD_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, COST_CENTER STRING, COST NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

