USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_RECOVERY_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, RUN_ID STRING, ALLOCATION_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

