USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUESTS_08 ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REQUEST_TYPE STRING, STATUS STRING, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

