USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_LEDGER_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, RUN_ID STRING, SNAPSHOT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

