USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_LEDGER_SNAPSHOT_INDEX ( IDX_ID STRING PRIMARY KEY, SNAP_ID STRING, ACCOUNT_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

