USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EVIDENCE_RETENTION ( RETAIN_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RETENTION_EXPIRES_AT TIMESTAMP_LTZ, NOTIFIED BOOLEAN DEFAULT FALSE );

