USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PSEUDONYMIZATION_JOBS_08 ( JOB_ID STRING PRIMARY KEY, TARGET_TABLE STRING, STATUS STRING, SCHEDULED_AT TIMESTAMP_LTZ );

