USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, HOLD_ID STRING, LEVEL STRING, MESSAGE CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

