USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_IMPACT_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, REVIEWER STRING, RESULT VARIANT, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

