USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PROVENANCE_QUERIES ( QUERY_ID STRING PRIMARY KEY, PROV_ID STRING, QUERY_JSON VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

