USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, DESCRIPTION STRING );

