USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_SWAP_REQUESTS ( REQ_ID STRING PRIMARY KEY, ROTA_ID STRING, FROM_OP STRING, TO_OP STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

