USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DISCOVERY_INDEX ( SERVICE_ID STRING PRIMARY KEY, METADATA VARIANT, DISCOVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

