USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_EVIDENCES_09 (
  EVIDENCE_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  VERIFIER STRING,
  RESULT STRING,
  DETAIL VARIANT,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

