-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_CLASSIFICATION_09 ( CLASS_ID STRING PRIMARY KEY, NAME STRING, SENSITIVITY_LEVEL STRING, RULES VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

