USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTARY_RECORDS_09 (
  NOTARY_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  NOTARY_NAME STRING,
  CERT_REF STRING,
  SIGNED_AT TIMESTAMP_LTZ,
  META VARIANT
);

