USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_RECORDS_09 (
  ANCHOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ANCHOR_TYPE STRING,
  ANCHOR_REF STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

