-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_MASKS_09 ( MASK_ID STRING PRIMARY KEY, FIELD_NAME STRING, MASK_EXPRESSION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

