USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_HEARTBEAT_HISTORY ( HB_ID STRING PRIMARY KEY, AGENT_ID STRING, STATUS STRING, HEARTBEAT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

