USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHORS_09 (
  TX_ID STRING PRIMARY KEY,
  ANCHOR_ID STRING,
  BLOCKCHAIN STRING,
  TX_REF STRING,
  CONFIRMED_AT TIMESTAMP_LTZ
);

