USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_CONFIG_VERSIONS ( VERSION_ID STRING PRIMARY KEY, AGENT_ID STRING, CONFIG VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

