-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_POLICIES_09 ( POLICY_ID STRING PRIMARY KEY, NAME STRING, TARGET_TABLE STRING, RETENTION_DAYS INT, ACTION VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

