USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_EXCEPTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, POLICY_ID STRING, REQUESTOR STRING, REASON CLOB, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

