USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_CONTROLS_09 (
  CONTROL_ID STRING PRIMARY KEY,
  RESOURCE_REF STRING,
  PRINCIPAL STRING,
  PERMISSIONS VARIANT,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

