USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_TOKEN_CACHE ( TOKEN_ID STRING PRIMARY KEY, INTEGRATION_ID STRING, TOKEN_JSON VARIANT, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

