USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_AUDIT_09 (
  AUDIT_ID STRING PRIMARY KEY,
  RESOURCE_REF STRING,
  PRINCIPAL STRING,
  ACTION STRING,
  DETAIL VARIANT,
  ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

