USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ROTATION_JOBS_09 (
  JOB_ID STRING PRIMARY KEY,
  KEY_REF STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

