-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ACCESS_REQUESTS_09 ( REQ_ID STRING PRIMARY KEY, REQUESTOR STRING, BUNDLE_ID STRING, PURPOSE STRING, STATUS STRING, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

