USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_STORE_09 (
  CERT_ID STRING PRIMARY KEY,
  KEY_REF STRING,
  PEM CLOB,
  IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

