USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_REVOCATIONS_09 (
  REVOC_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  REASON STRING
);

