USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAG_USAGE_STATS ( STATS_ID STRING PRIMARY KEY, TAG STRING, USAGE_COUNT INT, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

