USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_WORKFLOW ( WF_ID STRING PRIMARY KEY, REQ_ID STRING, STEPS VARIANT, CURRENT_STEP STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

