USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_REGISTRY ( CONSENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_JSON VARIANT, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

