USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REDACTION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REDACTION_JSON VARIANT, PERFORMED_BY STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

