USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENFORCEMENTS_09 (
  ENFORCE_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  RESULT VARIANT,
  ENFORCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

