USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_FLAGS_09 (
  FLAG_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  FLAG_KEY STRING,
  FLAG_VALUE VARIANT,
  SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

