USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PSEUDONYMIZATION_JOBS ( JOB_ID STRING PRIMARY KEY, SCOPE VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); -- @36

