USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_DISCOVERY_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

