USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PROFILE_VERSIONS ( VERSION_ID STRING PRIMARY KEY, PROFILE_ID STRING, VERSION_NUMBER INT, SETTINGS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

