USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_JOBS_09 (
  JOB_ID STRING PRIMARY KEY,
  SCOPE VARIANT,
  STATUS STRING,
  OUTPUT_REF STRING,
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

