-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKUP_MANIFESTS_09 ( MANIFEST_ID STRING PRIMARY KEY, DESCRIPTION STRING, STORAGE_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

