USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_RISK_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, PARTY_REF STRING, SCORE NUMBER, DETAILS VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

