USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATIONS_09 (
  NOTIF_ID STRING PRIMARY KEY,
  TITLE STRING,
  BODY VARIANT,
  LEVEL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

