USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_AUDIT_FINDINGS ( FINDING_ID STRING PRIMARY KEY, RUN_ID STRING, SEVERITY STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

