USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ALERT_ROUTES_09 (
  ROUTE_ID STRING PRIMARY KEY,
  NAME STRING,
  CHANNELS ARRAY,
  CRITERIA VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE
);

