USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_INCIDENT_REPORTS ( INCIDENT_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, DESCRIPTION CLOB, SEVERITY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

