USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_VERSION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CONTRACT_ID STRING, VERSION_NUMBER INT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @36

