-- Generated per Snowflake E-Signature patterns. @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_MAINTENANCE_09 ( MAINT_ID STRING PRIMARY KEY, DESCRIPTION STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

