USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_DASHBOARD_VIEWS_09 (
  VIEW_ID STRING PRIMARY KEY,
  NAME STRING,
  DEFINITION VARIANT,
  OWNER STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

