USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_LIMIT_EVENTS ( EVENT_ID STRING PRIMARY KEY, PROFILE_ID STRING, SUBJECT_REF STRING, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

