USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_DASHBOARD_METRICS_09 (
  METRIC_ID STRING PRIMARY KEY,
  VIEW_ID STRING,
  METRIC_DEF VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

