USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_HEARTBEAT_09 (
  HB_ID STRING PRIMARY KEY,
  COMPONENT STRING,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

