USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CONFIG_CHANGES_09 (
  CHANGE_ID STRING PRIMARY KEY,
  CONFIG_KEY STRING,
  OLD_VAL VARIANT,
  NEW_VAL VARIANT,
  CHANGED_BY STRING,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

