USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_EXPORTS_09 (
  EXPORT_ID STRING PRIMARY KEY,
  SCOPE VARIANT,
  OUT_REF STRING,
  REQUESTED_BY STRING,
  STATUS STRING,
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

