USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_DELIVERY_STATS ( STATS_ID STRING PRIMARY KEY, PROVIDER STRING, SUCCESS INT, FAIL INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

