USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_PROVIDER_CONFIGS_10 (
  CONFIG_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  CONFIG VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

