USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PENDING_ACTIONS_10 (
  ACTION_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  ACTION_TYPE STRING,
  PAYLOAD VARIANT,
  DUE_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

