USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PAYMENT_RECONCILIATIONS ( RECON_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RUN_ID STRING, STATUS STRING, COMPLETED_AT TIMESTAMP_LTZ ); -- @36

