USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_DELIVERY_QUEUE_10 (
  QUEUE_ID STRING PRIMARY KEY,
  RECIPIENT STRING,
  SUBJECT STRING,
  BODY VARIANT,
  CHANNEL STRING,
  STATUS STRING DEFAULT 'QUEUED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

