USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESELLER_ACCOUNT_MAPPING ( MAP_ID STRING PRIMARY KEY, RESELLER_REF STRING, ACCOUNT_ID STRING, MAPPED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @36

