USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SMS_DELIVERY_QUEUE_10 (
  QUEUE_ID STRING PRIMARY KEY,
  MSISDN STRING,
  MESSAGE STRING,
  STATUS STRING DEFAULT 'QUEUED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

