USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PUSH_NOTIFICATIONS_10 (
  NOTIF_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  PAYLOAD VARIANT,
  STATUS STRING DEFAULT 'QUEUED',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

