USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_HANDLERS_10 (
  HANDLER_ID STRING PRIMARY KEY,
  SOURCE STRING,
  ENDPOINT STRING,
  METHOD STRING,
  ENABLED BOOLEAN DEFAULT TRUE,
  CONFIG VARIANT
);

