USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_EVENT_INDEX ( IDX_ID STRING PRIMARY KEY, EVENT_REF STRING, PARTNER_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

