USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_HEATMAP ( HM_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, USAGE_COUNT NUMBER, LAST_USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

