USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CALLBACK_LOGS_10 (
  LOG_ID STRING PRIMARY KEY,
  ENDPOINT_ID STRING,
  PAYLOAD VARIANT,
  RESPONSE VARIANT,
  STATUS STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

