USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_VARIANT_REGISTRY ( VAR_ID STRING PRIMARY KEY, CLAUSE_ID STRING, VARIANT_BODY CLOB, LOCALE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

