USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_RULES_10 (
  RULE_ID STRING PRIMARY KEY,
  NAME STRING,
  SCOPE VARIANT,
  LIMIT_CONFIG VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

