USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNING_SEQUENCE ( SEQ_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STEP_NUMBER INT, SIGNER_REF STRING, REQUIRED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

