USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_EVENTS_10 (
  EVENT_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  KEY STRING,
  ACTION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

