USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_DEVICE_REGISTRY ( DEVICE_ID STRING PRIMARY KEY, SIGNER_REF STRING, DEVICE_META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

