USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_AUDIT_LOGS_10 (
  LOG_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  ACTION STRING,
  PAYLOAD VARIANT,
  LOG_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

