USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_RULE_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, RULE_ID STRING, BUNDLE_ID STRING, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

