USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_QA_FEEDBACK ( FEEDBACK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, USER_REF STRING, FEEDBACK CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

