USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OFFLINE_VERIFICATIONS_10 (
  VERIF_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  METHOD STRING,
  RESULT STRING,
  DETAILS VARIANT,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

