USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VALIDATION_RULES_10 (
  RULE_ID STRING PRIMARY KEY,
  NAME STRING,
  TARGET STRING,
  EXPRESSION STRING,
  ENABLED BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

