USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_EVENTS_10 (
  ALERT_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  PAYLOAD VARIANT,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

