USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCR_TEXT_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PAGE_NUMBER INT, OCR_TEXT CLOB, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

