USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_QUERY_TELEMETRY ( TELE_ID STRING PRIMARY KEY, TENANT_ID STRING, QUERY_TEXT STRING, RESULT_COUNT INT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

