USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_UPDATES_10 (
  UPDATE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  UPDATE_TEXT STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

