USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAVED_SEARCH_CATALOG ( SEARCH_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, QUERY JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

