USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POSTMORTEMS_10 (
  PM_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  SUMMARY CLOB,
  ACTIONS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

