USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_ACCESS_CONTROLS ( CONTROL_ID STRING PRIMARY KEY, REPORT_ID STRING, RULE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

