USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_BREACH_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TENANT_ID STRING, SLA_NAME STRING, DETAILS VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

