USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_INCIDENTS_10 (
  SLA_INC_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  SLA_METRIC STRING,
  METRIC_VALUE VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

