USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_BREACH_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, NOTIF_ID STRING, RESOLVED BOOLEAN DEFAULT FALSE, RESOLVED_AT TIMESTAMP_LTZ );

