USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_AUDITS_10 (
  AUDIT_ID STRING PRIMARY KEY,
  NAME STRING,
  SCHEDULE STRING,
  LAST_RUN_AT TIMESTAMP_LTZ,
  ENABLED BOOLEAN DEFAULT TRUE
);

