USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ESCALATION_EVENTS ( EVENT_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_ID STRING, EVENT_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

