USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_TICKET_REGISTRY ( TICKET_ID STRING PRIMARY KEY, TENANT_ID STRING, SUBJECT STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

