USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RUN_HISTORY_10 (
  RUN_ID STRING PRIMARY KEY,
  AUDIT_ID STRING,
  STATUS STRING,
  RESULT VARIANT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

