USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_AUDITS_10 (
  CONSENT_AUDIT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CONSENT_TEXT STRING,
  CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

