USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SATISFACTION_SURVEYS ( SURVEY_ID STRING PRIMARY KEY, OPERATOR_REF STRING, SCORE NUMBER, COMMENTS CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

