USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_FEEDBACK_REGISTRY ( FEEDBACK_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, COMMENTS CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

