USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRICS_INDEX_11 (
  BIOMETRIC_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  TYPE STRING,
  HASH STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

