USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_SCORES_11 (
  RISK_ID STRING PRIMARY KEY,
  SUBJECT_ID STRING,
  SCOPE STRING,
  SCORE NUMBER,
  METADATA VARIANT,
  SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

