USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_ALERTS_11 (
  ALERT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  BUNDLE_ID STRING,
  ALERT_TYPE STRING,
  DETAILS VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

