USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAYBOOK_METRICS_ARCHIVE (
  ARCH_ID STRING PRIMARY KEY,
  PB_ID STRING,
  METRICS VARIANT,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

