USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_EVENTS_11 (
  EVENT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  BUNDLE_ID STRING,
  EVENT_TYPE STRING,
  PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

