USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_USAGE_BREAKDOWN ( BREAK_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, USAGE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

