USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_RESTRICTIONS_11 (
  RESTR_ID STRING PRIMARY KEY,
  NAME STRING,
  COUNTRIES ARRAY,
  ACTION STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

