USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_QUOTA_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, QUOTA_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

