USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_EVENTS_11 (
  GEO_EVENT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  COUNTRY STRING,
  ACTION STRING,
  DETAILS VARIANT,
  EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

