USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_PREVIEW_CACHE ( CACHE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PREVIEW_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

