USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_MASKS_11 (
  MASK_ID STRING PRIMARY KEY,
  NAME STRING,
  TARGET_FIELD STRING,
  MASKING_RULE STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

