USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MANUAL_BILLING_ADJUSTMENTS ( ADJ_ID STRING PRIMARY KEY, INVOICE_REF STRING, ADJ_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

