USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_GATEWAY_TRANSACTIONS ( TX_ID STRING PRIMARY KEY, GW_ID STRING, INVOICE_REF STRING, STATUS STRING, tx_payload VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

