USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DASHBOARD_11 (
  DASH_ID STRING PRIMARY KEY,
  NAME STRING,
  DEFINITION VARIANT,
  OWNER STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

