USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PIPELINE_RUNS (
  RUN_ID STRING PRIMARY KEY,
  CFG_ID STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ,
  LOG VARIANT
);
-- Generated per Snowflake E-Sign patterns @31 @24 @56

