USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MANIFEST_REGISTRY_11 (
  MANIFEST_ID STRING PRIMARY KEY,
  NAME STRING,
  CONTENT VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

