USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_VERSIONS_11 (
  VERSION_ID STRING PRIMARY KEY,
  NAME STRING,
  CHANGELOG VARIANT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

