USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_CHANGE_REGISTRY ( CHANGE_ID STRING PRIMARY KEY, REGION STRING, CHANGE_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

