USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_POLICY_VIOLATION_INDEX ( IDX_ID STRING PRIMARY KEY, AUDIT_ID STRING, POLICY_ID STRING, VIOLATION_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

