USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_CHANGE_REQUESTS_11 (
  REQUEST_ID STRING PRIMARY KEY,
  REQUESTOR STRING,
  REQUEST VARIANT,
  STATUS STRING,
  SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

