USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_WORKFLOWS_11 (
  WF_ID STRING PRIMARY KEY,
  NAME STRING,
  STEPS VARIANT,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

