USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_INSTANCES_11 (
  INSTANCE_ID STRING PRIMARY KEY,
  WF_ID STRING,
  TARGET_REF STRING,
  STATUS STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

