USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_ALERTS ( ALERT_ID STRING PRIMARY KEY, FEED_ID STRING, TARGET_REF STRING, ALERT_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

