USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INDEX_12 (
  DOC_INDEX_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  DOCUMENT_TEXT CLOB,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

