USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_TOKENS_12 (
  TOKEN_ID STRING PRIMARY KEY,
  DOC_INDEX_ID STRING,
  TOKEN STRING,
  POSITION NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

