USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_FAILURE_ALERTS ( ALERT_ID STRING PRIMARY KEY, RENDERER_ID STRING, JOB_ID STRING, ERROR_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

