USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_SNAPSHOT_MANIFEST_11 ( MANIFEST_ID STRING PRIMARY KEY, S3_PREFIX STRING, SHARD_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

