USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, SLA_NAME STRING, HEALTH_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

