USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_BUILD_JOBS_12 (
  JOB_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);

