USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_FALLBACK_ROUTES_11 ( ROUTE_ID STRING PRIMARY KEY, NAME STRING, PRIMARY_METHOD STRING, FALLBACK_METHODS ARRAY, ENABLED BOOLEAN DEFAULT TRUE );

