USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_SERVICE_REGISTRY_12 (
  SERVICE_ID STRING PRIMARY KEY,
  HOST STRING,
  PORT NUMBER,
  HEALTH_VAR VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

