USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QUALITY_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REVIEWER STRING, SCORE NUMBER, COMMENTS CLOB, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
