USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_METRICS_11 ( METRIC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, USAGE_COUNT NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

