USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_HEALTH_12 (
  CHECK_ID STRING PRIMARY KEY,
  SERVICE_ID STRING,
  STATUS STRING,
  LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

