USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PROFILE_COMPATIBILITY ( COMP_ID STRING PRIMARY KEY, PROFILE_ID STRING, PLATFORM STRING, COMPAT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
