USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RECOMMENDATIONS_11 ( RECO_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TEMPLATE_ID STRING, SCORE NUMBER, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

