USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_RECONCILIATIONS_12 (
  RECON_ID STRING PRIMARY KEY,
  SHARD_ID STRING,
  STATUS STRING,
  DISCREPANCIES VARIANT,
  RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

