USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_CAPACITY_HISTORY ( HIST_ID STRING PRIMARY KEY, RENDERER_ID STRING, CAPACITY_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

