USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIMILARITY_SCORES_11 ( SCORE_ID STRING PRIMARY KEY, DOC_A STRING, DOC_B STRING, SCORE NUMBER, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

