USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, RISK_SCORE NUMBER, CALCULATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
