USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BEHAVIOR_PROFILES_11 ( PROFILE_ID STRING PRIMARY KEY, SIGNER_ID STRING, BEHAVIOR_METRICS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

