USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_RESTORE_REQUESTS_12 (
  REQ_ID STRING PRIMARY KEY,
  BACKUP_ID STRING,
  STATUS STRING,
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

