USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BEHAVIOR_ALERTS_11 ( ALERT_ID STRING PRIMARY KEY, PROFILE_ID STRING, ALERT_TYPE STRING, DETAILS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

