USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BOT_INTERACTION_LOGS ( LOG_ID STRING PRIMARY KEY, BOT_ID STRING, SESSION_ID STRING, MESSAGE_IN VARIANT, MESSAGE_OUT VARIANT, INTERACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
