USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_NODE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, NODE_REF STRING, JOB_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

