USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_RISK_EVALS_11 ( EVAL_ID STRING PRIMARY KEY, SIGNER_ID STRING, CONFIG_ID STRING, SCORE NUMBER, DETAIL VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

