USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_ROUTES_12 (
  ROUTE_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  TENANT_ID STRING,
  PRIORITY NUMBER,
  CONFIG VARIANT
);

