USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONVERSATION_TRANSCRIPT_STORE ( TRANS_ID STRING PRIMARY KEY, SESSION_ID STRING, TRANSCRIPT CLOB, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
