USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONVERSATION_FEEDBACK_LOGS ( FB_ID STRING PRIMARY KEY, TRANS_ID STRING, USER_REF STRING, FEEDBACK CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
