USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_ROUTING_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RULE_ID STRING, INVOCATION JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
