USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_QUOTA_ENFORCEMENTS ( ENF_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, MODEL_ID STRING, STATUS STRING, ENFORCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
