USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_RETRAIN_JOBS ( JOB_ID STRING PRIMARY KEY, MODEL_ID STRING, TRIGGER_REASON STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); -- @1
