USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESPONSE_PROVENANCE_STORE ( PROV_ID STRING PRIMARY KEY, REQ_ID STRING, PROVENANCE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
