USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_PREVIEW_AUDIT_11 ( AUDIT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, INV_PREVIEW VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
