USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_EXPORTS_11 ( EXPORT_ID STRING PRIMARY KEY, INVOICE_ID STRING, LOCATION STRING, EXPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
