USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_NODE_UPTIME ( UPTIME_ID STRING PRIMARY KEY, NODE_REF STRING, UPTIME_SECONDS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

