USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_LOAD_BALANCER_REGISTRY ( REG_ID STRING PRIMARY KEY, AGENT_ID STRING, BACKENDS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
