USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PURGE_AUDIT_11 ( PURGE_ID STRING PRIMARY KEY, TARGET_TABLE STRING, ROWS_PURGED NUMBER, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
