USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_RELEASE_NOTES ( NOTE_ID STRING PRIMARY KEY, AGENT_ID STRING, VERSION STRING, NOTES CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
