USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_DEPLOYMENT_RUNS ( RUN_ID STRING PRIMARY KEY, AGENT_ID STRING, VERSION STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); -- @1
