USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CONTRACT_REGISTRY ( CONTRACT_ID STRING PRIMARY KEY, NAME STRING, SPEC CLOB, VERSION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
