USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HOLD_EXEMPTIONS_11 ( EXEMPT_ID STRING PRIMARY KEY, HOLD_ID STRING, REASON STRING, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
