USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_VERSION_COMPAT_INDEX ( IDX_ID STRING PRIMARY KEY, CONTRACT_ID STRING, VERSION STRING, COMPAT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
