USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_DEPRECATION_NOTICES ( NOTICE_ID STRING PRIMARY KEY, CONTRACT_ID STRING, VERSION STRING, MESSAGE CLOB, ANNOUNCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
