USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DSAR_RESPONSES_11 ( RESPONSE_ID STRING PRIMARY KEY, REQ_ID STRING, RESPONDER STRING, RESPONSE_PAYLOAD VARIANT, RESPONDED_AT TIMESTAMP_LTZ
);
