USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_TASKS_11 ( TASK_ID STRING PRIMARY KEY, TARGET STRING, SCHEDULE STRING, LAST_RUN TIMESTAMP_LTZ, ENABLED BOOLEAN DEFAULT TRUE
);
