USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKOFF_RETRY_HISTORY ( HISTORY_ID STRING PRIMARY KEY, POLICY_ID STRING, EVENT_REF STRING, ATTEMPT INT, LAST_ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); -- @1
