USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BULK_OPERATION_PROGRESS ( PROG_ID STRING PRIMARY KEY, JOB_ID STRING, PCT_COMPLETE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
