USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COURT_ORDERS_11 ( ORDER_ID STRING PRIMARY KEY, TARGET STRING, ORDER_DOC CLOB, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING
);
