USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_QUALITY_ALARMS ( ALARM_ID STRING PRIMARY KEY, CHECK_ID STRING, TARGET_REF STRING, ALARM_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
