USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEMA_MIGRATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MIGRATION_ID STRING, APPLIED_BY STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @1
