USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_LEVEL_REPORTS ( RPT_ID STRING PRIMARY KEY, TENANT_ID STRING, SLA_NAME STRING, RPT_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1
