USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_DEPLOY_ERRORS ( ERR_ID STRING PRIMARY KEY, DEPLOY_ID STRING, ERROR_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

