USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AML_CHECKS_11 ( AML_ID STRING PRIMARY KEY, SUBJECT_REF STRING, RESULT VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
