USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOFENCING_RULES_11 ( RULE_ID STRING PRIMARY KEY, NAME STRING, POLYGON VARIANT, ACTION STRING, ENABLED BOOLEAN DEFAULT TRUE
);
