USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.APPROVAL_AUDIT ( AUDIT_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
