USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_NOTIFICATION_CHANNELS_11 ( CHANNEL_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHANNEL_TYPE STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE
);
