USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_CONFIG ( CONFIG_ID STRING PRIMARY KEY, PROVIDER_GROUP STRING, CONFIG_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
