USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TOGGLE_AUDIT_11 ( AUDIT_ID STRING PRIMARY KEY, FEATURE_KEY STRING, ACCOUNT_ID STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
