USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_SNAPSHOT ( SNAP_ID STRING PRIMARY KEY, PROVIDER_REF STRING, STATUS JSON, TAKEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
