USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DIFF_INDEX ( DIFF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, BASE_VERSION STRING, DIFF_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
