USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, HOLD_ID STRING, SUBJECT_REF STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
