USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_CONSENTS_12 ( CONSENT_ID STRING PRIMARY KEY, SIGNER_ID STRING, BUNDLE_ID STRING, CONSENT_TEXT STRING, CONSENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

