USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_EVENTS_12 (
  TELE_ID STRING PRIMARY KEY,
  TYPE STRING,
  CONTEXT VARIANT,
  EMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

