USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_VENDOR_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, PROVIDER_REF STRING, CONTACT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
