USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECKS_12 (
  CHECK_ID STRING PRIMARY KEY,
  COMPONENT STRING,
  STATUS STRING,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

