USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_ESCALATION_REGISTRY ( ESC_ID STRING PRIMARY KEY, CASE_REF STRING, POLICY_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
