USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PROFILE_HISTORY ( HIST_ID STRING PRIMARY KEY, PROFILE_ID STRING, ENTITY_REF STRING, CHANGE_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

