USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_QUEUE_12 ( QUEUE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TEMPLATE_ID STRING, PRIORITY NUMBER DEFAULT 50, STATUS STRING, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

