USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSES_12 (
  RESPONSE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  ACTIONS VARIANT,
  RESOLVED_AT TIMESTAMP_LTZ
);

