USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_SLA_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, CASE_REF STRING, SLA_ID STRING, DETAILS VARIANT, VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
