USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_LOGS_12 (
  LOG_ID STRING PRIMARY KEY,
  ENTITY_NAME STRING,
  ENTITY_ID STRING,
  CHANGES VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

