USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_QUEUE_12 ( NOTIF_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHANNEL STRING, PAYLOAD VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

