USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATIONS_12 (
  NOTIF_ID STRING PRIMARY KEY,
  TITLE STRING,
  BODY STRING,
  LEVEL STRING,
  TARGET_ROLE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

