USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_RETIREMENT_REGISTRY ( RETIRE_ID STRING PRIMARY KEY, FEATURE_NAME STRING, RETIRE_AT TIMESTAMP_LTZ, REASON CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
