USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DISPATCH_LOG_12 ( LOG_ID STRING PRIMARY KEY, NOTIF_ID STRING, CHANNEL STRING, STATUS STRING, RESPONSE VARIANT, DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

