USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_TEMPLATES_12 ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, SUBJECT STRING, BODY CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

