USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIONS_12 (
  ACTION_ID STRING PRIMARY KEY,
  EXEC_ID STRING,
  OPERATOR STRING,
  STEP STRING,
  RESULT VARIANT,
  ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

