USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS_12 (
  WINDOW_ID STRING PRIMARY KEY,
  START_AT TIMESTAMP_LTZ,
  END_AT TIMESTAMP_LTZ,
  DESCRIPTION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

