USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PUSH_TEMPLATES_12 ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, PAYLOAD VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

