USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNC_ERROR_DLQ ( DLQ_ID STRING PRIMARY KEY, INTEGRATION_REF STRING, RECORD_REF STRING, ERROR_JSON VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
