USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BACKUP_SCHEDULES_12 (
  SCHEDULE_ID STRING PRIMARY KEY,
  TARGET STRING,
  CRON_EXPR STRING,
  LAST_RUN TIMESTAMP_LTZ,
  ENABLED BOOLEAN DEFAULT TRUE
);

