USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_PRIORITY_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, CASE_REF STRING, RULE_ID STRING, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
