USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_SLA_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, CASE_REF STRING, SLA_ID STRING, MESSAGE STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
