USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_TICKET_UPDATES_12 ( UPDATE_ID STRING PRIMARY KEY, TICKET_ID STRING, NOTE STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

