USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_USAGE_12 (
  USAGE_ID STRING PRIMARY KEY,
  QUOTA_ID STRING,
  USAGE_AMOUNT NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

