USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_TASK_RUNS ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

