USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_ALERTS_12 ( ALERT_ID STRING PRIMARY KEY, SLA_ID STRING, METRIC STRING, VALUE VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

