USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_ALERTS_12 (
  ALERT_ID STRING PRIMARY KEY,
  QUOTA_ID STRING,
  THRESHOLD NUMBER,
  CURRENT_USAGE NUMBER,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

