USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACCESS_LOGS_12 (
  LOG_ID STRING PRIMARY KEY,
  ADMIN_USER STRING,
  ACTION STRING,
  TARGET STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

