USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_KEY_ROTATION_HISTORY ( ROT_ID STRING PRIMARY KEY, KEY_ID STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

