USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_HISTORY_12 (
  NH_ID STRING PRIMARY KEY,
  PREF_ID STRING,
  CHANNEL STRING,
  PAYLOAD VARIANT,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

