USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_REGISTRY ( KEY_ID STRING PRIMARY KEY, KEY_REF STRING, META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

