USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_TASKS_12 (
  TASK_ID STRING PRIMARY KEY,
  NAME STRING,
  COMMAND STRING,
  SCHEDULE STRING,
  ENABLED BOOLEAN DEFAULT TRUE
);

