USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_CERTIFICATE_BINDING ( BIND_ID STRING PRIMARY KEY, SIGNER_REF STRING, CERT_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

