USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_TOKENS_12 (
  TOKEN_ID STRING PRIMARY KEY,
  SUBJECT STRING,
  SCOPE STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

