USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TOKENS_12 (
  SESS_TOKEN_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  TOKEN_ID STRING,
  ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ
);

