USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_PACKET_STORE ( PACKET_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PACKET_JSON VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

