USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PACKET_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, PACKET_ID STRING, SUBJECT_REF STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

