USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_QUEUE_13 (
  QUEUE_ID STRING PRIMARY KEY,
  REQ_ID STRING,
  STATUS STRING,
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

