USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ANNOUNCEMENTS_12 (
  ANN_ID STRING PRIMARY KEY,
  TITLE STRING,
  BODY STRING,
  PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  AUTHOR STRING
);

