USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_INDEX_13 (
  PROV_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  PROV_HASH STRING,
  ANCHOR_TXID STRING,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

