USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEEDBACK_12 (
  FB_ID STRING PRIMARY KEY,
  ANN_ID STRING,
  USER STRING,
  FEEDBACK TEXT,
  SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

