USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_PUBLISH_JOBS_13 (
  JOB_ID STRING PRIMARY KEY,
  PROV_ID STRING,
  STATUS STRING,
  PUBLISHED_AT TIMESTAMP_LTZ
);

