USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VALIDATION_DISCREPANCY_LOGS ( LOG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, DISCREPANCY_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

