USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICIES_12 (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  SCOPE VARIANT,
  RULES VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

