USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_AUDIT_12 (
  AUDIT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  CHANGED_BY STRING,
  CHANGES VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

