USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_REPORTS_12 (
  REPORT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  SUMMARY VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

