USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_BLOCK_USAGE_13 (
  USAGE_ID STRING PRIMARY KEY,
  BLOCK_ID STRING,
  DOCUMENT_ID STRING,
  USED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

