USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UI_CONFIG_13 (
  CONFIG_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  CONFIG VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

