USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PIA_ASSESSMENTS_12 (
  PIA_ID STRING PRIMARY KEY,
  NAME STRING,
  SCOPE VARIANT,
  FINDINGS VARIANT,
  COMPLETED_AT TIMESTAMP_LTZ
);

