USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UI_THEMES_13 (
  THEME_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  THEME VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

