USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RED_TEAM_FINDINGS_12 (
  FINDING_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  DETAILS VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

