USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_JOBS_12 (
  JOB_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  CONFIG VARIANT,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  FINISHED_AT TIMESTAMP_LTZ
);

