USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DEPLOYMENTS_12 (
  DEPLOY_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  ENV STRING,
  VERSION STRING,
  DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

