USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_USAGE_ALERTS_12 (
  ALERT_ID STRING PRIMARY KEY,
  FEATURE_KEY STRING,
  ACCOUNT_ID STRING,
  METRIC VARIANT,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

