USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_SLOWNESS_12 (
  INCIDENT_ID STRING PRIMARY KEY,
  SERVICE_ID STRING,
  LATENCY_MS NUMBER,
  SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

