USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_POLICIES_13 (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  RULES VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE
);

