USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ROTATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, KEY_REF STRING, MESSAGE STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

