USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIVITY_SESSIONS ( SESSION_ID STRING PRIMARY KEY, OPERATOR_REF STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, META VARIANT );

