USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_INVESTIGATIONS_13 (
  INVEST_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  BUNDLE_ID STRING,
  STATUS STRING,
  DETAILS VARIANT,
  OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

