USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_ACCESS_POLICIES_12 (
  POLICY_ID STRING PRIMARY KEY,
  NAME STRING,
  CONDITIONS VARIANT,
  ENABLED BOOLEAN DEFAULT TRUE
);

