USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_CASE_UPDATES_13 (
  UPDATE_ID STRING PRIMARY KEY,
  INVEST_ID STRING,
  NOTE STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

