USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_POLICY_ASSIGNMENTS_13 (
  ASSIGN_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

