USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SSO_PROVIDER_REGISTRY ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

