USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXCEPTIONS_13 (
  EX_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  GRANTED_BY STRING,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

