USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ASSIGNMENTS_12 (
  ASSIGN_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ROLE_ID STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

