USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SESSIONS_12 (
  SESSION_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ
);

