USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_AUDIT_TRAIL_13 (
  AUDIT_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  ACTION STRING,
  PERFORMED_BY STRING,
  DETAILS VARIANT,
  PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

