USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_FLAGS_13 (
  FLAG_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  FLAG_TYPE STRING,
  SET_BY STRING,
  SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

