USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AUDIT_TRAIL_12 (
  AUDIT_ID STRING PRIMARY KEY,
  OPERATOR STRING,
  ACTION STRING,
  TARGET STRING,
  DETAILS VARIANT,
  ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

