USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_OVERRIDE_REQUESTS ( REQ_ID STRING PRIMARY KEY, CLIENT_ID STRING, REQUESTED_LIMIT JSON, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

