USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TEMPLATE_LOCKS ( LOCK_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCKED_BY STRING, LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); -- @31 @24 @56

