USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SENSITIVITY_13 (
  SENS_ID STRING PRIMARY KEY,
  FIELD_REF STRING,
  LEVEL STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

