USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TAG_INDEX ( TAG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TAG_KEY STRING, TAG_VALUE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

