USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_OWNER_CONTACTS_12 (
  CONTACT_ID STRING PRIMARY KEY,
  FEATURE_KEY STRING,
  OWNER STRING,
  CONTACT_INFO VARIANT
);

