USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_OWNER_ESCALATIONS_12 (
  ESC_ID STRING PRIMARY KEY,
  CONTACT_ID STRING,
  ISSUE_REF STRING,
  ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

