USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SNAPSHOTS_12 (
  SNAP_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  SNAPSHOT_REF STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

