USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_OPERATOR_NOTES_13 ( NOTE_ID STRING PRIMARY KEY, OPERATOR STRING, CONTEXT VARIANT, NOTE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

