USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SNAPSHOT_REFERENCES_12 (
  REF_ID STRING PRIMARY KEY,
  SNAP_ID STRING,
  REF_TYPE STRING,
  REF_PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

