USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_EXCEPTION_REGISTRY ( EX_ID STRING PRIMARY KEY, NAME STRING, SCOPE VARIANT, APPROVAL_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

