USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_PLAYBOOK_RUNS_13 ( RUN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, STATUS STRING, LOGS VARIANT, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), COMPLETED_AT TIMESTAMP_LTZ );

