USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_SERVICE_INCIDENTS_13 ( INCIDENT_ID STRING PRIMARY KEY, SERVICE STRING, SEVERITY STRING, DESCRIPTION STRING, STATUS STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

