USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, POLICY_ID STRING, ISSUED_TO STRING, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); -- @31 @24 @56

