USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_SERVICE_MAINTENANCES_13 ( MAINT_ID STRING PRIMARY KEY, SERVICE STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, DESCRIPTION STRING );

