USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_PROVIDER_HEALTH_13 ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

