USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_PROVIDER_NOTIFICATIONS_13 ( NOTIF_ID STRING PRIMARY KEY, PROVIDER_ID STRING, TYPE STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

