USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_INTEGRATION_EVENTS_13 ( EVENT_ID STRING PRIMARY KEY, INTEGRATION STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

