USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_WEBHOOK_BACKOFF_13 ( BACKOFF_ID STRING PRIMARY KEY, EVENT_ID STRING, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, BACKOFF_MS NUMBER );

