USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELEGATED_ADMIN_REGISTRY ( ADMIN_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SUBJECT_REF STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

