USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELEGATED_ADMIN_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ADMIN_ID STRING, ACTION_JSON VARIANT, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

