USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_DELIVERY_PROVIDERS_13 ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, TYPE STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE );

