USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_CALLBACK_HISTORY_13 ( CALLBACK_ID STRING PRIMARY KEY, ENDPOINT_ID STRING, PAYLOAD VARIANT, RESPONSE VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

