USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_ACTION_EXECUTION_LOGS_13 ( LOG_ID STRING PRIMARY KEY, ACTION_ID STRING, STATUS STRING, OUTPUT VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

