USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTHOR_REGISTRY ( AUTHOR_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, AUTHOR_REF STRING, ATC_DT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
