USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_API_USAGE_13 ( USAGE_ID STRING PRIMARY KEY, KEY_ID STRING, ENDPOINT STRING, METHOD STRING, RESPONSE_CODE NUMBER, TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

