USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EMBEDDING_CACHE ( CACHE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EMBEDDING VECTOR, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
