USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_RATE_LIMIT_VIOLATIONS_13 ( VIOLATION_ID STRING PRIMARY KEY, KEY_ID STRING, WINDOW_START TIMESTAMP_LTZ, REQUESTS NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

