USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CHANNEL STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); -- @31 @24
