USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ORIGIN_REGISTRY ( ORIGIN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SOURCE STRING, IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
