USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_TELEMETRY ( TELE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RENDER_MS NUMBER, RENDERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); -- @31 @24
