USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_POLICY_INSTANCES_13 ( INSTANCE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGET_REF STRING, ACTIVE BOOLEAN DEFAULT TRUE, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

