USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PROFILE_USAGE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, PROFILE_ID STRING, LIMIT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
