USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIG_ANALYTICS_EVENTS_13 ( EVENT_ID STRING PRIMARY KEY, NAME STRING, METADATA VARIANT, EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

