USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_GATE_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, RULE_ID STRING, TEMPLATE_ID STRING, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
