USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_POSITIONS ( POS_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNER_REF STRING, PAGE_NUMBER INT, COORDS VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
