USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS_14 (
  SESSION_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  BUNDLE_ID STRING,
  IP_ADDRESS STRING,
  USER_AGENT STRING,
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_SEEN_AT TIMESTAMP_LTZ,
  EXPIRES_AT TIMESTAMP_LTZ
);

