USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_AUDIT_MARKERS ( MARKER_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, KEY STRING, VALUE VARIANT, SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
