USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHUNK_STORE ( CHUNK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SEQ INT, TEXT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
