USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINTS_14 (
  FPRINT_ID STRING PRIMARY KEY,
  DEVICE_ID STRING,
  SIGNER_ID STRING,
  FINGERPRINT VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

