USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_QUEUE ( Q_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ACTIVITY VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

