USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IP_WATCHLIST_14 (
  IP_ID STRING PRIMARY KEY,
  IP_ADDR STRING,
  DESCRIPTION STRING,
  RISK_LEVEL STRING,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

