USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_LOOKUP_CACHE_14 (
  GEO_ID STRING PRIMARY KEY,
  IP_ADDR STRING,
  GEO JSON,
  LOOKUP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

