USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_ARCHIVE_14 (
  ARCHIVE_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PAYLOAD VARIANT
);

