USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_LOGS_14 (
  LOG_ID STRING PRIMARY KEY,
  ACTION_ID STRING,
  RESULT VARIANT,
  RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

