USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANNOTATION_SENTIMENT_INDEX ( IDX_ID STRING PRIMARY KEY, ANNOT_ID STRING, SENTIMENT_SCORE NUMBER, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
