USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHARD_MANIFEST_14 (
  SHARD_ID STRING PRIMARY KEY,
  INDEX_NAME STRING,
  SHARD_URI STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

