USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_SNAPSHOT_MANIFEST_14 (
  SNAPSHOT_ID STRING PRIMARY KEY,
  INDEX_NAME STRING,
  S3_PREFIX STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

