USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_LOAD_JOBS_14 (
  JOB_ID STRING PRIMARY KEY,
  SOURCE STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  FINISHED_AT TIMESTAMP_LTZ
);

