USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_COLLABORATION_SESSIONS ( SESSION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, HOST_REF STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
