USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_PARTICIPANT_INDEX ( PID STRING PRIMARY KEY, SESSION_ID STRING, SUBJECT_REF STRING, JOINED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
