USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_ACTIVITY_LOGS ( LOG_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
