USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_LOAD_ERRORS_14 (
  ERROR_ID STRING PRIMARY KEY,
  JOB_ID STRING,
  ERROR_PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

