USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_REQUEST_LOG_14 (
  REQ_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  QUERY VARIANT,
  RESULT_COUNT NUMBER,
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

