USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_TRANSCRIPT_INDEX ( TID STRING PRIMARY KEY, SESSION_ID STRING, TRANSCRIPT_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
