USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_SNAPSHOT_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, SESSION_ID STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
