USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_METADATA_14 (
  INDEX_NAME STRING PRIMARY KEY,
  DESCRIPTION STRING,
  VECTOR_DIM NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

