USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_RECONCILIATIONS_14 (
  RECON_ID STRING PRIMARY KEY,
  INDEX_NAME STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);

