USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_CONFLICTS ( CONFLICT_ID STRING PRIMARY KEY, SESSION_ID STRING, DETAIL VARIANT, RESOLVED BOOLEAN DEFAULT FALSE, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

