USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_RECON_ISSUES_14 (
  ISSUE_ID STRING PRIMARY KEY,
  RECON_ID STRING,
  ITEM_REF STRING,
  ISSUE_DESC STRING,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

