USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_REPORTS ( INCIDENT_ID STRING PRIMARY KEY, OPERATOR_REF STRING, DESCRIPTION CLOB, SEVERITY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24
