USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_REPORTS_14 (
  REPORT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  METRICS VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

