USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUSINESS_HOURS_14 (
  BH_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  TIMEZONE STRING,
  HOURS VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

