USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_ACCESS_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, IP_GEO VARIANT, LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

