USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_POLICY_VIOLATIONS_14 (
  VIOLATION_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  SIGNER_ID STRING,
  LOCATION VARIANT,
  VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

