USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_TRUST_SCORES_14 (
  SCORE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  SCORE NUMBER,
  COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

