USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_INCIDENT_UPDATES_14 (
  UPDATE_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  NOTE STRING,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

