USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REQUESTS (
  REQUEST_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ
);

Core signature request table storing request lifecycle state. @34 @27

