USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNERS (
  SIGNER_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  EMAIL STRING,
  NAME STRING,
  SIGNING_METHOD STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Signer registry per signature request to model multi-signer flows. @34 @28

