USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSIONS (
  SESSION_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  REQUEST_ID STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  CONTEXT VARIANT
);

Signer session storage for ephemeral context and device fingerprints. @34 @28

