USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_IMAGES (
  IMAGE_ID STRING PRIMARY KEY,
  BLOB_REF STRING,
  MIME_TYPE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Stores references to signature image artifacts (for drawn signatures). @34 @28

