USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ESCALATIONS_14 (
  ESC_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  ISSUE_REF STRING,
  ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

