USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_HASHES (
  HASH_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  HASH_VALUE STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Stores provenance hashes for document+signature bundles used in anchoring. @34 @41

