USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_CHAIN (
  PROV_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  PREV_HASH STRING,
  ANCHOR_TXID STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Stores provenance chain entries and optional blockchain anchors. @41 @36

