USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_REVOCATION_INDEX (
  INDEX_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  STATUS STRING,
  LAST_CHECK TIMESTAMP_LTZ,
  DETAILS VARIANT
);

OCSP/CRL revocation index used by verification procedures. @118 @36

