USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_STATUS_CACHE ( CACHE_ID STRING PRIMARY KEY, TX_ID STRING, STATUS STRING, LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

