USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  DOCUMENT_ID STRING,
  SIGNER_ID STRING,
  EVENT_TYPE STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Event table capturing all signature-related events for audit & analytics. @90 @31

