USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_ALERTS_14 (
  ALERT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  TYPE STRING,
  DETAILS VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

