USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICES (
  DEVICE_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  DEVICE_FINGERPRINT VARIANT,
  REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Device registry for device-bound signature telemetry and fraud checks. @92 @31

