USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_EXPLAINABILITY_LOGS_14 (
  LOG_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  INPUT VARIANT,
  EXPLANATION VARIANT,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

