USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ASSEMBLIES (
  ASSEMBLY_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ACCOUNT_ID STRING,
  STATUS STRING,
  METADATA VARIANT,
  RENDERED_URL STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Tracks document assembly runs and their rendered artifacts for preview/sign flows. @86 @31

