USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_BREACH_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, EVENT_ID STRING, CHANNEL STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

