USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_BIAS_REPORTS_14 (
  REPORT_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  METRICS VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

