USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMP_FILES (
  TEMP_ID STRING PRIMARY KEY,
  PATH STRING,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Temporary file staging table for assembly/render pipelines. @88 @31

