USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, SERVICE_NAME STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, META VARIANT ); @31 @24

