USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_REPORTS (
  INCIDENT_ID STRING PRIMARY KEY,
  TITLE STRING,
  DESCRIPTION STRING,
  SEVERITY STRING,
  STATUS STRING DEFAULT 'OPEN',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED_AT TIMESTAMP_LTZ
);

Incident tracking for operator-runbook and compliance investigations. @105 @31

