USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONFIG_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, KEY STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

