USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_PREFERENCES (
  PREF_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  CHANNELS ARRAY,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Tenant notification preferences (email/SMS/webhook) for signer notifications. @114 @31

