USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_INBOUND_LOG (
  LOG_ID STRING PRIMARY KEY,
  SOURCE STRING,
  PAYLOAD VARIANT,
  RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  HANDLED BOOLEAN DEFAULT FALSE
);

Raw webhook ingestion log for provider events before idempotent upsert SP. @116 @31

