USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECKS (
  HEALTH_ID STRING PRIMARY KEY,
  COMPONENT STRING,
  STATUS STRING,
  LAST_RUN TIMESTAMP_LTZ,
  DETAILS VARIANT
);

Health checks for HSM/OCSP/External Function endpoints. @103 @31

