USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VECTOR_STORE (
  VECTOR_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  EMBEDDING VECTOR,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Vector store table for signature embeddings used in FAISS snapshot export. @100 @31

