USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CONSENT_RECORDS (
  CONSENT_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  CONSENT_TEXT CLOB,
  GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  METHOD STRING
);

Consent capture records tied to signers and evidence bundles. @99 @31

