USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_INDEX (
  SEI_ID STRING PRIMARY KEY,
  EVENT_REF STRING,
  EVENT_TYPE STRING,
  SOURCE_SYSTEM STRING,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Index table to accelerate event search and retrieval for audits. @130 @31

