USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_FORECAST_RUNS ( RUN_ID STRING PRIMARY KEY, MODEL_ID STRING, SCOPE VARIANT, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ ); @31 @24

