USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORTING_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  METRIC_NAME STRING,
  METRIC_VALUE VARIANT,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Operational reporting metrics for signature SLAs and throughput. @123 @31

