USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  METRIC_NAME STRING,
  VALUE VARIANT,
  CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Incident telemetry to support audits and RCA. @105 @31

