USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_SLA_BREACH_LOGS ( LOG_ID STRING PRIMARY KEY, TRACK_ID STRING, DETAILS VARIANT, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

