USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_CONTROL_ROLES (
  ROLE_ID STRING PRIMARY KEY,
  NAME STRING,
  DESCRIPTION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

RBAC roles table to complement row access/masking policies for admin console. @36 @31

