USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_GRANTS (
  GRANT_ID STRING PRIMARY KEY,
  ROLE_ID STRING,
  SUBJECT STRING,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Grants audit table to manage per-user/per-service role attachments. @36 @31

