USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOTS (
  SNAPSHOT_ID STRING PRIMARY KEY,
  CREATED_BY STRING,
  MANIFEST VARIANT,
  LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Index snapshot manifest records used by FAISS snapshot loader patterns. @31 @66

