USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_LIBRARY (
  CLAUSE_ID STRING PRIMARY KEY,
  NAME STRING,
  BODY CLOB,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Clause library for reusable clause inserts in assemblies. @338 @31

