USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PREVIEW_CACHE (
  CACHE_ID STRING PRIMARY KEY,
  ASSEMBLY_ID STRING,
  RENDERED_URL STRING,
  EXPIRES_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

Preview cache to speed repeated document previews prior to signing. @86 @31

