USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_METRICS ( MET_ID STRING PRIMARY KEY, LOCATION STRING, METRIC_NAME STRING, METRIC_VALUE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

