USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRY_QUEUE (
  RETRY_ID STRING PRIMARY KEY,
  ORIGINAL_ID STRING,
  REASON STRING,
  NEXT_RUN_AT TIMESTAMP_LTZ,
  ATTEMPTS INT DEFAULT 0,
  PAYLOAD VARIANT
);

Retry queue metadata for failed webhook/notification deliveries and DLQ patterns. @36 @31

