USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_SIGNATURE_AUDIT_SUMMARY AS
SELECT
  ACCOUNT_ID,
  COUNT(*) AS TOTAL_SIGNATURES,
  SUM(CASE WHEN RESULT='SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
  CURRENT_TIMESTAMP() AS SNAPSHOT_AT
FROM DOCGEN.SIGNATURE_VERIFICATIONS
GROUP BY ACCOUNT_ID;

A materialized view to summarize verification counts per account for dashboards. @170 @31

