USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_SIGNATURE_METRICS AS
SELECT
  v.METRIC_ID, v.TENANT_ID, v.METRIC_NAME, v.METRIC_VALUE, v.GENERATED_AT
FROM DOCGEN.REPORTING_METRICS v;

Reporting view to expose metrics to admin consoles and dashboards. @30 @31

