USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RECONCILIATION ( REC_ID STRING PRIMARY KEY, MANIFEST_ID STRING, EXPECTED_COUNT INT, ACTUAL_COUNT INT, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

