CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_MANIFEST (MANIFEST_ID STRING PRIMARY KEY, S3_PATH STRING, ROW_COUNT NUMBER, EXPORT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RECONCILIATION (RECON_ID STRING PRIMARY KEY, MANIFEST_ID STRING, STATUS STRING, DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());

Manifest and reconciliation tables implement the evidence export/reconcile pattern noted in your evidence runbooks @23 @25. @23 @25

