USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_VIOLATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, VIOL_ID STRING, ACTION_JSON VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

