USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ACTIVITY_AGGREGATES ( AGG_ID STRING PRIMARY KEY, USER_REF STRING, AGG_JSON VARIANT, AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

