```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_LOG (
  LOG_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  ACTION STRING,
  DETAILS VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

