```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  SLA_ID STRING,
  DESCRIPTION STRING,
  SEVERITY STRING,
  FIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

