```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_LOOKUPS (
  GEO_ID STRING PRIMARY KEY,
  IP_ADDRESS STRING,
  GEO_DATA VARIANT,
  LOOKED_UP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

