```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IP_BLACKLIST (
  IP_ID STRING PRIMARY KEY,
  IP_ADDRESS STRING,
  REASON STRING,
  BLOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

