```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUARANTINE_STORE (
  Q_ID STRING PRIMARY KEY,
  BUNDLE_ID STRING,
  REASON STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

