USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FLAG_ID STRING, OLD_VAL VARIANT, NEW_VAL VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

