```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_HANDLERS (
  HANDLER_ID STRING PRIMARY KEY,
  ALERT_NAME STRING,
  HANDLER_TYPE STRING,
  CONFIG VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

