```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_AUDIT_INDEX (
  SAI_ID STRING PRIMARY KEY,
  SIGNATURE_ID STRING,
  BUNDLE_ID STRING,
  SIGNER_ID STRING,
  AUDIT_HASH STRING,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

