USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_REPORTS ( REPORT_ID STRING PRIMARY KEY, NAME STRING, CRON JSON, LAST_RUN_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

