```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_LINKS (
  PL_ID STRING PRIMARY KEY,
  PARENT_REF STRING,
  CHILD_REF STRING,
  RELATION_TYPE STRING,
  LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

