```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_INDEX (
  PI_ID STRING PRIMARY KEY,
  REF STRING,
  METADATA VARIANT,
  INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
```

