USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_EXPORT_JOBS ( JOB_ID STRING PRIMARY KEY, RUN_ID STRING, STATUS STRING, LOCATION STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

