```sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_RUNS (
  RUN_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  PARAMETERS VARIANT,
  STATUS STRING DEFAULT 'QUEUED',
  OUTPUT_LOCATION STRING,
  STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ
);
```

