USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VERSION_HISTORY ( VER_ID STRING PRIMARY KEY, POLICY_ID STRING, VERSION_NUMBER INT, BODY VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

