USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PRIVILEGE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, USER_REF STRING, REVIEW_JSON VARIANT, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

