USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ONCALL_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, INCIDENT_ID STRING, LEVEL INT, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

