USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_WEBHOOKS ( WEBHOOK_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, PAYLOAD_SCHEMA VARIANT, LAST_RECEIVED_AT TIMESTAMP_LTZ, ACTIVE BOOLEAN DEFAULT TRUE ); @31

