USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRY_POLICIES ( POLICY_ID STRING PRIMARY KEY, NAME STRING, BACKOFF_CONFIG VARIANT, MAX_ATTEMPTS INT DEFAULT 5, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

