USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DLQ ( DLQ_ID STRING PRIMARY KEY, SOURCE_TABLE STRING, PAYLOAD VARIANT, ERROR_DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

