USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, CHANNEL STRING, SUBJECT STRING, BODY CLOB, LOCALE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

