USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_HISTORY ( NH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGET STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ, RESPONSE VARIANT ); @31

