USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINTS ( FP_ID STRING PRIMARY KEY, DEVICE_ID STRING, FINGERPRINT_HASH STRING, FIRST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_SEEN TIMESTAMP_LTZ ); @31

