USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_EVENTS ( GEO_ID STRING PRIMARY KEY, SIGNER_ID STRING, LATITUDE NUMBER, LONGITUDE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

