USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BROWSER_SIGNALS ( SIGNAL_ID STRING PRIMARY KEY, SESSION_ID STRING, USER_AGENT STRING, SIGNALS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

