USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_METRICS ( METRIC_ID STRING PRIMARY KEY, JOB_ID STRING, DURATION_MS NUMBER, WORKER_ID STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

