USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_INDEX ( PDF_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PAGE_COUNT INT, TEXT_EXTRACT VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

