USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEXT_EXTRACTIONS ( EXTRACTION_ID STRING PRIMARY KEY, PDF_ID STRING, EXTRACTED_TEXT CLOB, LANGUAGE STRING, EXTRACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

