USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_TELEMETRY ( QT_ID STRING PRIMARY KEY, USER_REF STRING, QUERY_TEXT STRING, LATENCY_MS NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

