USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_AUDIT ( QA_ID STRING PRIMARY KEY, USER_REF STRING, QUERY_TEXT STRING, RESULT_SUMMARY VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

