USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_FLAGS ( FLAG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, FLAG_KEY STRING, FLAG_VALUE STRING, SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

