USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_TOKENS ( AT_ID STRING PRIMARY KEY, SUBJECT STRING, TOKEN_HASH STRING, EXPIRES_AT TIMESTAMP_LTZ, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

