USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_AUDIT ( AUDIT_ID STRING PRIMARY KEY, OPERATION STRING, PAYLOAD VARIANT, RESULT VARIANT, TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

