USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_RESPONSES ( RESP_ID STRING PRIMARY KEY, REQ_ID STRING, RESPONSE_PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

