USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_OPERATIONAL_NOTES ( NOTE_ID STRING PRIMARY KEY, CONTEXT VARIANT, NOTE CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

