USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_REQUESTS ( ANCHOR_REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PROVIDER_ID STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

