USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_EXPORT_ARTIFACTS ( ARTIFACT_ID STRING PRIMARY KEY, REQ_ID STRING, BUNDLE_ID STRING, URI STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

