USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SUBJECT_REF STRING, REQUEST_TYPE STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

