USE DATABASE AI_FEATURE_HUB;

USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.PRIVACY_ACTIONS (
    ACTION_ID STRING PRIMARY KEY,
    REQ_ID STRING,
    ACTION_TYPE STRING,
    EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT
);

-- @31