USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_PERMISSIONS ( PERM_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ACTION STRING, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

