USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECRET_ROTATION_LOG ( ROT_ID STRING PRIMARY KEY, SECRET_REF STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ROTATED_BY STRING, DETAILS VARIANT ); @31

