USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ESCALATION_LOG ( ESC_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ESCALATED_BY STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES STRING ); @31

