USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_INTEGRITY ( INTEGRITY_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHECKSUM STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

