USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_RUNBOOK_REVISIONS ( REV_ID STRING PRIMARY KEY, RUNBOOK_ID STRING, REV_NOTE STRING, REVISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

