USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBJECT_DATA_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, REQ_ID STRING, LOCATION STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

