USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COURT_ORDERS ( ORDER_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ORDER_JSON VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), COMPLIED BOOLEAN DEFAULT FALSE ); @31

