USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COURT_ORDER_ACTIONS ( ACTION_ID STRING PRIMARY KEY, ORDER_ID STRING, ACTION_TAKEN STRING, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT ); @31

