USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_RESPONSE_TIMES ( RECORD_ID STRING PRIMARY KEY, INCIDENT_ID STRING, RESPONSE_SECONDS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

