USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLACK_INTEGRATION_LOG ( LOG_ID STRING PRIMARY KEY, CHANNEL STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE VARIANT ); @31

