USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_INTEGRATION_LOG ( LOG_ID STRING PRIMARY KEY, RECIPIENT STRING, SUBJECT STRING, BODY CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESPONSE VARIANT ); @31

