USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, NAME STRING, CHANNELS VARIANT, ONCALL BOOLEAN DEFAULT FALSE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

