USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_INCIDENT_INDEX ( SII_ID STRING PRIMARY KEY, SERVICE_NAME STRING, INCIDENT_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

