USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_TEMPLATES_INDEX ( PTIDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, NAME STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

