USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATIONS ( DEP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPRECATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REPLACEMENT_TEMPLATE STRING ); @31

