USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_PLAYBOOK_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, PB_ID STRING, ASSIGNED_TO STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

