USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_PLAYBOOK_HISTORY ( HIST_ID STRING PRIMARY KEY, PB_ID STRING, RUN_ID STRING, ACTIONS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

