USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_LIMIT_LOG ( LOG_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

