USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_LOCATION_HISTORY ( HIST_ID STRING PRIMARY KEY, DEVICE_ID STRING, LAT NUMBER, LNG NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

