USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_SCORES ( SCORE_ID STRING PRIMARY KEY, SIGNER_ID STRING, SCORE NUMBER, MODEL_ID STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

