USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHN_LOGS ( AUTHN_ID STRING PRIMARY KEY, SUBJECT STRING, METHOD STRING, RESULT STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

