USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHZ_LOGS ( AUTHZ_ID STRING PRIMARY KEY, SUBJECT STRING, RESOURCE STRING, DECISION STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

