USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAML_ASSERTIONS ( ASSERTION_ID STRING PRIMARY KEY, SUBJECT STRING, ASSERTION_XML CLOB, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

