USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IP_WHITELIST ( ENTRY_ID STRING PRIMARY KEY, NETWORK_CIDR STRING, DESCRIPTION STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

