USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EFFECTIVE_POLICIES ( EFFECT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, POLICY_JSON VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

