USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_TENANT_AUDIT_SUMMARY AS SELECT TENANT_ID, COUNT(*) AS AUDIT_EVENTS, MAX(AUDIT_TS) AS LAST_AUDIT FROM DOCGEN.ADMIN_AUDIT GROUP BY TENANT_ID; @31

