USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_TENANT_COMPLIANCE_OVERVIEW AS SELECT TENANT_ID, COUNT(DISTINCT BUNDLE_ID) AS BUNDLES, SUM(CASE WHEN FINALIZED='true' THEN 1 ELSE 0 END) AS FINALIZED FROM DOCGEN.SIGNATURE_EVIDENCE_BUNDLES GROUP BY TENANT_ID; @31

