USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_LOGS ( LOG_ID STRING PRIMARY KEY, WF_ID STRING, STEP_NAME STRING, STATUS STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

