USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRANSFORMER_REGISTRY ( TRANSFORMER_ID STRING PRIMARY KEY, NAME STRING, LANGUAGE STRING, ENTRYPOINT STRING, CONFIG VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

