USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_RETRIES ( RETRY_ID STRING PRIMARY KEY, EVENT_ID STRING, ATTEMPT INT DEFAULT 0, LAST_ATTEMPT_AT TIMESTAMP_LTZ, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, STATUS STRING
);
-- @31 @24

