USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPLAY_REQUESTS ( REPLAY_ID STRING PRIMARY KEY, REQUESTOR STRING, START_TS TIMESTAMP_LTZ, END_TS TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

