USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INGEST_METRICS ( METRIC_ID STRING PRIMARY KEY, PIPE_NAME STRING, RECORDS_INGESTED NUMBER, INGEST_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

