USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_BACKOFF ( BACKOFF_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, NEXT_RETRY_AT TIMESTAMP_LTZ, CURRENT_DELAY_MS NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

