USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_FEEDBACK_LOOP ( LOOP_ID STRING PRIMARY KEY, SOURCE STRING, FEEDBACK_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

