USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.METRICS_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, METRIC_NAME STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, VALUE VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

