USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SECRETS_META ( SECRET_META_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, SECRET_REF STRING, ROTATED_AT TIMESTAMP_LTZ, META VARIANT
);
-- @31 @24

