USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_BACKFILL_LOG ( BACKFILL_ID STRING PRIMARY KEY, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, STATUS STRING, DETAILS VARIANT
);
-- @31 @24

