USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_STATUS ( PROVIDER_ID STRING PRIMARY KEY, NAME STRING, LAST_PING TIMESTAMP_LTZ, STATUS STRING, DETAILS VARIANT );

