USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_TRANSFORM_RUNS ( RUN_ID STRING PRIMARY KEY, TRANSFORM_ID STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, STATUS STRING, METRICS VARIANT
);
-- @31 @24

