USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_THROTTLE_EXCEPTIONS ( EXC_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

