USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_RULES ( RULE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, FALLBACK_PROVIDER STRING, CONDITION VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

