USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_COMPATIBILITY ( COMPAT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, COMPAT_VERSION STRING, NOTES STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

