USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, CLIENT_ID STRING, CONTRACT_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

