USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLIENT_ACTIVITY_SUMMARY ( SUMMARY_ID STRING PRIMARY KEY, CLIENT_ID STRING, ACTIVITY JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

