USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_BACKPRESSURE ( ENTRY_ID STRING PRIMARY KEY, SOURCE STRING, CURRENT_QDEPTH INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

