USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PREVIEW_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, PREVIEW_URL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

