USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EVENT_MAPPINGS ( MAPPING_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, EVENT_TYPE STRING, MAPPED_TO STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

