USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EVENT_LOGS ( PEL_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, EVENT_REF STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

