USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SYNC_LOG ( SYNC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SYNC_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING, DETAILS VARIANT
);
-- @31 @24

