USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INBOUND_RATE_LIMIT ( LIMIT_ID STRING PRIMARY KEY, SOURCE_IP STRING, LIMIT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

