USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_CONSUMER_OFFSETS ( OFFSET_ID STRING PRIMARY KEY, CONSUMER_NAME STRING, LAST_OFFSET STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

