USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_FOLDERS ( FOLDER_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, PARENT_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

