USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RESPONSE_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, PATTERN VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

