USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FOLDER_INDEX ( FIDX_ID STRING PRIMARY KEY, FOLDER_ID STRING, META VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

