USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FOLDER_EMBEDDINGS ( EMB_ID STRING PRIMARY KEY, FOLDER_ID STRING, BUNDLE_ID STRING, EMBEDDING VECTOR, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

