USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_LATENCY_PROFILES ( PROFILE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, LATENCY_BUCKETS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

