USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FOLDER_ACTIVITY_LOG ( LOG_ID STRING PRIMARY KEY, FOLDER_ID STRING, ACTION STRING, PERFORMED_BY STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

