USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TLS_CERT_INDEX ( CERT_IDX_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, CERT_FINGERPRINT STRING, EXPIRES_AT TIMESTAMP_LTZ );

