USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FOLDER_RECOMMENDATIONS ( REC_ID STRING PRIMARY KEY, FOLDER_ID STRING, SUGGESTION VARIANT, SCORE NUMBER, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

