USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_AUDIT_INDEX ( PAIDX_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, AUDIT_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

