USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_CONFIDENCE_LOG ( LOG_ID STRING PRIMARY KEY, CLAUSE_ID STRING, SOURCE STRING, CONFIDENCE NUMBER, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

