USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KMS_MAPPINGS ( MAPPING_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, KMS_ARN STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

