USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIM_INDEX_SHARDS ( SHARD_ID STRING PRIMARY KEY, SNAPSHOT_ID STRING, LOCATION STRING, SHARD_META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

