USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_AGREEMENTS ( SLA_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, SLA_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

