USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIM_INDEX_RECONCILE ( RECON_ID STRING PRIMARY KEY, SNAPSHOT_ID STRING, EXPECTED_COUNT INT, ACTUAL_COUNT INT, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

