USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FLAG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FLAG_KEY STRING, PREV_VALUE BOOLEAN, NEW_VALUE BOOLEAN, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

