USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INVOICE_LINKS ( LINK_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, INVOICE_REF STRING, URI STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

