USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_REVIEW_NOTES ( NOTE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, NOTE_TEXT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

