USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RISK_MATRIX ( MATRIX_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, RISK_JSON VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

