USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CHECKLISTS ( CHECKLIST_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ITEMS VARIANT, COMPLETED BOOLEAN DEFAULT FALSE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

