USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONN_HISTORY ( CONN_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING, DETAILS VARIANT );

