USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONN_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT VARIANT );

