USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXEMPTIONS ( EXEMPT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACCOUNT_ID STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GRANTED_BY STRING
);
-- @31 @24

