USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PAYOUTS ( PAYOUT_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, AMOUNT NUMBER, CURRENCY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

