USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SETTLEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

