USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, SCHED_ID STRING, INCIDENT_REF STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31 @24

