USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_EXEMPTIONS ( EX_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );
-- @31 @24

