USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_ADJUSTMENTS ( ADJ_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, ADJUSTMENT VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

