USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_SUBSCRIPTIONS ( SUBS_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, EVENT_TYPE STRING, CALLBACK_URI STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

