USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, THRESHOLD VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

