USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATECARD_VERSIONS ( RCV_ID STRING PRIMARY KEY, RC_ID STRING, VERSION INT, RULES VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

