USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_METRICS_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, METRIC JSON, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

