USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_GEO_RESTRICTIONS ( RESTR_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, REGION STRING, ENFORCED BOOLEAN DEFAULT TRUE );

