USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MIRROR_INDEX ( MIRROR_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, SOURCE_REF STRING, MIRRORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

