USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TEST_HARNESS ( HARNESS_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, TEST_JSON VARIANT, LAST_RUN TIMESTAMP_LTZ );

