USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, NEXT_ROTATION TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

