USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_DEPLOYMENTS ( DEPLOY_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, DEPLOY_JSON VARIANT, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

