USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENTS ( INC_ID STRING PRIMARY KEY, TITLE STRING, DESCRIPTION STRING, SEVERITY STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

