USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, HEALTH_SUMMARY VARIANT, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

