USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_FEEDS ( FEED_ID STRING PRIMARY KEY, NAME STRING, SOURCE_URI STRING, LAST_FETCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

