USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_FEED_EVENTS ( TFE_ID STRING PRIMARY KEY, FEED_ID STRING, EVENT_JSON VARIANT, INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

