USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TEST_MATRIX ( MATRIX_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, TESTS VARIANT, LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

