USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_REGION_STATUS ( RS_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, REGION STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

