USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_URIS ( URI_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, PATH STRING, TYPE STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

