USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_ACTIONS ( TA_ID STRING PRIMARY KEY, SCORE_ID STRING, ACTION STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
-- @31 @24

