USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_API_LOGS ( LOG_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, ENDPOINT STRING, REQUEST VARIANT, RESPONSE VARIANT, TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

