USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_VIOLATIONS ( PV_ID STRING PRIMARY KEY, TENANT_ID STRING, DESCRIPTION STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED BOOLEAN DEFAULT FALSE );
-- @31 @24

