USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_ACTIONS_ADMIN ( PA_ID STRING PRIMARY KEY, VIOLATION_ID STRING, ACTION STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );
-- @31 @24

