USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_PRIVACY_AUDIT AS SELECT PA.*, PV.DESCRIPTION FROM DOCGEN.PRIVACY_ACTIONS_ADMIN PA LEFT JOIN DOCGEN.PRIVACY_VIOLATIONS PV ON PA.VIOLATION_ID = PV.PV_ID;
-- @31 @24

