USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SECURITY_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, SEVERITY STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

