USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER STRING, CONTRACT_JSON VARIANT, SIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

