USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PHASED_MIGRATIONS ( MIG_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, PHASES VARIANT, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

