USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPRECATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, MESSAGE STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

