USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAGS_HISTORY ( HIST_ID STRING PRIMARY KEY, FLAG_ID STRING, OLD_VALUE STRING, NEW_VALUE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

