USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_ROTATION_LOG ( LOG_ID STRING PRIMARY KEY, SCHED_ID STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PERFORMED_BY STRING, DETAILS VARIANT );
-- @31 @24

