USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTESTATION_REPORTS ( REPORT_ID STRING PRIMARY KEY, ATTEST_ID STRING, STATUS STRING, REPORT JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

