USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ACCESS_AUDIT ( KAA_ID STRING PRIMARY KEY, KEY_REF STRING, ACCESSOR STRING, ACCESS_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ACTION STRING );
-- @31 @24

