USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, SLO_ID STRING, PROVIDER_NAME STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

