USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CIRCUIT_BREAKER_STATE ( STATE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, STATE STRING, LAST_CHANGED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

