USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_ITEMS ( ITEM_ID STRING PRIMARY KEY, EXPORT_ID STRING, BUNDLE_ID STRING, STATUS STRING, PROCESSED_AT TIMESTAMP_LTZ );
-- @31 @24

