USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RESOURCE_TAGS ( TAG_ID STRING PRIMARY KEY, RESOURCE_REF STRING, TAG_KEY STRING, TAG_VALUE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

