USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_ERRORS ( ERR_ID STRING PRIMARY KEY, EXPORT_ID STRING, ERROR_DETAIL VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

