USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_REPORTS ( REPORT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REPORT JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24

