USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JOB_SCHEDULE_HISTORY ( HIST_ID STRING PRIMARY KEY, JOB_ID STRING, RUN_AT TIMESTAMP_LTZ, STATUS STRING, DETAILS VARIANT );

