USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUEUE_STATS ( STATS_ID STRING PRIMARY KEY, QUEUE_NAME STRING, DEPTH INT, BACKPRESSURE BOOLEAN, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

