USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PROVIDER_HEALTH AS SELECT PROVIDER_NAME, STATUS, MAX(LAST_CHECK) AS LAST_CHECK FROM DOCGEN.PROVIDER_STATUS GROUP BY PROVIDER_NAME;

