USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PROVIDER_METRICS AS SELECT PROVIDER_NAME, AVG(LATENCY) AS AVG_LATENCY, SUM(ERRORS) AS TOTAL_ERRORS FROM DOCGEN.PROVIDER_API_LOGS GROUP BY PROVIDER_NAME;

