USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_RUN_ACCESS_REVIEWS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 6 * * MON UTC'
AS CALL DOCGEN.RUN_ACCESS_REVIEW();
-- @31 @24

