USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_SCHEDULES ( SCHEDULE_ID STRING PRIMARY KEY, REPORT_NAME STRING, CRON_EXPR STRING, OWNER STRING, LAST_RUN TIMESTAMP_LTZ ); -- @1

