USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_IMPORT_ERRORS ( ERROR_ID STRING PRIMARY KEY, IMPORT_ID STRING, ERROR_DETAIL VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

