USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_HISTORY ( HW_ID STRING PRIMARY KEY, JOB_ID STRING, WORKER STRING, DURATION_MS NUMBER, STATUS STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

