USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ASSEMBLY_LOCK_HISTORY ( LH_ID STRING PRIMARY KEY, LOCK_ID STRING, OBJECT_REF STRING, LOCKED_BY STRING, ACQUIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RELEASED_AT TIMESTAMP_LTZ ); -- @1

