USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_OUTAGE_SCHEDULE ( OUTAGE_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, NOTES STRING ); -- @1

