USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHIFT_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, SHIFT_ID STRING, OPERATOR STRING, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

