USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_FLAG_HISTORY ( FH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FLAG_KEY STRING, PREV_VALUE STRING, NEW_VALUE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

