USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_MIGRATION_ERRORS ( ERR_ID STRING PRIMARY KEY, MIG_ID STRING, TEMPLATE_ID STRING, ERROR_DETAIL VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

