USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, FIELDS_TO_REDACT VARIANT, REQUESTED_BY STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

