USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_JOBS ( JOB_ID STRING PRIMARY KEY, REQ_ID STRING, STATUS STRING, PROGRESS VARIANT, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); -- @1

