USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, POLICY_ID STRING, REASON STRING, OPENED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CLOSED_AT TIMESTAMP_LTZ ); -- @1

