USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_HOLD_REFS ( REF_ID STRING PRIMARY KEY, HOLD_ID STRING, DOCUMENT_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

