USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_HEALTH_METRICS ( MET_ID STRING PRIMARY KEY, MANIFEST_ID STRING, STATUS STRING, LAST_VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @1

