USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_CLAIMS ( CLAIM_ID STRING PRIMARY KEY, JOB_ID STRING, WORKER_ID STRING, CLAIMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); -- @1

