USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_ERRORS ( ERR_ID STRING PRIMARY KEY, JOB_ID STRING, WORKER_ID STRING, ERROR_DETAIL VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

