USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MEDIA_PURGE_LOG ( LOG_ID STRING PRIMARY KEY, MEDIA_ID STRING, PURGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @1

