USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MEDIA_ACCESS_CONTROL ( MAC_ID STRING PRIMARY KEY, MEDIA_ID STRING, SUBJECT_REF STRING, PERMISSIONS VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

