USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_TEXT_INDEX_STATS ( STAT_ID STRING PRIMARY KEY, PDF_ID STRING, TOKEN_COUNT INT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

