USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_INDEX_HEALTH ( SIH_ID STRING PRIMARY KEY, INDEX_REF STRING, STATUS STRING, LAST_REBUILT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @1

