USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_INDEX_REBUILDS ( RB_ID STRING PRIMARY KEY, INDEX_REF STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, STATUS STRING, NOTES VARIANT ); -- @1

