USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_CACHE_STATS ( QCS_ID STRING PRIMARY KEY, CACHE_KEY STRING, HITS NUMBER, MISSES NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

