USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_CACHE_POLICIES ( QP_ID STRING PRIMARY KEY, NAME STRING, TTL_SECONDS INT, MAX_ENTRIES INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

