USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_PREFETCH_JOBS ( PJ_ID STRING PRIMARY KEY, KEY STRING, SCHEDULE_CRON STRING, LAST_RUN TIMESTAMP_LTZ, STATUS STRING ); -- @1

