USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_PREFETCH_HISTORY ( H_ID STRING PRIMARY KEY, PJ_ID STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), OUTPUT_LOCATION STRING, STATUS STRING ); -- @1

