USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_AUDIT_SAMPLE ( SAMPLE_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, RESPONSE_CODE INT, LATENCY_MS NUMBER, SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

