USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_SAMPLES ( SAMPLE_ID STRING PRIMARY KEY, CLIENT_ID STRING, USAGE_METRICS VARIANT, SAMPLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

