USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_GEO_AGG ( AGG_ID STRING PRIMARY KEY, SIGNER_ID STRING, COUNTRY STRING, SESSIONS INT, LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

