USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FP_AGG ( AGG_ID STRING PRIMARY KEY, DEVICE_ID STRING, FIRST_SEEN TIMESTAMP_LTZ, LAST_SEEN TIMESTAMP_LTZ, TOTAL_SESSIONS INT ); -- @1

