USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_METHOD_STATS ( STAT_ID STRING PRIMARY KEY, METHOD STRING, USE_COUNT INT, LAST_USED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

