USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_MANIFEST_HISTORY ( H_ID STRING PRIMARY KEY, MANIFEST_ID STRING, STATUS STRING, PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @1

