USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_VERIFICATION_METRICS ( MET_ID STRING PRIMARY KEY, MANIFEST_ID STRING, VERIFIED_COUNT INT, FAILED_COUNT INT, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

