USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOT_LINKS ( LINK_ID STRING PRIMARY KEY, SNAP_ID STRING, RELATED_AUDIT_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @1

