USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_SLA_DASHBOARD AS SELECT SLO_ID, NAME, (SELECT MAX(RECORDED_AT) FROM DOCGEN.SLO_HISTORY WHERE SLO_ID = SLO_ID) AS LAST_METRIC FROM DOCGEN.SLO_CONFIGS; -- @1

