USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_CAPACITY_UTILIZATION AS SELECT PLAN_ID, AVG((VALUE:usage)::NUMBER) AS AVG_USAGE FROM DOCGEN.CAPACITY_USAGE GROUP BY PLAN_ID; -- @1

