USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_BILLING_TRENDS AS SELECT DATE_TRUNC('DAY', CREATED_AT) AS DAY, SUM(AMOUNT) AS AMOUNT FROM DOCGEN.BILLING_LINE_ITEM GROUP BY DAY ORDER BY DAY DESC; -- @1

