USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_COMPLIANCE_DASHBOARD AS SELECT TENANT_ID, COUNT(DISTINCT BUNDLE_ID) AS BUNDLES, SUM(CASE WHEN ARCHIVED_AT IS NOT NULL THEN 1 ELSE 0 END) AS ARCHIVED FROM DOCGEN.SIGNATURE_EVIDENCE_BUNDLES GROUP BY TENANT_ID; -- @1

