USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_PRIVACY_DASHBOARD AS SELECT TENANT_ID, COUNT(*) AS REQUESTS, SUM(CASE WHEN STATUS='COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED FROM DOCGEN.PRIVACY_REQUESTS GROUP BY TENANT_ID; -- @1

