USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_HEALTH_OVERVIEW AS SELECT COMPONENT, STATUS, MAX(CHECKED_AT) AS LAST_CHECK FROM DOCGEN.HEALTH_CHECKS GROUP BY COMPONENT, STATUS; -- @1

