USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_OPERATOR_RESPONSE_TIMES AS SELECT INCIDENT_ID, AVG(RESPONSE_SECONDS) AS AVG_RESPONSE FROM DOCGEN.OPERATOR_RESPONSE_TIMES GROUP BY INCIDENT_ID; -- @1

