USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_INCIDENT_TRENDS AS SELECT DATE_TRUNC('WEEK', CREATED_AT) AS WEEK, COUNT(*) AS INCIDENTS FROM DOCGEN.INCIDENT_REPORTS GROUP BY WEEK ORDER BY WEEK DESC; -- @1

