USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_MATCH_HISTORY ( MATCH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE NUMBER, DECISION STRING, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

