USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FIRMWARE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, DEVICE_ID STRING, FIRMWARE_VERSION STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

