USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TELEMETRY ( TELE_ID STRING PRIMARY KEY, SESSION_ID STRING, TELEMETRY VARIANT, COLLECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

