USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REALTIME_ALERTS ( ALERT_ID STRING PRIMARY KEY, SOURCE_REF STRING, ALERT_TYPE STRING, SEVERITY STRING, DETAILS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

