USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.U2F_KEY_REGISTRY ( KEY_ID STRING PRIMARY KEY, USER_REF STRING, KEY_META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

