USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MFA_CHALLENGE_LOG ( CH_ID STRING PRIMARY KEY, USER_REF STRING, CHALLENGE_TYPE STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

