USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_SCORE_HISTORY ( H_ID STRING PRIMARY KEY, SCORE_ID STRING, PREV_SCORE NUMBER, NEW_SCORE NUMBER, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

