USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_SCORE_FACTORS ( FACTOR_ID STRING PRIMARY KEY, SCORE_ID STRING, FACTOR_KEY STRING, FACTOR_VALUE VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

