USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPUTATION_SOURCES ( SRC_ID STRING PRIMARY KEY, SIGNER_ID STRING, SOURCE_NAME STRING, PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

