USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_CONSENT_LOG ( CONSENT_LOG_ID STRING PRIMARY KEY, SIGNER_ID STRING, CONSENT_JSON VARIANT, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

