USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_WITHDRAWALS ( WD_ID STRING PRIMARY KEY, CONSENT_LOG_ID STRING, WITHDRAWN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );

