USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_REVOCATIONS ( REV_ID STRING PRIMARY KEY, CONSENT_ID STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REVOKED_BY STRING );

