USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_CONSENT_AUDIT AS SELECT SIGNER_ID, COUNT(*) AS CONSENTS FROM DOCGEN.SIGNER_CONSENT_LOG GROUP BY SIGNER_ID;

