USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESS_METRICS ( M_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, VIEWS INT, LAST_VIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

