USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CLONE_HISTORY ( CH_ID STRING PRIMARY KEY, REQ_ID STRING, ORIGINAL_DOC STRING, NEW_DOC STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

