USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TEMPLATE_MAPPINGS ( MAP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TEMPLATE_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

