USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CHANGE_REQUESTS ( CR_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REQUESTOR STRING, CHANGE_JSON VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

