USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_APPROVAL_LOGS ( LOG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, APPROVAL_STATUS STRING, APPROVED_BY STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

