USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ISSUES ( ISSUE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ISSUE_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

