USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LINKED_RESOURCES ( LR_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RESOURCE_REF STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

