USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_THUMBNAILS ( THUMB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, IMAGE_PATH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

