USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_CHUNK_STATS ( STAT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHUNK_COUNT INT, AVG_DIM INT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

