USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_VERSION_MAP ( MAP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION INT, SNAPSHOT_ID STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

