USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIM_MODEL_STATS ( STAT_ID STRING PRIMARY KEY, MODEL_ID STRING, QPS NUMBER, LATENCY_MS NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

