USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIM_MODEL_VERSIONS ( MV_ID STRING PRIMARY KEY, MODEL_ID STRING, VERSION STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

