USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIM_FEEDBACK_AGG ( AGG_ID STRING PRIMARY KEY, MODEL_ID STRING, AVG_RATING NUMBER, TOTAL_FEEDBACK INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

