USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_QUERY_LABELS ( LABEL_ID STRING PRIMARY KEY, QUERY_ID STRING, LABEL STRING, LABELED_BY STRING, LABELED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

