USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_RELEVANCE_EVENTS ( EVT_ID STRING PRIMARY KEY, QUERY_ID STRING, DOC_REF STRING, RATING INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

