USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEVANCE_MODEL_TRAINING ( TRAIN_ID STRING PRIMARY KEY, MODEL_ID STRING, TRAINING_PAYLOAD VARIANT, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, STATUS STRING );

