USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEVANCE_DEPLOYMENTS ( DEP_ID STRING PRIMARY KEY, MODEL_ID STRING, VERSION STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

