USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PRIVACY_EVENTS ( UPE_ID STRING PRIMARY KEY, USER_REF STRING, EVENT_TYPE STRING, DETAILS VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

