USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBJECT_ACCESS_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUEST_ID STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

