USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EDIT_AUDIT_6034 ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EDITOR STRING, CHANGES VARIANT, EDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

