USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBJECT_EXPORT_DELIVERY ( DEL_ID STRING PRIMARY KEY, ART_ID STRING, METHOD STRING, STATUS STRING, DELIVERED_AT TIMESTAMP_LTZ );

