USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_COMMENT_INDEX_6040 ( COMMENT_ID STRING PRIMARY KEY, REVIEW_ID STRING, COMMENT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

