USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCR_EXTRACTION_INDEX_6041 ( EX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, OCR_JSON VARIANT, EXTRACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

