USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBJECT_REQUEST_RECONCILE ( RECON_ID STRING PRIMARY KEY, REQ_ID STRING, EXPECTED_ITEMS INT, PROVIDED_ITEMS INT, STATUS STRING, RECON_DATE TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

