USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUEST_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, REQ_ID STRING, ESCALATED_TO STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

