USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_ANNOTATION_INDEX_6043 ( ANNOT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ANNOT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

