USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_TRAINING_LOGS ( LOG_ID STRING PRIMARY KEY, MODULE STRING, USER_REF STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SCORE NUMBER );

