USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, MODULE STRING, ASSIGNEE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DUE_AT TIMESTAMP_LTZ );

