USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_HISTORY ( TH_ID STRING PRIMARY KEY, ASSIGN_ID STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SCORE NUMBER );

