USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_MANIFEST_INDEX_6054 ( MANIFEST_ID STRING PRIMARY KEY, LOCATION STRING, FILE_COUNT INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

