USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SHIFT_COVERAGE ( COVER_ID STRING PRIMARY KEY, SHIFT_ID STRING, REQUIRED INT, ASSIGNED INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

