USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_FALLBACK_REGISTRY_6056 ( REG_ID STRING PRIMARY KEY, NAME STRING, CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

