USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_TEMPLATE_LIBRARY ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, TEMPLATE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

