USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CATALOG_SYNC_JOBS_6058 ( JOB_ID STRING PRIMARY KEY, TARGET_SCHEMA STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

