USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MONITORING_HEARTBEAT_INDEX_6058 ( HB_ID STRING PRIMARY KEY, COMPONENT STRING, STATUS STRING, LAST_HEARTBEAT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

