USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_ACTION_HISTORY_6060 ( ACTION_ID STRING PRIMARY KEY, ALERT_ID STRING, ACTION_JSON VARIANT, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

