USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_AUDIT_TRAIL ( AT_ID STRING PRIMARY KEY, REPORT_ID STRING, ACTION STRING, PERFORMED_BY STRING, AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

