USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_NOTIFICATION_PREFERENCES_6062 ( PREF_ID STRING PRIMARY KEY, USER_REF STRING, PREFERENCES JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

