USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_VIOLATION_6063 ( VIOL_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

