USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TOGGLE_AUDIT_6065 ( AUDIT_ID STRING PRIMARY KEY, TOGGLE_KEY STRING, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

