USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_AUDIT_INDEX_6069 ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, AUDIT_SUMMARY VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

