USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, ACTION STRING, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

