USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_RESPONSES ( RESPONSE_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR STRING, RESPONSE TEXT, RESPONDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

