USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QC_FLOW_6072 ( FLOW_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STEPS VARIANT, STATUS STRING DEFAULT 'NEW', UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

