USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_IMPACT_ASSESSMENT_6073 ( PIA_ID STRING PRIMARY KEY, TENANT_ID STRING, ASSESSMENT_JSON VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

