USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, INCIDENT_ID STRING, FROM_OPERATOR STRING, TO_OPERATOR STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

