USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_ALERT_RULES ( RULE_ID STRING PRIMARY KEY, SLO_ID STRING, CONDITION VARIANT, TARGET_CHANNEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

