USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_VIOLATION_NOTIFS ( NOTIF_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, NOTIF_PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

