USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_AUDIT_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, BILLING_RUN_ID STRING, SNAPSHOT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

