USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_RECONCILE_QUEUE ( REQ_ID STRING PRIMARY KEY, INVOICE_ID STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

