USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_RETRY_QUEUE ( QUEUE_ID STRING PRIMARY KEY, PAYMENT_REF STRING, ATTEMPTS INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

