USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCE_RECONCILE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, RUN_ID STRING, SUMMARY VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

