USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_REGION_PREFERENCES_6088 ( PREF_ID STRING PRIMARY KEY, USER_REF STRING, REGION STRING, PREFERENCES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

