USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_STATEMENTS ( STATEMENT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, STATEMENT_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

