USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_INDEX_6089 ( HEALTH_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, HEALTH_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

