USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_JURISDICTIONS ( JURIS_ID STRING PRIMARY KEY, COUNTRY STRING, REGION STRING, TAX_RATE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

