USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAX_AUDIT ( AUDIT_ID STRING PRIMARY KEY, INVOICE_ID STRING, TAX_DETAILS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

