USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECALL_RECONCILIATION_INDEX_6096 ( IDX_ID STRING PRIMARY KEY, REQ_ID STRING, RECON_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

