USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CURRENCY_RATES ( RATE_ID STRING PRIMARY KEY, FROM_CURR STRING, TO_CURR STRING, RATE NUMBER, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

