USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_EXCEPTIONS_6098 ( EX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REASON CLOB, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

