USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_DRYRUN ( DRYRUN_ID STRING PRIMARY KEY, POLICY_ID STRING, SAMPLE_COUNT INT, ESTIMATED_REMOVALS INT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

