USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDIT_NOTES ( NOTE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

