USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATION_REGISTRY_6102 ( NOTIF_ID STRING PRIMARY KEY, TITLE STRING, BODY STRING, LEVEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

