USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_COMPLIANCE_INDEX_6102 ( IDX_ID STRING PRIMARY KEY, ROLE STRING, COMPLIANCE_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

