USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAILED_PAYMENTS ( FP_ID STRING PRIMARY KEY, PAYMENT_REF STRING, FAILURE_CODE STRING, FAILURE_DETAIL VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

