USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_HANDOFF_RECORDS_6106 ( HANDOFF_ID STRING PRIMARY KEY, FROM_OPERATOR STRING, TO_OPERATOR STRING, HANDOFF_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

