USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RECOMMENDATION_INDEX_6106 ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, RECOMMENDATIONS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

