USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECOVERY_ACTIONS ( ACT_ID STRING PRIMARY KEY, CAMP_ID STRING, ACCOUNT_ID STRING, ACTION JSON, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

