USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLECTION_EVENTS ( EVT_ID STRING PRIMARY KEY, PARTNER_ID STRING, ACCOUNT_ID STRING, EVENT_PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

