USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_EFFICIENCY_INDEX_6110 ( IDX_ID STRING PRIMARY KEY, OPERATOR_REF STRING, EFFICIENCY_METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

