USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPENDENCY_MAP_6110 ( MAP_ID STRING PRIMARY KEY, SERVICE_REF STRING, DEPENDS_ON ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

