USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_REPORTS ( REPORT_ID STRING PRIMARY KEY, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, PAYLOAD VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

