USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_ERROR_BUDGET_6112 ( BUDGET_ID STRING PRIMARY KEY, TENANT_ID STRING, ALLOWED_ERRORS INT, WINDOW_SECONDS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

