USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_AD_HOC_QUERIES ( QUERY_ID STRING PRIMARY KEY, REQUESTOR STRING, QUERY TEXT, RESULT_LOCATION STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

