USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_SLO_VIOLATIONS_6114 ( VIOL_ID STRING PRIMARY KEY, SLO_REF STRING, DETAILS VARIANT, VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

