USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNERSHIP_TRANSFER_6118 ( TRANSFER_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, FROM_OWNER STRING, TO_OWNER STRING, TRANSFERRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

