USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHARGE_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, CHARGE_REF STRING, COST_CENTER_ID STRING, AMOUNT NUMBER, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

