USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_FINANCIAL_PROFILE_6120 ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, PROFILE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

