USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTICE_BOARD ( NOTICE_ID STRING PRIMARY KEY, TITLE STRING, BODY STRING, LEVEL STRING, CREATED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

