USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_CHANGE_LOGS_6125 ( LOG_ID STRING PRIMARY KEY, CHANGE_ID STRING, ENTRY VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

