USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNERSHIP_TRANSFER_6126 ( TRANSFER_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, OLD_OWNER STRING, NEW_OWNER STRING, TRANSFERRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

