USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_AI_MODEL_REGISTRY_6128 ( MODEL_ID STRING PRIMARY KEY, NAME STRING, VERSION STRING, META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

