USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_CATEGORIZATION_6130 ( CAT_ID STRING PRIMARY KEY, POLICY_ID STRING, CATEGORY STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

