USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUNDLE_STORAGE_QOS ( QOS_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STORAGE_TIER STRING, COST_ESTIMATE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

