USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SUBJECT STRING, ACTION STRING, ACCESS_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

