USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_LOCKS ( LOCK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCKED_BY STRING, LOCKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

