USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.USER_FEEDBACK_INDEX_6136 ( FB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, USER_REF STRING, FEEDBACK_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

