USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_GEO ( GEO_ID STRING PRIMARY KEY, SESSION_ID STRING, LAT NUMBER, LON NUMBER, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

