USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SNAPSHOT_INDEX_6138 ( SNAP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

