USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENT_AGGREGATES_6142 ( AGG_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, AGG_PAYLOAD VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

