USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VERSION_HISTORY ( PVH_ID STRING PRIMARY KEY, POLICY_ID STRING, VERSION INT, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

