USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_PREFLIGHT_CACHE ( CACHE_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_HASH STRING, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

