USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVISIONING_AUDIT_INDEX_6146 ( AUDIT_ID STRING PRIMARY KEY, RUN_REF STRING, AUDIT_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

