USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_HEALTH_INDEX_6148 ( IDX_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @31 @24 @56

