USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_NEGOTIATION_LOGS ( LOG_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, NEGOTIATION_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

