USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SANCTIONS_SCREENING ( SCREEN_ID STRING PRIMARY KEY, SIGNER_ID STRING, LIST_NAME STRING, RESULT STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

