USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TERMS_ACCEPTANCE ( ACC_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, ACCEPTED_BY STRING, ACCEPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

