USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DELIVERY_RETRY_QUEUE_6154 ( RETRY_ID STRING PRIMARY KEY, NOTIF_ID STRING, ATTEMPTS INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING' ); -- @31 @24 @56

