USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KYC_DOCUMENTS ( DOC_ID STRING PRIMARY KEY, SIGNER_ID STRING, DOC_TYPE STRING, FILE_REF STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

