USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PROVIDER_HEALTH_SUMMARY AS SELECT PROVIDER_NAME, COUNT(*) AS EVENTS, MAX(RECORDED_AT) AS LAST_EVENT FROM DOCGEN.PROVIDER_HEALTH_EVENTS GROUP BY PROVIDER_NAME;

