USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_SIGNATURE_INDEX ( SIGIDX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SIG_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

