USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_EVIDENCE_CHAIN_INDEX AS SELECT BUNDLE_ID, COUNT(*) AS CHAIN_LENGTH FROM DOCGEN.PROOF_CHAIN GROUP BY BUNDLE_ID;

