USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_RETAIN_REQUESTS_6166 ( REQ_ID STRING PRIMARY KEY, BUNDLE_REF STRING, RETAIN_DAYS INT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

