USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_AUDIT_6168 ( AUDIT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RETENTION_JSON VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

