USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_HISTORY ( H_ID STRING PRIMARY KEY, OPERATOR STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, NOTES VARIANT );

