USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATE_REQUESTS_6172 ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, CERT_TYPE STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

