USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_SHIFT_PREFERENCES AS SELECT OPERATOR, COUNT(*) AS PREF_COUNT FROM DOCGEN.SHIFT_PREFERENCES GROUP BY OPERATOR;

