USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_POLICY_VERSIONS_6174 ( VERSION_ID STRING PRIMARY KEY, POLICY_ID STRING, BODY VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

