USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_MEMO_INDEX_6178 ( MEMO_ID STRING PRIMARY KEY, INV_ID STRING, AMOUNT NUMBER, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

