USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PAYMENT_GATEWAY_LOGS_6181 ( LOG_ID STRING PRIMARY KEY, METRIC_ID STRING, ENTRY VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24 @56

