USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_FEEDBACK ( FB_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR STRING, FEEDBACK TEXT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

