USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PRIVACY_EVENTS AS SELECT EVENT_TYPE, COUNT(*) AS TOTAL FROM DOCGEN.USER_PRIVACY_EVENTS GROUP BY EVENT_TYPE;

