USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PUBLICATION_REGISTRY_6186 ( PUB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VERSION STRING, PUBLISHED_BY STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

