USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_RESPONSE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ASSIGNEE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

