USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_LIFECYCLE_INDEX_6188 ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LIFECYCLE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

