USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_EXEC_LOGS ( LOG_ID STRING PRIMARY KEY, RB_ID STRING, EXECUTOR STRING, STATUS STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

