USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SLA_AWARENESS ( AWARE_ID STRING PRIMARY KEY, OPERATOR STRING, SLO_IDS ARRAY, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

