USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_SIGNATURE_INDEX_6194 ( BIO_ID STRING PRIMARY KEY, SIGNATURE_ID STRING, BIOMETRIC_META VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

