USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OTP_CHALLENGE_INDEX_6198 ( CHALLENGE_ID STRING PRIMARY KEY, SIGNER_ID STRING, CHALLENGE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

