USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_ALERT_HISTORY ( H_ID STRING PRIMARY KEY, KPI_ID STRING, ALERT_ID STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

