USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SIGNER_ID STRING, THRESHOLD_ID STRING, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

