USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UI_FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, KEY STRING, ENABLED BOOLEAN DEFAULT FALSE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

