USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_KEY_REGISTRY_6202 ( KEY_ID STRING PRIMARY KEY, KEY_META VARIANT, ACTIVATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REVOKED BOOLEAN DEFAULT FALSE );

