USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONFIG_CHANGE_LOG ( LOG_ID STRING PRIMARY KEY, CONFIG_KEY STRING, OLD JSON, NEW JSON, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

