USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_QUEUE ( Q_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

