USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_POLICY_VIOLATIONS AS SELECT POLICY_ID, COUNT(*) AS VIOLATIONS FROM DOCGEN.POLICY_COMPLIANCE_INDEX WHERE COMPLIANT = FALSE GROUP BY POLICY_ID;

