USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_AUDIT_INDEX_6214 ( AUDIT_ID STRING PRIMARY KEY, MANIFEST_ID STRING, AUDIT_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

