USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RBAC_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ACTION STRING, TARGET_REF STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

