USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_STATUS_INDEX_6216 ( IDX_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CERT_STATUS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

