USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_GRANT_HISTORY ( GH_ID STRING PRIMARY KEY, ROLE_NAME STRING, SUBJECT_REF STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GRANTED_BY STRING );

