USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUTHZ_METRICS ( MET_ID STRING PRIMARY KEY, ACTION STRING, SUBJECT_REF STRING, COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

