USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOGIN_EVENTS ( EVENT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METHOD STRING, SUCCESS BOOLEAN, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

