USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAILED_LOGIN_ALERTS ( ALERT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ATTEMPTS INT, LAST_ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

