USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_LATENCY_INDEX_6224 ( IDX_ID STRING PRIMARY KEY, SESSION_ID STRING, LATENCY_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

