USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_USER_SESSION_SUMMARY AS SELECT USER_REF, COUNT(*) AS SESSIONS, MAX(EVENT_AT) AS LAST_SEEN FROM DOCGEN.LOGIN_EVENTS GROUP BY USER_REF;

