USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_CONFIG_HISTORY ( H_ID STRING PRIMARY KEY, CONFIG_KEY STRING, OLD JSON, NEW JSON, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

