USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_RELEASE_NOTES ( NOTE_ID STRING PRIMARY KEY, FEATURE_KEY STRING, NOTES CLOB, RELEASED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

