USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_FEEDBACK ( FB_ID STRING PRIMARY KEY, SUBJECT_REF STRING, COMMENTS STRING, RATING INT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

