USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEEDBACK_AGGREGATES ( AGG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, AVG_RATING NUMBER, COUNT INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

