USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_ROLLBACKS ( RB_ID STRING PRIMARY KEY, REL_ID STRING, INITIATED_BY STRING, ROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

