USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_RISK_SCORES_6244 ( SCORE_ID STRING PRIMARY KEY, SESSION_ID STRING, RISK_SCORE NUMBER, FACTORS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

