USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_REVIEW_HISTORY ( RH_ID STRING PRIMARY KEY, SLO_ID STRING, REVIEW_OUTCOME JSON, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

