USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_INDEX_6246 ( V_ID STRING PRIMARY KEY, SIGNER_ID STRING, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ, DETAILS VARIANT ); @31

