USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_AUDIT_OVERVIEW AS SELECT TARGET_REF, COUNT(*) AS EVENTS FROM DOCGEN.AUDIT_SNAPSHOT_ITEMS GROUP BY TARGET_REF;

