USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_IMPACT_INDEX ( IDX_ID STRING PRIMARY KEY, CHANGE_REF STRING, AFFECTED_COMPONENTS ARRAY, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

