USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_NOTARY_REGISTRY ( NOTARY_ID STRING PRIMARY KEY, NAME STRING, METADATA VARIANT, REGISTERED_AT TIMESTAMP_LTZ ); @31 @24
