USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_SUPPRESSION_HISTORY ( HIST_ID STRING PRIMARY KEY, RULE_ID STRING, ALERT_ID STRING, SUPPRESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

