USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_EVIDENCE_INDEX_6254 ( EVID_ID STRING PRIMARY KEY, BUNDLE_ID STRING, EVIDENCE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

