USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_RESOLUTION_REPORTS ( REPORT_ID STRING PRIMARY KEY, CASE_ID STRING, SUMMARY CLOB, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

