USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_INTEGRITY_INDEX_6261 ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, INTEGRITY_HASH STRING, VERIFIED_AT TIMESTAMP_LTZ ); @31

