USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BEHAVIOR_PROFILES ( PROFILE_ID STRING PRIMARY KEY, SIGNER_ID STRING, PROFILE JSON, UPDATED_AT TIMESTAMP_LTZ ); @31 @24
