USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANOMALY_DETECTION_QUEUE ( Q_ID STRING PRIMARY KEY, SUBJECT_REF STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ ); @31 @24
