USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_CASE_INDEX ( CASE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SIGNER_ID STRING, SEVERITY STRING, CREATED_AT TIMESTAMP_LTZ ); @31 @24
