USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_RATE_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, CLIENT_ID STRING, WINDOW_START TIMESTAMP_LTZ, ATTEMPTED INT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

