USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_INDEX_6267 ( ANCHOR_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TXID STRING, CHAIN_NAME STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

