USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_LOGS_6268 ( LOG_ID STRING PRIMARY KEY, ANCHOR_ID STRING, ENTRY VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

