USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_INVESTIGATION_QUEUE ( Q_ID STRING PRIMARY KEY, CASE_ID STRING, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ ); @31 @24
