USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITION VARIANT, TARGET_CHANNEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

