USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_ENTROPY ( ENT_ID STRING PRIMARY KEY, SESSION_ID STRING, ENTROPY_METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
