USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPLIANCE_INDEX_6271 ( IDX_ID STRING PRIMARY KEY, PROVIDER_ID STRING, COMPLIANCE_JSON VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

