USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_DEVICE_METRICS ( M_ID STRING PRIMARY KEY, SESSION_ID STRING, DEVICE_META VARIANT, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
