USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_KYC_RECORDS ( KYC_ID STRING PRIMARY KEY, SIGNER_ID STRING, KYC_JSON VARIANT, VERIFIED_AT TIMESTAMP_LTZ ); @31 @24
