USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_NOTICE_INDEX_6273 ( NOTICE_ID STRING PRIMARY KEY, REGION STRING, NOTICE_JSON VARIANT, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

