USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_STATE_HISTORY ( H_ID STRING PRIMARY KEY, SIGNATURE_ID STRING, OLD_STATE STRING, NEW_STATE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

