USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REVOCATION_INDEX ( REV_ID STRING PRIMARY KEY, CERT_ID STRING, SIGNATURE_ID STRING, REVOCATION_STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

