USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_STORE ( CERT_REF STRING PRIMARY KEY, CERT_META VARIANT, IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

