USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_THRESHOLD_ACTIONS ( ACTION_ID STRING PRIMARY KEY, THRESHOLD_ID STRING, ACTION JSON, CREATED_AT TIMESTAMP_LTZ ); @31 @24
