USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SUBJECT_ACCESS_INDEX_6281 ( ACCESS_ID STRING PRIMARY KEY, USER_REF STRING, SCOPE VARIANT, COMPLETED_AT TIMESTAMP_LTZ ); @31

