USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MODEL_TELEMETRY ( TEL_ID STRING PRIMARY KEY, MODEL_ID STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
