USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CHANGE_APPROVAL_INDEX_6283 ( IDX_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVAL_JSON VARIANT, APPROVED_AT TIMESTAMP_LTZ ); @31

