USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AML_CASE_QUEUE ( CASE_QID STRING PRIMARY KEY, BUNDLE_ID STRING, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ ); @31 @24
