USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANNOUNCEMENT_BROADCASTS_6285 ( ANN_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, CHANNELS ARRAY, SCHEDULED_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

