USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_LINKS ( LINK_ID STRING PRIMARY KEY, SIGNATURE_ID STRING, BUNDLE_ID STRING, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

