USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_HITS ( HIT_ID STRING PRIMARY KEY, FEED_ID STRING, SUBJECT_REF STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ ); @31 @24
