USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_MAINTENANCE_WINDOWS_6287 ( WINDOW_ID STRING PRIMARY KEY, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, DETAILS VARIANT ); @31

