USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_SCORES ( SCORE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCORE NUMBER, ASSESSED_AT TIMESTAMP_LTZ ); @31 @24
