USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_MONITORING_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, RULE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
