USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTACHMENT_MIME_INDEX ( ATT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, MIME_TYPE STRING, SIZE_BYTES NUMBER, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

