USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTACHMENT_STORAGE_TIERS ( TIER_ID STRING PRIMARY KEY, NAME STRING, COST_PER_GB NUMBER, DESCRIPTION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

