USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ENRICHMENT_INDEX_6291 ( ENRICH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ENRICH_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

