USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTACHMENT_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, ATT_ID STRING, SUBJECT_REF STRING, ACCESS_TYPE STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

