USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTACHMENT_PURGE_HISTORY ( H_ID STRING PRIMARY KEY, Q_ID STRING, ATT_ID STRING, RESULT VARIANT, PURGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

