USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_EXPORT_CONTROL ( EXPORT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, APPROVED_BY STRING, APPROVED_AT TIMESTAMP_LTZ ); @31 @24
