USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRDPARTY_SHARING_AGREEMENTS ( AGR_ID STRING PRIMARY KEY, PARTY_NAME STRING, AGREEMENT_JSON VARIANT, SIGNED_AT TIMESTAMP_LTZ ); @31 @24
