USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SHARING_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, REQUESTOR STRING, SCOPE VARIANT, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ ); @31 @24
