USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SHARING_TRANSFERS ( TRANS_ID STRING PRIMARY KEY, REQ_ID STRING, TARGET_PARTY STRING, TRANSFER_DETAILS VARIANT, TRANSFERRED_AT TIMESTAMP_LTZ ); @31 @24
