USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETIREMENT_SCHEDULE_6299 ( SCHEDULE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RETIRE_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

