USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, TERMS CLOB, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

