USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_ADMIN_TELEMETRY_AGG AS SELECT COMPONENT, COUNT(*) AS EVENTS, MAX(RECORDED_AT) AS LAST_EVENT FROM DOCGEN.ADMIN_TELEMETRY_EVENTS GROUP BY COMPONENT;

