USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_RETENTION ( RET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RETAIN_UNTIL TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ ); @31 @24
