USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_ALERTS ( ALERT_ID STRING PRIMARY KEY, SLO_ID STRING, SEVERITY STRING, PAYLOAD VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

