USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, SHIFT_ID STRING, INCIDENT_ID STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

