USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_EXCEPTION_APPROVALS ( APP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, APPROVED_BY STRING, APPROVED_AT TIMESTAMP_LTZ, NOTES VARIANT ); @31 @24
