USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_INCIDENT_METRICS AS SELECT INCIDENT_ID, COUNT(*) AS ACTIONS, MAX(CREATED_AT) AS LAST_ACTION FROM DOCGEN.OPERATOR_ACTION_HISTORY GROUP BY INCIDENT_ID;

