USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REQUEST_AUDIT ( AR_ID STRING PRIMARY KEY, REQUEST_ID STRING, ACTION STRING, PERFORMED_AT TIMESTAMP_LTZ ); @31 @24
