USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEC_INCIDENT_CORRELATIONS ( CORR_ID STRING PRIMARY KEY, INCIDENT_ID STRING, CORRELATED_WITH VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

