USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_COMPLIANCE_REPORTS ( REP_ID STRING PRIMARY KEY, TENANT_ID STRING, REPORT_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ ); @31 @24
