USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CRED_HISTORY ( HIST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CRED_META VARIANT, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

