USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_REPORT_SUBS ( SUB_ID STRING PRIMARY KEY, REP_ID STRING, SUBSCRIBER STRING, CREATED_AT TIMESTAMP_LTZ ); @31 @24
