USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_REPORT_DELIVERY ( DL_ID STRING PRIMARY KEY, REP_ID STRING, TARGET STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ ); @31 @24
