USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEP_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DEPENDS_ON ARRAY, COMPUTED_AT TIMESTAMP_LTZ ); @31 @24
