USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_GRAPH_NODES ( NODE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, NODE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
