USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_GRAPH_EDGES ( EDGE_ID STRING PRIMARY KEY, FROM_NODE STRING, TO_NODE STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
