USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GRAPH_TRAVERSAL_LOGS ( LOG_ID STRING PRIMARY KEY, START_NODE STRING, END_NODE STRING, PATH VARIANT, EXECUTED_AT TIMESTAMP_LTZ ); @31 @24
