USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_SUMMARY_6317 ( SUM_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGN_COUNT INT, LAST_SIGNED_AT TIMESTAMP_LTZ );

