USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ERROR_RATE_METRICS ( MET_ID STRING PRIMARY KEY, COMPONENT STRING, ERROR_RATE NUMBER, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
