USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLATFORM_ALERTS ( ALERT_ID STRING PRIMARY KEY, COMPONENT STRING, SEVERITY STRING, PAYLOAD VARIANT, RAISED_AT TIMESTAMP_LTZ ); @31 @24
