USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SKILL_GAP_ANALYSIS ( ANALYSIS_ID STRING PRIMARY KEY, OPERATOR STRING, GAPS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

