USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_SLA_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, INCIDENT_ID STRING, SLO_ID STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

