USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PERF_ALERTS ( ALERT_ID STRING PRIMARY KEY, OPERATOR STRING, METRIC JSON, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

