USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COACHING_NOTES ( NOTE_ID STRING PRIMARY KEY, OPERATOR STRING, COACH STRING, NOTE TEXT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

