USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CAPACITY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, PLAN_ID STRING, ASSIGNED_TO STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

