USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROGRAM_ENROLLMENTS ( ENROLL_ID STRING PRIMARY KEY, OPERATOR STRING, PROGRAM STRING, ENROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

