USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STORAGE_COST_ESTIMATES ( EST_ID STRING PRIMARY KEY, TENANT_ID STRING, EST_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ ); @31 @24
