USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_WHO_DID_WHAT AS SELECT PERFORMED_BY, ACTION, COUNT(*) AS CNT FROM DOCGEN.AUDIT_SNAPSHOT_ITEMS GROUP BY PERFORMED_BY, ACTION;

