USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PERMISSION_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCOPE VARIANT, STATUS STRING, REVIEWED_AT TIMESTAMP_LTZ );

