USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_FAILURES ( FAIL_ID STRING PRIMARY KEY, MANIFEST_ID STRING, ERROR_DETAIL VARIANT, FAILED_AT TIMESTAMP_LTZ ); @31 @24
