USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPLICATION_STATS ( STAT_ID STRING PRIMARY KEY, JOB_ID STRING, TRANSFERRED_BYTES NUMBER, DURATION_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
