USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPLICATION_ERRORS ( ERR_ID STRING PRIMARY KEY, JOB_ID STRING, ERROR_DETAIL VARIANT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
