USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SCHEMA_VERSIONS_6340 ( SCHEMA_VERSION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VERSION_NUMBER INT, SCHEMA_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

