USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIV_ACCESS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, APP_ID STRING, ACTION STRING, NOTES VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

