USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSS_REGION_SYNC ( SYNC_ID STRING PRIMARY KEY, SOURCE_REGION STRING, TARGET_REGION STRING, STATUS STRING, LAST_SYNC_AT TIMESTAMP_LTZ ); @31 @24
