USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_MERGE_QUEUE_6342 ( REQ_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, MERGE_INSTRUCTIONS VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

