USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ASSIGNEE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

