USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VARIANT_USAGE_6346 ( USAGE_ID STRING PRIMARY KEY, VARIANT_ID STRING, TENANT_ID STRING, USAGE_COUNT INT DEFAULT 0, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

