USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_INDEX_6348 ( VERSION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_NUMBER INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

