USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CLAUSE_DEP_INDEX ( IDX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, DEPENDS_ON ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

