USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_PROFILE_USAGE_6352 ( USAGE_ID STRING PRIMARY KEY, PROFILE_ID STRING, CALL_COUNT INT DEFAULT 0, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

