USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PREV_REQUESTS ( REQ_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

