USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.WORKFLOW_INSTANCES ( INST_ID STRING PRIMARY KEY, WF_ID STRING, DOCUMENT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

