USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_SIGNATURE_INDEX_6358 ( SIGN_ID STRING PRIMARY KEY, CONTRACT_ID STRING, SIGNER_ID STRING, SIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

