USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_SECRETS ( SECRET_ID STRING PRIMARY KEY, CLIENT_ID STRING, SECRET_HASH STRING, CREATED_AT TIMESTAMP_LTZ ); @31 @24
