USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.COUNTERSIGN_RECORDS ( CS_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNER_ID STRING, COUNTERSIGNED_AT TIMESTAMP_LTZ ); @24

