USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_EVENTS ( EVT_ID STRING PRIMARY KEY, PROFILE_ID STRING, SUBJECT_REF STRING, TRIGGERED_AT TIMESTAMP_LTZ ); @31 @24
