USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_COUNTERS ( CTR_ID STRING PRIMARY KEY, PROFILE_ID STRING, SUBJECT_REF STRING, COUNT INT, WINDOW_START TIMESTAMP_LTZ ); @31 @24
