USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_POLICY_BINDINGS ( BIND_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, BOUND_AT TIMESTAMP_LTZ ); @31 @24
