USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BOT_DETECTION_METRICS ( MET_ID STRING PRIMARY KEY, SUBJECT_REF STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ ); @31 @24
