USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CONSENT_REVOCATION_HISTORY ( H_ID STRING PRIMARY KEY, CONSENT_ID STRING, REVokedBy STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT ); @24

