USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_USAGE_ALERTS_6366 ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ALERT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

