USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DSAR_EXPORT_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, REQ_ID STRING, FILE_URL STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

