USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLIENT_QUOTA_USAGE ( USAGE_ID STRING PRIMARY KEY, QUOTA_ID STRING, USAGE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ ); @31 @24
