USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_VIOLATION_LOG ( LOG_ID STRING PRIMARY KEY, QUOTA_ID STRING, SUBJECT_REF STRING, OCCURRED_AT TIMESTAMP_LTZ ); @31 @24
