USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLIENT_PLAN_MAPPINGS ( MAP_ID STRING PRIMARY KEY, CLIENT_ID STRING, PLAN_ID STRING, EFFECTIVE_AT TIMESTAMP_LTZ ); @31 @24
