USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAN_OVERAGE_POLICIES ( POLICY_ID STRING PRIMARY KEY, PLAN_ID STRING, RULES VARIANT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
