USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLAN_OVERAGE_EVENTS ( EVT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACCOUNT_ID STRING, OCCURRED_AT TIMESTAMP_LTZ ); @31 @24
