USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_INDEX_6376 ( FLAG_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ENABLED BOOLEAN DEFAULT TRUE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

