USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.WATERMARK_APPLIED ( APPL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RULE_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

