USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_GRACE_PERIODS ( GP_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, GRACE_DAYS INT, CREATED_AT TIMESTAMP_LTZ ); @31 @24
