USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_STATUS_HISTORY ( H_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, OLD_STATUS STRING, NEW_STATUS STRING, CHANGED_AT TIMESTAMP_LTZ ); @31 @24
