USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_JOBS ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ENGINE_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ ); @24

