USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_ROLLOUT_JOBS_6378 ( JOB_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ROLLOUT_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ );

