USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_BENEFIT_LOGS ( LOG_ID STRING PRIMARY KEY, SUBSCRIPTION_ID STRING, BENEFIT JSON, LOGGED_AT TIMESTAMP_LTZ ); @31 @24
