USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CREDIT_ELIGIBILITY ( ELIG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CRITERIA JSON, EVALUATED_AT TIMESTAMP_LTZ ); @31 @24
