USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PDF_RENDER_ERRORS ( ERR_ID STRING PRIMARY KEY, JOB_ID STRING, ERROR_DETAIL VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

