USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SENSITIVITY_INDEX_6380 ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SENSITIVITY_SCORE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

