USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FULLTEXT_INDEX_META ( META_ID STRING PRIMARY KEY, INDEX_NAME STRING, LAST_BUILD_AT TIMESTAMP_LTZ, SHARD_COUNT INT ); @24

