USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SENSITIVE_DATA_MASKING_RULES_6382 ( RULE_ID STRING PRIMARY KEY, FIELD_PATH STRING, MASK_PATTERN STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

