USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SEARCH_SUGGEST_STATS ( STAT_ID STRING PRIMARY KEY, SUGGESTION STRING, SELECTED_COUNT INT, LAST_SELECTED_AT TIMESTAMP_LTZ ); @24

