USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TAG_CLOUD_METRICS ( MET_ID STRING PRIMARY KEY, TAG STRING, COUNT INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

