USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVIEW_SCORECARD_6386 ( SCORE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORES VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

