USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.BULK_SIGNING_JOBS ( JOB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TEMPLATE_ID STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

