USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.BULK_SIGNING_ITEMS ( ITEM_ID STRING PRIMARY KEY, JOB_ID STRING, SIGNER_ID STRING, STATUS STRING, ATTEMPTS INT DEFAULT 0, LAST_TRIED_AT TIMESTAMP_LTZ ); @24

