USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_QUOTA_PROFILES_6390 ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, QUOTA_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

