USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.API_USAGE_AGG ( AGG_ID STRING PRIMARY KEY, CLIENT_ID STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, CALLS INT, ERRORS INT ); @24

