USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.API_USAGE_ALERTS ( ALERT_ID STRING PRIMARY KEY, CLIENT_ID STRING, METRIC JSON, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

