USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INGEST_BACKPRESSURE ( MET_ID STRING PRIMARY KEY, COMPONENT STRING, BACKPRESSURE_LEVEL NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

