USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SLA_BREACH_NOTICES ( NOTICE_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, BREACH_DETAILS VARIANT, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

