USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_INDEX ( HEALTH_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, METRICS VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

