USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_COMPLIANCE_FLAGS ( FLAG_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FLAG_KEY STRING, SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

