USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.QUOTA_ENFORCE_LOGS ( LOG_ID STRING PRIMARY KEY, QUOTA_ID STRING, SUBJECT_REF STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

