USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SLA_BINDINGS ( BIND_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SLO_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

