USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_PREFLIGHT_CACHE ( CACHE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, RESULT JSON, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

