USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_TOS_ACCEPT ( ACC_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, VERSION_ID STRING, ACCEPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

