USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RELEASE_PIPELINE_6406 ( PIPE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, STAGE STRING, STATUS STRING DEFAULT 'PENDING', UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

