USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INVOICE_MAP ( MAP_ID STRING PRIMARY KEY, PROVIDER STRING, INVOICE_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

