USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SETTLEMENT_QUEUE ( Q_ID STRING PRIMARY KEY, PROVIDER STRING, AMOUNT NUMBER, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

