USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SHIFT_ROSTERS ( ROSTER_ID STRING PRIMARY KEY, SHIFT_DATE DATE, OPERATOR_LIST ARRAY, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

