USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FATIGUE_METRICS ( MET_ID STRING PRIMARY KEY, OPERATOR STRING, SCORE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

