USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.COVERAGE_FORECASTS ( FC_ID STRING PRIMARY KEY, DATE_DAY DATE, PREDICTED_NEED INT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

