USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_UTIL_REPORTS ( REP_ID STRING PRIMARY KEY, OPERATOR STRING, UTILIZATION_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

