USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INCIDENT_AUTOMATIONS ( AUTO_ID STRING PRIMARY KEY, INCIDENT_TYPE STRING, ACTIONS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

