USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RESPONSE_TIME_STATS ( STAT_ID STRING PRIMARY KEY, OPERATOR STRING, AVG_RESPONSE_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

