USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.WORKLOAD_PROJECTIONS ( PROJ_ID STRING PRIMARY KEY, OPERATOR STRING, PROJECTION JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24

