USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOCALIZATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCALE STRING, ACTION STRING, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

