USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_REMINDER_SCHEDULE ( SCH_ID STRING PRIMARY KEY, REQUEST_ID STRING, SCHEDULE_AT TIMESTAMP_LTZ, CHANNEL STRING, STATUS STRING DEFAULT 'SCHEDULED' ); -- @31 @24

