USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REMINDER_DISPATCH_LOG ( LOG_ID STRING PRIMARY KEY, SCH_ID STRING, ATTEMPT INT, STATUS STRING, DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

