USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_TEMPLATE_BINDINGS ( BIND_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, NOTIF_TEMPLATE_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

