USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_EVENT_STREAM ( EVT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

