USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_NOTIFICATION_METRICS ( MET_ID STRING PRIMARY KEY, SIGNER_ID STRING, NOTIF_COUNT INT, LAST_NOTIF_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

