USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_FRAUD_FLAGS ( FLAG_ID STRING PRIMARY KEY, SESSION_ID STRING, FLAG_TYPE STRING, FLAG_DETAIL VARIANT, FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

