USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETIREMENT_HISTORY ( H_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RETIRED_BY STRING, RETIRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

