USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ARCHIVE_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, BUNDLE_ID STRING, ARCHIVE_LOCATION STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

