USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHECKSUM_MON ( MON_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EXPECTED_CHECKSUM STRING, LAST_VERIFIED_AT TIMESTAMP_LTZ ); -- @31 @24

