USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_ERROR_TRACES ( TRACE_ID STRING PRIMARY KEY, JOB_ID STRING, STACK TRACE CLOB, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

