USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_ACTIVITY_SEQS ( SEQ_ID STRING PRIMARY KEY, SIGNER_ID STRING, EVENTS VARIANT, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

