USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_INDEX ( RIDX_ID STRING PRIMARY KEY, SESSION_ID STRING, REPLAY_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

