USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_STORAGE ( STORE_ID STRING PRIMARY KEY, REPLAY_REF STRING, STORAGE_URL STRING, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

