USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CONFLICT_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CONFLICT_JSON VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

