USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_MERGE_HISTORY ( MH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, MERGED_BY STRING, MERGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); -- @31 @24

