USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_MERGE_CONFLICT_IDX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CONFLICT_REF STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

