USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LINEAGE_EDGES ( EDGE_ID STRING PRIMARY KEY, FROM_TEMPLATE STRING, TO_TEMPLATE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

