USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ROLLBACK_POINTS ( RB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SNAPSHOT_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

