USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ROLLBACK_HISTORY ( H_ID STRING PRIMARY KEY, RB_ID STRING, ROLLED_BY STRING, ROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

