USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CONCURRENCY_METRICS ( MET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PEAK_LOCKS INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

