USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_EVENTS ( EVT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, USER_REF STRING, EVENT JSON, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

