USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COLLAB_CONFLICT_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CONFLICT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

