USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PUBLISH_HISTORY ( PH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PUBLISHED_BY STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), VERSION INT ); -- @31 @24

