USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_VIOLATIONS ( V_ID STRING PRIMARY KEY, SUBJECT_REF STRING, POLICY_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

