USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RISK_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, PROVIDER_NAME STRING, SCORE NUMBER, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31 @24

