USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RECERT_QUEUE ( Q_ID STRING PRIMARY KEY, PROVIDER STRING, DUE_DATE DATE, STATUS STRING DEFAULT 'PENDING' ); -- @31 @24

