USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DISPATCH_METRICS ( METRIC_ID STRING PRIMARY KEY, RULE_ID STRING, SENT INT, FAILED INT, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

