USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_LOCATION_HISTORY ( LOCATION_ID STRING PRIMARY KEY, DEVICE_ID STRING, LOCATION JSON, EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

