USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_TIMEZONE_INDEX ( TZ_ID STRING PRIMARY KEY, SIGNER_ID STRING, TIMEZONE STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

