USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_VIOLATION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, POLICY_ID STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

