USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_FORECASTS ( FORECAST_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PREDICTED_USAGE INT, FORECAST_WINDOW VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

