USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_SIMILARITY_INDEX ( INDEX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, VECTOR VECTOR, EMBEDDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

