USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_SIMILARITY_SHARD_MAP ( MAP_ID STRING PRIMARY KEY, SHARD_ID STRING, RANGE_START INT, RANGE_END INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

