USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ACCESS_CONTROLS ( CONTROL_ID STRING PRIMARY KEY, BUNDLE_ID STRING, POLICY VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

