USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_ACCESS_REQUESTS ( REQ_ID STRING PRIMARY KEY, BUNDLE_ID STRING, REQUESTOR STRING, PURPOSE STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

