USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PERF_METRICS_SUMMARY ( METRIC_ID STRING PRIMARY KEY, COMPONENT STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, METRICS VARIANT );

