USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LATENCY_PERCENTILES ( PID STRING PRIMARY KEY, COMPONENT STRING, P50 NUMBER, P95 NUMBER, P99 NUMBER, SAMPLE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

