USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ERROR_CATEGORY_INDEX ( CAT_ID STRING PRIMARY KEY, COMPONENT STRING, ERROR_CODE STRING, DESCRIPTION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

