USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ERROR_TRACES ( TRACE_ID STRING PRIMARY KEY, COMPONENT STRING, ERROR_CODE STRING, TRACE CLOB, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

