USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENGAGEMENT_HISTORY ( HIST_ID STRING PRIMARY KEY, SIGNER_ID STRING, METRIC JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

