USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_EFFECTIVENESS ( EFFECT_ID STRING PRIMARY KEY, RULE_ID STRING, SENT INT, CLICKED INT, CONVERSION_RATE NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

