USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_FENCING_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, POLYGON VARIANT, ACTION JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

