USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEO_EVENTS ( EVT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, LOCATION JSON, EVENT_TYPE STRING, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

