USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_GEO_CORRELATION ( CORR_ID STRING PRIMARY KEY, SESSION_ID STRING, GEO_MATCH BOOLEAN, DETAILS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

