USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_GEO_POLICY_BINDINGS ( BIND_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

