USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WORKFLOW_TASKS ( TASK_ID STRING PRIMARY KEY, RUN_ID STRING, STEP_INDEX INT, TASK_JSON VARIANT, STATUS STRING, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

