USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, PROFILE_ID STRING, CHECK_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING );

