USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_CHANGES ( CHANGE_ID STRING PRIMARY KEY, FLAG_KEY STRING, ACTOR STRING, CHANGE_JSON VARIANT, CHANGE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

