USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXP_METRIC_ROLLUP ( ROLLUP_ID STRING PRIMARY KEY, EXP_ID STRING, METRIC_NAME STRING, AGG_JSON VARIANT, ROLLUP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

