USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, OPERATOR STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

