USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_SHIFT_CHANGES ( CHANGE_ID STRING PRIMARY KEY, SCHEDULE_ID STRING, CHANGED_BY STRING, CHANGE_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

