USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_INCIDENT_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

