USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, ENTITY_REF STRING, EVENT_TYPE STRING, ENDPOINT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

