USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DELIVERY_METRICS ( METRIC_ID STRING PRIMARY KEY, PROVIDER STRING, SUCCESS INT, FAIL INT, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

