USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_GATEWAY_THREAT_HITS ( HIT_ID STRING PRIMARY KEY, CLIENT_ID STRING, TYPE STRING, DETAIL VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

