USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_GATEWAY_IP_BANS ( BAN_ID STRING PRIMARY KEY, IP_ADDRESS STRING, REASON STRING, BANNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

