USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_REQ_SIGNATURE_CHECKS ( CHECK_ID STRING PRIMARY KEY, REQUEST_REF STRING, VALID BOOLEAN, DETAILS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

