USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_DELIVERIES ( DELIVERY_ID STRING PRIMARY KEY, SUB_ID STRING, PAYLOAD VARIANT, STATUS STRING, ATTEMPT_COUNT INT DEFAULT 0, LAST_ATTEMPT_AT TIMESTAMP_LTZ );
-- Generated per Snowflake E-Sign patterns @31

