USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_HEALTH_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, COMPONENT STRING, SEVERITY STRING, DESCRIPTION STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

