USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTION_HISTORY ( ACTION_ID STRING PRIMARY KEY, OPERATOR STRING, ACTION JSON, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

