USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_RESPONSE ( RESP_ID STRING PRIMARY KEY, INCIDENT_ID STRING, OPERATOR STRING, ACTION JSON, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

