USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_DELIVERY_LOG ( LOG_ID STRING PRIMARY KEY, DELIVERY_ID STRING, ATTEMPT INT, STATUS STRING, RESPONSE VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

