USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OP_PRIV_ACTION_REQS ( REQ_ID STRING PRIMARY KEY, OPERATOR STRING, ACTION JSON, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

