USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OP_PRIV_ACTION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, REQ_ID STRING, RESULT JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

