USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUPPORT_ESCALATION_HISTORY ( H_ID STRING PRIMARY KEY, TICKET_ID STRING, RULE_ID STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES VARIANT );

