USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_APPROVALS ( APP_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, APPROVED_BY STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

