USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_REFUND_HISTORY ( REF_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, REASON STRING, PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

