USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_LATENCY_ROLLING ( ROLL_ID STRING PRIMARY KEY, PROVIDER STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, LATENCY_MS_AVG NUMBER );

