USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ERROR_BUDGET ( BUDGET_ID STRING PRIMARY KEY, PROVIDER STRING, ALLOWED_ERRORS INT, WINDOW JSON, TRACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

