USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FALLBACK_HISTORY ( H_ID STRING PRIMARY KEY, REQUEST_REF STRING, PRIMARY_PROVIDER STRING, FALLBACK_PROVIDER STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

