USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, PROVIDER STRING, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, STATUS STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

