USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOT_ITEMS ( ITEM_ID STRING PRIMARY KEY, MANIFEST_ID STRING, PAYLOAD VARIANT, SNAPSHOT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

