USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DASHBOARD_SHARES ( SHARE_ID STRING PRIMARY KEY, DASH_ID STRING, SUBJECT_REF STRING, SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

