USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVELOPER_USAGE_LEDGER ( LEDGER_ID STRING PRIMARY KEY, API_KEY_ID STRING, METRIC STRING, COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

