USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INBOUND_IDEMPOTENCY ( IDEMPOTENCY_KEY STRING PRIMARY KEY, SOURCE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CONSUMED BOOLEAN DEFAULT FALSE );
-- Generated per Snowflake E-Sign patterns @31

