USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_REPORTS ( SCHED_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CRON_EXPR STRING, TARGETS VARIANT, LAST_RUN_AT TIMESTAMP_LTZ );

