USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_RUNS ( RUN_ID STRING PRIMARY KEY, SCHED_ID STRING, STATUS STRING, OUTPUT_LOCATION STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

