USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORT_DELIVERY_LOG ( LOG_ID STRING PRIMARY KEY, RUN_ID STRING, TARGET STRING, STATUS STRING, DELIVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

