USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_EXPORT_FAILURES ( FAIL_ID STRING PRIMARY KEY, JOB_ID STRING, ERROR_DETAIL VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

