USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIV_ESCALATION_HISTORY ( H_ID STRING PRIMARY KEY, Q_ID STRING, ACTION JSON, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

