USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTROL_BINDINGS ( BIND_ID STRING PRIMARY KEY, CONTROL_ID STRING, TARGET_REF STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

