USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_POLICY_AUDIT AS SELECT POLICY_ID, COUNT(*) AS EVENTS, MAX(EVENT_AT) AS LAST_EVENT FROM DOCGEN.POLICY_AUDIT GROUP BY POLICY_ID;

