USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_OPERATOR_PERF AS SELECT OPERATOR, AVG(METRIC:response_time::NUMBER) AS AVG_RESP FROM DOCGEN.OPERATOR_PERF_METRICS GROUP BY OPERATOR;

