USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ACTION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, ACTIONS JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

