USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVELOPER_QUOTA_USAGE ( USAGE_ID STRING PRIMARY KEY, API_KEY_ID STRING, USAGE_COUNT NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ ); @31

