USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ROTATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, KEY_REF STRING, NEXT_ROTATION_at TIMESTAMP_LTZ, INTERVAL_DAYS INT, LAST_ROTATED_AT TIMESTAMP_LTZ );

