USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTARY_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, NOTARY_ID STRING, ACTION STRING, PAYLOAD VARIANT, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

