USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, PROVIDER STRING, DESCRIPTION STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

