USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'ACTIVE', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

