USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_INTEGRITY_ALERTS ( ALERT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ISSUE JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

