USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHAIN_EDGES ( EDGE_ID STRING PRIMARY KEY, FROM_NODE STRING, TO_NODE STRING, RELATION STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

