USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAIMS_ASSERTION_INDEX ( IDX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CLAIMS VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

