USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAIMS_DISCREPANCY_ALERTS ( ALERT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, DISCREPANCY JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

