USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JOB_RETRIES_QUEUE ( Q_ID STRING PRIMARY KEY, JOB_REF STRING, PAYLOAD VARIANT, NEXT_ATTEMPT TIMESTAMP_LTZ, ATTEMPTS INT DEFAULT 0 );

