USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JOB_DEAD_LETTER ( DLQ_ID STRING PRIMARY KEY, JOB_REF STRING, ERROR_JSON VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

