USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_TASKS ( TASK_ID STRING PRIMARY KEY, MW_ID STRING, TASK_JSON VARIANT, STATUS STRING, SCHEDULED_AT TIMESTAMP_LTZ );

