USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_HISTORY ( H_ID STRING PRIMARY KEY, TASK_ID STRING, OUTCOME JSON, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

