USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAMPLING_AUDIT_LOGS ( LOG_ID STRING PRIMARY KEY, SAMPLE_REF STRING, REASON STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

