USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_CATALOG_ENTRIES ( ENTRY_ID STRING PRIMARY KEY, TABLE_NAME STRING, SCHEMA_JSON VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

