USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PROVENANCE_INDEX ( IDX_ID STRING PRIMARY KEY, RECORD_REF STRING, PROVENANCE JSON, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

