USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYS_MAINT_EVENTS ( EVT_ID STRING PRIMARY KEY, COMPONENT STRING, DETAILS VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

