USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNTIME_CONFIG_AUDIT ( AUDIT_ID STRING PRIMARY KEY, OVERRIDE_ID STRING, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DIFF VARIANT );

