USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_RULE_HITS ( HIT_ID STRING PRIMARY KEY, RULE_ID STRING, REQUEST_REF STRING, HIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

