USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_JOBS ( JOB_ID STRING PRIMARY KEY, BUNDLE_ID STRING, STATUS STRING, TX_ID STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );
-- Generated per Snowflake E-Sign patterns @31

