USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SIGNER_RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, SIGNER_ID STRING, RISK_SCORE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

