USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ADAPTIVE_CHALLENGE_QUEUE ( Q_ID STRING PRIMARY KEY, SIGNER_ID STRING, CHALLENGE_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

