USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UPDATE_DEPLOYMENTS ( DEPLOY_ID STRING PRIMARY KEY, COMPONENT STRING, VERSION STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DEPLOYED_BY STRING ); @31

