USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_ARTIFACTS ( ART_ID STRING PRIMARY KEY, REQ_ID STRING, LOCATION STRING, SIZE_BYTES NUMBER, PRODUCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

