USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_ACCESS_CONTROLS ( CTRL_ID STRING PRIMARY KEY, MANIFEST_ID STRING, POLICY JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

