USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_ACCESS_REQ_HISTORY ( H_ID STRING PRIMARY KEY, REQ_ID STRING, ACTION JSON, PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

