USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_COMPLIANCE_EXPORT_MANIFEST AS SELECT MANIFEST_ID, COUNT(*) AS ITEMS, MAX(ARCHIVED_AT) AS LAST_ARCHIVE FROM DOCGEN.DOCUMENT_ARCHIVE_MANIFEST GROUP BY MANIFEST_ID;

