USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_CERTS ( CERT_ID STRING PRIMARY KEY, DEVICE_ID STRING, CERT_PEM CLOB, ISSUED_AT TIMESTAMP_LTZ, EXPIRES_AT TIMESTAMP_LTZ );

