USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERT_CHAIN_CACHE ( CERT_FP STRING PRIMARY KEY, CHAIN VARIANT, FETCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );
-- Generated per Snowflake E-Sign patterns @31

