USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.UPDATE_DEPLOY_ERRORS ( ERR_ID STRING PRIMARY KEY, DEPLOY_ID STRING, ERROR_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

