USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CONTRACT_RENEWAL_QUEUE ( Q_ID STRING PRIMARY KEY, CONTRACT_ID STRING, TENANT_ID STRING, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING' );

