USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CONTRACT_RENEWAL_HISTORY ( H_ID STRING PRIMARY KEY, Q_ID STRING, OUTCOME JSON, PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

