USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SECURITY_LABELS ( LABEL_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LABEL_KEY STRING, LABEL_VALUE STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

