USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SECURITY_LABELS ( DSL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LABEL_KEY STRING, LABEL_VALUE STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

