USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CACHE ( OCSP_ID STRING PRIMARY KEY, CERT_FP STRING, OCSP_RESPONSE VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
-- Generated per Snowflake E-Sign patterns @31

