USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MIGRATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MIGRATION_NAME STRING, STATUS STRING, LOG VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

