USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.LABEL_CHANGE_HISTORY ( H_ID STRING PRIMARY KEY, TARGET_REF STRING, LABEL_KEY STRING, OLD_VALUE STRING, NEW_VALUE STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

