USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ENTROPY_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ENTROPY_SCORE NUMBER, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

