USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DUPLICATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DUPLICATE_REF STRING, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

