USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SIMILARITY_MAP ( MAP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SIMILAR_TO STRING, SCORE NUMBER, MAPPED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

