USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_FEATURE_USAGE ( USAGE_ID STRING PRIMARY KEY, MODEL_ID STRING, FEATURE_KEY STRING, USAGE_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

