USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_COST_ALERTS ( ALERT_ID STRING PRIMARY KEY, MODEL_ID STRING, THRESHOLD_JSON VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

