USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_QUOTA_BINDINGS ( BIND_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, QUOTA_JSON VARIANT, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

