USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.MODEL_QUOTA_USAGE ( USAGE_ID STRING PRIMARY KEY, BIND_ID STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, USAGE JSON );

