USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_QUALITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, NAME STRING, QUERY STRING, LAST_RUN_AT TIMESTAMP_LTZ, LAST_RESULT VARIANT ); @31

