USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_VERIFICATION_CHECKS ( CHECK_ID STRING PRIMARY KEY, PROVIDER STRING, CHECK_JSON VARIANT, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

