USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_BILLING_AUDIT AS SELECT ACCOUNT_ID, COUNT(*) AS DISPUTES, MAX(SUBMITTED_AT) AS LAST_DISPUTE FROM DOCGEN.BILLING_DISPUTE_QUEUE GROUP BY ACCOUNT_ID;

