USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DISPUTE_METRICS_BY_TENANT ( MET_ID STRING PRIMARY KEY, TENANT_ID STRING, OPEN_DISPUTES INT, RESOLVED_DISPUTES INT, AS_OF TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

