USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_OVERRIDES ( OV_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, OVERRIDE_JSON VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ );

