USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.INVOICE_ALERTS ( ALERT_ID STRING PRIMARY KEY, INVOICE_REF STRING, TENANT_ID STRING, REASON STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

