USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PAYMENT_PROVIDER_MAPPINGS ( MAP_ID STRING PRIMARY KEY, TENANT_ID STRING, PROVIDER STRING, META VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

