USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_CONTROL_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CONTROL_ID STRING, CHANGE_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

