USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TENANT_BILLING_PROFILES ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, PROFILE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

