USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.BILLING_PROFILE_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, TENANT_ID STRING, PROFILE_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

