USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TAX_JURISDICTION_INDEX ( JURIS_ID STRING PRIMARY KEY, COUNTRY_CODE STRING, REGION_CODE STRING, TAX_META VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

