USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TAX_CALC_LOGS ( LOG_ID STRING PRIMARY KEY, INVOICE_REF STRING, TAX_BREAKDOWN JSON, CALCULATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

