USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.LOCALIZATION_QUALITY_METRICS ( MET_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LOCALE STRING, SCORE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

