USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.TRANSLATOR_PERF_STATS ( STAT_ID STRING PRIMARY KEY, PROVIDER STRING, LATENCY_MS NUMBER, ERR_RATE NUMBER, SAMPLE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

