USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_STATES ( FLAG_ID STRING PRIMARY KEY, NAME STRING, ENABLED BOOLEAN DEFAULT FALSE, TARGET JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

