USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.AI_MODERATION_ISSUES ( ISSUE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ISSUE_JSON VARIANT, FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

