USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.AI_MODERATION_WORKFLOW ( WF_ID STRING PRIMARY KEY, ISSUE_ID STRING, STEPS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

