USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLIANCE_CERTS ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

