USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLIANCE_AUDITS ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, RESULT JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

