USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PRIVACY_INCIDENT_REPORTS ( INCIDENT_ID STRING PRIMARY KEY, TENANT_ID STRING, SEVERITY STRING, DESCRIPTION STRING, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

