USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DPA_ACCEPTANCE ( ACCEPT_ID STRING PRIMARY KEY, DPA_ID STRING, SUBJECT_REF STRING, ACCEPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

