USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PRIVACY_SUMMARIES ( SUMMARY_ID STRING PRIMARY KEY, PROVIDER STRING, SUMMARY JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

