USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_KEY_ROTATION ( ROT_ID STRING PRIMARY KEY, KEY_ID STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PREVIOUS_KEY_ID STRING );
-- Generated per Snowflake E-Sign patterns @31

