USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_RATE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, CLIENT_ID STRING, RATE_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

