USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.CLIENT_SECRET_LEAK_REPORTS ( REPORT_ID STRING PRIMARY KEY, CLIENT_ID STRING, LEAK_DETAIL VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

