USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CRED_ROTATION ( ROT_ID STRING PRIMARY KEY, OPERATOR STRING, CRED_REF STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

