USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_USE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, KEY_ID STRING, OPERATION STRING, INVOKED_BY STRING, INVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

