USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.LRT_ENFORCEMENTS ( ENF_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_TABLE STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

