USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DATA_DISPOSAL_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, TARGET_REF STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

