USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.DATA_DISPOSAL_HISTORY ( H_ID STRING PRIMARY KEY, REQ_ID STRING, ACTION_JSON VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

