USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OP_AUDIT_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, OPERATOR STRING, CERT_JSON VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

