USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.OPERATOR_COMPLIANCE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, OPERATOR STRING, REVIEWER STRING, RESULT JSON, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

