USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_COST_BREAKDOWNS ( BREAK_ID STRING PRIMARY KEY, RUN_ID STRING, ACCOUNT_ID STRING, COST_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

