USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PRIV_ACTION_AUDIT AS SELECT PERFORMED_BY, COUNT(*) AS ACTIONS, MAX(PERFORMED_AT) AS LAST_ACTION FROM DOCGEN.OP_PRIV_ACTION_AUDIT GROUP BY PERFORMED_BY;

