USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_EXEC_LOGS ( LOG_ID STRING PRIMARY KEY, RUNBOOK_REF STRING, STEP_JSON VARIANT, STATUS STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

