USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_ACTIVITY_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTIVITY JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

