USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_ADMIN_CHANGE_REQUESTS AS SELECT REQUESTOR, COUNT(*) AS PENDING_REQUESTS, MAX(REQUESTED_AT) AS LAST_REQUEST FROM DOCGEN.TEMPLATE_CHANGE_REQUESTS WHERE STATUS='OPEN' GROUP BY REQUESTOR;

