USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_SYSTEM_HEALTH_SUMMARY AS SELECT COMPONENT, MAX(UPDATED_AT) AS LAST_UPDATE, COUNT(*) FILTER (WHERE STATUS!='OK') AS ISSUES FROM DOCGEN.SERVICE_HEALTH_DASHBOARD GROUP BY COMPONENT;

