USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VARIANT_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VARIANT_KEY STRING, METADATA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

