USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REFERENCE_INDEX ( REF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REF_KEY STRING, REF_VALUE STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

