USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSICS_ARTIFACTS ( ARTIFACT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ARTIFACT_TYPE STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

