USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_QUERY_LOGS ( LOG_ID STRING PRIMARY KEY, QUERY_TEXT STRING, RESULT_COUNT INT, LATENCY_MS NUMBER, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

