USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_CHAIN_NODES ( NODE_ID STRING PRIMARY KEY, BUNDLE_ID STRING, HASH STRING, NODE_META VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

