USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_RECON_LOG ( LOG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, EXPECTED_HASH STRING, SEEN_HASH STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

