USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_AFFINITY_INDEX ( AFF_ID STRING PRIMARY KEY, NETWORK STRING, PROVIDER_PREF JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

