USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_JURISDICTION_INDEX ( J_ID STRING PRIMARY KEY, TENANT_ID STRING, JURISDICTION JSON, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

