USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JURISDICTION_VIOLATION_REPORTS ( REP_ID STRING PRIMARY KEY, CHECK_ID STRING, TENANT_ID STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

