USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CONSENT_BINDINGS ( BIND_ID STRING PRIMARY KEY, POLICY_ID STRING, SIGNER_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

