USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICYSYNC_EVENT_LOG ( EVT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION STRING, PAYLOAD VARIANT, EVT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

