USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNTIME_FEATURE_METRICS ( MET_ID STRING PRIMARY KEY, FEATURE_KEY STRING, TENANT_ID STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

