USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_IMPACT_ANALYSIS ( ANAL_ID STRING PRIMARY KEY, FEATURE_KEY STRING, IMPACT_JSON VARIANT, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

