USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AB_TEST_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, EXP_ID STRING, SUMMARY JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

