USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_TICKETS ( TICKET_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ASSIGNED_TO STRING, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

