USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEGMENT_ASSIGNMENT_LOGS ( LOG_ID STRING PRIMARY KEY, SEG_ID STRING, SUBJECT_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

