USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_CONFIG_CACHE ( CACHE_ID STRING PRIMARY KEY, SCOPE_REF STRING, CONFIG JSON, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

