USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_INCIDENT_PLAYBOOKS ( PLAYBOOK_ID STRING PRIMARY KEY, NAME STRING, STEPS JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

