USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OP_ONCALL_FEEDBACK ( FB_ID STRING PRIMARY KEY, OPERATOR STRING, FEEDBACK JSON, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

