USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OP_CASE_LOAD_METRICS ( MET_ID STRING PRIMARY KEY, OPERATOR STRING, OPEN_CASES INT, AVG_RESOLVE_TIME NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

