USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_BATCH_RUN_STATS ( STAT_ID STRING PRIMARY KEY, BATCH_NAME STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), METRICS VARIANT );

