USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_PREVIEW_AUDIT AS SELECT TEMPLATE_ID, COUNT(*) AS PREVIEWS, MAX(REQUESTED_AT) AS LAST_PREVIEW FROM DOCGEN.TEMPLATE_PREV_REQUESTS GROUP BY TEMPLATE_ID;

