USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_FAILURE_RATE ( FR_ID STRING PRIMARY KEY, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, FAIL_COUNT INT, TOTAL_COUNT INT );

