USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OP_INCIDENT_EMAIL_NOTIFS ( NOTIF_ID STRING PRIMARY KEY, INCIDENT_ID STRING, EMAIL_TO STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

