USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_ESCALATION_HISTORY ( H_ID STRING PRIMARY KEY, INCIDENT_ID STRING, POLICY_ID STRING, ACTION JSON, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

