USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REVIEW_NOTES ( NOTE_ID STRING PRIMARY KEY, REVIEW_ID STRING, NOTE STRING, AUTHOR STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

