USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_QUALITY_METRICS ( MET_ID STRING PRIMARY KEY, REVIEW_ID STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

