USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REBATE_REDEMPTIONS ( RED_ID STRING PRIMARY KEY, ASSIGN_ID STRING, AMOUNT NUMBER, REDEEMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

