USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EDITOR_SESSIONS ( SES_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EDITOR STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_HEARTBEAT TIMESTAMP_LTZ );

