USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_EDITOR_CONFLICT_LOGS ( LOG_ID STRING PRIMARY KEY, CHANGE_ID STRING, CONFLICT JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

