USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_DATA_SHARING ( SHARING_ID STRING PRIMARY KEY, TENANT_ID STRING, PROVIDER STRING, SCOPE VARIANT, AGREED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

