USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_SHARING_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, PROVIDER STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

