USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_THROTTLE_BINDINGS ( BIND_ID STRING PRIMARY KEY, PROFILE_ID STRING, SUBJECT_REF STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

