USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REQUEST_RETRY_INDEX ( IDX_ID STRING PRIMARY KEY, REQUEST_REF STRING, NEXT_RETRY_AT TIMESTAMP_LTZ, ATTEMPTS INT DEFAULT 0 );

