USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TRAFFIC_STATS ( STAT_ID STRING PRIMARY KEY, PROVIDER STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, CALLS INT, ERRORS INT );

