USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, NAME STRING, EMAIL STRING, PHONE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

