USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_DEVICE_ATTESTATIONS ( ATTEST_ID STRING PRIMARY KEY, DEVICE_ID STRING, ATTEST_JSON VARIANT, ATTESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

