USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ATTESTATION_VERIFICATION_LOG ( LOG_ID STRING PRIMARY KEY, ATTEST_ID STRING, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

