USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_IDENTITY_LINKS ( LINK_ID STRING PRIMARY KEY, SIGNER_ID STRING, IDP STRING, ID_REF STRING, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

