USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_CHECKS ( CHK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECKSUM STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

