USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPLAY_PROTECTION_INDEX ( IDX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, NONCE_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

