USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINGERPRINT_COLLISION_ALERTS ( ALERT_ID STRING PRIMARY KEY, F_ID STRING, COLLIDING_IDS ARRAY, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

