USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPORTING_JOB_CONFIGS ( CONFIG_ID STRING PRIMARY KEY, NAME STRING, SCHEDULE JSON, QUERY TEXT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

