USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_NOTIFICATION_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

