USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_RESOURCE_USAGE ( USAGE_ID STRING PRIMARY KEY, SESSION_ID STRING, CPU_MS NUMBER, MEM_BYTES NUMBER, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

