USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_QUEUE_BACKPRESSURE ( BP_ID STRING PRIMARY KEY, QUEUE_NAME STRING, BACKPRESSURE_LEVEL STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

