USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_THROTTLE_EVENTS ( EVT_ID STRING PRIMARY KEY, QUEUE_NAME STRING, THROTTLE_REASON STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

