USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHECKPOINT_RECOVERY_LOGS ( LOG_ID STRING PRIMARY KEY, CP_ID STRING, RECOVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

