USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_STATE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SESSION_ID STRING, STATE VARIANT, SNAP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

