USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LABEL_PROPAGATION_LOGS ( LOG_ID STRING PRIMARY KEY, SOURCE_REF STRING, TARGET_REF STRING, LABELS ARRAY, PROPAGATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

