USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LABEL_CONFLICT_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, TARGET_REF STRING, CONFLICT_JSON VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

