USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETENTION_LABEL_ENFORCEMENT ( ENF_ID STRING PRIMARY KEY, LABEL_ID STRING, ACTION_JSON VARIANT, ENFORCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

