USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REPLACEMENT_INDEX ( IDX_ID STRING PRIMARY KEY, ORIGINAL_DOC STRING, REPLACEMENT_DOC STRING, REPLACED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

