USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_DEPRECATION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, DEPRECATED_BY STRING, DEPRECATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );

