USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATION_HISTORY ( H_ID STRING PRIMARY KEY, REQ_ID STRING, ACTION_JSON VARIANT, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

