USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_MITIGATIONS ( MIT_ID STRING PRIMARY KEY, V_ID STRING, ACTION_JSON VARIANT, MITIGATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

