USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_WEBHOOK_EVENTS ( EVENT_ID STRING PRIMARY KEY, WEBHOOK_ID STRING, EVENT_PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), HANDLED BOOLEAN DEFAULT FALSE );

