USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MAINT_WINDOW ( MW_ID STRING PRIMARY KEY, PROVIDER STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, NOTES STRING );

