USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_PROVIDER_BINDINGS ( BIND_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PROVIDER STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

