USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_SESSIONS ( SESSION_ID STRING PRIMARY KEY, SIGNER_ID STRING, DEVICE_ID STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_ACTIVE_AT TIMESTAMP_LTZ );

