USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SIGNER_ID STRING, CHANNEL STRING, PAYLOAD VARIANT, SENT_AT TIMESTAMP_LTZ, STATUS STRING );

