USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_RECONCILIATION_ITEMS ( ITEM_ID STRING PRIMARY KEY, REC_ID STRING, LINE_REF STRING, EXPECTED_AMOUNT NUMBER, ACTUAL_AMOUNT NUMBER, STATUS STRING );
-- Generated per Snowflake E-Sign patterns @31

