USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_BUCKETS ( BUCKET_ID STRING PRIMARY KEY, NAME STRING, RETENTION_DAYS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

