USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_PROFILES ( PROFILE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PROFILE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- Generated per Snowflake E-Sign patterns @31

