USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_METRICS ( MET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TOTAL_SIGS INT, UNIQUE_SIGNERS INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

