USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_OPT_OUTS ( OPT_ID STRING PRIMARY KEY, SIGNER_ID STRING, CHANNEL STRING, OPTED_OUT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

