USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TICKET_ACTIVITY_LOGS ( LOG_ID STRING PRIMARY KEY, TICKET_ID STRING, ACTOR STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

