USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEALTH_CHECK_REGISTRY ( CHECK_ID STRING PRIMARY KEY, NAME STRING, LAST_RUN_AT TIMESTAMP_LTZ, STATUS STRING, DETAILS VARIANT ); @31

