USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTACT_DIRECTORY_INDEX ( CONTACT_ID STRING PRIMARY KEY, TENANT_ID STRING, CONTACT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

