USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_CONTACT_ROLES ( ROLE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CONTACT_ID STRING, ROLE STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

