USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VIEW_METRICS ( MET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VIEW_COUNT INT, UNIQUE_VIEWERS INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

