USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_STORAGE_QUOTAS ( QUOTA_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, QUOTA_BYTES NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

