USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STORAGE_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CURRENT_USAGE NUMBER, QUOTA NUMBER, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

