USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SNAPSHOT_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, SNAP_ID STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

