USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRON_JOB_REGISTRY ( JOB_ID STRING PRIMARY KEY, NAME STRING, CRON_EXPR STRING, LAST_RUN_AT TIMESTAMP_LTZ, ENABLED BOOLEAN DEFAULT TRUE ); @31

