USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_ROSTER ( ROSTER_ID STRING PRIMARY KEY, OPERATOR STRING, START_DATE TIMESTAMP_LTZ, END_DATE TIMESTAMP_LTZ );

