USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_ACTIVITY_HEARTBEAT ( HB_ID STRING PRIMARY KEY, SIGNER_ID STRING, ACTIVITY_JSON VARIANT, HEARTBEAT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

