USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_LATENCY_HISTOGRAM ( HIST_ID STRING PRIMARY KEY, PROVIDER STRING, BUCKET_MS NUMBER, COUNT INT, SAMPLE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

