USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ERROR_DASHBOARD ( DASH_ID STRING PRIMARY KEY, PROVIDER STRING, ERROR_TYPE STRING, COUNT INT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

