USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PDF_ACCESS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, MANIFEST_ID STRING, SUBJECT_REF STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

