USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_DEVICE_LINK_HISTORY ( LINK_H_ID STRING PRIMARY KEY, USER_REF STRING, DEVICE_ID STRING, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), UNLINKED_AT TIMESTAMP_LTZ );

