USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PREFERENCES_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, PREF_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

