USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTITENANT_FEATURE_USAGE ( USG_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_KEY STRING, USAGE_COUNT NUMBER, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ );

