USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ESTIMATE_HISTORY ( HIST_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ESTIMATE_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

