USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_STATS ( STAT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, USAGE_COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

