USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_NOTES ( NOTE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REFERENCE JSON );

