USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_DISCLAIMER_RECORDS ( REC_ID STRING PRIMARY KEY, TENANT_ID STRING, DISCLAIMER_TEXT CLOB, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

