USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_NOTIFICATION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, TENANT_ID STRING, CHANNEL STRING, TEMPLATE_CLOB CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

