USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_ERRORS ( ERROR_ID STRING PRIMARY KEY, SESSION_ID STRING, ERROR_CODE STRING, ERROR_MSG STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

