USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_QUEUE ( Q_ID STRING PRIMARY KEY, EVENT_ID STRING, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, ATTEMPTS INT DEFAULT 0 ) ; -- @31

