USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_DEADLETTER ( DLQ_ID STRING PRIMARY KEY, EVENT_ID STRING, PAYLOAD VARIANT, FAILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), FAILURE_REASON STRING ) ; -- @31

