USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_POLICIES ( POLICY_ID STRING PRIMARY KEY, NAME STRING, ORDERED_PROVIDERS ARRAY, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

