USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_ERROR_REPORTS ( REPORT_ID STRING PRIMARY KEY, SDK_NAME STRING, VERSION STRING, ERROR_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

