USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_TELEMETRY_HEARTBEAT ( HB_ID STRING PRIMARY KEY, SDK_NAME STRING, VERSION STRING, HEARTBEAT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

