USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_STATE ( STATE_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTIVE_PROVIDER STRING, SWITCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ) ; -- @31

