USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, ALERT_ID STRING, CHANNEL STRING, TARGET STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ ); @31

