USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_APPROVAL_LOGS ( LOG_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, DECISION STRING, NOTES CLOB, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

