USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_PORTAL_SESSIONS ( SESSION_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, USER_REF STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LAST_ACTIVITY TIMESTAMP_LTZ );

