USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_JOBS ( JOB_ID STRING PRIMARY KEY, CERT_ID STRING, STATUS STRING DEFAULT 'PENDING', SCHEDULED_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

