USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRL_INGEST_LOG ( LOG_ID STRING PRIMARY KEY, SOURCE STRING, PAYLOAD VARIANT, INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), PARSED BOOLEAN DEFAULT FALSE ) ; -- @31

