USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_EVENTS ( EVENT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, EVENT_TYPE STRING, DETAILS VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

