USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENT_RESPONSE ( INCIDENT_ID STRING PRIMARY KEY, SEVERITY STRING, STEPS JSON, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

