USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_POSTMORTEM_ARCHIVE ( PM_ID STRING PRIMARY KEY, INCIDENT_ID STRING, DOC_URL STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

