USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DATA_MAP ( MAP_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

