USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANNEL_PROVIDER_CATALOG ( PROVIDER_ID STRING PRIMARY KEY, CHANNEL STRING, PROVIDER_JSON VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

