USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVAL_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, PACKET_ID STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ARCHIVE_LOCATION STRING ) ; -- @31

