USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANNEL_DISPATCH_TELEMETRY ( TEL_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHANNEL STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

