USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TEMPORAL_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ) ; -- @31

