USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANNEL_FAILOVER_POLICIES ( POLICY_ID STRING PRIMARY KEY, TENANT_ID STRING, CHANNEL STRING, POLICY_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

