USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_VERSION_LINKS ( LINK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_REF STRING, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

