USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANNEL_FAILOVER_EVENTS ( EVT_ID STRING PRIMARY KEY, POLICY_ID STRING, EVENT_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

