USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_RECONCILE ( RECON_ID STRING PRIMARY KEY, PROVIDER STRING, FINDINGS JSON, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

