USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REPLACEMENT_MAP ( MAP_ID STRING PRIMARY KEY, OLD_TEMPLATE_ID STRING, NEW_TEMPLATE_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

