USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_USAGE_BUDGET ( BUDGET_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, BUDGET_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

