USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_SLA_EVENTS ( EVT_ID STRING PRIMARY KEY, SLO_ID STRING, TENANT_ID STRING, EVENT JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

