USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_USAGE_BREACH_EVENTS ( EVT_ID STRING PRIMARY KEY, BUDGET_ID STRING, DETAILS JSON, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

