USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_SLA_ACKS ( ACK_ID STRING PRIMARY KEY, EVT_ID STRING, ACK_BY STRING, ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

