USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_FALLBACK_LOGS ( LOG_ID STRING PRIMARY KEY, REQUEST_REF STRING, PRIMARY_MODEL STRING, FALLBACK_MODEL STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

