USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_KPI_DEFINITIONS ( KPI_ID STRING PRIMARY KEY, NAME STRING, QUERY_SQL CLOB, TARGET JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

