USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FINANCIAL_PROJECTION_RUNS ( RUN_ID STRING PRIMARY KEY, TENANT_ID STRING, PROJECTION_JSON VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

