USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_ALERT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, KPI_ID STRING, TENANT_ID STRING, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

