USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_ALERT_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, SUB_ID STRING, ALERT_JSON VARIANT, DELIVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ) ; -- @31

