USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_ALERTS ( ALERT_ID STRING PRIMARY KEY, SLA_ID STRING, METRIC_NAME STRING, THRESHOLD VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

