USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BUSINESS_METRIC_ALERTS ( ALERT_ID STRING PRIMARY KEY, TENANT_ID STRING, METRIC_KEY STRING, THRESHOLD_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

