USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_MAINTENANCE_NOTICES ( NOTICE_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

