USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_DEPRECATED_FEATURES ( FEATURE_ID STRING PRIMARY KEY, NAME STRING, DEPRECATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTICE STRING ) ; -- @31

