USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_REFUND_JOBS ( JOB_ID STRING PRIMARY KEY, INVOICE_ID STRING, AMOUNT NUMBER, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ) ; -- @31

