USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SRE_PAGERDUTY_INTEGRATIONS ( INT_ID STRING PRIMARY KEY, SERVICE_KEY STRING, CONFIG JSON, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

