USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_OUTAGE_POSTMORTEMS ( PM_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ROOT_CAUSE JSON, MITIGATIONS JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

