USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_LEGAL_NOTICES ( NOTICE_ID STRING PRIMARY KEY, PROVIDER STRING, NOTICE_TEXT CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

