USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_USAGE_INDEX ( IDX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, DOCUMENT_ID STRING, POSITION JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

