USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_VERSIONS ( VERSION_ID STRING PRIMARY KEY, SERVICE_ID STRING, VERSION STRING, CHANGELOG CLOB, RELEASED_AT TIMESTAMP_LTZ ); @31

