USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTERPRISE_COMPLIANCE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCOPE VARIANT, REVIEWER STRING, RESULT JSON, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

