USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENTERPRISE_EXPORT_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

