USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_COMPLIANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, OPERATOR STRING, DETAILS VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

