USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERT_REVOC_HISTORY ( H_ID STRING PRIMARY KEY, CERT_ID STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

