USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_HEALTH_CHECKS ( CHECK_ID STRING PRIMARY KEY, SERVICE_ID STRING, CHECK_NAME STRING, STATUS STRING, LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

