USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ONBOARDING_CHECKLIST ( CHECK_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, ITEMS VARIANT, COMPLETED_AT TIMESTAMP_LTZ );

