USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_CONTRACT_REGISTRY ( CONTRACT_ID STRING PRIMARY KEY, NAME STRING, CONTRACT_JSON VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

