USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_CONTRACT_VERSIONS ( VER_ID STRING PRIMARY KEY, CONTRACT_ID STRING, VERSION_NUMBER INT, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

