USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVELOPER_API_KEYS ( KEY_ID STRING PRIMARY KEY, DEVELOPER_REF STRING, KEY_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

