USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRDPARTY_INTEGRATION_HEALTH ( HEALTH_ID STRING PRIMARY KEY, PROVIDER STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ, DETAILS VARIANT ); @31

