USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CANARY_RELEASE_DECISIONS ( DEC_ID STRING PRIMARY KEY, VERSION STRING, DECISION_JSON VARIANT, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

