USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNTIME_FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, FLAG_KEY STRING, ENABLED BOOLEAN DEFAULT FALSE, SCOPE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

