USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPLOYMENT_NOTIFICATION_LOGS ( NOTIF_ID STRING PRIMARY KEY, RUN_ID STRING, MESSAGE STRING, LEVEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

