USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_SESSION_AUDIT ( SESSION_AUDIT_ID STRING PRIMARY KEY, ADMIN_USER STRING, ACTION STRING, TARGET_REF STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

