USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COST_FORECAST ( FORECAST_ID STRING PRIMARY KEY, PROVIDER STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, ESTIMATES VARIANT );

