USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIAL_ROTATIONS ( ROT_ID STRING PRIMARY KEY, PROVIDER STRING, CRED_META VARIANT, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

