USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_PROFILES ( PROFILE_ID STRING PRIMARY KEY, NAME STRING, RENDER_OPTIONS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

