USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNTIME_METRICS_LABELS ( LABEL_ID STRING PRIMARY KEY, METRIC_KEY STRING, LABEL JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

