USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTICE_HISTORY ( NOTICE_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, PUBLISHED_BY STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

