USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REDACTION_LOGS ( REDACT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REDACTED_BY STRING, REDACTION_JSON VARIANT, REDACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

