USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REDACTION_RECOVERY_REQUESTS ( REQ_ID STRING PRIMARY KEY, TOKEN_ID STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

