USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_EVENT_INDEX ( EVT_IDX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, EVENT_TYPE STRING, EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

