USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ANCHOR_LINKS ( LINK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ANCHOR_TXID STRING, CHAIN_POS INT, LINKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

