USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SAFELIST ( SAFE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EXEMPT_REASON STRING, EXEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

