USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLACK_CONFIGS ( CFG_ID STRING PRIMARY KEY, PROVIDER STRING, WEBHOOK_URL STRING, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

