USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EMAIL_CONFIGS ( CFG_ID STRING PRIMARY KEY, PROVIDER STRING, SMTP_JSON VARIANT, DEFAULT_FROM STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

