USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SMS_CONFIGS ( CFG_ID STRING PRIMARY KEY, PROVIDER STRING, API_JSON VARIANT, CARRIER INFO VARCHAR, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

