USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_TRACKING ( TRACK_ID STRING PRIMARY KEY, PROVIDER STRING, SLA_JSON VARIANT, LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

