USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MANUAL_REVIEW_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, RES_ID STRING, ESCALATED_TO STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

