USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REVIEW_KPI_ROLLUPS ( ROLL_ID STRING PRIMARY KEY, TENANT_ID STRING, KPI_JSON VARIANT, ROLL_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

