USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_FEEDBACK_INDEX ( FB_ID STRING PRIMARY KEY, SUBJECT_REF STRING, DOCUMENT_ID STRING, RATING INT, FEEDBACK_TEXT CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

