USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_RUN_HISTORY ( RUN_ID STRING PRIMARY KEY, AGENT_ID STRING, INPUT VARIANT, OUTPUT VARIANT, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

