USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_TELEMETRY_METRICS ( MET_ID STRING PRIMARY KEY, AGENT_ID STRING, METRICS VARIANT, COLLECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

