USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_VERSION_REGISTRY ( AGENT_VER_ID STRING PRIMARY KEY, AGENT_ID STRING, VERSION STRING, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

