USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_ROLLBACK_REQUESTS ( REQ_ID STRING PRIMARY KEY, AGENT_ID STRING, TO_VERSION STRING, REQUESTED_BY STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

