USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_POLICY_VERSIONS ( POLICY_ID STRING PRIMARY KEY, TENANT_ID STRING, VERSION_NUMBER INT, BODY CLOB, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

