USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DSR_METRICS ( MET_ID STRING PRIMARY KEY, TENANT_ID STRING, OPEN_REQUESTS INT, AVG_TTR NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

