USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_SIGNER_FLAGS ( FLG_ID STRING PRIMARY KEY, SIGNER_ID STRING, FLAG_KEY STRING, DETAILS VARIANT, FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

