USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDER_CACHE_INVALIDATION ( INV_ID STRING PRIMARY KEY, TARGET_REF STRING, REASON STRING, INVALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

