USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_QUOTA_HISTORY ( HIST_ID STRING PRIMARY KEY, PROFILE_ID STRING, USED NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ ); @31

