USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AML_CHECKS ( AML_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CHECK_JSON VARIANT, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

