USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_API_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ADMIN_USER STRING, ACTION STRING, TARGET STRING, DETAILS VARIANT, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

