USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LOCALIZATION_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  LOC_ID STRING,
  CHANGED_BY STRING,
  CHANGES VARIANT,
  CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

