USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RENDER_BACKUPS (
  BACKUP_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  SNAPSHOT_LOCATION STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

