USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_COST_BREAKDOWN (
  B_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  LINE_ITEMS VARIANT,
  COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

