USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_TRUST_SCORES (
  SCORE_ID STRING PRIMARY KEY,
  DEVICE_ID STRING,
  SIGNER_ID STRING,
  SCORE NUMBER,
  EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

