USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_HEARTBEATS ( HB_ID STRING PRIMARY KEY, WORKER_REF STRING, LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @31 @24

