USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELEGATED_CREDENTIALS ( CRED_ID STRING PRIMARY KEY, SUBJECT STRING, CRED_META VARIANT, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

