USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FINGERPRINT_REGISTRY (
  FP_ID STRING PRIMARY KEY,
  DEVICE_ID STRING,
  FINGERPRINT JSON,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

