USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_RISK_EVENT_QUEUE (
  Q_ID STRING PRIMARY KEY,
  DEVICE_ID STRING,
  EVENT_JSON VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

