USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_TEMPLATE_STORE (
  TEMPLATE_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  TEMPLATE_HASH STRING,
  META VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

