USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LIVENESS_CHALLENGE_QUEUE (
  Q_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  CHALLENGE_JSON VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

