USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDER_WORKER_CONFIGS ( CONFIG_ID STRING PRIMARY KEY, WORKER_REF STRING, CONFIG VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

