USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPENDENCY_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ISSUE JSON,
  DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

