USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CHANGE_NOTIFICATION_QUEUE (
  Q_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  EVENT JSON,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

