USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_INCIDENTS (
  INCIDENT_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  INCIDENT_JSON VARIANT,
  REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

