USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_INVESTIGATIONS (
  INV_ID STRING PRIMARY KEY,
  INCIDENT_ID STRING,
  INVESTIGATOR STRING,
  STATUS STRING DEFAULT 'OPEN',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

