USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_TOKENS ( TOKEN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

