USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_CONSENT_AUDIT_TRAIL (
  AUDIT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  CONSENT_JSON VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

