USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTION_REVIEWS (
  REVIEW_ID STRING PRIMARY KEY,
  ACTION_REF STRING,
  REVIEWER STRING,
  OUTCOME STRING,
  REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

