USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ESCALATION_RULES (
  RULE_ID STRING PRIMARY KEY,
  NAME STRING,
  CONDITION JSON,
  ACTION JSON,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

