USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_FORECAST (
  FORECAST_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TENANT_ID STRING,
  FORECAST JSON,
  GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

