USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGION_DATA_RESIDENCY ( RES_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, REGION STRING, POLICY_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

