USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.ACCESS_TOKEN_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TOKEN_ID STRING, ACTION STRING, PERFORMED_BY STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

