USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPRECATION_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  SCHED_ID STRING,
  SENT_TO ARRAY,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

