USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SLA_REPORTS (
  REPORT_ID STRING PRIMARY KEY,
  PROFILE_ID STRING,
  WINDOW_START TIMESTAMP_LTZ,
  WINDOW_END TIMESTAMP_LTZ,
  METRICS VARIANT
);
-- @31

