USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_BREACH_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  PROFILE_ID STRING,
  TENANT_ID STRING,
  BREACH_JSON VARIANT,
  NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

