USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EDITOR_CHANGE_TRACKING (
  TRACK_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  USER_REF STRING,
  DIFF VARIANT,
  TRACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

