USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTOSAVE_SNAPSHOTS (
  SNAP_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  BODY CLOB,
  SAVED_BY STRING,
  SAVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

