USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EDITOR_PRESENCE_INDEX (
  PRES_ID STRING PRIMARY KEY,
  SESSION_ID STRING,
  USER_REF STRING,
  LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

