USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_AI_ANNOTATION_INDEX (
  ANN_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ANNOTATION JSON,
  ANNOTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

