USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_ANNOTATION_FEEDBACK (
  FB_ID STRING PRIMARY KEY,
  ANN_ID STRING,
  USER_REF STRING,
  RATING INT,
  NOTES CLOB,
  SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

