USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AI_TRAINING_JOB_QUEUE (
  JOB_ID STRING PRIMARY KEY,
  DATASET_ID STRING,
  MODEL_ID STRING,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

