USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SLO_BREACH_EVENTS (
  EVT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  BREACH_JSON VARIANT,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

