USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SLO_ACKNOWLEDGEMENTS (
  ACK_ID STRING PRIMARY KEY,
  EVT_ID STRING,
  ACK_BY STRING,
  ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

