USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ROLLBACK_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TO_VERSION INT,
  REQUESTED_BY STRING,
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

