USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QNA_JOBS (
  JOB_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  QUERY_JSON VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

