USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STYLE_GUIDE_ASSIGNMENTS (
  ASSIGN_ID STRING PRIMARY KEY,
  GUIDE_ID STRING,
  TEMPLATE_ID STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

