USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESSIBILITY_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ISSUES VARIANT,
  AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

