USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INDEX_SNAPSHOTS ( SNAPSHOT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

