USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_IMAGE_ASSETS (
  ASSET_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  PATH STRING,
  METADATA VARIANT,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

