USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_FONT_REGISTRY (
  FONT_ID STRING PRIMARY KEY,
  NAME STRING,
  LICENSE JSON,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

