USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_FONT_USAGE (
  USG_ID STRING PRIMARY KEY,
  FONT_ID STRING,
  TEMPLATE_ID STRING,
  USAGE_COUNT INT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

