USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_ENGINE_POOL_NODES (
  NODE_ID STRING PRIMARY KEY,
  POOL_ID STRING,
  HOST STRING,
  STATUS STRING,
  LAST_HEARTBEAT TIMESTAMP_LTZ
);
-- @31

