USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.EMBEDDED_RESOURCES ( RESOURCE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RESOURCE_TYPE STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

