USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUEST_LOGS ( LOG_ID STRING PRIMARY KEY, REQ_ID STRING, ACTION STRING, DETAIL VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

