USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_MERGE_JOBS (
  JOB_ID STRING PRIMARY KEY,
  SOURCE_DOCS ARRAY,
  TARGET_DOC STRING,
  STATUS STRING DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

