USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUALITY_REVIEWERS (
  REVIEWER_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  REVIEWER_REF STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

