USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUALITY_REVIEW_LOGS (
  LOG_ID STRING PRIMARY KEY,
  REVIEWER_ID STRING,
  COMMENTS CLOB,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

