USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTOTEST_SCRIPTS (
  SCRIPT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  SCRIPT_TEXT CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

