USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTOTEST_RUNS (
  RUN_ID STRING PRIMARY KEY,
  SCRIPT_ID STRING,
  STATUS STRING DEFAULT 'PENDING',
  STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ENDED_AT TIMESTAMP_LTZ
);
-- @31

