USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_INTERNAL_NOTES (
  NOTE_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  NOTE_CLOB CLOB,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

