USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_THIRD_PARTY_INTEGRATIONS (
  INT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  PROVIDER STRING,
  CONFIG VARIANT,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

