USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_COMPLIANCE_TAGS (
  TAG_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TAG_KEY STRING,
  TAG_VALUE STRING,
  ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

