USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DATA_CLASSIFICATION (
  CLASS_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  CLASS_JSON VARIANT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

