USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNER_HISTORY (
  H_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  OWNER_REF STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

