USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNERSHIP_TRANSFER_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  FROM_OWNER STRING,
  TO_OWNER STRING,
  STATUS STRING DEFAULT 'PENDING',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

