USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DELEGATION_POLICIES (
  POLICY_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  DELEGATIONS JSON,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

