USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DELEGATION_AUDIT_LOG (
  LOG_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  ACTION JSON,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- @31

