USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SSO_AUDIT_LOG ( LOG_ID STRING PRIMARY KEY, USER_REF STRING, IDP STRING, ACTION STRING, TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

