USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVIEW_FEEDBACK (
  FB_ID STRING PRIMARY KEY,
  ASSIGN_ID STRING,
  FEEDBACK_CLOB CLOB,
  RATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

