USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROCESSING_NODE_HEALTH ( HEALTH_ID STRING PRIMARY KEY, NODE_REF STRING, STATUS STRING, LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @31 @24

