USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_TAG_ASSIGNMENTS (
  ASSIGN_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  TAG_ID STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

