USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_TRENDS (
  TREND_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  PERIOD_START TIMESTAMP_LTZ,
  PERIOD_END TIMESTAMP_LTZ,
  METRICS VARIANT
);

