USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_COMPLIANCE_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  CHECK_JSON VARIANT,
  RESULT STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

