USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SNAPSHOT_RETENTION (
  RET_ID STRING PRIMARY KEY,
  SNAP_ID STRING,
  RETENTION_DAYS INT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

