USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVILEGED_ACTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, ACTION_JSON VARIANT, REQUESTOR STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

