USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.SIGNING_DEVICE_HEALTH (
  HEALTH_ID STRING PRIMARY KEY,
  DEVICE_ID STRING,
  STATUS STRING,
  LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
);

