USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_DEPENDENCY_GRAPH (
  GRAPH_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ADJ_LIST VARIANT,
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

