USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_APPROVAL_LOGS (
  LOG_ID STRING PRIMARY KEY,
  MATRIX_ID STRING,
  ACTION JSON,
  ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

