USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROCESSING_NODE_ERRORS ( ERR_ID STRING PRIMARY KEY, NODE_REF STRING, JOB_REF STRING, ERROR_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

