USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_WATERMARK_LOGS (
  LOG_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  WATERMARK_JSON VARIANT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

