USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETAIN_FLAGS (
  FLAG_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  REASON STRING,
  SET_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

