USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_RETENTION_OVERRIDES (
  OVERRIDE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  POLICY_ID STRING,
  OVERRIDE_JSON VARIANT,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

