USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_ASSIGNMENTS (
  ASSIGN_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

