USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_VIOLATIONS (
  V_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  BUNDLE_ID STRING,
  DETAILS VARIANT,
  DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

