USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
-- Generated per Snowflake E-Signature patterns @31 @24 @56
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_REMEDIATIONS (
  REM_ID STRING PRIMARY KEY,
  V_ID STRING,
  ACTION_JSON VARIANT,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

