USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_COMPLIANCE_REPORTS ( REPORT_ID STRING PRIMARY KEY, POLICY_ID STRING, SCOPE VARIANT, STATUS STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

