USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_LATENCY_METRICS (
  METRIC_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  P95_MS NUMBER,
  P99_MS NUMBER,
  SAMPLE_COUNT NUMBER,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

