USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ERROR_RATES (
  METRIC_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  ERROR_RATE NUMBER,
  WINDOW_START TIMESTAMP_LTZ,
  WINDOW_END TIMESTAMP_LTZ
); -- @1

