USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_THROUGHPUT (
  METRIC_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  REQ_PER_MIN NUMBER,
  WINDOW_START TIMESTAMP_LTZ,
  WINDOW_END TIMESTAMP_LTZ
); -- @1

