USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_BACKUP_RECONCILIATION (
  RECON_ID STRING PRIMARY KEY,
  BACKUP_ID STRING,
  CHECKSUM STRING,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

