USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_AUDIT_LOGS (
  LOG_ID STRING PRIMARY KEY,
  HSM_ACTION STRING,
  ACTOR STRING,
  LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); -- @1

