USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_KEY_PERMISSIONS (
  PERM_ID STRING PRIMARY KEY,
  KEY_ID STRING,
  SUBJECT_REF STRING,
  GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

