USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_IDENTITY_VERIFICATIONS (
  VER_ID STRING PRIMARY KEY,
  SIGNER_ID STRING,
  METHOD STRING,
  RESULT STRING,
  VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  META VARIANT
); -- @1

