USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_PURGE_LOGS ( LOG_ID STRING PRIMARY KEY, TARGET_TABLE STRING, PURGED_COUNT INT, PURGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31

