USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDENTITY_PROVIDER_HEALTH (
  HEALTH_ID STRING PRIMARY KEY,
  PROVIDER STRING,
  STATUS STRING,
  LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); -- @1

