USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_REQUEST_PRIORITY_QUEUE (
  Q_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  PRIORITY INT,
  STATUS STRING DEFAULT 'QUEUED',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

