USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_REQUEST_PREEMPTION_LOG (
  LOG_ID STRING PRIMARY KEY,
  Q_ID STRING,
  PREEMPTED_BY STRING,
  REASON STRING,
  PREEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

