USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HIGH_VALUE_SIGNING_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  AMOUNT NUMBER,
  RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); -- @1

