USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONSENT_REGISTRY (
  CONSENT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  PROVIDER STRING,
  CONSENT_JSON VARIANT,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

