USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONSENT_AUDIT (
  AUDIT_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  ACTION STRING,
  ACTOR STRING,
  ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

