USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_DATA_SHARING_LOGS (
  LOG_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  TARGET_PROVIDER STRING,
  SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PAYLOAD VARIANT
); -- @1

