USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_DATA_REVOKE_QUEUE (
  Q_ID STRING PRIMARY KEY,
  CONSENT_ID STRING,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

