USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_CHECKS ( CHECK_ID STRING PRIMARY KEY, NAME STRING, LAST_RUN TIMESTAMP_LTZ, RESULT VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

