USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_MASKING_AUDIT_RULES (
  RULE_ID STRING PRIMARY KEY,
  TARGET_TABLE STRING,
  TARGET_COLUMN STRING,
  RULE_JSON VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

