USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_RULE_ASSIGNMENTS (
  ASSIGN_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  TENANT_ID STRING,
  APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

