USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MASKING_ENFORCEMENT_LOGS (
  LOG_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  QUERY_TEXT CLOB,
  ENFORCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

