USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_QUEUE (
  Q_ID STRING PRIMARY KEY,
  POLICY_ID STRING,
  TARGET_REF STRING,
  STATUS STRING DEFAULT 'PENDING',
  ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

