USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REGISTRY (
  HOLD_ID STRING PRIMARY KEY,
  TARGET_REF STRING,
  REASON STRING,
  PLACED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

