USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  SCOPE VARIANT,
  ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_LTZ
); -- @1

