USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_CERTIFICATE_REQUESTS (
  REQ_ID STRING PRIMARY KEY,
  SUBJECT_REF STRING,
  SCOPE VARIANT,
  STATUS STRING DEFAULT 'PENDING',
  REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

