USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLIANCE_CHECKS (
  CHECK_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  CHECK_JSON VARIANT,
  RESULT STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

