USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_USAGE_REPORTS ( REPORT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, USAGE JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

