USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.LAYOUT_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, DEFINITION VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

