USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_MAINTENANCE_WINDOWS (
  WINDOW_ID STRING PRIMARY KEY,
  NAME STRING,
  START_AT TIMESTAMP_LTZ,
  END_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

