USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_NOTIFICATIONS (
  NOTIF_ID STRING PRIMARY KEY,
  WINDOW_ID STRING,
  MESSAGE CLOB,
  SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

