USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MAINTENANCE_POSTMORTEMS (
  PM_ID STRING PRIMARY KEY,
  WINDOW_ID STRING,
  SUMMARY CLOB,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

