USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CAPACITY_ALLOCATION_LOG (
  LOG_ID STRING PRIMARY KEY,
  PROFILE_ID STRING,
  ALLOC_JSON VARIANT,
  ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

