USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_EVENTS (
  EVT_ID STRING PRIMARY KEY,
  RULE_ID STRING,
  TARGET_REF STRING,
  OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); -- @1

