USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_QUOTA_OVERRIDES (
  OVERRIDE_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  QUOTA_JSON VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
); -- @1

