USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUOTA_VIOLATION_ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  TENANT_ID STRING,
  QUOTA_KEY STRING,
  TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  DETAILS VARIANT
); -- @1

