USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_QUEUE ( Q_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, BILL_REF STRING, REASON CLOB, STATUS STRING DEFAULT 'OPEN', FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

