USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDERING_COST_ESTIMATES ( EST_ID STRING PRIMARY KEY, JOB_ID STRING, ESTIMATE JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

