USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_ADJUSTMENT_LOGS ( LOG_ID STRING PRIMARY KEY, INVOICE_ID STRING, ADJ_JSON VARIANT, ADJUSTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

