USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_BILLING_PROFILES ( PROFILE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, PAYMENT_METHOD JSON, BILLING_ADDR VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

