USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_COST_CENTER_MAP ( MAP_ID STRING PRIMARY KEY, TENANT_ID STRING, COST_CENTER STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

