USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_CHURN_RISK ( RISK_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, RISK_SCORE NUMBER, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

