USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_REENGAGEMENT_QUEUE ( Q_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, CAMPAIGN_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

