USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPERIMENTATION_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, EXP_ID STRING, SUBJECT_REF STRING, VARIANT STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

