USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AB_TEST_ROLLUP ( ROLL_ID STRING PRIMARY KEY, EXP_ID STRING, AGG_METRICS VARIANT, ROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

