USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRODUCT_USAGE_ANCHORS ( ANCHOR_ID STRING PRIMARY KEY, TENANT_ID STRING, ANCHOR_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

