USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_ACTIVITY_HEATMAP ( HM_ID STRING PRIMARY KEY, SUBJECT_REF STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, BUCKETS VARIANT );

