USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ALERT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, OPERATOR_REF STRING, ALERT_CRITERIA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

