USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDERING_QUOTA_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, THRESHOLD NUMBER, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

