USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RUNBOOK_EXECUTION_STEPS ( STEP_ID STRING PRIMARY KEY, EXEC_ID STRING, STEP_INDEX INT, STATUS STRING, DETAIL VARIANT, EXECUTED_AT TIMESTAMP_LTZ ); @31

