USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_FEEDBACK_QUEUE ( FEED_ID STRING PRIMARY KEY, OPERATOR STRING, FEEDBACK CLOB, STATUS STRING DEFAULT 'PENDING', SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

