USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.RENDERING_SLA_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, JOB_ID STRING, SLA_ID STRING, DETAILS VARIANT, VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

