USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_IMAGE_ASSET_REQUESTS ( REQ_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ASSET_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

