USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_ENGINE_NODE_PROVISIONING ( PROV_ID STRING PRIMARY KEY, NODE_ID STRING, ACTION STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

