USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_INDEX_MAINTENANCE ( MAINT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACTION STRING, SCHEDULED_AT TIMESTAMP_LTZ, COMPLETED_AT TIMESTAMP_LTZ );

