USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ERROR_RATES ( ERR_ID STRING PRIMARY KEY, PROVIDER_ID STRING, ERROR_RATE NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ ); @31 @24

