USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OPT_OUT_REGISTRY ( OPT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SUBJECT_REF STRING, OPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

