USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_USAGE_QUOTA ( QUOTA_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LIMIT INT, PERIOD STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

