USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_QUOTA_BREACH_QUEUE ( Q_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CURRENT_USAGE INT, LIMIT INT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

