USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETIREMENT_PLANS ( PLAN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RETIRE_AT TIMESTAMP_LTZ, NOTICE_CLOB CLOB );

