USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RETIREMENT_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, PLAN_ID STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SENT_TO ARRAY );

