USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_CHECKS ( CHECK_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHECK_NAME STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

