USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNERSHIP_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PREV_OWNER STRING, NEW_OWNER STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
