USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PUBLISHER_REGISTRY ( PUB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PUBLISHER_REF STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
