USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CONTRACT_BINDINGS ( BIND_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CONTRACT_REF STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
