USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VENDOR_CREDENTIAL_STORE ( CRED_ID STRING PRIMARY KEY, VENDOR_REF STRING, CRED_META VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
