USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_INTEGRATION_HEALTH ( HEALTH_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, INTEGRATION_NAME STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
