USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REVIEW_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, ASSIGN_ID STRING, AUTHOR STRING, COMMENT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

