USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_PREVIEW_CACHE ( CACHE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PREVIEW_LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
