USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PREVIEW_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, ACCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT
);
