USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_NOTIFICATION_HISTORY ( HIST_ID STRING PRIMARY KEY, PREF_ID STRING, NOTIF_ID STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
