USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_NOTIFICATION_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SUBSCRIBER STRING, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
