USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_NOTIFICATION_EVENTS ( EVT_ID STRING PRIMARY KEY, SUB_ID STRING, EVENT_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
