USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CONTRIBUTOR_PERMISSIONS ( PERM_ID STRING PRIMARY KEY, CONTRIB_ID STRING, PERMISSIONS ARRAY, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
