USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CONTENT_SIGNATURES ( SIG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SIGNATURE_HASH STRING, SIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
