USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUALITY_ASSURANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, NAME STRING, RULE JSON, LAST_RUN_AT TIMESTAMP_LTZ, LAST_RESULT VARIANT ); @31

