USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_POLICY_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, POLICY_ID STRING, ACTION JSON, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
