USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_POLICY_VERSION_HISTORY ( VER_ID STRING PRIMARY KEY, POLICY_ID STRING, VERSION_NUMBER INT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
