USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_STALENESS_WARNINGS ( WARN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, WARNING_TEXT CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
