USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVIEW_ASSIGNMENT_LOGS ( LOG_ID STRING PRIMARY KEY, RULE_ID STRING, ASSIGNED_TO STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
