USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_OWNER_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, OWNER_REF STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
