USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MAINTENANCE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, PROVIDER_ID STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, RECURRING JSON ); @31 @24

