USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_SESSION_REPLAYS ( REPLAY_ID STRING PRIMARY KEY, SESSION_ID STRING, REPLAY_PAYLOAD VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

