USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_STATUS_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, PROVIDER_ID STRING, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @31 @24

