USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_RENDER_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, RENDER_ENGINE STRING, LATENCY_MS NUMBER, RENDERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

