USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_OPT_IN_AUDIT ( AUDIT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, OPT_IN BOOLEAN, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

