USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_VERSIONS ( VER_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNATURE_ID STRING, VERSION_NUMBER INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

