USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVIDENCE_CHUNKS ( CHUNK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHUNK_INDEX INT, PAYLOAD VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

