USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CERT_PEM CLOB, IMPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

