USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVENANCE_VERIFICATION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT STRING, DETAILS VARIANT ); -- @31

