USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN; @31 @24
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_TRUST_ANCHORS ( ANCHOR_ID STRING PRIMARY KEY, PROVIDER_ID STRING, META VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31 @24

