USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECK_JSON VARIANT, RESULT STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

