USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDED_OCR_TEXT_STORE ( OCR_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PAGE_NUMBER INT, OCR_TEXT CLOB, EXTRACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

