USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCR_SEARCH_QUERIES ( Q_ID STRING PRIMARY KEY, QUERY_TEXT STRING, RESULT_REF STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

