USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCR_SEARCH_METRICS ( MET_ID STRING PRIMARY KEY, QUERY_TEXT STRING, LATENCY_MS NUMBER, RESULT_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

