USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VARIANT_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, VAR_ID STRING, ACCOUNT_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

