USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_VARIANT_ROLLOUT_QUEUE ( Q_ID STRING PRIMARY KEY, VAR_ID STRING, TARGET_ACCOUNTS ARRAY, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

