USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_TELEMETRY_AGGREGATES ( AGG_ID STRING PRIMARY KEY, SCOPE STRING, AGG_PAYLOAD VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

