USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_TEMPLATE_ENTITLEMENTS ( ENT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TEMPLATE_ID STRING, ENT_JSON VARIANT, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

