USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_MATERIALS ( MAT_ID STRING PRIMARY KEY, TITLE STRING, CONTENT CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

