USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_FINGERPRINTS ( FP_ID STRING PRIMARY KEY, SIGNER_ID STRING, DEVICE_TYPE STRING, FINGERPRINT_HASH STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

