USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ATTEMPTS ( ATTEMPT_ID STRING PRIMARY KEY, SIGNATURE_REQUEST_ID STRING, SIGNER_ID STRING, ATTEMPT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT STRING, DETAILS VARIANT ); @1

