USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_THREAT_EVENTS ( EVENT_ID STRING PRIMARY KEY, SIGNER_ID STRING, DOCUMENT_ID STRING, EVENT_TYPE STRING, EVENT_PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

