USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, POLICY_ID STRING, DOCUMENT_ID STRING, RESULT STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

