USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_POLICY_COMPLIANCE_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, CHECK_ID STRING, SEVERITY STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

