USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_BACKOFF_EVENTS ( EVENT_ID STRING PRIMARY KEY, PROFILE_ID STRING, ENDPOINT STRING, LAST_ATTEMPT_AT TIMESTAMP_LTZ, ATTEMPT_COUNT INT );

