USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, MAT_ID STRING, OPERATOR STRING, STATUS STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

