USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_OCSP_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, CERT_ID STRING, OCSP_JSON VARIANT, POLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

