USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, VERIFY_ID STRING, DOCUMENT_ID STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

