USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_ERRORS ( ERR_ID STRING PRIMARY KEY, VERIFY_ID STRING, ERROR_CODE STRING, DETAILS VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

