USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_RETRY_QUEUE ( Q_ID STRING PRIMARY KEY, VERIFY_ID STRING, NEXT_RETRY_AT TIMESTAMP_LTZ, ATTEMPT_COUNT INT DEFAULT 0 ); @1

