USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_POLICY_METRICS ( MET_ID STRING PRIMARY KEY, POLICY_ID STRING, PASSED INT, FAILED INT, SAMPLE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

