USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VERIFICATION_LATENCY_BREAKDOWN ( MET_ID STRING PRIMARY KEY, VERIFY_PATH STRING, P50_MS NUMBER, P95_MS NUMBER, P99_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

