USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_IMAGE_STORE ( IMAGE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SIGNER_ID STRING, IMAGE_LOCATION STRING, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

