USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_IMAGE_HASH_INDEX ( IDX_ID STRING PRIMARY KEY, IMAGE_ID STRING, HASH STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

