USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HANDWRITING_MODELS ( MODEL_ID STRING PRIMARY KEY, NAME STRING, VERSION STRING, META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

