USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HANDWRITING_SCORES ( SCORE_ID STRING PRIMARY KEY, IMAGE_ID STRING, MODEL_ID STRING, SCORE NUMBER, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

