USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_FALLBACKS ( FB_ID STRING PRIMARY KEY, REQUEST_ID STRING, METHOD_ORDER ARRAY, TRIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

