USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VIEW_ACCESS_LOGS ( LOG_ID STRING PRIMARY KEY, VIEW_NAME STRING, SUBJECT_REF STRING, ACCESS_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

