USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AML_CHECK_REQUESTS ( REQ_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REQUEST_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

