USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_QUARANTINE_QUEUE ( Q_ID STRING PRIMARY KEY, REQUEST_ID STRING, REASON STRING, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'QUARANTINED' ); @1

