USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ESCALATION_LOG ( LOG_ID STRING PRIMARY KEY, Q_ID STRING, ESCALATED_TO STRING, REASON CLOB, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

