USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_KPI_WEEKLY ( KPI_ID STRING PRIMARY KEY, OP_REF STRING, METRICS VARIANT, WEEK_START DATE, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

