USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERTIFICATIONS ( CERT_ID STRING PRIMARY KEY, OP_REF STRING, CERT_NAME STRING, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

