USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_LOG_ARCHIVE_INDEX ( IDX_ID STRING PRIMARY KEY, AUDIT_REF STRING, ARCHIVE_LOCATION STRING, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

