USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WORKER_DISPATCH_LOG ( LOG_ID STRING PRIMARY KEY, WORKER_REF STRING, TASK_REF STRING, DISPATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @31

