USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_PLAN_CACHE ( PLAN_ID STRING PRIMARY KEY, QUERY_HASH STRING, PLAN VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

