USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_DATA_MASKING_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, MASKING_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

