USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_MASKING_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGET_TABLE STRING, TARGET_COLUMN STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

