USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_MASKING_APPLICATION_LOGS ( LOG_ID STRING PRIMARY KEY, ASSIGN_ID STRING, QUERY_TEXT CLOB, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @1

