USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WORKER_ERROR_STATS ( STAT_ID STRING PRIMARY KEY, WORKER_REF STRING, ERROR_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

