USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DELIVERY_HISTORY ( DELIVERY_ID STRING PRIMARY KEY, POLICY_ID STRING, DESTINATION STRING, STATUS STRING, DELIVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
