USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PLAYBOOK_LINKS ( LINK_ID STRING PRIMARY KEY, PLAYBOOK_ID STRING, OPERATOR_REF STRING, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
