USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.JOB_BACKLOG_STATS ( STAT_ID STRING PRIMARY KEY, QUEUE_ID STRING, PENDING_COUNT INT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

