USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SETTINGS ( SETTING_ID STRING PRIMARY KEY, TENANT_ID STRING, SETTING_KEY STRING, SETTING_VALUE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

