USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_INDEX ( IDX_ID STRING PRIMARY KEY, REQ_ID STRING, TARGET_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
