USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_POSTURE ( POSTURE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCORE NUMBER, DETAILS VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
