USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_RECOMMENDATIONS ( REC_ID STRING PRIMARY KEY, POSTURE_ID STRING, RECOMMENDATION CLOB, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
