USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_ACTION_QUEUE ( Q_ID STRING PRIMARY KEY, REC_ID STRING, ASSIGNED_TO STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
