USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_HEALTH_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, CHECK_ID STRING, SEVERITY STRING, DESCRIPTION CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
