USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACCESS_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, OPERATOR_REF STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
