USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_OUTAGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, REPORT_ID STRING, SENT_TO ARRAY, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
-- @31 @54
