USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RESILIENCE_HISTORY ( HIST_ID STRING PRIMARY KEY, TEST_ID STRING, PROVIDER STRING, SUMMARY VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
