USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TOKEN_ROTATION_HISTORY ( ROT_ID STRING PRIMARY KEY, TOKEN_REF STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ROTATED_BY STRING );

