USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_HISTORY_MV ( MV_ID STRING PRIMARY KEY, ALERT_ID STRING, POLICY_ID STRING, SEVERITY STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
