USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CASE_WORKFLOW ( CASE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CURRENT_STEP STRING, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
