USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CASE_WORKFLOW_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CASE_ID STRING, FROM_STEP STRING, TO_STEP STRING, TRANSITIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
