USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_RETENTION_AUDITS ( AUDIT_ID STRING PRIMARY KEY, TARGET_TABLE STRING, ACTION STRING, PERFORMED_BY STRING, AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

