USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_SESSION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ADMIN_USER STRING, SESSION_REF STRING, ACTION STRING, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

