USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_ONBOARDING_FUNNEL ( FUNNEL_ID STRING PRIMARY KEY, TENANT_ID STRING, STAGES VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @54
