USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_REPORTS ( REPORT_ID STRING PRIMARY KEY, OP_REF STRING, SHIFT_START TIMESTAMP_LTZ, SHIFT_END TIMESTAMP_LTZ, METRICS VARIANT );
-- @31 @54
