USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATECARDS ( RATECARD_ID STRING PRIMARY KEY, PROVIDER STRING, RATE_JSON VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

