USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RATECARD_HISTORY ( HIST_ID STRING PRIMARY KEY, RATECARD_ID STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), CHANGE_META VARIANT ); -- @31

