USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CREDENTIALS ( CRED_ID STRING PRIMARY KEY, SERVICE_ID STRING, CRED_META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

