USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_PERMISSION_TOKENS ( TOKEN_ID STRING PRIMARY KEY, SUBJECT_REF STRING, PERMISSIONS VARIANT, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

