USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_PERMISSION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TOKEN_ID STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @31

