USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STREAMING_INGEST_OFFSETS ( OFFSET_ID STRING PRIMARY KEY, STREAM_NAME STRING, OFFSET_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

