USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.STREAMING_INGEST_LAG ( LAG_ID STRING PRIMARY KEY, STREAM_NAME STRING, LAG_SECONDS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

