USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_MAINTENANCE_LOGS ( LOG_ID STRING PRIMARY KEY, MAINT_ID STRING, ENTRY JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

