USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_SCHEDULE ( SCHED_ID STRING PRIMARY KEY, TEAM_REF STRING, ONCALL_JSON VARIANT, EFFECTIVE_FROM DATE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

