USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INCIDENT_POSTMORTEM_INDEX ( IDX_ID STRING PRIMARY KEY, INCIDENT_ID STRING, SUMMARY CLOB, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

