USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POSTMORTEM_ACTION_ITEMS ( ITEM_ID STRING PRIMARY KEY, INCIDENT_ID STRING, ACTION_JSON VARIANT, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

