USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_REPORTING_JOBS ( JOB_ID STRING PRIMARY KEY, REPORT_NAME STRING, SCOPE VARIANT, SCHEDULE STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

