USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENFORCEMENT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, POLICY_ID STRING, EXECUTED_BY STRING, ACTION_DETAIL VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

