USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_AUDIT_INDEX ( IDX_ID STRING PRIMARY KEY, REG_REF STRING, SUMMARY VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

