USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ORG_WIDE_POLICY_CATALOG ( POLICY_ID STRING PRIMARY KEY, NAME STRING, BODY VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

