USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

