USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ASSIGNMENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ASSIGN_ID STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

