USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DISMISSAL_LOGS ( LOG_ID STRING PRIMARY KEY, ALERT_ID STRING, DISMISSED_BY STRING, REASON CLOB, DISMISSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

