USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INCIDENT_HISTORY ( INCIDENT_ID STRING PRIMARY KEY, PROVIDER STRING, DESCRIPTION CLOB, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ, DETAILS VARIANT ); -- @31

