USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SENSITIVE_FIELD_INVENTORY ( FIELD_ID STRING PRIMARY KEY, TABLE_NAME STRING, COLUMN_NAME STRING, SENSITIVITY_LEVEL STRING, DISCOVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

