USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LINEAGE_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, STATUS STRING, DETAILS VARIANT, RECONCILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

