USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LINEAGE_ANOMALIES ( ANOMALY_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, DESCRIPTION CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

