USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_LATENCY_METRICS ( MET_ID STRING PRIMARY KEY, TENANT_ID STRING, P50_MS NUMBER, P95_MS NUMBER, P99_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

