USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CACHE_INDEX ( CACHE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CACHE_META VARIANT, EXPIRES_AT TIMESTAMP_LTZ ); -- @31

