USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CACHE_HITS ( HIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, ACCOUNT_ID STRING, HIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

