USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_CANARY_RUNS ( RUN_ID STRING PRIMARY KEY, MODEL_ID STRING, SAMPLE VARIANT, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

