USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_RETRY_POLICIES ( POLICY_ID STRING PRIMARY KEY, AGENT_ID STRING, POLICY_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

