USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_EVENT_SCHEMA_REGISTRY ( SCHEMA_ID STRING PRIMARY KEY, NAME STRING, SCHEMA_JSON VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

