USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_LOG_INGEST_QUEUE ( Q_ID STRING PRIMARY KEY, PAYLOAD VARIANT, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'PENDING' ); -- @31

