USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_ENTRIES ( ENTRY_ID STRING PRIMARY KEY, FEED_ID STRING, INDICATOR STRING, DETAILS VARIANT, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

