USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOT_FILES ( FILE_ID STRING PRIMARY KEY, MANIFEST_ID STRING, LOCATION STRING, CHECKSUM STRING, SIZE_BYTES NUMBER );

