USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REPUTATION_SCORES ( SCORE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCORE NUMBER, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

