USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RECONCILIATION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, BILLING_RUN_ID STRING, REASON CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

