USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_BILLING_DISPUTES ( DISPUTE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, BILLING_RUN_ID STRING, STATUS STRING DEFAULT 'OPEN', FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

