USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_BILLING_RESOLUTION ( RES_ID STRING PRIMARY KEY, DISPUTE_ID STRING, OUTCOME JSON, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

