USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_DELIVERY_METRICS ( MET_ID STRING PRIMARY KEY, BILLING_RUN_ID STRING, DELIVERY_STATS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

