USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INTEGRATION_HEARTBEAT ( HB_ID STRING PRIMARY KEY, PROVIDER STRING, STATUS STRING, LAST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

