USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_USAGE_QUOTA ( QUOTA_ID STRING PRIMARY KEY, CLIENT_ID STRING, LIMITS VARIANT, WINDOW STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

