USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_VIOLATION_LOGS ( LOG_ID STRING PRIMARY KEY, CLIENT_ID STRING, VIOLATION_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31

