USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_TELEMETRY_INDEXES ( IDX_ID STRING PRIMARY KEY, METRIC_NAME STRING, LAST_UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); @31

