USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_OF_CUSTODY ( COC_ID STRING PRIMARY KEY, BUNDLE_ID STRING, EVENT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

