USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_TREATMENT_PROGRESS ( PROG_ID STRING PRIMARY KEY, PLAN_ID STRING, PROGRESS_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

