USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, PROVIDER STRING, RESULTS VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

