USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTODY_TRANSFER_EVENTS ( EVT_ID STRING PRIMARY KEY, COC_ID STRING, TRANSFERRED_TO STRING, TRANSFERRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

