USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, SERVICE_REF STRING, REQUESTOR STRING, CHANGE_JSON VARIANT, STATUS STRING DEFAULT 'OPEN', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

