USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CHANGE_APPROVALS ( APP_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, APPROVED_AT TIMESTAMP_LTZ, COMMENTS CLOB );

