USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPLOYMENT_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, DEPLOY_REF STRING, ACTOR STRING, ACTION STRING, ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

