USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSIC_RETENTION_INDEX ( IDX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RETENTION_UNTIL TIMESTAMP_LTZ, REASON STRING );

