USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CONFLICT_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, LOG_ID STRING, RESOLUTION_JSON VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

