USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPRECATION_SCHEDULE ( SCHED_ID STRING PRIMARY KEY, SERVICE_REF STRING, DEPRECATION_DATE DATE, NOTICE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

