USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPRECATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SCHED_ID STRING, SENT_TO ARRAY, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

