USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_FEATURE_USAGE_SUMMARY ( SUM_ID STRING PRIMARY KEY, TENANT_ID STRING, PERIOD_START DATE, PERIOD_END DATE, METRICS VARIANT );

