USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_RISK_REGISTER ( RISK_ID STRING PRIMARY KEY, TITLE STRING, DESCRIPTION CLOB, LIKELIHOOD STRING, IMPACT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

