USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_OWNERSHIP_REGISTRY ( OWN_ID STRING PRIMARY KEY, SERVICE_REF STRING, OWNERS ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

