USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_ONCALL_ROTATIONS ( ROT_ID STRING PRIMARY KEY, SERVICE_REF STRING, ROTATION JSON, EFFECTIVE_FROM DATE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

