USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_HEALTH_REPORT_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SERVICE_REF STRING, METRICS VARIANT, SNAPSHOT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

