USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEBT_REGISTRY ( DEBT_ID STRING PRIMARY KEY, SERVICE_REF STRING, DESCRIPTION CLOB, PRIORITY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

