USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_KPI_ACHIEVEMENTS ( ACH_ID STRING PRIMARY KEY, KPI_ID STRING, PERIOD_START DATE, PERIOD_END DATE, METRICS VARIANT );

