USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRODUCT_FEEDBACK_QUEUE ( FB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, FEEDBACK CLOB, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

