USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_RUN_CAPACITY ( CAP_ID STRING PRIMARY KEY, SERVICE_REF STRING, CAPACITY_METRICS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

