USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PROVIDER STRING, TERMS VARIANT, STARTED_AT TIMESTAMP_LTZ, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

