USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONTRACT_CHANGES ( CHANGE_ID STRING PRIMARY KEY, CONTRACT_ID STRING, CHANGE_JSON VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

