USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_BLOCKERS ( BLOCKER_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, DESCRIPTION CLOB, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'OPEN' );

