USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONBOARDING_BLOCKER_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, BLOCKER_ID STRING, RESOLUTION_JSON VARIANT, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

