USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_PRIVILEGE_CHANGES ( CHANGE_ID STRING PRIMARY KEY, USER_REF STRING, OLD_PRIVS VARIANT, NEW_PRIVS VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

