USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_SIMILARITY_INDEX ( IDX_ID STRING PRIMARY KEY, CLAUSE_ID STRING, EMBEDDING VECTOR, INSERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

