USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REPLACEMENT_SUGGESTIONS ( SUG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SUGGESTION_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

