USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_ASSURANCE_CERTIFICATES ( CERT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CERT_META VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

