USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_ASSURANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, CERT_ID STRING, RESULT JSON, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

