USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BEHAVIORAL_PROFILES ( PROFILE_ID STRING PRIMARY KEY, SIGNER_ID STRING, BEHAVIOR_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

