USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIMILARITY_CLUSTERS ( CLUSTER_ID STRING PRIMARY KEY, MEMBERS ARRAY, CENTROID VECTOR, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

