USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_USAGE ( USG_ID STRING PRIMARY KEY, TENANT_ID STRING, QUERY TEXT, HIT_COUNT INT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

