USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEGRADATION_INCIDENTS ( INCIDENT_ID STRING PRIMARY KEY, SERVICE_ID STRING, DESCRIPTION STRING, SEVERITY STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED_AT TIMESTAMP_LTZ );

