USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_COST_ESTIMATES ( EST_ID STRING PRIMARY KEY, QUERY_HASH STRING, COST_ESTIMATE VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

