USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOCATION_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, ALLOC_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

