USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_REVOCATION_INDEX ( IDX_ID STRING PRIMARY KEY, CERT_ID STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

