USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHORING_TX_INDEX ( TX_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHAIN_REF STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

