USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CREDENTIAL_ROTATION_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ROT_ID STRING, ACTION STRING, ACTIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

