USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTI_TENANT_ISOLATION_MATRIX ( MATRIX_ID STRING PRIMARY KEY, TENANT_ID STRING, ISOLATION_CONFIG VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

