USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPENDENCY_MAP ( EDGE_ID STRING PRIMARY KEY, FROM_SERVICE STRING, TO_SERVICE STRING, RELATION_TYPE STRING, META VARIANT );

