USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_QUOTA_ENFORCEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

