USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HEARTBEAT_MONITORING_PROFILES ( PROFILE_ID STRING PRIMARY KEY, NAME STRING, CHECKS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

