USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_BREACH_EVENTS ( EVENT_ID STRING PRIMARY KEY, SLO_ID STRING, SERVICE_REF STRING, DETAILS VARIANT, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

