USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECOVERY_POINT_CHECKPOINTS ( CP_ID STRING PRIMARY KEY, REPO_REF STRING, SNAPSHOT_LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

