USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_TELEMETRY_TRACES ( TRACE_ID STRING PRIMARY KEY, FEATURE_NAME STRING, TRACE_JSON VARIANT, TRACE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

