USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_HEALTH_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, FEATURE_NAME STRING, PERIOD_START DATE, PERIOD_END DATE, METRICS VARIANT );

