USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEGRADATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, FEATURE_NAME STRING, METRICS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

