USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_PROFILE_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, CHANGE_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

