USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_REVISION_HISTORY ( REV_ID STRING PRIMARY KEY, POLICY_ID STRING, DIFF JSON, REVISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

