USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ONCALL_ACK_LOG ( ACK_ID STRING PRIMARY KEY, NOTIF_ID STRING, ACK_BY STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

