USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLATFORM_SECURITY_ANNOUNCEMENTS ( ANN_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, SEVERITY STRING, PUBLISHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

