USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CERTIFICATION_INDEX ( IDX_ID STRING PRIMARY KEY, PROVIDER STRING, CERTIFICATIONS VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

