USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, REQ_ID STRING, RESULT JSON, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

