USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GDPR_DATA_EXPORT_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, EXPORT_LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

