USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GDPR_DATA_ERASURE_INDEX ( IDX_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ERASURE_STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

