USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_FAILURE_PATTERNS ( PATTERN_ID STRING PRIMARY KEY, CHANNEL STRING, PATTERN_JSON VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

