USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERTIFICATION_COMPLETIONS ( COMP_ID STRING PRIMARY KEY, REQ_ID STRING, PROVIDER STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

