USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LIFECYCLE_EVENT_SUBSCRIPTIONS ( SUB_ID STRING PRIMARY KEY, EVENT_TYPE STRING, DESTINATION VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

