USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LIFECYCLE_EVENT_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, SUB_ID STRING, EVENT_REF STRING, STATUS STRING, DELIVERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

