USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LIFECYCLE_EVENT_RETRY_QUEUE ( Q_ID STRING PRIMARY KEY, LOG_ID STRING, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

