USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_BREACH_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SLO_ID STRING, METRIC JSON, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

