USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HELPDESK_TICKETS ( TICKET_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SUBJECT STRING, DESCRIPTION CLOB, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

