USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HELPDESK_TICKET_UPDATES ( UPDATE_ID STRING PRIMARY KEY, TICKET_ID STRING, UPDATE_BY STRING, NOTE CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

