USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_CAPACITY_PLANS ( PLAN_ID STRING PRIMARY KEY, FEATURE_NAME STRING, TENANT_ID STRING, PLAN_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

