USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_REMEDIATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, SLO_ID STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );

