USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_CONSENT_BINDINGS ( BIND_ID STRING PRIMARY KEY, SESSION_ID STRING, CONSENT_ID STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

