USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_DEVICE_CHECKS ( CHECK_ID STRING PRIMARY KEY, SESSION_ID STRING, DEVICE_JSON VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

