USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_RISK_DECISIONS ( DEC_ID STRING PRIMARY KEY, SESSION_ID STRING, DECISION_JSON VARIANT, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

