USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_FAILURE_RETRIES ( RETRY_ID STRING PRIMARY KEY, TASK_ID STRING, FAILURE_JSON VARIANT, RETRY_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ATTEMPT INT );

