USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_NOTIFICATION_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, NOTIF_ID STRING, CHANNEL STRING, OUTCOME JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

