USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TASK_DEADLETTER_QUEUE ( DLQ_ID STRING PRIMARY KEY, TASK_ID STRING, PAYLOAD VARIANT, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON STRING );

