USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIPTION_CHANGE_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, EVENT_ID STRING, STATUS STRING, DETAILS VARIANT, RECONCILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

