USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THRESHOLD_VIOLATION_ALERTS ( ALERT_ID STRING PRIMARY KEY, THRESH_ID STRING, TENANT_ID STRING, METRICS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

