USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_QUOTA_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, STATUS STRING, DETAILS VARIANT, RECONCILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

