USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_QUOTA_ALERT_HISTORY ( HIST_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, ALERT_JSON VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

