USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, PROVIDER STRING, DETAILS VARIANT, VIOLATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

