USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_AFFILIATION_INDEX ( IDX_ID STRING PRIMARY KEY, SIGNER_ID STRING, AFFILIATION_JSON VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

