USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DLQ_REPROCESS_LOG ( LOG_ID STRING PRIMARY KEY, DLQ_ID STRING, ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING, NOTES CLOB );

