USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_IDENTITY_VALIDATION_LOGS ( LOG_ID STRING PRIMARY KEY, SIGNER_ID STRING, VALIDATOR STRING, OUTCOME JSON, VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

