USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_TRUST_TRANSITIONS ( TRANS_ID STRING PRIMARY KEY, SIGNER_ID STRING, FROM_SCORE NUMBER, TO_SCORE NUMBER, TRANSITIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

