USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRUST_HISTORY_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SNAPSHOT_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

