USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_QUALITY_AUDITS ( AUDIT_ID STRING PRIMARY KEY, OP_REF STRING, AUDIT_JSON VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

