USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_CHANGE_AUDITS ( AUDIT_ID STRING PRIMARY KEY, REQ_ID STRING, ACTOR STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

