USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_TYPE_MAPPINGS ( MAP_ID STRING PRIMARY KEY, TYPE_ID STRING, PROVIDER STRING, MAPPING_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

