USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDENTITY_PROVIDER_CHECK_JOBS ( JOB_ID STRING PRIMARY KEY, IDP_ID STRING, STATUS STRING DEFAULT 'PENDING', SCHEDULED_AT TIMESTAMP_LTZ );

