USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_TRUST_BAND_DEFINITIONS ( BAND_ID STRING PRIMARY KEY, NAME STRING, CRITERIA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

