USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_REVISION_APPROVALS ( APP_ID STRING PRIMARY KEY, REVISION_ID STRING, APPROVER STRING, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), COMMENTS CLOB );

