USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RECONCILIATION_JOBS ( JOB_ID STRING PRIMARY KEY, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, STATUS STRING, STARTED_AT TIMESTAMP_LTZ );

