USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_ANOMALY_ALERTS ( ALERT_ID STRING PRIMARY KEY, TENANT_ID STRING, METRICS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

