USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_RECONCILIATION_ITEMS ( ITEM_ID STRING PRIMARY KEY, JOB_ID STRING, LINE_REF STRING, EXPECTED_AMOUNT NUMBER, ACTUAL_AMOUNT NUMBER, STATUS STRING );

