USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BLACKLIST_APPEALS ( APPEAL_ID STRING PRIMARY KEY, BL_ID STRING, APPELLANT STRING, STATUS STRING DEFAULT 'OPEN', SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

