USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CAPACITY_CLAIM_RESPONSES ( RESP_ID STRING PRIMARY KEY, CLAIM_ID STRING, RESPONSE_JSON VARIANT, RESPONDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

