USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ONBOARDING_READINESS ( READ_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, COMPONENTS VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

