USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ONBOARDING_READINESS_ACTIONS ( ACTION_ID STRING PRIMARY KEY, READ_ID STRING, ACTION_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

