USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_TRAINING_ENROLLMENTS ( ENROLL_ID STRING PRIMARY KEY, OP_REF STRING, TRAINING_ID STRING, ENROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

