USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BEHAVIORAL_INSIGHT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, INSIGHT_ID STRING, ACTION_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

