USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CONFIDENCE_SCORES ( SCORE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE NUMBER, DETAILS VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

