USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_INTEGRITY_MONITORING ( MON_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECKS VARIANT, LAST_CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

