USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_AUTOREPAIR_JOBS ( JOB_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, REPAIR_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

