USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_MIGRATION_JOBS ( JOB_ID STRING PRIMARY KEY, SOURCE_TENANT STRING, DEST_TENANT STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

