USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, BUNDLE_ID STRING, PROVIDER STRING, TX_REF STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
