USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_JOB_QUEUE ( JOB_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TEMPLATE_ID STRING, STATUS STRING DEFAULT 'PENDING', PRIORITY NUMBER DEFAULT 5, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

