USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_MANIFEST_INDEX ( MAN_ID STRING PRIMARY KEY, BUNDLE_ID STRING, LOCATION STRING, MANIFEST JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
