USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_MIGRATION_LOGS ( LOG_ID STRING PRIMARY KEY, JOB_ID STRING, STEP STRING, LOG_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

