USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_RETRY_QUEUE ( Q_ID STRING PRIMARY KEY, CALL_REF STRING, PROVIDER_ID STRING, STATUS STRING DEFAULT 'PENDING', NEXT_ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

