USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IDENTITY_VERIFICATION_REQUESTS ( REQ_ID STRING PRIMARY KEY, SIGNER_ID STRING, PROVIDER STRING, PAYLOAD VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

