USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_INHERITANCE_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, PARENT_TEMPLATE_ID STRING, RELATION_TYPE STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
