USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TAXONOMY_TERM_REGISTRY ( TERM_ID STRING PRIMARY KEY, PARENT_ID STRING, NAME STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

