USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_COMPLIANCE_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VIOLATION_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
