USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_FORMAT_VERSIONING ( VER_ID STRING PRIMARY KEY, FORMAT_ID STRING, VERSION INT, SCHEMA VARIANT, RELEASED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

