USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_SIGNAL_ANALYTICS ( ANALYTICS_ID STRING PRIMARY KEY, DEVICE_ID STRING, METRICS VARIANT, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
