USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SENSOR_DATA_AGGREGATES ( AGG_ID STRING PRIMARY KEY, SESSION_ID STRING, AGG_JSON VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
