USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RETENTION_EXEMPTIONS ( EXEMPT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REASON CLOB, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GRANTED_BY STRING );

