USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GEOFENCE_ALERTS ( ALERT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, GEO_JSON VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

