USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_ROLLOUT_FLAGS ( FLAG_ID STRING PRIMARY KEY, FEATURE_NAME STRING, ROLL_OUT JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

