USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_E2E_CHECKS ( CHECK_ID STRING PRIMARY KEY, SESSION_ID STRING, CHECKS_JSON VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
