USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_TELEMETRY_HLL ( HLL_ID STRING PRIMARY KEY, SESSION_ID STRING, HLL BINARY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
