USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_AUTH_FAILURE_STATS ( STAT_ID STRING PRIMARY KEY, SIGNER_ID STRING, FAIL_COUNT NUMBER, LAST_FAILED_AT TIMESTAMP_LTZ );

