USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_POLICY_AUDIT_TRIGGERS ( TRIG_ID STRING PRIMARY KEY, POLICY_ID STRING, TRIGGER_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

