USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SEGMENT_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, SEG_ID STRING, SIGNER_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
