USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SEGMENT_PERFORMANCE ( PERF_ID STRING PRIMARY KEY, SEG_ID STRING, METRICS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
