USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SENSITIVE_FIELD_CATALOG ( FIELD_ID STRING PRIMARY KEY, NAME STRING, DESCRIPTION STRING, SENSITIVITY_LEVEL STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

