USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BEHAVIORAL_MODEL_RETRAIN_JOBS ( JOB_ID STRING PRIMARY KEY, MODEL_ID STRING, CONFIG VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
