USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_RETENTION_INDEX ( IDX_ID STRING PRIMARY KEY, AUDIT_REF STRING, RETENTION_UNTIL TIMESTAMP_LTZ, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

