USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_PROVENANCE_INDEX ( IDX_ID STRING PRIMARY KEY, MODEL_ID STRING, PROVENANCE JSON, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
