USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_CHANGE_VOTES ( VOTE_ID STRING PRIMARY KEY, PROP_ID STRING, VOTER STRING, VOTE STRING, VOTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
