USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ROLLBACK_REQUESTS ( REQ_ID STRING PRIMARY KEY, POLICY_ID STRING, REASON CLOB, REQUESTED_BY STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
