USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_CONFIGURATION_CHANGES ( CHANGE_ID STRING PRIMARY KEY, KEY_NAME STRING, OLD_VALUE VARIANT, NEW_VALUE VARIANT, CHANGED_BY STRING, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
