USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_ROLLBACK_LOGS ( LOG_ID STRING PRIMARY KEY, ROLLOUT_ID STRING, ACTION STRING, ACTOR STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
