USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_DATA_RETENTION_JOBS ( JOB_ID STRING PRIMARY KEY, POLICY_ID STRING, STATUS STRING DEFAULT 'PENDING', SCHEDULED_AT TIMESTAMP_LTZ );
