USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, ACTIONS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
