USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_TELEMETRY_ROLLUPS ( ROLLUP_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, METRICS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
