USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_SUMMARIES ( SUM_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PERIOD_START DATE, PERIOD_END DATE, METRICS VARIANT );
