USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_DISCREPANCY_QUEUE ( Q_ID STRING PRIMARY KEY, BUNDLE_ID STRING, DISCREPANCY_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
