USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BEHAVIOR_SIMILARITY_INDEX ( IDX_ID STRING PRIMARY KEY, SIGNER_ID STRING, EMBEDDING VECTOR, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
