USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISPUTE_ESCALATION_QUEUE ( Q_ID STRING PRIMARY KEY, DISPUTE_ID STRING, ESCALATED_TO STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
