USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SATISFACTION_OUTCOMES ( OUT_ID STRING PRIMARY KEY, ACTION_ID STRING, OUTCOME JSON, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
