USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BREACH_INVESTIGATIONS ( INV_ID STRING PRIMARY KEY, SIGNER_ID STRING, INCIDENT_REF STRING, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
