USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_APPROVAL_WORKFLOW ( WF_ID STRING PRIMARY KEY, MODEL_ID STRING, APPROVAL_JSON VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

