USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REQUESTS ( REQUEST_ID STRING PRIMARY KEY, SCOPE VARIANT, REQUESTED_BY STRING, STATUS STRING DEFAULT 'OPEN', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

