USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SATISFACTION_SURVEYS ( SURVEY_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SURVEY_JSON VARIANT, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

