USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_SCORES ( SCORE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, SCORE NUMBER, METRICS VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

