USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_ALERTS ( ALERT_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, DETAILS VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

