USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERTIFICATION_MATRIX ( MAT_ID STRING PRIMARY KEY, OP_REF STRING, CERTS ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

