USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_TELEMETRY_AGG ( AGG_ID STRING PRIMARY KEY, MODEL_ID STRING, METRIC_NAME STRING, VALUE VARIANT, AGG_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

