USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_REVOCATION_INDEX ( INDEX_ID STRING PRIMARY KEY, CERT_ID STRING, REVOCATION_JSON VARIANT, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

