USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CRYPTOGRAPHIC_AUDIT_INDEX ( AUDIT_ID STRING PRIMARY KEY, ACTION STRING, SUBJECT_REF STRING, DETAILS VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

