USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_MATCHES ( MATCH_ID STRING PRIMARY KEY, FEED_ID STRING, SUBJECT_REF STRING, MATCH_JSON VARIANT, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

