USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_AUDIT_TRAILS ( AUDIT_ID STRING PRIMARY KEY, PROVIDER STRING, ACTION JSON, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

