USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CONFIG_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, PROVIDER STRING, CHANGE_JSON VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'PENDING' );

