USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISTRIBUTION_LIST_ACTIVITY ( ACT_ID STRING PRIMARY KEY, LIST_ID STRING, ACTION JSON, ACTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

