USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BATCH_EXPORT_MANIFESTS ( MAN_ID STRING PRIMARY KEY, SCOPE VARIANT, DESTINATION VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

