USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRAIN_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, MODEL_ID STRING, CRON_EXPR STRING, ENABLED BOOLEAN DEFAULT TRUE, LAST_RUN_AT TIMESTAMP_LTZ );

