USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_VIOLATION_ACKS ( ACK_ID STRING PRIMARY KEY, NOTIF_ID STRING, ACK_BY STRING, ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), COMMENTS CLOB ); @24 @31

