USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_DIGEST_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, DIGEST_ID STRING, STATUS STRING, LAST_CHECK TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @24 @31

