USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_MAINTENANCE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, SCHEDULE_ID STRING, MESSAGE CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @24 @31

