USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_MAINTENANCE_ACKS ( ACK_ID STRING PRIMARY KEY, NOTIF_ID STRING, ACK_BY STRING, ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

