USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CLIENT_USAGE_LOGS ( LOG_ID STRING PRIMARY KEY, CLIENT_ID STRING, ENDPOINT STRING, METHOD STRING, STATUS_CODE INT, LATENCY_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

