USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_MAPPINGS ( MAPPING_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SCHEMA_JSON VARIANT, VERSION INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

