USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_INGEST_MONITOR ( MON_ID STRING PRIMARY KEY, PROVIDER_ID STRING, STATUS STRING, LAST_RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), METRICS VARIANT ); @24 @31

