USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_USAGE_CHARGEBACK ( CHARGE_ID STRING PRIMARY KEY, MODEL_ID STRING, ACCOUNT_ID STRING, AMOUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

