USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TARGET_REF STRING, CHANNEL STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); @24 @31

