USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_NOTIFICATION_RESPONSES ( RES_ID STRING PRIMARY KEY, NOTIF_ID STRING, RESPONSE_JSON VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

