USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TWO_FACTOR_CHALLENGES ( CHALLENGE_ID STRING PRIMARY KEY, SIGNER_ID STRING, METHOD STRING, STATUS STRING DEFAULT 'PENDING', EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

