USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_DEVICE_REGISTRATION_LOGS ( LOG_ID STRING PRIMARY KEY, DEVICE_ID STRING, USER_REF STRING, ACTION STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); @24 @31

