USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_CERT_BINDING ( BIND_ID STRING PRIMARY KEY, DEVICE_ID STRING, CERT_REF STRING, BOUND_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

