USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DELIVERY_METRICS ( MET_ID STRING PRIMARY KEY, CHANNEL STRING, SUCCESS_RATE NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ ); @24 @31

