USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_TRACE_BACKLINKS ( LINK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, RELATED_REF STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

