USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_POLICY_ENFORCEMENT_LOGS ( LOG_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, RESULT JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

