USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_PREVIEW_CACHE ( PREVIEW_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PREVIEW_LOCATION STRING, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @24 @31

