USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_INCIDENT_LOGS ( INCIDENT_ID STRING PRIMARY KEY, SLA_ID STRING, DESCRIPTION CLOB, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESOLVED_AT TIMESTAMP_LTZ );
-- @31 @24
