USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RETENTION_APPLICATIONS ( APP_ID STRING PRIMARY KEY, POLICY_ID STRING, BUNDLE_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
