USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_CHANGE_REGISTER ( CHANGE_ID STRING PRIMARY KEY, JURISDICTION STRING, SUMMARY CLOB, EFFECTIVE_DATE DATE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
