USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_IMPACT_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, CHANGE_ID STRING, SCOPE VARIANT, IMPACT_JSON VARIANT, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
