USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHECKSUM_INDEX ( CK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHECKSUM STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
