USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FAISS_INDEX_SHARDS ( SHARD_ID STRING PRIMARY KEY, INDEX_ID STRING, LOCATION STRING, METADATA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

