USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_CHECKSUM_FAILURES ( FAIL_ID STRING PRIMARY KEY, CK_ID STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
