USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_INTEGRITY_VERIFICATIONS ( VER_ID STRING PRIMARY KEY, AUDIT_REF STRING, RESULT STRING, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
