USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_MAINTENANCE_EVENTS ( EVENT_ID STRING PRIMARY KEY, WINDOW_ID STRING, EVENT_JSON VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
