USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_QUERY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, QUERY_ID STRING, USER_REF STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT_META VARIANT );
