USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELEASE_ROLLOUT_STATUS ( ROLLOUT_ID STRING PRIMARY KEY, NOTE_ID STRING, TENANT_SCOPE VARIANT, STATUS STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
