USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_COMPLETIONS ( COMPLETION_ID STRING PRIMARY KEY, ASSIGN_ID STRING, COMPLETED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), SCORE NUMBER );
-- @31 @24
