USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERTIFICATION_AUDITS ( AUDIT_ID STRING PRIMARY KEY, OP_REF STRING, CERT_ID STRING, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), RESULT JSON );
-- @31 @24
