USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ONBOARDING_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, TENANT_ID STRING, TEMPLATE_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
