USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_ONBOARDING_RUNS ( RUN_ID STRING PRIMARY KEY, TENANT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENDED_AT TIMESTAMP_LTZ );
-- @31 @24
