USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_POLICY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, POLICY_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
