USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_FEATURE_ROLLOUTS ( ROLLOUT_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, CONFIG VARIANT, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );
-- @31 @24
