USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_POLICY_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_ID STRING, REASON CLOB, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
