USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_AUDIT_OVERVIEW ( OVERVIEW_ID STRING PRIMARY KEY, TENANT_ID STRING, SUMMARY VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
