USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_CREDIT_ADJUSTMENTS ( ADJ_ID STRING PRIMARY KEY, TENANT_ID STRING, AMOUNT NUMBER, REASON CLOB, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
