USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_QUEUE ( DISPUTE_ID STRING PRIMARY KEY, INVOICE_REF STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
