USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_NOTIFICATION_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, BODY CLOB, CHANNELS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
