USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_NOTIFICATION_STATS ( STAT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SENT_COUNT NUMBER, FAILURE_COUNT NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
