USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_QUERY_LOGS ( QLOG_ID STRING PRIMARY KEY, QUERY_REF STRING, INPUT_VECTOR VARIANT, RESULTS VARIANT, QUERY_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

