USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INVOICE_ADJUSTMENT_LOGS ( LOG_ID STRING PRIMARY KEY, INVOICE_REF STRING, ADJUSTMENT JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
