USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_BILLING_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, HEALTH_JSON VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
