USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVAL_RETENTION_EXCEPTIONS ( EX_ID STRING PRIMARY KEY, TARGET_REF STRING, REASON CLOB, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GRANTED_BY STRING );
-- @31 @24
