USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ALERT_TRIGGERS ( TRIG_ID STRING PRIMARY KEY, RULE_ID STRING, TRIGGER_JSON VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
