USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_CREDIT_MEMO_REQUESTS ( REQ_ID STRING PRIMARY KEY, INVOICE_REF STRING, AMOUNT NUMBER, REQUESTED_BY STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
