USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_CONTROL_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ACTION STRING, ACTOR STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
-- @31 @24
