USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_SETTLEMENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, SETTLEMENT_REF STRING, DETAILS VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
