USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_POLICY_INSTANCES ( INSTANCE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGET_REF STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

