USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_INCIDENT_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, ALERT_ID STRING, INCIDENT_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

