USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_INCIDENT_RESOLUTIONS ( RES_ID STRING PRIMARY KEY, INCIDENT_ID STRING, RESOLUTION JSON, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

