USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_USAGE_TELEMETRY ( TELE_ID STRING PRIMARY KEY, KEY_REF STRING, USAGE_METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

