USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_FALLBACK_METRICS ( MET_ID STRING PRIMARY KEY, QUERY_REF STRING, USED_FAISS BOOLEAN, RESPONSE_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

