USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_CONSENT_INSTANCES ( CONSENT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SUBJECT_REF STRING, GIVEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

