USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_SCHEDULES ( SCHEDULE_ID STRING PRIMARY KEY, NAME STRING, INTERVAL JSON, NEXT_RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

