USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_RISK_REGISTRY ( TP_ID STRING PRIMARY KEY, NAME STRING, RISK_PROFILE VARIANT, LAST_ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
