USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_ROTATION_POLICIES ( POLICY_ID STRING PRIMARY KEY, PROVIDER_ID STRING, ROTATE_EVERY_DAYS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

