USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_SHARD_MAP ( MAP_ID STRING PRIMARY KEY, SHARD_ID STRING, RANGE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

