USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_ROTATION_JOBS ( JOB_ID STRING PRIMARY KEY, POLICY_ID STRING, STATUS STRING DEFAULT 'PENDING', SCHEDULED_AT TIMESTAMP_LTZ );

