USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_REMEDIATION_QUEUE ( Q_ID STRING PRIMARY KEY, TP_ID STRING, ACTION_JSON VARIANT, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
