USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SHARING_AGREEMENTS ( AGREEMENT_ID STRING PRIMARY KEY, PARTIES VARIANT, TERMS VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31 @24
