USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SHARING_AUDIT ( AUDIT_ID STRING PRIMARY KEY, AGREEMENT_ID STRING, ACTION STRING, ACTOR STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
-- @31 @24
