USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REPLAY_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, SESSION_ID STRING, LOCATION STRING, EXPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

