USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_LOG_IMMUTABILITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, AUDIT_REF STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
-- @31 @24
