USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHAIN_OF_CUSTODY_ENTRIES ( ENTRY_ID STRING PRIMARY KEY, BUNDLE_ID STRING, ACTION STRING, ACTOR STRING, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );
-- @31 @24
