USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_TRUST_SCORES ( SCORE_ID STRING PRIMARY KEY, DEVICE_ID STRING, SCORE NUMBER, FACTORS VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

