USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRANSACTIONAL_AUDIT_ANOMALIES ( ANOM_ID STRING PRIMARY KEY, IDX_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

