USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_HARDENING_EVENTS ( EVENT_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTION JSON, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

