USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_PERFORMANCE_SCORES ( SCORE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SCORES VARIANT, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

