USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_CLASSIFICATION_RUNS ( RUN_ID STRING PRIMARY KEY, MODEL_ID STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

