USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMBEDDING_INGEST_AUDIT ( AUDIT_ID STRING PRIMARY KEY, BATCH_REF STRING, RECORD_COUNT INT, INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING );

