USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_DRIFT_DETECTORS ( DETECTOR_ID STRING PRIMARY KEY, MODEL_ID STRING, CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

