USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_RESOLUTION_LOGS ( LOG_ID STRING PRIMARY KEY, CONFLICT_ID STRING, RESOLUTION JSON, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

