USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LOCALIZATION_CHANGE_LOGS ( LOG_ID STRING PRIMARY KEY, LOC_ID STRING, ACTION JSON, ACTOR STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

