USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_TELEMETRY ( TELE_ID STRING PRIMARY KEY, QUERY_TEXT STRING, USER_REF STRING, LATENCY_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

