USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_POLICY_ENFORCEMENTS ( ENF_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, STATUS STRING, ENFORCED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

