USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYNTHETIC_TEST_RUNS ( RUN_ID STRING PRIMARY KEY, PAYLOAD_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), ENDED_AT TIMESTAMP_LTZ );

