USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEARCH_FEEDBACK ( FB_ID STRING PRIMARY KEY, QUERY_REF STRING, USER_REF STRING, FEEDBACK JSON, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

