USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAFFIC_SHAPING_EVENTS ( EVENT_ID STRING PRIMARY KEY, POLICY_ID STRING, METRICS VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

