USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CONTACT_DIRECTORY ( CONTACT_ID STRING PRIMARY KEY, NAME STRING, ROLE STRING, CONTACT JSON, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

