USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_STORE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, LOCATION STRING, METADATA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

