USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_REWARDS_LOG ( LOG_ID STRING PRIMARY KEY, OP_REF STRING, REWARD_JSON VARIANT, AWARDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

