USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_BLACKLIST ( BL_ID STRING PRIMARY KEY, PROVIDER_ID STRING, REASON CLOB, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

