USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_ROUTING_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CRITERIA VARIANT, ROUTE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

