USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FAILOVER_CONFIGS ( CFG_ID STRING PRIMARY KEY, PRIMARY_PROVIDER STRING, SECONDARY_PROVIDER STRING, SWITCH_RULES VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

