USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_HISTORY ( HIST_ID STRING PRIMARY KEY, OP_REF STRING, ROSTER_ID STRING, ACTION JSON, TIMESTAMP_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

