USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ACTIVITY_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, OP_REF STRING, CONTENT CLOB, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

