USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_COACHING_SESSIONS ( SESSION_ID STRING PRIMARY KEY, OP_REF STRING, TOPICS VARIANT, SCHEDULED_AT TIMESTAMP_LTZ );

