USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANNOTATION_STORE ( ANNO_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PAGE INT, ANNOTATION JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

