USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_DEPENDENCY_GRAPH ( NODE_ID STRING PRIMARY KEY, NODE_REF STRING, DEPENDS_ON ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

