USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_HEALTH_CHECK_CONFIGS ( CFG_ID STRING PRIMARY KEY, NAME STRING, CHECK JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

