USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMERGENCY_CONTACT_LISTS ( LIST_ID STRING PRIMARY KEY, NAME STRING, CONTACTS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

