USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_DOCUMENT_LABELS ( LABEL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, USER_REF STRING, LABEL JSON, LABELED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

