USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_ONCALL_ROTATIONS ( ROTATION_ID STRING PRIMARY KEY, NAME STRING, MEMBERS ARRAY, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

