USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESCALATION_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, LIST_ID STRING, MESSAGE CLOB, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

