USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KPI_DEFINITIONS ( KPI_ID STRING PRIMARY KEY, NAME STRING, DESCRIPTION CLOB, EXPRESSION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

