USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SENSITIVITY_LABELS ( LABEL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, LEVEL STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

