USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_LIFECYCLE_TRANSITIONS ( TRANS_ID STRING PRIMARY KEY, CONTRACT_ID STRING, FROM_STATE STRING, TO_STATE STRING, TRANSITIONED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

