USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_VERSION_DIFF ( DIFF_ID STRING PRIMARY KEY, VERSION_A STRING, VERSION_B STRING, DIFF_JSON VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

