USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_REGISTRY ( HOLD_ID STRING PRIMARY KEY, NAME STRING, SCOPE VARIANT, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING ); -- @24 @31 @56

