USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_EXEMPTIONS ( EX_ID STRING PRIMARY KEY, HOLD_ID STRING, TARGET_REF STRING, REASON CLOB, APPROVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

