USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_INDEX ( ANCHOR_ID STRING PRIMARY KEY, BUNDLE_ID STRING, CHAIN_REF STRING, TX_HASH STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

