USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_VERIFICATIONS ( VER_ID STRING PRIMARY KEY, ANCHOR_ID STRING, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT ); -- @24 @31 @56

