USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_AUDIT_SIGNATURES ( SIG_ID STRING PRIMARY KEY, EXPORT_REF STRING, SIGNER STRING, SIG_META VARIANT, SIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

