USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRAINING_DATA_USAGE ( USG_ID STRING PRIMARY KEY, DATA_ID STRING, MODEL_ID STRING, USAGE_METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

