USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_LATENCY_HISTOGRAMS ( HIST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, BUCKETS VARIANT ); -- @24 @31 @56

