USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_BREACH_LOGS ( LOG_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SLA_ID STRING, DETAILS VARIANT, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

