USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_FINGERPRINT_INDEX ( FPRINT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FPRINT STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

