USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_FINGERPRINT_MATCHES ( MATCH_ID STRING PRIMARY KEY, FPRINT_ID STRING, MATCHED_DOC_REF STRING, SCORE NUMBER, MATCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

