USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOCATION_RUNS ( RUN_ID STRING PRIMARY KEY, PERIOD_START DATE, PERIOD_END DATE, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

