USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_COST_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, CC_ID STRING, PERIOD_START DATE, PERIOD_END DATE, AMOUNTS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

