USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_DERIVATIVE_INDEX ( DERIV_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, DERIV_TYPE STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

