USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMINISTRATIVE_ANNOUNCEMENTS ( ANN_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, LEVEL STRING, CREATED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

