USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ANNOUNCEMENT_READS ( READ_ID STRING PRIMARY KEY, ANN_ID STRING, USER_REF STRING, READ_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

