USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_VERSION_MIGRATION_JOBS ( JOB_ID STRING PRIMARY KEY, SERVICE_REF STRING, FROM_VERSION STRING, TO_VERSION STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

