USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SUPPORT_CONTACTS ( CONTACT_ID STRING PRIMARY KEY, TENANT_ID STRING, NAME STRING, CONTACT JSON, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31 @56

