USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ALERT_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, SUB_ID STRING, DELIVERY_STATUS STRING, DELIVERY_META VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

