USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_FEEDBACK ( FB_ID STRING PRIMARY KEY, MATERIAL_ID STRING, OP_REF STRING, FEEDBACK CLOB, SUBMITTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

