USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SKILL_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, PROFILE_ID STRING, SCORE NUMBER, DETAILS VARIANT, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

