USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SKILL_IMPROVEMENT_PLANS ( PLAN_ID STRING PRIMARY KEY, PROFILE_ID STRING, ACTIONS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

