USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_ACCEPTANCE ( ACCEPT_ID STRING PRIMARY KEY, SUG_ID STRING, OP_REF STRING, ACCEPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

