USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ACCESS_GRANTS ( GRANT_ID STRING PRIMARY KEY, REQ_ID STRING, GRANTED_TO STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ );

