USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_HEARTBEAT ( HB_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, STATUS STRING, LAST_PING TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

