USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KYC_PROVIDER_HEALTH ( HEALTH_ID STRING PRIMARY KEY, PROVIDER_ID STRING, METRICS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

