USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BADGE_REGISTRY ( BADGE_ID STRING PRIMARY KEY, SIGNER_ID STRING, BADGE JSON, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

