USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_REVOCATION_LOG ( REV_ID STRING PRIMARY KEY, DEVICE_ID STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REVOKED_BY STRING, NOTES CLOB );

