USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_OUTAGE_WINDOWS ( OUTAGE_ID STRING PRIMARY KEY, INTEGRATION_NAME STRING, START_AT TIMESTAMP_LTZ, END_AT TIMESTAMP_LTZ, NOTES CLOB );

