USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_DENSITY ( DENS_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, DENSITY_METRICS VARIANT, CALCULATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

