USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_PROFILE_USAGE ( USG_ID STRING PRIMARY KEY, PROFILE_ID STRING, TENANT_ID STRING, COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

