USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WATERMARK_APPLICATION_LOGS ( LOG_ID STRING PRIMARY KEY, POLICY_ID STRING, DOCUMENT_ID STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

