USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_LINEAGE_EVENTS ( EVT_ID STRING PRIMARY KEY, LINEAGE_ID STRING, EVENT_JSON VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

