USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_INDEX_RETENTION_ENFORCEMENT ( ENF_ID STRING PRIMARY KEY, POLICY_ID STRING, STATUS STRING, LAST_RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

