USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRIEVAL_CACHE_CONFIGS ( CFG_ID STRING PRIMARY KEY, NAME STRING, TTL_SECONDS INT, MAX_ITEMS NUMBER, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

