USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_BUDGET_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, ASSIGN_ID STRING, METRICS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

