USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_PROVENANCE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EVENT JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

