USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_LINEAGE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LINEAGE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

