USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.GDPR_EXPORT_MANIFESTS ( MANIFEST_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

