USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_RETENTION_CHECKS ( CHECK_ID STRING PRIMARY KEY, BUNDLE_ID STRING, POLICY_ID STRING, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

