USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_PACKET_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, STRUCTURE VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

