USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_PACKET_GENERATIONS ( GEN_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, BUNDLE_ID STRING, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), LOCATION STRING );

