USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_COMPLIANCE_CHECKS ( CHECK_ID STRING PRIMARY KEY, FEATURE_NAME STRING, CHECK_JSON VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

