USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATIONAL_RUNBOOK_VERSIONS ( VERSION_ID STRING PRIMARY KEY, RUNBOOK_NAME STRING, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

