USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_COMPLIANCE_DASHBOARDS ( DASH_ID STRING PRIMARY KEY, TENANT_ID STRING, DASH_CONFIG VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

