USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_AUDIT_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, HOLD_ID STRING, SNAPSHOT_LOC STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

