USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CERTIFICATE_REVOCATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, CERT_ID STRING, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

