USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIGNATURE_CHAIN_INDEX ( CHAIN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHAIN_JSON VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

