USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_POLICY_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, POLICY_ID STRING, RESULT VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

