USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, SIGNER_ID STRING, POLICY_ID STRING, RESULT JSON, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

