USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_RISK_REGISTER ( RISK_ID STRING PRIMARY KEY, PROVIDER_ID STRING, RISK_JSON VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

