USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_AUDIT_HOUSEKEEPING ( HK_ID STRING PRIMARY KEY, INTEGRATION_REF STRING, ACTION STRING, SCHEDULE JSON, LAST_RUN_AT TIMESTAMP_LTZ ); @31

