USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_EVENT_INGEST ( EVENT_ID STRING PRIMARY KEY, SCHEMA_ID STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

