USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_EVENT_INDEX ( IDX_ID STRING PRIMARY KEY, EVENT_ID STRING, KEY STRING, VALUE VARIANT, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

