USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USAGE_AGGREGATION_JOBS ( JOB_ID STRING PRIMARY KEY, TENANT_ID STRING, WINDOW JSON, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

