USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_PREVIEW_CACHE ( CACHE_ID STRING PRIMARY KEY, TENANT_ID STRING, PREVIEW_JSON VARIANT, EXPIRES_AT TIMESTAMP_LTZ ); @31

