USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CAPACITY_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, PROFILE_ID STRING, SERVICE_REF STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

