USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_EVENT_DLQ ( DLQ_ID STRING PRIMARY KEY, STREAM_ID STRING, PAYLOAD VARIANT, ERROR TEXT, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

