USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_THROTTLE_EVENTS ( EVT_ID STRING PRIMARY KEY, CFG_ID STRING, METRICS VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

