USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_ALERTS ( ALERT_ID STRING PRIMARY KEY, SIGNER_ID STRING, BUNDLE_ID STRING, ALERT_TYPE STRING, SEVERITY STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

