USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_REVOCATION_INDEX ( REV_ID STRING PRIMARY KEY, SESSION_ID STRING, REVOKED_AT TIMESTAMP_LTZ, REVOKED_BY STRING );

