USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_APPROVAL_ACTIONS ( ACTION_ID STRING PRIMARY KEY, INSTANCE_ID STRING, ACTOR STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), NOTES CLOB );

