USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_TEMPLATE_VERSIONS ( VERSION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, VERSION_NUMBER INT, CONTENT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

