USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FRAUD_INVESTIGATION_LOG ( LOG_ID STRING PRIMARY KEY, ALERT_ID STRING, INVESTIGATOR STRING, ACTION JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

