USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_FEEDBACK_QUEUE ( FBQ_ID STRING PRIMARY KEY, SIGNER_ID STRING, FEEDBACK CLOB, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

