USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_KEY_ROTATIONS ( ROT_ID STRING PRIMARY KEY, INTEGRATION_REF STRING, OLD_KEY_HASH STRING, NEW_KEY_HASH STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

