USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SECTION_INDEX ( SECTION_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TITLE STRING, CONTENT CLOB, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

