USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECTION_SIMILARITY_INDEX ( IDX_ID STRING PRIMARY KEY, SECTION_ID STRING, EMBEDDING VECTOR, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

