USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_AGGREGATION_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, SLA_ID STRING, SNAPSHOT JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

