USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_UTILIZATION_HISTORIES ( HIST_ID STRING PRIMARY KEY, OP_REF STRING, PERIOD_START TIMESTAMP_LTZ, PERIOD_END TIMESTAMP_LTZ, UTILIZATION_JSON VARIANT );

