USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_CONFIG_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, SETTINGS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

