USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_COMPLIANCE_SCORES ( SCORE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SCORE NUMBER, DETAILS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

