USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_METHOD_USAGE ( USAGE_ID STRING PRIMARY KEY, METHOD_ID STRING, ACCOUNT_ID STRING, USAGE_COUNT NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

