USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_ERROR_RATE_METRICS ( MET_ID STRING PRIMARY KEY, RENDERER_REF STRING, ERROR_COUNT NUMBER, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ );

