USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_LATENCY_METRICS ( MET_ID STRING PRIMARY KEY, RENDERER_REF STRING, P50 NUMBER, P95 NUMBER, P99 NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

