USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_RENDER_PREVIEW_CACHE ( PREVIEW_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PREVIEW_URL STRING, EXPIRES_AT TIMESTAMP_LTZ );

