USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ROLE_GRANT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, ROLE_NAME STRING, GRANTED_TO STRING, GRANTED_BY STRING, GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

