USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SAML_AUDIT_EVENTS ( EVENT_ID STRING PRIMARY KEY, SUBJECT STRING, ASSERTION VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

