USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OAUTH_TOKEN_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CLIENT_ID STRING, SUBJECT STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

