USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONTRACT_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, PROVIDER_ID STRING, REVIEWER STRING, RESULT JSON, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

