USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_NOTIFICATION_LOGS ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, NOTIF JSON, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

