USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_CERTIFICATIONS ( CERT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, EXPIRES_AT TIMESTAMP_LTZ, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

