USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_DISPATCH_WORKERS ( WORKER_ID STRING PRIMARY KEY, NAME STRING, STATUS STRING, LAST_HEARTBEAT TIMESTAMP_LTZ );

