USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CREDENTIAL_STORE ( CRED_ID STRING PRIMARY KEY, OP_REF STRING, CRED_META VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

