USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_CHANGE_APPROVAL_QUEUE ( Q_ID STRING PRIMARY KEY, CHANGE_JSON VARIANT, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

