USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_RESPONSE_TIME_INDEX ( IDX_ID STRING PRIMARY KEY, OP_REF STRING, AVG_MS NUMBER, P95_MS NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

