USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_RISK_SCORES ( SCORE_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, DETAILS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

