USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDERER_AUTOSCALE_EVENTS ( EVT_ID STRING PRIMARY KEY, POLICY_ID STRING, METRICS VARIANT, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

