USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_INDEX_BY_TENANT ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, AUDIT_REF STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

