USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_AUDIT_AGG_BY_DAY ( AGG_ID STRING PRIMARY KEY, TENANT_ID STRING, DAY DATE, AGG JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

