USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ENTITLEMENT_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, TENANT_ID STRING, FEATURE_NAME STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

