USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_PROCESSING_AGREEMENTS ( DPA_ID STRING PRIMARY KEY, TENANT_ID STRING, AGREEMENT CLOB, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

