USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_QUEUE ( POLL_ID STRING PRIMARY KEY, CERT_FINGERPRINT STRING, NEXT_POLL_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

