USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_ENTITLEMENT_MITIGATION_JOBS ( JOB_ID STRING PRIMARY KEY, VIOL_ID STRING, ACTIONS VARIANT, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

