USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_REVISION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REV_NUMBER INT, NOTIFIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

