USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, THREAD_ID STRING, AUTHOR STRING, BODY CLOB, POSTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

