USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_COMMENT_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, COMMENT_ID STRING, TARGET_USER STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

