USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_DOCUMENT_NOTES ( NOTE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, AUTHOR STRING, NOTE CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

