USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PERFORMANCE_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, OP_REF STRING, REVIEWER STRING, SCORE NUMBER, COMMENTS CLOB, REVIEWED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

