USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATION_TEMPLATES_V2 ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, SUBJECT STRING, BODY CLOB, LOCALE STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

