USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_NOTIFICATION_SENDS ( SEND_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TARGET_SCOPE VARIANT, STATUS STRING, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

