USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_INCIDENT_FOLLOWUPS ( FOLLOWUP_ID STRING PRIMARY KEY, INCIDENT_ID STRING, NOTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

