USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_CHANGE_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, LOG_ID STRING, APPROVER STRING, STATUS STRING DEFAULT 'PENDING', DECIDED_AT TIMESTAMP_LTZ );

