USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_INCIDENT_CORRELATION ( CORR_ID STRING PRIMARY KEY, SHIFT_ID STRING, INCIDENT_IDS ARRAY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

