USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_SERVICE_CATALOG ( CATALOG_ID STRING PRIMARY KEY, TENANT_ID STRING, SERVICES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() )

