USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_DEPRECATION_PLANS ( PLAN_ID STRING PRIMARY KEY, SERVICE_REF STRING, TIMELINE JSON, NOTES CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() )

