USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEPRECATION_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, PLAN_ID STRING, TENANT_SCOPE VARIANT, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() )

