USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPLIANCE_DOCUMENTS ( DOC_ID STRING PRIMARY KEY, PROVIDER_ID STRING, DOC_META VARIANT, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() )

