USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_ACKNOWLEDGEMENT_LOGS ( ACK_ID STRING PRIMARY KEY, ADMIN_USER STRING, ITEM_REF STRING, ACK_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

