USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_WORKFLOW_ACTIONS ( ACTION_ID STRING PRIMARY KEY, RUN_ID STRING, ACTOR STRING, ACTION JSON, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

