USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_RETRY_LOGS ( LOG_ID STRING PRIMARY KEY, QUEUE_ID STRING, ATTEMPT_NO INT, STATUS STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

