USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_CALLBACK_REGISTRY ( REG_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CALLBACK_URL STRING, META VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

