USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_PROVIDER_SLA_STATS ( STAT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, WINDOW JSON, STATS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

