USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_VERIFICATION_EVENTS ( EVENT_ID STRING PRIMARY KEY, USER_REF STRING, METHOD STRING, PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

