USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_RISK_MITIGATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, DEVICE_HASH STRING, ACTION JSON, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

