USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_ROTATION_SCHEDULES ( SCHEDULE_ID STRING PRIMARY KEY, TARGET_REF STRING, CRON_EXPR STRING, ENABLED BOOLEAN DEFAULT TRUE, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

