USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_CACHE_SNAPSHOTS ( SNAP_ID STRING PRIMARY KEY, PAYLOAD VARIANT, SNAPSHOT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

