USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RELAY_SERVICE_METRICS ( MET_ID STRING PRIMARY KEY, SERVICE_REF STRING, METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

