USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_RUN_INDEX ( RUN_ID STRING PRIMARY KEY, AGENT_REF STRING, INPUT VARIANT, OUTPUT VARIANT, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

