USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_RUN_EVENTS ( EVT_ID STRING PRIMARY KEY, RUN_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

