USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_FAILURE_DLQ ( DLQ_ID STRING PRIMARY KEY, RUN_ID STRING, ERROR CLOB, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

