USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AGENT_COMPATIBILITY_MATRIX ( MAT_ID STRING PRIMARY KEY, AGENT_REF STRING, CAPABILITIES VARIANT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

