USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_INFERENCE_TELEMETRY ( TELE_ID STRING PRIMARY KEY, MODEL_ID STRING, INPUT_META VARIANT, OUTPUT_META VARIANT, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

