USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXPORT_RECONCILIATION_STATUS ( RECON_ID STRING PRIMARY KEY, MANIFEST_ID STRING, EXPECTED_COUNT INT, UPLOADED_COUNT INT, STATUS STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

