USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SLA_TARGETS ( TARGET_ID STRING PRIMARY KEY, PROVIDER_ID STRING, METRICS VARIANT, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ ); -- @24 @31

