USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_CLIENT_REGISTRY ( CLIENT_ID STRING PRIMARY KEY, NAME STRING, OWNER_ACCOUNT STRING, META VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

