USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_USAGE_EVENTS ( EVENT_ID STRING PRIMARY KEY, CLIENT_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

