USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_INDEX_SHARDS ( SHARD_ID STRING PRIMARY KEY, INDEX_ID STRING, NODE_REF STRING, META VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
