USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VECTOR_INDEX_REPLICAS ( REPLICA_ID STRING PRIMARY KEY, SHARD_ID STRING, HOST STRING, STATUS STRING, LAST_HEARTBEAT TIMESTAMP_LTZ ); -- @31
