USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOT_MANIFESTS ( MANIFEST_ID STRING PRIMARY KEY, INDEX_ID STRING, S3_PATH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT ); -- @31
