USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_RATE_LIMIT_VIOLATIONS ( VIOLATION_ID STRING PRIMARY KEY, LIMIT_ID STRING, CLIENT_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

