USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_REGISTRY ( SCHEMA_ID STRING PRIMARY KEY, NAME STRING, MAPPING VARIANT, VERSION INT, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

