USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BLOCKCHAIN_ANCHOR_RECORDS ( ANCHOR_ID STRING PRIMARY KEY, BUNDLE_ID STRING, TX_ID STRING, CHAIN STRING, ANCHORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

