USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_INBOUND_AUDIT ( AUDIT_ID STRING PRIMARY KEY, WEBHOOK_ID STRING, RECEIVED_PAYLOAD VARIANT, VERIFIED BOOLEAN, VERIFIED_AT TIMESTAMP_LTZ ); -- @24 @31

