USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_API_RATE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, SERVICE_REF STRING, LIMIT_SPEC VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
