USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_API_RATE_USAGE ( USG_ID STRING PRIMARY KEY, LIMIT_ID STRING, WINDOW_START TIMESTAMP_LTZ, WINDOW_END TIMESTAMP_LTZ, USAGE_COUNT NUMBER ); -- @31
