USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTIPART_UPLOAD_REGISTRY ( UPLOAD_ID STRING PRIMARY KEY, OBJECT_KEY STRING, PARTS VARIANT, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
