USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MULTIPART_UPLOAD_PARTS ( PART_ID STRING PRIMARY KEY, UPLOAD_ID STRING, PART_NO INT, ETAG STRING, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
