USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIMILARITY_REQUEST_LOGS ( REQ_ID STRING PRIMARY KEY, QUERY_JSON VARIANT, RESP_JSON VARIANT, SERVED_BY STRING, SERVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

