USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANCHOR_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, ANCHOR_ID STRING, STATUS STRING, VERIFIED_AT TIMESTAMP_LTZ, DETAILS VARIANT );

