USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_AUDIT ( AUDIT_ID STRING PRIMARY KEY, QUERY_HASH STRING, TENANT_ID STRING, RESULTS_META VARIANT, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

