USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ANNOTATIONS ( ANNOT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ANNOTATOR STRING, ANNOTATION JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

