USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CONTENT_HASHES ( HASH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CONTENT_HASH STRING, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
