USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTENT_DUPLICATION_INDEX ( IDX_ID STRING PRIMARY KEY, CONTENT_HASH STRING, DOCUMENT_IDS ARRAY, FIRST_SEEN TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
