USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_USAGE ( USG_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, TENANT_ID STRING, RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
