USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROMPT_CACHE_EVICTIONS ( EVICT_ID STRING PRIMARY KEY, PROMPT_ID STRING, REASON STRING, EVICTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
