USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LLM_RATE_LIMIT_USAGE ( USG_ID STRING PRIMARY KEY, PROFILE_ID STRING, WINDOW JSON, USAGE_METRICS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
