USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_TRAINING_ENROLLMENTS ( ENROLL_ID STRING PRIMARY KEY, MAT_ID STRING, OP_REF STRING, STATUS STRING, ENROLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
