USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORensics_ARTIFACT_STORE ( ART_ID STRING PRIMARY KEY, CASE_ID STRING, ART_META VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

