USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAUSED_TENANT_REGISTRY ( REG_ID STRING PRIMARY KEY, TENANT_ID STRING, PAUSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REASON CLOB ); -- @31
