USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_CERTIFICATE_REVOCATIONS ( REV_ID STRING PRIMARY KEY, CERT_ID STRING, REVOKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), REVOKED_BY STRING ); -- @24 @31

