USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_BILLING_HOLD_QUEUE ( Q_ID STRING PRIMARY KEY, TENANT_ID STRING, REASON CLOB, ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'PENDING' ); -- @31
