USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_POLICY_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @24 @31

