USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFIER_SERVICE_LOGS ( LOG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, VERIFIER STRING, LOG_PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

