USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_DEPRECATION_QUEUE ( Q_ID STRING PRIMARY KEY, FEATURE_NAME STRING, REASON CLOB, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), STATUS STRING DEFAULT 'PENDING' ); -- @31
