USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_PARTITIONS ( PARTITION_ID STRING PRIMARY KEY, SCOPE STRING, RANGE_START TIMESTAMP_LTZ, RANGE_END TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

