USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVENT_METRICS ( METRIC_ID STRING PRIMARY KEY, EVENT_TYPE STRING, COUNT NUMBER, METADATA VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

