USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HOURLY_ACTIVITY_AGG ( AGG_ID STRING PRIMARY KEY, HOUR_SLOT TIMESTAMP_LTZ, METRICS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

