USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ALERT_DELIVERY_LOGS ( LOG_ID STRING PRIMARY KEY, PROFILE_ID STRING, ALERT_REF STRING, STATUS STRING, ATTEMPTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

