USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SYSTEM_MAINTENANCE_NOTES ( NOTE_ID STRING PRIMARY KEY, TITLE STRING, BODY CLOB, SCHEDULE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

