USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTERNAL_AUDIT_FINDINGS ( FINDING_ID STRING PRIMARY KEY, REPORT_ID STRING, SEVERITY STRING, DETAILS VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
