USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_LOGS ( LOG_ID STRING PRIMARY KEY, OP_REF STRING, SHIFT_START TIMESTAMP_LTZ, SHIFT_END TIMESTAMP_LTZ, NOTES CLOB ); @31

