USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_REQUEST_RESPONSES ( RES_ID STRING PRIMARY KEY, REQ_ID STRING, RESPONSE JSON, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); -- @31
