USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_REQUEST_REGISTRY ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, SUBJECT_REF STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

