USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VERIFICATION_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, VERIFY_ID STRING, ACTION STRING, PERFORMED_BY STRING, AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DETAILS VARIANT );

