USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_IMPACT_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, REG_ID STRING, SCOPE VARIANT, RESULT JSON, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

