USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PCI_SCOPE_REGISTRY ( SCOPE_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE_META VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

