USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_ACCESS_POLICY_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, POLICY_ID STRING, TARGET_REF STRING, RESULT JSON, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

