USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_IMAGE_STORE ( IMG_ID STRING PRIMARY KEY, BUNDLE_ID STRING, SIGNER_ID STRING, LOCATION STRING, HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

