USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AD_HOC_QUERY_REGISTRY ( QUERY_ID STRING PRIMARY KEY, NAME STRING, QUERY_TEXT CLOB, OWNER STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

