USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AD_HOC_QUERY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, QUERY_ID STRING, EXECUTED_BY STRING, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), DURATION_MS NUMBER ); @31

