USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_CENTER_MAPPING ( MAPPING_ID STRING PRIMARY KEY, TENANT_ID STRING, COST_CENTER STRING, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ ); @31

