USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COST_ALLOCATION_EVENTS ( EVENT_ID STRING PRIMARY KEY, MAPPING_ID STRING, AMOUNT NUMBER, CURRENCY STRING, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

