USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_FRAUD_FLAGS ( FLAG_ID STRING PRIMARY KEY, NOTIF_ID STRING, REASON STRING, FLAGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

