USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_ANOMALY_SCORES ( SCORE_ID STRING PRIMARY KEY, SESSION_ID STRING, SCORE NUMBER, META VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

