USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ANOMALY_ALERTS ( ALERT_ID STRING PRIMARY KEY, SCORE_ID STRING, LEVEL STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

