USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THREAT_INTEL_SCORE_HISTORY ( HIST_ID STRING PRIMARY KEY, SUBJECT_REF STRING, SCORE NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

