USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, STEPS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

