USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_EXCEPTION_REGISTRY ( EX_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, AUTHORIZED_BY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

