USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_MINIMIZATION_AUDITS ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, RESULT JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

