USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.IMMUTABLE_EVIDENCE_STORE ( EVID_ID STRING PRIMARY KEY, BUNDLE JSON, STORAGE_LOC STRING, WRITTEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

