USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_SLA_BREACH_LOGS ( LOG_ID STRING PRIMARY KEY, SLA_ID STRING, TENANT_ID STRING, DETAILS VARIANT, BREACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

