USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_METADATA ( SESSION_ID STRING PRIMARY KEY, SIGNER_ID STRING, DOCUMENT_ID STRING, METADATA VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

