USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLO_INCIDENT_REGISTRY ( INCIDENT_ID STRING PRIMARY KEY, SLO_ID STRING, DETAILS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

