USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHANGE_MANAGEMENT_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, DECISION STRING, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

