USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SCHEDULED_REPORT_REGISTRY ( REPORT_ID STRING PRIMARY KEY, NAME STRING, CRON_EXPR STRING, OWNER STRING, LAST_RUN_AT TIMESTAMP_LTZ ); @31

