USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LICENSE_KEY_REGISTRY ( KEY_ID STRING PRIMARY KEY, TENANT_ID STRING, KEY_HASH STRING, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ ); @31

