USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRIAL_ACCOUNT_REGISTRY ( TRIAL_ID STRING PRIMARY KEY, TENANT_ID STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), EXPIRES_AT TIMESTAMP_LTZ, STATUS STRING ); @31

