USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_DEVICE_FINGERPRINTS ( FP_ID STRING PRIMARY KEY, SESSION_ID STRING, DEVICE_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

