USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TRIAL_CONVERSION_EVENTS ( EVT_ID STRING PRIMARY KEY, TRIAL_ID STRING, TENANT_ID STRING, EVENT JSON, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

