USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_HEALTH_INDEX ( IDX_ID STRING PRIMARY KEY, TENANT_ID STRING, SCORE NUMBER, DETAILS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() ); @31

