USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_HEALTH_INTERVENTIONS ( INTERV_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTIONS VARIANT, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING' ); @31

