USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_QUALITY_SCORES ( SCORE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, METRICS VARIANT, SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

