USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_GEO_INDEX ( IDX_ID STRING PRIMARY KEY, SESSION_ID STRING, LAT NUMBER, LON NUMBER, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

