USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VIOLATION_RESOLUTION_LOG ( LOG_ID STRING PRIMARY KEY, VIOL_ID STRING, RESOLVED_BY STRING, RESOLUTION JSON, RESOLVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

