USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_CONTRACT_REGISTRY ( CONTRACT_ID STRING PRIMARY KEY, NAME STRING, SCHEMA JSON, OWNER STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

