USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_CERT_STORE ( CERT_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CERT_PEM CLOB, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

