USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.KEY_MANAGEMENT_EVENTS ( EVT_ID STRING PRIMARY KEY, KEY_REF STRING, EVENT JSON, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

