USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.HSM_INTEGRATION_LOGS ( LOG_ID STRING PRIMARY KEY, OPERATION STRING, PAYLOAD VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

