USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_LOG_ARCHIVAL_INDEX ( IDX_ID STRING PRIMARY KEY, ARCHIVE_REF STRING, ROW_COUNT NUMBER, ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

