USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.USER_OPTOUT_REGISTRY ( OPTOUT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CATEGORY STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

