USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SHARING_REGISTRY ( SHARE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SUBJECT_REF STRING, PERMS VARIANT, SHARED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

