USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_DATA_TRANSFERS ( TRANSFER_ID STRING PRIMARY KEY, SOURCE_REF STRING, DESTINATION_REF STRING, META VARIANT, INITIATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

