USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSS_TENANT_ACCESS_REQUESTS ( REQ_ID STRING PRIMARY KEY, REQUESTOR_TENANT STRING, TARGET_TENANT STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

