USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_SOVEREIGNTY_REGISTRY ( REG_ID STRING PRIMARY KEY, TENANT_ID STRING, REGION STRING, REQUIREMENTS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

