USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CICD_DEPLOY_REGISTRY ( DEPLOY_ID STRING PRIMARY KEY, ENVIRONMENT STRING, ARTIFACTS VARIANT, DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

