USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CICD_DEPLOY_EVENTS ( EVT_ID STRING PRIMARY KEY, DEPLOY_ID STRING, STATUS STRING, EVENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

