USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCGEN_FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, FEATURE_NAME STRING, CONFIG VARIANT, ENABLED BOOLEAN DEFAULT TRUE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

