USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_FLAG_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, FLAG_ID STRING, CHANGED_BY STRING, CHANGE JSON, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

