USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_ACCESS_APPROVALS ( APRV_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, DECISION STRING, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

