USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONSENT_HISTORY ( CH_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CONSENT_JSON VARIANT, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

