USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_RETRY_QUEUE ( Q_ID STRING PRIMARY KEY, WEBHOOK_ID STRING, PAYLOAD VARIANT, ATTEMPT_COUNT INT DEFAULT 0, NEXT_ATTEMPT_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

