USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_BIOMETRIC_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, SIGNER_ID STRING, TEMPLATE_BLOB BINARY, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

