USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_RISK_PROFILES ( PROFILE_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, RISK_LEVEL STRING, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), META VARIANT );

