USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUSPICIOUS_ACTIVITY_FLAGS ( FLAG_ID STRING PRIMARY KEY, SUBJECT_REF STRING, REASON STRING, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

