USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RISK_MITIGATION_ACTIONS ( ACTION_ID STRING PRIMARY KEY, TARGET_REF STRING, ACTION_JSON VARIANT, SCHEDULED_AT TIMESTAMP_LTZ, STATUS STRING DEFAULT 'PENDING' );

