USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_SNAPSHOT_MANIFEST ( MANIFEST_ID STRING PRIMARY KEY, SCOPE VARIANT, S3_PATH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

