USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_DISPUTE_QUEUE ( Q_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, DESCRIPTION CLOB, STATUS STRING DEFAULT 'OPEN', ENQUEUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

