USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_APPROVAL_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, INST_ID STRING, REASON CLOB, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

