USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_AUDIT_RUNS ( RUN_ID STRING PRIMARY KEY, CHECKLIST_ID STRING, OP_REF STRING, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

