USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_CERTIFICATION_AUDITS ( AUDIT_ID STRING PRIMARY KEY, CERT_ID STRING, RESULT JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

