USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_SECURITY_POLICY_EVALUATIONS ( EVAL_ID STRING PRIMARY KEY, POLICY_ID STRING, TENANT_ID STRING, RESULT JSON, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

