USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TENANT_CONFIG_OVERRIDES ( OVERRIDE_ID STRING PRIMARY KEY, TENANT_ID STRING, CONFIG JSON, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

