USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SERVICE_CAPACITY_PROFILES ( PROFILE_ID STRING PRIMARY KEY, SERVICE_REF STRING, CAPACITY JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

