USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_METRIC_EXPOSURE ( EXP_ID STRING PRIMARY KEY, TENANT_ID STRING, METRIC JSON, EXPOSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

