USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROMOTION_REDEMPTIONS ( RED_ID STRING PRIMARY KEY, PROMO_ID STRING, TENANT_ID STRING, REDEEMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

