USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_DISPUTE_OUTCOMES ( OUTCOME_ID STRING PRIMARY KEY, JOB_ID STRING, OUTCOME_JSON VARIANT, FINALIZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

