USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PARTNER_INTEGRATIONS_AUDIT ( AUDIT_ID STRING PRIMARY KEY, PARTNER_ID STRING, ACTION STRING, PAYLOAD VARIANT, ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

