USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_HOLD_ESCROW_REGISTRY ( ESCROW_ID STRING PRIMARY KEY, HOLD_ID STRING, PROVIDER STRING, REFERENCE STRING, REGISTERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

