USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VENDOR_RISK_REGISTRY ( VEND_ID STRING PRIMARY KEY, NAME STRING, RISK_PROFILE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

