USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.VENDOR_RISK_ASSESSMENTS ( ASSESS_ID STRING PRIMARY KEY, VEND_ID STRING, SCOPE VARIANT, RESULT JSON, ASSESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

