USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONTRACTS ( CONTRACT_ID STRING PRIMARY KEY, PARTNER_ID STRING, BODY CLOB, EFFECTIVE_FROM TIMESTAMP_LTZ, EFFECTIVE_TO TIMESTAMP_LTZ );

