USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_CONTRACT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, CONTRACT_ID STRING, ACTION STRING, ACTOR STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

