USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ADMIN_PRIV_ESCALATION_REQUESTS ( REQ_ID STRING PRIMARY KEY, REQUESTOR STRING, TARGET_PRIV STRING, STATUS STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

