USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_ROUTING_RULES ( RULE_ID STRING PRIMARY KEY, POLICY_ID STRING, MATCH_COND VARIANT, ROUTE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
