USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_THROTTLE_COUNTERS ( CNT_ID STRING PRIMARY KEY, PROFILE_ID STRING, WINDOW_START TIMESTAMP_LTZ, COUNT NUMBER );
