USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHECKSUM_INDEX ( CHK_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECKSUM STRING, COMPUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
