USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SUCCESS_RATES ( RATE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SUCCESS_RATE NUMBER, PERIOD JSON, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
