USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOBILE_SDK_ERROR_REPORTS ( ERR_ID STRING PRIMARY KEY, SDK_CLIENT_ID STRING, ERROR_JSON VARIANT, REPORTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
