USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_DEPRECATION_SCHEDULE ( SCHEDULE_ID STRING PRIMARY KEY, PROVIDER_ID STRING, DEPRECATION_DATE TIMESTAMP_LTZ, NOTICE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
