USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EXTERNAL_PROVIDER_RATE_LIMITS ( LIMIT_ID STRING PRIMARY KEY, PROVIDER STRING, LIMIT_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

