USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_COMPATIBILITY_TESTS ( TEST_ID STRING PRIMARY KEY, PROVIDER_ID STRING, NAME STRING, SCRIPT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
