USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.API_USAGE_ALERT_PROFILES ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, THRESHOLDS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
