USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_QUOTA_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, PROVIDER STRING, TENANT_ID STRING, QUOTA NUMBER, ALLOCATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

