USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_CHECK_CONFIGS ( CONFIG_ID STRING PRIMARY KEY, PROVIDER_ID STRING, CHECK_EXPR STRING, INTERVAL_SECONDS INT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

