USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_CHECK_HISTORY ( HISTORY_ID STRING PRIMARY KEY, CONFIG_ID STRING, STATUS STRING, DETAILS VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

