USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_FEATURE_FLAGS ( FLAG_ID STRING PRIMARY KEY, PROVIDER_ID STRING, FEATURE_NAME STRING, ENABLED BOOLEAN DEFAULT TRUE, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

