USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CROSS_DOC_REFERENCE_INDEX ( REF_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, REFERENCES ARRAY, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

