USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_SIMILARITY_INDEX ( IDX_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, EMBEDDING VECTOR, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

