USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_SIMILARITY_STORE ( SIM_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EMBEDDING VECTOR, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

