USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CLUSTER_ASSIGNMENTS ( ASSIGN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CLUSTER_ID STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

