USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_INDEX_METRICS ( MET_ID STRING PRIMARY KEY, INDEX_REF STRING, SIZE NUMBER, LAST_REFRESH TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

