USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_BIAS_AUDIT_REGISTRY ( AUDIT_ID STRING PRIMARY KEY, MODEL_ID STRING, SCOPE VARIANT, RESULT JSON, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

