USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, ACTION STRING, PAYLOAD VARIANT, AUDITED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

