USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SHARD_METADATA ( SHARD_ID STRING PRIMARY KEY, INDEX_REF STRING, NODE_REF STRING, SIZE NUMBER, LAST_FLUSH TIMESTAMP_LTZ );

