USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.QUERY_TRACING_SPANS ( SPAN_ID STRING PRIMARY KEY, TRACE_ID STRING, SPAN JSON, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

