USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AUDIT_LOG_SHARDS ( SHARD_ID STRING PRIMARY KEY, PATH STRING, ROW_COUNT NUMBER, LAST_ARCHIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

