USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.AD_HOC_REPORT_TEMPLATES ( TEMPLATE_ID STRING PRIMARY KEY, NAME STRING, QUERY_TEXT CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

