USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ORG_SETTINGS ( SETTING_ID STRING PRIMARY KEY, ORG_ID STRING, KEY_NAME STRING, VALUE VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
