USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_DEVICE_AUTH_ATTEMPTS ( ATTEMPT_ID STRING PRIMARY KEY, DEVICE_ID STRING, SIGNER_ID STRING, SUCCESS BOOLEAN, ATTEMPT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
