USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_SESSION_ACTIVITY ( ACT_ID STRING PRIMARY KEY, SESSION_ID STRING, ACTION STRING, META VARIANT, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
