USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_TIMELINE_EVENTS ( TLE_ID STRING PRIMARY KEY, SESSION_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
