USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SESSION_DEVICE_MAPPING ( MAP_ID STRING PRIMARY KEY, SESSION_ID STRING, DEVICE_ID STRING, MAPPED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
