USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_CREDENTIAL_CACHE ( CACHE_ID STRING PRIMARY KEY, CRED_REF STRING, CRED_META VARIANT, EXPIRES_AT TIMESTAMP_LTZ, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
