USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ASSIGNMENT_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, TEMPLATE_ID STRING, ASSIGNED_BY STRING, ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
