USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_AUTH_SESSIONS ( AUTH_ID STRING PRIMARY KEY, SIGNER_ID STRING, SESSION_ID STRING, AUTH_METHOD STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
