USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNER_VERIFICATION_REQUESTS ( REQ_ID STRING PRIMARY KEY, SIGNER_ID STRING, DOCUMENT_ID STRING, STATUS STRING DEFAULT 'NEW', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
