USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_COLLECTION_JOBS ( JOB_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, AMOUNT NUMBER, STATUS STRING, STARTED_AT TIMESTAMP_LTZ, ENDED_AT TIMESTAMP_LTZ );

