USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_PROVIDER_SWITCHES ( SWITCH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FROM_PROVIDER STRING, TO_PROVIDER STRING, SWITCHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
