USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_SELECTION_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, SELECTED_PROVIDER STRING, SELECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
