USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_MERKLE_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, MERKLE_ROOT STRING, INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
