USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_FINGERPRINT_INDEX ( FP_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, FINGERPRINT STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
