USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_TELEMETRY_EVENTS ( TELE_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EVENT_TYPE STRING, PAYLOAD VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
