USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TELEMETRY_ALERT_EVENTS ( EVT_ID STRING PRIMARY KEY, PROFILE_ID STRING, PAYLOAD VARIANT, RAISED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
