USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_ACTIVITY_HEATMAP ( HM_ID STRING PRIMARY KEY, TENANT_ID STRING, BUCKET JSON, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
