USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CLASSIFICATION_JOBS ( JOB_ID STRING PRIMARY KEY, MODEL_ID STRING, DOCUMENT_ID STRING, STATUS STRING DEFAULT 'PENDING', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
