USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_CURATIONS ( CURATION_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CURATOR STRING, NOTES CLOB, CURATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
