USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.COMPLIANCE_CERTIFICATION_CHECKS ( CHECK_ID STRING PRIMARY KEY, CERT_ID STRING, CHECK_NAME STRING, RESULT JSON, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
