USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_COMPLIANCE_EVENTS ( EVENT_ID STRING PRIMARY KEY, POLICY_ID STRING, TENANT_ID STRING, DETAILS VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
