USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_ENFORCEMENT_ACTIONS ( ACTION_ID STRING PRIMARY KEY, EVENT_ID STRING, ACTION JSON, EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
