USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHAIN_INDEX ( CHAIN_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, PREV_HASH STRING, NEXT_HASH STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
