USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, CLAUSE_ID STRING, REQUESTOR STRING, REQUEST_JSON VARIANT, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
