USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAUSE_CHANGE_APPROVALS ( APPROVAL_ID STRING PRIMARY KEY, REQ_ID STRING, APPROVER STRING, DECISION STRING, DECIDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
