USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LANGUAGE_MODEL_USAGE ( USAGE_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, TOKEN_COUNT NUMBER, USAGE_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
