USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_QUOTA_PROFILES ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, QUOTA_JSON VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
