USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_ACTION_ITEMS ( ITEM_ID STRING PRIMARY KEY, PIA_ID STRING, ACTION JSON, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
