USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_COST_CENTER_ALLOCATIONS ( ALLOC_ID STRING PRIMARY KEY, TENANT_ID STRING, MODEL_ID STRING, ALLOC_JSON VARIANT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
