USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MODEL_ROUTING_LOGS ( LOG_ID STRING PRIMARY KEY, INVOCATION_ID STRING, ROUTE_JSON VARIANT, ROUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
