USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.NOTIFICATION_AUDIT_TRAIL ( AUDIT_ID STRING PRIMARY KEY, NOTIF_ID STRING, STATUS STRING, LOG JSON, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
