USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECIPIENT_HISTORY ( RH_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, RECIPIENT_REF STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
