USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RECIPIENT_BEHAVIOR_PROFILES ( PROFILE_ID STRING PRIMARY KEY, SUBJECT_REF STRING, BEHAVIOR JSON, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
