USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_APPROVAL_RULES ( RULE_ID STRING PRIMARY KEY, NAME STRING, CONDITIONS VARIANT, ACTIONS VARIANT, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
