USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_APPROVAL_ACTIONS ( ACT_ID STRING PRIMARY KEY, INST_ID STRING, ACTOR STRING, ACTION STRING, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
