USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DYNAMIC_APPROVAL_ESCALATIONS ( ESC_ID STRING PRIMARY KEY, INST_ID STRING, REASON STRING, ESCALATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
