USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOC_VERSION_RETENTION ( RET_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, VERSION_ID STRING, RETAIN_UNTIL TIMESTAMP_LTZ );
-- @31
