USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_AUDIT ( AUDIT_ID STRING PRIMARY KEY, QUERY_TEXT STRING, TENANT_ID STRING, USER_REF STRING, RESULT_COUNT NUMBER, QUERY_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
