USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SEMANTIC_SEARCH_CONSENT_LOG ( LOG_ID STRING PRIMARY KEY, TENANT_ID STRING, USER_REF STRING, CONSENTED BOOLEAN, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
