USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FUZZY_MATCH_THRESHOLDS ( THRESH_ID STRING PRIMARY KEY, NAME STRING, VALUE NUMBER, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
