USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CLAIMS_MAPPING_REGISTRY ( MAP_ID STRING PRIMARY KEY, SOURCE_FIELD STRING, TARGET_FIELD STRING, TRANSFORM JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
