USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINTS ( COMPLAINT_ID STRING PRIMARY KEY, SUBJECT_REF STRING, DETAILS VARIANT, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
