USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCESS_REVIEW_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'OPEN', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
