USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PRIVACY_COMPLAINT_INVESTIGATIONS ( INVEST_ID STRING PRIMARY KEY, COMPLAINT_ID STRING, STATUS STRING DEFAULT 'OPEN', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
