USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DATA_CLASSIFICATION_PROFILES ( PROFILE_ID STRING PRIMARY KEY, TENANT_ID STRING, RULES VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
