USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ENCRYPTION_KEY_REGISTRY ( KEY_ID STRING PRIMARY KEY, TENANT_ID STRING, KEY_META VARIANT, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
