USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_CERTIFICATE_REGISTRY ( CERT_ID STRING PRIMARY KEY, DEVICE_ID STRING, CERT_META VARIANT, ISSUED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
