USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_KEY_ROTATIONS ( ROTATION_ID STRING PRIMARY KEY, TENANT_ID STRING, KEY_HASH STRING, ROTATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

