USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DEVICE_FIRMWARE_UPDATE_JOBS ( JOB_ID STRING PRIMARY KEY, FW_ID STRING, DEVICE_ID STRING, STATUS STRING DEFAULT 'PENDING', SCHEDULED_AT TIMESTAMP_LTZ );
-- @31
