USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_KEY_AUDIT ( AUDIT_ID STRING PRIMARY KEY, TENANT_ID STRING, ACTION STRING, DETAILS VARIANT, AUDIT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

