USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RATE_LIMIT_USAGE_WINDOWS ( WINDOW_ID STRING PRIMARY KEY, PROFILE_ID STRING, WINDOW_START TIMESTAMP_LTZ, COUNT NUMBER );

