USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_EXCEPTION_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, POLICY_ID STRING, JUSTIFICATION CLOB, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
