USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BILLING_ESTIMATE_CACHE ( CACHE_ID STRING PRIMARY KEY, TENANT_ID STRING, SCOPE VARIANT, ESTIMATE JSON, EXPIRES_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
