USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.BIOMETRIC_VERIFICATION_LOGS ( LOG_ID STRING PRIMARY KEY, SIGNER_ID STRING, TEMPLATE_ID STRING, RESULT STRING, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

