USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISCOUNT_CODE_REGISTRY ( CODE_ID STRING PRIMARY KEY, TENANT_ID STRING, CODE STRING, RULES VARIANT, EXPIRES_AT TIMESTAMP_LTZ );
-- @31
