USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISCOUNT_REDEMPTIONS ( RED_ID STRING PRIMARY KEY, CODE_ID STRING, TENANT_ID STRING, REDEEMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
