USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OCSP_POLL_HISTORY ( POLL_ID STRING PRIMARY KEY, CERT_ID STRING, STATUS STRING, POLLED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

