USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PAYMENT_GATEWAY_TRANSACTIONS ( TX_ID STRING PRIMARY KEY, PROVIDER_ID STRING, TENANT_ID STRING, AMOUNT NUMBER, STATUS STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
