USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CHARGEBACK_REGISTRY ( CB_ID STRING PRIMARY KEY, TX_ID STRING, TENANT_ID STRING, DETAILS VARIANT, FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
