USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_WORKFLOW_INSTANCES ( INSTANCE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, DOCUMENT_ID STRING, STATUS STRING, STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

