USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CURRENCY_RATE_UPDATE_JOBS ( JOB_ID STRING PRIMARY KEY, SOURCE STRING, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
