USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONDITIONAL_ROUTING_RULES ( RULE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, CONDITION JSON, ROUTE JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

