USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SUBSCRIBER_NOTIFICATION_PREFERENCES ( PREF_ID STRING PRIMARY KEY, SUBJECT_REF STRING, CHANNELS ARRAY, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
