USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNING_SESSION_TERMINATION_LOGS ( LOG_ID STRING PRIMARY KEY, SESSION_ID STRING, REASON STRING, TERMINATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

