USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.MOBILE_PUSH_NOTIFICATION_REGISTRY ( REG_ID STRING PRIMARY KEY, TENANT_ID STRING, CHANNEL JSON, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

