USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EMAIL_TEMPLATE_LOCALIZATION ( LOC_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, LANG STRING, BODY CLOB, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

