USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_DERIVATIVE_ARTIFACTS ( ART_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TYPE STRING, LOCATION STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

