USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ACCOUNT_FINANCIAL_CONTROL_VIOLATIONS ( VIOL_ID STRING PRIMARY KEY, CTRL_ID STRING, TENANT_ID STRING, DETAILS VARIANT, DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
