USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REPLAY_LOGS ( LOG_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, ACTIONS VARIANT, REPLAYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

