USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FORENSIC_EVIDENCE_STORE ( EVID_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, EVIDENCE_JSON VARIANT, STORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

