USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.WEBHOOK_SCHEMA_MIGRATIONS ( MIG_ID STRING PRIMARY KEY, SCHEMA_NAME STRING, FROM_VERSION INT, TO_VERSION INT, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

