USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_CHECKSUM_INDEX ( IDX_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, CHECKSUM STRING, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

