USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_INTEGRITY_CHECKS ( CHECK_ID STRING PRIMARY KEY, EVIDENCE_ID STRING, RESULT JSON, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

