USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THIRD_PARTY_ASSURANCE_DOCS ( DOC_ID STRING PRIMARY KEY, PARTNER_ID STRING, DOC_META VARIANT, UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
