USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGISTRY_CHANGE_NOTIFICATIONS ( NOTIF_ID STRING PRIMARY KEY, REGISTRY_REF STRING, CHANGE JSON, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );
-- @31
