USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PROVIDER_HEALTH_SUMMARY ( HS_ID STRING PRIMARY KEY, PROVIDER_ID STRING, SUMMARY VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

