USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_TEMPLATE_CACHE ( CACHE_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SNAPSHOT_JSON VARIANT, CACHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

