USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RENDER_ERROR_LOGS ( LOG_ID STRING PRIMARY KEY, JOB_ID STRING, ERROR_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

