USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEMPLATE_HEALTH_INDEX ( H_ID STRING PRIMARY KEY, TEMPLATE_ID STRING, SCORE NUMBER, METADATA VARIANT, EVALUATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

