USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.TEST_HARNESS_RUNS ( RUN_ID STRING PRIMARY KEY, INJ_ID STRING, STATUS STRING DEFAULT 'PENDING', STARTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

