USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CI_DEPLOY_HISTORY ( DEPLOY_ID STRING PRIMARY KEY, ENVIRONMENT STRING, STATUS STRING, TRIGGERED_BY STRING, TRIGGERED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

