USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_SHIFT_ROSTERS ( ROSTER_ID STRING PRIMARY KEY, OP_REF STRING, SHIFT_JSON VARIANT, EFFECTIVE_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

