USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ESIGN_SDK_EVENT_LOGS ( LOG_ID STRING PRIMARY KEY, SDK_NAME STRING, EVENT_JSON VARIANT, LOGGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

