USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SDK_COMPATIBILITY_MATRIX ( MATRIX_ID STRING PRIMARY KEY, SDK_NAME STRING, TARGETS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

