USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.THROTTLE_EVENTS ( EVT_ID STRING PRIMARY KEY, POLICY_ID STRING, SUBJECT_REF STRING, DETAILS VARIANT, OCCURRED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

