USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SLA_MAINTENANCE_IMPACT ( IMP_ID STRING PRIMARY KEY, WINDOW_ID STRING, SLA_IMPACT VARIANT, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

