USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTOMER_SUPPORT_COMMENTS ( COMMENT_ID STRING PRIMARY KEY, TICKET_ID STRING, AUTHOR STRING, BODY CLOB, COMMENTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

