USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INTEGRATION_CHANGE_RECONCILIATION ( RECON_ID STRING PRIMARY KEY, EVT_ID STRING, STATUS STRING DEFAULT 'PENDING', COMPLETED_AT TIMESTAMP_LTZ );

