USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.REGULATORY_NOTICE_DISPATCH ( DISPATCH_ID STRING PRIMARY KEY, JUR_ID STRING, NOTICE JSON, SENT_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

