USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_AUDIT_TRAILS ( AUDIT_ID STRING PRIMARY KEY, CONTRACT_REF STRING, ACTION JSON, ACTION_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

