USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONTRACT_DISPUTE_REGISTRY ( DISPUTE_ID STRING PRIMARY KEY, CONTRACT_REF STRING, SUBJECT_REF STRING, STATUS STRING DEFAULT 'OPEN', FILED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

