USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.LEGAL_EVIDENCE_EXPORTS ( EXPORT_ID STRING PRIMARY KEY, DOCUMENT_ID STRING, TARGET_URI STRING, REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

