USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.DISCLOSURE_ACKNOWLEDGEMENTS ( ACK_ID STRING PRIMARY KEY, DISC_ID STRING, SUBJECT_REF STRING, ACKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

