USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CONFIG_CHANGE_REQUESTS ( REQ_ID STRING PRIMARY KEY, TENANT_ID STRING, CHANGES VARIANT, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

