USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.FEATURE_GATE_AUDIT ( AUDIT_ID STRING PRIMARY KEY, FEATURE_NAME STRING, CHANGED_BY STRING, FROM_VALUE VARIANT, TO_VALUE VARIANT, CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

