USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_GUIDANCE_SNIPPETS ( SNIP_ID STRING PRIMARY KEY, TOPIC STRING, BODY CLOB, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

