USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_QUALITY_REVIEWS ( REVIEW_ID STRING PRIMARY KEY, OP_REF STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

