USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.OPERATOR_PERFORMANCE_LEADERBOARD ( LB_ID STRING PRIMARY KEY, PERIOD JSON, RANKINGS VARIANT, GENERATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

