USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTODIAN_REGISTRY ( CUST_ID STRING PRIMARY KEY, NAME STRING, CONTACT JSON, ADDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

