USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.CUSTODIAN_TRANSFER_JOBS ( JOB_ID STRING PRIMARY KEY, CUST_ID STRING, DOCUMENTS ARRAY, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

