USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.ARCHIVE_RECALL_REQUESTS ( REQ_ID STRING PRIMARY KEY, EVIDENCE_ID STRING, REQUESTOR STRING, STATUS STRING DEFAULT 'PENDING', REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

