USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.SECURITY_INCIDENT_TICKETS ( TICKET_ID STRING PRIMARY KEY, CLASS_ID STRING, SCOPE VARIANT, STATUS STRING DEFAULT 'OPEN', CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

