USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLATFORM_INCIDENT_MATRIX ( MAT_ID STRING PRIMARY KEY, INCIDENT_TYPE STRING, SEVERITY_MAP VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

