USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.PLATFORM_OPERATIONAL_RISKS ( RISK_ID STRING PRIMARY KEY, NAME STRING, MITIGATIONS VARIANT, UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

