USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.POLICY_REVIEW_SCHEDULES ( SCHED_ID STRING PRIMARY KEY, POLICY_ID STRING, NEXT_REVIEW_AT TIMESTAMP_LTZ, CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() );

