-- Evidence reconciliation table used by the reconciliation stored-proc @296
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RECONCILIATION (
  RECON_ID STRING PRIMARY KEY,
  MANIFEST_ID STRING,
  EXPECTED_ROWS NUMBER,
  ACTUAL_ROWS NUMBER,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

