-- Index snapshot manifest table (records FAISS snapshot metadata and shard locations) @63 @296
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.INDEX_SNAPSHOT_MANIFEST (
  SNAPSHOT_ID STRING PRIMARY KEY,
  INDEX_NAME STRING,
  S3_PREFIX STRING,
  SHARD_COUNT NUMBER,
  INDEX_VERSION STRING,
  CHECKSUM STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

