-- Model registry and routing tables (demo)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.MODEL_REGISTRY (
  MODEL_ID STRING PRIMARY KEY,
  MODEL_NAME STRING,
  PROVIDER STRING,
  MODEL_VERSION STRING,
  DEFAULT BOOL,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.MODEL_ROUTING_RULE (
  RULE_ID STRING PRIMARY KEY,
  MODEL_ID STRING,
  FEATURE_KEY STRING,
  PRIORITY NUMBER,
  CONDITIONS VARIANT,
  ACTIVE BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE VIEW DOCGEN.V_ACTIVE_MODEL_FOR_FEATURE AS
SELECT r.FEATURE_KEY, r.PRIORITY, m.MODEL_ID, m.MODEL_NAME, m.PROVIDER, m.MODEL_VERSION
FROM DOCGEN.MODEL_ROUTING_RULE r
JOIN DOCGEN.MODEL_REGISTRY m ON r.MODEL_ID = m.MODEL_ID
WHERE r.ACTIVE = TRUE
ORDER BY r.FEATURE_KEY, r.PRIORITY;

