Purpose: PKI-related metadata tables to record certificates, OCSP snapshots, and revocation evidence (note: actual HSM integration performed outside Snowflake). @115 @173

USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.PKI_CERTIFICATES (
  CERT_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  CERT_PEM STRING,
  ISSUER STRING,
  SUBJECT STRING,
  NOT_BEFORE TIMESTAMP_LTZ,
  NOT_AFTER TIMESTAMP_LTZ,
  FINGERPRINT STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.PKI_OCSP_STATUS (
  OCSP_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  OCSP_RESPONSE VARIANT,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.PKI_REVOCATION_LOG (
  REVOC_ID STRING PRIMARY KEY,
  CERT_ID STRING,
  REVOKED_AT TIMESTAMP_LTZ,
  REVOKED_BY STRING,
  REASON STRING
);

