-- PKI & OCSP tables for certificate lifecycle and revocation checking
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.PKI_CERTIFICATE_STORE (
    CERT_ID STRING PRIMARY KEY,
    CERT_PEM STRING,
    SUBJECT STRING,
    ISSUER STRING,
    SERIAL_NUMBER STRING,
    FINGERPRINT STRING,
    NOT_BEFORE TIMESTAMP_LTZ,
    NOT_AFTER TIMESTAMP_LTZ,
    UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.PKI_OCSP_STATUS (
    OCSP_ID STRING PRIMARY KEY,
    CERT_FINGERPRINT STRING,
    OCSP_RESPONSE VARIANT,
    STATUS STRING, -- GOOD, REVOKED, UNKNOWN
    CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

These tables persist certificate material and last-known OCSP/responder status used by signature validation and compliance investigations @68 @311.

