Purpose: Create tables to persist billing reconciliation runs and mismatches for deterministic invoice_hash checks. @21 @29

USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.BILLING_RECONCILIATION_RUN (
  RECONC_RUN_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  RUN_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
  EXPECTED_INVOICE_HASH STRING,
  ACTUAL_INVOICE_HASH STRING,
  STATUS STRING,
  NOTES STRING
);

CREATE OR REPLACE TABLE DOCGEN.BILLING_RECONCILIATION_MISMATCH (
  MISMATCH_ID STRING PRIMARY KEY,
  RECONC_RUN_ID STRING,
  BILLING_RUN_ID STRING,
  FIELD_NAME STRING,
  EXPECTED_VAL VARIANT,
  ACTUAL_VAL VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

