-- Retention policy metadata table and a scheduled retention enforcement task (demo values)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TABLE DOCGEN.RETENTION_POLICY (
  POLICY_ID STRING PRIMARY KEY,
  ENTITY_NAME STRING,
  RETENTION_DAYS NUMBER,
  ACTION STRING, -- 'Purge'|'Archive'
  ACTIVE BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO DOCGEN.RETENTION_POLICY (POLICY_ID, ENTITY_NAME, RETENTION_DAYS, ACTION, ACTIVE)
VALUES ('ret_doc_365', 'DOCUMENT_ARCHIVE', 365, 'Purge', TRUE);

CREATE OR REPLACE TASK DOCGEN.TASK_RETENTION_ENFORCEMENT
WAREHOUSE = "COMPUTE_WH"
SCHEDULE = 'USING CRON 30 4 * * * UTC'
AS
-- For demo, call purge stored-proc with retention for documents
CALL DOCGEN.PURGE_OLD_DOCUMENTS(365, TRUE);

