-- Retrieval results storage (for audit and downstream assembly) @63
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TABLE DOCGEN.RETRIEVAL_RESULTS (
  RETRIEVAL_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  DOCUMENT_ID STRING,
  SCORE FLOAT,
  RETRIEVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

