-- Domain DDL for E‑Signature module (complete, copy/paste-ready)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

-- Signers / Accounts / Templates / Requests / Events
CREATE OR REPLACE TABLE DOCGEN.ACCOUNTS (
  ACCOUNT_ID STRING PRIMARY KEY,
  ACCOUNT_NAME STRING,
  BILLING_PROFILE VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.SIGNERS (
  SIGNER_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  SIGNER_NAME STRING,
  SIGNER_EMAIL STRING,
  SIGNER_ROLE STRING,
  PREFERRED_METHOD STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.TEMPLATES (
  TEMPLATE_ID STRING PRIMARY KEY,
  ACCOUNT_ID STRING,
  TEMPLATE_NAME STRING,
  TEMPLATE_BODY STRING,
  TEMPLATE_METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_REQUESTS (
  REQUEST_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  TEMPLATE_ID STRING,
  STATUS STRING, -- DRAFT, SENT, COMPLETED, CANCELLED
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP_LTZ
);

-- Raw ingest table receives JSON lines via Snowpipe
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS_RAW (
  RAW_VARIANT VARIANT,
  FILE_NAME STRING,
  INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Normalized events table (MERGE from stream)
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  EVENT_TYPE STRING, -- VIEWED, SIGNED, REJECTED, VERIFIED
  EVENT_TS TIMESTAMP_LTZ,
  DEVICE_INFO VARIANT,
  IP_ADDR STRING,
  USER_AGENT STRING,
  PAYLOAD VARIANT,
  INSERTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Signature validation results (proof blobs / HSM outputs / cert refs)
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_VALIDATION (
  VALIDATION_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  VALIDATION_STATUS STRING, -- PENDING, SIGNED_BY_HSM, VERIFIED, FAILED
  VALIDATION_HASH STRING,
  SIGNATURE_BLOB_BASE64 STRING,
  SIGNER_CERT_FINGERPRINT STRING,
  VERIFIED_AT TIMESTAMP_LTZ,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Evidence bundle metadata persisted after assembly/zipper
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_BUNDLE (
  BUNDLE_ID STRING PRIMARY KEY,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  ARCHIVE_LOCATION STRING, -- S3 path
  BUNDLE_HASH STRING,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Evidence export manifest for S3 uploads (reconciliation)
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_EXPORT_MANIFEST (
  MANIFEST_ID STRING PRIMARY KEY,
  S3_PATH STRING,
  ROW_COUNT NUMBER,
  EXPORT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Reconciliation audit table
CREATE OR REPLACE TABLE DOCGEN.EVIDENCE_RECONCILIATION (
  RECON_ID STRING PRIMARY KEY,
  MANIFEST_ID STRING,
  EXPECTED_ROWS NUMBER,
  ACTUAL_ROWS NUMBER,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Alerts and operator notes
CREATE OR REPLACE TABLE DOCGEN.ALERTS (
  ALERT_ID STRING PRIMARY KEY,
  ALERT_TYPE STRING,
  PAYLOAD VARIANT,
  SEVERITY STRING,
  ALERT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
  RESOLVED BOOLEAN DEFAULT FALSE,
  RESOLVED_AT TIMESTAMP_LTZ
);

-- Purge audit for archival/purge operations
CREATE OR REPLACE TABLE DOCGEN.PURGE_AUDIT (
  PURGE_ID STRING PRIMARY KEY,
  ENTITY_NAME STRING,
  ROWS_PURGED NUMBER,
  CUT_OFF TIMESTAMP_LTZ,
  EXECUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Document archive table (rendered document metadata)
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ARCHIVE (
  DOCUMENT_ID STRING PRIMARY KEY,
  TEMPLATE_ID STRING,
  ASSEMBLY_RUN_ID STRING,
  DOCUMENT_URL STRING,
  DOCUMENT_HASH STRING,
  MIME_TYPE STRING,
  SIZE_BYTES NUMBER,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Assembly run (tracks assembly jobs)
CREATE OR REPLACE TABLE DOCGEN.DOCUMENT_ASSEMBLY_RUN (
  ASSEMBLY_RUN_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  TEMPLATE_ID STRING,
  STATUS STRING,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
  COMPLETED_AT TIMESTAMP_LTZ
);

-- PKI / OCSP tables (referenced by verification flows)
CREATE OR REPLACE TABLE DOCGEN.PKI_CERTIFICATE_STORE (
  CERT_ID STRING PRIMARY KEY,
  CERT_PEM STRING,
  SUBJECT STRING,
  ISSUER STRING,
  SERIAL_NUMBER STRING,
  FINGERPRINT STRING,
  NOT_BEFORE TIMESTAMP_LTZ,
  NOT_AFTER TIMESTAMP_LTZ,
  UPLOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE DOCGEN.PKI_OCSP_STATUS (
  OCSP_ID STRING PRIMARY KEY,
  CERT_FINGERPRINT STRING,
  OCSP_RESPONSE VARIANT,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes / clustering for performance (example)
CREATE OR REPLACE MATERIALIZED VIEW DOCGEN.MV_RECENT_EVENTS AS
SELECT EVENT_ID, REQUEST_ID, SIGNER_ID, EVENT_TYPE, EVENT_TS FROM DOCGEN.SIGNATURE_EVENTS WHERE EVENT_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP());

-- End of domain DDL (this DDL implements the canonical tables and patterns described in your Snowflake design artifacts). @4 @102

