-- Temporary & analytics helper tables (demo values; for dev only)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

-- temporary tables used by ingest procedures
CREATE OR REPLACE TABLE DOCGEN.TMP_EMBEDDINGS (
  DOCUMENT_ID STRING,
  SECTION_ID STRING,
  EMBEDDING VARIANT,
  PROVENANCE VARIANT,
  METADATA VARIANT
);

CREATE OR REPLACE TABLE DOCGEN.TMP_SIG_EVENT (
  EVENT_ID STRING,
  EVENT_PAYLOAD VARIANT,
  EVENT_TS TIMESTAMP_LTZ
);

-- signature analytics rollup (daily)
CREATE OR REPLACE TABLE DOCGEN.SIGNATURE_ANALYTICS (
  ANALYTICS_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  SIGNER_ID STRING,
  EVENT_COUNT NUMBER,
  FIRST_TS TIMESTAMP_LTZ,
  LAST_TS TIMESTAMP_LTZ,
  DURATION_SECONDS NUMBER,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

