USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE MASKING POLICY DOCGEN.MASK_SIGNER_EMAIL AS (val STRING) RETURNS STRING ->
CASE WHEN CURRENT_ROLE() IN ('DOCGEN_ADMIN','DOCGEN_COMPLIANCE') THEN val ELSE CONCAT('***@', SPLIT_PART(val,'@',2)) END;
ALTER TABLE DOCGEN.SIGNERS MODIFY COLUMN SIGNER_EMAIL SET MASKING POLICY DOCGEN.MASK_SIGNER_EMAIL;
-- Masking policy applied to signer email per security guidance @103 @76

