USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
-- API_INTEGRATION for OCSP
CREATE OR REPLACE API_INTEGRATION DOCGEN.OCSP_API_INTEGRATION
API_PROVIDER = AWS_API_GATEWAY
API_AWS_ROLE_ARN = '<API_AWS_ROLE_ARN_PLACEHOLDER>'
API_ALLOWED_PREFIXES = ('https://ocsp.example.com/');
-- External Function for OCSP call
CREATE OR REPLACE EXTERNAL FUNCTION DOCGEN.CALL_OCSP(cert_pem STRING)
RETURNS VARIANT
API_INTEGRATION = DOCGEN.OCSP_API_INTEGRATION
HEADERS = (('Content-Type','application/json'));
-- API_INTEGRATION & External Function patterns as per registration guidance @82 @31

