USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE API_INTEGRATION DOCGEN.FAISS_API_INTEGRATION
API_PROVIDER = AWS_API_GATEWAY
API_AWS_ROLE_ARN = '<API_AWS_ROLE_ARN_PLACEHOLDER>'
API_ALLOWED_PREFIXES = ('https://faiss.example.com/');
CREATE OR REPLACE EXTERNAL FUNCTION DOCGEN.SIMILARITY_QUERY(payload VARIANT)
RETURNS VARIANT
API_INTEGRATION = DOCGEN.FAISS_API_INTEGRATION
HEADERS = (('Content-Type','application/json'));
-- FAISS External Function template; fill gateway ARNs before register per External Function patterns @31 @316

