-- Materialized view-like helper for admin dashboards to surface top alerts and counts USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_ALERT_SUMMARY AS
SELECT ALERT_TYPE, SEVERITY, COUNT(*) AS count, MIN(ALERT_TS) AS first_seen, MAX(ALERT_TS) AS last_seen
FROM DOCGEN.ALERTS
WHERE RESOLVED = FALSE
GROUP BY ALERT_TYPE, SEVERITY
ORDER BY count DESC;
