-- Create an alert view for anomalous signature velocity (e.g., spikes from same IP or signer)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE VIEW DOCGEN.V_SIGNATURE_VELOCITY AS
SELECT SIGNER_ID, COUNT(*) AS event_count, MIN(EVENT_TS) AS first_ts, MAX(EVENT_TS) AS last_ts, MAX(EVENT_TS) - MIN(EVENT_TS) AS span
FROM DOCGEN.SIGNATURE_EVENTS
WHERE EVENT_TS >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
GROUP BY SIGNER_ID
HAVING COUNT(*) > 50; -- threshold for demo

CREATE OR REPLACE TASK DOCGEN.TASK_SIGNATURE_VELOCITY
  WAREHOUSE = "COMPUTE_WH"
  SCHEDULE = 'USING CRON */15 * * * * UTC'
AS
INSERT INTO DOCGEN.ALERTS (ALERT_ID, ALERT_TYPE, PAYLOAD, SEVERITY)
SELECT 'alert_vel_' || REPLACE(TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS') || '_' || SIGNER_ID, ' ', '_'), 'SIGNATURE_VELOCITY', OBJECT_CONSTRUCT('signer_id', SIGNER_ID, 'event_count', EVENT_COUNT), 'MEDIUM'
FROM DOCGEN.V_SIGNATURE_VELOCITY
WHERE NOT EXISTS (
  SELECT 1 FROM DOCGEN.ALERTS a WHERE a.PAYLOAD:signer_id::string = DOCGEN.V_SIGNATURE_VELOCITY.SIGNER_ID AND a.ALERT_TYPE = 'SIGNATURE_VELOCITY' AND a.RESOLVED = FALSE
);

