USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_ALERT_DETECTOR
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 */5 * * * UTC'
AS
CALL DOCGEN.DETECT_SIGNATURE_ANOMALIES();
-- Scheduled task skeleton for anomaly detectors per operational patterns @2363 @3150

