-- View summarizing provider health for admin console. @31 @24 @52
CREATE OR REPLACE VIEW DOCGEN.V_PROVIDER_HEALTH AS
SELECT PROVIDER_ID, STATUS, LAST_HEALTH_AT FROM DOCGEN.SIGNATURE_PROVIDER_STATUS;

