-- View showing unresolved alerts for SOC/Ops dashboards. @31 @24 @52
CREATE OR REPLACE VIEW DOCGEN.V_UNRESOLVED_ALERTS AS
SELECT ALERT_ID, ALERT_TYPE, ENTITY_REF, DETAILS, CREATED_AT FROM DOCGEN.SIGNATURE_ALERTS WHERE RESOLVED = FALSE;

