-- Summarize SLA metrics for admin dashboards and SLO checks. @1 @31
CREATE OR REPLACE VIEW DOCGEN.V_SLA_SUMMARY AS
SELECT METRIC_NAME, MAX(RECORDED_AT) AS last_at, COUNT(*) AS points FROM DOCGEN.SLA_METRICS GROUP BY METRIC_NAME;

