-- Aggregate view of ratecard events for billing runs to compute charges efficiently. @1 @31
CREATE OR REPLACE VIEW DOCGEN.V_RATECARD_EVENT_SUMMARY AS
SELECT ACCOUNT_ID, TEMPLATE_ID, EVENT_TYPE, COUNT(*) AS CNT FROM DOCGEN.SIGNATURE_RATECARD_EVENTS GROUP BY ACCOUNT_ID, TEMPLATE_ID, EVENT_TYPE;

