CREATE OR REPLACE VIEW DOCGEN.V_REQUEST_LIFECYCLE AS
SELECT r.REQUEST_ID, r.STATUS, ARRAY_AGG(e.EVENT_TYPE) AS EVENTS, MAX(e.EVENT_TS) AS LAST_EVENT_TS
FROM DOCGEN.SIGNATURE_REQUESTS r
LEFT JOIN DOCGEN.SIGNATURE_EVENTS e ON r.REQUEST_ID = e.REQUEST_ID
GROUP BY r.REQUEST_ID, r.STATUS;

