-- Aggregated view of provider latency for admin dashboards and routing logic. CREATE OR REPLACE VIEW DOCGEN.V_PROVIDER_LATENCY AS SELECT PROVIDER_ID, AVG((METRIC_VALUE::NUMBER)) AS AVG_LATENCY FROM DOCGEN.PROVIDER_METRICS WHERE METRIC_NAME = 'latency_ms' GROUP BY PROVIDER_ID;

