-- View to surface signers failing AML/KYC checks for compliance review. CREATE OR REPLACE VIEW DOCGEN.V_AML_FLAGGED_SIGNERS AS SELECT SIGNER_ID, CHECK_PROVIDER, RESULT, DETAILS FROM DOCGEN.AML_KYC_CHECKS WHERE RESULT != 'PASS';

