-- Admin-facing view: signer verification confidence heatmap materialized view skeleton for dashboards and admin UI. @31 @3149
CREATE OR REPLACE VIEW DOCGEN.V_SIGNER_CONFIDENCE AS
SELECT s.SIGNER_ID, s.SIGNER_NAME, COUNT(v.VERIFY_ID) AS VERIFY_COUNT,
       AVG(CASE WHEN v.RESULT = 'VERIFIED' THEN 1 ELSE 0 END) AS VERIFIED_RATE
FROM DOCGEN.SIGNERS s
LEFT JOIN DOCGEN.SIGNATURE_VERIFICATIONS v ON s.SIGNER_ID = v.SIGNER_ID
GROUP BY s.SIGNER_ID, s.SIGNER_NAME;

