-- Reconcile view to compare expected S3 manifests vs DB rows for evidence exports per acceptance tests. @28 @30
CREATE OR REPLACE VIEW DOCGEN.V_EVIDENCE_RECONCILE AS
SELECT b.BUNDLE_ID, b.BUNDLE_URL, COUNT(e.EVENT_ID) AS event_count
FROM DOCGEN.SIGNATURE_EVIDENCE_BUNDLE b
LEFT JOIN DOCGEN.SIGNATURE_EVENTS e ON b.REQUEST_ID = e.REQUEST_ID
GROUP BY b.BUNDLE_ID, b.BUNDLE_URL;

