Purpose: Admin view to show pending and recent evidence exports with reconciliation state. @70 @113
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_EVIDENCE_EXPORT_STATUS AS
SELECT m.MANIFEST_ID, m.S3_PATH, m.ROW_COUNT, m.EXPORT_TS, r.STATUS AS RECON_STATUS, r.CHECKED_AT
FROM DOCGEN.EVIDENCE_EXPORT_MANIFEST m
LEFT JOIN DOCGEN.EVIDENCE_RECONCILIATION r ON r.MANIFEST_ID = m.MANIFEST_ID
ORDER BY m.EXPORT_TS DESC;

