Purpose: operator view showing manifests, reconciliation status and alerts to help compliance reviewers and SREs trace exports as recommended in runbooks. @214 @118

-- v_evidence_reconcile_status.sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_EVIDENCE_RECONCILIATION_STATUS AS
SELECT em.MANIFEST_ID, em.S3_PATH, em.ROW_COUNT AS DECLARED, COALESCE(er.ACTUAL_ROWS,0) AS ACTUAL_ROWS, er.STATUS, er.CHECKED_AT,
(SELECT COUNT(*) FROM DOCGEN.ALERTS a WHERE a.PAYLOAD:manifest_id::STRING = em.MANIFEST_ID AND a.RESOLVED = FALSE) AS ACTIVE_ALERTS
FROM DOCGEN.EVIDENCE_EXPORT_MANIFEST em
LEFT JOIN DOCGEN.EVIDENCE_RECONCILIATION er ON er.MANIFEST_ID = em.MANIFEST_ID
ORDER BY em.EXPORT_TS DESC;

----
