-- Health view combining export and reconciliation status for operations dashboard
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_EVIDENCE_HEALTH AS
SELECT m.MANIFEST_ID, m.S3_PATH, m.ROW_COUNT, r.ACTUAL_ROWS, r.STATUS AS RECON_STATUS, CASE WHEN m.ROW_COUNT = COALESCE(r.ACTUAL_ROWS, -1) THEN 'GOOD' ELSE 'ISSUE' END AS HEALTH, GREATEST(m.EXPORT_TS, COALESCE(r.CHECKED_AT, m.EXPORT_TS)) AS LAST_CHECK
FROM DOCGEN.EVIDENCE_EXPORT_MANIFEST m
LEFT JOIN DOCGEN.EVIDENCE_RECONCILIATION r ON r.MANIFEST_ID = m.MANIFEST_ID
ORDER BY LAST_CHECK DESC;

