-- View: recent signature events for Admin UI
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE VIEW DOCGEN.V_RECENT_SIGNATURES AS
SELECT e.EVENT_TS, e.EVENT_TYPE, e.REQUEST_ID, e.SIGNER_ID, r.SIGNER_EMAIL, ra.DOCUMENT_ID
FROM DOCGEN.SIGNATURE_EVENTS e
LEFT JOIN DOCGEN.SIGNERS r ON r.SIGNER_ID = e.SIGNER_ID
LEFT JOIN DOCGEN.SIGNATURE_REQUESTS ra ON ra.REQUEST_ID = e.REQUEST_ID
WHERE e.EVENT_TS >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY e.EVENT_TS DESC
LIMIT 1000;
