-- View: signature completion KPI aggregated
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE VIEW DOCGEN.V_SIGNATURE_COMPLETION_KPI AS
SELECT
  DATE_TRUNC('hour', r.CREATED_AT) AS hour_bucket,
  COUNT(*) AS total_requests,
  SUM(CASE WHEN r.STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_requests,
  CASE WHEN COUNT(*) = 0 THEN 0 ELSE ROUND(100.0 * SUM(CASE WHEN r.STATUS = 'COMPLETED' THEN 1 ELSE 0 END) / COUNT(*), 2) END AS completion_pct
FROM DOCGEN.SIGNATURE_REQUESTS r
WHERE r.CREATED_AT >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 1 DESC;

