-- Task to aggregate SIGNATURE_EVENTS into SIGNATURE_EVENT_METRICS on schedule. @31 @24 @52
CREATE OR REPLACE TASK DOCGEN.TASK_AGG_SIGNATURE_METRICS
WAREHOUSE = WH_PROC
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
CALL DOCGEN.AGG_SIGNATURE_EVENTS();

