CREATE OR REPLACE TASK DOCGEN.TASK_RUN_FORENSICS_EXPORTS WAREHOUSE = WH_PROC SCHEDULE = 'USING CRON 0 3 * * * UTC' AS CALL DOCGEN.RUN_FORENSICS_EXPORTS(); FILENAME: sql/procs/1925_run_forensics_exports.sql
CREATE OR REPLACE PROCEDURE DOCGEN.RUN_FORENSICS_EXPORTS()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION='3.8'
HANDLER='handler'
AS
$$
# staged at @~/procedures/run_forensics_exports.py
$$;

