-- Snowflake TASK to run UPSERT_SIGNATURE_WEBHOOK on staged payloads per Snowpipe/Task pattern. @14 @31
CREATE OR REPLACE TASK DOCGEN.TASK_SIGNATURE_INGEST
  WAREHOUSE = WH_PROC
  SCHEDULE = 'USING CRON 0/1 * * * * UTC'
AS
  CALL DOCGEN.UPSERT_SIGNATURE_WEBHOOK((SELECT $1 FROM TABLE(INFER_SCHEMA(INPUT)))),;

