-- Task to run notify_pending_alerts every 10 minutes
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TASK DOCGEN.TASK_NOTIFY_ALERTS
WAREHOUSE = "COMPUTE_WH"
SCHEDULE = 'USING CRON */10 * * * * UTC'
AS
CALL DOCGEN.NOTIFY_PENDING_ALERTS(50);

