-- Task to run ingestion processing (pull from raw staged events) every minute (demo frequency)
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;

CREATE OR REPLACE TASK DOCGEN.TASK_INGEST_SIGNATURE_EVENTS
  WAREHOUSE = "COMPUTE_WH"
  SCHEDULE = 'USING CRON */1 * * * * UTC'
AS
  CALL DOCGEN.INGEST_SIGNATURE_EVENTS();

-- Task to run analytics hourly
CREATE OR REPLACE TASK DOCGEN.TASK_SIGNATURE_ANALYTICS
  WAREHOUSE = "COMPUTE_WH"
  SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
  CALL DOCGEN.RUN_SIGNATURE_ANALYTICS();

