-- scheduled refresh for entitlement cache every 5 minutes
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_UPDATE_ENTITLEMENT WAREHOUSE = "COMPUTE_WH" SCHEDULE = 'USING CRON */5 * * * * UTC'
AS CALL DOCGEN.UPDATE_ENTITLEMENT_CACHE();

