USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_PURGE_OLD_DOCUMENTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 3 * * * UTC'
AS
CALL DOCGEN.PURGE_OLD_DOCUMENTS(365, FALSE);
-- Scheduled purge task skeleton for retention enforcement @176 @62

