Purpose: scheduled task that runs RECONCILE_EVIDENCE_EXPORTS for manifests in NEW state, following the task scheduling patterns in your design docs. @35 @29

-- task_reconcile_evidence.sql
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_RECONCILE_EVIDENCE WAREHOUSE = 'COMPUTE_WH' SCHEDULE = 'USING CRON 0 4 * * * UTC'
AS
DECLARE
  rec CURSOR FOR SELECT MANIFEST_ID FROM DOCGEN.EVIDENCE_EXPORT_MANIFEST WHERE EXPORT_TS >= DATEADD('day', -2, CURRENT_TIMESTAMP());
BEGIN
  FOR r IN rec DO
    CALL DOCGEN.RECONCILE_EVIDENCE_EXPORTS(r.MANIFEST_ID);
  END FOR;
END;

----
