USE DATABASE AI_FEATURE_HUB; USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_INGEST_SIGNATURE_EVENTS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON * * * * * UTC'
AS
CALL DOCGEN.PROCESS_RAW_SIGNATURE_EVENTS(100);
-- Periodic task to process staged signature events per Snowpipe/TASK patterns @31 @36

