-- Task to send Slack summaries every 15 minutes for high severity alerts
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_NOTIFY_SLACK WAREHOUSE = "COMPUTE_WH" SCHEDULE = 'USING CRON */15 * * * * UTC'
AS CALL DOCGEN.NOTIFY_SLACK('HIGH', 50);

