-- Task to run alert dispatch every 5 minutes
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE TASK DOCGEN.TASK_ALERT_DISPATCH WAREHOUSE = "COMPUTE_WH" SCHEDULE = 'USING CRON */5 * * * * UTC'
AS CALL DOCGEN.NOTIFY_ALERTS(50);
