name: Snowflake CI
on: [push, pull_request]
jobs:
  register_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install snowflake-connector-python pytest
      - name: Register procedures
        env:
          SNOW_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_PWD: ${{ secrets.SNOW_PWD }}
          SNOW_ROLE: ${{ secrets.SNOW_ROLE }}
        run: ./register/register_all_procs.sh
      - name: Run tests
        env:
          SNOW_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_PWD: ${{ secrets.SNOW_PWD }}
          SNOW_ROLE: ${{ secrets.SNOW_ROLE }}
        run: pytest -q tests/test_signature_flow.py

