-- RBAC and masking policy examples; replace YOUR_SERVICE_ROLE
GRANT USAGE ON DATABASE AI_FEATURE_HUB TO ROLE YOUR_SERVICE_ROLE;
GRANT USAGE ON SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE YOUR_SERVICE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE YOUR_SERVICE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AI_FEATURE_HUB.DOCGEN TO ROLE YOUR_SERVICE_ROLE;

-- Masking policy template for PII (apply to SIGNER_EMAIL)
CREATE OR REPLACE MASKING POLICY DOCGEN.mask_email AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE') THEN val ELSE CONCAT(SUBSTR(val,1,1),'***@***') END;

ALTER TABLE DOCGEN.SIGNERS MODIFY COLUMN SIGNER_EMAIL SET MASKING POLICY DOCGEN.mask_email;

