-- Snowpipe example: stage JSONL signature events and auto-copy into SIGNATURE_EVENTS_RAW then stream to ingestion per Snowpipe patterns. @14 @31
CREATE OR REPLACE FILE FORMAT DOCGEN.JSONL_FORMAT TYPE = 'JSON';
CREATE OR REPLACE STAGE DOCGEN.STAGE_SIGNATURE_EVENTS URL='s3://REPLACE_BUCKET/signature_events/' FILE_FORMAT = DOCGEN.JSONL_FORMAT;
CREATE OR REPLACE PIPE DOCGEN.PIPE_SIGNATURE_EVENTS AS
  COPY INTO DOCGEN.SIGNATURE_EVENTS FROM @DOCGEN.STAGE_SIGNATURE_EVENTS ON_ERROR='CONTINUE';

