-- Convenience procedure to trigger Snowpipe ingestion from staged object names (wraps COPY INTO for manual runs) @21 @31
USE DATABASE AI_FEATURE_HUB;
USE SCHEMA DOCGEN;
CREATE OR REPLACE PROCEDURE DOCGEN.TRIGGER_PIPE_INGEST(prefix STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
COPY INTO DOCGEN.SIGNATURE_EVENTS_RAW FROM @DOCGEN.SIGNATURE_EVENTS_STAGE (FILE => ' ' || prefix) FILE_FORMAT=(FORMAT_NAME='DOCGEN.FF_JSONL') ON_ERROR='CONTINUE';
RETURN 'triggered';
$$;

