-- Example stages and pipes for embeddings and signature events (replace YOUR_BUCKET and STORAGE_INTEGRATION)
CREATE OR REPLACE FILE FORMAT AI_FEATURE_HUB.DOCGEN.JSONL_FORMAT TYPE = 'JSON' COMPRESSION = 'AUTO';

CREATE OR REPLACE STAGE AI_FEATURE_HUB.DOCGEN.EMBEDDINGS_STAGE
  URL = 's3://YOUR_BUCKET/embeddings/'
  FILE_FORMAT = AI_FEATURE_HUB.DOCGEN.JSONL_FORMAT
  STORAGE_INTEGRATION = 'YOUR_STORAGE_INTEGRATION';

CREATE OR REPLACE PIPE AI_FEATURE_HUB.DOCGEN.EMBEDDINGS_PIPE AUTO_INGEST = TRUE AS
COPY INTO DOCGEN.DOCUMENT_EMBEDDINGS FROM @AI_FEATURE_HUB.DOCGEN.EMBEDDINGS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'AI_FEATURE_HUB.DOCGEN.JSONL_FORMAT');

CREATE OR REPLACE STAGE AI_FEATURE_HUB.DOCGEN.SIGNATURE_EVENTS_STAGE
  URL = 's3://YOUR_BUCKET/signature-events/'
  FILE_FORMAT = AI_FEATURE_HUB.DOCGEN.JSONL_FORMAT
  STORAGE_INTEGRATION = 'YOUR_STORAGE_INTEGRATION';

CREATE OR REPLACE PIPE AI_FEATURE_HUB.DOCGEN.SIGNATURE_EVENTS_PIPE AUTO_INGEST = TRUE AS
COPY INTO DOCGEN.SIGNATURE_EVENTS FROM @AI_FEATURE_HUB.DOCGEN.SIGNATURE_EVENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'AI_FEATURE_HUB.DOCGEN.JSONL_FORMAT');

